import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe,expect,it } from 'vitest';
import { migrateSqlite,SqliteLedgerRepository } from '@robin/ledger';
import { activePositionReconciliationAudit,buildPersistedPortfolioSnapshot,enqueueTargetedPositionReconciliation,leaseTargetedPositionReconciliations,markOperationalPositionOpenConfirming,reconcileActivePositions } from '../apps/cli/src/active-position-reconciliation.js';
import { persistedPositionViews } from '../apps/telegram-lp-bot/src/persisted-portfolio.js';
import { robinhoodMainnet } from '@robin/core';

const wallet='0x00000000000000000000000000000000000000AA';
const token='0x0000000000000000000000000000000000000011';
const key={currency0:token,currency1:robinhoodMainnet.assets.USDG,fee:500,tickSpacing:10,hooks:'0x0000000000000000000000000000000000000000'};
function opened(){
 const dir=mkdtempSync(join(tmpdir(),'active-position-truth-')),path=join(dir,'db.sqlite');migrateSqlite(path,'infra/migrations');const repo=new SqliteLedgerRepository(path);
 for(const [id,symbol,operational] of [['335446','GME',true],['334913','AI',false],['337285','JACKET',false]] as const){repo.ensurePosition(`v4:${id}`,id,`pool-${id}`);repo.upsertV4Position({tokenId:BigInt(id),owner:wallet,poolId:`pool-${id}`,poolKey:key,currency0:key.currency0,currency1:key.currency1,fee:key.fee,tickSpacing:key.tickSpacing,hooks:key.hooks,tickLower:-100,tickUpper:100,liquidity:1n,initialAmount0:0n,initialAmount1:operational?5_000_000n:1_000_000_000n,mintHash:`0x${id.padStart(64,'0')}`,targetToken:token,fundingToken:robinhoodMainnet.assets.USDG,targetSymbol:symbol,fundingSymbol:'USDG',targetDecimals:18,fundingDecimals:6,targetIndex:0,fundingIndex:1,openIntentId:operational?'operational-gme':undefined});repo.ingestDeposit({id:`deposit-${id}`,positionId:`v4:${id}`,txHash:`0x${id.padStart(64,'0')}`,logIndex:0,amounts:{token0:0n,token1:operational?5_000_000n:1_000_000_000n},blockNumber:1n,blockTimestamp:new Date().toISOString()});}
 repo.ensurePosition('live:333525','333525','v3-pool');
 const success=(result:unknown)=>({status:'success',result}),failure=(message:string)=>({status:'failure',error:{shortMessage:message}});
 const calls=[success(wallet),success(0n),success([0n,0n,0n]),success([0n,0n]),success([2n**96n,0,0,500]),success(1_000_000_000_000_000_000_000_000_000n),success(wallet),success(10n),success([10n,0n,0n]),success([0n,0n]),success([2n**96n,0,0,500]),success(1_000_000_000_000_000_000_000_000_000n),success(wallet),success(20n),success([20n,0n,0n]),success([0n,0n]),success([2n**96n,0,0,500]),success(1_000_000_000_000_000_000_000_000_000n),failure('ERC721: owner query for nonexistent token'),failure('Invalid token ID')];
 const rpc={withClient:async(work:any)=>work({getBlockNumber:async()=>100n,multicall:async()=>calls})} as any;
 return {dir,repo,rpc,close(){repo.close();rmSync(dir,{recursive:true,force:true});}};
}
describe('active position lifecycle truth',()=>{
 it('reconciles the four production-shaped records to exactly two active positions and preserves history',async()=>{
  const f=opened();try{const before=(f.repo.db.prepare('SELECT COUNT(*) count FROM position_deposits').get() as {count:number}).count,result=await reconcileActivePositions({repo:f.repo,rpc:f.rpc,wallet,positionIds:['v4:335446','v4:334913','v4:337285','live:333525'],limit:4,nowMs:1_000,ttlMs:90_000});expect(result).toMatchObject({activePositionChecks:4,ethCallCount:20,multicallCount:1,multicallMembers:20});const audit=activePositionReconciliationAudit(f.repo,2_000);expect(audit.confirmedActiveCount).toBe(2);expect(audit.pendingReconciliationCount).toBe(0);expect(audit.positions.find(x=>x.tokenId==='335446')?.terminalReason).toBe('CLOSED_EMPTY');expect(audit.positions.find(x=>x.tokenId==='333525')?.terminalReason).toBe('BURNED');expect(audit.positions.filter(x=>x.classification==='CONFIRMED_ACTIVE_FRESH').map(x=>x.tokenId).sort()).toEqual(['334913','337285']);expect((f.repo.db.prepare('SELECT COUNT(*) count FROM position_deposits').get() as {count:number}).count).toBe(before);expect(persistedPositionViews(f.repo).find(x=>x.tokenId==='335446')).toMatchObject({source:'BOT_OPERATIONAL',terminalReason:'CLOSED_EMPTY'});expect(buildPersistedPortfolioSnapshot(f.repo,2_000).confirmedActiveCount).toBe(2);}finally{f.close();}});
 it('upserts reconciliation idempotently and keeps expired verified ownership visible while refreshing',async()=>{
  const f=opened();try{await reconcileActivePositions({repo:f.repo,rpc:f.rpc,wallet,positionIds:['v4:335446','v4:334913','v4:337285','live:333525'],nowMs:1_000,ttlMs:90_000});await reconcileActivePositions({repo:f.repo,rpc:f.rpc,wallet,positionIds:['v4:335446','v4:334913','v4:337285','live:333525'],nowMs:2_000,ttlMs:90_000});expect((f.repo.db.prepare('SELECT COUNT(*) count FROM active_position_reconciliations').get() as {count:number}).count).toBe(4);const stale=activePositionReconciliationAudit(f.repo,100_000);expect(stale.confirmedActiveCount).toBe(2);expect(stale.refreshingCount).toBe(2);expect(stale.pendingReconciliationCount).toBe(0);expect(stale.terminalizedCount).toBe(2);expect(buildPersistedPortfolioSnapshot(f.repo,100_000).confirmedActiveCount).toBe(2);}finally{f.close();}});
 it('does not terminalize a missing v4 NFT without receipt-backed burn evidence',async()=>{
  const f=opened();try{f.repo.ensurePosition('v4:999','999','pool-999');f.repo.upsertV4Position({tokenId:999n,owner:wallet,poolId:'pool-999',poolKey:key,currency0:key.currency0,currency1:key.currency1,fee:key.fee,tickSpacing:key.tickSpacing,hooks:key.hooks,tickLower:-100,tickUpper:100,liquidity:1n,initialAmount0:0n,initialAmount1:1n,mintHash:`0x${'9'.repeat(64)}`,targetToken:token,fundingToken:robinhoodMainnet.assets.USDG,targetSymbol:'MISSING',fundingSymbol:'USDG',targetDecimals:18,fundingDecimals:6,targetIndex:0,fundingIndex:1});const failure=(message:string)=>({status:'failure',error:{shortMessage:message}}),rpc={withClient:async(work:any)=>work({getBlockNumber:async()=>101n,multicall:async()=>[failure('NOT_MINTED'),failure('NOT_MINTED'),failure('unavailable'),failure('unavailable'),failure('unavailable')]})} as any;await reconcileActivePositions({repo:f.repo,rpc,wallet,positionIds:['v4:999'],nowMs:3_000,ttlMs:90_000});const item=activePositionReconciliationAudit(f.repo,3_001).positions.find(x=>x.tokenId==='999');expect(item?.classification).toBe('PENDING_NEVER_VERIFIED');expect(item?.terminalReason).toBeNull();expect(item?.reconciliation?.last_error).toBe('V4_NONEXISTENT_WITHOUT_BURN_RECEIPT');}finally{f.close();}
 });
 it('reopens a terminal stale ownership record through the normal targeted reconciliation path',async()=>{
  const f=opened();try{
   const positionId='v4:365878',tokenId='365878',owner=wallet.toLowerCase();f.repo.ensurePosition(positionId,tokenId,'pool-365878');f.repo.upsertV4Position({tokenId:BigInt(tokenId),owner:wallet,poolId:'pool-365878',poolKey:key,currency0:key.currency0,currency1:key.currency1,fee:key.fee,tickSpacing:key.tickSpacing,hooks:key.hooks,tickLower:-100,tickUpper:-50,liquidity:1n,initialAmount0:0n,initialAmount1:1n,mintHash:`0x${'6'.repeat(64)}`,targetToken:token,fundingToken:robinhoodMainnet.assets.USDG,targetSymbol:'ACTIVE',fundingSymbol:'USDG',targetDecimals:18,fundingDecimals:6,targetIndex:0,fundingIndex:1,status:'closed'});
   f.repo.db.prepare("INSERT INTO active_position_reconciliations(position_id,protocol_version,token_id,manager_address,owner_status,terminal_reason,confirmed_active,contributes_equity,checked_at_ms,fresh_until_ms,retry_count,details_json) VALUES(?,'v4',?,?, 'VERIFIED_UNOWNED','OWNERSHIP_LOST',0,0,1,1,0,'{}')").run(positionId,tokenId,'0x0000000000000000000000000000000000000001');
   expect(enqueueTargetedPositionReconciliation(f.repo,{positionId,tokenId,protocol:'v4',reason:'OPERATOR_TARGETED_RECONCILIATION',nowMs:2_000})).toBe('ENQUEUED');expect(enqueueTargetedPositionReconciliation(f.repo,{positionId,tokenId,protocol:'v4',reason:'OPERATOR_TARGETED_RECONCILIATION',nowMs:2_001})).toBe('ALREADY_PENDING');expect(leaseTargetedPositionReconciliations(f.repo,1,15_000,2_002).map(row=>row.position_id)).toEqual([positionId]);
   const success=(result:unknown)=>({status:'success',result}),rpc={withClient:async(work:any)=>work({getBlockNumber:async()=>200n,multicall:async()=>[success(owner),success(9n),success([0n,0n,0n]),success([0n,0n]),success([2n**96n,0,0,500])]})} as any;
   await reconcileActivePositions({repo:f.repo,rpc,wallet,positionIds:[positionId],nowMs:2_100,ttlMs:90_000});const row=f.repo.db.prepare('SELECT owner_status,terminal_reason,confirmed_active,contributes_equity FROM active_position_reconciliations WHERE position_id=?').get(positionId) as Record<string,unknown>,truth=activePositionReconciliationAudit(f.repo,2_101).positions.find(item=>item.positionId===positionId);expect(row).toMatchObject({owner_status:'VERIFIED_OWNED',terminal_reason:null,confirmed_active:1,contributes_equity:1});expect(truth?.classification).toBe('CONFIRMED_ACTIVE_FRESH');expect(f.repo.v4Position(tokenId)?.status).toBe('open');
  }finally{f.close();}
 });
 });
 it('creates OPEN_CONFIRMING after a confirmed operational receipt and targets only the new NFT',async()=>{
  const f=opened();try{
   const success=(result:unknown)=>({status:'success',result}),activeRpc={withClient:async(work:any)=>work({getBlockNumber:async()=>124n,multicall:async()=>[success(wallet),success(50n),success([50n,0n,0n]),success([0n,0n]),success([2n**96n,0,0,500])]})} as any;
   await reconcileActivePositions({repo:f.repo,rpc:activeRpc,wallet,positionIds:['v4:334913'],nowMs:1_000,ttlMs:90_000});
   f.repo.ensurePosition('v4:343976','343976','pool-new');f.repo.upsertV4Position({tokenId:343976n,owner:wallet,poolId:'pool-new',poolKey:key,currency0:key.currency0,currency1:key.currency1,fee:key.fee,tickSpacing:key.tickSpacing,hooks:key.hooks,tickLower:-100,tickUpper:100,liquidity:50n,initialAmount0:0n,initialAmount1:5_000_000n,mintHash:`0x${'3'.repeat(64)}`,targetToken:token,fundingToken:robinhoodMainnet.assets.USDG,targetSymbol:'NEW',fundingSymbol:'USDG',targetDecimals:18,fundingDecimals:6,targetIndex:0,fundingIndex:1,openIntentId:'intent-new',openEvidence:{lane:'operational'}});
   markOperationalPositionOpenConfirming(f.repo,{positionId:'v4:343976',tokenId:'343976',intentId:'intent-new',mintHash:`0x${'3'.repeat(64)}`,blockNumber:123n,nowMs:2_000});
   const before=activePositionReconciliationAudit(f.repo,2_001);expect(before.openConfirmingCount).toBe(1);expect(before.positions.find(x=>x.tokenId==='343976')?.classification).toBe('OPEN_CONFIRMING');expect(before.positions.find(x=>x.tokenId==='334913')?.classification).toBe('CONFIRMED_ACTIVE_FRESH');
   const leased=leaseTargetedPositionReconciliations(f.repo,16,15_000,2_001);expect(leased.map(x=>x.position_id)).toEqual(['v4:343976']);
   await reconcileActivePositions({repo:f.repo,rpc:activeRpc,wallet,positionIds:['v4:343976'],nowMs:2_100,ttlMs:90_000});
   const after=activePositionReconciliationAudit(f.repo,2_101);expect(after.positions.find(x=>x.tokenId==='343976')?.classification).toBe('CONFIRMED_ACTIVE_FRESH');expect(after.positions.find(x=>x.tokenId==='334913')?.classification).toBe('CONFIRMED_ACTIVE_FRESH');expect(persistedPositionViews(f.repo).find(x=>x.tokenId==='343976')?.source).toBe('BOT_OPERATIONAL');
  }finally{f.close();}
 });
