import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { migrateSqlite, SqliteLedgerRepository } from '@robin/ledger';
import { botManagedExposureGate, botManagedProjectedExposure } from '../apps/cli/src/bot-managed-exposure.js';

function repo(){const path=join(mkdtempSync(join(tmpdir(),'bot-exposure-')),'db.sqlite');migrateSqlite(path,'infra/migrations');return new SqliteLedgerRepository(path);}
function position(id:string,source:string,equity:number,status='open',liquidity='1'){return {positionId:id,status,lifecycle:'CONFIRMED_ACTIVE_FRESH',liquidityRaw:liquidity,source,openIntentId:source==='BOT_OPERATIONAL'?`intent-${id}`:null,accounting:{currentEquityUsd:equity}};}
function snapshot(db:SqliteLedgerRepository,positions:any[],now=1_000_000){db.db.prepare("INSERT OR REPLACE INTO portfolio_persisted_snapshot(snapshot_key,payload_json,content_hash,refreshed_at_ms,last_reconciliation_at_ms) VALUES('current',?,?,?,?)").run(JSON.stringify({positions,lastReconciliationAt:new Date(now).toISOString()}),'test',now,now);}
function open(db:SqliteLedgerRepository,id:string,amount=10,state='CLAIMED'){const intent=db.createV4LiveOpenIntent({idempotencyKey:id,owner:'0x1',poolId:`0x${'1'.repeat(64)}`,poolKey:{},amount:BigInt(amount*1e6),payload:{genericSelection:{fundingDecimals:6},fundingUsd:1}});if(state!=='PREVIEWED')db.transitionV4LiveOpenIntent(String(intent.id),state);return String(intent.id);}
function workflow(db:SqliteLedgerRepository,input:{id:string;old:string;replacement?:string;state?:string;topup?:number;reopen?:number}){db.db.prepare('INSERT INTO rebalance_lineages(id,root_position_id,original_principal_usd,original_funding_token,original_funding_symbol,protocol_version,pool_id,created_at) VALUES(?,?,?,?,?,?,?,?)').run(`lineage-${input.id}`,input.old,100,'0x1','USDG','v4','pool',new Date().toISOString());db.db.prepare('INSERT INTO rebalance_workflows(id,idempotency_key,lineage_id,old_position_id,replacement_position_id,mode,downside_pct,state,preview_json,state_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(input.id,input.id,`lineage-${input.id}`,input.old,input.replacement??null,'REBALANCE',10,input.state??'TOPUP_AUTHORIZED',JSON.stringify({plan:{requiredTopUpUsd:input.topup??0,actualReopenUsd:input.reopen??100}}),'{}',new Date().toISOString(),new Date().toISOString());}

describe('canonical bot-managed projected exposure',()=>{
 it('fails closed when the cap is absent only for live execution',()=>{const db=repo();try{snapshot(db,[]);const result=botManagedProjectedExposure(db,{incrementalActionCapitalUsd:1,nowMs:1_000_001});expect(botManagedExposureGate({result,live:true})).toBe('BOT_MANAGED_EXPOSURE_CAP_UNCONFIGURED');expect(botManagedExposureGate({result,live:false})).toBeUndefined();}finally{db.close();}});
 it('counts proven bot equity and reports external equity separately',()=>{const db=repo();try{snapshot(db,[position('bot','BOT_OPERATIONAL',40),position('manual','MANUAL_EXTERNAL',60)]);const result=botManagedProjectedExposure(db,{incrementalActionCapitalUsd:5,nowMs:1_000_001});expect(result.breakdown).toMatchObject({activeBotManagedEquityUsd:40,externalEquityUsd:60,totalWalletEquityUsd:100,projectedExposureUsd:45,includedPositionIds:['bot']});}finally{db.close();}});
 it('blocks tracked, unknown, and unavailable/stale data without assigning it to Robin',()=>{const db=repo();try{snapshot(db,[position('tracked','TRACKED',20)]);expect(botManagedProjectedExposure(db,{incrementalActionCapitalUsd:0,nowMs:1_000_001}).reason).toBe('BOT_MANAGED_EXPOSURE_SOURCE_AMBIGUOUS');snapshot(db,[position('unknown','',20)]);expect(botManagedProjectedExposure(db,{incrementalActionCapitalUsd:0,nowMs:1_000_001}).reason).toBe('BOT_MANAGED_EXPOSURE_SOURCE_AMBIGUOUS');snapshot(db,[{...position('refreshing','BOT_OPERATIONAL',20),lifecycle:'CONFIRMED_ACTIVE_REFRESHING'}]);expect(botManagedProjectedExposure(db,{incrementalActionCapitalUsd:0,nowMs:1_000_001}).reason).toBe('BOT_MANAGED_EXPOSURE_DATA_STALE');snapshot(db,[position('bot','BOT_OPERATIONAL',0)],1);expect(botManagedProjectedExposure(db,{incrementalActionCapitalUsd:0,nowMs:1_000_001}).reason).toBe('BOT_MANAGED_EXPOSURE_DATA_STALE');snapshot(db,[position('bot','BOT_OPERATIONAL',NaN)]);expect(botManagedProjectedExposure(db,{incrementalActionCapitalUsd:0,nowMs:1_000_001}).reason).toBe('BOT_MANAGED_EXPOSURE_VALUE_UNAVAILABLE');}finally{db.close();}});
 it('counts unresolved open commitments once and retains funded failed work',()=>{const db=repo();try{snapshot(db,[position('bot','BOT_OPERATIONAL',20)]);const id=open(db,'pending-open',10),failed=open(db,'funded-failure',7,'FAILED');const result=botManagedProjectedExposure(db,{incrementalActionCapitalUsd:0,nowMs:1_000_001});expect(result.breakdown.pendingOpenCommitmentUsd).toBe(17);expect(result.breakdown.includedCommitmentIds).toEqual(expect.arrayContaining([`open:${id}`,`open:${failed}`]));}finally{db.close();}});
 it('does not double-count active rebalance parents or active replacements',()=>{const db=repo();try{snapshot(db,[position('parent','BOT_OPERATIONAL',100)]);workflow(db,{id:'topup',old:'parent',topup:15,reopen:100});let result=botManagedProjectedExposure(db,{incrementalActionCapitalUsd:0,nowMs:1_000_001});expect(result.breakdown.pendingReplacementCommitmentUsd).toBe(15);db.db.prepare("UPDATE rebalance_workflows SET replacement_position_id=? WHERE id='topup'").run('replacement');snapshot(db,[position('replacement','BOT_OPERATIONAL',115)]);result=botManagedProjectedExposure(db,{incrementalActionCapitalUsd:0,nowMs:1_000_001});expect(result.breakdown.pendingReplacementCommitmentUsd).toBe(0);}finally{db.close();}});
 it('counts a closed parent replacement at committed reopen exposure and excludes closed/zero-liquidity positions',()=>{const db=repo();try{snapshot(db,[position('closed','BOT_OPERATIONAL',100,'closed','0')]);workflow(db,{id:'reopen',old:'closed',topup:10,reopen:110});const result=botManagedProjectedExposure(db,{incrementalActionCapitalUsd:0,nowMs:1_000_001});expect(result.breakdown.activeBotManagedEquityUsd).toBe(0);expect(result.breakdown.pendingReplacementCommitmentUsd).toBe(110);expect(result.breakdown.projectedExposureUsd).toBe(110);}finally{db.close();}});
 it('applies the cap independently after canonical aggregation',()=>{const db=repo();try{snapshot(db,[position('bot','BOT_OPERATIONAL',40)]);const result=botManagedProjectedExposure(db,{incrementalActionCapitalUsd:5,nowMs:1_000_001});expect(botManagedExposureGate({result,maxBotManagedExposureUsd:44,live:true})).toBe('BOT_MANAGED_EXPOSURE_CAP_EXCEEDED');expect(botManagedExposureGate({result,maxBotManagedExposureUsd:45,live:true})).toBeUndefined();}finally{db.close();}});
});
