import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { afterEach, describe, expect, it } from 'vitest';
import type { PublicClient } from 'viem';
import { adaptiveLogRead, chainProfile, classifyEthGetLogsError, FallbackRpc, protocolDeployment, robinhoodMainnet, v3PoolCreatedEvent } from '@funi/core';
import { migrateSqlite, SqliteLedgerRepository } from '@funi/ledger';
import { bscReadOnlyRuntimeStatus, probePublicRpcCapabilities } from '../apps/cli/src/multichain-runtime.js';
import { runReadOnlyWorkerOnce } from '../apps/workers/src/multichain-readonly-worker.js';

const cleanup:string[]=[];
afterEach(()=>{for(const path of cleanup.splice(0))rmSync(path,{recursive:true,force:true});});
const url='https://example.invalid',limitError=()=>Object.assign(new Error('query returned more than the provider result limit'),{code:-32005}),unsupportedError=()=>Object.assign(new Error('the method eth_getLogs is not supported'),{code:-32601}),rateError=()=>Object.assign(new Error('HTTP 429 Too Many Requests'),{status:429});
function rpc(clients:any[],chainId=56,options:Record<string,unknown>={}){return new FallbackRpc({chainId,name:`chain-${chainId}`,nativeSymbol:chainId===56?'BNB':'ETH',rpcUrls:clients.map(()=>url),assets:{}},undefined,{clients:clients as PublicClient[],...options});}
function stateClient(getLogs:(input:any)=>Promise<any[]>,reportedChainId=56){const profile=chainProfile('bsc'),deployment=protocolDeployment(56,'pancakeswap_v3'),pool='0x00000000000000000000000000000000000000aa' as const,quote=profile.quoteTokens[0]!.address,wrapped=profile.wrappedNativeAddress;return {getChainId:async()=>reportedChainId,getBytecode:async()=> '0x01',getBlockNumber:async()=>100n,getBlock:async()=>({number:100n,timestamp:1_700_000_000n,baseFeePerGas:null}),getLogs,readContract:async({address,functionName,args}:{address:string;functionName:string;args?:readonly unknown[]})=>functionName==='getPool'?args?.[2]===500?pool:'0x0000000000000000000000000000000000000000':functionName==='feeAmountTickSpacing'?10:functionName==='decimals'?address.toLowerCase()===quote.toLowerCase()?18:18:functionName==='symbol'?address.toLowerCase()===quote.toLowerCase()?'USDT':'WBNB':functionName==='name'?address.toLowerCase()===quote.toLowerCase()?'USDT':'Wrapped BNB':functionName==='factory'?deployment.contracts.factory:functionName==='WETH9'?wrapped:functionName==='deployer'?deployment.contracts.poolDeployer:functionName==='token0'?quote:functionName==='token1'?wrapped:functionName==='fee'?500:functionName==='tickSpacing'?10:functionName==='slot0'?[1n,0,0,0,0,0,true]:functionName==='liquidity'?5n:undefined};}

describe('BSC public RPC method capabilities and adaptive logs',()=>{
 it('classifies provider log failures precisely',()=>{expect(classifyEthGetLogsError(Object.assign(new Error('block range is too large'),{code:-32602}))).toBe('RANGE_TOO_LARGE');expect(classifyEthGetLogsError(limitError())).toBe('RESULT_LIMIT_EXCEEDED');expect(classifyEthGetLogsError(rateError())).toBe('RATE_LIMITED');expect(classifyEthGetLogsError(unsupportedError())).toBe('METHOD_UNSUPPORTED');expect(classifyEthGetLogsError(new Error('request timed out'))).toBe('TRANSIENT_TIMEOUT');expect(classifyEthGetLogsError(new Error('malformed response: missing result'))).toBe('MALFORMED_RESPONSE');expect(classifyEthGetLogsError(new Error('upstream exploded'))).toBe('PROVIDER_ERROR');});

 it('shrinks result-limited ranges until one block succeeds and preserves logs capability',async()=>{const ranges:Array<[bigint,bigint]>=[],client={getLogs:async({fromBlock,toBlock}:any)=>{ranges.push([fromBlock,toBlock]);if(toBlock>fromBlock)throw limitError();return [];}};const selected=rpc([client]),result=await adaptiveLogRead({rpc:selected,address:protocolDeployment(56,'pancakeswap_v3').contracts.factory!,event:v3PoolCreatedEvent,fromBlock:10n,toBlock:13n,options:{chunkSize:4n,maxRequests:16,maxRecursiveSplits:4,maxElapsedMs:1_000}});expect(result).toMatchObject({status:'success',minimumSuccessfulLogWindow:1});expect(ranges[0]).toEqual([10n,13n]);expect(ranges).toContainEqual([10n,10n]);expect(selected.capabilitySnapshot().find(item=>item.methodCapability==='logs')).toMatchObject({status:'SUPPORTED'});});

 it('rejects explicit one-block method unsupported, routes later logs to a capable provider, and retains eth_call eligibility',async()=>{let unsupportedCalls=0,healthyLogCalls=0,stateCalls=0;const first={getLogs:async()=>{unsupportedCalls++;throw unsupportedError();},readContract:async()=>{stateCalls++;return 7;}},second={getLogs:async()=>{healthyLogCalls++;return [];},readContract:async()=>8},selected=rpc([first,second]);await expect(selected.withClient(client=>client.getLogs({address:protocolDeployment(56,'pancakeswap_v3').contracts.factory!,event:v3PoolCreatedEvent,fromBlock:1n,toBlock:1n}),{method:'eth_getLogs',requiredCapabilities:['logs'],logRange:{fromBlock:1n,toBlock:1n}})).resolves.toEqual([]);expect(selected.capabilitySnapshot().find(item=>item.providerIndex===0&&item.methodCapability==='logs')).toMatchObject({status:'UNSUPPORTED',lastFailureCategory:'METHOD_UNSUPPORTED'});await selected.withClient(client=>client.getLogs({address:protocolDeployment(56,'pancakeswap_v3').contracts.factory!,event:v3PoolCreatedEvent,fromBlock:2n,toBlock:2n}),{method:'eth_getLogs',requiredCapabilities:['logs'],logRange:{fromBlock:2n,toBlock:2n}});expect(unsupportedCalls).toBe(1);expect(healthyLogCalls).toBe(2);await expect(selected.withClient(client=>client.readContract({} as any),{method:'eth_call',requiredCapabilities:['eth_call']})).resolves.toBe(7);expect(stateCalls).toBe(1);});

 it('does not poison eth_call after a broad log limit and bounds retries and rate-limit cooldown by method',async()=>{let clock=0,logCalls=0,stateCalls=0;const client={getLogs:async()=>{logCalls++;throw rateError();},readContract:async()=>{stateCalls++;return 9;}},selected=rpc([client],56,{now:()=>clock,cooldownMs:1_000});await expect(selected.withClient(value=>value.getLogs({address:protocolDeployment(56,'pancakeswap_v3').contracts.factory!,event:v3PoolCreatedEvent,fromBlock:1n,toBlock:1n}),{method:'eth_getLogs',requiredCapabilities:['logs'],logRange:{fromBlock:1n,toBlock:1n}})).rejects.toThrow('RPC_PROVIDER_FAILURE');expect(selected.capabilitySnapshot().find(item=>item.methodCapability==='logs')).toMatchObject({status:'COOLDOWN',lastFailureCategory:'RATE_LIMITED'});await expect(selected.withClient(value=>value.readContract({} as any),{method:'eth_call',requiredCapabilities:['eth_call']})).resolves.toBe(9);await expect(selected.withClient(value=>value.getLogs({} as any),{method:'eth_getLogs',requiredCapabilities:['logs'],logRange:{fromBlock:2n,toBlock:2n}})).rejects.toThrow('RPC_METHOD_PROVIDER_UNAVAILABLE:logs');expect(logCalls).toBe(1);expect(stateCalls).toBe(1);clock=1_000;});

 it('stops at hard request bounds',async()=>{let calls=0;const selected=rpc([{getLogs:async()=>{calls++;throw limitError();}}]),result=await adaptiveLogRead({rpc:selected,address:protocolDeployment(56,'pancakeswap_v3').contracts.factory!,event:v3PoolCreatedEvent,fromBlock:0n,toBlock:1_000n,options:{chunkSize:1_001n,maxRequests:5,maxRecursiveSplits:20,maxElapsedMs:10_000}});expect(result).toMatchObject({status:'blocked',failureCategory:'REQUEST_LIMIT',requestCount:5});expect(calls).toBe(5);});
});

describe('BSC read-only partial runtime and workers',()=>{
 it('probes only the actual factory/event with explicit bounds and keeps a range-limited provider eligible',async()=>{const seen:any[]=[],client=stateClient(async input=>{seen.push(input);if(input.toBlock>input.fromBlock)throw limitError();return [];}),selected=rpc([client]),providers=await probePublicRpcCapabilities({profile:chainProfile('bsc'),rpc:selected,protocol:'pancakeswap_v3',smallLogWindow:4n});expect(providers).toEqual([{providerIndex:0,stateReadEligibility:true,logEligibility:true,minimumSuccessfulLogWindow:1}]);expect(seen.length).toBeGreaterThan(2);expect(seen.every(item=>item.address.toLowerCase()===protocolDeployment(56,'pancakeswap_v3').contracts.factory!.toLowerCase()&&item.event.name==='PoolCreated'&&typeof item.fromBlock==='bigint'&&typeof item.toBlock==='bigint')).toBe(true);expect(JSON.stringify(providers)).not.toContain('https://');});

 it('keeps partial read-only available and execution false when logs are blocked',()=>{expect(bscReadOnlyRuntimeStatus({deploymentVerification:'VERIFIED',providers:[{providerIndex:0,stateReadEligibility:true,logEligibility:false,failureCategory:'METHOD_UNSUPPORTED'}]})).toEqual({runtimeState:'BSC_READ_ONLY_PARTIAL_LOG_DISCOVERY_BLOCKED',readOnlyAvailable:true,readOnlyMode:'PARTIAL',deploymentVerification:'VERIFIED',registryDiscovery:false,blocker:'BSC_LOG_DISCOVERY_PROVIDER_UNAVAILABLE',executionReady:false});});

 it('does not advance a partial registry interval and restarts at the exact range',async()=>{const dir=mkdtempSync(join(tmpdir(),'bsc-log-cursor-'));cleanup.push(dir);const path=join(dir,'runtime.sqlite'),firstRanges:Array<[bigint,bigint]>=[],secondRanges:Array<[bigint,bigint]>=[],limited=(target:Array<[bigint,bigint]>)=>async({fromBlock,toBlock}:any)=>{target.push([fromBlock,toBlock]);if(toBlock>fromBlock)throw limitError();if(fromBlock===1n)throw new Error('upstream failed');return [];},env={BSC_ENABLED:'true',BSC_RPC_URLS:url};const first=await runReadOnlyWorkerOnce({chain:'bsc',role:'registry',env,databasePath:path,rpc:rpc([stateClient(limited(firstRanges))]),maxRetries:1});expect(first).toMatchObject({status:'IDLE',blockerReason:'BSC_LOG_DISCOVERY_PROVIDER_UNAVAILABLE',signerConstructed:false,nonceReserved:false,mainnetTransactionsSent:0});let repo=new SqliteLedgerRepository(path);try{expect(repo.chainRegistryCursor(56,'pancakeswap_v3','deployment_verification')).toBeUndefined();expect(repo.db.prepare('SELECT COUNT(*) count FROM chain_transaction_journal').get()).toEqual({count:0});}finally{repo.close();}const second=await runReadOnlyWorkerOnce({chain:'bsc',role:'registry',env,databasePath:path,rpc:rpc([stateClient(limited(secondRanges))]),maxRetries:1});expect(second.status).toBe('IDLE');expect(firstRanges[0]).toEqual([0n,85n]);expect(secondRanges[0]).toEqual(firstRanges[0]);repo=new SqliteLedgerRepository(path);try{expect(repo.chainRegistryCursor(56,'pancakeswap_v3','deployment_verification')).toBeUndefined();}finally{repo.close();}});

 it('lets state-cache refresh a known BSC pool through a state-only provider',async()=>{const dir=mkdtempSync(join(tmpdir(),'bsc-state-only-'));cleanup.push(dir);const path=join(dir,'runtime.sqlite');migrateSqlite(path,'infra/migrations');const repo=new SqliteLedgerRepository(path),deployment=protocolDeployment(56,'pancakeswap_v3'),profile=chainProfile('bsc');try{repo.upsertChainPool({chainId:56,protocol:'pancakeswap_v3',poolAddress:'0x00000000000000000000000000000000000000aa',token0:profile.quoteTokens[0]!.address,token1:profile.wrappedNativeAddress,fee:500,tickSpacing:10,state:{seeded:true},validationStatus:'VERIFIED_READ_ONLY'});}finally{repo.close();}let logCalls=0;const result=await runReadOnlyWorkerOnce({chain:'bsc',role:'state-cache',env:{BSC_ENABLED:'true',BSC_RPC_URLS:url},databasePath:path,rpc:rpc([stateClient(async()=>{logCalls++;throw unsupportedError();})]),maxRetries:1});expect(result).toMatchObject({status:'COMPLETED',poolsRefreshed:1,signerConstructed:false,nonceReserved:false,mainnetTransactionsSent:0});expect(logCalls).toBe(0);});

 it('rejects wrong chain and isolates BSC capability failures from Ethereum and FUNI pools',async()=>{const wrong=rpc([{readContract:async()=>1}],56);wrong.markProviderCapability(0,'chain_identity','WRONG_CHAIN','PROVIDER_ERROR');await expect(wrong.withClient(client=>client.readContract({} as any),{method:'eth_call',requiredCapabilities:['eth_call']})).rejects.toThrow('RPC_METHOD_PROVIDER_UNAVAILABLE:eth_call');const bsc=rpc([{getLogs:async()=>{throw unsupportedError();}}]),ethereum=rpc([{getLogs:async()=>[]}],1),funi=new FallbackRpc(robinhoodMainnet,undefined,{clients:[{getLogs:async()=>[]} as any]});await expect(bsc.withClient(client=>client.getLogs({} as any),{method:'eth_getLogs',requiredCapabilities:['logs'],logRange:{fromBlock:1n,toBlock:1n}})).rejects.toThrow();expect(ethereum.capabilitySnapshot().find(item=>item.methodCapability==='logs')?.status).toBe('UNKNOWN');expect(funi.capabilitySnapshot().find(item=>item.methodCapability==='logs')?.status).toBe('UNKNOWN');});
});
