import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it, vi } from 'vitest';
import { keccak256, type Hex } from 'viem';
import { migrateSqlite, SqliteLedgerRepository } from '@funi/ledger';
import { broadcastDurableTransaction, DurableTransactionReconciliationPendingError, type DurablePreparedTransaction } from '../apps/cli/src/transaction-boundary.js';

const wallet='0x0000000000000000000000000000000000000002' as const;
const target='0x0000000000000000000000000000000000000003' as const;
const busy=Object.assign(new Error('database is locked'),{code:'SQLITE_BUSY'});
const missing=()=>{throw new Error('transaction not found');};

function fixture(){const dir=mkdtempSync(join(tmpdir(),'durable-boundary-')),path=join(dir,'db.sqlite');migrateSqlite(path,'infra/migrations');const repo=new SqliteLedgerRepository(path),id='intent';repo.persistIntent(id,'durable-boundary',{});return {repo,id,path,close(){repo.close();rmSync(dir,{recursive:true,force:true});}};}
function journal(f:ReturnType<typeof fixture>){return {load:()=>{const row=f.repo.db.prepare('SELECT payload_json FROM transaction_intents WHERE id=?').get(f.id) as {payload_json:string};return (JSON.parse(row.payload_json,(key,value)=>/^(gas|gasPrice|value)$/.test(key)&&typeof value==='string'?BigInt(value):value) as {prepared?:DurablePreparedTransaction}).prepared;},persistPrepared:(prepared:DurablePreparedTransaction)=>{f.repo.db.transaction(()=>{f.repo.db.prepare("UPDATE transaction_intents SET state='PREPARED',payload_json=? WHERE id=?").run(JSON.stringify({prepared},(_,value)=>typeof value==='bigint'?value.toString():value),f.id);})();},markSubmitted:()=>{f.repo.db.prepare("UPDATE transaction_intents SET state='SUBMITTED' WHERE id=?").run(f.id);}};}
function rpc(client:Record<string,unknown>){return {config:{chainId:4663,rpcUrls:['http://127.0.0.1']},clients:[client],withClient:async(fn:(value:any)=>unknown)=>fn(client)} as any;}
function client(input:Record<string,unknown>={}){return {getGasPrice:async()=>1n,getTransactionCount:async()=>9,getTransactionReceipt:missing,getTransaction:missing,...input};}
function walletClient(serialized:Hex,onSend:()=>void,hash=keccak256(serialized)){return {account:{signTransaction:async()=>serialized},signTransaction:async()=>serialized,syntheticSerializedTransactionFixture:true,request:async()=>{onSend();return hash;}} as any;}
function execute(f:ReturnType<typeof fixture>,clientValue:Record<string,unknown>,walletValue:any,hooks?:Record<string,unknown>){return broadcastDurableTransaction({repo:f.repo,rpc:rpc(clientValue),walletClient:walletValue,wallet,workflowId:f.id,semanticStage:'OPEN_MINT',to:target,data:'0x12',estimatedGas:100_000n,journal:journal(f),hooks} as any);}
function chainJournal(f:ReturnType<typeof fixture>,workflowId='chain-workflow',semanticStage='CLOSE_BATCH'){
 const id=`${workflowId}:${semanticStage}:0`;
 const row=()=>f.repo.db.prepare('SELECT * FROM chain_transaction_journal WHERE chain_id=4663 AND journal_id=?').get(id) as Record<string,unknown>|undefined;
 return {id,row,journal:{load:()=>{const current=row();if(!current||!['PREPARED','SUBMITTED'].includes(String(current.status)))return;const raw=JSON.parse(String(current.provider_evidence_json)).prepared;return {...raw,request:{...raw.request,value:BigInt(raw.request.value),gas:BigInt(raw.request.gas),gasPrice:BigInt(raw.request.gasPrice)}};},persistPrepared:(prepared:DurablePreparedTransaction)=>{f.repo.persistChainPreparedTransaction({chainId:4663,chainKey:'robinhood',protocol:'uniswap_v4',journalId:id,wallet,workflowIdentity:workflowId,semanticStage,attempt:0,nonce:prepared.request.nonce,transactionType:semanticStage,expectedHash:prepared.expectedHash,to:prepared.request.to,requestFingerprint:prepared.requestFingerprint,feeModel:'legacy'});f.repo.db.prepare('UPDATE chain_transaction_journal SET provider_evidence_json=? WHERE chain_id=4663 AND journal_id=?').run(JSON.stringify({prepared},(_,value)=>typeof value==='bigint'?value.toString():value),id);},markSubmitted:()=>{const current=row();if(current?.status==='PREPARED')f.repo.transitionChainTransaction({chainId:4663,journalId:id,from:'PREPARED',to:'SUBMITTED'});}}};
}

describe('journal-before-broadcast boundary',()=>{
 it('retries a transient nonce-admission lock before signing and completes one durable transition',async()=>{const f=fixture(),serialized='0x111213' as Hex;let attempts=0,signs=0,sends=0;const original=f.repo.db.prepare.bind(f.repo.db),prepare=vi.spyOn(f.repo.db,'prepare').mockImplementation(((sql:string)=>{const statement=original(sql);if(!sql.startsWith('INSERT INTO nonce_mutex'))return statement;return {...statement,run:(...args:any[])=>{attempts++;if(attempts<3)throw busy;return statement.run(...args);}};}) as any);try{await execute(f,client(),{account:{signTransaction:async()=>{signs++;return serialized;}},signTransaction:async()=>{signs++;return serialized;},syntheticSerializedTransactionFixture:true,request:async()=>{sends++;return keccak256(serialized);}} as any);expect({attempts,signs,sends}).toEqual({attempts:3,signs:1,sends:1});expect(f.repo.db.prepare('SELECT state FROM transaction_intents WHERE id=?').get(f.id)).toEqual({state:'SUBMITTED'});expect(f.repo.db.prepare('SELECT COUNT(*) count FROM nonce_mutex').get()).toEqual({count:0});}finally{prepare.mockRestore();f.close();}});
 it('exhausts nonce-admission SQLITE_BUSY before signing, with no journal or broadcast',async()=>{const f=fixture(),original=f.repo.db.prepare.bind(f.repo.db),prepare=vi.spyOn(f.repo.db,'prepare').mockImplementation(((sql:string)=>{const statement=original(sql);return sql.startsWith('INSERT INTO nonce_mutex')?{...statement,run:()=>{throw busy;}}:statement;}) as any);let signs=0,sends=0;try{await expect(execute(f,client(),{account:{signTransaction:async()=>{signs++;return '0x141516';}},signTransaction:async()=>{signs++;return '0x141516';},syntheticSerializedTransactionFixture:true,request:async()=>{sends++;return keccak256('0x141516');}} as any)).rejects.toThrow('SQLITE_TRANSIENT_RETRY_EXHAUSTED:chain_nonce_mutex_acquire:SQLITE_BUSY');expect({signs,sends}).toEqual({signs:0,sends:0});expect(f.repo.db.prepare('SELECT state FROM transaction_intents WHERE id=?').get(f.id)).toEqual({state:'simulated'});expect(f.repo.db.prepare('SELECT COUNT(*) count FROM nonce_mutex').get()).toEqual({count:0});}finally{prepare.mockRestore();f.close();}});
 it('commits PREPARED before the outbound provider call',async()=>{const f=fixture(),serialized='0x010203' as Hex;let sends=0;try{await execute(f,client(),walletClient(serialized,()=>{sends++;expect(f.repo.db.prepare('SELECT state FROM transaction_intents WHERE id=?').get(f.id)).toEqual({state:'PREPARED'});}));expect(sends).toBe(1);expect(f.repo.db.prepare('SELECT state FROM transaction_intents WHERE id=?').get(f.id)).toEqual({state:'SUBMITTED'});}finally{f.close();}});
 it('sends zero transactions when the PREPARED commit fails',async()=>{const f=fixture(),serialized='0x020304' as Hex;let sends=0;const broken={...journal(f),persistPrepared:()=>f.repo.db.transaction(()=>{f.repo.db.prepare("UPDATE transaction_intents SET state='PREPARED' WHERE id=?").run(f.id);throw new Error('SQLITE_INJECTED_COMMIT_FAILURE');})()};try{await expect(broadcastDurableTransaction({repo:f.repo,rpc:rpc(client()),walletClient:walletClient(serialized,()=>{sends++;}),wallet,workflowId:f.id,semanticStage:'OPEN_MINT',to:target,data:'0x12',estimatedGas:100_000n,journal:broken})).rejects.toThrow('SQLITE_INJECTED_COMMIT_FAILURE');expect(sends).toBe(0);expect(f.repo.db.prepare('SELECT state FROM transaction_intents WHERE id=?').get(f.id)).toEqual({state:'simulated'});expect(f.repo.db.prepare('SELECT COUNT(*) count FROM nonce_mutex').get()).toEqual({count:0});}finally{f.close();}});
 it('returns reconciliation pending when provider acceptance is ambiguous and never rebroadcasts on confirm replay',async()=>{const f=fixture(),serialized='0x020305' as Hex,hash=keccak256(serialized);let signs=0,sends=0;const ambiguous={account:{signTransaction:async()=>serialized},signTransaction:async()=>{signs++;return serialized;},syntheticSerializedTransactionFixture:true,request:async()=>{sends++;throw new Error('transport disconnected after write');}} as any;try{await expect(execute(f,client(),ambiguous)).rejects.toMatchObject({name:'DurableTransactionReconciliationPendingError',message:'DURABLE_TRANSACTION_RECONCILIATION_PENDING',expectedHash:hash,nonce:9});expect({signs,sends}).toEqual({signs:1,sends:1});expect(f.repo.db.prepare('SELECT state FROM transaction_intents WHERE id=?').get(f.id)).toEqual({state:'PREPARED'});await expect(execute(f,client(),walletClient(serialized,()=>{sends++;},hash))).rejects.toBeInstanceOf(DurableTransactionReconciliationPendingError);expect({signs,sends}).toEqual({signs:1,sends:1});expect(f.repo.db.prepare('SELECT state FROM transaction_intents WHERE id=?').get(f.id)).toEqual({state:'PREPARED'});}finally{f.close();}});
 it('keeps an exact prepared hash reconciliation-pending after a crash while its nonce remains available',async()=>{const f=fixture(),serialized='0x030405' as Hex,hash=keccak256(serialized);let sends=0;try{await expect(execute(f,client(),walletClient(serialized,()=>{sends++;},hash),{afterPreparedCommit:()=>{throw new Error('CRASH_AFTER_PREPARED');}})).rejects.toThrow('CRASH_AFTER_PREPARED');expect(sends).toBe(0);expect(f.repo.db.prepare('SELECT state FROM transaction_intents WHERE id=?').get(f.id)).toEqual({state:'PREPARED'});await expect(execute(f,client(),walletClient(serialized,()=>{sends++;},hash))).rejects.toMatchObject({name:'DurableTransactionReconciliationPendingError',message:'DURABLE_TRANSACTION_RECONCILIATION_PENDING',expectedHash:hash,nonce:9,evidence:'EXACT_HASH_ABSENT_NONCE_AVAILABLE'});expect(sends).toBe(0);expect(f.repo.db.prepare('SELECT state FROM transaction_intents WHERE id=?').get(f.id)).toEqual({state:'PREPARED'});}finally{f.close();}});
 it('keeps exact evidence after provider acceptance and never sends twice',async()=>{const f=fixture(),serialized='0x040506' as Hex,hash=keccak256(serialized);let sends=0,accepted=false;const c=client({getTransaction:async()=>accepted?{hash,nonce:9,from:wallet,blockNumber:null}:missing()});try{await expect(execute(f,c,walletClient(serialized,()=>{sends++;accepted=true;},hash),{afterProviderAcceptance:()=>{throw new Error('CRASH_AFTER_ACCEPTANCE');}})).rejects.toThrow('CRASH_AFTER_ACCEPTANCE');expect(f.repo.db.prepare('SELECT state FROM transaction_intents WHERE id=?').get(f.id)).toEqual({state:'SUBMITTED'});await expect(execute(f,c,walletClient(serialized,()=>{sends++;},hash))).rejects.toBeInstanceOf(DurableTransactionReconciliationPendingError);expect(sends).toBe(1);expect(f.repo.db.prepare('SELECT state FROM transaction_intents WHERE id=?').get(f.id)).toEqual({state:'SUBMITTED'});}finally{f.close();}});
 it('probes immediately after a successful send and terminalizes an already-visible exact receipt',async()=>{const f=fixture(),serialized='0x151617' as Hex,hash=keccak256(serialized),chain=chainJournal(f,'post-send-receipt'),receipt={status:'success',transactionHash:hash,blockNumber:12n,gasUsed:52n,effectiveGasPrice:2n};let accepted=false,sends=0,receiptCalls=0;const c=client({getTransactionReceipt:async()=>{receiptCalls++;return accepted?receipt:missing();}});try{const result=await broadcastDurableTransaction({repo:f.repo,rpc:rpc(c),walletClient:walletClient(serialized,()=>{accepted=true;sends++;},hash),wallet,workflowId:'post-send-receipt',semanticStage:'CLOSE_BATCH',to:target,data:'0x12',estimatedGas:100_000n,journal:chain.journal});expect(result).toMatchObject({hash,receipt});expect({sends,receiptCalls}).toEqual({sends:1,receiptCalls:1});expect(chain.row()).toMatchObject({status:'CONFIRMED'});}finally{f.close();}});
 it('bounds propagation probing and converges when the exact receipt appears on the third check',async()=>{const f=fixture(),serialized='0x242526' as Hex,hash=keccak256(serialized),chain=chainJournal(f,'bounded-probe'),receipt={status:'success',transactionHash:hash,blockNumber:15n,gasUsed:55n,effectiveGasPrice:2n};let accepted=false,sends=0,receiptCalls=0;const c=client({getTransactionReceipt:async()=>{receiptCalls++;if(accepted&&receiptCalls===3)return receipt;return missing();}});try{const result=await broadcastDurableTransaction({repo:f.repo,rpc:rpc(c),walletClient:walletClient(serialized,()=>{accepted=true;sends++;},hash),wallet,workflowId:'bounded-probe',semanticStage:'CLOSE_BATCH',to:target,data:'0x12',estimatedGas:100_000n,journal:chain.journal});expect(result).toMatchObject({hash,receipt});expect({sends,receiptCalls}).toEqual({sends:1,receiptCalls:3});expect(chain.row()).toMatchObject({status:'CONFIRMED'});}finally{f.close();}});
 it('recovers an accepted exact receipt when send throws an ambiguous timeout',async()=>{const f=fixture(),serialized='0x18191a' as Hex,hash=keccak256(serialized),chain=chainJournal(f,'timeout-landed'),receipt={status:'success',transactionHash:hash,blockNumber:13n,gasUsed:53n,effectiveGasPrice:2n};let accepted=false,sends=0;const c=client({getTransactionReceipt:async()=>accepted?receipt:missing()}),sender={...walletClient(serialized,()=>{},hash),request:async()=>{accepted=true;sends++;throw new Error('timeout after write');}} as any;try{const result=await broadcastDurableTransaction({repo:f.repo,rpc:rpc(c),walletClient:sender,wallet,workflowId:'timeout-landed',semanticStage:'CLOSE_BATCH',to:target,data:'0x12',estimatedGas:100_000n,journal:chain.journal});expect(result).toMatchObject({hash,receipt});expect(sends).toBe(1);expect(chain.row()).toMatchObject({status:'CONFIRMED'});}finally{f.close();}});
 it('retries a real SQLITE_BUSY on SUBMITTED persistence and never sends twice',async()=>{const f=fixture(),serialized='0x1b1c1d' as Hex,hash=keccak256(serialized),base=journal(f),locker=new SqliteLedgerRepository(f.path,{busyTimeoutMs:1});let sends=0,attempts=0;f.repo.db.pragma('busy_timeout = 1');const durable={...base,markSubmitted:()=>{attempts++;try{base.markSubmitted();}catch(error){if(attempts===1)locker.db.exec('ROLLBACK');throw error;}}};try{await broadcastDurableTransaction({repo:f.repo,rpc:rpc(client()),walletClient:walletClient(serialized,()=>{locker.db.exec('BEGIN IMMEDIATE');sends++;},hash),wallet,workflowId:f.id,semanticStage:'OPEN_MINT',to:target,data:'0x12',estimatedGas:100_000n,journal:durable});expect({sends,attempts}).toEqual({sends:1,attempts:2});expect(f.repo.db.prepare('SELECT state FROM transaction_intents WHERE id=?').get(f.id)).toEqual({state:'SUBMITTED'});}finally{try{locker.db.exec('ROLLBACK');}catch{}locker.close();f.close();}});
 it('hands the exact hash to recovery when all bounded SUBMITTED retries exhaust',async()=>{const f=fixture(),serialized='0x1e1f20' as Hex,hash=keccak256(serialized),base=journal(f);let sends=0,attempts=0,handoffs=0;const durable={...base,markSubmitted:()=>{attempts++;throw busy;},handoffRecovery:(prepared:DurablePreparedTransaction)=>{expect(prepared.expectedHash).toBe(hash);handoffs++;}};try{await expect(broadcastDurableTransaction({repo:f.repo,rpc:rpc(client()),walletClient:walletClient(serialized,()=>{sends++;},hash),wallet,workflowId:f.id,semanticStage:'OPEN_MINT',to:target,data:'0x12',estimatedGas:100_000n,journal:durable})).rejects.toMatchObject({name:'DurableTransactionReconciliationPendingError',evidence:'SQLITE_BUSY_AFTER_POSSIBLE_BROADCAST'});expect({sends,attempts,handoffs}).toEqual({sends:1,attempts:7,handoffs:1});expect(f.repo.db.prepare('SELECT state FROM transaction_intents WHERE id=?').get(f.id)).toEqual({state:'PREPARED'});}finally{f.close();}});
 it('retries a real SQLITE_BUSY while persisting an immediate exact receipt',async()=>{const f=fixture(),serialized='0x212223' as Hex,hash=keccak256(serialized),chain=chainJournal(f,'receipt-busy'),receipt={status:'success',transactionHash:hash,blockNumber:14n,gasUsed:54n,effectiveGasPrice:2n},locker=new SqliteLedgerRepository(f.path,{busyTimeoutMs:1});let accepted=false,sends=0,attempts=0;f.repo.db.pragma('busy_timeout = 1');const original=f.repo.reconcileDurableChainTransaction.bind(f.repo);vi.spyOn(f.repo,'reconcileDurableChainTransaction').mockImplementation(((input:any)=>{attempts++;try{return original(input);}catch(error){if(attempts===1)locker.db.exec('ROLLBACK');throw error;}}) as any);try{const result=await broadcastDurableTransaction({repo:f.repo,rpc:rpc(client({getTransactionReceipt:async()=>accepted?receipt:missing()})),walletClient:walletClient(serialized,()=>{locker.db.exec('BEGIN IMMEDIATE');accepted=true;sends++;},hash),wallet,workflowId:'receipt-busy',semanticStage:'CLOSE_BATCH',to:target,data:'0x12',estimatedGas:100_000n,journal:chain.journal});expect(result).toMatchObject({hash,receipt});expect({sends,attempts}).toEqual({sends:1,attempts:2});expect(chain.row()).toMatchObject({status:'CONFIRMED'});}finally{try{locker.db.exec('ROLLBACK');}catch{}locker.close();f.close();}});
 it('reconciles an exact mined receipt before comparing rebuilt dynamic calldata',async()=>{const f=fixture(),serialized='0x050607' as Hex,hash=keccak256(serialized);let signs=0,sends=0;const receipt={status:'reverted',transactionHash:hash,blockNumber:10n,gasUsed:50n,effectiveGasPrice:2n};try{await expect(execute(f,client(),walletClient(serialized,()=>{sends++;},hash),{afterPreparedCommit:()=>{throw new Error('CRASH_AFTER_PREPARED');}})).rejects.toThrow('CRASH_AFTER_PREPARED');const result=await broadcastDurableTransaction({repo:f.repo,rpc:rpc(client({getTransactionReceipt:async()=>receipt})),walletClient:{account:{signTransaction:async()=>{signs++;return serialized;}},request:async()=>{sends++;return hash;}} as any,wallet,workflowId:f.id,semanticStage:'OPEN_MINT',to:target,data:'0x13',estimatedGas:100_000n,journal:journal(f)});expect(result).toMatchObject({hash,recovered:true,receipt});expect({signs,sends}).toEqual({signs:0,sends:0});}finally{f.close();}});
 it('keeps metadata mismatch fail-closed when the exact hash is proven absent and nonce remains available',async()=>{const f=fixture(),serialized='0x060708' as Hex,hash=keccak256(serialized);let signs=0,sends=0;try{await expect(execute(f,client(),walletClient(serialized,()=>{sends++;},hash),{afterPreparedCommit:()=>{throw new Error('CRASH_AFTER_PREPARED');}})).rejects.toThrow('CRASH_AFTER_PREPARED');await expect(broadcastDurableTransaction({repo:f.repo,rpc:rpc(client()),walletClient:{account:{signTransaction:async()=>{signs++;return serialized;}},request:async()=>{sends++;return hash;}} as any,wallet,workflowId:f.id,semanticStage:'OPEN_MINT',to:target,data:'0x13',estimatedGas:100_000n,journal:journal(f)})).rejects.toThrow('DURABLE_PREPARED_TRANSACTION_METADATA_MISMATCH');expect({signs,sends}).toEqual({signs:0,sends:0});}finally{f.close();}});
 it('never rebuilds or rebroadcasts when the exact prepared hash may still land',async()=>{const f=fixture(),serialized='0x070809' as Hex,hash=keccak256(serialized);let signs=0,sends=0;try{await expect(execute(f,client(),walletClient(serialized,()=>{sends++;},hash),{afterPreparedCommit:()=>{throw new Error('CRASH_AFTER_PREPARED');}})).rejects.toThrow('CRASH_AFTER_PREPARED');await expect(broadcastDurableTransaction({repo:f.repo,rpc:rpc(client({getTransaction:async()=>({hash,nonce:9,from:wallet,blockNumber:null})})),walletClient:{account:{signTransaction:async()=>{signs++;return serialized;}},request:async()=>{sends++;return hash;}} as any,wallet,workflowId:f.id,semanticStage:'OPEN_MINT',to:target,data:'0x13',estimatedGas:100_000n,journal:journal(f)})).rejects.toBeInstanceOf(DurableTransactionReconciliationPendingError);expect({signs,sends}).toEqual({signs:0,sends:0});expect(f.repo.db.prepare('SELECT state FROM transaction_intents WHERE id=?').get(f.id)).toEqual({state:'SUBMITTED'});}finally{f.close();}});
 it('terminalizes a chain PREPARED row from exact success before a higher-level callback can throw',async()=>{const f=fixture(),serialized='0x08090a' as Hex,hash=keccak256(serialized),chain=chainJournal(f),receipt={status:'success',transactionHash:hash,blockNumber:10n,gasUsed:50n,effectiveGasPrice:2n};let sends=0;try{await expect(broadcastDurableTransaction({repo:f.repo,rpc:rpc(client()),walletClient:walletClient(serialized,()=>{sends++;},hash),wallet,workflowId:'chain-workflow',semanticStage:'CLOSE_BATCH',to:target,data:'0x12',estimatedGas:100_000n,journal:chain.journal,hooks:{afterPreparedCommit:()=>{throw new Error('CRASH_AFTER_PREPARED');}}})).rejects.toThrow('CRASH_AFTER_PREPARED');await expect(broadcastDurableTransaction({repo:f.repo,rpc:rpc(client({getTransactionReceipt:async()=>receipt})),walletClient:walletClient(serialized,()=>{sends++;},hash),wallet,workflowId:'chain-workflow',semanticStage:'CLOSE_BATCH',to:target,data:'0x12',estimatedGas:100_000n,journal:{...chain.journal,markSubmitted:()=>{throw new Error('HIGHER_LEVEL_FAILURE');}}})).rejects.toThrow('HIGHER_LEVEL_FAILURE');expect(chain.row()).toMatchObject({status:'CONFIRMED',failure_reason:null});expect(JSON.parse(String(chain.row()!.receipt_json))).toMatchObject({status:'success',transactionHash:hash});expect(sends).toBe(0);}finally{f.close();}});
 it('terminalizes exact revert and consumed nonce, but keeps an available nonce unresolved',async()=>{for(const scenario of ['revert','consumed','available'] as const){const f=fixture(),serialized=scenario==='revert'?'0x0b0c0d':scenario==='consumed'?'0x0e0f10':'0x111214' as Hex,hash=keccak256(serialized as Hex),chain=chainJournal(f,`chain-${scenario}`);try{await expect(broadcastDurableTransaction({repo:f.repo,rpc:rpc(client()),walletClient:walletClient(serialized as Hex,()=>{},hash),wallet,workflowId:`chain-${scenario}`,semanticStage:'CLOSE_BATCH',to:target,data:'0x12',estimatedGas:100_000n,journal:chain.journal,hooks:{afterPreparedCommit:()=>{throw new Error('CRASH');}}})).rejects.toThrow('CRASH');const receipt={status:'reverted',transactionHash:hash,blockNumber:11n,gasUsed:51n,effectiveGasPrice:2n},latest=scenario==='consumed'?10:9,observed=client(scenario==='revert'?{getTransactionReceipt:async()=>receipt}:{getTransactionCount:async()=>latest});const recovery=broadcastDurableTransaction({repo:f.repo,rpc:rpc(observed),walletClient:walletClient(serialized as Hex,()=>{},hash),wallet,workflowId:`chain-${scenario}`,semanticStage:'CLOSE_BATCH',to:target,data:'0x12',estimatedGas:100_000n,journal:chain.journal});if(scenario==='revert')expect((await recovery).receipt).toMatchObject({status:'reverted'});else if(scenario==='consumed')await expect(recovery).rejects.toThrow('DURABLE_TRANSACTION_EXACT_HASH_ABSENT_NONCE_UNAVAILABLE');else await expect(recovery).rejects.toBeInstanceOf(DurableTransactionReconciliationPendingError);expect(chain.row()).toMatchObject(scenario==='revert'?{status:'FAILED',failure_reason:'TRANSACTION_REVERTED'}:scenario==='consumed'?{status:'FAILED',failure_reason:'NONCE_NO_LONGER_AVAILABLE'}:{status:'PREPARED'});}finally{f.close();}}});
});
