import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {describe,expect,it} from 'vitest';
import {migrateSqlite,SqliteLedgerRepository} from '@funi/ledger';
import {canonicalEconomicWorkId,completeEconomicReconciliationWork,ensureEconomicReconciliationWork,leaseEconomicReconciliationWork,retryEconomicReconciliationWork} from '../apps/cli/src/economic-reconciliation-work.js';

const hash=`0x${'AB'.repeat(32)}`;
function fixture(){const dir=mkdtempSync(join(tmpdir(),'economic-reconcile-')),path=join(dir,'db.sqlite');migrateSqlite(path,'infra/migrations');const repo=new SqliteLedgerRepository(path);return {repo,close(){repo.close();rmSync(dir,{recursive:true,force:true});}};}
const identity={chainId:4663,workflowKind:'V4_BID_LADDER_OPEN' as const,workflowIdentity:'ladder:1',semanticStage:'OPEN_BATCH',transactionHash:hash};

describe('durable economic reconciliation work',()=>{
 it('uses one deterministic normalized identity across replay paths',()=>{const f=fixture();try{const a=ensureEconomicReconciliationWork(f.repo,{...identity,sourceTable:'chain_transaction_journal',sourceIdentity:'journal:1',nowMs:10}),b=ensureEconomicReconciliationWork(f.repo,{...identity,transactionHash:hash.toLowerCase(),sourceTable:'chain_transaction_journal',sourceIdentity:'journal:1',nowMs:20});expect(a.work_id).toBe(b.work_id);expect(a.work_id).toBe(canonicalEconomicWorkId(identity));expect(f.repo.db.prepare('SELECT count(*) count FROM economic_reconciliation_work').get()).toEqual({count:1});}finally{f.close();}});
 it('rejects an equivalent canonical stage mapped to a conflicting source',()=>{const f=fixture();try{ensureEconomicReconciliationWork(f.repo,{...identity,sourceTable:'chain_transaction_journal',sourceIdentity:'journal:1'});expect(()=>ensureEconomicReconciliationWork(f.repo,{...identity,sourceTable:'chain_transaction_journal',sourceIdentity:'journal:2'})).toThrow('ECONOMIC_RECONCILIATION_CANONICAL_IDENTITY_CONFLICT');}finally{f.close();}});
 it('leases exclusively, reclaims expiry, retries with backoff, and completes only for its owner',()=>{const f=fixture();try{const work=ensureEconomicReconciliationWork(f.repo,{...identity,sourceTable:'chain_transaction_journal',sourceIdentity:'journal:1',nowMs:100});expect(leaseEconomicReconciliationWork(f.repo,{owner:'worker-a',nowMs:100,leaseMs:1_000})).toHaveLength(1);expect(leaseEconomicReconciliationWork(f.repo,{owner:'worker-b',nowMs:200})).toHaveLength(0);expect(leaseEconomicReconciliationWork(f.repo,{owner:'worker-b',nowMs:1_100})).toHaveLength(1);expect(retryEconomicReconciliationWork(f.repo,{workId:String(work.work_id),owner:'worker-a',errorCode:'wrong owner',nowMs:1_100})).toBe(false);expect(retryEconomicReconciliationWork(f.repo,{workId:String(work.work_id),owner:'worker-b',errorCode:'rpc unavailable',nowMs:1_100})).toBe(true);expect(leaseEconomicReconciliationWork(f.repo,{owner:'worker-c',nowMs:2_000})).toHaveLength(0);const due=Number((f.repo.db.prepare('SELECT available_at_ms FROM economic_reconciliation_work').get() as any).available_at_ms);expect(leaseEconomicReconciliationWork(f.repo,{owner:'worker-c',nowMs:due})).toHaveLength(1);expect(completeEconomicReconciliationWork(f.repo,{workId:String(work.work_id),owner:'worker-c',nowMs:due+1})).toBe(true);expect(leaseEconomicReconciliationWork(f.repo,{owner:'worker-d',nowMs:due+2})).toHaveLength(0);}finally{f.close();}});
});
