import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {describe,expect,it,vi} from 'vitest';
import {migrateSqlite,SqliteLedgerRepository} from '@funi/ledger';
import {discoverMissingEconomicReconciliationWork,ensureEconomicReconciliationWork,leaseEconomicReconciliationWork} from '../apps/cli/src/economic-reconciliation-work.js';

const tx=`0x${'7'.repeat(64)}`,wallet='0x0000000000000000000000000000000000000001',key={currency0:'0x0000000000000000000000000000000000000002',currency1:'0x0000000000000000000000000000000000000003',fee:500,tickSpacing:10,hooks:'0x0000000000000000000000000000000000000000'};
function fixture(){const dir=mkdtempSync(join(tmpdir(),'economic-architecture-')),path=join(dir,'db.sqlite');migrateSqlite(path,'infra/migrations');const repo=new SqliteLedgerRepository(path);return {repo,close(){repo.close();rmSync(dir,{recursive:true,force:true});}};}

describe('Telegram economic durable async architecture',()=>{
 it('lets acknowledgement return while a controlled slow reconciliation remains pending',async()=>{const f=fixture();try{let release!:()=>void;const slow=new Promise<void>(resolve=>{release=resolve;}),handler=async()=>{ensureEconomicReconciliationWork(f.repo,{chainId:4663,workflowKind:'V4_OPERATIONAL_OPEN',workflowIdentity:'intent:latency',semanticStage:'V4_MINT',transactionHash:tx,sourceTable:'v4_live_open_intents',sourceIdentity:'intent:latency'});return 'ACK_RETURNED';},ack=await handler(),leased=leaseEconomicReconciliationWork(f.repo,{owner:'funi-reconcile:test',nowMs:Date.now()});let finished=false;const background=(async()=>{await slow;finished=true;})();expect(ack).toBe('ACK_RETURNED');expect(leased).toHaveLength(1);expect(finished).toBe(false);release();await background;expect(finished).toBe(true);}finally{f.close();}});
 it('reconstructs an absent handoff from an authoritative successful operational receipt',()=>{const f=fixture();try{const intent=f.repo.createV4LiveOpenIntent({idempotencyKey:'missing-handoff',owner:wallet,userId:'u',chatId:'c',poolId:'pool',poolKey:key,amount:1n,payload:{genericSelection:{...key,key,target:key.currency0,funding:key.currency1}}});f.repo.db.prepare("UPDATE v4_live_open_intents SET state='MINT_CONFIRMED',mint_hash=? WHERE id=?").run(tx,intent.id);f.repo.db.prepare("INSERT INTO v4_operational_open_receipts(tx_hash,intent_id,phase,receipt_json,created_at) VALUES(?,?,'V4_MINT',?,datetime('now'))").run(tx,intent.id,JSON.stringify({status:'success',transactionHash:tx}));expect(f.repo.db.prepare('SELECT count(*) count FROM economic_reconciliation_work').get()).toEqual({count:0});expect(discoverMissingEconomicReconciliationWork(f.repo,100)).toMatchObject({scanned:1,materialized:1});expect(f.repo.db.prepare('SELECT workflow_kind,status,transaction_hash FROM economic_reconciliation_work').get()).toEqual({workflow_kind:'V4_OPERATIONAL_OPEN',status:'PENDING',transaction_hash:tx});expect(discoverMissingEconomicReconciliationWork(f.repo,101).materialized).toBe(1);expect(f.repo.db.prepare('SELECT count(*) count FROM economic_reconciliation_work').get()).toEqual({count:1});}finally{f.close();}});
 it('keeps queue leasing exclusive to reconcile owner code and exposes no execution primitive',()=>{const cycle=readFileSync('apps/cli/src/economic-reconciliation-cycle.ts','utf8'),state=readFileSync('apps/workers/src/state-cache-worker.ts','utf8'),telegram=readFileSync('apps/telegram-lp-bot/src/index.ts','utf8');expect(cycle).toContain('leaseEconomicReconciliationWork');expect(state).not.toContain('economic_reconciliation_work');expect(state).not.toContain('leaseEconomicReconciliationWork');expect(cycle).not.toMatch(/WalletClient|signWithConfiguredAccount|broadcastSignedTransaction|sendRawTransaction|acquireNonceMutex/);expect(telegram).not.toMatch(/setImmediate\(|runner\(/);});
 it('never rematerializes historical OPEN work for an already-CLOSED ladder',()=>{const f=fixture(),ladder='historical-closed',hash='0x'+'b'.repeat(64),address=(digit:string)=>`0x${digit.repeat(40)}`;try{f.repo.db.prepare("INSERT INTO v4_bid_ladders(ladder_id,strategy_version,execution_mode,pool_id,currency0,currency1,fee,tick_spacing,hooks,funding_token,target_token,funding_index,target_index,reference_tick,reference_block,total_funding_amount_raw,status,created_at_ms,updated_at_ms) VALUES(?,'V4_BID_LADDER_V1','LIVE',?,?,?,?,?,?,?,?,1,0,0,'1','100','CLOSED',1,2)").run(ladder,'0x'+'1'.repeat(64),address('1'),address('2'),3000,10,address('0'),address('2'),address('1'));f.repo.db.prepare("INSERT INTO chain_transaction_journal(chain_id,chain_key,protocol,journal_id,wallet_address,workflow_identity,semantic_stage,attempt,status,nonce,transaction_type,expected_hash,to_address,request_fingerprint,fee_model,receipt_json,confirmation_count,created_at,confirmed_at,updated_at) VALUES(4663,'robinhood','uniswap_v4',?,?,?, 'OPEN_BATCH',0,'CONFIRMED',7,'legacy',?,?,?,'legacy',?,1,'2026-01-01','2026-01-01','2026-01-01')").run('historical-open',address('3'),ladder,hash,address('4'),'fingerprint',JSON.stringify({status:'success',transactionHash:hash}));const before={journal:f.repo.db.prepare('SELECT status,receipt_json FROM chain_transaction_journal WHERE journal_id=?').get('historical-open'),pnl:f.repo.db.prepare('SELECT COUNT(*) count FROM realized_pnl_events').get()};expect(discoverMissingEconomicReconciliationWork(f.repo,100)).toEqual({scanned:0,materialized:0});expect(discoverMissingEconomicReconciliationWork(f.repo,101)).toEqual({scanned:0,materialized:0});expect(f.repo.db.prepare('SELECT COUNT(*) count FROM economic_reconciliation_work').get()).toEqual({count:0});expect({journal:f.repo.db.prepare('SELECT status,receipt_json FROM chain_transaction_journal WHERE journal_id=?').get('historical-open'),pnl:f.repo.db.prepare('SELECT COUNT(*) count FROM realized_pnl_events').get()}).toEqual(before);}finally{f.close();}});
 it('classifies pre-receipt failures separately from receipt-backed downstream work',()=>{const lifecycle=readFileSync('apps/cli/src/v4-lifecycle.ts','utf8'),operational=readFileSync('apps/cli/src/v4-operational-executor.ts','utf8');expect(lifecycle).toContain('failBeforeConfirmation');expect(lifecycle).toContain('CONFIRMED_RECONCILIATION_REQUIRED');expect(lifecycle).toContain('ECONOMIC_CONFIRMED_RECONCILIATION_PENDING');expect(operational).toContain('receiptBacked');expect(operational).toContain('OPEN_RECONCILIATION_PENDING');});
});
