import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawn } from 'node:child_process';
import Database from 'better-sqlite3';
import { afterEach, describe, expect, it } from 'vitest';
import {
  acquireEconomicForegroundDemand,
  economicForegroundMarkerDirectory,
  inspectEconomicForegroundDemand,
  waitForEconomicForegroundDemandToClear,
  withEconomicForegroundPersistenceSync,
} from '@funi/ledger';

const roots:string[]=[];
const fixture=()=>{const root=mkdtempSync(join(tmpdir(),'funi-economic-priority-')),path=join(root,'db.sqlite'),db=new Database(path);roots.push(root);db.pragma('journal_mode=WAL');db.exec('CREATE TABLE journal(id INTEGER PRIMARY KEY,value INTEGER NOT NULL); INSERT INTO journal(value) VALUES(0)');return {root,path,db};};
afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});

describe('filesystem economic foreground priority',()=>{
 it('publishes multiple independent owners atomically and releases exactly its own marker',()=>{const f=fixture(),a=acquireEconomicForegroundDemand({databasePath:f.path,component:'test-a',operation:'prepared'}),b=acquireEconomicForegroundDemand({databasePath:f.path,component:'test-b',operation:'submitted'});try{expect(inspectEconomicForegroundDemand(f.path)).toMatchObject({demandPresent:true,liveOwnerCount:2,staleOwnerCount:0});a.release();expect(inspectEconomicForegroundDemand(f.path)).toMatchObject({demandPresent:true,liveOwnerCount:1});b.release();expect(inspectEconomicForegroundDemand(f.path)).toMatchObject({demandPresent:false,liveOwnerCount:0});expect(economicForegroundMarkerDirectory(f.path)).toContain('.sqlite-economic-foreground');}finally{a.release();b.release();f.db.close();}});

 it('ignores and safely cleans a crash-stale owner without pausing background forever',async()=>{const f=fixture(),crashed=acquireEconomicForegroundDemand({databasePath:f.path,component:'crashed',operation:'prepared',ttlMs:100});try{expect(inspectEconomicForegroundDemand(f.path).demandPresent).toBe(true);await new Promise(resolve=>setTimeout(resolve,125));expect(inspectEconomicForegroundDemand(f.path)).toMatchObject({demandPresent:false,staleOwnerCount:1});const next=acquireEconomicForegroundDemand({databasePath:f.path,component:'next',operation:'prepared',ttlMs:100});try{expect(inspectEconomicForegroundDemand(f.path)).toMatchObject({demandPresent:true,liveOwnerCount:1,staleOwnerCount:0});}finally{next.release();}}finally{crashed.release();f.db.close();}});

 it('makes a pending background writer yield until foreground release',async()=>{const f=fixture(),foreground=acquireEconomicForegroundDemand({databasePath:f.path,component:'economic',operation:'open_prepared'});try{setTimeout(()=>foreground.release(),75);const result=await waitForEconomicForegroundDemandToClear({databasePath:f.path,component:'registry',operation:'registry_write',pollMs:5,maxWaitMs:500});expect(result.cleared).toBe(true);expect(result.demandPresent).toBe(true);expect(result.waitedMs).toBeGreaterThanOrEqual(50);f.db.prepare('UPDATE journal SET value=value+1').run();expect(f.db.prepare('SELECT value FROM journal').get()).toEqual({value:1});}finally{foreground.release();f.db.close();}});

 it('absorbs only an already-running cross-process writer and then commits foreground once',async()=>{const f=fixture();f.db.pragma('busy_timeout=1');const child=spawn(process.execPath,['-e',`const Database=require('better-sqlite3'),db=new Database(${JSON.stringify(f.path)});db.pragma('busy_timeout=1');db.exec('BEGIN IMMEDIATE');process.stdout.write('locked');setTimeout(()=>{db.exec('COMMIT');db.close()},350)`],{cwd:process.cwd(),stdio:['ignore','pipe','inherit']}),closed=new Promise<void>((resolve,reject)=>{child.once('close',()=>resolve());child.once('error',reject);});await new Promise<void>((resolve,reject)=>{child.stdout!.on('data',chunk=>{if(String(chunk).includes('locked'))resolve();});child.once('error',reject);});const events:any[]=[],started=Date.now(),result=withEconomicForegroundPersistenceSync({databasePath:f.path,component:'test-economic',operation:'open_batch_prepared_commit',workflow:'workflow',semanticStage:'OPEN_BATCH',run:()=>f.db.prepare('UPDATE journal SET value=value+1').run(),onTelemetry:event=>events.push(event)});await closed;expect(result.changes).toBe(1);expect(Date.now()-started).toBeGreaterThanOrEqual(250);expect(f.db.prepare('SELECT value FROM journal').get()).toEqual({value:1});expect(events).toEqual([expect.objectContaining({persistenceClass:'foreground',operation:'open_batch_prepared_commit',outcome:'SUCCEEDED',retryCount:expect.any(Number)})]);expect(inspectEconomicForegroundDemand(f.path).demandPresent).toBe(false);f.db.close();});

 it('measures bounded PREPARED commits while short background writer windows are already active',async()=>{const f=fixture();f.db.pragma('busy_timeout=1');const samples:number[]=[],retries:number[]=[];try{for(let index=0;index<8;index++){const child=spawn(process.execPath,['-e',`const Database=require('better-sqlite3'),db=new Database(${JSON.stringify(f.path)});db.pragma('busy_timeout=1');db.exec('BEGIN IMMEDIATE');db.prepare('UPDATE journal SET value=value+1').run();process.stdout.write('locked');setTimeout(()=>{db.exec('COMMIT');db.close()},20)`],{cwd:process.cwd(),stdio:['ignore','pipe','inherit']}),closed=new Promise<void>((resolve,reject)=>{child.once('close',()=>resolve());child.once('error',reject);});await new Promise<void>((resolve,reject)=>{child.stdout!.on('data',chunk=>{if(String(chunk).includes('locked'))resolve();});child.once('error',reject);});const events:any[]=[],started=performance.now();withEconomicForegroundPersistenceSync({databasePath:f.path,component:'performance-proof',operation:'open_batch_prepared_commit',workflow:`w${index}`,semanticStage:'OPEN_BATCH',run:()=>f.db.prepare('UPDATE journal SET value=value+1').run(),onTelemetry:event=>events.push(event)});samples.push(performance.now()-started);retries.push(Number(events[0]?.retryCount??0));await closed;}samples.sort((a,b)=>a-b);const at=(p:number)=>samples[Math.ceil(samples.length*p)-1]!;console.log(JSON.stringify({event:'public_economic_foreground_performance',samples:samples.length,p50Ms:at(.5),p95Ms:at(.95),maxMs:samples.at(-1),retryExhaustionCount:0,maxRetryCount:Math.max(...retries)}));expect(f.db.prepare('SELECT value FROM journal').get()).toEqual({value:16});}finally{f.db.close();}});

 it('allows background progress between repeated tiny foreground commits without foreground starvation',async()=>{const f=fixture();let background=0;for(let i=0;i<12;i++){withEconomicForegroundPersistenceSync({databasePath:f.path,component:'soak',operation:'prepared',workflow:`w${i}`,semanticStage:'OPEN_BATCH',run:()=>f.db.prepare('UPDATE journal SET value=value+1').run()});const clear=await waitForEconomicForegroundDemandToClear({databasePath:f.path,component:'background-soak',operation:'cache',maxWaitMs:100});if(clear.cleared){f.db.prepare('UPDATE journal SET value=value+1').run();background++;}}expect(background).toBe(12);expect(f.db.prepare('SELECT value FROM journal').get()).toEqual({value:24});f.db.close();});
});
