import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { migrateSqlite, SqliteLedgerRepository } from '@robin/ledger';
import { sanitizeRpcError, sanitizeSensitiveText } from '@robin/core';
import { applyErrorSecretScrub, errorSecretScrubPlan } from '../apps/cli/src/rebalance-transaction.js';
import { safeTelegramError } from '../apps/telegram-lp-bot/src/telegram-error.js';

const secret='synthetic-secret-123';
function fixture(){const dir=mkdtempSync(join(tmpdir(),'error-scrub-')),path=join(dir,'db.sqlite');migrateSqlite(path,'infra/migrations');const repo=new SqliteLedgerRepository(path);repo.db.prepare('INSERT INTO rebalance_lineages(id,root_position_id,original_principal_usd,original_funding_token,original_funding_symbol,protocol_version,pool_id,created_at) VALUES(?,?,?,?,?,?,?,?)').run('lineage','v4:1',1,'0x1','USDG','v4','pool','2020-01-01');repo.db.prepare('INSERT INTO rebalance_workflows(id,idempotency_key,lineage_id,old_position_id,mode,downside_pct,state,preview_json,state_json,last_error,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run('workflow','workflow','lineage','v4:1','REBALANCE',10,'FAILED_RECOVERABLE','{}',JSON.stringify({diagnostic:`method eth_call endpoint https://rpc.example/v2/${secret}?api_key=${secret}`}),`HTTP 429 provider=https://rpc.example/v2/${secret} Authorization: Bearer ${secret}`,'2020-01-01','2020-01-01');const at='2020-01-01';repo.db.prepare('INSERT INTO rebalance_transactions(id,workflow_id,semantic_stage,attempt,status,tx_hash,nonce,to_address,calldata_hash,request_json,estimated_gas_raw,estimated_gas_usd,failure_reason,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run('tx','workflow','CLOSE_FULL',0,'FAILED',`0x${'11'.repeat(32)}`,1,'0x1','0x2','{}','1',0,`transport api_key=${secret}`,at,at);return {repo,close(){repo.close();rmSync(dir,{recursive:true,force:true});}};}

describe('canonical credential redaction and scrub',()=>{
 it('redacts URL paths, queries, bearer tokens, authorization headers, API keys, and nested causes',()=>{const forms=[`https://rpc.example/v2/${secret}`,`https://rpc.example?api_key=${secret}`,`Bearer ${secret}`,`Authorization: Bearer ${secret}`,`api_key=${secret}`];for(const form of forms){const safe=sanitizeSensitiveText(`provider HttpRequestError method=eth_call code=429 ${form}`);expect(safe).toContain('provider HttpRequestError method=eth_call code=429');expect(safe).not.toContain(secret);expect(safeTelegramError(new Error(`operator failure ${form}`)).errorMessage).not.toContain(secret);}const nested=Object.assign(new Error('provider request failed'),{name:'HttpRequestError',status:429,cause:new Error(`https://rpc.example/v2/${secret}?token=${secret}`)}),safe=sanitizeRpcError(nested,{stage:'close_full',method:'eth_sendRawTransaction'});expect(safe).toContain('stage=close_full method=eth_sendRawTransaction');expect(safe).toContain('status=429');expect(safe).not.toContain(secret);expect(safe).not.toContain('https://rpc.example/v2/');});
 it('previews counts only, preserves diagnostics, and is idempotent',()=>{const f=fixture();try{const states=f.repo.db.prepare('SELECT state FROM rebalance_workflows WHERE id=?').get('workflow'),plan=errorSecretScrubPlan(f.repo);expect(plan.totalRows).toBe(3);expect(plan.counts).toEqual([{table:'rebalance_workflows',rowCount:2},{table:'rebalance_transactions',rowCount:1}]);const applied=applyErrorSecretScrub(f.repo,plan.fingerprint);expect(applied.totalRows).toBe(3);const stored=f.repo.db.prepare('SELECT state_json,last_error FROM rebalance_workflows WHERE id=?').get('workflow') as Record<string,string>,failure=(f.repo.db.prepare('SELECT failure_reason FROM rebalance_transactions WHERE id=?').get('tx') as Record<string,string>).failure_reason;expect(`${stored.state_json} ${stored.last_error} ${failure}`).not.toContain(secret);expect(`${stored.state_json} ${stored.last_error} ${failure}`).toContain('eth_call');expect(`${stored.state_json} ${stored.last_error} ${failure}`).toContain('HTTP 429');expect(f.repo.db.prepare('SELECT state FROM rebalance_workflows WHERE id=?').get('workflow')).toEqual(states);expect(errorSecretScrubPlan(f.repo).totalRows).toBe(0);expect(applyErrorSecretScrub(f.repo,errorSecretScrubPlan(f.repo).fingerprint).totalRows).toBe(0);}finally{f.close();}});
});
