import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { migrateSqlite, SqliteLedgerRepository } from '@funi/ledger';
import { evaluateIntentFundingReadiness, staticCanaryReachability } from '../apps/cli/src/runtime.js';
import { evaluateCanaryGates, executeConfirmedCanaryRoute, executePreparedCanaryRoute } from '../apps/cli/src/live-canary-route.js';

const address='0x0000000000000000000000000000000000000001' as const;
const factory='0x0000000000000000000000000000000000000002' as const;
const ready={status:'READY_FOR_USDG_ONLY_CANARY',approvalStatus:'APPROVAL_REQUIRED' as const,estimatedGasUsd:1};
function database(){const root=mkdtempSync(join(tmpdir(),'funi-route-')),path=join(root,'ledger.sqlite');migrateSqlite(path,join(process.cwd(),'infra/migrations'));return new SqliteLedgerRepository(path);}
function fixture(repo:SqliteLedgerRepository){const flow=repo.createTelegramFlow({userId:'u',chatId:'c',state:{kind:'pool'},now:Date.now(),ttlMs:600_000}),selection=repo.createPoolSelection({userId:'u',chatId:'c',sessionId:flow.sessionId,poolAddress:address,factoryAddress:factory,token0Address:address,token1Address:factory,fee:100,tickSpacing:1,discoveryBlock:1n,liquidity:1n,tvlUsd:5_000_000,initialized:true}),confirmation=repo.createConfirmation({action:'SINGLE_SIDED_DOWNSIDE_MINT',payload:{selectionId:selection.id},expiresAt:new Date(Date.now()+600_000).toISOString(),owner:'u',idempotencyKey:`route:${Math.random()}`})!;return {flow,selection,confirmation};}
function routeInput(repo:SqliteLedgerRepository,f:ReturnType<typeof fixture>){return {repo,confirmationId:String(f.confirmation.id),selectionId:String(f.selection.id),sessionId:f.flow.sessionId,buttonPool:address,verifiedFactory:factory,userId:'u',chatId:'c',allowlisted:true,readiness:ready,executionEnabled:true,dryRun:false,emergencyPause:false,liveCanaryEnabled:true,signerConfigured:true,chainId:4663,deploymentVerified:true,positionUsd:5,approvalUsd:5,maxPositionUsd:5,maxApprovalUsd:5,openPositions:0,maxOpenPositions:1,wallet:address,poolValidator:async()=>({ok:true as const}),executorInput:{rpc:{} as any,walletClient:{} as any,wallet:address,owner:'u',pool:address,target:{address,symbol:'PONS',decimals:18},funding:{address:factory,symbol:'USDG',decimals:6},fundingAmount:5_000_000n,upperDropPct:0,lowerDropPct:30,slippageBps:50,deadlineSeconds:300,maxGasUsd:2,gasUsdPerNative:2_000,notify:async()=>{}}};}

describe('selected-intent canary readiness',()=>{
 it('accepts one funding asset without requiring the unrelated or target asset',()=>{const usdg=evaluateIntentFundingReadiness({fundingSymbol:'USDG',fundingBalance:519_792_957n,fundingAmount:5_000_000n,currentAllowance:0n,nativeBalance:10n**18n,combinedGasEstimate:300_000n,gasPriceWei:1_000_000_000n,nativeUsd:2_000,maxGasUsd:2}),weth=evaluateIntentFundingReadiness({fundingSymbol:'WETH',fundingBalance:10n**18n,fundingAmount:10n**17n,currentAllowance:10n**17n,nativeBalance:10n**18n,combinedGasEstimate:300_000n,gasPriceWei:1_000_000_000n,nativeUsd:2_000,maxGasUsd:2});expect(usdg).toMatchObject({status:'READY_FOR_USDG_ONLY_CANARY',approvalStatus:'APPROVAL_REQUIRED'});expect(weth).toMatchObject({status:'READY_FOR_WETH_ONLY_CANARY',approvalStatus:'ALLOWANCE_SUFFICIENT'});expect('targetBalance' in usdg).toBe(false);});
 it('separates funding, native gas, and combined gas-cap failures',()=>{const base={fundingSymbol:'USDG',fundingBalance:10_000_000n,fundingAmount:5_000_000n,currentAllowance:0n,combinedGasEstimate:500_000n,gasPriceWei:1_000_000_000n,nativeUsd:2_000,maxGasUsd:2};expect(evaluateIntentFundingReadiness({...base,nativeBalance:1n}).status).toBe('GAS_BALANCE_INSUFFICIENT');expect(evaluateIntentFundingReadiness({...base,nativeBalance:10n**18n,maxGasUsd:.5}).status).toBe('GAS_CAP_TOO_LOW');expect(evaluateIntentFundingReadiness({...base,nativeBalance:10n**18n,fundingBalance:1n}).status).toBe('FUNDING_ASSET_BALANCE_INSUFFICIENT');});
 it('keeps safe defaults unreachable',()=>{const base={executionEnabled:true,dryRun:false,emergencyPause:false,liveCanaryEnabled:true,signerConfigured:true,operatorConfigured:true,chainId:4663,deploymentVerified:true};expect(staticCanaryReachability({...base,dryRun:true}).executionReachable).toBe(false);expect(staticCanaryReachability(base).executionReachable).toBe(true);});
});

describe('no-arm durable canary route',()=>{
 it('uses one prepared final-click intent and does not inspect preview age or hashes',async()=>{const repo=database();try{const f=fixture(repo),prepared=repo.createCanaryIntent({wallet:address,owner:'u',idempotencyKey:'prepared-final-click',payload:{canary:{pool:'0x52e65B17fB6E5BA00Ed806f37Afcd2DaA50271Ca'}}}),base=routeInput(repo,f),{confirmationId,...rest}=base;let calls=0;const executor=(async(input:any)=>{calls++;repo.claimCanaryIntent(input.intentId);return {ok:true,status:'COMPLETED'};}) as any;const first=await executePreparedCanaryRoute({...rest,intentId:String(prepared.id)},executor),duplicate=await executePreparedCanaryRoute({...rest,intentId:String(prepared.id)},executor);expect(first.status).toBe('EXECUTOR_INVOKED');expect(duplicate.status).toBe('ALREADY_PROCESSING_OR_COMPLETED');expect(calls).toBe(1);expect(repo.confirmation(String(f.confirmation.id))?.state).toBe('AWAITING_CONFIRMATION');}finally{repo.close();}});
 it('claims one persistent budget and invokes the executor exactly once without an arm',async()=>{const repo=database();try{const f=fixture(repo);let calls=0;const executor=(async()=>{calls++;return {ok:true,status:'COMPLETED'};}) as any;const first=await executeConfirmedCanaryRoute(routeInput(repo,f),executor),duplicate=await executeConfirmedCanaryRoute(routeInput(repo,f),executor);expect(first.status).toBe('EXECUTOR_INVOKED');expect(duplicate.status).toBe('EXECUTION_BLOCKED');expect(calls).toBe(1);expect(repo.canaryBudget()).toMatchObject({status:'CLAIMED',attempts_used:1});expect(repo.canaryIntentByKey(`telegram-canary:${String(f.confirmation.id)}`)).toBeTruthy();}finally{repo.close();}});
 it('persists budget across restart and terminal attempts enable manual pause',()=>{const repo=database(),path=repo.path;try{const f=fixture(repo),claim=repo.claimCanaryConfirmation({confirmationId:String(f.confirmation.id),owner:'u',userId:'u',chatId:'c',wallet:address,now:Date.now(),payload:{}});expect(claim.status).toBe('CLAIMED');repo.finalizeCanaryBudget(String((claim as any).intent.id),false,{failureReason:'mint blocked',remainingAllowanceRaw:5_000_000n});}finally{repo.close();}const reopened=new SqliteLedgerRepository(path);try{expect(reopened.canaryBudget()).toMatchObject({status:'FAILED',attempts_used:1,remaining_allowance_raw:'5000000'});expect(reopened.safetyState()?.manualPause).toBe(true);}finally{reopened.close();}});
 it('requires an explicit one-time CLI reset token',()=>{const repo=database();try{const request=repo.requestCanaryBudgetReset(100,100);expect(repo.resetCanaryBudget('wrong',101)).toBe(false);expect(repo.resetCanaryBudget(request.token,101)).toBe(true);expect(repo.canaryBudgetAvailable()).toBe(true);expect(repo.resetCanaryBudget(request.token,101)).toBe(false);}finally{repo.close();}});
 it('keeps immutable pool selections distinct and marks zero liquidity unavailable',()=>{const repo=database();try{const flow=repo.createTelegramFlow({userId:'u',chatId:'c',state:{},now:1,ttlMs:100}),a=repo.createPoolSelection({userId:'u',chatId:'c',sessionId:flow.sessionId,poolAddress:address,factoryAddress:factory,token0Address:address,token1Address:factory,fee:100,tickSpacing:1,discoveryBlock:1n,liquidity:10n,initialized:true}),b=repo.createPoolSelection({userId:'u',chatId:'c',sessionId:flow.sessionId,poolAddress:factory,factoryAddress:factory,token0Address:address,token1Address:factory,fee:10_000,tickSpacing:200,discoveryBlock:1n,liquidity:0n,initialized:true});expect(a.id).not.toBe(b.id);expect(repo.poolSelection(String(a.id))).toMatchObject({pool_address:address,fee:100,liquidity_raw:'10'});expect(repo.poolSelection(String(b.id))).toMatchObject({pool_address:factory,fee:10_000,liquidity_raw:'0'});}finally{repo.close();}});
 it('shared evaluator returns identical readiness and mismatch reasons',()=>{const input={executionEnabled:true,dryRun:false,emergencyPause:false,liveCanaryEnabled:true,manualPause:false,runtimeConfigurationMatches:true,allowlisted:true,signerConfigured:true,chainId:4663,deploymentVerified:true,positionUsd:5,approvalUsd:5,maxPositionUsd:5,maxApprovalUsd:5,pendingExecutions:0,budgetAvailable:true,openPositions:0,maxOpenPositions:1,readiness:ready,poolValidation:{ok:true}};expect(evaluateCanaryGates(input)).toEqual(evaluateCanaryGates(input));expect(evaluateCanaryGates({...input,runtimeConfigurationMatches:false}).blockingReasons).toContain('RUNTIME_CONFIGURATION_MISMATCH');expect(evaluateCanaryGates({...input,poolValidation:{ok:false,reason:'POOL_ZERO_ACTIVE_LIQUIDITY'}}).blockingReasons).toContain('POOL_ZERO_ACTIVE_LIQUIDITY');});
});
