import Database from 'better-sqlite3';
import { existsSync, mkdtempSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { migrateSqlite } from '@funi/ledger';

const cleanup:string[]=[];
afterEach(()=>{for(const root of cleanup.splice(0))rmSync(root,{recursive:true,force:true});});
const fixture=()=>{const root=mkdtempSync(join(tmpdir(),'migration-batch-backup-')),database=join(root,'ledger.sqlite'),migrations=join(root,'migrations');mkdirSync(migrations);writeFileSync(join(migrations,'001_base.sql'),'CREATE TABLE base_rows(id INTEGER PRIMARY KEY);');cleanup.push(root);return {root,database,migrations};};
const add=(directory:string,name:string,sql:string)=>writeFileSync(join(directory,name),sql);
const backupDirectory=(root:string)=>join(root,'backups');
const backupFiles=(root:string)=>existsSync(backupDirectory(root))?readdirSync(backupDirectory(root)).filter(name=>name.startsWith('pre-migration-batch-')&&name.endsWith('.sqlite')).sort():[];
const readManifests=(root:string)=>backupFiles(root).map(name=>JSON.parse(readFileSync(join(backupDirectory(root),`${name}.json`),'utf8')) as {migrationBatchId:string;outcome:string});

describe('migration batch backups',()=>{
 it('creates zero backups for initial and repeated no-op migration runs',()=>{const f=fixture();migrateSqlite(f.database,f.migrations);expect(backupFiles(f.root)).toEqual([]);expect(migrateSqlite(f.database,f.migrations).pending).toEqual([]);expect(migrateSqlite(f.database,f.migrations).pending).toEqual([]);expect(backupFiles(f.root)).toEqual([]);});
 it('creates exactly one validated backup for one complete pending batch and reruns idempotently',()=>{const f=fixture();migrateSqlite(f.database,f.migrations);add(f.migrations,'002_one.sql','CREATE TABLE one_rows(id INTEGER PRIMARY KEY);');add(f.migrations,'003_two.sql','CREATE TABLE two_rows(id INTEGER PRIMARY KEY);');expect(migrateSqlite(f.database,f.migrations).pending).toEqual([]);const first=backupFiles(f.root);expect(first).toHaveLength(1);const manifest=readManifests(f.root);expect(manifest).toHaveLength(1);expect(manifest[0]).toMatchObject({migrationBatchId:expect.any(String),outcome:'SUCCESS'});expect(migrateSqlite(f.database,f.migrations).pending).toEqual([]);expect(backupFiles(f.root)).toEqual(first);const db=new Database(f.database);try{expect(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name IN ('one_rows','two_rows') ORDER BY name").all()).toEqual([{name:'one_rows'},{name:'two_rows'}]);}finally{db.close();}});
 it('reuses one pending backup for retries of the same failed batch',()=>{const f=fixture();migrateSqlite(f.database,f.migrations);add(f.migrations,'002_fail.sql','CREATE TABLE retry_rows(id INTEGER PRIMARY KEY); INSERT INTO missing_table VALUES(1);');expect(()=>migrateSqlite(f.database,f.migrations)).toThrow(/no such table: missing_table/);const first=backupFiles(f.root);expect(first).toHaveLength(1);expect(readManifests(f.root)[0]).toMatchObject({outcome:'PENDING'});expect(()=>migrateSqlite(f.database,f.migrations)).toThrow(/no such table: missing_table/);expect(backupFiles(f.root)).toEqual(first);});
 it('does not accept an incomplete backup as valid and atomically replaces it on retry',()=>{const f=fixture();migrateSqlite(f.database,f.migrations);add(f.migrations,'002_fail.sql','INSERT INTO missing_table VALUES(1);');expect(()=>migrateSqlite(f.database,f.migrations)).toThrow(/no such table: missing_table/);const backup=backupFiles(f.root).at(0);if(!backup)throw new Error('TEST_BACKUP_MISSING');const path=join(backupDirectory(f.root),backup);writeFileSync(path,'incomplete');expect(()=>migrateSqlite(f.database,f.migrations)).toThrow(/no such table: missing_table/);const verified=new Database(path,{readonly:true,fileMustExist:true});try{expect(verified.pragma('integrity_check',{simple:true})).toBe('ok');}finally{verified.close();}expect(backupFiles(f.root)).toEqual([backup]);});
 it('keeps only the latest successful batch backup while preserving a distinct failed batch',()=>{const f=fixture();migrateSqlite(f.database,f.migrations);add(f.migrations,'002_success.sql','CREATE TABLE success_rows(id INTEGER PRIMARY KEY);');migrateSqlite(f.database,f.migrations);const initialSuccess=backupFiles(f.root);expect(initialSuccess).toHaveLength(1);add(f.migrations,'003_repaired.sql','INSERT INTO missing_table VALUES(1);');expect(()=>migrateSqlite(f.database,f.migrations)).toThrow(/no such table: missing_table/);const failed=backupFiles(f.root);expect(failed).toHaveLength(2);add(f.migrations,'003_repaired.sql','CREATE TABLE repaired_rows(id INTEGER PRIMARY KEY);');add(f.migrations,'004_success.sql','CREATE TABLE later_rows(id INTEGER PRIMARY KEY);');expect(migrateSqlite(f.database,f.migrations).pending).toEqual([]);const retained=backupFiles(f.root);expect(retained).toHaveLength(2);expect(retained).not.toContain(initialSuccess[0]);expect(readManifests(f.root).map(manifest=>manifest.outcome).sort()).toEqual(['PENDING','SUCCESS']);});
});
