import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { describe, expect, it } from 'vitest';
import { migrateSqlite, SqliteLedgerRepository } from '@funi/ledger';

function opened(){const dir=mkdtempSync(join(tmpdir(),'callback-chain-')),path=join(dir,'db.sqlite');migrateSqlite(path,'infra/migrations');const repo=new SqliteLedgerRepository(path);return {repo,close(){repo.close();rmSync(dir,{recursive:true,force:true});}};}
describe('chain-bound callback and journal finality',()=>{
 it('rejects cross-chain callbacks, deployment/preview changes, and replay',()=>{const f=opened();try{f.repo.authorizeChainCallback({authorizationId:'a',userId:'u',chatId:'c',chainId:56,protocol:'pancakeswap_v3',workflowOrPositionId:'7',action:'open',previewRevision:2,deploymentVersion:1,expiresAtMs:200,now:100,idempotencyKey:'once'});expect(()=>f.repo.consumeChainCallback({authorizationId:'a',userId:'u',chatId:'c',chainId:1,protocol:'pancakeswap_v3',workflowOrPositionId:'7',action:'open',previewRevision:2,deploymentVersion:1,now:101})).toThrow('CALLBACK_AUTHORIZATION_INVALID_STALE_OR_REPLAYED');expect(()=>f.repo.consumeChainCallback({authorizationId:'a',userId:'u',chatId:'c',chainId:56,protocol:'pancakeswap_v3',workflowOrPositionId:'7',action:'open',previewRevision:2,deploymentVersion:2,now:101})).toThrow();expect(()=>f.repo.consumeChainCallback({authorizationId:'a',userId:'u',chatId:'c',chainId:56,protocol:'pancakeswap_v3',workflowOrPositionId:'7',action:'open',previewRevision:1,deploymentVersion:1,now:101})).toThrow();expect(f.repo.consumeChainCallback({authorizationId:'a',userId:'u',chatId:'c',chainId:56,protocol:'pancakeswap_v3',workflowOrPositionId:'7',action:'open',previewRevision:2,deploymentVersion:1,now:101})).toBe(true);expect(()=>f.repo.consumeChainCallback({authorizationId:'a',userId:'u',chatId:'c',chainId:56,protocol:'pancakeswap_v3',workflowOrPositionId:'7',action:'open',previewRevision:2,deploymentVersion:1,now:102})).toThrow();}finally{f.close();}});
 it('binds wallet, exposure, and fee revisions and cannot cross into Ethereum or Robinhood',()=>{const f=opened();try{const base={authorizationId:'bound',userId:'u',chatId:'c',chainId:56,protocol:'pancakeswap_v3',workflowOrPositionId:'w',action:'close',previewRevision:3,deploymentVersion:1,walletAddress:'0x0000000000000000000000000000000000000002',exposureRevision:'cap:100:v2',feeEvidenceRevision:'fee:block:10',expiresAtMs:500,now:100,idempotencyKey:'bound-once'};f.repo.authorizeChainCallback(base);for(const patch of [{chainId:1},{chainId:4663},{walletAddress:'0x0000000000000000000000000000000000000003'},{exposureRevision:'cap:101:v3'},{feeEvidenceRevision:'fee:block:11'}])expect(()=>f.repo.consumeChainCallback({...base,...patch,now:101})).toThrow('CALLBACK_AUTHORIZATION_INVALID_STALE_OR_REPLAYED');expect(f.repo.consumeChainCallback({...base,now:101})).toBe(true);}finally{f.close();}});
 it('persists PREPARED before state advancement and makes confirmation receipt truth durable',()=>{const f=opened();try{const row=f.repo.persistChainPreparedTransaction({chainId:56,chainKey:'bsc',protocol:'pancakeswap_v3',journalId:'j',wallet:'0x0000000000000000000000000000000000000002',workflowIdentity:'w',semanticStage:'OPEN',attempt:0,nonce:10,transactionType:'legacy',expectedHash:`0x${'12'.repeat(32)}`,to:'0x0000000000000000000000000000000000000003',requestFingerprint:'fp',feeModel:'legacy',projectedGasNative:100n});expect(row.status).toBe('PREPARED');f.repo.transitionChainTransaction({chainId:56,journalId:'j',from:'PREPARED',to:'SUBMITTED',providerEvidence:{accepted:true}});const confirmed=f.repo.transitionChainTransaction({chainId:56,journalId:'j',from:'SUBMITTED',to:'CONFIRMED',receipt:{status:'success'},confirmationCount:15,actualGasNative:120n});expect(confirmed).toMatchObject({status:'CONFIRMED',confirmation_count:15,actual_gas_native:'120'});expect(()=>f.repo.transitionChainTransaction({chainId:56,journalId:'j',from:'SUBMITTED',to:'FAILED'})).toThrow('CHAIN_JOURNAL_TRANSITION_CONFLICT');}finally{f.close();}});
 it('accounts BOT commitments per chain, excludes external positions, and surfaces missing valuation',()=>{const f=opened();try{const insert=f.repo.db.prepare('INSERT INTO chain_exposure_commitments(chain_id,protocol,workflow_id,provenance,committed_usd,valuation_status,evidence_json) VALUES(?,?,?,?,?,?,?)');insert.run(56,'pancakeswap_v3','same','BOT_OPERATIONAL',100,'AVAILABLE','{}');insert.run(1,'uniswap_v3','same','BOT_OPERATIONAL',200,'AVAILABLE','{}');insert.run(56,'pancakeswap_v3','external','MANUAL_EXTERNAL',999,'AVAILABLE','{}');expect(f.repo.chainBotExposure(56)).toEqual({chainId:56,totalUsd:100,valuationAvailable:true,unavailableCommitments:0});expect(f.repo.chainBotExposure(1)).toEqual({chainId:1,totalUsd:200,valuationAvailable:true,unavailableCommitments:0});insert.run(56,'uniswap_v3','unknown','BOT_OPERATIONAL',null,'UNAVAILABLE','{}');expect(f.repo.chainBotExposure(56)).toEqual({chainId:56,totalUsd:100,valuationAvailable:false,unavailableCommitments:1});}finally{f.close();}});
});
