import { copyFileSync, mkdirSync, mkdtempSync, readdirSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import Database from 'better-sqlite3';
import { describe, expect, it } from 'vitest';
import { migrateSqlite, SqliteLedgerRepository, validateMigrationsOnCopy } from '@funi/ledger';

function fixture(){const dir=mkdtempSync(join(tmpdir(),'funi-multichain-')),path=join(dir,'db.sqlite');return {dir,path,close(){rmSync(dir,{recursive:true,force:true});}};}

describe('migration 034 multi-chain identity',()=>{
 it('creates a fresh schema, is restart-safe, and permits the same asset/position/nonce on three chains',()=>{const f=fixture();try{const first=migrateSqlite(f.path,'infra/migrations');expect(first.applied).toContain('034_multichain_identity.sql');const second=migrateSqlite(f.path,'infra/migrations');expect(second.pending).toEqual([]);const repo=new SqliteLedgerRepository(f.path);try{for(const chainId of [4663,56,1]){repo.db.prepare('INSERT INTO chain_tokens(chain_id,address,symbol,decimals) VALUES(?,?,?,?)').run(chainId,'0x0000000000000000000000000000000000000001','SAME',18);repo.upsertChainPosition({chainId,protocol:'uniswap_v3',positionIdentifier:'7',provenance:'BOT_OPERATIONAL',lifecycleState:'open'});expect(repo.acquireChainNonceMutex(chainId,'0x0000000000000000000000000000000000000002',10n)).toBe(true);}expect(repo.db.prepare('SELECT count(*) count FROM chain_tokens').get()).toEqual({count:3});expect(repo.db.prepare('SELECT count(*) count FROM chain_positions').get()).toEqual({count:3});expect(repo.db.prepare('SELECT count(*) count FROM chain_nonce_mutex').get()).toEqual({count:3});}finally{repo.close();}}finally{f.close();}});
 it('backfills historical FUNI rows to 4663 without rewriting identifiers or receipts',()=>{const f=fixture();try{migrateSqlite(f.path,'infra/migrations');const db=new Database(f.path);try{expect(db.prepare("SELECT sql FROM sqlite_master WHERE type='table' AND name='chain_transaction_journal'").get()).toBeDefined();for(const table of ['positions','v4_positions','transaction_receipts','confirmation_requests']){const columns=db.prepare(`PRAGMA table_info(${table})`).all() as Array<{name:string;dflt_value:string|null}>;expect(columns.some(column=>column.name==='chain_id'&&column.dflt_value==='4663')).toBe(true);}expect(db.prepare("SELECT COUNT(*) count FROM schema_migrations WHERE name='034_multichain_identity.sql'").get()).toEqual({count:1});}finally{db.close();}}finally{f.close();}});
 it('upgrades a pre-034 historical FUNI fixture with identifiers and receipt JSON unchanged',()=>{const f=fixture(),oldMigrations=join(f.dir,'old-migrations');try{mkdirSync(oldMigrations);for(const name of readdirSync('infra/migrations').filter(name=>name.endsWith('.sql')&&name<'034_multichain_identity.sql'))copyFileSync(join('infra/migrations',name),join(oldMigrations,name));migrateSqlite(f.path,oldMigrations);const db=new Database(f.path);try{db.prepare('INSERT INTO positions(id,token_id,pool_address,status,created_at) VALUES(?,?,?,?,?)').run('live:7','7','0xpool','open','2020-01-01');db.prepare('INSERT INTO transaction_intents(id,idempotency_key,state,payload_json,created_at) VALUES(?,?,?,?,?)').run('intent','key','submitted','{}','2020-01-01');db.prepare('INSERT INTO transaction_receipts(tx_hash,intent_id,receipt_json) VALUES(?,?,?)').run('0xreceipt','intent','{"status":"success"}');}finally{db.close();}migrateSqlite(f.path,'infra/migrations');const upgraded=new Database(f.path);try{expect(upgraded.prepare('SELECT id,token_id,chain_id,protocol FROM positions').get()).toEqual({id:'live:7',token_id:'7',chain_id:4663,protocol:'uniswap_v3'});expect(upgraded.prepare('SELECT tx_hash,receipt_json,chain_id FROM transaction_receipts').get()).toEqual({tx_hash:'0xreceipt',receipt_json:'{"status":"success"}',chain_id:4663});expect(upgraded.prepare('SELECT chain_id,protocol,position_identifier,legacy_position_id FROM chain_positions').get()).toEqual({chain_id:4663,protocol:'uniswap_v3',position_identifier:'7',legacy_position_id:'live:7'});}finally{upgraded.close();}}finally{f.close();}});
 it('allows the same expected hash on different chains while rejecting same-chain attribution reuse',()=>{const f=fixture();try{migrateSqlite(f.path,'infra/migrations');const repo=new SqliteLedgerRepository(f.path),base={protocol:'uniswap_v3',wallet:'0x0000000000000000000000000000000000000002',semanticStage:'OPEN',attempt:0,nonce:10,transactionType:'eip1559',expectedHash:`0x${'11'.repeat(32)}`,to:'0x0000000000000000000000000000000000000003',requestFingerprint:'fp',feeModel:'eip1559' as const};try{repo.persistChainPreparedTransaction({...base,chainId:1,chainKey:'ethereum',journalId:'eth',workflowIdentity:'workflow'});repo.persistChainPreparedTransaction({...base,chainId:56,chainKey:'bsc',journalId:'bsc',workflowIdentity:'workflow',feeModel:'legacy'});expect(repo.db.prepare('SELECT count(*) count FROM chain_transaction_journal').get()).toEqual({count:2});expect(()=>repo.persistChainPreparedTransaction({...base,chainId:1,chainKey:'ethereum',journalId:'other',workflowIdentity:'other'})).toThrow();}finally{repo.close();}}finally{f.close();}});
 it('rejects different bytes for the same chain wallet and nonce while allowing the nonce on another chain',()=>{const f=fixture();try{migrateSqlite(f.path,'infra/migrations');const repo=new SqliteLedgerRepository(f.path),base={wallet:'0x0000000000000000000000000000000000000002',semanticStage:'OPEN',attempt:0,nonce:10,transactionType:'legacy',to:'0x0000000000000000000000000000000000000003',requestFingerprint:'fp',feeModel:'legacy' as const};try{repo.persistChainPreparedTransaction({...base,chainId:56,chainKey:'bsc',protocol:'pancakeswap_v3',journalId:'first',workflowIdentity:'first',expectedHash:`0x${'11'.repeat(32)}`});expect(()=>repo.persistChainPreparedTransaction({...base,chainId:56,chainKey:'bsc',protocol:'pancakeswap_v3',journalId:'conflict',workflowIdentity:'conflict',expectedHash:`0x${'22'.repeat(32)}`})).toThrow('CHAIN_JOURNAL_SAME_NONCE_DIFFERENT_TRANSACTION');expect(()=>repo.persistChainPreparedTransaction({...base,chainId:1,chainKey:'ethereum',protocol:'uniswap_v3',journalId:'ethereum',workflowIdentity:'ethereum',expectedHash:`0x${'22'.repeat(32)}`,transactionType:'eip1559',feeModel:'eip1559'})).not.toThrow();}finally{repo.close();}}finally{f.close();}});
 it('validates 034 and guarded-v3 migrations only on a copied historical database',async()=>{const f=fixture();try{const old=join(f.dir,'old');mkdirSync(old);for(const name of readdirSync('infra/migrations').filter(name=>name.endsWith('.sql')&&name<'034_multichain_identity.sql'))copyFileSync(join('infra/migrations',name),join(old,name));migrateSqlite(f.path,old);const before=new Database(f.path);try{before.prepare('INSERT INTO positions(id,token_id,pool_address,status,created_at) VALUES(?,?,?,?,?)').run('live:9','9','pool','open','2020-01-01');}finally{before.close();}const result=await validateMigrationsOnCopy({sourcePath:f.path,copyPath:join(f.dir,'validated.sqlite'),migrationsDir:'infra/migrations'});expect(result).toMatchObject({sourceUnchanged:true,integrity:'ok'});expect(result.migrations).toContain('034_multichain_identity.sql');expect(result.migrations).toContain('035_guarded_v3_lifecycle.sql');const source=new Database(f.path,{readonly:true}),copy=new Database(result.copyPath,{readonly:true});try{expect(()=>source.prepare('SELECT chain_id FROM positions')).toThrow();expect(copy.prepare('SELECT chain_id,protocol FROM positions WHERE token_id=?').get('9')).toEqual({chain_id:4663,protocol:'uniswap_v3'});}finally{source.close();copy.close();}}finally{f.close();}});
});
