import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { describe, expect, it } from 'vitest';
import { FallbackRpc, chainProfile, protocolDeployment } from '@funi/core';
import type { PublicClient } from 'viem';
import { assertRuntimeProviderIdentity, createChainRuntimeContext, verifyDeploymentReadOnly } from '../apps/cli/src/multichain-runtime.js';

const rpc=(chainId:number,reported=chainId)=>new FallbackRpc({chainId,name:`chain-${chainId}`,nativeSymbol:'ETH',rpcUrls:['https://example.invalid'],assets:{}},undefined,{clients:[{getChainId:async()=>reported} as unknown as PublicClient]});
describe('chain runtime isolation',()=>{
 it('rejects a provider reporting the wrong chain with a specific blocker',async()=>{const dir=mkdtempSync(join(tmpdir(),'runtime-context-'));try{const env={ETHEREUM_ENABLED:'true',ETHEREUM_RPC_URLS:'https://example.invalid'},context=createChainRuntimeContext({key:'ethereum',databasePath:join(dir,'eth.sqlite'),env,rpc:rpc(1,56)});await expect(assertRuntimeProviderIdentity(context)).rejects.toThrow('WRONG_CHAIN_PROVIDER:56:1');context.close();}finally{rmSync(dir,{recursive:true,force:true});}});
 it('does not share providers, health state, caches, or repositories',()=>{const dir=mkdtempSync(join(tmpdir(),'runtime-context-'));try{const bsc=createChainRuntimeContext({key:'bsc',databasePath:join(dir,'bsc.sqlite'),env:{BSC_ENABLED:'true',BSC_RPC_URLS:'https://bsc.invalid'},rpc:rpc(56)}),eth=createChainRuntimeContext({key:'ethereum',databasePath:join(dir,'eth.sqlite'),env:{ETHEREUM_ENABLED:'true',ETHEREUM_RPC_URLS:'https://eth.invalid'},rpc:rpc(1)});expect(bsc.rpc).not.toBe(eth.rpc);expect(bsc.tokenMetadataCache).not.toBe(eth.tokenMetadataCache);bsc.tokenMetadataCache.set('same-address',{symbol:'BNB-side'});expect(eth.tokenMetadataCache.has('same-address')).toBe(false);expect(bsc.repository.path).not.toBe(eth.repository.path);expect(bsc.profile).toBe(chainProfile(56));bsc.close();eth.close();}finally{rmSync(dir,{recursive:true,force:true});}});
 it('requires Pancake position manager, known-pool, wrapped-native, and pool-deployer evidence',async()=>{const deployment=protocolDeployment(56,'pancakeswap_v3'),pool='0x00000000000000000000000000000000000000aa' as const,token0=chainProfile(56).quoteTokens[0]!.address,token1=chainProfile(56).wrappedNativeAddress,client=(wrongDeployer=false)=>({getChainId:async()=>56,getBytecode:async()=> '0x01' as const,getBlock:async()=>({number:100n,timestamp:1_700_000_000n,baseFeePerGas:null}),readContract:async({address,functionName,args}:{address:string;functionName:string;args?:readonly unknown[]})=>functionName==='getPool'?args?.[2]===500?pool:'0x0000000000000000000000000000000000000000':functionName==='feeAmountTickSpacing'?10:functionName==='decimals'?18:functionName==='factory'?address.toLowerCase()===pool.toLowerCase()?deployment.contracts.factory:deployment.contracts.factory:functionName==='WETH9'?deployment.contracts.wrappedNative:functionName==='deployer'?wrongDeployer?'0x0000000000000000000000000000000000000001':deployment.contracts.poolDeployer:functionName==='token0'?token0:functionName==='token1'?token1:functionName==='fee'?500:functionName==='tickSpacing'?10:functionName==='slot0'?[1n,0,0,0,0,0,true]:functionName==='liquidity'?1n:undefined});const selected=(value:ReturnType<typeof client>)=>new FallbackRpc({chainId:56,name:'BSC',nativeSymbol:'BNB',rpcUrls:['https://example.invalid'],assets:{}},undefined,{clients:[value as unknown as PublicClient]});await expect(verifyDeploymentReadOnly({profile:chainProfile(56),rpc:selected(client())},'pancakeswap_v3')).resolves.toMatchObject({status:'VERIFIED',executionSupported:true});await expect(verifyDeploymentReadOnly({profile:chainProfile(56),rpc:selected(client(true))},'pancakeswap_v3')).resolves.toMatchObject({status:'UNVERIFIED',executionSupported:false});});
});
