import { encodeAbiParameters, keccak256, toFunctionSelector, toHex, type Address, type StateOverride } from 'viem';
import { describe, expect, it } from 'vitest';
import { FallbackRpc, chainProfile, eip1559FeeQuote, legacyFeeQuote, protocolDeployment } from '@funi/core';
import { GAS_CALIBRATION_ACCOUNT, bindCalibrationProvider, calibrateGuardedV3OpenGas, calibrationProviderRpc, calibrationStateOverride, deriveCalibrationRange, deriveRepresentativeAmounts, deriveWethOnlyCalibrationRange, type CalibrationProviderProvenance, type CalibrationSource } from '../apps/cli/src/open-gas-calibration.js';
import type { CanonicalDeploymentVerificationEvidence } from '../apps/cli/src/multichain-runtime.js';

const pool='0x0000000000000000000000000000000000000010' as const,Q96=2n**96n;
function evidence(chainId:1|56,protocol:'uniswap_v3'|'pancakeswap_v3',providerRevision:`0x${string}`):CanonicalDeploymentVerificationEvidence{return {chainId,protocol,deploymentVersion:protocolDeployment(chainId,protocol).registryVersion,deploymentRegistryRevision:`0x${'1'.repeat(64)}`,providerSetRevision:providerRevision,verifiedBlock:100n,verifiedAtMs:100,validUntilMs:1_000,status:'VERIFIED',evidenceRevision:`0x${'3'.repeat(64)}`,requiredContractCodeHashes:{},requiredRelationshipHash:`0x${'4'.repeat(64)}`,providerCount:1,source:'RUNTIME_VERIFIED'};}
function fixture(chainId:1|56){
 const protocol=chainId===56?'pancakeswap_v3' as const:'uniswap_v3' as const,profile=chainProfile(chainId),deployment=protocolDeployment(chainId,protocol),stable=profile.quoteTokens.find(token=>token.stable)!,ordered=[stable.address,profile.wrappedNativeAddress].sort((a,b)=>BigInt(a)<BigInt(b)?-1:1) as [Address,Address],gasRequests:Array<Record<string,unknown>>=[],callRequests:Array<Record<string,unknown>>=[];let stateOverrideFactoryCalls=0;
 const client={getChainId:async()=>chainId,getBlockNumber:async()=>100n,getBlock:async()=>({number:100n,timestamp:1_000n,baseFeePerGas:10n}),getBytecode:async()=> '0x6000',readContract:async({address,functionName}:any)=>{if(address.toLowerCase()===pool.toLowerCase()){if(functionName==='factory')return deployment.contracts.factory;if(functionName==='token0')return ordered[0];if(functionName==='token1')return ordered[1];if(functionName==='fee')return 500;if(functionName==='tickSpacing')return 10;if(functionName==='liquidity')return 1_000_000n;if(functionName==='slot0')return [Q96,0,0,0,0,0,true];}if(functionName==='decimals')return address.toLowerCase()===stable.address.toLowerCase()?stable.decimals:18;if(functionName==='symbol')return address.toLowerCase()===stable.address.toLowerCase()?stable.symbol:profile.nativeSymbol;if(functionName==='name')return 'calibration token';if(functionName==='totalSupply')return 10n**30n;throw new Error(`unexpected:${functionName}`);},estimateGas:async(request:Record<string,unknown>)=>{gasRequests.push(request);return chainId===1?200_000n:gasRequests.length===1?50_000n:200_000n;},call:async(request:Record<string,unknown>)=>{callRequests.push(request);return {data:'0x'};}} as any,rpc=new FallbackRpc({chainId,name:profile.displayName,nativeSymbol:profile.nativeSymbol,rpcUrls:['https://provider.invalid'],assets:{}},undefined,{clients:[client]}),providerSetRevision=`0x${'2'.repeat(64)}` as const,providerProvenance:CalibrationProviderProvenance={requestedChainAlias:chainId===56?'bsc':'ethereum',expectedChainId:chainId,observedChainId:chainId,providerSourceKey:chainId===56?'BSC_RPC_URLS':'ETHEREUM_RPC_URLS',providerIndex:0,providerSetRevision,calibrationSource:'DIRECT_RPC'},stateOverrideFactory=async({token,tokenAmount,nativeAmount}:any)=>{stateOverrideFactoryCalls++;return {stateOverride:[{address:GAS_CALIBRATION_ACCOUNT,balance:nativeAmount+10n**18n},{address:token,stateDiff:[{slot:`0x${'0'.repeat(64)}`,value:toHex(tokenAmount,{size:32})}]}] as StateOverride,evidenceRevision:`0x${'5'.repeat(64)}`};};return {protocol,profile,stable,rpc,gasRequests,callRequests,providerSetRevision,providerProvenance,stateOverrideFactory,stateOverrideFactoryCalls:()=>stateOverrideFactoryCalls};
}
function calibrationInput(chainId:1|56,source:CalibrationSource='DIRECT_RPC'){
 const f=fixture(chainId),providerProvenance:CalibrationProviderProvenance={...f.providerProvenance,calibrationSource:source,...(source==='ANVIL_FORK'?{forkChainId:chainId}:{})};return {f,input:{rpc:f.rpc,chainId,protocol:f.protocol,poolAddress:pool,deploymentEvidence:evidence(chainId,f.protocol,f.providerSetRevision),feeQuote:chainId===56?legacyFeeQuote({gasPrice:3n,observedAtMs:100}):eip1559FeeQuote({baseFeePerGas:10n,maxPriorityFeePerGas:2n,observedAtMs:100}),feeEvidenceRevision:'fee',feeEvidenceMaxAgeMs:100,walletEvidenceRevision:'wallet',currentWalletNativeBalance:chainId===56?1n:0n,nativeUsd:chainId===56?500:2_000,nowMs:100,providerProvenance,stateOverrideFactory:f.stateOverrideFactory as any}};
}

describe('deterministic guarded-v3 OPEN gas calibration',()=>{
 it('keeps BSC calibration successful with bound BSC provenance',async()=>{const {f,input}=calibrationInput(56),result=await calibrateGuardedV3OpenGas(input);expect(result).toMatchObject({status:'GAS_CALIBRATION_VERIFIED',chain:'bsc',providerProvenance:{requestedChainAlias:'bsc',expectedChainId:56,observedChainId:56,providerSourceKey:'BSC_RPC_URLS',providerIndex:0,calibrationSource:'DIRECT_RPC'},productionWalletCapitalUsed:false,executionReady:false});expect(result.parameterDerivation.tickLower).toBeLessThan(0);expect(result.parameterDerivation.tickUpper).toBeGreaterThan(0);expect(result.gasStages.map(stage=>stage.stage)).toEqual(['STABLE_TOKEN_APPROVAL','NATIVE_WRAP_AND_MINT']);expect(result.gasStages.map(stage=>stage.estimatedGas)).toEqual([50_000n,200_000n]);expect(result.projectedLifecycleGas).toMatchObject({high:250_000n,bufferedHigh:300_000n});expect(result.gasFunding.fundingDeficit).toBe(899_999n);expect(f.gasRequests).toHaveLength(2);expect(f.stateOverrideFactoryCalls()).toBe(1);});

 it('uses a below-current WETH-only payable Ethereum multicall without probing or overriding USDC',async()=>{const {f,input}=calibrationInput(1),result=await calibrateGuardedV3OpenGas(input);expect(result).toMatchObject({status:'GAS_CALIBRATION_VERIFIED',actionableOpenStatus:'ACTIONABLE_OPEN_NOT_CONFIGURED',chain:'ethereum',providerProvenance:{expectedChainId:1,observedChainId:1,providerSourceKey:'ETHEREUM_RPC_URLS',calibrationSource:'DIRECT_RPC'},calibrationFundingSource:'NATIVE_BALANCE_STATE_OVERRIDE',productionWalletCapitalUsed:false,calibrationParametersPromotableToExecution:false,executionReady:false,signerConstructed:false,nonceReserved:false,journalWritten:false,authorizationCreated:false,signingUsed:false,broadcastUsed:false});expect(result.parameterDerivation).toMatchObject({token0:{decimals:6,representativeAmountNonZero:false},token1:{decimals:18,representativeAmountNonZero:true},approvalRequirement:'NOT_APPLICABLE_USDC_AMOUNT_ZERO'});expect(result.parameterDerivation.tickLower).toBeLessThan(result.parameterDerivation.tickUpper);expect(result.parameterDerivation.tickUpper).toBeLessThan(result.parameterDerivation.currentTick);expect(result.parameterDerivation.tickLower%result.parameterDerivation.tickSpacing===0).toBe(true);expect(result.parameterDerivation.tickUpper%result.parameterDerivation.tickSpacing===0).toBe(true);expect(result.gasStages.map(stage=>stage.stage)).toEqual(['NATIVE_ETH_WETH_MINT_MULTICALL']);expect(result.gasStages[0]!.estimatedGas).toBe(200_000n);expect(result.projectedLifecycleGas).toMatchObject({high:200_000n,bufferedHigh:240_000n});expect(result.maxFeePerGasUsed).toBe(22n);expect(result.gasFunding).toMatchObject({currentNativeBalance:0n,safetyBufferedNativeRequirementHigh:5_280_000n,fundingDeficit:5_280_000n});expect(result.gasFunding.fundingDeficitUsd).toBeGreaterThan(0);expect(f.stateOverrideFactoryCalls()).toBe(0);expect(f.gasRequests).toHaveLength(1);expect(f.gasRequests[0]!.to).toBe(protocolDeployment(1,'uniswap_v3').contracts.positionManager);expect(f.gasRequests[0]!.value).toBeGreaterThan(0n);expect(String(f.gasRequests[0]!.data).slice(0,10)).toBe(toFunctionSelector('multicall(bytes[])'));expect(f.gasRequests[0]!.stateOverride).toEqual([{address:GAS_CALIBRATION_ACCOUNT,balance:expect.any(BigInt)}]);});

 it('uses only Anvil native balance funding on the fork path',async()=>{const {f,input}=calibrationInput(1,'ANVIL_FORK'),result=await calibrateGuardedV3OpenGas(input);expect(result.providerProvenance).toMatchObject({calibrationSource:'ANVIL_FORK',forkChainId:1});expect(result.calibrationFundingSource).toBe('ANVIL_SET_BALANCE');expect(f.stateOverrideFactoryCalls()).toBe(0);expect(f.gasRequests).toHaveLength(1);expect(f.gasRequests[0]).not.toHaveProperty('stateOverride');expect(f.gasRequests[0]!.value).toBeGreaterThan(0n);});

 it('derives strict usable ticks for both enclosing and WETH-only calibration',()=>{expect(deriveCalibrationRange(0,10)).toMatchObject({tickLower:-10,tickUpper:10});expect(deriveCalibrationRange(-1,10)).toMatchObject({tickLower:-10,tickUpper:0});expect(deriveWethOnlyCalibrationRange(0,10)).toMatchObject({tickLower:-20,tickUpper:-10});expect(()=>deriveCalibrationRange(-887272,1)).toThrow('GAS_CALIBRATION_CURRENT_TICK_AT_PROTOCOL_BOUNDARY');});

 it('derives balanced non-zero BSC representative amounts without a notional decision',()=>{const range=deriveCalibrationRange(0,10),amounts=deriveRepresentativeAmounts({sqrtPriceX96:Q96,tickLower:range.tickLower,tickUpper:range.tickUpper,token0Decimals:18,token1Decimals:6});expect(amounts.amount0Desired).toBeGreaterThan(0n);expect(amounts.amount1Desired).toBeGreaterThan(0n);expect(amounts.amount0Min).toBe(0n);expect(amounts.amount1Min).toBe(0n);});

 it('retains bounded generic balance and allowance slot discovery only for BSC calibration',async()=>{const token='0x0000000000000000000000000000000000000020' as const,spender='0x0000000000000000000000000000000000000030' as const,balanceIndex=2,allowanceIndex=3,balanceKey=keccak256(encodeAbiParameters([{type:'address'},{type:'uint256'}],[GAS_CALIBRATION_ACCOUNT,BigInt(balanceIndex)])),outer=keccak256(encodeAbiParameters([{type:'address'},{type:'uint256'}],[GAS_CALIBRATION_ACCOUNT,BigInt(allowanceIndex)])),allowanceKey=keccak256(encodeAbiParameters([{type:'address'},{type:'bytes32'}],[spender,outer])),client={readContract:async({functionName,stateOverride}:any)=>{const change=stateOverride[0].stateDiff[0];return change.slot===(functionName==='balanceOf'?balanceKey:allowanceKey)?BigInt(change.value):0n;}} as any,result=await calibrationStateOverride({client,token,spender,tokenAmount:100n,nativeAmount:200n});expect(result.stateOverride).toHaveLength(2);expect(result.evidenceRevision).toMatch(/^0x/);});

 it.each([['bsc',56,'BSC_RPC_URLS'],['ethereum',1,'ETHEREUM_RPC_URLS']] as const)('binds %s only to its own configuration source and observed chain',async(requestedChainAlias,chainId,providerSourceKey)=>{const calls:number[]=[] as number[],client={getChainId:async()=>{calls.push(chainId);return chainId;}} as any,rpc=new FallbackRpc({chainId,name:requestedChainAlias,nativeSymbol:chainId===56?'BNB':'ETH',rpcUrls:['https://provider.invalid'],assets:{}},undefined,{clients:[client]}),bound=await bindCalibrationProvider({requestedChainAlias,providerSourceKey,rpc});expect(bound.provenance).toMatchObject({requestedChainAlias,expectedChainId:chainId,observedChainId:chainId,providerSourceKey,providerIndex:0,calibrationSource:'DIRECT_RPC'});expect(calls).toEqual([chainId]);expect(JSON.stringify(bound.provenance)).not.toContain('https://');});

 it.each([['bsc','BSC_RPC_URLS','https://bsc.invalid'],['ethereum','ETHEREUM_RPC_URLS','https://ethereum.invalid']] as const)('loads %s calibration providers exclusively from %s',(requestedChainAlias,expectedKey,expectedUrl)=>{const otherKey=requestedChainAlias==='bsc'?'ETHEREUM_RPC_URLS':'BSC_RPC_URLS',configured=calibrationProviderRpc(requestedChainAlias,{[expectedKey]:expectedUrl,[otherKey]:'https://wrong-chain.invalid'});expect(configured.providerSourceKey).toBe(expectedKey);expect(configured.rpc.config.rpcUrls).toEqual([expectedUrl]);});

 it('rejects a wrong configuration source before touching a provider',async()=>{let calls=0;const client={getChainId:async()=>{calls++;return 1;}} as any,rpc=new FallbackRpc({chainId:1,name:'Ethereum',nativeSymbol:'ETH',rpcUrls:['https://provider.invalid'],assets:{}},undefined,{clients:[client]});await expect(bindCalibrationProvider({requestedChainAlias:'ethereum',providerSourceKey:'BSC_RPC_URLS',rpc})).rejects.toThrow('GAS_CALIBRATION_PROVIDER_SOURCE_MISMATCH:ETHEREUM_RPC_URLS');expect(calls).toBe(0);});

 it('rejects a provider whose observed chain differs from the requested chain',async()=>{const client={getChainId:async()=>1} as any,rpc=new FallbackRpc({chainId:56,name:'BSC',nativeSymbol:'BNB',rpcUrls:['https://provider.invalid'],assets:{}},undefined,{clients:[client]});await expect(bindCalibrationProvider({requestedChainAlias:'bsc',providerSourceKey:'BSC_RPC_URLS',rpc})).rejects.toThrow('GAS_CALIBRATION_PROVIDER_CHAIN_MISMATCH:0:1:56');});

 it('cannot render or execute calibration with mislabeled provenance',async()=>{const {input}=calibrationInput(56);await expect(calibrateGuardedV3OpenGas({...input,providerProvenance:{...input.providerProvenance,providerSourceKey:'ETHEREUM_RPC_URLS'}})).rejects.toThrow('GAS_CALIBRATION_PROVIDER_PROVENANCE_INVALID');});

 it('keeps BSC and Ethereum deployment evidence isolated',async()=>{const {input}=calibrationInput(56);await expect(calibrateGuardedV3OpenGas({...input,deploymentEvidence:evidence(1,'uniswap_v3',input.providerProvenance.providerSetRevision)})).rejects.toThrow('GAS_CALIBRATION_DEPLOYMENT_EVIDENCE_INVALID');});
});
