import { describe, expect, it } from 'vitest';
import { eip1559FeeQuote, legacyFeeQuote } from '@funi/core';
import { buildEmergencyExitTransactions, buildOperationalGasFloorResult, operationalForkSource, type OperationalGasStage } from '../apps/cli/src/operational-gas-floor.js';
import type { CalibrationProviderProvenance } from '../apps/cli/src/open-gas-calibration.js';

const wallet='0x0000000000000000000000000000000000000008' as const;
const provenance=(chainId:1|56):CalibrationProviderProvenance=>({requestedChainAlias:chainId===56?'bsc':'ethereum',expectedChainId:chainId,observedChainId:chainId,providerSourceKey:chainId===56?'BSC_RPC_URLS':'ETHEREUM_RPC_URLS',providerIndex:0,providerSetRevision:`0x${'1'.repeat(64)}`,calibrationSource:'DIRECT_RPC'});
const stage=(phase:'OPEN'|'EMERGENCY_FULL_EXIT',name:string,action:string,gas:bigint):OperationalGasStage=>({phase,stage:name,transactionAction:action,estimatedGas:gas,bufferedGas:(gas*12n+9n)/10n,actualGasUsed:gas-1n,receiptStatus:'SUCCESS',receiptBlock:100n,destinationVerified:true,selectorVerified:true,valueVerified:true,successfulForkSimulationReceipt:true});
const bscStages=()=>[stage('OPEN','STABLE_TOKEN_APPROVAL','approval',100n),stage('OPEN','NATIVE_WRAP_AND_MINT','mint',200n),stage('EMERGENCY_FULL_EXIT','FULL_CLOSE_DECREASE','full_close',300n),stage('EMERGENCY_FULL_EXIT','COLLECT','collect',400n),stage('EMERGENCY_FULL_EXIT','BURN','burn',500n)];
const ethereumStages=()=>[stage('OPEN','NATIVE_ETH_WETH_MINT_MULTICALL','mint',200n),stage('EMERGENCY_FULL_EXIT','FULL_CLOSE_DECREASE','full_close',300n),stage('EMERGENCY_FULL_EXIT','COLLECT','collect',400n),stage('EMERGENCY_FULL_EXIT','BURN','burn',500n)];

describe('deterministic guarded-v3 operational gas floor',()=>{
 it('aggregates one BSC synthetic OPEN and one complete exit with exact balance subtraction',()=>{const result=buildOperationalGasFloorResult({chainId:56,protocol:'pancakeswap_v3',stages:bscStages(),feeQuote:legacyFeeQuote({gasPrice:50n,observedAtMs:100}),feeEvidenceRevision:'fee-bsc',feeEvidenceMaxAgeMs:100,currentProductionNativeBalance:80_000n,nativeUsd:500,providerProvenance:provenance(56),forkSourceKey:'BSC_FORK_RPC_URL',forkBlock:100n,deploymentEvidenceRevision:'deployment-bsc',nowMs:100});expect(result).toMatchObject({status:'OPERATIONAL_GAS_FLOOR_VERIFIED',openStatus:'OPEN_GAS_CALIBRATION_VERIFIED',emergencyExitStatus:'EMERGENCY_EXIT_GAS_CALIBRATION_VERIFIED',actionableOpenStatus:'ACTIONABLE_OPEN_NOT_CONFIGURED',liveExecutionStatus:'LIVE_EXECUTION_DISABLED',chain:'bsc',budgets:{OPEN:{rawGas:300n,bufferedGas:360n,bufferedNative:18_000n},EMERGENCY_FULL_EXIT:{rawGas:1_200n,bufferedGas:1_440n,bufferedNative:72_000n},TOTAL_OPERATIONAL_FLOOR:{rawGas:1_500n,bufferedGas:1_800n,bufferedNative:90_000n,currentProductionNativeBalance:80_000n,operationalFundingDeficit:10_000n}},provenance:{forkSourceKey:'BSC_FORK_RPC_URL',forkChainId:56,forkBlock:100n},reportConsistency:{stageGasSum:1_500n,lifecycleGas:1_500n,bufferedStageGasSum:1_800n,bufferedLifecycleGas:1_800n,nativeEqualsBufferedGasTimesFee:true,deficitArithmeticExact:true},executionReady:false,productionWalletCapitalUsed:false,forkOnlySigningUsed:true});});

 it('aggregates Ethereum WETH-only OPEN plus exit and produces a positive zero-balance deficit',()=>{const result=buildOperationalGasFloorResult({chainId:1,protocol:'uniswap_v3',stages:ethereumStages(),feeQuote:eip1559FeeQuote({baseFeePerGas:10n,maxPriorityFeePerGas:2n,observedAtMs:100}),feeEvidenceRevision:'fee-eth',feeEvidenceMaxAgeMs:100,currentProductionNativeBalance:0n,nativeUsd:2_000,providerProvenance:provenance(1),forkSourceKey:'ETHEREUM_RPC_URLS',forkBlock:100n,deploymentEvidenceRevision:'deployment-eth',nowMs:100});expect(result.budgets.OPEN).toMatchObject({rawGas:200n,bufferedGas:240n,bufferedNative:5_280n});expect(result.budgets.EMERGENCY_FULL_EXIT).toMatchObject({rawGas:1_200n,bufferedGas:1_440n,bufferedNative:31_680n});expect(result.budgets.TOTAL_OPERATIONAL_FLOOR).toMatchObject({bufferedGas:1_680n,bufferedNative:36_960n,operationalFundingDeficit:36_960n});expect(result.stages.filter(item=>item.phase==='OPEN').map(item=>item.stage)).toEqual(['NATIVE_ETH_WETH_MINT_MULTICALL']);});

 it.each([[56,'pancakeswap_v3'],[1,'uniswap_v3']] as const)('constructs chain %s emergency decrease, collect, and burn exactly once without replacement',(chainId,protocol)=>{const transactions=buildEmergencyExitTransactions({chainId,protocol,tokenId:7n,liquidity:10n,recipient:wallet,deadline:200n,nowUnix:100n});expect(transactions.map(item=>item.stage)).toEqual(['FULL_CLOSE_DECREASE','COLLECT','BURN']);expect(transactions.map(item=>item.transaction.action)).toEqual(['full_close','collect','burn']);expect(transactions.filter(item=>item.transaction.action==='mint'||item.transaction.action==='approval')).toHaveLength(0);expect(new Set(transactions.map(item=>item.stage)).size).toBe(3);});

 it('rejects contradictory buffered stage totals instead of rendering inconsistent numbers',()=>{const stages=bscStages();stages[0]={...stages[0]!,bufferedGas:119n};expect(()=>buildOperationalGasFloorResult({chainId:56,protocol:'pancakeswap_v3',stages,feeQuote:legacyFeeQuote({gasPrice:50n,observedAtMs:100}),feeEvidenceRevision:'fee',feeEvidenceMaxAgeMs:100,currentProductionNativeBalance:0n,providerProvenance:provenance(56),forkSourceKey:'BSC_RPC_URLS',forkBlock:100n,deploymentEvidenceRevision:'deployment',nowMs:100})).toThrow('OPERATIONAL_GAS_FLOOR_STAGE_EVIDENCE_INVALID');});

 it('rejects a duplicate exit stage or replacement mint',()=>{const duplicate=[...bscStages(),stage('EMERGENCY_FULL_EXIT','BURN','burn',10n)];expect(()=>buildOperationalGasFloorResult({chainId:56,protocol:'pancakeswap_v3',stages:duplicate,feeQuote:legacyFeeQuote({gasPrice:50n,observedAtMs:100}),feeEvidenceRevision:'fee',feeEvidenceMaxAgeMs:100,currentProductionNativeBalance:0n,providerProvenance:provenance(56),forkSourceKey:'BSC_RPC_URLS',forkBlock:100n,deploymentEvidenceRevision:'deployment',nowMs:100})).toThrow();const replacement=ethereumStages();replacement[3]={...replacement[3]!,transactionAction:'mint'};expect(()=>buildOperationalGasFloorResult({chainId:1,protocol:'uniswap_v3',stages:replacement,feeQuote:eip1559FeeQuote({baseFeePerGas:10n,maxPriorityFeePerGas:2n,observedAtMs:100}),feeEvidenceRevision:'fee',feeEvidenceMaxAgeMs:100,currentProductionNativeBalance:0n,providerProvenance:provenance(1),forkSourceKey:'ETHEREUM_RPC_URLS',forkBlock:100n,deploymentEvidenceRevision:'deployment',nowMs:100})).toThrow('OPERATIONAL_GAS_FLOOR_EXIT_SCOPE_INVALID');});

 it('keeps fork source selection chain-scoped and never returns the other chain source',()=>{expect(operationalForkSource({chain:'bsc',directProviderUrl:'https://bsc.invalid',env:{BSC_FORK_RPC_URL:'https://bsc-fork.invalid',ETHEREUM_FORK_RPC_URL:'https://wrong.invalid'}})).toEqual({forkUrl:'https://bsc-fork.invalid',forkSourceKey:'BSC_FORK_RPC_URL'});expect(operationalForkSource({chain:'ethereum',directProviderUrl:'https://eth.invalid',env:{BSC_FORK_RPC_URL:'https://wrong.invalid'}})).toEqual({forkUrl:'https://eth.invalid',forkSourceKey:'ETHEREUM_RPC_URLS'});});

 it('rejects cross-chain provider and fork provenance before rendering',()=>{expect(()=>buildOperationalGasFloorResult({chainId:56,protocol:'pancakeswap_v3',stages:bscStages(),feeQuote:legacyFeeQuote({gasPrice:50n,observedAtMs:100}),feeEvidenceRevision:'fee',feeEvidenceMaxAgeMs:100,currentProductionNativeBalance:0n,providerProvenance:provenance(1),forkSourceKey:'ETHEREUM_FORK_RPC_URL',forkBlock:100n,deploymentEvidenceRevision:'deployment',nowMs:100})).toThrow('OPERATIONAL_GAS_FLOOR_REPORT_PROVENANCE_INVALID');});

 it('reports every production safety invariant false while classifying local signing as fork-only',()=>{const result=buildOperationalGasFloorResult({chainId:1,protocol:'uniswap_v3',stages:ethereumStages(),feeQuote:eip1559FeeQuote({baseFeePerGas:10n,maxPriorityFeePerGas:2n,observedAtMs:100}),feeEvidenceRevision:'fee',feeEvidenceMaxAgeMs:100,currentProductionNativeBalance:0n,providerProvenance:provenance(1),forkSourceKey:'ETHEREUM_FORK_RPC_URL',forkBlock:100n,deploymentEvidenceRevision:'deployment',nowMs:100});expect(result).toMatchObject({signerConstructed:false,productionNonceReserved:false,productionJournalWritten:false,authorizationCreated:false,signingUsed:false,mainnetBroadcastUsed:false,executionReady:false,calibrationParametersPromotableToExecution:false,productionWalletCapitalUsed:false,forkOnlySigningUsed:true});});
});
