import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { afterEach, describe, expect, it, vi } from "vitest";
import { migrateSqlite, SqliteLedgerRepository } from "@funi/ledger";
import { drainClosePnlCardDeliveries } from "../apps/telegram-lp-bot/src/pnl-card-delivery.js";

const T0=1_800_000_000_000;
function fixture(){const dir=mkdtempSync(join(tmpdir(),"funi-pnl-delivery-")),path=join(dir,"ledger.sqlite");migrateSqlite(path,"infra/migrations");const open=()=>new SqliteLedgerRepository(path);return {dir,path,open};}
function appendClose(repo:SqliteLedgerRepository,id:string,ladder=id,finalAt=T0,pair=id){repo.appendRealizedPnlEvent({eventId:id,eventKind:"CLOSE",protocol:"v4",strategyType:"V4_BID_LADDER",ladderIdentity:ladder,workflowIdentity:ladder,journalStage:"CLOSE_BATCH",transactionHash:`0x${id.charCodeAt(0).toString(16).padStart(2,"0").repeat(32)}`,blockNumber:1n,economicFinalAtMs:finalAt,capitalBasisUsd:"100",realizedPnlUsd:"12.5",valuationStatus:"AVAILABLE",valuationEvidence:{source:"fixture"},closeReason:"NORMAL_OPERATOR_CLOSE",presentationMetadata:{pair:`${pair}/USDG`,strategy:"V4 BID LADDER",mode:"LIVE",openedAt:new Date(finalAt-3_600_000).toISOString(),returnedValueUsd:"112.5"}});}
function ensure(repo:SqliteLedgerRepository,id:string,chat="chat"){return repo.ensurePnlCardDelivery({deliveryId:`close:${id}:${chat}`,cardKind:"CLOSE",economicEventId:id,chatIdentity:chat,metadata:{automatic:true}});}
function sender(onSend?:()=>{delivered:boolean;messageId:number|null;retryable?:boolean;failureCode?:string}){let sends=0;return {sendPhoto:async()=>{sends++;return onSend?.()??{delivered:true,messageId:sends};},sendMessage:async()=>{sends++;return onSend?.()??{delivered:true,messageId:sends};},count:()=>sends};}
afterEach(()=>vi.useRealTimers());

describe("event-driven Position Closed delivery",()=>{
  it("uses a date-only, identifier-free public caption while retaining canonical event data",async()=>{const f=fixture();try{const db=f.open();appendClose(db,"privacy","v4bid_private_ladder",Date.parse("2026-08-29T03:37:00.000Z"),"VERONA");ensure(db,"privacy");const before=db.db.prepare("SELECT event_id,transaction_hash,ladder_identity FROM realized_pnl_events WHERE event_id='privacy'").get() as Record<string,string>;db.close();const captions:string[]=[];await drainClosePnlCardDeliveries({openRepository:f.open,sendPhoto:async(_png,caption)=>{captions.push(caption);return {delivered:true,messageId:1};},sendMessage:async(caption)=>{captions.push(caption);return {delivered:true,messageId:1};},consumerSource:"TELEGRAM_EVENT_DRIVEN"});const caption=captions[0]!;expect(caption).toBe("FUNI · POSITION CLOSED\nVERONA/USDG\nClosed: 29 Aug 2026 · WIB\nCoverage: FULL");for(const forbidden of ["Tx:","Event:","v4bid_","0x","privacy",before.transaction_hash,before.event_id,"03:37"])expect(caption).not.toContain(forbidden);const verify=f.open();expect(verify.db.prepare("SELECT event_id,transaction_hash,ladder_identity FROM realized_pnl_events WHERE event_id='privacy'").get()).toEqual(before);verify.close();}finally{rmSync(f.dir,{recursive:true,force:true});}});

  it("keeps FULL, PARTIAL, and INCOMPLETE coverage truthful in public captions",async()=>{const f=fixture();try{const db=f.open();appendClose(db,"full");ensure(db,"full");appendClose(db,"partial");db.appendRealizedPnlEvent({eventId:"partial-claim",eventKind:"CLAIM",protocol:"v4",strategyType:"V4_BID_LADDER",ladderIdentity:"partial",workflowIdentity:"partial",journalStage:"COLLECT_BATCH",transactionHash:"0x"+"1".repeat(64),blockNumber:1n,economicFinalAtMs:T0-1,valuationStatus:"INCOMPLETE",valuationEvidence:{reason:"fixture"}});ensure(db,"partial");appendClose(db,"incomplete");db.db.prepare("UPDATE realized_pnl_events SET valuation_status='INCOMPLETE' WHERE event_id='incomplete'").run();ensure(db,"incomplete");db.close();const captions:string[]=[];await drainClosePnlCardDeliveries({openRepository:f.open,sendPhoto:async(_png,caption)=>{captions.push(caption);return {delivered:true,messageId:1};},sendMessage:async(caption)=>{captions.push(caption);return {delivered:true,messageId:1};},consumerSource:"TELEGRAM_EVENT_DRIVEN",limit:3});for(const [pair,coverage] of [["full/USDG","FULL"],["partial/USDG","PARTIAL"],["incomplete/USDG","INCOMPLETE"]])expect(captions).toContain(`FUNI · POSITION CLOSED\n${pair}\nClosed: 15 Jan 2027 · WIB\nCoverage: ${coverage}`);}finally{rmSync(f.dir,{recursive:true,force:true});}});

  it("persists at T0+2s, claims on the 250ms consumer path, and delivers below both latency bounds",async()=>{const f=fixture();try{const closeConfirmedAt=Date.now()-2_000,db=f.open();appendClose(db,"latency","latency",closeConfirmedAt);ensure(db,"latency");ensure(db,"latency");db.close();const sent=sender(),telemetry:Record<string,unknown>[]=[];const cycle=await drainClosePnlCardDeliveries({openRepository:f.open,sendPhoto:sent.sendPhoto,sendMessage:sent.sendMessage,consumerSource:"TELEGRAM_EVENT_DRIVEN",telemetry:(_event,details)=>telemetry.push(details)});expect(cycle.claimed).toBe(1);expect(sent.count()).toBe(1);expect(Number(telemetry[0]!.totalCloseToDeliveredMs)).toBeLessThan(10_000);expect(Number(telemetry[0]!.totalCloseToDeliveredMs)).toBeLessThan(30_000);expect(Number(telemetry[0]!.accountingReadyToClaimMs)).toBeGreaterThanOrEqual(0);expect(telemetry[0]).toMatchObject({economicEventId:"latency",consumerSource:"TELEGRAM_EVENT_DRIVEN",sla:"PASS",attempt:1});const verify=f.open();expect(verify.db.prepare("SELECT COUNT(*) count FROM pnl_card_deliveries WHERE economic_event_id='latency'").get()).toEqual({count:1});expect(verify.db.prepare("SELECT delivery_status,telegram_message_id FROM pnl_card_deliveries WHERE economic_event_id='latency'").get()).toEqual({delivery_status:"DELIVERED",telegram_message_id:"1"});verify.close();}finally{rmSync(f.dir,{recursive:true,force:true});}});

  it("allows exactly one atomic winner when Telegram and reconcile race",async()=>{const f=fixture();try{vi.useFakeTimers();vi.setSystemTime(T0+2_000);const db=f.open();appendClose(db,"race");ensure(db,"race");db.close();const sent=sender(),common={openRepository:f.open,sendPhoto:sent.sendPhoto,sendMessage:sent.sendMessage};const [telegram,reconcile]=await Promise.all([drainClosePnlCardDeliveries({...common,consumerSource:"TELEGRAM_EVENT_DRIVEN"}),drainClosePnlCardDeliveries({...common,consumerSource:"RECONCILE_FALLBACK"})]);expect(telegram.claimed+reconcile.claimed).toBe(1);expect(sent.count()).toBe(1);const verify=f.open();expect(verify.db.prepare("SELECT COUNT(*) count,delivery_status FROM pnl_card_deliveries WHERE economic_event_id='race'").get()).toEqual({count:1,delivery_status:"DELIVERED"});verify.close();}finally{rmSync(f.dir,{recursive:true,force:true});}});

  it("recovers a pre-send crash but terminalizes an ambiguous post-send crash",async()=>{const f=fixture();try{vi.useFakeTimers();vi.setSystemTime(T0);let db=f.open();appendClose(db,"before");ensure(db,"before");const before=db.claimPnlCardDelivery("close:before:chat","TELEGRAM_EVENT_DRIVEN")!;expect(before.delivery_status).toBe("SENDING");db.close();vi.setSystemTime(T0+30_001);const sent=sender();await drainClosePnlCardDeliveries({openRepository:f.open,sendPhoto:sent.sendPhoto,sendMessage:sent.sendMessage,consumerSource:"TELEGRAM_EVENT_DRIVEN",retryDelayMs:0});expect(sent.count()).toBe(1);db=f.open();appendClose(db,"ambiguous", "ambiguous",T0+31_000);ensure(db,"ambiguous");db.claimPnlCardDelivery("close:ambiguous:chat","TELEGRAM_EVENT_DRIVEN");db.markPnlCardDeliverySendStarted("close:ambiguous:chat",T0+31_000);db.close();vi.setSystemTime(T0+61_001);await drainClosePnlCardDeliveries({openRepository:f.open,sendPhoto:sent.sendPhoto,sendMessage:sent.sendMessage,consumerSource:"TELEGRAM_EVENT_DRIVEN",retryDelayMs:0});expect(sent.count()).toBe(1);db=f.open();expect(db.db.prepare("SELECT delivery_status,error_code FROM pnl_card_deliveries WHERE economic_event_id='ambiguous'").get()).toEqual({delivery_status:"DELIVERY_UNCERTAIN",error_code:"TELEGRAM_SEND_OUTCOME_AMBIGUOUS_AFTER_CRASH"});db.close();}finally{rmSync(f.dir,{recursive:true,force:true});}});

  it("delivers PENDING after restart, leaves pre-claim work durable, and never resends DELIVERED",async()=>{const f=fixture();try{vi.useFakeTimers();vi.setSystemTime(T0);let db=f.open();appendClose(db,"restart");ensure(db,"restart");expect(db.db.prepare("SELECT delivery_status FROM pnl_card_deliveries WHERE economic_event_id='restart'").get()).toEqual({delivery_status:"PENDING"});db.close();const sent=sender();await drainClosePnlCardDeliveries({openRepository:f.open,sendPhoto:sent.sendPhoto,sendMessage:sent.sendMessage,consumerSource:"TELEGRAM_EVENT_DRIVEN"});await drainClosePnlCardDeliveries({openRepository:f.open,sendPhoto:sent.sendPhoto,sendMessage:sent.sendMessage,consumerSource:"RECONCILE_FALLBACK"});expect(sent.count()).toBe(1);db=f.open();expect(db.db.prepare("SELECT delivery_status FROM pnl_card_deliveries WHERE economic_event_id='restart'").get()).toEqual({delivery_status:"DELIVERED"});db.close();}finally{rmSync(f.dir,{recursive:true,force:true});}});

  it("bounds backlog work and continues after one retryable send failure",async()=>{const f=fixture();try{vi.useFakeTimers();vi.setSystemTime(T0);const db=f.open();for(const id of ["a","b","c"]){appendClose(db,id);ensure(db,id);}db.close();let attempt=0;const sent=sender(()=>++attempt===1?{delivered:false,messageId:null,retryable:true,failureCode:"TELEGRAM_TRANSIENT_DELIVERY_FAILURE"}:{delivered:true,messageId:attempt});const cycle=await drainClosePnlCardDeliveries({openRepository:f.open,sendPhoto:sent.sendPhoto,sendMessage:sent.sendMessage,consumerSource:"TELEGRAM_EVENT_DRIVEN",limit:3});expect(cycle.claimed).toBe(3);expect(sent.count()).toBe(3);const verify=f.open();expect(verify.db.prepare("SELECT delivery_status,COUNT(*) count FROM pnl_card_deliveries GROUP BY delivery_status ORDER BY delivery_status").all()).toEqual([{delivery_status:"DELIVERED",count:2},{delivery_status:"PENDING",count:1}]);verify.close();}finally{rmSync(f.dir,{recursive:true,force:true});}});

  it("keeps producer ordering and fallback repair tied to canonical CLOSE truth",()=>{const producer=readFileSync("apps/cli/src/v4-bid-ladder-live.ts","utf8"),append=producer.indexOf("appendRealizedPnlEvent"),delivery=producer.indexOf("ensurePnlCardDelivery",append);expect(append).toBeGreaterThanOrEqual(0);expect(delivery).toBeGreaterThan(append);expect(producer).toContain("V4_BID_LADDER_CLOSE_REALIZED_EVENT_NOT_DURABLE");const fallback=readFileSync("apps/cli/src/index.ts","utf8");expect(fallback).toMatch(/consumerSource:\s*"RECONCILE_FALLBACK"/);});
});
