import { describe, expect, it } from 'vitest';
import { aggregatePortfolio, canonicalPortfolioAccounting, PORTFOLIO_PRICE_TTL_MS, type PortfolioPosition } from '../apps/cli/src/portfolio.js';
import { FUNI_COMMAND_MENU, HELP_TEXT, START_TEXT } from '../apps/telegram-lp-bot/src/command-menu.js';

function position(accounting:ReturnType<typeof canonicalPortfolioAccounting>,overrides:Partial<PortfolioPosition>={}):PortfolioPosition{return {positionId:'v4:1',tokenId:'1',protocol:'v4',pair:'TOKEN/USDG',poolId:'pool',token0Address:'0x0000000000000000000000000000000000000001',token1Address:'0x0000000000000000000000000000000000000002',status:'open',rangeStatus:'IN_RANGE',range:'-10–10',currentPrice:2,valuationStatus:'PRICED',raw:{originalDeposits:{token0:0n,token1:1_000_000n},currentPrincipal:{token0:1n,token1:0n},uncollectedFees:{token0:0n,token1:0n},collectedFees:{token0:0n,token1:0n},withdrawnPrincipal:{token0:0n,token1:0n}},accounting,reconciliation:'COMPLETE',...overrides};}
describe('canonical portfolio accounting',()=>{
 it('uses non-overlapping principal, fees, proceeds, and gas formulas',()=>{const result=canonicalPortfolioAccounting({externalCapitalUsd:100,activePrincipalUsd:70,uncollectedFeesUsd:5,collectedFeesUsd:8,realizedProceedsUsd:30,gasSpentUsd:2});expect(result.currentEquityUsd).toBe(75);expect(result.grossPnlUsd).toBe(13);expect(result.grossPnlPct).toBe(13);expect(result.netPnlUsd).toBe(11);expect(result.netPnlPct).toBe(11);});
 it('does not double-count principal withdrawals as collected fees',()=>{const result=canonicalPortfolioAccounting({externalCapitalUsd:100,activePrincipalUsd:50,uncollectedFeesUsd:3,collectedFeesUsd:2,realizedProceedsUsd:50,gasSpentUsd:1});expect(result.grossPnlUsd).toBe(5);expect(result.netPnlUsd).toBe(4);});
 it('fails closed for missing historical valuation rather than fabricating PnL',()=>{const result=canonicalPortfolioAccounting({externalCapitalUsd:100,activePrincipalUsd:90,uncollectedFeesUsd:2,collectedFeesUsd:null,realizedProceedsUsd:10,gasSpentUsd:1});expect(result.currentEquityUsd).toBe(92);expect(result.grossPnlUsd).toBeNull();expect(result.netPnlUsd).toBeNull();expect(result.warnings).toContain('COLLECTEDFEESUSD_UNAVAILABLE');});
 it('aggregates priced components and explicitly marks partial valuation',()=>{const complete=position(canonicalPortfolioAccounting({externalCapitalUsd:100,activePrincipalUsd:90,uncollectedFeesUsd:5,collectedFeesUsd:2,realizedProceedsUsd:10,gasSpentUsd:1})),unpriced=position(canonicalPortfolioAccounting({externalCapitalUsd:null,activePrincipalUsd:null,uncollectedFeesUsd:null,collectedFeesUsd:0,realizedProceedsUsd:0,gasSpentUsd:null}),{positionId:'live:2',tokenId:'2',protocol:'v3',valuationStatus:'UNPRICED',rangeStatus:'OUT_OF_RANGE'}),aggregate=aggregatePortfolio([complete,unpriced]);expect(aggregate.pricedPositions).toBe(1);expect(aggregate.unpricedPositions).toBe(1);expect(aggregate.activePrincipalUsd).toBe(90);expect(aggregate.partialValuation).toBe(true);});
 it('excludes a replaced parent from aggregate equity to avoid lineage double-counting',()=>{const accounting=canonicalPortfolioAccounting({externalCapitalUsd:100,activePrincipalUsd:100,uncollectedFeesUsd:0,collectedFeesUsd:0,realizedProceedsUsd:0,gasSpentUsd:0}),parent=position(accounting,{status:'closed',excludedFromAggregateReason:'REPLACED_BY_CHILD_POSITION'}),child=position(accounting,{positionId:'v4:2',tokenId:'2'}),aggregate=aggregatePortfolio([parent,child]);expect(aggregate.currentEquityUsd).toBe(100);expect(aggregate.excludedReplacedPositions).toBe(1);});
 it('uses a bounded two-minute price freshness policy',()=>expect(PORTFOLIO_PRICE_TTL_MS).toBe(120_000));
});
describe('public Telegram command menu',()=>{
 it('contains only approved manual FUNI commands',()=>{expect(FUNI_COMMAND_MENU.map(item=>item.command)).toEqual(['start','help','positions','portfolio','bid_ladder_preview','bid_ladder_view','bid_ladder_list','cancel','chatid']);expect(HELP_TEXT).toContain('explicit preview and final confirmation');expect(HELP_TEXT).toContain('never transact');});
 it('documents manual previews, unavailable accounting, and transaction safety',()=>{expect(START_TEXT).toContain('Paste a token contract address');expect(HELP_TEXT).toContain('Unknown accounting is shown as Unavailable');expect(HELP_TEXT).toContain('Portfolio reads never transact');expect(HELP_TEXT).toContain('fail-closed');});
});
