import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { migrateSqlite, SqliteLedgerRepository } from '@robin/ledger';
import { applyClosedNoReplacementTerminalization, assertPermanentReleaseEligibility, assertRebalanceCommitmentNotPermanentlyReleased, insertRebalanceCommitmentRelease, previewClosedNoReplacementTerminalization, rebalanceCommitmentReleaseEvidence, releaseConfirmationToken, verifyReleaseConfirmationToken } from '../apps/cli/src/rebalance-commitment-release.js';
import { botManagedProjectedExposure } from '../apps/cli/src/bot-managed-exposure.js';

function fixture(){const dir=mkdtempSync(join(tmpdir(),'commitment-release-')),path=join(dir,'db.sqlite');migrateSqlite(path,'infra/migrations');const repo=new SqliteLedgerRepository(path),id='released';repo.ensurePosition('v4:7','7','pool');repo.upsertV4Position({tokenId:7n,owner:'0x00000000000000000000000000000000000000aa',poolId:'pool',poolKey:{},currency0:'0x1',currency1:'0x2',fee:500,tickSpacing:10,hooks:'0x0000000000000000000000000000000000000000',tickLower:0,tickUpper:10,liquidity:0n,initialAmount0:0n,initialAmount1:0n,mintHash:'0xhash',status:'burned'});repo.db.prepare('INSERT INTO rebalance_lineages(id,root_position_id,original_principal_usd,original_funding_token,original_funding_symbol,protocol_version,pool_id,created_at) VALUES(?,?,?,?,?,?,?,?)').run('lineage','v4:7',100,'0x1','USDG','v4','pool','2020-01-01');repo.db.prepare("INSERT INTO rebalance_workflows(id,idempotency_key,lineage_id,old_position_id,mode,downside_pct,state,revision,preview_json,state_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").run(id,id,'lineage','v4:7','REBALANCE',10,'FAILED_RECOVERABLE',3,JSON.stringify({plan:{actualReopenUsd:100,requiredTopUpUsd:0}}),'{}','2020-01-01','2020-01-01');repo.db.prepare("INSERT INTO portfolio_persisted_snapshot(snapshot_key,payload_json,content_hash,refreshed_at_ms,last_reconciliation_at_ms) VALUES('current',?,?,?,?)").run(JSON.stringify({positions:[],lastReconciliationAt:new Date(1_000_000).toISOString()}),'x',1_000_000,1_000_000);return {repo,id,close(){repo.close();rmSync(dir,{recursive:true,force:true});}};}
const absent=async()=>{throw new Error('transaction not found');};
function prepared(f:ReturnType<typeof fixture>,input:{nonce?:number;hash?:string;submittedAt?:string|null;confirmedAt?:string|null}={}){const hash=input.hash??`0x${'11'.repeat(32)}`,nonce=input.nonce??4;f.repo.db.prepare("INSERT INTO rebalance_transactions(id,workflow_id,semantic_stage,attempt,status,tx_hash,nonce,to_address,calldata_hash,request_json,estimated_gas_raw,estimated_gas_usd,created_at,submitted_at,confirmed_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run('prepared',f.id,'REOPEN_MINT',0,'PREPARED',hash,nonce,'0x0000000000000000000000000000000000000001','0x1','{}','1',0,'2020-01-01',input.submittedAt??null,input.confirmedAt??null,'2020-01-01');return hash;}
function proofRpc(input:{latest?:number;pending?:number;transaction?:unknown;receipt?:unknown;malformed?:boolean}={}){const client={getTransactionReceipt:input.receipt!==undefined?async()=>input.receipt:absent,getTransaction:input.transaction!==undefined?async()=>input.transaction:absent,getTransactionCount:async({blockTag}:{blockTag:string})=>blockTag==='latest'?(input.latest??5):(input.pending??5)};return {clients:input.malformed?[{...client,getTransactionReceipt:async()=>({status:'success'})}]:[client]} as any;}
describe('permanent rebalance commitment release',()=>{
 it('creates one append-only canonical marker and excludes only its commitment',()=>{const f=fixture();try{const before=f.repo.db.prepare('SELECT state,revision,preview_json,state_json FROM rebalance_workflows WHERE id=?').get(f.id);const evidence=rebalanceCommitmentReleaseEvidence(f.repo,f.id);expect(evidence.releasedCommitmentUsd).toBe(100);const marker=insertRebalanceCommitmentRelease(f.repo,{workflowId:f.id,operatorActor:'test',operatorReason:'synthetic abandonment'});expect(marker.released_commitment_usd).toBe(100);expect(f.repo.db.prepare('SELECT state,revision,preview_json,state_json FROM rebalance_workflows WHERE id=?').get(f.id)).toEqual(before);expect(()=>insertRebalanceCommitmentRelease(f.repo,{workflowId:f.id,operatorActor:'test',operatorReason:'duplicate'})).toThrow('REBALANCE_COMMITMENT_RELEASE_ALREADY_EXISTS');const exposure=botManagedProjectedExposure(f.repo,{incrementalActionCapitalUsd:0,nowMs:1_000_001});expect(exposure.breakdown).toMatchObject({pendingReplacementCommitmentUsd:0,releasedHistoricalCommitmentUsd:100,releasedWorkflowIds:[f.id]});expect(()=>assertRebalanceCommitmentNotPermanentlyReleased(f.repo,f.id)).toThrow('REBALANCE_COMMITMENT_PERMANENTLY_RELEASED');}finally{f.close();}});
 it('binds confirmation to evidence, amount, kind, and expiry and fails closed when evidence changes',()=>{const f=fixture();try{const e=rebalanceCommitmentReleaseEvidence(f.repo,f.id),token=releaseConfirmationToken({workflowId:f.id,fingerprint:e.fingerprint,releasedCommitmentUsd:e.releasedCommitmentUsd,expiresAt:100});expect(verifyReleaseConfirmationToken(token,{workflowId:f.id,fingerprint:e.fingerprint,releasedCommitmentUsd:100,now:99})).toBe(true);expect(verifyReleaseConfirmationToken(token,{workflowId:'other',fingerprint:e.fingerprint,releasedCommitmentUsd:100,now:99})).toBe(false);expect(verifyReleaseConfirmationToken(token,{workflowId:f.id,fingerprint:e.fingerprint,releasedCommitmentUsd:99,now:99})).toBe(false);f.repo.db.prepare('UPDATE rebalance_workflows SET revision=4 WHERE id=?').run(f.id);expect(rebalanceCommitmentReleaseEvidence(f.repo,f.id).fingerprint).not.toBe(e.fingerprint);}finally{f.close();}});
 it('proves an unsubmitted prepared hash is nonce-exhausted without mutating history',async()=>{const f=fixture();try{prepared(f);const before=Object.fromEntries(['rebalance_workflows','rebalance_transitions','rebalance_transactions','rebalance_receipts','rebalance_accounting_events'].map(table=>[table,f.repo.db.prepare(`SELECT * FROM ${table}`).all()]));const current=await assertPermanentReleaseEligibility(f.repo,f.id,proofRpc());expect(current.evidence.preparedReleaseProof).toEqual([expect.objectContaining({semanticStage:'REOPEN_MINT',nonce:4,exactHashLookup:'ABSENT',receiptLookup:'ABSENT',latestNonce:5,pendingNonce:5,classification:'PREPARED_UNSUBMITTED_NONCE_EXHAUSTED'})]);const token=releaseConfirmationToken({workflowId:f.id,fingerprint:current.fingerprint,releasedCommitmentUsd:100,expiresAt:100});expect(verifyReleaseConfirmationToken(token,{workflowId:f.id,fingerprint:(await assertPermanentReleaseEligibility(f.repo,f.id,proofRpc())).fingerprint,releasedCommitmentUsd:100,now:99})).toBe(true);insertRebalanceCommitmentRelease(f.repo,{workflowId:f.id,operatorActor:'test',operatorReason:'proof',current});expect(Object.fromEntries(['rebalance_workflows','rebalance_transitions','rebalance_transactions','rebalance_receipts','rebalance_accounting_events'].map(table=>[table,f.repo.db.prepare(`SELECT * FROM ${table}`).all()]))).toEqual(before);expect(f.repo.db.prepare('SELECT count(*) count FROM rebalance_commitment_releases').get()).toEqual({count:1});expect(()=>assertRebalanceCommitmentNotPermanentlyReleased(f.repo,f.id)).toThrow('REBALANCE_COMMITMENT_PERMANENTLY_RELEASED');}finally{f.close();}});
 it.each([{name:'latest equals prepared',rpc:proofRpc({latest:4,pending:4})},{name:'latest below prepared',rpc:proofRpc({latest:3,pending:3})},{name:'pending differs',rpc:proofRpc({latest:5,pending:6})},{name:'transaction found',rpc:proofRpc({transaction:{hash:`0x${'11'.repeat(32)}`,nonce:4,from:'0x00000000000000000000000000000000000000aa',blockNumber:null}})},{name:'receipt found',rpc:proofRpc({receipt:{transactionHash:`0x${'11'.repeat(32)}`,status:'success',blockNumber:1n,gasUsed:1n,effectiveGasPrice:1n}})},{name:'malformed provider',rpc:proofRpc({malformed:true})}])('fails closed when $name',async({rpc})=>{const f=fixture();try{prepared(f);await expect(assertPermanentReleaseEligibility(f.repo,f.id,rpc)).rejects.toThrow('REBALANCE_COMMITMENT_RELEASE_PREPARED_TRANSACTION_UNPROVEN');}finally{f.close();}});
 it.each([{name:'submitted_at',row:{submittedAt:'2020-01-02'}},{name:'confirmed_at',row:{confirmedAt:'2020-01-02'}}])('fails closed when $name is populated',async({row})=>{const f=fixture();try{prepared(f,row);await expect(assertPermanentReleaseEligibility(f.repo,f.id,proofRpc())).rejects.toThrow('REBALANCE_COMMITMENT_RELEASE_PREPARED_TRANSACTION_UNPROVEN');}finally{f.close();}});
 it('binds changed nonce and hash proof into the fingerprint',async()=>{const f=fixture();try{prepared(f);const preview=await assertPermanentReleaseEligibility(f.repo,f.id,proofRpc()),token=releaseConfirmationToken({workflowId:f.id,fingerprint:preview.fingerprint,releasedCommitmentUsd:100,expiresAt:100});const changed=await assertPermanentReleaseEligibility(f.repo,f.id,proofRpc({latest:6,pending:6}));expect(verifyReleaseConfirmationToken(token,{workflowId:f.id,fingerprint:changed.fingerprint,releasedCommitmentUsd:100,now:99})).toBe(false);f.repo.db.prepare('UPDATE rebalance_transactions SET tx_hash=? WHERE id=?').run(`0x${'22'.repeat(32)}`,'prepared');const hashChanged=await assertPermanentReleaseEligibility(f.repo,f.id,proofRpc());expect(verifyReleaseConfirmationToken(token,{workflowId:f.id,fingerprint:hashChanged.fingerprint,releasedCommitmentUsd:100,now:99})).toBe(false);}finally{f.close();}});
});

describe('confirmed close and burn without replacement terminalization',()=>{
 it('atomically preserves confirmed history, fails only the absent attempt, finalizes burn, and permanently blocks resume',async()=>{const f=fixture();try{
  const j=(value:unknown)=>JSON.stringify(value,(_,item)=>typeof item==='bigint'?item.toString():item),closeHash=`0x${'31'.repeat(32)}`,burnHash=`0x${'32'.repeat(32)}`,absentHash=`0x${'33'.repeat(32)}`,at='2020-01-02';
  f.repo.db.prepare("UPDATE v4_positions SET status='closed' WHERE token_id='7'").run();
  const tx=f.repo.db.prepare("INSERT INTO rebalance_transactions(id,workflow_id,semantic_stage,attempt,status,tx_hash,nonce,to_address,calldata_hash,request_json,estimated_gas_raw,estimated_gas_usd,receipt_json,created_at,submitted_at,confirmed_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
  const closeReceipt={transactionHash:closeHash,status:'success',blockNumber:10n,gasUsed:2n,effectiveGasPrice:3n,logs:[]},burnReceipt={transactionHash:burnHash,status:'success',blockNumber:11n,gasUsed:2n,effectiveGasPrice:3n,logs:[]};
  tx.run('close',f.id,'CLOSE_FULL',0,'CONFIRMED',closeHash,14,'0x0000000000000000000000000000000000000001',closeHash,'{}','2',0,j(closeReceipt),at,at,at,at);
  tx.run('burn',f.id,'CLOSE_BURN',0,'CONFIRMED',burnHash,15,'0x0000000000000000000000000000000000000001',burnHash,'{}','2',0,j(burnReceipt),at,at,at,at);
  tx.run('later',f.id,'FEE_TARGET_TO_FUNDING:ERC20_APPROVAL',0,'PREPARED',absentHash,16,'0x0000000000000000000000000000000000000001',absentHash,'{}','2',0,null,at,null,null,at);
  for(const [stage,hash,receipt] of [['close-full',closeHash,closeReceipt],['close-burn',burnHash,burnReceipt]] as const)f.repo.db.prepare('INSERT INTO rebalance_receipts(workflow_id,stage,tx_hash,receipt_json,confirmed_at) VALUES(?,?,?,?,?)').run(f.id,stage,hash,j(receipt),at);
  const burnIntent=f.repo.createV4LifecycleIntent({tokenId:7n,action:'burn',idempotencyKey:`rebalance:${f.id}:burn:0`});f.repo.claimV4LifecycleIntent(String(burnIntent.id));f.repo.transitionV4LifecycleIntent(String(burnIntent.id),'RECONCILED',{txHash:burnHash});f.repo.persistV4LifecycleReceipt(burnHash,String(burnIntent.id),burnReceipt);
  const client={getTransactionReceipt:async({hash}:{hash:string})=>{if(hash===closeHash)return closeReceipt;if(hash===burnHash)return burnReceipt;throw new Error('transaction not found');},getTransaction:absent,getTransactionCount:async()=>16,readContract:async()=>{throw new Error('NOT_MINTED');}},rpc={clients:[client]} as any;
  const confirmedBefore=f.repo.db.prepare("SELECT * FROM rebalance_transactions WHERE status='CONFIRMED' ORDER BY id").all(),workflowBefore=f.repo.db.prepare('SELECT * FROM rebalance_workflows WHERE id=?').get(f.id);
  const preview=await previewClosedNoReplacementTerminalization(f.repo,rpc,'0x00000000000000000000000000000000000000aa',f.id);expect(preview).toMatchObject({abandonedAttempt:{nonce:16,latestNonce:16,pendingNonce:16,classification:'SIGNED_HASH_ABSENT_NONCE_AVAILABLE'},burnedProof:{classification:'OWNER_OF_NOT_MINTED_ALL_PROVIDERS'},resultingWorkflowCheckpoint:'PERMANENTLY_NON_RESUMABLE_CLOSED_NO_REPLACEMENT'});
  const applied=applyClosedNoReplacementTerminalization(f.repo,preview);expect(applied.status).toBe('TERMINALIZED');expect(f.repo.db.prepare("SELECT status,tx_hash,nonce,failure_reason FROM rebalance_transactions WHERE id='later'").get()).toMatchObject({status:'FAILED',tx_hash:absentHash,nonce:16,failure_reason:'SIGNED_HASH_PROVEN_ABSENT_NONCE_AVAILABLE_OPERATOR_TERMINALIZATION'});expect(f.repo.db.prepare("SELECT state,tx_hash FROM v4_lifecycle_intents WHERE id=?").get(String(burnIntent.id))).toEqual({state:'BURNED',tx_hash:burnHash});expect(f.repo.v4Position(7n)).toMatchObject({status:'burned',liquidity_raw:'0'});expect(f.repo.db.prepare("SELECT * FROM rebalance_transactions WHERE status='CONFIRMED' ORDER BY id").all()).toEqual(confirmedBefore);expect(f.repo.db.prepare('SELECT * FROM rebalance_workflows WHERE id=?').get(f.id)).toEqual(workflowBefore);expect(()=>assertRebalanceCommitmentNotPermanentlyReleased(f.repo,f.id)).toThrow('REBALANCE_COMMITMENT_PERMANENTLY_RELEASED');
  const second=await previewClosedNoReplacementTerminalization(f.repo,rpc,'0x00000000000000000000000000000000000000aa',f.id);expect(applyClosedNoReplacementTerminalization(f.repo,second).status).toBe('ALREADY_TERMINALIZED');expect(f.repo.db.prepare('SELECT count(*) count FROM rebalance_commitment_releases').get()).toEqual({count:1});
 }finally{f.close();}});
});
