import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { describe, expect, it } from 'vitest';
import { sanitizeRpcError } from '@robin/core';
import { migrateSqlite, SqliteLedgerRepository } from '@robin/ledger';
import { authorizeRebalanceWorkflow, createRebalanceWorkflow, ensureRebalanceLineage, markRebalanceExecutionFailure, markRebalancePreTransactionFailure, rebalanceTransitions, rebalanceWorkflow, reuseRebalanceWorkflowForFreshPreview } from '../apps/cli/src/rebalance.js';
import { withFinalPreflightDeadline } from '../apps/cli/src/v4-rebalance-executor.js';

function fixture(){const dir=mkdtempSync(join(tmpdir(),'rebalance-recovery-')),path=join(dir,'db.sqlite');migrateSqlite(path,'infra/migrations');const repo=new SqliteLedgerRepository(path),lineage=ensureRebalanceLineage(repo,{rootPositionId:'v4:4242',originalPrincipalUsd:10,fundingToken:'0x0000000000000000000000000000000000000001',fundingSymbol:'USDG',protocol:'v4',poolId:'pool'});return {repo,lineage,close(){repo.close();rmSync(dir,{recursive:true,force:true});}};}
const input=(lineageId:string,key:string)=>({idempotencyKey:key,lineageId,oldPositionId:'v4:4242',mode:'REBALANCE' as const,downsidePct:30,preview:{plan:{requiredTopUpUsd:0}}});

describe('rebalance stale-workflow recovery',()=>{
 it('reuses a nonterminal old-position workflow for a fresh preview and clears every stale preflight snapshot',()=>{const f=fixture();try{const first=createRebalanceWorkflow(f.repo,input(String(f.lineage.id),'first'));f.repo.db.prepare("UPDATE rebalance_workflows SET state='TOPUP_AUTHORIZED',execution_json='{\"stale\":true}',projected_gas_usd=1,actual_gas_usd=1 WHERE id=?").run(String(first.id));const reused=reuseRebalanceWorkflowForFreshPreview(f.repo,{...input(String(f.lineage.id),'fresh'),oldPositionActive:true});expect(reused.id).toBe(first.id);expect(reused).toMatchObject({state:'PREVIEWED',execution_json:'{}',projected_gas_usd:null,actual_gas_usd:0,last_error:null});expect(rebalanceTransitions(f.repo,String(first.id)).at(-1)).toMatchObject({state:'PREVIEWED'});}finally{f.close();}});
 it('persists a retryable pre-transaction failure instead of TOPUP_AUTHORIZED',()=>{const f=fixture();try{const workflow=createRebalanceWorkflow(f.repo,input(String(f.lineage.id),'one'));f.repo.db.prepare("UPDATE rebalance_workflows SET state='TOPUP_AUTHORIZED' WHERE id=?").run(String(workflow.id));const failed=markRebalancePreTransactionFailure(f.repo,String(workflow.id),'REBALANCE_PRICE_STALE');expect(failed).toMatchObject({state:'FAILED_RECOVERABLE',last_error:'REBALANCE_PRICE_STALE'});expect(JSON.parse(String(failed.state_json))).toMatchObject({resumeFrom:'TOPUP_AUTHORIZED'});}finally{f.close();}});
 it('bounds an overall hung preflight, persists FAILED_RECOVERABLE, and never invokes submission',async()=>{const f=fixture();let submissions=0;try{const workflow=createRebalanceWorkflow(f.repo,input(String(f.lineage.id),'overall-timeout')),workflowId=String(workflow.id);f.repo.db.prepare("UPDATE rebalance_workflows SET state='TOPUP_AUTHORIZED' WHERE id=?").run(workflowId);let error:unknown;try{await withFinalPreflightDeadline(workflowId,signal=>new Promise((_,reject)=>signal.addEventListener('abort',()=>reject(signal.reason),{once:true})),20);}catch(caught){error=caught;}const failed=markRebalanceExecutionFailure(f.repo,workflowId,sanitizeRpcError(error,{stage:'v4_rebalance_final_preflight',method:'overall_deadline'}));expect(failed).toMatchObject({state:'FAILED_RECOVERABLE'});expect(String(failed.last_error)).toContain('RPC_PREFLIGHT_TIMEOUT stage=v4_rebalance_final_preflight method=overall_deadline');expect(f.repo.db.prepare('SELECT COUNT(*) n FROM rebalance_transactions WHERE workflow_id=?').get(workflowId)).toMatchObject({n:0});expect(submissions).toBe(0);}finally{f.close();}});
 it('persists only a sanitized provider failure without an RPC URL or API key',()=>{const f=fixture();try{const secret='synthetic-api-key-456',workflow=createRebalanceWorkflow(f.repo,input(String(f.lineage.id),'provider-failure'));f.repo.db.prepare("UPDATE rebalance_workflows SET state='TOPUP_AUTHORIZED' WHERE id=?").run(String(workflow.id));const raw=Object.assign(new Error(`HTTP 429 https://provider.example/v2/${secret}`),{name:'HttpRequestError',status:429}),safe=sanitizeRpcError(raw,{stage:'v4_pool_inspection',method:'StateView.getSlot0'}),failed=markRebalanceExecutionFailure(f.repo,String(workflow.id),safe);expect(failed.state).toBe('FAILED_RECOVERABLE');expect(String(failed.last_error)).toContain('providerIndex=-1 status=429');expect(String(failed.last_error)).not.toContain(secret);expect(String(failed.last_error)).not.toContain('https://');}finally{f.close();}});
 it('deduplicates repeated final authorization callbacks without adding a second transition',()=>{const f=fixture();try{const plan={mode:'REBALANCE' as const,originalPrincipalUsd:10,recoveredPrincipalUsd:10,verifiedFeesUsd:0,requiredTopUpUsd:0,requestedReopenUsd:10,actualReopenUsd:10,principalSurplusUsd:0,compoundFeesUsd:0,feeSurplusToUsdgUsd:0,totalSurplusToUsdgUsd:0,originalFundingSymbol:'USDG',classification:{principalForReopenUsd:10,feesForReopenUsd:0,principalSurplusToUsdgUsd:0,feesToUsdgUsd:0}},workflow=createRebalanceWorkflow(f.repo,{...input(String(f.lineage.id),'final-dedupe'),preview:{plan}}),workflowId=String(workflow.id),args={workflowId,maximumTopUpUsd:0,balances:{originalFundingUsd:0,usdgUsd:0}};expect(authorizeRebalanceWorkflow(f.repo,args).state).toBe('TOPUP_AUTHORIZED');expect(authorizeRebalanceWorkflow(f.repo,args).state).toBe('TOPUP_AUTHORIZED');expect(rebalanceTransitions(f.repo,workflowId).filter(row=>row.state==='TOPUP_AUTHORIZED')).toHaveLength(1);}finally{f.close();}});
 it('refuses reuse when a recorded transaction requires reconciliation',()=>{const f=fixture();try{const workflow=createRebalanceWorkflow(f.repo,input(String(f.lineage.id),'one'));f.repo.db.prepare("INSERT INTO rebalance_transactions(id,workflow_id,semantic_stage,attempt,status,tx_hash,nonce,to_address,calldata_hash,request_json,estimated_gas_raw,estimated_gas_usd,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run('tx',String(workflow.id),'CLOSE_FULL',0,'PREPARED','0xhash',0,'0x0000000000000000000000000000000000000001','0xdata','{}','1',0,new Date().toISOString(),new Date().toISOString());expect(()=>reuseRebalanceWorkflowForFreshPreview(f.repo,{...input(String(f.lineage.id),'fresh'),oldPositionActive:true})).toThrow('REBALANCE_RECONCILIATION_REQUIRED');}finally{f.close();}});
 it('persists a durable recoverable capital state after a transaction has been recorded',()=>{const f=fixture();try{const workflow=createRebalanceWorkflow(f.repo,input(String(f.lineage.id),'one'));f.repo.db.prepare("UPDATE rebalance_workflows SET state='CLOSE_CONFIRMED' WHERE id=?").run(String(workflow.id));f.repo.db.prepare("INSERT INTO rebalance_transactions(id,workflow_id,semantic_stage,attempt,status,tx_hash,nonce,to_address,calldata_hash,request_json,estimated_gas_raw,estimated_gas_usd,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run('tx',String(workflow.id),'CLOSE_FULL',0,'CONFIRMED','0xhash',0,'0x0000000000000000000000000000000000000001','0xdata','{}','1',0,new Date().toISOString(),new Date().toISOString());const failed=markRebalanceExecutionFailure(f.repo,String(workflow.id),'REOPEN_PRECHECK_FAILED');expect(failed).toMatchObject({state:'FAILED_RECOVERABLE',last_error:'REOPEN_PRECHECK_FAILED'});expect(JSON.parse(String(failed.state_json))).toMatchObject({resumeFrom:'CLOSE_CONFIRMED'});}finally{f.close();}});
 it('continues callback handling when Telegram reports an expired callback answer',()=>{const source=readFileSync('apps/telegram-lp-bot/src/index.ts','utf8'),handler=source.slice(source.indexOf('bot.use(async (ctx, next)'),source.indexOf('bot.command'));expect(handler).toMatch(/answerCallbackQuery\(\)/);expect(handler).toMatch(/telegram_callback_ack_expired/);expect(handler).toMatch(/query.*(?:old|expired)/is);});
 it('keeps range previews wired, shows preparation, and reports RPC failures without crashing the worker',()=>{const source=readFileSync('apps/telegram-lp-bot/src/index.ts','utf8');expect(source).toMatch(/import \{[^}]*createRebalanceWorkflow/);expect(source).toContain('Preparing rebalance preview');expect(source).toContain("rebalance_preview_latency");expect(source).toContain("rebalance_preview_deferred");expect(source).toContain('REBALANCE_PREVIEW_UNAVAILABLE');});
 it('uses one fresh position/price/deployment promise set for the immutable final-preflight snapshot',()=>{const source=readFileSync('apps/cli/src/v4-rebalance-executor.ts','utf8'),lifecycle=readFileSync('apps/cli/src/v4-lifecycle.ts','utf8'),prepare=source.slice(source.indexOf('async function prepareInitial'),source.indexOf('async function lifecycle'));expect(source).toContain('positionStatePromise=inspectV4PositionState(preflightRpc,tokenId)');expect(source).toContain('v4PositionStates:new Map([[tokenId.toString(),positionStatePromise]])');expect(source).toContain('wethUsdReference:v4WethReference');expect(source).toContain("protocolScope:'v4'");expect(prepare.match(/auditRobinhoodV4Deployments\(preflightRpc\)/g)).toHaveLength(1);expect(source).toContain("preflightState=action==='full_close'?freshPreflightStates.get(input.workflowId):undefined");expect(lifecycle).toContain('input.preflightState??await inspectV4PositionState');});
 it('shows immediate final-preflight progress and passes top-up plus funding approval to the button label',()=>{const source=readFileSync('apps/telegram-lp-bot/src/index.ts','utf8'),preview=source.slice(source.indexOf('async function rebalancePreview'),source.indexOf('async function executeRebalanceFromTelegram')),execution=source.slice(source.indexOf('async function executeRebalanceFromTelegram'),source.indexOf('async function finalizeRebalance'));expect(execution).toMatch(/Preparing final rebalance preflight/);expect(preview).toMatch(/rebalanceConfirmationLabel\(/);expect(preview).toMatch(/plan\.requiredTopUpUsd\s*,\s*approval\.requestedApprovalUsd\s*>\s*0/);});
});
