import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { keccak256, type Hash } from 'viem';
import { migrateSqlite, SqliteLedgerRepository } from '@robin/ledger';
import { applyRebalanceExactHashReconciliation, exactHashReconcileToken, previewRebalanceExactHashReconciliation, verifyExactHashReconcileToken } from '../apps/cli/src/rebalance-transaction.js';
import { authorizeRebalanceWorkflow, calculateRebalancePlan, createRebalanceWorkflow, ensureRebalanceLineage } from '../apps/cli/src/rebalance.js';

const wallet='0x00000000000000000000000000000000000000aa' as const,hash=keccak256('0xabcdef'),receipt={status:'success' as const,transactionHash:hash,blockNumber:77n,gasUsed:90_000n,effectiveGasPrice:2n,logs:[]};
function fixture(){const dir=mkdtempSync(join(tmpdir(),'exact-reconcile-')),path=join(dir,'db.sqlite');migrateSqlite(path,'infra/migrations');const repo=new SqliteLedgerRepository(path);repo.ensurePosition('v4:7','7','pool');repo.upsertV4Position({tokenId:7n,owner:wallet,poolId:'pool',poolKey:{},currency0:'0x0000000000000000000000000000000000000001',currency1:'0x0000000000000000000000000000000000000002',fee:500,tickSpacing:10,hooks:'0x0000000000000000000000000000000000000000',tickLower:0,tickUpper:10,liquidity:0n,initialAmount0:10n,initialAmount1:20n,mintHash:`0x${'33'.repeat(32)}`,status:'closed'});const lineage=ensureRebalanceLineage(repo,{rootPositionId:'v4:7',originalPrincipalUsd:5,fundingToken:'0x0000000000000000000000000000000000000001',fundingSymbol:'USDG',protocol:'v4',poolId:'pool'}),plan=calculateRebalancePlan({mode:'REBALANCE',originalPrincipalUsd:5,recoveredPrincipalUsd:5,verifiedFeesUsd:0,compoundCapUsd:100,originalFundingSymbol:'USDG'}),workflow=createRebalanceWorkflow(repo,{idempotencyKey:'incident-shape',lineageId:String(lineage.id),oldPositionId:'v4:7',mode:'REBALANCE',downsidePct:30,preview:{plan}}),workflowId=String(workflow.id);authorizeRebalanceWorkflow(repo,{workflowId,maximumTopUpUsd:0,balances:{originalFundingUsd:0,usdgUsd:0}});repo.db.prepare("UPDATE rebalance_workflows SET state='FAILED_RECOVERABLE',state_json=?,execution_json=? WHERE id=?").run(JSON.stringify({resumeFrom:'CLOSE_STARTED'}),JSON.stringify({prices:{wethUsd:2}}),workflowId);const intent=repo.createV4LifecycleIntent({tokenId:7n,action:'full_close',idempotencyKey:`rebalance:${workflowId}:full_close:0`,payload:{prepared:{key:{currency0:'0x0000000000000000000000000000000000000001',currency1:'0x0000000000000000000000000000000000000002',fee:500,tickSpacing:10,hooks:'0x0000000000000000000000000000000000000000'},principal:{token0:'10',token1:'20'}}}});repo.claimV4LifecycleIntent(String(intent.id));repo.transitionV4LifecycleIntent(String(intent.id),'SIMULATION_PASSED');const at=new Date().toISOString();repo.db.prepare('INSERT INTO rebalance_transactions(id,workflow_id,semantic_stage,attempt,status,tx_hash,nonce,to_address,calldata_hash,request_json,estimated_gas_raw,estimated_gas_usd,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run('incident-tx',workflowId,'CLOSE_FULL',0,'PREPARED',hash,14,'0x0000000000000000000000000000000000000003',`0x${'44'.repeat(32)}`,'{}','100000',0,at,at);const client={getTransactionReceipt:async()=>receipt};const rpc={clients:[client],withClient:async(fn:(client:any)=>unknown)=>fn(client)} as any;return {repo,workflowId,rpc,close(){repo.close();rmSync(dir,{recursive:true,force:true});}};}

describe('canonical rebalance exact-hash reconciliation',()=>{
 it('atomically reconciles the incident shape at CLOSE_FULL and is idempotent',async()=>{const f=fixture();try{const preview=await previewRebalanceExactHashReconciliation(f.repo,f.rpc,wallet,f.workflowId,'CLOSE_FULL'),binding={workflowId:preview.workflowId,transactionRowId:preview.transactionRowId,semanticStage:preview.semanticStage,exactHash:preview.exactHash,nonce:preview.nonce,receiptBlock:preview.receiptBlock,receiptStatus:preview.receiptStatus,journalFingerprint:preview.journalFingerprint},token=exactHashReconcileToken({...binding,expiresAt:100});expect(preview).toMatchObject({transactionRowId:'incident-tx',exactHash:hash,nonce:14,receiptBlock:77,receiptStatus:'success',resultingWorkflowCheckpoint:{confirmedStage:'CLOSE_FULL',nextResumableStage:'CLOSE_BURN'}});expect(verifyExactHashReconcileToken(token,{...binding,now:99})).toBe(true);const first=applyRebalanceExactHashReconciliation(f.repo,preview),counts=()=>Object.fromEntries(['rebalance_receipts','v4_lifecycle_receipts','liquidity_changes','collections','principal_withdrawals','fee_claims','gas_costs','rebalance_accounting_events'].map(table=>[table,(f.repo.db.prepare(`SELECT count(*) count FROM ${table}`).get() as {count:number}).count]));expect(first).toEqual({status:'RECONCILED',workflowCheckpoint:'CLOSE_FULL_CONFIRMED',nextResumableStage:'CLOSE_BURN'});expect(f.repo.db.prepare('SELECT status,tx_hash,submitted_at,confirmed_at,actual_gas_raw FROM rebalance_transactions WHERE id=?').get('incident-tx')).toMatchObject({status:'CONFIRMED',tx_hash:hash,actual_gas_raw:'90000'});expect(f.repo.db.prepare('SELECT state,state_json FROM rebalance_workflows WHERE id=?').get(f.workflowId)).toMatchObject({state:'CLOSE_FULL_CONFIRMED'});expect(JSON.parse(String((f.repo.db.prepare('SELECT state_json FROM rebalance_workflows WHERE id=?').get(f.workflowId) as any).state_json))).toMatchObject({confirmedStage:'CLOSE_FULL',nextResumableStage:'CLOSE_BURN'});expect(f.repo.db.prepare('SELECT state,tx_hash FROM v4_lifecycle_intents').get()).toEqual({state:'RECONCILED',tx_hash:hash});const after=counts();expect(after).toMatchObject({rebalance_receipts:1,v4_lifecycle_receipts:1,liquidity_changes:1,collections:1,gas_costs:1,rebalance_accounting_events:0});expect(applyRebalanceExactHashReconciliation(f.repo,preview)).toMatchObject({status:'ALREADY_RECONCILED'});expect(counts()).toEqual(after);}finally{f.close();}});
 it('rolls back every row when the bound journal fingerprint is stale',async()=>{const f=fixture();try{const preview=await previewRebalanceExactHashReconciliation(f.repo,f.rpc,wallet,f.workflowId,'CLOSE_FULL');f.repo.db.prepare('UPDATE rebalance_workflows SET revision=revision+1 WHERE id=?').run(f.workflowId);expect(()=>applyRebalanceExactHashReconciliation(f.repo,preview)).toThrow('REBALANCE_EXACT_HASH_RECONCILE_EVIDENCE_CHANGED');expect(f.repo.db.prepare('SELECT status FROM rebalance_transactions WHERE id=?').get('incident-tx')).toEqual({status:'PREPARED'});expect(f.repo.db.prepare('SELECT count(*) count FROM rebalance_receipts').get()).toEqual({count:0});expect(f.repo.db.prepare('SELECT count(*) count FROM v4_lifecycle_receipts').get()).toEqual({count:0});}finally{f.close();}});
});
