process.env.MAX_POSITION_VALUE_USD??='1000';
process.env.MAX_APPROVAL_VALUE_USD??='1000';
process.env.MAX_REBALANCE_COMPOUND_VALUE_USD??='5000';
process.env.MAX_REBALANCE_APPROVAL_VALUE_USD??='5000';
