import { describe, expect, it } from 'vitest';
import { Q96, DOWNSIDE_PRESETS, RangeNotStrictlySingleSidedError, allowanceSimulationState, downsideFromCurrent, explainMintSimulationFailure, resolveSingleSidedRoles, singleSidedDownsideQuote, validateDownsidePercentages } from '@funi/v3';
import { Ledger, oneSidedMarkToMarket } from '@funi/ledger';

const token0={address:'0x0000000000000000000000000000000000000001' as const,symbol:'PONS',decimals:18};
const token1={address:'0x0000000000000000000000000000000000000002' as const,symbol:'USDG',decimals:18};
const pool={address:token0.address,factory:token0.address,token0:token0.address,token1:token1.address,fee:3000,tickSpacing:60,liquidity:1n,sqrtPriceX96:Q96,tick:0,initialized:true,blockNumber:1n};
describe('single-sided downside planner',()=>{
 it('does not confuse a successful future approval with an already-applied allowance',()=>{const status=allowanceSimulationState(0n,25_000_000n);expect(status).toMatchObject({currentAllowance:0n,requiredAllowance:25_000_000n,approvalRequired:true,approvalStatus:'APPROVAL_REQUIRED',directMintStatus:'MINT_BLOCKED_UNTIL_APPROVAL',approvalAppliedToSimulationState:false});});
 it('permits a direct mint simulation only when the live NPM allowance is sufficient',()=>{expect(allowanceSimulationState(25_000_000n,25_000_000n)).toMatchObject({approvalRequired:false,approvalStatus:'ALLOWANCE_SUFFICIENT',directMintStatus:'DIRECT_MINT_ALLOWED'});});
 it('decodes STF without presenting it as a range failure',()=>{expect(explainMintSimulationFailure('execution reverted: STF')).toMatch(/Funding token transfer failed/);});
 it('supports all accepted preset percentages and custom validation',()=>{expect(DOWNSIDE_PRESETS).toEqual([10,20,30,40,50,60]);for(const pct of DOWNSIDE_PRESETS)expect(downsideFromCurrent(2.4,pct)).toMatchObject({upperDropPct:0,lowerDropPct:pct});expect(()=>validateDownsidePercentages(30,30)).toThrow(/0 <=/);expect(()=>validateDownsidePercentages(-1,30)).toThrow(/0 <=/);expect(()=>validateDownsidePercentages(30,100)).toThrow(/0 <=/);});
 it('keeps a token0 target entirely token1-funded before a downside range',()=>{const roles=resolveSingleSidedRoles({target:token0,funding:token1,token0,token1});const q=singleSidedDownsideQuote(pool,roles,1_000_000n,downsideFromCurrent(1,30));expect(q.amount0Desired).toBe(0n);expect(q.amount1Desired).toBe(1_000_000n);expect(q.requiredAmount0).toBe(0n);expect(q.requiredAmount1).toBeGreaterThan(0n);expect(q.tickUpper).toBeLessThanOrEqual(pool.tick);expect(q.requestedLowerPrice).toBeCloseTo(.7);});
 it('inverts display orientation for a token1 target while retaining token0-only funding',()=>{const roles=resolveSingleSidedRoles({target:token1,funding:token0,token0,token1});const q=singleSidedDownsideQuote(pool,roles,1_000_000n,downsideFromCurrent(1,30));expect(q.amount0Desired).toBe(1_000_000n);expect(q.amount1Desired).toBe(0n);expect(q.requiredAmount1).toBe(0n);expect(q.requiredAmount0).toBeGreaterThan(0n);expect(q.tickLower).toBeGreaterThan(pool.tick);expect(q.actualUpperPrice).toBeGreaterThan(q.actualLowerPrice);});
 it('fails closed if tick alignment cannot form a strict range',()=>{const roles=resolveSingleSidedRoles({target:token0,funding:token1,token0,token1});expect(()=>singleSidedDownsideQuote({...pool,tickSpacing:887272},roles,1n,downsideFromCurrent(1,10))).toThrow(RangeNotStrictlySingleSidedError);});
 it('benchmarks one-sided PnL against the funding asset, including WETH funding',()=>{const ledger=new Ledger(),p=ledger.state('weth-funded');const result=oneSidedMarkToMarket(p,{currentLiquidity:{token0:25n*10n**17n,token1:5n*10n**17n},current:{token0Usd:100,token1Usd:2000,token0Decimals:18,token1Decimals:18,blockNumber:1n,source:'test',confidence:'derived',observedAt:'now'},initialFunding:1n*10n**18n,fundingIndex:1,initialFundingExecutionValue:2000,targetPriceInFunding:.05});expect(result.holdValue).toBe(2000);expect(result.benchmarkAssetIndex).toBe(1);expect(result.fundingConversionPct).toBe(50);expect(result.averageTargetAcquisitionPrice).toBeCloseTo(.2);});
});
