import { Worker } from 'node:worker_threads';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe,expect,it } from 'vitest';
import { migrateSqlite,SqliteLedgerRepository } from '@funi/ledger';
import { buildPersistedPortfolioSnapshot,persistPortfolioSnapshot } from '../apps/cli/src/active-position-reconciliation.js';
import { robinhoodMainnet } from '@funi/core';

const wallet='0x00000000000000000000000000000000000000AA',token='0x0000000000000000000000000000000000000011',key={currency0:token,currency1:robinhoodMainnet.assets.USDG,fee:500,tickSpacing:10,hooks:'0x0000000000000000000000000000000000000000'};
const percentile=(values:number[],value:number)=>values.slice().sort((a,b)=>a-b)[Math.min(values.length-1,Math.ceil(values.length*value)-1)]!;
const workerSource=`
const {parentPort,workerData}=require('node:worker_threads'),Database=require('better-sqlite3'),wait=ms=>Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,ms);
const db=new Database(workerData.path);db.pragma('busy_timeout=1');parentPort.postMessage({ready:true});parentPort.on('message',message=>{if(message!=='run')return;parentPort.postMessage({started:true});wait(5);const latencies=[],counts={busy:0,retries:0,failures:0};for(let i=0;i<40;i++){const started=Date.now();let done=false;for(let attempt=0;attempt<5;attempt++){try{if(i%2===0)db.prepare("UPDATE telegram_flow_sessions SET updated_at_ms=updated_at_ms+1 WHERE session_id='stress-flow'").run();else db.prepare("UPDATE active_position_reconciliations SET checked_at_ms=checked_at_ms+1 WHERE position_id='v4:500000'").run();done=true;break;}catch(error){if(!String(error.code||'').startsWith('SQLITE_BUSY'))throw error;counts.busy++;if(attempt<4){counts.retries++;wait(1<<attempt);}}}if(!done)counts.failures++;latencies.push(Date.now()-started);}db.close();parentPort.postMessage({done:true,latencies,...counts});});`;
async function workerRun(path:string,work:()=>number){const worker=new Worker(workerSource,{eval:true,workerData:{path}});await new Promise<void>((resolve,reject)=>{worker.once('message',()=>resolve());worker.once('error',reject);});const started=new Promise<void>((resolve,reject)=>{worker.once('message',message=>message.started?resolve():reject(new Error('stress worker did not start')));worker.once('error',reject);});const done=new Promise<any>((resolve,reject)=>{worker.on('message',message=>{if(message.done)resolve(message);});worker.once('error',reject);});worker.postMessage('run');await started;const lockMs=work(),result=await done;await worker.terminate();return {lockMs,p50:percentile(result.latencies,.5),p90:percentile(result.latencies,.9),p99:percentile(result.latencies,.99),busy:result.busy,retries:result.retries,failures:result.failures};}

describe('SQLite reconciliation contention stress',()=>{
 it('removes derived snapshot work from the production-scale writer window',async()=>{
  const dir=mkdtempSync(join(tmpdir(),'funi-contention-stress-')),path=join(dir,'db.sqlite');migrateSqlite(path,'infra/migrations');const repo=new SqliteLedgerRepository(path);try{for(let i=0;i<60;i++){const id=String(500_000+i),positionId=`v4:${id}`;repo.ensurePosition(positionId,id,`pool-${id}`);repo.upsertV4Position({tokenId:BigInt(id),owner:wallet,poolId:`pool-${id}`,poolKey:key,currency0:key.currency0,currency1:key.currency1,fee:key.fee,tickSpacing:key.tickSpacing,hooks:key.hooks,tickLower:-100,tickUpper:100,liquidity:10n,initialAmount0:0n,initialAmount1:1_000_000n,mintHash:`0x${id.padStart(64,'0')}`,targetToken:token,fundingToken:robinhoodMainnet.assets.USDG,targetSymbol:`T${i}`,fundingSymbol:'USDG',targetDecimals:18,fundingDecimals:6,targetIndex:0,fundingIndex:1});repo.db.prepare("INSERT INTO active_position_reconciliations(position_id,protocol_version,token_id,manager_address,owner_result,owner_status,liquidity_raw,claimable0_raw,claimable1_raw,confirmed_active,contributes_equity,check_block,checked_at_ms,fresh_until_ms,retry_count,details_json) VALUES(?,'v4',?,'0x0000000000000000000000000000000000000001',?,'VERIFIED_OWNED','10','0','0',1,1,'100',1000,9999999999999,0,'{}')").run(positionId,id,wallet.toLowerCase());}repo.db.prepare("INSERT INTO telegram_flow_sessions(session_id,scope,user_id,chat_id,state_json,status,created_at_ms,updated_at_ms,expires_at_ms) VALUES('stress-flow','u:c','u','c','{}','active',1,1,9999999999999)").run();const old=await workerRun(path,()=>{const started=Date.now();repo.db.transaction(()=>{repo.db.prepare("UPDATE active_position_reconciliations SET checked_at_ms=checked_at_ms WHERE position_id='v4:500000'").run();for(let i=0;i<20;i++)buildPersistedPortfolioSnapshot(repo,2_000);})();return Date.now()-started;}),after=await workerRun(path,()=>{const started=Date.now();repo.db.transaction(()=>repo.db.prepare("UPDATE active_position_reconciliations SET checked_at_ms=checked_at_ms WHERE position_id='v4:500000'").run())();const lockMs=Date.now()-started;for(let i=0;i<20;i++)buildPersistedPortfolioSnapshot(repo,2_001);persistPortfolioSnapshot(repo,2_001);return lockMs;});console.log(JSON.stringify({event:'sqlite_contention_stress',scale:{positions:60,telegramAndStateWrites:40},before:old,after}));expect(old.lockMs).toBeGreaterThan(after.lockMs);expect(after.lockMs).toBeLessThan(100);expect(after.busy).toBeLessThan(old.busy);expect(after.failures).toBe(0);}finally{repo.close();rmSync(dir,{recursive:true,force:true});}
 },30_000);
});
