import { describe, expect, it } from 'vitest';
import { actionableChainHeader, chainActionButton, chainSelectionResult, chainSelectorView, manualVerifiedPoolView, multichainActionFlow, parseChainActionCallback } from '../apps/telegram-lp-bot/src/multichain-ux.js';

describe('Telegram multi-chain UX',()=>{
 it('shows every chain, identity, and disabled execution defaults',()=>{const view=chainSelectorView({});expect(view.text).toContain('Robinhood Chain (4663)');expect(view.text).toContain('BNB Smart Chain (56)');expect(view.text).toContain('Ethereum Mainnet (1)');expect(view.keyboard.flat().map(item=>item.callback_data)).toEqual(['mc:c:4663','mc:c:56','mc:c:1']);expect(view.rows.find(row=>row.key==='bsc')).toMatchObject({enabled:false,executionAvailable:false});});
 it('never exposes execution support merely because read-only is enabled',()=>{const selected=chainSelectionResult(56,{BSC_ENABLED:'true',BSC_RPC_URLS:'https://example.invalid'});expect(selected.readOnlyAvailable).toBe(true);expect(selected.protocols.some(item=>item.discovery)).toBe(true);expect(selected.protocols.every(item=>item.executionSupported===false)).toBe(true);});
 it('formats active chain, protocol, and action together',()=>{expect(actionableChainHeader({chainId:1,protocol:'uniswap_v3',action:'position 7'})).toBe('Ethereum Mainnet (1) · uniswap_v3 · position 7');});
 it('hides action buttons unless readiness is proven and carries only a durable authorization id',()=>{expect(chainActionButton({chainId:56,protocol:'pancakeswap_v3',action:'close',authorizationId:'auth_1',executionReady:false}).keyboard).toEqual([]);const ready=chainActionButton({chainId:56,protocol:'pancakeswap_v3',action:'close',authorizationId:'auth_1',executionReady:true});expect(ready.keyboard).toEqual([[{text:'Confirm close',callback_data:'mc:x:auth_1'}]]);expect(parseChainActionCallback('mc:x:auth_1')).toEqual({authorizationId:'auth_1'});expect(()=>parseChainActionCallback('mc:x:bad:ethereum')).toThrow('CHAIN_CALLBACK_PAYLOAD_INVALID');});
 it('exposes the complete guarded flow while hiding confirmation until every gate passes',()=>{const blocked=multichainActionFlow({chainId:1,protocol:'uniswap_v3',poolOrPosition:'7',action:'close',readinessState:'GUARDED_LIVE_CONFIGURATION_BLOCKED',authorizationId:'auth',blockers:['CHAIN_EXECUTION_DISABLED']});expect(blocked.steps).toEqual(['chain','protocol','pool_or_position','action','preview','gas_readiness','exposure_readiness','explicit_confirmation','chain_bound_executor']);expect(blocked.keyboard).toEqual([]);expect(multichainActionFlow({...blocked.scope,readinessState:'GUARDED_LIVE_CODE_READY',authorizationId:'auth'}).keyboard).toHaveLength(1);});
 it('renders manually verified BSC pools without claiming discovery completeness',()=>{const text=manualVerifiedPoolView({chain_id:56,protocol:'pancakeswap_v3',validation_status:'MANUAL_VERIFIED',pool_address:'0x1',token0_address:'0x2',token1_address:'0x3',fee:500,tick_spacing:10,state_json:JSON.stringify({tick:1,liquidity:'2'})});expect(text).toContain('Source: MANUAL_VERIFIED');expect(text).toContain('Registry discovery completeness: not claimed');expect(()=>manualVerifiedPoolView({chain_id:1,protocol:'uniswap_v3',validation_status:'MANUAL_VERIFIED'})).toThrow('MANUAL_VERIFIED_BSC_POOL_REQUIRED');});
});
