import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { computeExpiresAt, isExpired, migrateSqlite, SqliteLedgerRepository } from '@robin/ledger';
import { canExecuteV3 } from '@robin/v3';

const ttl=600_000, base=1_700_000_000_000;
function fixture(){const dir=mkdtempSync(join(tmpdir(),'robin-session-')),path=join(dir,'db.sqlite');migrateSqlite(path,join(process.cwd(),'infra/migrations'));return {dir,repo:new SqliteLedgerRepository(path)};}
describe('Telegram persistent flow TTL',()=>{
 it('uses epoch milliseconds without seconds/milliseconds comparisons',()=>{expect(computeExpiresAt(base,ttl)).toBe(base+ttl);expect(isExpired(base+ttl,base+59_000)).toBe(false);expect(isExpired(base+ttl,base+ttl)).toBe(true);});
 it('is valid immediately and after one minute, then expires after ten minutes',()=>{const {dir,repo}=fixture();try{const flow=repo.createTelegramFlow({userId:'u',chatId:'c',state:{kind:'pool'},now:base,ttlMs:ttl});expect(repo.telegramFlow({userId:'u',chatId:'c',sessionId:flow.sessionId,now:base})?.status).toBe('active');expect(repo.telegramFlow({userId:'u',chatId:'c',sessionId:flow.sessionId,now:base+60_000})?.status).toBe('active');expect(repo.telegramFlow({userId:'u',chatId:'c',sessionId:flow.sessionId,now:base+ttl})?.status).toBe('expired');}finally{repo.close();rmSync(dir,{recursive:true,force:true});}});
 it('refreshes TTL on range, amount-side, valid amount, invalid amount, and Back transitions',()=>{const {dir,repo}=fixture();try{const first=repo.createTelegramFlow({userId:'u',chatId:'c',state:{kind:'pool'},now:base,ttlMs:ttl});const range=repo.transitionTelegramFlow({userId:'u',chatId:'c',sessionId:first.sessionId,state:{kind:'range'},now:base+60_000,ttlMs:ttl})!;const asset=repo.transitionTelegramFlow({userId:'u',chatId:'c',sessionId:first.sessionId,state:{kind:'asset'},now:base+120_000,ttlMs:ttl})!;const amount=repo.transitionTelegramFlow({userId:'u',chatId:'c',sessionId:first.sessionId,state:{kind:'amount'},now:base+180_000,ttlMs:ttl})!;const invalid=repo.transitionTelegramFlow({userId:'u',chatId:'c',sessionId:first.sessionId,state:amount.state,now:base+240_000,ttlMs:ttl})!;const back=repo.transitionTelegramFlow({userId:'u',chatId:'c',sessionId:first.sessionId,state:{kind:'asset'},now:base+300_000,ttlMs:ttl})!;expect([range,asset,amount,invalid,back].map(x=>x.expiresAtMs)).toEqual([base+660_000,base+720_000,base+780_000,base+840_000,base+900_000]);expect(back.state.kind).toBe('asset');}finally{repo.close();rmSync(dir,{recursive:true,force:true});}});
 it('rejects an old callback without mutating the current replacement flow',()=>{const {dir,repo}=fixture();try{const old=repo.createTelegramFlow({userId:'u',chatId:'c',state:{kind:'range'},now:base,ttlMs:ttl}),current=repo.createTelegramFlow({userId:'u',chatId:'c',state:{kind:'asset'},now:base+1,ttlMs:ttl});expect(repo.telegramFlow({userId:'u',chatId:'c',sessionId:old.sessionId,now:base+2})?.status).toBe('superseded');expect(repo.transitionTelegramFlow({userId:'u',chatId:'c',sessionId:old.sessionId,state:{kind:'amount'},now:base+2,ttlMs:ttl})).toBeUndefined();expect(repo.activeTelegramFlow({userId:'u',chatId:'c',now:base+2})?.sessionId).toBe(current.sessionId);expect(repo.activeTelegramFlow({userId:'u',chatId:'c',now:base+2})?.state.kind).toBe('asset');}finally{repo.close();rmSync(dir,{recursive:true,force:true});}});
 it('start over receives a fresh deadline and startup recovery retains non-expired sessions',()=>{const {dir,repo}=fixture();try{const old=repo.createTelegramFlow({userId:'u',chatId:'c',state:{kind:'pool'},now:base,ttlMs:ttl}),fresh=repo.createTelegramFlow({userId:'u',chatId:'c',state:{kind:'pool'},now:base+100_000,ttlMs:ttl});expect(fresh.expiresAtMs).toBe(base+700_000);expect(repo.recoverTelegramFlows(base+200_000)).toBe(0);expect(repo.telegramFlow({userId:'u',chatId:'c',sessionId:fresh.sessionId,now:base+200_000})?.status).toBe('active');expect(old.sessionId).not.toBe(fresh.sessionId);}finally{repo.close();rmSync(dir,{recursive:true,force:true});}});
 it('rejects genuinely expired and cross-user/chat sessions',()=>{const {dir,repo}=fixture();try{const flow=repo.createTelegramFlow({userId:'u1',chatId:'c1',state:{kind:'amount'},now:base,ttlMs:ttl});expect(repo.telegramFlow({userId:'u1',chatId:'c1',sessionId:flow.sessionId,now:base+ttl})?.status).toBe('expired');const other=repo.createTelegramFlow({userId:'u2',chatId:'c2',state:{kind:'amount'},now:base,ttlMs:ttl});expect(repo.telegramFlow({userId:'u1',chatId:'c2',sessionId:other.sessionId,now:base})).toBeUndefined();}finally{repo.close();rmSync(dir,{recursive:true,force:true});}});
 it('starts fresh after expiry, cancel, start-over, or an existing active flow',()=>{const {dir,repo}=fixture();try{const expired=repo.createTelegramFlow({userId:'u',chatId:'c',state:{kind:'amount'},now:base,ttlMs:ttl});expect(repo.activeTelegramFlow({userId:'u',chatId:'c',now:base+ttl})).toBeUndefined();const afterExpiry=repo.createTelegramFlow({userId:'u',chatId:'c',state:{kind:'pool'},now:base+ttl,ttlMs:ttl});expect(repo.telegramFlow({userId:'u',chatId:'c',sessionId:expired.sessionId,now:base+ttl})?.status).toBe('expired');expect(repo.cancelTelegramFlow({userId:'u',chatId:'c',sessionId:afterExpiry.sessionId})).toBe(true);expect(repo.activeTelegramFlow({userId:'u',chatId:'c',now:base+ttl+1})).toBeUndefined();const afterCancel=repo.createTelegramFlow({userId:'u',chatId:'c',state:{kind:'token_entry'},now:base+ttl+1,ttlMs:ttl}),afterStartOver=repo.createTelegramFlow({userId:'u',chatId:'c',state:{kind:'token_entry'},now:base+ttl+2,ttlMs:ttl}),afterPaste=repo.createTelegramFlow({userId:'u',chatId:'c',state:{kind:'pool'},now:base+ttl+3,ttlMs:ttl});expect(new Set([afterCancel.sessionId,afterStartOver.sessionId,afterPaste.sessionId]).size).toBe(3);expect(repo.telegramFlow({userId:'u',chatId:'c',sessionId:afterStartOver.sessionId,now:base+ttl+3})?.status).toBe('superseded');expect(repo.activeTelegramFlow({userId:'u',chatId:'c',now:base+ttl+3})?.sessionId).toBe(afterPaste.sessionId);expect(repo.telegramFlowDiagnostics({userId:'u',chatId:'c',now:base+ttl+3}).filter(x=>x.qualifiesAsActive)).toHaveLength(1);}finally{repo.close();rmSync(dir,{recursive:true,force:true});}});
 it('excludes cancelled and completed history from active lookup and isolates scopes',()=>{const {dir,repo}=fixture();try{const cancelled=repo.createTelegramFlow({userId:'u1',chatId:'c1',state:{kind:'pool'},now:base,ttlMs:ttl});repo.cancelTelegramFlow({userId:'u1',chatId:'c1',sessionId:cancelled.sessionId});expect(repo.activeTelegramFlow({userId:'u1',chatId:'c1',now:base+1})).toBeUndefined();const completed=repo.createTelegramFlow({userId:'u1',chatId:'c1',state:{kind:'done'},now:base+2,ttlMs:ttl});repo.db.prepare("UPDATE telegram_flow_sessions SET status='completed' WHERE session_id=?").run(completed.sessionId);expect(repo.activeTelegramFlow({userId:'u1',chatId:'c1',now:base+3})).toBeUndefined();const other=repo.createTelegramFlow({userId:'u2',chatId:'c2',state:{kind:'pool'},now:base+3,ttlMs:ttl});expect(repo.activeTelegramFlow({userId:'u1',chatId:'c1',now:base+3})).toBeUndefined();expect(repo.activeTelegramFlow({userId:'u2',chatId:'c2',now:base+3})?.sessionId).toBe(other.sessionId);}finally{repo.close();rmSync(dir,{recursive:true,force:true});}});
 it('retains the execution gate as blocked',()=>{expect(canExecuteV3({status:'unavailable',reason:'no'},false,true,true).allowed).toBe(false);});
});
