import { describe, expect, it } from 'vitest';
import { authorizeTelegramInbound, groupInboundRoute, telegramMessageShape, telegramUpdateKind } from '../apps/telegram-lp-bot/src/group-silent.js';
describe('Telegram group silent routing',()=>{
 it('silences ordinary text, mentions, replies, service-like text, and unauthorized commands',()=>{for(const text of ['hello','@funi hello','0xC2362AfF2A2a4CC1f48cF3Dab2C4e2605eb94BA3','/chatid','/unknown'])expect(groupInboundRoute({chatType:'group',text,authorized:false})).toBe('silent');expect(groupInboundRoute({chatType:'supergroup',authorized:true})).toBe('silent');});
 it('silences authorized group chatid and callbacks too',()=>{expect(groupInboundRoute({chatType:'group',text:'/chatid',authorized:true})).toBe('silent');expect(groupInboundRoute({chatType:'supergroup',text:'/chatid@funi_bot',authorized:true})).toBe('silent');expect(authorizeTelegramInbound({chatType:'group',senderId:'7',chatId:'-9',operatorUserId:'7',operatorPrivateChatId:'9',updateKind:'callback_query'})).toBe('silent');});
 it('leaves private authorized CA flow routable',()=>expect(groupInboundRoute({chatType:'private',text:'0xC2362AfF2A2a4CC1f48cF3Dab2C4e2605eb94BA3',authorized:true})).toBe('private_or_other'));
 it('authorizes only the exact ordinary private operator envelope',()=>{const base={chatType:'private',senderId:'7',chatId:'9',operatorUserId:'7',operatorPrivateChatId:'9',updateKind:'message'};expect(authorizeTelegramInbound(base)).toBe('authorized');for(const patch of [{chatType:'channel'},{senderId:'8'},{chatId:'10'},{updateKind:'edited_message'},{updateKind:'channel_post'},{isReply:true},{isForward:true},{isMention:true}])expect(authorizeTelegramInbound({...base,...patch})).toBe('silent');expect(authorizeTelegramInbound({...base,updateKind:'callback_query'})).toBe('authorized');});
 it('classifies edited/channel updates and reply, mention, and forwarded message shapes before parsing',()=>{expect(telegramUpdateKind({edited_message:{}})).toBe('edited_message');expect(telegramUpdateKind({channel_post:{}})).toBe('channel_post');expect(telegramMessageShape({reply_to_message:{},forward_origin:{},text:'/status@funi_bot'})).toEqual({isReply:true,isForward:true,isMention:true});});
});
