import { describe,expect,it } from 'vitest';
import { mkdtempSync,rmSync,readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { migrateSqlite, SqliteLedgerRepository } from '@funi/ledger';
import { compactLabel, poolListingPage, poolListingSummary, rankPoolListing, unavailablePoolListingPage, type PoolListing, type PoolListingItem } from '../apps/telegram-lp-bot/src/pool-selection-ux.js';
import { telegramCallbackData } from '../apps/telegram-lp-bot/src/callback-data.js';

function listing(){const items:PoolListingItem[]=[...Array.from({length:12},(_,i)=>({section:'v4_eligible' as const,rank:i,label:`v4 ${String(i).padStart(2,'0')}`,data:`v4-pool:${i}`})),...Array.from({length:3},(_,i)=>({section:'v3_eligible' as const,rank:i,label:`v3 ${i}`,data:`pool:s:${i}`}))];return {tokenSymbol:'AI',tokenAddress:'0xai',items:rankPoolListing(items),counts:{v4Eligible:12,v3Eligible:3,v4Unavailable:0,zeroLiquidity:1,checking:1,unsupported:1}} satisfies PoolListing;}

describe('Telegram all-pool v4-first listing',()=>{
 it('keeps every eligible pool accessible across first, middle, and last pages',()=>{const value=listing(),first=poolListingPage(value,0),middle=poolListingPage(value,1),last=poolListingPage(value,99);expect(first.totalPages).toBe(2);expect(first.items).toHaveLength(9);expect(middle.items).toHaveLength(6);expect(last.current).toBe(1);expect(new Set([...first.items,...middle.items].map(x=>x.data)).size).toBe(15);expect([...first.items,...middle.items].filter(x=>x.section==='v4_eligible')).toHaveLength(12);expect([...first.items,...middle.items].filter(x=>x.section==='v3_eligible')).toHaveLength(3);});
 it('places all v4 rows before v3 and exposes no hidden selection callbacks',()=>{const items=listing().items;expect(items.slice(0,12).map(x=>x.data)).toEqual(Array.from({length:12},(_,i)=>`v4-pool:${i}`));expect(items.slice(12).every(x=>x.section==='v3_eligible')).toBe(true);expect(items.every(x=>!x.data.includes('unavailable')&&!x.data.includes('checking'))).toBe(true);});
 it('has stable page boundaries',()=>{const value=listing(),first=poolListingPage(value,0),last=poolListingPage(value,1);expect(first.hasPrevious).toBe(false);expect(first.hasNext).toBe(true);expect(last.hasPrevious).toBe(true);expect(last.hasNext).toBe(false);});
 it('renders terminal-evidence summary and Telegram-safe labels without transaction data',()=>{const value=listing(),summary=poolListingSummary(value,0);expect(summary).toContain('Eligible v4: 12 · eligible v3: 3');expect(summary).toContain('v4 prioritized.');expect(summary).toContain('Checking: 1 · No active liquidity: 1 · Not initialized: 0 · Evidence unavailable: 0 · Unsupported: 1');expect(compactLabel('x'.repeat(100))).toHaveLength(58);expect(value.items.every(x=>!x.data.includes('open-canary')&&!x.data.includes('v4-open'))).toBe(true);});
 it('keeps unavailable and checking pools out of executable pages while exposing unavailable rows only as information',()=>{const unavailable:PoolListing={tokenSymbol:'AI',tokenAddress:'0xai',items:[],unavailableItems:[{section:'v4_unavailable',rank:0,label:'UNAVAILABLE · EXTREME_STATIC_FEE · AI/USDG',data:''},{section:'v4_unavailable',rank:1,label:'UNAVAILABLE · NONZERO_HOOK_UNSUPPORTED · AI/USDG',data:''}],counts:{v4Eligible:0,v3Eligible:0,v4Unavailable:2,zeroLiquidity:0,checking:0,evidenceUnavailable:3,unsupported:2}};const normal=poolListingPage(unavailable,0),informational=unavailablePoolListingPage(unavailable,0),summary=poolListingSummary(unavailable,0);expect(normal.items).toEqual([]);expect(summary).toContain('No executable pools currently found.');expect(summary).toContain('Checking: 0 · No active liquidity: 0 · Not initialized: 0 · Evidence unavailable: 3 · Unsupported: 2');expect(informational.items.map(item=>item.label)).toEqual(['UNAVAILABLE · EXTREME_STATIC_FEE · AI/USDG','UNAVAILABLE · NONZERO_HOOK_UNSUPPORTED · AI/USDG']);expect([...normal.items,...informational.items].every(item=>!item.data.startsWith('v4-pool:')&&!item.data.startsWith('pool:'))).toBe(true);});
 it('filters unavailable rows from a pre-reload listing while retaining them for the read-only subview',()=>{const legacy:PoolListing={tokenSymbol:'AI',tokenAddress:'0xai',items:[{section:'v4_unavailable',label:'UNAVAILABLE · EXTREME_STATIC_FEE · AI/USDG',data:'pool-unavailable:EXTREME_STATIC_FEE'}],counts:{v4Eligible:0,v3Eligible:0,v4Unavailable:1,zeroLiquidity:0,checking:0,unsupported:1}};expect(poolListingPage(legacy,0).items).toEqual([]);expect(unavailablePoolListingPage(legacy,0).items).toHaveLength(1);expect(poolListingSummary(legacy,0)).toContain('No executable pools currently found.');});
 it('routes unavailable pagination only to its read-only view and keeps the normal renderer executable-only',()=>{const source=readFileSync('apps/telegram-lp-bot/src/index.ts','utf8'),persist=source.slice(source.indexOf('function persistPoolListing'),source.indexOf('async function rankV4CandidatesForTelegram')),normalItems=persist.slice(persist.indexOf('const items'),persist.indexOf('unavailableItems:')),normal=source.slice(source.indexOf('function poolListingRender'),source.indexOf('function messageNotModified')),unavailable=source.slice(source.indexOf('function renderUnavailablePoolListing'),source.indexOf('async function pageUnavailablePoolListing'));expect(persist).toContain('items: rankPoolListing(items)');expect(persist).toContain('unavailableItems');expect(normalItems).not.toContain('...unsupportedV4.map');expect(normal).toContain('Show unavailable pools');expect(normal).toContain('direct-lookup-retry:');expect(unavailable).toContain('informational only. They cannot be selected or executed.');expect(unavailable).not.toContain('v4-pool:');expect(source).toContain('bot.callbackQuery(/^pool-unavailable-page:([^:]+):(\\d+)$/');expect(source).not.toContain('bot.callbackQuery(/^pool-unavailable:/');});
 it('keeps unavailable pagination and refresh callback data within Telegram’s 64-byte limit',()=>{for(const data of ['pool-unavailable-page:00000000-0000-0000-0000-000000000000:0','pool-page:00000000-0000-0000-0000-000000000000:0','direct-lookup-retry:0x0000000000000000000000000000000000000000'])expect(Buffer.byteLength(telegramCallbackData(data),'utf8')).toBeLessThanOrEqual(64);});
 it('renders an unleased worker stall distinctly from an actively worked timeout',()=>{const source=readFileSync('apps/telegram-lp-bot/src/index.ts','utf8'),terminal=source.slice(source.indexOf('function terminalLookupRender'),source.indexOf('function persistPoolListing'));expect(terminal).toContain('DIRECT_LOOKUP_WORKER_NOT_LEASED');expect(terminal).toContain('worker did not start this request');expect(terminal).toContain('Pool lookup timed out safely.');});
 it('is deterministic under reordered input and duplicate page callbacks are read-only',()=>{const value=listing(),again=rankPoolListing([...value.items].reverse());expect(again.map(x=>x.data)).toEqual(value.items.map(x=>x.data));expect(poolListingPage(value,1)).toEqual(poolListingPage(value,1));});
 it('keeps all immutable v4 selections through pagination and supersedes them only for a replacement session',()=>{const dir=mkdtempSync(join(tmpdir(),'funi-pages-')),path=join(dir,'ledger.sqlite');migrateSqlite(path,join(process.cwd(),'infra/migrations'));const repo=new SqliteLedgerRepository(path);try{const first='first',second='second',key={currency0:'0x0000000000000000000000000000000000000001',currency1:'0x0000000000000000000000000000000000000002',fee:500,tickSpacing:10,hooks:'0x0000000000000000000000000000000000000000'};const ids=Array.from({length:12},(_,index)=>String(repo.createV4PoolSelection({userId:'u',chatId:'c',sessionId:first,poolId:`0x${String(index).padStart(64,'0')}`,poolKey:key,discoveryBlock:1n,liquidity:1n,eligibility:true,supersedeExisting:false,expiresAtMs:2_000}).id));expect(ids.every(id=>Number(repo.v4PoolSelection(id)?.superseded)===0)).toBe(true);poolListingPage(listing(),0);poolListingPage(listing(),1);expect(ids.every(id=>Number(repo.v4PoolSelection(id)?.superseded)===0)).toBe(true);repo.supersedeOtherV4PoolSelections('u','c',second);expect(ids.every(id=>Number(repo.v4PoolSelection(id)?.superseded)===1)).toBe(true);}finally{repo.close();rmSync(dir,{recursive:true,force:true});}});
});
