import { describe,expect,it } from 'vitest';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { migrateSqlite, SqliteLedgerRepository } from '@robin/ledger';
import { compactLabel, poolListingPage, poolListingSummary, rankPoolListing, type PoolListing, type PoolListingItem } from '../apps/telegram-lp-bot/src/pool-selection-ux.js';

function listing(){const items:PoolListingItem[]=[...Array.from({length:12},(_,i)=>({section:'v4_eligible' as const,rank:i,label:`v4 ${String(i).padStart(2,'0')}`,data:`v4-pool:${i}`})),...Array.from({length:3},(_,i)=>({section:'v3_eligible' as const,rank:i,label:`v3 ${i}`,data:`pool:s:${i}`}))];return {tokenSymbol:'AI',tokenAddress:'0xai',items:rankPoolListing(items),counts:{v4Eligible:12,v3Eligible:3,v4Unavailable:0,zeroLiquidity:1,checking:1,unsupported:1}} satisfies PoolListing;}

describe('Telegram all-pool v4-first listing',()=>{
 it('keeps every eligible pool accessible across first, middle, and last pages',()=>{const value=listing(),first=poolListingPage(value,0),middle=poolListingPage(value,1),last=poolListingPage(value,99);expect(first.totalPages).toBe(2);expect(first.items).toHaveLength(9);expect(middle.items).toHaveLength(6);expect(last.current).toBe(1);expect(new Set([...first.items,...middle.items].map(x=>x.data)).size).toBe(15);expect([...first.items,...middle.items].filter(x=>x.section==='v4_eligible')).toHaveLength(12);expect([...first.items,...middle.items].filter(x=>x.section==='v3_eligible')).toHaveLength(3);});
 it('places all v4 rows before v3 and exposes no hidden selection callbacks',()=>{const items=listing().items;expect(items.slice(0,12).map(x=>x.data)).toEqual(Array.from({length:12},(_,i)=>`v4-pool:${i}`));expect(items.slice(12).every(x=>x.section==='v3_eligible')).toBe(true);expect(items.every(x=>!x.data.includes('unavailable')&&!x.data.includes('checking'))).toBe(true);});
 it('has stable page boundaries',()=>{const value=listing(),first=poolListingPage(value,0),last=poolListingPage(value,1);expect(first.hasPrevious).toBe(false);expect(first.hasNext).toBe(true);expect(last.hasPrevious).toBe(true);expect(last.hasNext).toBe(false);});
 it('renders active-liquidity summary and Telegram-safe labels without transaction data',()=>{const value=listing(),summary=poolListingSummary(value,0);expect(summary).toContain('Eligible v4: 12 · eligible v3: 3');expect(summary).toContain('v4 prioritized.');expect(summary).toContain('Hidden: zero liquidity 1; checking 1; unsupported 1');expect(compactLabel('x'.repeat(100))).toHaveLength(58);expect(value.items.every(x=>!x.data.includes('open-canary')&&!x.data.includes('v4-open'))).toBe(true);});
 it('is deterministic under reordered input and duplicate page callbacks are read-only',()=>{const value=listing(),again=rankPoolListing([...value.items].reverse());expect(again.map(x=>x.data)).toEqual(value.items.map(x=>x.data));expect(poolListingPage(value,1)).toEqual(poolListingPage(value,1));});
 it('keeps all immutable v4 selections through pagination and supersedes them only for a replacement session',()=>{const dir=mkdtempSync(join(tmpdir(),'robin-pages-')),path=join(dir,'ledger.sqlite');migrateSqlite(path,join(process.cwd(),'infra/migrations'));const repo=new SqliteLedgerRepository(path);try{const first='first',second='second',key={currency0:'0x0000000000000000000000000000000000000001',currency1:'0x0000000000000000000000000000000000000002',fee:500,tickSpacing:10,hooks:'0x0000000000000000000000000000000000000000'};const ids=Array.from({length:12},(_,index)=>String(repo.createV4PoolSelection({userId:'u',chatId:'c',sessionId:first,poolId:`0x${String(index).padStart(64,'0')}`,poolKey:key,discoveryBlock:1n,liquidity:1n,eligibility:true,supersedeExisting:false,expiresAtMs:2_000}).id));expect(ids.every(id=>Number(repo.v4PoolSelection(id)?.superseded)===0)).toBe(true);poolListingPage(listing(),0);poolListingPage(listing(),1);expect(ids.every(id=>Number(repo.v4PoolSelection(id)?.superseded)===0)).toBe(true);repo.supersedeOtherV4PoolSelections('u','c',second);expect(ids.every(id=>Number(repo.v4PoolSelection(id)?.superseded)===1)).toBe(true);}finally{repo.close();rmSync(dir,{recursive:true,force:true});}});
});
