import { describe, expect, it } from 'vitest';
import { keccak256, type Hex } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { broadcastSignedTransaction, bufferedBroadcastGasPrice, type BroadcastTransportEvidence } from '../apps/cli/src/transaction-boundary.js';

const account=privateKeyToAccount(`0x${'11'.repeat(32)}`);
async function signed(){return account.signTransaction({chainId:4663,nonce:16,to:'0x00000000000000000000000000000000000000aa',data:'0x095ea7b3',value:0n,gas:49_425n,gasPrice:29_042_000n});}
function client(request:(args:any,options?:any)=>Promise<unknown>){return {request} as any;}

describe('canonical raw transaction broadcaster',()=>{
 it('buffers the observed legacy gas price by 1.10x before signing',()=>{expect(bufferedBroadcastGasPrice(28_268_000n)).toBe(31_094_800n);expect([1n,9n,10n,11n,101n].map(bufferedBroadcastGasPrice)).toEqual([1n,9n,11n,12n,111n]);expect(()=>bufferedBroadcastGasPrice(0n)).toThrow('TRANSACTION_GAS_PRICE_INVALID');});
 it('invokes exactly eth_sendRawTransaction with one serialized-byte parameter and records provider response separately',async()=>{const serialized=await signed(),expectedHash=keccak256(serialized),calls:any[]=[],evidence:BroadcastTransportEvidence[]=[];const returned=await broadcastSignedTransaction({walletClient:client(async(args,options)=>(calls.push({args,options}),expectedHash)),serializedTransaction:serialized,expectedHash,expectedSender:account.address,expectedChainId:4663,expectedNonce:16,providerIndex:2,providerName:'synthetic-provider',onEvidence:item=>{evidence.push(item);}});expect(returned).toBe(expectedHash);expect(calls).toEqual([{args:{method:'eth_sendRawTransaction',params:[serialized]},options:{retryCount:0}}]);expect(evidence).toEqual([expect.objectContaining({method:'eth_sendRawTransaction',parameterCount:1,serializedByteLength:(serialized.length-2)/2,classification:'REQUESTED',expectedHashReturnedHashEqual:null}),expect.objectContaining({classification:'ACCEPTED',expectedHashReturnedHashEqual:true})]);expect(JSON.stringify(evidence)).not.toContain(serialized);});
 it('fails closed when the provider hash differs from the local expected hash',async()=>{const serialized=await signed(),expectedHash=keccak256(serialized),other=`0x${'22'.repeat(32)}` as const,evidence:BroadcastTransportEvidence[]=[];await expect(broadcastSignedTransaction({walletClient:client(async()=>other),serializedTransaction:serialized,expectedHash,expectedSender:account.address,expectedChainId:4663,expectedNonce:16,onEvidence:item=>{evidence.push(item);}})).rejects.toThrow('TRANSACTION_PROVIDER_RETURNED_HASH_MISMATCH');expect(evidence.at(-1)).toMatchObject({classification:'HASH_MISMATCH',expectedHashReturnedHashEqual:false});});
 it.each([undefined,null,'0x1234',{}])('rejects malformed or missing provider response %p',async response=>{const serialized=await signed(),expectedHash=keccak256(serialized);await expect(broadcastSignedTransaction({walletClient:client(async()=>response),serializedTransaction:serialized,expectedHash,expectedSender:account.address,expectedChainId:4663,expectedNonce:16})).rejects.toThrow('TRANSACTION_BROADCAST_RESPONSE_MALFORMED');});
 it('sanitizes a transport error without retaining URL credentials or serialized bytes',async()=>{const serialized=await signed(),expectedHash=keccak256(serialized),evidence:BroadcastTransportEvidence[]=[];await expect(broadcastSignedTransaction({walletClient:client(async()=>{throw new Error('HTTP 401 https://rpc.example/v2/synthetic-secret-key');}),serializedTransaction:serialized,expectedHash,expectedSender:account.address,expectedChainId:4663,expectedNonce:16,onEvidence:item=>{evidence.push(item);}})).rejects.toThrow('TRANSACTION_BROADCAST_TRANSPORT_ERROR');const text=JSON.stringify(evidence);expect(text).not.toContain('synthetic-secret-key');expect(text).not.toContain(serialized);expect(evidence.at(-1)).toMatchObject({classification:'TRANSPORT_ERROR'});});
 it('rejects malformed bytes and a wrong signed envelope before transport invocation',async()=>{let calls=0;await expect(broadcastSignedTransaction({walletClient:client(async()=>{calls++;return `0x${'00'.repeat(32)}`;}),serializedTransaction:'0x12' as Hex,expectedHash:`0x${'00'.repeat(32)}`,expectedSender:account.address,expectedChainId:4663,expectedNonce:16})).rejects.toThrow('TRANSACTION_SERIALIZED_BYTES_MALFORMED');const serialized=await signed();await expect(broadcastSignedTransaction({walletClient:client(async()=>{calls++;return keccak256(serialized);}),serializedTransaction:serialized,expectedHash:keccak256(serialized),expectedSender:account.address,expectedChainId:4663,expectedNonce:17})).rejects.toThrow('TRANSACTION_SIGNED_ENVELOPE_MISMATCH');expect(calls).toBe(0);});
 it('preserves identical bytes, nonce, and hash across one explicit second transport invocation',async()=>{const serialized=await signed(),expectedHash=keccak256(serialized),params:unknown[]=[];for(const providerIndex of [0,1])await broadcastSignedTransaction({walletClient:client(async args=>(params.push(args.params[0]),expectedHash)),serializedTransaction:serialized,expectedHash,expectedSender:account.address,expectedChainId:4663,expectedNonce:16,providerIndex});expect(params).toEqual([serialized,serialized]);expect(keccak256(params[0] as Hex)).toBe(expectedHash);expect(keccak256(params[1] as Hex)).toBe(expectedHash);});
});
