import { describe,expect,it } from 'vitest';
import { encodeAbiParameters } from 'viem';
import { amountsForLiquidity, buildGenericV4SingleSidedDownsidePlan, buildPermit2Approval, buildStrictToken1Plan, buildV4Burn, buildV4Collect, buildV4Decrease, buildV4Mint, buildV4SingleSidedDownsidePlan, decodePositionInfo, decodeV4Lifecycle, decodeV4Mint, inspectV4PositionTerminalAware, isCanonicalV4NotMinted, poolId, slippageMinimums, sqrtPriceAtTick, V4_ACTIONS, v4ApprovalRequirement, type V4PoolKey } from '@funi/v4';
const key:V4PoolKey={currency0:'0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73',currency1:'0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168',fee:500,tickSpacing:10,hooks:'0x0000000000000000000000000000000000000000'};
const owner='0x70997970C51812dc3A010C7d01b50e0d17dc79C8' as const;
describe('Uniswap v4 mint adapter',()=>{
 it('encodes deployed MINT_POSITION then SETTLE_PAIR and round-trips',()=>{const p=buildV4Mint({key,tickLower:-201620,tickUpper:-200560,liquidity:2193110814363n,amount0Max:0n,amount1Max:5_000_000n,owner,hookData:'0x',deadline:123n}),d=decodeV4Mint(p.calldata);expect(p.actions).toBe('0x020d');expect(d.actions).toBe('0x020d');expect(d.mint).toMatchObject({tickLower:-201620,tickUpper:-200560,liquidity:2193110814363n,amount0Max:0n,amount1Max:5_000_000n,owner});expect(d.settle).toEqual([key.currency0,key.currency1]);expect(p.actions).not.toContain(V4_ACTIONS.MINT_POSITION_FROM_DELTAS.toString(16).padStart(2,'0'));});
 it('constructs an exact strictly token1-only range',()=>{const plan=buildStrictToken1Plan({id:poolId(key),key,sqrtPriceX96:sqrtPriceAtTick(-200555),tick:-200555,liquidity:1n,initialized:true,blockNumber:1n},5_000_000n,owner,999n);expect(plan.tickUpper).toBe(-200560);expect(plan.currentTick).toBeGreaterThanOrEqual(plan.tickUpper);expect(plan.amount0Max).toBe(0n);expect(plan.amount0Expected).toBe(0n);expect(plan.amount1Expected).toBeGreaterThan(0n);expect(plan.amount1Max).toBe(5_000_000n);});
 it('preserves an exact-zero target for either funding ordering',()=>{const pool={id:poolId(key),key,sqrtPriceX96:sqrtPriceAtTick(-200560),tick:-200560,liquidity:1n,initialized:true,blockNumber:1n},token1=buildGenericV4SingleSidedDownsidePlan({pool,target:key.currency0,funding:key.currency1,fundingAmount:5_000_000n,owner,deadline:999n,range:{upperDropPct:0,lowerDropPct:10}}),token0=buildGenericV4SingleSidedDownsidePlan({pool,target:key.currency1,funding:key.currency0,fundingAmount:5_000_000n,owner,deadline:999n,range:{upperDropPct:0,lowerDropPct:10}});expect(token1.amount0Expected).toBe(0n);expect(token1.amount1Expected).toBeGreaterThan(0n);expect(token0.amount1Expected).toBe(0n);expect(token0.amount0Expected).toBeGreaterThan(0n);});
 it.each([10,30,50,60])('builds refreshed current-to-%i%% presets with aligned funding-only ticks',(lowerDropPct)=>{const pool={id:poolId(key),key,sqrtPriceX96:sqrtPriceAtTick(-200555),tick:-200555,liquidity:1n,initialized:true,blockNumber:1n},plan=buildV4SingleSidedDownsidePlan(pool,5_000_000n,owner,999n,{upperDropPct:0,lowerDropPct});expect(Math.abs(plan.tickLower%10)).toBe(0);expect(Math.abs(plan.tickUpper%10)).toBe(0);expect(plan.currentTick).toBeGreaterThanOrEqual(plan.tickUpper);expect(plan.amount0Expected).toBe(0n);expect(plan.amount1Expected).toBeGreaterThan(0n);expect(plan.requestedRange.lowerDropPct).toBe(lowerDropPct);});
 it('matches v3 custom semantics and rejects inverted/extreme input',()=>{const pool={id:poolId(key),key,sqrtPriceX96:sqrtPriceAtTick(-200555),tick:-200555,liquidity:1n,initialized:true,blockNumber:1n},plan=buildV4SingleSidedDownsidePlan(pool,5_000_000n,owner,999n,{upperDropPct:30,lowerDropPct:60});expect(plan.tickLower).toBeLessThan(plan.tickUpper);expect(plan.amount0Max).toBe(0n);for(const range of [{upperDropPct:30,lowerDropPct:30},{upperDropPct:60,lowerDropPct:30},{upperDropPct:-1,lowerDropPct:30},{upperDropPct:0,lowerDropPct:100},{upperDropPct:NaN,lowerDropPct:30}])expect(()=>buildV4SingleSidedDownsidePlan(pool,5_000_000n,owner,999n,range)).toThrow('0 <= upperDropPct');});
 it('rejects zero liquidity and target-side caps',()=>{expect(()=>buildStrictToken1Plan({id:poolId(key),key,sqrtPriceX96:1n,tick:-200555,liquidity:0n,initialized:true,blockNumber:1n},5_000_000n,owner,1n)).toThrow('V4_POOL_ZERO');expect(()=>buildV4Mint({key,tickLower:-2,tickUpper:-1,liquidity:1n,amount0Max:1n,amount1Max:1n,owner,hookData:'0x',deadline:1n})).toThrow('V4_TARGET_AMOUNT');});
 it('decodes signed packed position ticks deterministically',()=>{const enc=(BigInt((-201620)&0xffffff)<<8n)|(BigInt((-200560)&0xffffff)<<32n);expect(decodePositionInfo(enc)).toMatchObject({tickLower:-201620,tickUpper:-200560,hasSubscriber:false});});
 it('uses finite exact Permit2 authorization and refreshable nonce state',()=>{const approval=buildPermit2Approval(key.currency1,5_000_000n,10_000n);expect(approval.amount).toBe(5_000_000n);expect(approval.expiration).toBe(10_000n);expect(v4ApprovalRequirement(0n,[0n,0,7],5_000_000n,1n)).toBe('ERC20_TO_PERMIT2_REQUIRED');expect(v4ApprovalRequirement(5_000_000n,[0n,0,7],5_000_000n,1n)).toBe('PERMIT2_TO_POSITION_MANAGER_REQUIRED');expect(v4ApprovalRequirement(5_000_000n,[5_000_000n,10_000,7],5_000_000n,1n)).toBe('READY_TO_MINT');expect(()=>buildPermit2Approval(key.currency1,2n**160n,10n)).toThrow();});
});
describe('v4 terminal position interpretation',()=>{
 const data=`0x08c379a0${encodeAbiParameters([{type:'string'}],['NOT_MINTED']).slice(2)}` as const,error={data};
 it('requires canonical NOT_MINTED plus durable burn evidence',async()=>{expect(isCanonicalV4NotMinted(error)).toBe(true);const rpc={withClient:async(fn:any)=>fn({readContract:async()=>{throw error;}})} as any;await expect(inspectV4PositionTerminalAware(rpc,305784n,{previouslyMinted:true,burnConfirmed:true,burnTxHash:'0x1234'})).resolves.toMatchObject({status:'burned',terminal:true,owner:null,onchainLiquidity:0n,nftExists:false});await expect(inspectV4PositionTerminalAware(rpc,999999n)).resolves.toMatchObject({status:'not_found',terminal:false});});
 it('fails closed on an unknown revert',async()=>{const rpc={withClient:async(fn:any)=>fn({readContract:async()=>{throw {data:'0xdeadbeef'};}})} as any;await expect(inspectV4PositionTerminalAware(rpc,1n,{previouslyMinted:true,burnConfirmed:true,burnTxHash:'0x1234'})).rejects.toBeTruthy();});
});
describe('Uniswap v4 lifecycle codec',()=>{
 it('encodes fee collection as zero DECREASE plus TAKE_PAIR',()=>{const plan=buildV4Collect({tokenId:7n,recipient:owner,hookData:'0x',key,deadline:100n}),decoded=decodeV4Lifecycle(plan.calldata);expect(plan.actions).toBe('0x0111');expect(decoded).toMatchObject({kind:'collect',tokenId:7n,liquidity:0n,amount0Min:0n,amount1Min:0n});expect(decoded.take).toEqual([key.currency0,key.currency1,owner]);});
 it('round trips partial/full decreases with protected minimums',()=>{const plan=buildV4Decrease({tokenId:8n,liquidity:500n,amount0Min:12n,amount1Min:34n,recipient:owner,hookData:'0x1234',key,deadline:101n});expect(decodeV4Lifecycle(plan.calldata)).toMatchObject({kind:'decrease',tokenId:8n,liquidity:500n,amount0Min:12n,amount1Min:34n,hookData:'0x1234'});expect(plan.actions).not.toContain(V4_ACTIONS.MINT_POSITION_FROM_DELTAS.toString(16).padStart(2,'0'));});
 it('encodes burn plus TAKE_PAIR for an executor-validated empty position',()=>{const plan=buildV4Burn({tokenId:9n,amount0Min:0n,amount1Min:0n,recipient:owner,hookData:'0x',key,deadline:102n});expect(plan.actions).toBe('0x0311');expect(decodeV4Lifecycle(plan.calldata)).toMatchObject({kind:'burn',tokenId:9n});});
 it('computes partial principal and slippage deterministically',()=>{const amount=amountsForLiquidity(sqrtPriceAtTick(-200600),-201620,-200560,1_000_000n),mins=slippageMinimums(amount,50);expect(amount.token0+amount.token1).toBeGreaterThan(0n);expect(mins.amount0Min).toBeLessThanOrEqual(amount.token0);expect(mins.amount1Min).toBeLessThanOrEqual(amount.token1);});
});
