import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { decodeAbiParameters, decodeFunctionData, encodeAbiParameters, encodeEventTopics, encodeFunctionData, parseAbiItem, toHex, zeroAddress, type Address, type Hex } from 'viem';
import { migrateSqlite, SqliteLedgerRepository } from '@funi/ledger';
import { buildV4BatchCollect, buildV4BatchFullDecrease, buildV4BatchMint, decodeV4BatchCollect, decodeV4BatchFullDecrease, decodeV4BatchMint, poolId, positionManagerAbi, reconcileV4BatchCollectReceipt, reconcileV4BatchFullDecreaseReceipt, reconcileV4BatchMintReceipt, sqrtPriceAtTick, V4_ACTIONS, V4_ROBINHOOD_DEPLOYMENTS, type V4ConfirmedReceipt, type V4ExpectedCloseIdentity, type V4PoolKey, type V4PositionProof, type V4ReceiptLog } from '@funi/v4';
import { planV4BidLadderV1, v4BidLadderPersistencePlan } from '../apps/cli/src/v4-bid-ladder-planner.js';

const roots:string[]=[];
afterEach(()=>{for(const root of roots.splice(0))rmSync(root,{recursive:true,force:true});});
const currency0='0x0000000000000000000000000000000000000011' as const,currency1='0x0000000000000000000000000000000000000022' as const,owner='0x0000000000000000000000000000000000000033' as const,other='0x0000000000000000000000000000000000000044' as const;
const key:V4PoolKey={currency0,currency1,fee:3000,tickSpacing:10,hooks:zeroAddress};
const txHash=`0x${'ab'.repeat(32)}` as Hex;
const transferEvent=parseAbiItem('event Transfer(address indexed from,address indexed to,uint256 indexed id)');
const erc20TransferEvent=parseAbiItem('event Transfer(address indexed from,address indexed to,uint256 value)');
const modifyLiquidityEvent=parseAbiItem('event ModifyLiquidity(bytes32 indexed id,address indexed sender,int24 tickLower,int24 tickUpper,int256 liquidityDelta,bytes32 salt)');

function ladder(){const pool={id:poolId(key),key,sqrtPriceX96:sqrtPriceAtTick(0),tick:0,liquidity:1_000_000_000n,initialized:true,blockNumber:123n};return planV4BidLadderV1({ladderId:'batch-ladder',pool,fundingToken:currency1,targetToken:currency0,totalFundingAmount:10_000_000n,fundingDecimals:6,targetDecimals:18,owner,deadline:999_999n,nowMs:1000});}
function batchMint(count=5){const plan=ladder();return {strategy:plan,batch:buildV4BatchMint({legs:plan.legs.slice(0,count).map(leg=>leg.mint),deadline:999_999n})};}
function closeLegs(count=5){const plan=ladder();return plan.legs.slice(0,count).map((leg,index)=>({key,tokenId:101n+BigInt(index),liquidity:leg.mint.liquidity,amount0Min:BigInt(index+1),amount1Min:BigInt(index+2),hookData:index===0?'0x1234' as Hex:'0x' as Hex}));}
function recode(actions:Hex,params:readonly Hex[],deadline=999_999n){const unlockData=encodeAbiParameters([{type:'bytes'},{type:'bytes[]'}],[actions,params]);return encodeFunctionData({abi:positionManagerAbi,functionName:'modifyLiquidities',args:[unlockData,deadline]});}
function receipt(logs:V4ReceiptLog[]):V4ConfirmedReceipt{return {status:'success',transactionHash:txHash,logs};}
function nftTransfer(input:{id:bigint;from?:Address;to?:Address;logIndex:number;address?:Address}):V4ReceiptLog{return {address:input.address??V4_ROBINHOOD_DEPLOYMENTS.positionManager,data:'0x',topics:encodeEventTopics({abi:[transferEvent],eventName:'Transfer',args:{from:input.from??zeroAddress,to:input.to??owner,id:input.id}}) as Hex[],logIndex:input.logIndex,transactionHash:txHash};}
function liquidityChange(expected:V4ExpectedCloseIdentity,logIndex:number):V4ReceiptLog{return {address:V4_ROBINHOOD_DEPLOYMENTS.poolManager,topics:encodeEventTopics({abi:[modifyLiquidityEvent],eventName:'ModifyLiquidity',args:{id:poolId(expected.key),sender:V4_ROBINHOOD_DEPLOYMENTS.positionManager}}) as Hex[],data:encodeAbiParameters([{type:'int24'},{type:'int24'},{type:'int256'},{type:'bytes32'}],[expected.tickLower,expected.tickUpper,-expected.liquidity,toHex(expected.tokenId,{size:32})]),logIndex,transactionHash:txHash};}
function tokenTransfer(token:Address,value:bigint,logIndex:number):V4ReceiptLog{return {address:token,topics:encodeEventTopics({abi:[erc20TransferEvent],eventName:'Transfer',args:{from:V4_ROBINHOOD_DEPLOYMENTS.poolManager,to:owner}}) as Hex[],data:encodeAbiParameters([{type:'uint256'}],[value]),logIndex,transactionHash:txHash};}

describe('V4 native batch mint codec',()=>{
 it.each([2,5])('round-trips a realistic %i-leg planner vector with order preserved',(count)=>{const {strategy,batch}=batchMint(count),decoded=decodeV4BatchMint(batch.calldata);expect(decoded.legs).toHaveLength(count);expect(decoded.legs.map(leg=>[leg.tickLower,leg.tickUpper,leg.liquidity])).toEqual(strategy.legs.slice(0,count).map(leg=>[leg.tickLower,leg.tickUpper,leg.mint.liquidity]));expect(decoded.settle).toEqual([currency0,currency1]);expect(batch.actions).toBe(`0x${'02'.repeat(count)}0d`);expect(decoded.deadline).toBe(999_999n);});
 it('round-trips independent per-leg caps, owner, and hookData',()=>{const {strategy}=batchMint(2),legs=[strategy.legs[0]!.mint,{...strategy.legs[1]!.mint,owner:other,hookData:'0x1234' as Hex}],decoded=decodeV4BatchMint(buildV4BatchMint({legs,deadline:55n}).calldata);expect(decoded.legs.map(leg=>({amount0Max:leg.amount0Max,amount1Max:leg.amount1Max,owner:leg.owner,hookData:leg.hookData}))).toEqual(legs.map(leg=>({amount0Max:leg.amount0Max,amount1Max:leg.amount1Max,owner:leg.owner,hookData:leg.hookData})));});
 it('rejects a mixed PoolKey before encoding',()=>{const {strategy}=batchMint(2),mixed={...strategy.legs[1]!.mint,key:{...key,fee:500}};expect(()=>buildV4BatchMint({legs:[strategy.legs[0]!.mint,mixed],deadline:1n})).toThrow('V4_BATCH_POOL_KEY_MISMATCH');});
 it('rejects missing, duplicate, unexpected, or length-mismatched settlement shapes',()=>{const {batch}=batchMint(2),mintParams=batch.params.slice(0,2),settle=batch.params[2]!;expect(()=>decodeV4BatchMint(recode('0x0202',mintParams))).toThrow('INVALID_V4_BATCH_MINT_ACTIONS');expect(()=>decodeV4BatchMint(recode('0x02020d0d',[...mintParams,settle,settle]))).toThrow('INVALID_V4_BATCH_MINT_ACTIONS');expect(()=>decodeV4BatchMint(recode('0x020211',[...mintParams,settle]))).toThrow('INVALID_V4_BATCH_MINT_ACTIONS');expect(()=>decodeV4BatchMint(recode('0x02020d',mintParams))).toThrow('V4_BATCH_ACTION_PARAM_LENGTH_MISMATCH');});
 it('keeps the strict single-position decoder unchanged',()=>{const {batch}=batchMint(2);const call=decodeFunctionData({abi:positionManagerAbi,data:batch.calldata}),[actions]=decodeAbiParameters([{type:'bytes'},{type:'bytes[]'}],call.args[0] as Hex);expect(actions).toBe('0x02020d');});
});

describe('V4 batch mint receipt reconciliation',()=>{
 function expected(){return ladder().legs.map(leg=>({key,tickLower:leg.tickLower,tickUpper:leg.tickUpper,liquidity:leg.mint.liquidity,owner}));}
 function inspector(legs=expected()){return async(tokenId:bigint):Promise<V4PositionProof>=>{const index=Number(tokenId-101n),leg=legs[index]!;return {tokenId,owner,key:leg.key,tickLower:leg.tickLower,tickUpper:leg.tickUpper,liquidity:leg.liquidity};};}
 it('maps five manager mint Transfers by receipt log order and ignores unrelated NFT transfers',async()=>{const legs=expected(),logs=[nftTransfer({id:999n,to:other,logIndex:0,address:other}),...legs.map((_,index)=>nftTransfer({id:101n+BigInt(index),logIndex:index+2}))].reverse();const result=await reconcileV4BatchMintReceipt({receipt:receipt(logs),expectedLegs:legs,inspectPosition:inspector(legs)});expect(result.status).toBe('FULLY_RECONCILED');expect(result.bindings.map(binding=>[binding.legIndex,binding.tokenId])).toEqual([[0,101n],[1,102n],[2,103n],[3,104n],[4,105n]]);});
 it('fails closed on extra manager mints, recipient ambiguity, or identity mismatch',async()=>{const legs=expected(),base=legs.map((_,index)=>nftTransfer({id:101n+BigInt(index),logIndex:index}));await expect(reconcileV4BatchMintReceipt({receipt:receipt([...base,nftTransfer({id:106n,logIndex:6})]),expectedLegs:legs,inspectPosition:inspector(legs)})).rejects.toThrow('V4_BATCH_MINT_TRANSFER_COUNT_AMBIGUOUS');await expect(reconcileV4BatchMintReceipt({receipt:receipt(base.map((log,index)=>index===2?nftTransfer({id:103n,to:other,logIndex:2}):log)),expectedLegs:legs,inspectPosition:inspector(legs)})).rejects.toThrow('V4_BATCH_MINT_RECIPIENT_ORDER_MISMATCH');await expect(reconcileV4BatchMintReceipt({receipt:receipt(base),expectedLegs:legs,inspectPosition:async id=>({...await inspector(legs)(id),tickLower:-999})})).rejects.toThrow('V4_BATCH_POSITION_IDENTITY_MISMATCH');});
});

describe('V4 native batch full-decrease codec and close reconciliation',()=>{
 it.each([2,5])('round-trips %i ordered full decreases plus exactly one TAKE_PAIR with no burn',(count)=>{const legs=closeLegs(count),batch=buildV4BatchFullDecrease({legs,recipient:owner,deadline:888n}),decoded=decodeV4BatchFullDecrease(batch.calldata,{key,recipient:owner});expect(decoded.legs.map(leg=>[leg.tokenId,leg.liquidity,leg.amount0Min,leg.amount1Min,leg.hookData])).toEqual(legs.map(leg=>[leg.tokenId,leg.liquidity,leg.amount0Min,leg.amount1Min,leg.hookData]));expect(batch.actions).toBe(`0x${'01'.repeat(count)}11`);expect(decoded.bytes.filter(action=>action===V4_ACTIONS.TAKE_PAIR)).toHaveLength(1);expect(decoded.bytes).not.toContain(V4_ACTIONS.BURN_POSITION);expect(decoded.take).toEqual([currency0,currency1,owner]);});
 it('rejects missing, duplicate, or unexpected terminal TAKE_PAIR shapes',()=>{const batch=buildV4BatchFullDecrease({legs:closeLegs(2),recipient:owner,deadline:1n}),decreases=batch.params.slice(0,2),take=batch.params[2]!;expect(()=>decodeV4BatchFullDecrease(recode('0x0101',decreases))).toThrow('INVALID_V4_BATCH_DECREASE_ACTIONS');expect(()=>decodeV4BatchFullDecrease(recode('0x01011111',[...decreases,take,take]))).toThrow('INVALID_V4_BATCH_DECREASE_ACTIONS');expect(()=>decodeV4BatchFullDecrease(recode('0x01010d',[...decreases,take]))).toThrow('INVALID_V4_BATCH_DECREASE_ACTIONS');});
 it('rejects mixed leg pools and unexpected TAKE_PAIR currency or recipient',()=>{const legs=closeLegs(2),mixed={...legs[1]!,key:{...key,fee:500}};expect(()=>buildV4BatchFullDecrease({legs:[legs[0]!,mixed],recipient:owner,deadline:1n})).toThrow('V4_BATCH_POOL_KEY_MISMATCH');const batch=buildV4BatchFullDecrease({legs,recipient:owner,deadline:1n});expect(()=>decodeV4BatchFullDecrease(batch.calldata,{key:{...key,currency1:other}})).toThrow('V4_BATCH_TAKE_PAIR_MISMATCH');expect(()=>decodeV4BatchFullDecrease(batch.calldata,{key,recipient:other})).toThrow('V4_BATCH_TAKE_RECIPIENT_MISMATCH');});
 it('proves all five exact removals, zero post-close liquidity, live NFTs, and aggregate wallet assets',async()=>{const source=closeLegs(5),expected:V4ExpectedCloseIdentity[]=source.map(leg=>({...leg,owner,tickLower:ladder().legs[Number(leg.tokenId-101n)]!.tickLower,tickUpper:ladder().legs[Number(leg.tokenId-101n)]!.tickUpper})),logs=[...expected.map((leg,index)=>liquidityChange(leg,index)),tokenTransfer(currency0,12_345n,10),tokenTransfer(currency1,67_890n,11)];const result=await reconcileV4BatchFullDecreaseReceipt({receipt:receipt(logs),expectedLegs:expected,recipient:owner,inspectPosition:async id=>{const leg=expected[Number(id-101n)]!;return {...leg,liquidity:0n};}});expect(result.status).toBe('FULLY_RECONCILED');expect(result.legs).toHaveLength(5);expect(result.legs.every(leg=>leg.onchainLiquidity===0n&&leg.nftExists)).toBe(true);expect(result.aggregateTransfers).toMatchObject({token0:12_345n,token1:67_890n,evidence:'POOL_MANAGER_ERC20_TRANSFERS'});expect(result).toMatchObject({nftBurned:false,swapInvoked:false,perLegAssetAttribution:'UNAVAILABLE_FROM_AGGREGATE_TAKE_PAIR'});});
 it('fails closed if any leg remains liquid or any expected NFT is burned',async()=>{const source=closeLegs(5),strategy=ladder(),expected:V4ExpectedCloseIdentity[]=source.map((leg,index)=>({...leg,owner,tickLower:strategy.legs[index]!.tickLower,tickUpper:strategy.legs[index]!.tickUpper})),changes=expected.map((leg,index)=>liquidityChange(leg,index));await expect(reconcileV4BatchFullDecreaseReceipt({receipt:receipt(changes),expectedLegs:expected,recipient:owner,inspectPosition:async id=>({...expected[Number(id-101n)]!,liquidity:id===103n?1n:0n})})).rejects.toThrow('V4_BATCH_CLOSE_NONZERO_ONCHAIN_LIQUIDITY');await expect(reconcileV4BatchFullDecreaseReceipt({receipt:receipt([...changes,nftTransfer({id:103n,from:owner,to:zeroAddress,logIndex:9})]),expectedLegs:expected,recipient:owner,inspectPosition:async id=>({...expected[Number(id-101n)]!,liquidity:0n})})).rejects.toThrow('V4_BATCH_CLOSE_NFT_BURN_DETECTED');});
 it('keeps the close batch limited to liquidity-management actions',()=>{const batch=buildV4BatchFullDecrease({legs:closeLegs(5),recipient:owner,deadline:1n});expect(batch.actions).not.toContain(V4_ACTIONS.SWAP_EXACT_IN_SINGLE.toString(16).padStart(2,'0'));expect(batch.calldata.slice(0,10)).toBe(encodeFunctionData({abi:positionManagerAbi,functionName:'modifyLiquidities',args:['0x',0n]}).slice(0,10));});
});

describe('V4 five-NFT collect-only batch',()=>{
 const expected=()=>closeLegs(5).map((leg,index)=>({...leg,owner,tickLower:ladder().legs[index]!.tickLower,tickUpper:ladder().legs[index]!.tickUpper}));
 it('uses five zero-liquidity decreases, one TAKE_PAIR, and no burn or swap',()=>{const legs=closeLegs(5).map(({key,tokenId,hookData})=>({key,tokenId,hookData})),batch=buildV4BatchCollect({legs,recipient:owner,deadline:888n}),decoded=decodeV4BatchCollect(batch.calldata,{key,recipient:owner});expect(decoded.legs.map(leg=>leg.liquidity)).toEqual([0n,0n,0n,0n,0n]);expect(batch.actions).toBe(`0x${'01'.repeat(5)}11`);expect(decoded.bytes).not.toContain(V4_ACTIONS.BURN_POSITION);expect(decoded.bytes).not.toContain(V4_ACTIONS.SWAP_EXACT_IN_SINGLE);});
 it('reconciles exact receipt transfers while proving all five liquidity values are unchanged',async()=>{const legs=expected(),result=await reconcileV4BatchCollectReceipt({receipt:receipt([tokenTransfer(currency0,123n,10),tokenTransfer(currency1,456n,11)]),expectedLegs:legs,recipient:owner,inspectPosition:async id=>legs[Number(id-101n)]!});expect(result.aggregateTransfers).toMatchObject({token0:123n,token1:456n});expect(result.legs.every(leg=>leg.onchainLiquidity===legs[leg.legIndex]!.liquidity&&leg.nftExists)).toBe(true);expect(result).toMatchObject({nftBurned:false,swapInvoked:false});});
 it('fails closed if collection changes liquidity or burns an NFT',async()=>{const legs=expected();await expect(reconcileV4BatchCollectReceipt({receipt:receipt([]),expectedLegs:legs,recipient:owner,inspectPosition:async id=>({...legs[Number(id-101n)]!,liquidity:id===103n?0n:legs[Number(id-101n)]!.liquidity})})).rejects.toThrow('V4_BATCH_COLLECT_LIQUIDITY_CHANGED');await expect(reconcileV4BatchCollectReceipt({receipt:receipt([nftTransfer({id:103n,from:owner,to:zeroAddress,logIndex:9})]),expectedLegs:legs,recipient:owner,inspectPosition:async id=>legs[Number(id-101n)]!})).rejects.toThrow('V4_BATCH_COLLECT_NFT_BURN_DETECTED');});
});

describe('existing parent journal and five child binding model',()=>{
 it('stores one confirmed parent per atomic batch and binds all five child legs in one isolated DB transaction',()=>{const root=mkdtempSync(join(tmpdir(),'v4-batch-journal-'));roots.push(root);const path=join(root,'ledger.sqlite');migrateSqlite(path,'infra/migrations');const repo=new SqliteLedgerRepository(path),plan=ladder();try{repo.createDryRunBidLadder(v4BidLadderPersistencePlan(plan));const persist=(journalId:string,stage:string,nonce:number,hash:Hex)=>{repo.persistChainPreparedTransaction({chainId:4663,chainKey:'robinhood',protocol:'uniswap_v4',journalId,wallet:owner,workflowIdentity:plan.ladderId,semanticStage:stage,attempt:0,nonce,transactionType:'modifyLiquidities',expectedHash:hash,to:V4_ROBINHOOD_DEPLOYMENTS.positionManager,requestFingerprint:`${plan.ladderId}:${stage}`,feeModel:'legacy'});repo.transitionChainTransaction({chainId:4663,journalId,from:'PREPARED',to:'SUBMITTED'});repo.transitionChainTransaction({chainId:4663,journalId,from:'SUBMITTED',to:'CONFIRMED',receipt:{status:'success'}});};persist('open-parent','OPEN_BATCH',7,`0x${'11'.repeat(32)}`);repo.db.transaction(()=>{for(let index=0;index<5;index++)if(repo.db.prepare('UPDATE v4_bid_ladder_legs SET token_id=?,open_batch_id=? WHERE ladder_id=? AND leg_index=? AND token_id IS NULL AND open_batch_id IS NULL').run(String(101+index),'open-parent',plan.ladderId,index).changes!==1)throw new Error('ATOMIC_OPEN_BIND_FAILED');})();persist('close-parent','CLOSE_BATCH',8,`0x${'22'.repeat(32)}`);repo.db.transaction(()=>{for(let index=0;index<5;index++)if(repo.db.prepare('UPDATE v4_bid_ladder_legs SET close_batch_id=? WHERE ladder_id=? AND leg_index=? AND token_id=? AND close_batch_id IS NULL').run('close-parent',plan.ladderId,index,String(101+index)).changes!==1)throw new Error('ATOMIC_CLOSE_BIND_FAILED');})();expect(repo.db.prepare('SELECT semantic_stage,status,nonce FROM chain_transaction_journal ORDER BY nonce').all()).toEqual([{semantic_stage:'OPEN_BATCH',status:'CONFIRMED',nonce:7},{semantic_stage:'CLOSE_BATCH',status:'CONFIRMED',nonce:8}]);expect(repo.db.prepare('SELECT COUNT(*) count FROM v4_bid_ladder_legs WHERE open_batch_id=? AND close_batch_id=? AND token_id IS NOT NULL').get('open-parent','close-parent')).toEqual({count:5});}finally{repo.close();}});
});
