import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { migrateSqlite, SqliteLedgerRepository } from '@funi/ledger';
import { executeV4Lifecycle } from '../apps/cli/src/v4-lifecycle.js';

const wallet='0x0000000000000000000000000000000000000002' as const;
const hash=`0x${'12'.repeat(32)}` as const;
const key={currency0:'0x0000000000000000000000000000000000000003',currency1:'0x0000000000000000000000000000000000000004',fee:500,tickSpacing:10,hooks:'0x0000000000000000000000000000000000000000'} as const;
const receipt={status:'success' as const,transactionHash:hash,blockNumber:7n,gasUsed:80_000n,effectiveGasPrice:2n,logs:[]};

function fixture(){const dir=mkdtempSync(join(tmpdir(),'v4-finality-')),path=join(dir,'db.sqlite');migrateSqlite(path,'infra/migrations');const repo=new SqliteLedgerRepository(path);repo.ensurePosition('v4:1','1','pool');repo.upsertV4Position({tokenId:1n,owner:wallet,poolId:'pool',poolKey:key,currency0:key.currency0,currency1:key.currency1,fee:key.fee,tickSpacing:key.tickSpacing,hooks:key.hooks,tickLower:-20,tickUpper:-10,liquidity:0n,initialAmount0:0n,initialAmount1:1n,mintHash:`0x${'11'.repeat(32)}`,status:'closed'});const intent=repo.createV4LifecycleIntent({tokenId:1n,action:'burn',idempotencyKey:'burn-finality',payload:{prepared:{key,tickLower:-20,tickUpper:-10,price1Per0:1,removedLiquidity:'0',principal:{token0:'0',token1:'0'},calldataHash:`0x${'22'.repeat(32)}`,calldata:'0x12'}}});repo.claimV4LifecycleIntent(String(intent.id));repo.transitionV4LifecycleIntent(String(intent.id),'SUBMITTED',{txHash:hash});let waits=0,broadcasts=0;const client={waitForTransactionReceipt:async()=>{waits++;return receipt;}},rpc={config:{chainId:4663,rpcUrls:['http://127.0.0.1']},withClient:async(fn:(value:any)=>unknown)=>fn(client)} as any,walletClient={request:async()=>{broadcasts++;throw new Error('BROADCAST_FORBIDDEN');}} as any,input={repo,rpc,walletClient,wallet,tokenId:1n,action:'burn' as const,slippageBps:50,deadlineSeconds:600,idempotencyKey:'burn-finality'};return {repo,input,intentId:String(intent.id),counts:()=>({waits,broadcasts}),close(){repo.close();rmSync(dir,{recursive:true,force:true});}};}
function states(f:ReturnType<typeof fixture>){return (f.repo.db.prepare('SELECT state FROM v4_lifecycle_transitions WHERE intent_id=? ORDER BY ordinal').all(f.intentId) as Array<{state:string}>).map(row=>row.state);}

describe('confirmed lifecycle action finality',()=>{
 it('keeps a successful exact receipt confirmed when post-confirmation gas/accounting work throws',async()=>{const f=fixture();try{const failed=await executeV4Lifecycle({...f.input,gasPolicy:{beforeSigning:()=>undefined,afterConfirmation:()=>{throw new Error('POST_CONFIRMATION_ACCOUNTING_FAILURE');}}});expect(failed).toMatchObject({status:'RECOVERY_REQUIRED',hash});expect(f.repo.v4LifecycleIntent(f.intentId)).toMatchObject({state:'CONFIRMED_RECONCILIATION_REQUIRED',tx_hash:hash,failure_reason:null});expect(f.repo.db.prepare('SELECT COUNT(*) count FROM v4_lifecycle_receipts WHERE intent_id=? AND tx_hash=?').get(f.intentId,hash)).toEqual({count:1});expect(states(f)).not.toContain('FAILED');expect(f.counts()).toEqual({waits:1,broadcasts:0});const recovered=await executeV4Lifecycle(f.input);expect(recovered).toMatchObject({ok:true,status:'COMPLETED',hash});expect(f.repo.v4LifecycleIntent(f.intentId)).toMatchObject({state:'BURNED',tx_hash:hash});expect(f.counts()).toEqual({waits:1,broadcasts:0});}finally{f.close();}});
 it('does not discard confirmation or rebroadcast when downstream parsing/accounting throws',async()=>{const f=fixture(),original=f.repo.ingestCollection.bind(f.repo);(f.repo as any).ingestCollection=()=>{throw new Error('POST_CONFIRMATION_PARSER_FAILURE');};try{const failed=await executeV4Lifecycle(f.input);expect(failed).toMatchObject({status:'RECOVERY_REQUIRED',hash});expect(f.repo.v4LifecycleIntent(f.intentId)).toMatchObject({state:'CONFIRMED',tx_hash:hash});expect(states(f)).not.toContain('FAILED');(f.repo as any).ingestCollection=original;const recovered=await executeV4Lifecycle(f.input);expect(recovered).toMatchObject({ok:true,status:'COMPLETED',hash});expect(f.counts()).toEqual({waits:1,broadcasts:0});}finally{f.close();}});
 it('resumes after a workflow-transition failure without re-executing the confirmed action',async()=>{const f=fixture(),original=f.repo.transitionV4LifecycleIntent.bind(f.repo);(f.repo as any).transitionV4LifecycleIntent=(id:string,state:string,patch?:unknown)=>{if(state==='BURNED')throw new Error('POST_CONFIRMATION_WORKFLOW_TRANSITION_FAILURE');return original(id,state,patch as any);};try{const failed=await executeV4Lifecycle(f.input);expect(failed).toMatchObject({status:'RECOVERY_REQUIRED',hash});expect(f.repo.v4LifecycleIntent(f.intentId)).toMatchObject({state:'CONFIRMED',tx_hash:hash});expect(states(f)).not.toContain('FAILED');(f.repo as any).transitionV4LifecycleIntent=original;const recovered=await executeV4Lifecycle(f.input);expect(recovered).toMatchObject({ok:true,status:'COMPLETED',hash});expect(f.counts()).toEqual({waits:1,broadcasts:0});}finally{f.close();}});
 it('records an actual-gas breach without corrupting confirmation or reconciliation',async()=>{const f=fixture(),breach='ACTUAL_GAS_POLICY_BREACH:ACTUAL_TX_GAS_CAP_EXCEEDED';try{const result=await executeV4Lifecycle({...f.input,gasPolicy:{beforeSigning:()=>undefined,afterConfirmation:()=>({breach})}});expect(result).toMatchObject({ok:true,status:'COMPLETED',hash,gasPolicyBreach:breach});expect(f.repo.v4LifecycleIntent(f.intentId)).toMatchObject({state:'BURNED',tx_hash:hash,failure_reason:breach});expect(states(f)).not.toContain('FAILED');const repeated=await executeV4Lifecycle(f.input);expect(repeated).toMatchObject({status:'ALREADY_COMPLETED',hash,gasPolicyBreach:breach});expect(f.counts()).toEqual({waits:1,broadcasts:0});}finally{f.close();}});
});
