import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe,expect,it } from 'vitest';
import { migrateSqlite, SqliteLedgerRepository } from '@robin/ledger';

const key={currency0:'0x00000000000000000000000000000000000000b0',currency1:'0x00000000000000000000000000000000000000b1',fee:500,tickSpacing:10,hooks:'0x0000000000000000000000000000000000000000'};
function opened(){const path=join(mkdtempSync(join(tmpdir(),'v4-ledger-')),'db.sqlite');migrateSqlite(path,'infra/migrations');const repo=new SqliteLedgerRepository(path);repo.ensurePosition('v4:1','1','pool');repo.upsertV4Position({tokenId:1n,owner:'owner',poolId:'pool',poolKey:key,currency0:key.currency0,currency1:key.currency1,fee:500,tickSpacing:10,hooks:key.hooks,tickLower:-20,tickUpper:-10,liquidity:1000n,initialAmount0:0n,initialAmount1:5000000n,mintHash:'0xmint'});repo.ingestDeposit({id:'d',positionId:'v4:1',txHash:'0xmint',logIndex:0,amounts:{token0:0n,token1:5000000n},blockNumber:1n,blockTimestamp:new Date().toISOString()});return repo;}
describe('v4 lifecycle persistence and principal-first accounting',()=>{
 it('persists protocol-specific identity without affecting generic positions',()=>{const repo=opened();try{expect(repo.v4Position(1n)).toMatchObject({protocol_version:'v4',pool_id:'pool',status:'open'});expect(repo.listV4Positions()).toHaveLength(1);}finally{repo.close();}});
 it('allocates principal before fees across multiple collections',()=>{const repo=opened();try{repo.ingestLiquidityChange({id:'x',positionId:'v4:1',txHash:'0xa',logIndex:0,kind:'decrease',amounts:{token0:10n,token1:100n}});repo.ingestCollection({id:'c1',positionId:'v4:1',txHash:'0xb',logIndex:0,amounts:{token0:8n,token1:80n},pending:repo.positionAccounting('v4:1').pendingPrincipal});repo.ingestCollection({id:'c2',positionId:'v4:1',txHash:'0xc',logIndex:0,amounts:{token0:7n,token1:30n},pending:repo.positionAccounting('v4:1').pendingPrincipal});expect(repo.collectionTotals('v4:1')).toEqual({principal:{token0:10n,token1:100n},fees:{token0:5n,token1:10n}});const before=repo.reconciliationDelta('v4:1');repo.reconcileAll();expect(repo.reconciliationDelta('v4:1')).toEqual(before);}finally{repo.close();}});
 it('makes lifecycle intent claims and transitions idempotent',()=>{const repo=opened();try{const row=repo.createV4LifecycleIntent({tokenId:1n,action:'partial_close',idempotencyKey:'same',payload:{percent:50}});expect(repo.claimV4LifecycleIntent(String(row.id))).toBe(true);expect(repo.claimV4LifecycleIntent(String(row.id))).toBe(false);repo.transitionV4LifecycleIntent(String(row.id),'SUBMITTED',{txHash:'0x1'});repo.transitionV4LifecycleIntent(String(row.id),'SUBMITTED',{txHash:'0x1'});expect(repo.v4LifecycleHistory(1n).filter(x=>x.transition_state==='SUBMITTED')).toHaveLength(1);}finally{repo.close();}});
 it('records a terminal principal difference once and clears pending principal without changing fees',()=>{const repo=opened();try{repo.ingestLiquidityChange({id:'full',positionId:'v4:1',txHash:'0xclose',logIndex:0,kind:'decrease',amounts:{token0:0n,token1:5_000_000n}});repo.ingestCollection({id:'take',positionId:'v4:1',txHash:'0xclose',logIndex:1,amounts:{token0:25n,token1:4_992_684n},pending:repo.positionAccounting('v4:1').pendingPrincipal});const burn=repo.createV4LifecycleIntent({tokenId:1n,action:'burn',idempotencyKey:'burn'});repo.claimV4LifecycleIntent(String(burn.id));repo.transitionV4LifecycleIntent(String(burn.id),'SUBMITTED',{txHash:'0xburn'});repo.persistV4LifecycleReceipt('0xburn',String(burn.id),{status:'success'});repo.updateV4Position({tokenId:1n,liquidity:0n,status:'burned'});repo.transitionV4LifecycleIntent(String(burn.id),'BURNED');const first=repo.finalizeV4TerminalAccounting(1n),second=repo.finalizeV4TerminalAccounting(1n);expect(first.inserted).toBe(1);expect(second.inserted).toBe(0);expect(second.accounting.pendingPrincipal).toEqual({token0:0n,token1:0n});expect(second.accounting.terminalDifferences).toEqual({token0:0n,token1:7_316n});expect(second.accounting.claimedFees).toEqual({token0:25n,token1:0n});expect(second.accounting.terminalDifferenceRecords[0]).toMatchObject({reason:'realized_shortfall',amount_raw:'7316',source_tx_hash:'0xburn'});}finally{repo.close();}});
});
