import { mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { migrateSqlite, SqliteLedgerRepository } from '@robin/ledger';
import { V4_LIVE_AMOUNT, V4_LIVE_POOL_ID, V4_LIVE_POOL_KEY, enforceV4GasBudget, evaluateV4LiveGates, executeV4LiveCanaryOpen, isLoopbackRpc, v4ExactApprovalDecision } from '../apps/cli/src/v4-live-canary.js';

function repo(){const path=join(mkdtempSync(join(tmpdir(),'v4-live-test-')),'db.sqlite');migrateSqlite(path,'infra/migrations');return new SqliteLedgerRepository(path);}
const open={operation:'open' as const,executionEnabled:true,dryRun:false,emergencyPause:false,v4LiveCanaryEnabled:true,signerConfigured:true,allowlisted:true,chainId:4663,deploymentVerified:true,state:'AVAILABLE_FOR_OPEN',amountRaw:V4_LIVE_AMOUNT,fundingBalance:V4_LIVE_AMOUNT,nativeBalance:1n,poolValid:true,pendingIntent:false,openPositionCount:0};

describe('v4 live canary lane',()=>{
  it('uses the immutable full PoolKey and one exact 5 USDG amount',()=>{expect(V4_LIVE_POOL_ID).toHaveLength(66);expect(V4_LIVE_POOL_KEY.fee).toBe(500);expect(V4_LIVE_POOL_KEY.tickSpacing).toBe(10);expect(V4_LIVE_AMOUNT).toBe(5_000_000n);});
  it('shares fail-closed open and exact-position close gates',()=>{expect(evaluateV4LiveGates(open).executionReachable).toBe(true);expect(evaluateV4LiveGates({...open,dryRun:true}).reasons).toContain('DRY_RUN_ENABLED');expect(evaluateV4LiveGates({...open,amountRaw:5_000_001n}).reasons).toContain('V4_CANARY_AMOUNT_MUST_BE_EXACTLY_5_USDG');expect(evaluateV4LiveGates({...open,operation:'close',state:'OPENED',tokenId:'7',requestedTokenId:'7'}).executionReachable).toBe(true);expect(evaluateV4LiveGates({...open,operation:'close',state:'OPENED',tokenId:'7',requestedTokenId:'8'}).reasons).toContain('V4_CANARY_TOKEN_ID_MISMATCH');});
  it('claims one open and only the enrolled NFT can claim close',()=>{const db=repo();try{const i=db.createV4LiveOpenIntent({idempotencyKey:'open-1',owner:'0x1',poolId:V4_LIVE_POOL_ID,poolKey:V4_LIVE_POOL_KEY,amount:V4_LIVE_AMOUNT,payload:{}});expect(db.claimV4LiveOpen({intentId:String(i.id)})).toBe(true);expect(db.claimV4LiveOpen({intentId:'second'})).toBe(false);db.transitionV4LiveCanary('OPENED',{tokenId:'42'});expect(db.claimV4LiveClose({intentId:'wrong',tokenId:'41'})).toBe(false);expect(db.claimV4LiveClose({intentId:'close',tokenId:'42'})).toBe(true);expect(db.claimV4LiveClose({intentId:'duplicate',tokenId:'42'})).toBe(false);}finally{db.close();}});
  it('atomically claims an operational open without reading or mutating a consumed legacy canary',()=>{const db=repo();try{db.transitionV4LiveCanary('OPENED',{tokenId:'42'});const before=db.v4LiveCanary(),intent=db.createV4LiveOpenIntent({idempotencyKey:'operational-open-1',owner:'0x1',poolId:`0x${'1'.repeat(64)}`,poolKey:V4_LIVE_POOL_KEY,amount:25_000_000n,payload:{lane:'operational'}});expect(db.claimV4OperationalOpen({intentId:String(intent.id)})).toBe(true);expect(db.claimV4OperationalOpen({intentId:String(intent.id)})).toBe(false);expect(db.v4LiveOpenIntent(String(intent.id))?.state).toBe('CLAIMED');expect(db.v4LiveCanary()).toMatchObject({state:before.state,token_id:before.token_id,gas_spent_usd:before.gas_spent_usd});}finally{db.close();}});
  it('marks only a no-broadcast failed operational intent retryable, including the deployed pre-lane payload shape',()=>{const db=repo();try{const intent=db.createV4LiveOpenIntent({idempotencyKey:'operational-retry-1',owner:'0x1',poolId:`0x${'1'.repeat(64)}`,poolKey:V4_LIVE_POOL_KEY,amount:5_000_000n,payload:{executor:'executeV4OperationalOpen'}});db.claimV4OperationalOpen({intentId:String(intent.id)});db.transitionV4LiveOpenIntent(String(intent.id),'FAILED',{failureReason:'V4_NATIVE_USD_PRICE_INVALID'});expect(db.markV4OperationalOpenRetryable(String(intent.id))).toBe(true);expect(db.markV4OperationalOpenRetryable(String(intent.id))).toBe(false);expect(db.v4LiveOpenIntent(String(intent.id))?.state).toBe('FAILED_RETRYABLE');expect(db.v4LiveTransitions(String(intent.id)).at(-1)).toMatchObject({state:'FAILED_RETRYABLE'});}finally{db.close();}});
  it('persists operational receipts against the operational intent and never marks broadcast work retryable',()=>{const db=repo();try{const intent=db.createV4LiveOpenIntent({idempotencyKey:'operational-receipt-1',owner:'0x1',poolId:`0x${'1'.repeat(64)}`,poolKey:V4_LIVE_POOL_KEY,amount:5_000_000n,payload:{lane:'operational'}});db.claimV4OperationalOpen({intentId:String(intent.id)});expect(db.persistV4OperationalOpenReceipt(`0x${'2'.repeat(64)}`,String(intent.id),'ERC20_PERMIT2',{status:'success'})).toBe(true);db.transitionV4LiveOpenIntent(String(intent.id),'FAILED',{failureReason:'INTERRUPTED_AFTER_RECEIPT'});expect(db.markV4OperationalOpenRetryable(String(intent.id))).toBe(false);}finally{db.close();}});
  it('keeps operational receipt gas out of the legacy canary budget',()=>{const db=repo();try{const intent=db.createV4LiveOpenIntent({idempotencyKey:'operational-gas-1',owner:'0x1',poolId:V4_LIVE_POOL_ID,poolKey:V4_LIVE_POOL_KEY,amount:25_000_000n,payload:{lane:'operational'}});db.addV4LiveGasEstimate({txHash:'0x1',intentId:String(intent.id),phase:'MINT',gas:1n,eth:2n,usd:.1});expect(db.confirmV4OperationalGas({txHash:'0x1',gas:1n,eth:2n,usd:.1})).toBe(true);expect(db.v4OperationalGasSpentUsd(String(intent.id))).toBeCloseTo(.1);expect(db.v4LiveCanary().gas_spent_usd).toBe(0);}finally{db.close();}});
  it('enforces $0.25 per transaction and $1 lifecycle budget',()=>{const db=repo();try{expect(()=>enforceV4GasBudget(db,{usd:.251},{maxTxGasUsd:.25,totalGasUsd:1})).toThrow('TX_GAS_CAP_EXCEEDED');db.db.prepare('UPDATE v4_live_canary SET gas_spent_usd=.9 WHERE id=1').run();expect(()=>enforceV4GasBudget(db,{usd:.11},{maxTxGasUsd:.25,totalGasUsd:1})).toThrow('LIFECYCLE_GAS_BUDGET_EXCEEDED');expect(enforceV4GasBudget(db,{usd:.1},{maxTxGasUsd:.25,totalGasUsd:1}).remaining).toBeCloseTo(0);}finally{db.close();}});
  it('allows automated writes only to loopback transports',()=>{expect(isLoopbackRpc('http://127.0.0.1:8545')).toBe(true);expect(isLoopbackRpc('http://localhost:8545')).toBe(true);expect(isLoopbackRpc('https://rpc.mainnet.chain.robinhood.com')).toBe(false);});
  it('blocks the historical direct-send open lane on public RPC before wallet access',async()=>{let sends=0;await expect(executeV4LiveCanaryOpen({rpc:{config:{rpcUrls:['https://public.invalid']}} as any,walletClient:{sendTransaction:async()=>{sends++;}} as any,allowLocalTest:false} as any)).rejects.toThrow('V4_LEGACY_LIVE_OPEN_DISABLED_USE_OPERATIONAL_EXECUTOR');expect(sends).toBe(0);});
  it('does not send redundant exact approvals and truthfully identifies allowance normalization',()=>{expect(v4ExactApprovalDecision(V4_LIVE_AMOUNT,V4_LIVE_AMOUNT)).toMatchObject({alreadySufficient:true,alreadyExact:true,approvalTransactionRequired:false,status:'ALREADY_SUFFICIENT_EXACT'});expect(v4ExactApprovalDecision(2n**255n,V4_LIVE_AMOUNT)).toMatchObject({alreadySufficient:true,alreadyExact:false,exactApprovalRequired:true,approvalTransactionRequired:true,revocationRequired:true,status:'EXACT_APPROVAL_REQUIRED'});expect(v4ExactApprovalDecision(0n,V4_LIVE_AMOUNT)).toMatchObject({alreadySufficient:false,approvalTransactionRequired:true,status:'APPROVAL_TRANSACTION_REQUIRED'});});
});
