import { describe, expect, it } from 'vitest';
import { mkdtempSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { migrateSqlite, SqliteLedgerRepository } from '@funi/ledger';
import { persistPortfolioSnapshot } from '../apps/cli/src/active-position-reconciliation.js';

const target='0x0000000000000000000000000000000000000001',funding='0x0000000000000000000000000000000000000002',owner='0x0000000000000000000000000000000000000003';
function fixture(){const dir=mkdtempSync(join(tmpdir(),'v4-symbol-')),path=join(dir,'db.sqlite');migrateSqlite(path,'infra/migrations');return {dir,repo:new SqliteLedgerRepository(path)};}
function upsert(repo:SqliteLedgerRepository,symbol?:string){return repo.upsertV4Position({tokenId:7n,owner,poolId:'pool',poolKey:{currency0:target,currency1:funding,fee:500,tickSpacing:10,hooks:'0x0000000000000000000000000000000000000000'},currency0:target,currency1:funding,fee:500,tickSpacing:10,hooks:'0x0000000000000000000000000000000000000000',tickLower:-10,tickUpper:10,liquidity:99n,initialAmount0:0n,initialAmount1:1_000_000n,mintHash:'0xhash',targetToken:target,fundingToken:funding,targetSymbol:symbol,fundingSymbol:'USDG',symbolProvenance:symbol?{source:'TRUSTED_TEST',address:target,symbol}:undefined,openIntentId:'ladder'});}

describe('V4 durable symbol provenance',()=>{
 it('stores trusted selected symbols and evidence by exact address',()=>{const f=fixture();try{const row=f.repo.createV4PoolSelection({userId:'u',chatId:'c',sessionId:'s',poolId:'0x'+'1'.repeat(64),poolKey:{},discoveryBlock:1n,liquidity:1n,targetToken:target,fundingToken:funding,targetSymbol:'ARBITRARY',fundingSymbol:'USDG',symbolProvenance:{source:'TRUSTED_SELECTION',bindings:[{address:target,symbol:'ARBITRARY'}]},eligibility:true});expect(row).toMatchObject({target_symbol:'ARBITRARY',funding_symbol:'USDG'});expect(JSON.parse(String(row.symbol_provenance_json))).toMatchObject({source:'TRUSTED_SELECTION'});}finally{f.repo.close();rmSync(f.dir,{recursive:true,force:true});}});
 it('preserves a durable symbol without metadata cache, records conflicts, and leaves economics unchanged',()=>{const f=fixture();try{f.repo.ensurePosition('v4:7','7','pool');f.repo.db.prepare("UPDATE positions SET chain_id=4663,protocol='uniswap_v4' WHERE id='v4:7'").run();upsert(f.repo,'ARBITRARY');const before=f.repo.v4Position('7')!,economic=JSON.stringify({liquidity:before.liquidity_raw,initial0:before.initial_amount0_raw,initial1:before.initial_amount1_raw,mint:before.mint_hash,status:before.status});upsert(f.repo,'DIFFERENT');const after=f.repo.v4Position('7')!;expect(after.target_symbol).toBe('ARBITRARY');expect(JSON.stringify({liquidity:after.liquidity_raw,initial0:after.initial_amount0_raw,initial1:after.initial_amount1_raw,mint:after.mint_hash,status:after.status})).toBe(economic);expect(f.repo.db.prepare('SELECT established_symbol,proposed_symbol FROM v4_symbol_provenance_conflicts').get()).toEqual({established_symbol:'ARBITRARY',proposed_symbol:'DIFFERENT'});const snapshot=persistPortfolioSnapshot(f.repo);expect(snapshot.positions.find((p:any)=>p.tokenId==='7')?.pair).toBe('ARBITRARY/USDG');expect(f.repo.tokenMetadata(target)).toBeUndefined();}finally{f.repo.close();rmSync(f.dir,{recursive:true,force:true});}});
});
