import { CHAIN_PROFILES, FallbackRpc, loadChainRuntimeConfig, protocolDeployment, type ChainKey } from '@funi/core';
import type { Bot } from 'grammy';
import { bscReadOnlyRuntimeStatus, canonicalDeploymentVerification, probePublicRpcCapabilities } from '../../cli/src/multichain-runtime.js';
import { telegramCallbackData } from './callback-data.js';

type ReadOnlyEvidence={readOnlyAvailable:boolean;readOnlyMode:string;registryDiscovery:boolean;blocker?:string;executionReady:boolean};
async function chainEvidence(key:'bsc'|'ethereum',env:NodeJS.ProcessEnv):Promise<ReadOnlyEvidence|undefined>{const config=loadChainRuntimeConfig(key,env);if(!config.enabled||!config.available)return undefined;const profile=config.profile,protocol=key==='bsc'?'pancakeswap_v3' as const:'uniswap_v3' as const,assets=Object.fromEntries([['WRAPPED_NATIVE',profile.wrappedNativeAddress],...profile.quoteTokens.map(item=>[item.symbol,item.address])]),rpc=new FallbackRpc({chainId:profile.chainId,name:profile.displayName,rpcUrls:config.rpcUrls,nativeSymbol:profile.nativeSymbol,explorerUrl:profile.blockExplorerBase,assets},config.rpcUrls,{timeoutMs:8_000,attemptTimeoutMs:8_000}),deployment=await canonicalDeploymentVerification({profile,rpc,protocol});if(key==='ethereum')return {readOnlyAvailable:deployment.status==='VERIFIED',readOnlyMode:deployment.status==='VERIFIED'?'FULL':'BLOCKED',registryDiscovery:deployment.status==='VERIFIED',blocker:deployment.blockerReason,executionReady:false};const providers=await probePublicRpcCapabilities({profile,rpc,protocol});return bscReadOnlyRuntimeStatus({deploymentVerification:deployment.status,providers});}
export function chainSelectorView(env:NodeJS.ProcessEnv=process.env,evidence?:ReadOnlyEvidence){const rows=(Object.keys(CHAIN_PROFILES) as ChainKey[]).map(key=>{const config=loadChainRuntimeConfig(key,env),runtime=key==='bsc'?evidence:undefined,protocols=config.profile.supportedProtocolKeys.map(protocol=>{const deployment=protocolDeployment(config.profile.chainId,protocol),runtimeVerified=deployment.runtimeVerification.status==='VERIFIED',discovery=runtime?runtime.registryDiscovery&&deployment.capabilities.discovery:deployment.capabilities.discovery;return {protocol,readOnly:discovery||deployment.capabilities.portfolioRead,execution:runtime?false:config.executionEnabled&&config.available&&!config.dryRun&&!config.emergencyPause&&runtimeVerified&&deployment.capabilities.executionSupported,blocker:runtime?.blocker??(runtimeVerified?deployment.capabilities.blockerReason:deployment.runtimeVerification.blockerReason??'DEPLOYMENT_RUNTIME_NOT_VERIFIED')};});return {key,chainId:config.profile.chainId,label:config.profile.displayName,enabled:config.enabled,readOnlyAvailable:runtime?.readOnlyAvailable??(config.enabled&&config.available),readOnlyMode:runtime?.readOnlyMode,executionAvailable:protocols.some(item=>item.execution),blockerReason:runtime?.blocker??config.blockerReason,protocols};});return {text:['Select a chain for read-only views. Every actionable preview remains bound to its chain and protocol.',...rows.map(row=>`${row.label} (${row.chainId}) — ${row.readOnlyAvailable?'read-only available':row.enabled?'unavailable':'disabled'}${row.readOnlyMode?` (${row.readOnlyMode})`:''}; execution ${row.executionAvailable?'available':'disabled'}${row.blockerReason?`; blocker ${row.blockerReason}`:''}`)].join('\n'),keyboard:rows.map(row=>[{text:`${row.label}${row.enabled?'':' · disabled'}`,callback_data:telegramCallbackData(`mc:c:${row.chainId}`)}]),rows};}
export function chainSelectionResult(chainId:number,env:NodeJS.ProcessEnv=process.env,evidence?:ReadOnlyEvidence){const key=(Object.keys(CHAIN_PROFILES) as ChainKey[]).find(value=>CHAIN_PROFILES[value].chainId===chainId);if(!key)throw new Error('UNKNOWN_CHAIN');const config=loadChainRuntimeConfig(key,env),runtime=key==='bsc'?evidence:undefined,protocols=config.profile.supportedProtocolKeys.map(protocol=>{const deployment=protocolDeployment(chainId,protocol),runtimeVerified=deployment.runtimeVerification.status==='VERIFIED';return {protocol,discovery:runtime?runtime.registryDiscovery&&deployment.capabilities.discovery:deployment.capabilities.discovery,portfolioRead:deployment.capabilities.portfolioRead,executionSupported:runtime?false:config.executionEnabled&&config.available&&!config.dryRun&&!config.emergencyPause&&runtimeVerified&&deployment.capabilities.executionSupported,blockerReason:runtime?.blocker??(runtimeVerified?deployment.capabilities.blockerReason:deployment.runtimeVerification.blockerReason??'DEPLOYMENT_RUNTIME_NOT_VERIFIED')};});return {key,chainId,label:config.profile.displayName,enabled:config.enabled,readOnlyAvailable:runtime?.readOnlyAvailable??(config.enabled&&config.available),readOnlyMode:runtime?.readOnlyMode,registryDiscovery:runtime?.registryDiscovery,blocker:runtime?.blocker,executionEnabled:config.executionEnabled,protocols};}
export function actionableChainHeader(input:{chainId:number;protocol:string;action:string}){const profile=Object.values(CHAIN_PROFILES).find(item=>item.chainId===input.chainId);if(!profile)throw new Error('UNKNOWN_CHAIN');return `${profile.displayName} (${profile.chainId}) · ${input.protocol} · ${input.action}`;}
export function chainActionButton(input:{chainId:number;protocol:string;action:string;authorizationId:string;executionReady:boolean}){return {header:actionableChainHeader(input),keyboard:input.executionReady?[[{text:`Confirm ${input.action}`,callback_data:telegramCallbackData(`mc:x:${input.authorizationId}`)}]]:[],blocker:input.executionReady?undefined:'CHAIN_EXECUTION_NOT_READY'};}
export function parseChainActionCallback(payload:string){const match=/^mc:x:([A-Za-z0-9_-]{1,40})$/.exec(payload);if(!match)throw new Error('CHAIN_CALLBACK_PAYLOAD_INVALID');return {authorizationId:match[1]!};}
export const MULTICHAIN_ACTION_FLOW=['chain','protocol','pool_or_position','action','preview','gas_readiness','exposure_readiness','explicit_confirmation','chain_bound_executor'] as const;
export function multichainActionFlow(input:{chainId:56|1;protocol:'pancakeswap_v3'|'uniswap_v3';poolOrPosition:string;action:'open'|'collect'|'close';readinessState:string;authorizationId?:string;blockers?:readonly string[]}){const executionReady=input.readinessState==='GUARDED_LIVE_CODE_READY'&&Boolean(input.authorizationId),button=chainActionButton({chainId:input.chainId,protocol:input.protocol,action:input.action,authorizationId:input.authorizationId??'blocked',executionReady});return {steps:MULTICHAIN_ACTION_FLOW,scope:{chainId:input.chainId,protocol:input.protocol,poolOrPosition:input.poolOrPosition,action:input.action},readinessState:input.readinessState,blockers:[...(input.blockers??[]),...(button.blocker?[button.blocker]:[])],keyboard:button.keyboard};}
export function manualVerifiedPoolView(row:Record<string,unknown>){if(Number(row.chain_id)!==56||String(row.protocol)!=='pancakeswap_v3'||String(row.validation_status)!=='MANUAL_VERIFIED')throw new Error('MANUAL_VERIFIED_BSC_POOL_REQUIRED');let state:Record<string,unknown>={};try{state=JSON.parse(String(row.state_json));}catch{}return [`BNB Smart Chain (56) · pancakeswap_v3`,`Pool: ${String(row.pool_address)}`,`Token0: ${String(row.token0_address)}`,`Token1: ${String(row.token1_address)}`,`Fee: ${String(row.fee)}`,`Tick spacing: ${String(row.tick_spacing)}`,`Current tick: ${String(state.tick??'unavailable')}`,`Liquidity: ${String(state.liquidity??'unavailable')}`,`Source: MANUAL_VERIFIED`,`Registry discovery completeness: not claimed`].join('\n');}

export function registerMultichainUx(bot:Pick<Bot,'command'|'callbackQuery'>,env:NodeJS.ProcessEnv=process.env,dependencies:{poolLookup?:(chainId:number,protocol:string,address:string)=>Record<string,unknown>|undefined}={}){
 bot.command('chains',async ctx=>{const view=chainSelectorView(env,await chainEvidence('bsc',env));return ctx.reply(view.text,{reply_markup:{inline_keyboard:view.keyboard}});});
 bot.command('chainpool',async ctx=>{const parts=String(ctx.match??'').trim().split(/\s+/).filter(Boolean);if(parts.length!==3)return ctx.reply('Usage: /chainpool 56 pancakeswap_v3 <pool-address>');const [chain,protocol,address]=parts;if(chain!=='56'||protocol!=='pancakeswap_v3'||!/^0x[0-9a-fA-F]{40}$/.test(address!))return ctx.reply('Only manually verified BSC PancakeSwap v3 pools are supported.');const row=dependencies.poolLookup?.(56,protocol,address!);return ctx.reply(row?manualVerifiedPoolView(row):'Pool is not registered as MANUAL_VERIFIED.');});
 bot.callbackQuery(/^mc:c:(4663|56|1)$/,async ctx=>{const chainId=Number(ctx.match[1]),selected=chainSelectionResult(chainId,env,chainId===56?await chainEvidence('bsc',env):chainId===1?await chainEvidence('ethereum',env):undefined);await ctx.answerCallbackQuery({text:selected.enabled?selected.label:`${selected.label} is disabled`});return ctx.reply(`${selected.label} (${selected.chainId})\nRead-only: ${selected.readOnlyAvailable?'available':'unavailable'}${selected.readOnlyMode?` (${selected.readOnlyMode})`:''}\nRegistry discovery: ${selected.registryDiscovery===undefined?'not probed':selected.registryDiscovery?'available':'blocked'}${selected.blocker?` — ${selected.blocker}`:''}\nExecution: ${selected.executionEnabled?'configured but still capability-gated':'disabled'}\nProtocols:\n${selected.protocols.map(item=>`• ${item.protocol}: reads ${item.discovery||item.portfolioRead?'supported':'blocked'}, execution ${item.executionSupported?'supported':'blocked'}${item.blockerReason?` — ${item.blockerReason}`:''}`).join('\n')}`);});
 return Object.freeze({commands:Object.freeze(['chains','chainpool']),callbackPatterns:Object.freeze(['mc:c:<chainId>','mc:x:<authorizationId>'])});
}
