import Database from 'better-sqlite3';
import { chmodSync, copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, renameSync, statSync, unlinkSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { createHash, randomUUID } from 'node:crypto';

export type TokenAmounts = { token0: bigint; token1: bigint };
export type PricePoint = { token0Usd?: number; token1Usd?: number; token0Decimals: number; token1Decimals: number; blockNumber: bigint; source: string; confidence: 'verified'|'derived'|'partial'; observedAt: string };
export type LedgerEvent = { id:string; positionId:string; txHash:string; logIndex:number; kind:'mint'|'increase'|'decrease'|'collect'|'swap'|'gas'|'manual-correction'|'close'; amounts?:TokenAmounts; price?:PricePoint; gasUsd?:number; executionCostUsd?:number; reason?:string; timestamp:string };
export type CollectionAllocation = { eventId:string; principal:TokenAmounts; fees:TokenAmounts };
export type PositionLedger = { deposits:TokenAmounts; pendingPrincipal:TokenAmounts; withdrawnPrincipal:TokenAmounts; claimedFees:TokenAmounts; unclaimedFees:TokenAmounts; gasUsd:number; executionCostsUsd:number; events:LedgerEvent[]; allocations:CollectionAllocation[] };
const zero=():TokenAmounts=>({token0:0n,token1:0n});
const add=(a:TokenAmounts,b:TokenAmounts):TokenAmounts=>({token0:a.token0+b.token0,token1:a.token1+b.token1});
const take=(available:bigint, amount:bigint):[bigint,bigint]=>{const principal=available<amount?available:amount;return [principal,amount-principal];};
export class Ledger {
  private seen=new Set<string>(); private positions=new Map<string,PositionLedger>();
  state(positionId:string):PositionLedger { let p=this.positions.get(positionId); if(!p){p={deposits:zero(),pendingPrincipal:zero(),withdrawnPrincipal:zero(),claimedFees:zero(),unclaimedFees:zero(),gasUsd:0,executionCostsUsd:0,events:[],allocations:[]};this.positions.set(positionId,p);} return p; }
  ingest(e:LedgerEvent):boolean { const key=`${e.txHash}:${e.logIndex}`; if(this.seen.has(key)) return false; if(e.kind==='manual-correction'&&!e.reason) throw new Error('manual correction requires an audit reason'); this.seen.add(key); const p=this.state(e.positionId), a=e.amounts??zero(); p.events.push(e); switch(e.kind){case'mint':case'increase':p.deposits=add(p.deposits,a);break;case'decrease':p.pendingPrincipal=add(p.pendingPrincipal,a);break;case'collect':{const [p0,f0]=take(p.pendingPrincipal.token0,a.token0),[p1,f1]=take(p.pendingPrincipal.token1,a.token1);const principal={token0:p0,token1:p1},fees={token0:f0,token1:f1};p.pendingPrincipal={token0:p.pendingPrincipal.token0-p0,token1:p.pendingPrincipal.token1-p1};p.withdrawnPrincipal=add(p.withdrawnPrincipal,principal);p.claimedFees=add(p.claimedFees,fees);p.allocations.push({eventId:e.id,principal,fees});break;}case'gas':p.gasUsd+=e.gasUsd??0;break;case'swap':p.executionCostsUsd+=e.executionCostUsd??0;break;case'close':break;} return true; }
  setUnclaimedFees(positionId:string, fees:TokenAmounts):void { if(fees.token0<0n||fees.token1<0n) throw new Error('fees cannot be negative'); this.state(positionId).unclaimedFees=fees; }
}
export type Pnl = { currentLiquidityValue:number; unclaimedFeeValue:number; claimedFeeMtmValue:number; withdrawnPrincipalMtmValue:number; totalStrategyMtmValue:number; depositedValue:number; grossPnl:number; grossPnlPct:number; netPnl:number; holdValue:number; holdPnl:number; lpVsHold:number; realizedValue:number; label:'mark-to-market' };
function value(a:TokenAmounts,p:PricePoint):number { if(p.token0Usd===undefined||p.token1Usd===undefined) throw new Error('required token price unavailable'); return Number(a.token0)/10**p.token0Decimals*p.token0Usd+Number(a.token1)/10**p.token1Decimals*p.token1Usd; }
/** Raw token amounts are valued using the matching persisted token decimals. */
export function markToMarket(p:PositionLedger,currentLiquidity:TokenAmounts,current:PricePoint,depositValue:number,originalDeposit:TokenAmounts):Pnl { const currentLiquidityValue=value(currentLiquidity,current),unclaimedFeeValue=value(p.unclaimedFees,current),claimedFeeMtmValue=value(p.claimedFees,current),withdrawnPrincipalMtmValue=value(p.withdrawnPrincipal,current),totalStrategyMtmValue=currentLiquidityValue+unclaimedFeeValue+claimedFeeMtmValue+withdrawnPrincipalMtmValue,grossPnl=totalStrategyMtmValue-depositValue,holdValue=value(originalDeposit,current); return {currentLiquidityValue,unclaimedFeeValue,claimedFeeMtmValue,withdrawnPrincipalMtmValue,totalStrategyMtmValue,depositedValue:depositValue,grossPnl,grossPnlPct:depositValue===0?0:grossPnl/depositValue*100,netPnl:grossPnl-p.gasUsd-p.executionCostsUsd,holdValue,holdPnl:holdValue-depositValue,lpVsHold:totalStrategyMtmValue-holdValue,realizedValue:withdrawnPrincipalMtmValue,label:'mark-to-market'}; }

export type OneSidedPnlInput = { currentLiquidity:TokenAmounts; current:PricePoint; initialFunding:bigint; fundingIndex:0|1; initialFundingExecutionValue:number; realizedProceedsValue?:number; soldAssetValue?:number; targetAccumulatedRaw?:bigint; fundingRemainingRaw?:bigint; targetDecimals?:number; fundingDecimals?:number; targetPriceInFunding?:number; gasCosts?:number; executionCosts?:number };
export type OneSidedPnl = Pnl & { benchmarkAssetIndex:0|1; fundingConversionPct:number; targetAccumulatedRaw:bigint; fundingRemainingRaw:bigint; averageTargetAcquisitionPrice?:number; effectiveAcquisitionPrice?:number; breakEvenTargetPrice?:number };
/** Generic token-level one-sided accounting.  Its benchmark is explicitly the
 * original funding asset, never the old balanced HODL basket. */
export function oneSidedMarkToMarket(p:PositionLedger,input:OneSidedPnlInput):OneSidedPnl {
 const liquidity=value(input.currentLiquidity,input.current), unclaimed=value(p.unclaimedFees,input.current), claimed=value(p.claimedFees,input.current), withdrawn=value(p.withdrawnPrincipal,input.current);
 const realized=input.realizedProceedsValue??0, sold=input.soldAssetValue??0, total=liquidity+unclaimed+claimed+withdrawn+realized-sold;
 const deposited=input.initialFundingExecutionValue, gross=total-deposited;
 const fundingUsd=input.fundingIndex===0?input.current.token0Usd:input.current.token1Usd;
 const fundingDecimals=input.fundingDecimals??(input.fundingIndex===0?input.current.token0Decimals:input.current.token1Decimals);
 const holdValue=fundingUsd===undefined?NaN:Number(input.initialFunding)/10**fundingDecimals*fundingUsd;
 const fundingRemaining=input.fundingRemainingRaw??(input.fundingIndex===0?input.currentLiquidity.token0:input.currentLiquidity.token1);
 const targetAccumulated=input.targetAccumulatedRaw??(input.fundingIndex===0?input.currentLiquidity.token1:input.currentLiquidity.token0);
 const converted=input.initialFunding===0n?0:Number(input.initialFunding-fundingRemaining)/Number(input.initialFunding)*100;
 const targetDecimals=input.targetDecimals??(input.fundingIndex===0?input.current.token1Decimals:input.current.token0Decimals);
 const fundingUnits=Number(input.initialFunding)/10**fundingDecimals, targetUnits=Number(targetAccumulated)/10**targetDecimals;
 const average=targetUnits>0&&input.targetPriceInFunding!==undefined?(fundingUnits-Number(fundingRemaining)/10**fundingDecimals)/targetUnits:undefined;
 const costs=(input.gasCosts??p.gasUsd)+(input.executionCosts??p.executionCostsUsd), effective=average===undefined?undefined:average+costs/(targetUnits||1);
 const targetUsd=input.fundingIndex===0?input.current.token1Usd:input.current.token0Usd;
 const breakEven=targetUnits>0&&targetUsd!==undefined&&fundingUsd!==undefined?(deposited+costs-(total-targetUnits*targetUsd))/(targetUnits*(fundingUsd||1)):undefined;
 return {currentLiquidityValue:liquidity,unclaimedFeeValue:unclaimed,claimedFeeMtmValue:claimed,withdrawnPrincipalMtmValue:withdrawn,totalStrategyMtmValue:total,depositedValue:deposited,grossPnl:gross,grossPnlPct:deposited===0?0:gross/deposited*100,netPnl:gross-costs,holdValue,holdPnl:holdValue-deposited,lpVsHold:total-holdValue,realizedValue:withdrawn+realized, label:'mark-to-market',benchmarkAssetIndex:input.fundingIndex,fundingConversionPct:Math.max(0,Math.min(100,converted)),targetAccumulatedRaw:targetAccumulated,fundingRemainingRaw:fundingRemaining,averageTargetAcquisitionPrice:average,effectiveAcquisitionPrice:effective,breakEvenTargetPrice:breakEven};
}

export type MigrationStatus={applied:string[];pending:string[]};
export type V4RegistryPoolRecord={
 poolId:string;currency0:string;currency1:string;initializeFeeRaw:number;tickSpacing:number;hooks:string;initializationBlock:bigint;
 initializationTxHash?:string;initializationTxIndex?:number|null;initializationLogIndex?:number|null;dynamicFee:boolean;staticFeePips:number|null;hookClassification:string;
};
export const nowMs=()=>Date.now();
export const computeExpiresAt=(now:number,ttlMs:number)=>{if(!Number.isSafeInteger(now)||!Number.isSafeInteger(ttlMs)||ttlMs<=0)throw new Error('invalid session clock or TTL');return now+ttlMs;};
export const isExpired=(expiresAtMs:number,now:number)=>expiresAtMs<=now;
export type TelegramFlowStatus='active'|'expired'|'cancelled'|'completed'|'superseded';
export type TelegramFlowSession={sessionId:string;userId:string;chatId:string;state:Record<string,unknown>;status:TelegramFlowStatus;createdAtMs:number;updatedAtMs:number;expiresAtMs:number};
export type DatabasePaths={dataDir:string;databasePath:string;backupDir:string};
const DIRECTORY_MODE=0o700, FILE_MODE=0o600;
function secureDirectory(path:string){mkdirSync(path,{recursive:true,mode:DIRECTORY_MODE});chmodSync(path,DIRECTORY_MODE);}
function secureFile(path:string){if(existsSync(path))chmodSync(path,FILE_MODE);}
/** Resolves production storage without relying on /tmp. Tests can supply explicit paths. */
export function productionDatabasePaths(input:{dataDir?:string;databasePath?:string}={}):DatabasePaths{
 const dataDir=resolve(input.dataDir??process.env.DATA_DIR??'./data');
 const databasePath=resolve(input.databasePath??process.env.DATABASE_PATH??join(dataDir,'robinhood-lp.sqlite'));
 return {dataDir,databasePath,backupDir:join(dataDir,'backups')};
}
function configure(db:Database.Database,busyTimeoutMs=10_000){db.pragma('foreign_keys = ON');db.pragma('journal_mode = WAL');db.pragma(`busy_timeout = ${busyTimeoutMs}`);}
/** Durable JSON boundary: exact BigInt decimal strings, including nested arrays/objects. */
export function jsonStringify(value:unknown){return JSON.stringify(value,(_,entry)=>typeof entry==='bigint'?entry.toString():entry);}
/** SQLite migration runner with an append-only schema_migrations ledger. */
export function migrateSqlite(dbPath:string,migrationsDir:string):MigrationStatus{const existed=existsSync(dbPath);secureDirectory(dirname(dbPath));const db=new Database(dbPath);try{configure(db);db.exec('CREATE TABLE IF NOT EXISTS schema_migrations (name TEXT PRIMARY KEY, applied_at TEXT NOT NULL)');const applied=new Set((db.prepare('SELECT name FROM schema_migrations').all() as {name:string}[]).map(r=>r.name));const files=readdirSync(migrationsDir).filter(x=>x.endsWith('.sql')).sort(),pendingBefore=files.filter(x=>!applied.has(x));if(existed&&pendingBefore.length){const backupDir=join(dirname(dbPath),'backups'),stamp=new Date().toISOString().replace(/[:.]/g,'-'),target=join(backupDir,`pre-migration-${pendingBefore[0]}-${stamp}.sqlite`);secureDirectory(backupDir);db.pragma('wal_checkpoint(FULL)');db.exec(`VACUUM INTO '${target.replaceAll("'","''")}'`);secureFile(target);}const insert=db.prepare('INSERT INTO schema_migrations(name,applied_at) VALUES(?,?)');for(const name of pendingBefore){const run=db.transaction(()=>{db.exec(readFileSync(join(migrationsDir,name),'utf8'));insert.run(name,new Date().toISOString());});run();applied.add(name);}secureFile(dbPath);return {applied:[...applied].sort(),pending:files.filter(x=>!applied.has(x))};}finally{db.close();}}
export function sqliteStatus(dbPath:string,migrationsDir:string):MigrationStatus{const files=readdirSync(migrationsDir).filter(x=>x.endsWith('.sql')).sort();try{const db=new Database(dbPath,{readonly:true});const applied=(db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='schema_migrations'").get()?db.prepare('SELECT name FROM schema_migrations').all() as {name:string}[]:[]).map(x=>x.name);db.close();return {applied,pending:files.filter(x=>!applied.includes(x))};}catch{return {applied:[],pending:files};}}
/** Creates a timestamped SQLite backup through SQLite's online backup API, then atomically publishes it. */
export async function backupSqlite(dbPath:string,backupDir:string,retention=7):Promise<{path:string;retained:number}>{
 if(!existsSync(dbPath))throw new Error(`database does not exist: ${dbPath}`);secureDirectory(backupDir);const stamp=new Date().toISOString().replace(/[:.]/g,'-');const target=join(backupDir,`robinhood-lp-${stamp}.sqlite`),temporary=`${target}.${randomUUID()}.tmp`,db=new Database(dbPath,{readonly:true});
 try{await db.backup(temporary);}finally{db.close();}secureFile(temporary);renameSync(temporary,target);const backups=readdirSync(backupDir).filter(x=>/^robinhood-lp-.*\.sqlite$/.test(x)).sort().reverse();for(const stale of backups.slice(Math.max(0,retention)))unlinkSync(join(backupDir,stale));return {path:target,retained:Math.min(backups.length,retention)};
}
/** Testable restore helper; target must not exist to avoid accidental overwrite. */
export function restoreSqliteBackup(backupPath:string,targetPath:string){if(!existsSync(backupPath))throw new Error(`backup does not exist: ${backupPath}`);if(existsSync(targetPath))throw new Error(`refusing to overwrite existing database: ${targetPath}`);secureDirectory(dirname(targetPath));copyFileSync(backupPath,targetPath);secureFile(targetPath);}
/** Receipt/log-derived repository. The tx hash + log index unique keys make reruns and restarts idempotent. */
export class SqliteLedgerRepository{
 readonly db:Database.Database;
 private closed=false;
 constructor(readonly path:string,options:{busyTimeoutMs?:number}={}){secureDirectory(dirname(path));this.db=new Database(path);configure(this.db,options.busyTimeoutMs);secureFile(path);}
 close(){if(!this.closed){this.db.close();this.closed=true;}}
 ensurePosition(id:string,tokenId:string,pool:string){this.db.prepare('INSERT OR IGNORE INTO positions(id,token_id,pool_address,status,created_at) VALUES(?,?,?,?,?)').run(id,tokenId,pool,'open',new Date().toISOString());}
  persistStrategyPosition(input:{positionId:string;strategyMode:'BALANCED'|'SINGLE_SIDED_DOWNSIDE';targetToken?:string;fundingToken?:string;upperDropPct?:number;lowerDropPct?:number;requestedUpperPrice?:number;requestedLowerPrice?:number;actualUpperPrice?:number;actualLowerPrice?:number;tickLower?:number;tickUpper?:number;initialFundingRaw?:bigint;targetDesiredRaw?:bigint;fundingDesiredRaw?:bigint;benchmarkAsset?:string;intent?:unknown;simulation?:unknown}){const stringify=(value:unknown)=>JSON.stringify(value,(_,v)=>typeof v==='bigint'?v.toString():v);this.db.prepare('INSERT INTO position_strategy_details(position_id,strategy_mode,target_token,funding_token,upper_drop_pct,lower_drop_pct,requested_upper_price,requested_lower_price,actual_upper_price,actual_lower_price,tick_lower,tick_upper,initial_funding_raw,target_desired_raw,funding_desired_raw,benchmark_asset,intent_json,simulation_json,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(position_id) DO UPDATE SET strategy_mode=excluded.strategy_mode,target_token=excluded.target_token,funding_token=excluded.funding_token,upper_drop_pct=excluded.upper_drop_pct,lower_drop_pct=excluded.lower_drop_pct,requested_upper_price=excluded.requested_upper_price,requested_lower_price=excluded.requested_lower_price,actual_upper_price=excluded.actual_upper_price,actual_lower_price=excluded.actual_lower_price,tick_lower=excluded.tick_lower,tick_upper=excluded.tick_upper,initial_funding_raw=excluded.initial_funding_raw,target_desired_raw=excluded.target_desired_raw,funding_desired_raw=excluded.funding_desired_raw,benchmark_asset=excluded.benchmark_asset,intent_json=excluded.intent_json,simulation_json=excluded.simulation_json,updated_at=excluded.updated_at').run(input.positionId,input.strategyMode,input.targetToken??null,input.fundingToken??null,input.upperDropPct??null,input.lowerDropPct??null,input.requestedUpperPrice??null,input.requestedLowerPrice??null,input.actualUpperPrice??null,input.actualLowerPrice??null,input.tickLower??null,input.tickUpper??null,input.initialFundingRaw?.toString()??null,input.targetDesiredRaw?.toString()??null,input.fundingDesiredRaw?.toString()??null,input.benchmarkAsset??null,stringify(input.intent??{}),stringify(input.simulation??{}),new Date().toISOString());}
 strategyPosition(positionId:string){return this.db.prepare('SELECT * FROM position_strategy_details WHERE position_id=?').get(positionId) as Record<string,unknown>|undefined;}
 persistIntent(id:string,key:string,payload:unknown){this.db.prepare('INSERT OR IGNORE INTO transaction_intents(id,idempotency_key,state,payload_json,created_at) VALUES(?,?,?,?,?)').run(id,key,'simulated',JSON.stringify(payload),new Date().toISOString());}
 persistReceipt(hash:string,intentId:string|undefined,receipt:unknown){this.db.prepare('INSERT OR IGNORE INTO transaction_receipts(tx_hash,intent_id,receipt_json,reconciled_at) VALUES(?,?,?,NULL)').run(hash,intentId??null,JSON.stringify(receipt,(_,v)=>typeof v==='bigint'?v.toString():v));}
 ingestDeposit(input:{id:string;positionId:string;txHash:string;logIndex:number;amounts:TokenAmounts;blockNumber:bigint;blockTimestamp:string}){return this.db.prepare('INSERT OR IGNORE INTO position_deposits(id,position_id,tx_hash,log_index,token0_raw,token1_raw,prices_json,block_number,block_timestamp) VALUES(?,?,?,?,?,?,?,?,?)').run(input.id,input.positionId,input.txHash,input.logIndex,input.amounts.token0.toString(),input.amounts.token1.toString(),'{}',input.blockNumber.toString(),input.blockTimestamp).changes>0;}
 ingestLiquidityChange(input:{id:string;positionId:string;txHash:string;logIndex:number;kind:'decrease'|'increase';amounts:TokenAmounts}){return this.db.prepare('INSERT OR IGNORE INTO liquidity_changes(id,position_id,tx_hash,log_index,kind,token0_raw,token1_raw) VALUES(?,?,?,?,?,?,?)').run(input.id,input.positionId,input.txHash,input.logIndex,input.kind,input.amounts.token0.toString(),input.amounts.token1.toString()).changes>0;}
 ingestGas(positionId:string,hash:string,nativeRaw:bigint){return this.db.prepare('INSERT OR IGNORE INTO gas_costs(id,position_id,tx_hash,native_raw,usd_value) VALUES(?,?,?,?,NULL)').run(`gas:${hash}`,positionId,hash,nativeRaw.toString()).changes>0;}
 v4BurnEvidence(tokenId:bigint|string){const position=this.v4Position(tokenId);if(!position||!position.mint_hash)return {previouslyMinted:false,burnConfirmed:false};const burn=this.db.prepare("SELECT i.id,i.tx_hash FROM v4_lifecycle_intents i JOIN v4_lifecycle_receipts r ON r.intent_id=i.id AND r.tx_hash=i.tx_hash WHERE i.token_id=? AND i.action='burn' AND i.state='BURNED' AND i.tx_hash IS NOT NULL ORDER BY i.updated_at DESC LIMIT 1").get(tokenId.toString()) as {id:string;tx_hash:string}|undefined;return {previouslyMinted:true,burnConfirmed:!!burn,burnTxHash:burn?.tx_hash,sourceIntentId:burn?.id};}
 finalizeV4TerminalAccounting(tokenId:bigint|string){const row=this.v4Position(tokenId);if(!row||String(row.status)!=='burned'||BigInt(String(row.liquidity_raw))!==0n)throw new Error('V4_TERMINAL_EVIDENCE_INCOMPLETE');const evidence=this.v4BurnEvidence(tokenId);if(!evidence.burnConfirmed||!evidence.burnTxHash||!evidence.sourceIntentId)throw new Error('V4_TERMINAL_BURN_RECEIPT_MISSING');const positionId=`v4:${tokenId}`,before=this.positionAccounting(positionId),at=new Date().toISOString(),insert=this.db.prepare('INSERT OR IGNORE INTO v4_terminal_differences(id,position_id,token_index,token_address,amount_raw,reason,source_intent_id,source_tx_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?)');let inserted=0;for(const [index,amount,address] of [[0,before.pendingPrincipal.token0,String(row.currency0)],[1,before.pendingPrincipal.token1,String(row.currency1)]] as const)if(amount>0n)inserted+=insert.run(`v4-terminal:${tokenId}:${index}`,positionId,index,address,amount.toString(),'realized_shortfall',evidence.sourceIntentId,evidence.burnTxHash,at).changes;return {inserted,sourceIntentId:evidence.sourceIntentId,sourceTxHash:evidence.burnTxHash,accounting:this.positionAccounting(positionId)};}
 reconciliationDelta(positionId:string){const one=(table:string)=>Number((this.db.prepare(`SELECT COUNT(*) AS count FROM ${table} WHERE position_id=?`).get(positionId) as {count:number}).count);return {events:one('collections')+one('liquidity_changes'),deposits:one('position_deposits'),principal:one('principal_withdrawals'),fees:one('fee_claims')};}
 persistPnlSnapshot(id:string,positionId:string,payload:unknown){this.db.prepare('INSERT OR REPLACE INTO pnl_snapshots(id,position_id,payload_json,created_at) VALUES(?,?,?,?)').run(id,positionId,JSON.stringify(payload,(_,v)=>typeof v==='bigint'?v.toString():v),new Date().toISOString());}
 pnlSnapshot(id:string,positionId:string){const row=this.db.prepare('SELECT payload_json FROM pnl_snapshots WHERE id=? AND position_id=?').get(id,positionId) as {payload_json:string}|undefined;return row?JSON.parse(row.payload_json):undefined;}
 ingestCollection(input:{id:string;positionId:string;txHash:string;logIndex:number;amounts:TokenAmounts;pending:TokenAmounts}){const p0=input.pending.token0<input.amounts.token0?input.pending.token0:input.amounts.token0,p1=input.pending.token1<input.amounts.token1?input.pending.token1:input.amounts.token1,fee0=input.amounts.token0-p0,fee1=input.amounts.token1-p1;const write=this.db.transaction(()=>{const inserted=this.db.prepare('INSERT OR IGNORE INTO collections(id,position_id,tx_hash,log_index,token0_raw,token1_raw,principal0_raw,principal1_raw,fee0_raw,fee1_raw) VALUES(?,?,?,?,?,?,?,?,?,?)').run(input.id,input.positionId,input.txHash,input.logIndex,input.amounts.token0.toString(),input.amounts.token1.toString(),p0.toString(),p1.toString(),fee0.toString(),fee1.toString());if(!inserted.changes)return false;if(p0||p1)this.db.prepare('INSERT INTO principal_withdrawals(id,position_id,collection_id,token0_raw,token1_raw) VALUES(?,?,?,?,?)').run(`${input.id}:principal`,input.positionId,input.id,p0.toString(),p1.toString());if(fee0||fee1)this.db.prepare('INSERT INTO fee_claims(id,position_id,collection_id,token0_raw,token1_raw,claim_prices_json) VALUES(?,?,?,?,?,?)').run(`${input.id}:fees`,input.positionId,input.id,fee0.toString(),fee1.toString(),'{}');return true;});return write();}
 collectionTotals(positionId:string){const rows=this.db.prepare('SELECT principal0_raw,principal1_raw,fee0_raw,fee1_raw FROM collections WHERE position_id=?').all(positionId) as Array<Record<string,string>>;return rows.reduce((a,r)=>({principal:{token0:a.principal.token0+BigInt(r.principal0_raw),token1:a.principal.token1+BigInt(r.principal1_raw)},fees:{token0:a.fees.token0+BigInt(r.fee0_raw),token1:a.fees.token1+BigInt(r.fee1_raw)}}),{principal:zero(),fees:zero()});}
 positionAccounting(positionId:string):Pick<PositionLedger,'deposits'|'pendingPrincipal'|'withdrawnPrincipal'|'claimedFees'|'unclaimedFees'|'gasUsd'|'executionCostsUsd'|'events'|'allocations'>&{terminalDifferences:TokenAmounts;terminalDifferenceRecords:Record<string,unknown>[]}{const sum=(table:string,a:string,b:string)=>{const rows=this.db.prepare(`SELECT ${a} AS a, ${b} AS b FROM ${table} WHERE position_id=?`).all(positionId) as Array<{a:string;b:string}>;return rows.reduce<TokenAmounts>((total,row)=>({token0:total.token0+BigInt(row.a),token1:total.token1+BigInt(row.b)}),zero());};const deposits=sum('position_deposits','token0_raw','token1_raw'),changes=sum("liquidity_changes","token0_raw","token1_raw"),totals=this.collectionTotals(positionId),terminalDifferenceRecords=this.db.prepare("SELECT * FROM v4_terminal_differences WHERE position_id=? ORDER BY token_index,created_at").all(positionId) as Record<string,unknown>[],terminalDifferences=terminalDifferenceRecords.reduce<TokenAmounts>((a,row)=>{const key:keyof TokenAmounts=Number(row.token_index)===0?'token0':'token1';a[key]+=BigInt(String(row.amount_raw));return a;},zero()),gas=Number((this.db.prepare('SELECT COALESCE(SUM(usd_value),0) AS value FROM gas_costs WHERE position_id=?').get(positionId) as {value:number}).value),cost=Number((this.db.prepare('SELECT COALESCE(SUM(execution_cost_usd),0) AS value FROM swaps WHERE position_id=?').get(positionId) as {value:number}).value);return {deposits,pendingPrincipal:{token0:changes.token0-totals.principal.token0-terminalDifferences.token0,token1:changes.token1-totals.principal.token1-terminalDifferences.token1},withdrawnPrincipal:totals.principal,claimedFees:totals.fees,terminalDifferences,terminalDifferenceRecords,unclaimedFees:zero(),gasUsd:gas,executionCostsUsd:cost,events:[],allocations:[]};}
 recordReconciliation(id:string,positionId:string,details:unknown){this.db.prepare('INSERT OR REPLACE INTO reconciliation_runs(id,position_id,status,details_json,created_at) VALUES(?,?,?,?,?)').run(id,positionId,'complete',JSON.stringify(details,(_,v)=>typeof v==='bigint'?v.toString():v),new Date().toISOString());}
 listPositions(){return this.db.prepare('SELECT id,token_id,pool_address,status,created_at FROM positions ORDER BY created_at').all() as Array<{id:string;token_id:string;pool_address:string;status:string;created_at:string}>;}
 /** Local receipt-derived reconciliation is intentionally idempotent; chain readers may enrich it separately. */
 reconcileAll(){const at=new Date().toISOString();return this.listPositions().map(position=>{const details={positionId:position.id,observed:this.reconciliationDelta(position.id),source:'persisted receipt/log ledger',at};this.recordReconciliation(`startup:${position.id}`,position.id,details);return details;});}
 safetyState(){const row=this.db.prepare('SELECT payload_json FROM operator_safety_state WHERE id=1').get() as {payload_json:string}|undefined;return row?JSON.parse(row.payload_json):undefined;}
 persistSafetyState(payload:unknown){this.db.prepare('INSERT INTO operator_safety_state(id,payload_json,updated_at) VALUES(1,?,?) ON CONFLICT(id) DO UPDATE SET payload_json=excluded.payload_json,updated_at=excluded.updated_at').run(JSON.stringify(payload),new Date().toISOString());}
 setManualPause(paused:boolean,actor:string,reason?:string){const prior=this.safetyState()??{};this.persistSafetyState({...prior,manualPause:paused,manualPauseActor:actor,manualPauseReason:reason?.trim()||undefined,manualPauseAt:new Date().toISOString()});}
 canaryBudget(){return this.db.prepare('SELECT * FROM canary_budget WHERE id=1').get() as Record<string,unknown>|undefined;}
 canaryBudgetAvailable(){const row=this.canaryBudget();return row?.status==='AVAILABLE'&&Number(row.attempts_used)===0;}
 updateCanaryBudgetState(state:'APPROVAL_SUBMITTED'|'MINT_SUBMITTED',intentId:string){return this.db.prepare("UPDATE canary_budget SET status=?,updated_at=? WHERE id=1 AND intent_id=? AND status IN ('CLAIMED','APPROVAL_SUBMITTED')").run(state,new Date().toISOString(),intentId).changes===1;}
 finalizeCanaryBudget(intentId:string,succeeded:boolean,input:{failureReason?:string;remainingAllowanceRaw?:bigint}={}){const at=new Date().toISOString(),state=succeeded?'SUCCEEDED':'FAILED',finish=this.db.transaction(()=>{const changed=this.db.prepare("UPDATE canary_budget SET status=?,attempts_used=1,failure_reason=?,remaining_allowance_raw=?,updated_at=? WHERE id=1 AND intent_id=? AND status NOT IN ('SUCCEEDED','FAILED')").run(state,input.failureReason??null,input.remainingAllowanceRaw?.toString()??null,at,intentId).changes===1;if(changed)this.setManualPause(true,`canary-budget:${state.toLowerCase()}`);return changed;});return finish();}
 requestCanaryBudgetReset(now=Date.now(),ttlMs=300_000){const token=randomUUID(),hash=createHash('sha256').update(token).digest('hex'),expiresAt=new Date(now+ttlMs).toISOString();this.db.prepare('UPDATE canary_budget SET reset_token_hash=?,reset_expires_at=?,updated_at=? WHERE id=1').run(hash,expiresAt,new Date(now).toISOString());return {token,expiresAt};}
 resetCanaryBudget(token:string,now=Date.now()){const hash=createHash('sha256').update(token).digest('hex'),at=new Date(now).toISOString(),reset=this.db.transaction(()=>{const row=this.canaryBudget();if(!row||row.reset_token_hash!==hash||!row.reset_expires_at||Date.parse(String(row.reset_expires_at))<=now)return false;this.db.prepare("UPDATE canary_budget SET status='AVAILABLE',attempts_used=0,intent_id=NULL,failure_reason=NULL,remaining_allowance_raw=NULL,reset_token_hash=NULL,reset_expires_at=NULL,updated_at=? WHERE id=1").run(at);this.setManualPause(false,'canary-budget-manual-reset');return true;});return reset();}
 createPoolSelection(input:{userId:string;chatId:string;sessionId:string;poolAddress:string;factoryAddress:string;token0Address:string;token1Address:string;fee:number;tickSpacing:number;discoveryBlock:bigint;liquidity:bigint;tvlUsd?:number;tvlSource?:string;tvlObservedAtMs?:number;tvlFreshUntilMs?:number;tvlStatus?:string;initialized:boolean}){const id=randomUUID();this.db.prepare('INSERT INTO canary_pool_selections(id,user_id,chat_id,session_id,pool_address,factory_address,token0_address,token1_address,fee,tick_spacing,discovery_block,liquidity_raw,tvl_usd,tvl_source,tvl_observed_at_ms,tvl_fresh_until_ms,tvl_status,initialized,superseded,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,?)').run(id,input.userId,input.chatId,input.sessionId,input.poolAddress,input.factoryAddress,input.token0Address,input.token1Address,input.fee,input.tickSpacing,input.discoveryBlock.toString(),input.liquidity.toString(),input.tvlUsd??null,input.tvlSource??null,input.tvlObservedAtMs??null,input.tvlFreshUntilMs??null,input.tvlStatus??'missing',input.initialized?1:0,new Date().toISOString());return this.poolSelection(id)!;}
 poolSelection(id:string){return this.db.prepare('SELECT * FROM canary_pool_selections WHERE id=?').get(id) as Record<string,unknown>|undefined;}
 supersedePoolSelections(userId:string,chatId:string,exceptSessionId?:string){const suffix=exceptSessionId?' AND session_id<>?':'',args=exceptSessionId?[userId,chatId,exceptSessionId]:[userId,chatId];return this.db.prepare(`UPDATE canary_pool_selections SET superseded=1 WHERE user_id=? AND chat_id=? AND superseded=0${suffix}`).run(...args).changes;}
 createConfirmation(input:{action:string;payload:unknown;expiresAt:string;owner:string;idempotencyKey:string;blockNumber?:string;priceObservedAt?:string}){const existing=this.db.prepare('SELECT * FROM confirmation_requests WHERE idempotency_key=?').get(input.idempotencyKey) as Record<string,unknown>|undefined;if(existing)return existing;const id=randomUUID();this.db.prepare('INSERT INTO confirmation_requests(id,idempotency_key,action,payload_json,state,owner,block_number,price_observed_at,expires_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,input.idempotencyKey,input.action,JSON.stringify(input.payload,(_,v)=>typeof v==='bigint'?v.toString():v),'AWAITING_CONFIRMATION',input.owner,input.blockNumber??null,input.priceObservedAt??null,input.expiresAt,new Date().toISOString());return this.confirmation(id);}
 confirmation(id:string):Record<string,unknown>|undefined{const row=this.db.prepare('SELECT * FROM confirmation_requests WHERE id=?').get(id) as Record<string,unknown>|undefined;if(!row)return undefined;if(row.state==='AWAITING_CONFIRMATION'&&String(row.expires_at)<new Date().toISOString()){this.db.prepare("UPDATE confirmation_requests SET state='EXPIRED',updated_at=? WHERE id=? AND state='AWAITING_CONFIRMATION'").run(new Date().toISOString(),id);return this.confirmation(id);}return row;}
 resolveConfirmation(id:string,owner:string,decision:'confirm'|'cancel',currentBlock?:string){const row=this.confirmation(id);if(!row)throw new Error('unknown confirmation ID');if(row.owner!==owner)throw new Error('confirmation owner mismatch');if(row.state!=='AWAITING_CONFIRMATION')throw new Error(`confirmation is ${String(row.state)}`);if(decision==='cancel'){this.db.prepare("UPDATE confirmation_requests SET state='CANCELLED',updated_at=? WHERE id=? AND state='AWAITING_CONFIRMATION'").run(new Date().toISOString(),id);return this.confirmation(id)!;}const stale=currentBlock!==undefined&&row.block_number!==null&&BigInt(currentBlock)>BigInt(String(row.block_number))+5n;if(stale||this.pendingTransactions()>0){this.db.prepare("UPDATE confirmation_requests SET state='EXECUTION_BLOCKED',updated_at=? WHERE id=?").run(new Date().toISOString(),id);throw new Error(stale?'preview is stale; refresh and re-simulate':'pending transaction detected; wait for reconciliation');}this.db.prepare("UPDATE confirmation_requests SET state='EXECUTION_BLOCKED',updated_at=? WHERE id=? AND state='AWAITING_CONFIRMATION'").run(new Date().toISOString(),id);return this.confirmation(id)!;}
 recoverConfirmations(){return this.db.prepare("UPDATE confirmation_requests SET state='EXPIRED',updated_at=? WHERE state IN ('DRAFT','SIMULATED','AWAITING_CONFIRMATION') AND expires_at<?").run(new Date().toISOString(),new Date().toISOString()).changes;}
 session(owner:string){const row=this.db.prepare('SELECT state_json FROM telegram_sessions WHERE owner=?').get(owner) as {state_json:string}|undefined;return row?JSON.parse(row.state_json):undefined;}
 persistSession(owner:string,state:unknown){this.db.prepare('INSERT INTO telegram_sessions(owner,state_json,updated_at) VALUES(?,?,?) ON CONFLICT(owner) DO UPDATE SET state_json=excluded.state_json,updated_at=excluded.updated_at').run(owner,jsonStringify(state),new Date().toISOString());}
 clearSession(owner:string){this.db.prepare('DELETE FROM telegram_sessions WHERE owner=?').run(owner);}
 /** Atomic, restart-safe Telegram flow storage. Epoch milliseconds are used exclusively. */
 createTelegramFlow(input:{userId:string;chatId:string;state:Record<string,unknown>;now:number;ttlMs:number}){const scope=`${input.userId}:${input.chatId}`,sessionId=randomUUID(),expiresAtMs=computeExpiresAt(input.now,input.ttlMs),stateJson=jsonStringify(input.state),create=this.db.transaction(()=>{this.db.prepare("UPDATE telegram_flow_sessions SET status='expired',updated_at_ms=? WHERE scope=? AND status='active' AND expires_at_ms<=?").run(input.now,scope,input.now);this.db.prepare("UPDATE telegram_flow_sessions SET status='superseded',updated_at_ms=? WHERE scope=? AND status='active'").run(input.now,scope);this.db.prepare('INSERT INTO telegram_flow_sessions(session_id,scope,user_id,chat_id,state_json,status,created_at_ms,updated_at_ms,expires_at_ms) VALUES(?,?,?,?,?,?,?,?,?)').run(sessionId,scope,input.userId,input.chatId,stateJson,'active',input.now,input.now,expiresAtMs);});create();return {sessionId,userId:input.userId,chatId:input.chatId,state:input.state,status:'active' as const,createdAtMs:input.now,updatedAtMs:input.now,expiresAtMs};}
 private mapTelegramFlow(row:{session_id:string;user_id:string;chat_id:string;state_json:string;status:TelegramFlowStatus;created_at_ms:number;updated_at_ms:number;expires_at_ms:number}):TelegramFlowSession{return {sessionId:row.session_id,userId:row.user_id,chatId:row.chat_id,state:JSON.parse(row.state_json),status:row.status,createdAtMs:row.created_at_ms,updatedAtMs:row.updated_at_ms,expiresAtMs:row.expires_at_ms};}
 /** Historical lookup used for callback ownership/audit. It may return a terminal flow. */
 telegramFlow(input:{userId:string;chatId:string;sessionId?:string;now:number}):TelegramFlowSession|undefined{const scope=`${input.userId}:${input.chatId}`;if(input.sessionId)this.db.prepare("UPDATE telegram_flow_sessions SET status='expired',updated_at_ms=? WHERE scope=? AND session_id=? AND status='active' AND expires_at_ms<=?").run(input.now,scope,input.sessionId,input.now);const clause=input.sessionId?'scope=? AND session_id=?':'scope=?',args=input.sessionId?[scope,input.sessionId]:[scope],row=this.db.prepare(`SELECT * FROM telegram_flow_sessions WHERE ${clause} ORDER BY updated_at_ms DESC,created_at_ms DESC LIMIT 1`).get(...args) as Parameters<SqliteLedgerRepository['mapTelegramFlow']>[0]|undefined;return row?this.mapTelegramFlow(row):undefined;}
 /** The only lookup suitable for routing new state-dependent Telegram text. */
 activeTelegramFlow(input:{userId:string;chatId:string;now:number}):TelegramFlowSession|undefined{const scope=`${input.userId}:${input.chatId}`;this.db.prepare("UPDATE telegram_flow_sessions SET status='expired',updated_at_ms=? WHERE scope=? AND status='active' AND expires_at_ms<=?").run(input.now,scope,input.now);const row=this.db.prepare("SELECT * FROM telegram_flow_sessions WHERE scope=? AND status='active' AND expires_at_ms>? ORDER BY updated_at_ms DESC LIMIT 1").get(scope,input.now) as Parameters<SqliteLedgerRepository['mapTelegramFlow']>[0]|undefined;return row?this.mapTelegramFlow(row):undefined;}
 transitionTelegramFlow(input:{userId:string;chatId:string;sessionId:string;state:Record<string,unknown>;now:number;ttlMs:number}){const scope=`${input.userId}:${input.chatId}`,expiresAtMs=computeExpiresAt(input.now,input.ttlMs),updated=this.db.prepare("UPDATE telegram_flow_sessions SET state_json=?,updated_at_ms=?,expires_at_ms=? WHERE scope=? AND session_id=? AND status='active' AND expires_at_ms>?").run(jsonStringify(input.state),input.now,expiresAtMs,scope,input.sessionId,input.now);if(!updated.changes)return undefined;return this.telegramFlow({userId:input.userId,chatId:input.chatId,sessionId:input.sessionId,now:input.now});}
 applyTelegramHydrationRender(input:{userId:string;chatId:string;sessionId:string;state:Record<string,unknown>;now:number;ttlMs:number;selections:Array<{id:string;liquidity:bigint;refreshBlock?:bigint;eligibility:boolean;blockers:string[]}>}){const scope=`${input.userId}:${input.chatId}`,expiresAtMs=computeExpiresAt(input.now,input.ttlMs),stateJson=jsonStringify(input.state),updateSelection=this.db.prepare('UPDATE v4_pool_selections SET liquidity_raw=?,refresh_block=?,eligibility=?,blockers_json=? WHERE id=? AND superseded=0'),updateFlow=this.db.prepare("UPDATE telegram_flow_sessions SET state_json=?,updated_at_ms=?,expires_at_ms=? WHERE scope=? AND session_id=? AND status='active' AND expires_at_ms>?"),run=this.db.transaction(()=>{for(const selection of input.selections)updateSelection.run(selection.liquidity.toString(),selection.refreshBlock?.toString()??null,selection.eligibility?1:0,JSON.stringify(selection.blockers),selection.id);return updateFlow.run(stateJson,input.now,expiresAtMs,scope,input.sessionId,input.now).changes;});if(!run())return undefined;return this.telegramFlow({userId:input.userId,chatId:input.chatId,sessionId:input.sessionId,now:input.now});}
 cancelTelegramFlow(input:{userId:string;chatId:string;sessionId?:string}){const scope=`${input.userId}:${input.chatId}`,where=input.sessionId?' AND session_id=?':'',args=input.sessionId?[scope,input.sessionId]:[scope];return this.db.prepare(`UPDATE telegram_flow_sessions SET status='cancelled' WHERE scope=?${where} AND status='active'`).run(...args).changes>0;}
 recoverTelegramFlows(now:number){return this.db.prepare("UPDATE telegram_flow_sessions SET status='expired' WHERE status='active' AND expires_at_ms<=?").run(now).changes;}
 telegramFlowDiagnostics(input:{userId:string;chatId:string;now:number}){const scope=`${input.userId}:${input.chatId}`;return (this.db.prepare('SELECT session_id,state_json,status,created_at_ms,updated_at_ms,expires_at_ms FROM telegram_flow_sessions WHERE scope=? ORDER BY updated_at_ms DESC,created_at_ms DESC').all(scope) as Array<{session_id:string;state_json:string;status:TelegramFlowStatus;created_at_ms:number;updated_at_ms:number;expires_at_ms:number}>).map(row=>({sessionId:row.session_id,state:JSON.parse(row.state_json),status:row.status,createdAtMs:row.created_at_ms,updatedAtMs:row.updated_at_ms,expiresAtMs:row.expires_at_ms,qualifiesAsActive:row.status==='active'&&row.expires_at_ms>input.now}));}
 telegramFlowAudit(now:number){return (this.db.prepare('SELECT session_id,state_json,status,created_at_ms,updated_at_ms,expires_at_ms FROM telegram_flow_sessions ORDER BY updated_at_ms DESC,created_at_ms DESC').all() as Array<{session_id:string;state_json:string;status:TelegramFlowStatus;created_at_ms:number;updated_at_ms:number;expires_at_ms:number}>).map(row=>({sessionId:row.session_id,state:JSON.parse(row.state_json),status:row.status,createdAtMs:row.created_at_ms,updatedAtMs:row.updated_at_ms,expiresAtMs:row.expires_at_ms,qualifiesAsActive:row.status==='active'&&row.expires_at_ms>now}));}
 pendingTransactions(){return Number((this.db.prepare("SELECT COUNT(*) AS count FROM transaction_intents WHERE state='submitted'").get() as {count:number}).count);}
 acquireNonceMutex(wallet:string,nonce:bigint,ttlSeconds=300){const key=wallet.trim().toLowerCase(),now=new Date(),expires=new Date(now.getTime()+ttlSeconds*1000).toISOString(),acquire=this.db.transaction(()=>{this.db.prepare('DELETE FROM nonce_mutex WHERE expires_at<?').run(now.toISOString());if(this.db.prepare('SELECT 1 FROM nonce_mutex WHERE lower(wallet)=? LIMIT 1').get(key))return false;return this.db.prepare('INSERT OR IGNORE INTO nonce_mutex(wallet,nonce,acquired_at,expires_at) VALUES(?,?,?,?)').run(key,nonce.toString(),now.toISOString(),expires).changes===1;});return acquire();}
 releaseNonceMutex(wallet:string){return this.db.prepare('DELETE FROM nonce_mutex WHERE lower(wallet)=?').run(wallet.trim().toLowerCase()).changes>0;}
 armCanary(input:{userId:string;chatId:string;now:number;ttlMs:number}){const id=randomUUID(),expires=input.now+input.ttlMs,run=this.db.transaction(()=>{this.db.prepare("UPDATE canary_arms SET status='EXPIRED' WHERE status='ARMED' AND expires_at_ms<=?").run(input.now);this.db.prepare("UPDATE canary_arms SET status='DISARMED' WHERE user_id=? AND chat_id=? AND status='ARMED'").run(input.userId,input.chatId);this.db.prepare('INSERT INTO canary_arms(id,user_id,chat_id,status,expires_at_ms,created_at) VALUES(?,?,?,?,?,?)').run(id,input.userId,input.chatId,'ARMED',expires,new Date().toISOString());});run();return {id,expiresAtMs:expires};}
 requestCanaryArm(input:{userId:string;chatId:string;now:number;ttlMs:number}){const id=randomUUID(),expires=input.now+input.ttlMs;this.db.prepare("UPDATE canary_arms SET status='EXPIRED' WHERE user_id=? AND chat_id=? AND status='PENDING'").run(input.userId,input.chatId);this.db.prepare('INSERT INTO canary_arms(id,user_id,chat_id,status,expires_at_ms,created_at) VALUES(?,?,?,?,?,?)').run(id,input.userId,input.chatId,'PENDING',expires,new Date().toISOString());return {id,expiresAtMs:expires};}
 confirmCanaryArm(input:{userId:string;chatId:string;id:string;now:number;ttlMs:number}){const expires=input.now+input.ttlMs,run=this.db.transaction(()=>{this.db.prepare("UPDATE canary_arms SET status='DISARMED' WHERE user_id=? AND chat_id=? AND status='ARMED'").run(input.userId,input.chatId);return this.db.prepare("UPDATE canary_arms SET status='ARMED',expires_at_ms=? WHERE id=? AND user_id=? AND chat_id=? AND status='PENDING' AND expires_at_ms>?").run(expires,input.id,input.userId,input.chatId,input.now).changes===1;});return run()?{id:input.id,expiresAtMs:expires}:undefined;}
 disarmCanary(userId:string,chatId:string){return this.db.prepare("UPDATE canary_arms SET status='DISARMED' WHERE user_id=? AND chat_id=? AND status='ARMED'").run(userId,chatId).changes>0;}
 activeCanaryArm(userId:string,chatId:string,now:number){this.db.prepare("UPDATE canary_arms SET status='EXPIRED' WHERE status='ARMED' AND expires_at_ms<=?").run(now);return this.db.prepare("SELECT id,expires_at_ms FROM canary_arms WHERE user_id=? AND chat_id=? AND status='ARMED' AND expires_at_ms>? ORDER BY created_at DESC LIMIT 1").get(userId,chatId,now) as {id:string;expires_at_ms:number}|undefined;}
 consumeCanaryArm(userId:string,chatId:string,id:string,now:number){return this.db.prepare("UPDATE canary_arms SET status='CONSUMED',consumed_at=? WHERE id=? AND user_id=? AND chat_id=? AND status='ARMED' AND expires_at_ms>?").run(new Date().toISOString(),id,userId,chatId,now).changes===1;}
 createCanaryIntent(input:{wallet:string;owner:string;idempotencyKey:string;payload:unknown}){const existing=this.db.prepare('SELECT * FROM canary_execution_intents WHERE idempotency_key=?').get(input.idempotencyKey) as Record<string,unknown>|undefined;if(existing)return existing;const id=randomUUID(),at=new Date().toISOString();const create=this.db.transaction(()=>{this.db.prepare('INSERT INTO canary_execution_intents(id,wallet,owner,state,idempotency_key,payload_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(id,input.wallet,input.owner,'PREVIEWED',input.idempotencyKey,JSON.stringify(input.payload,(_,v)=>typeof v==='bigint'?v.toString():v),at,at);this.db.prepare('INSERT OR IGNORE INTO canary_execution_transitions(intent_id,state,created_at) VALUES(?,?,?)').run(id,'PREVIEWED',at);});create();return this.canaryIntent(id)!;}
 claimPreparedCanaryIntent(input:{intentId:string;owner:string;wallet:string}){const at=new Date().toISOString(),claim=this.db.transaction(()=>{const intent=this.canaryIntent(input.intentId);if(!intent||intent.owner!==input.owner||String(intent.wallet).toLowerCase()!==input.wallet.toLowerCase())return {status:'INVALID_INTENT' as const};if(intent.state!=='PREVIEWED')return {status:'ALREADY_CLAIMED' as const,intent};const budget=this.db.prepare("UPDATE canary_budget SET status='CLAIMED',attempts_used=1,intent_id=?,updated_at=? WHERE id=1 AND status='AVAILABLE' AND attempts_used=0").run(input.intentId,at).changes===1;if(!budget)return {status:'CANARY_BUDGET_UNAVAILABLE' as const};return {status:'CLAIMED' as const,intent:this.canaryIntent(input.intentId)!};});return claim();}
 canaryIntent(id:string){return this.db.prepare('SELECT * FROM canary_execution_intents WHERE id=?').get(id) as Record<string,unknown>|undefined;}
 canaryIntentByKey(key:string){return this.db.prepare('SELECT * FROM canary_execution_intents WHERE idempotency_key=?').get(key) as Record<string,unknown>|undefined;}
 claimDirectCanaryIntent(input:{updateId:string;messageId:string;owner:string;userId:string;chatId:string;sessionId:string;selectionId:string;wallet:string;now:number;payload:unknown}){const key=`telegram-amount:${input.chatId}:${input.messageId}:${input.updateId}`,claim=this.db.transaction(()=>{const existing=this.canaryIntentByKey(key);if(existing)return {status:'ALREADY_CLAIMED' as const,intent:existing};const selection=this.poolSelection(input.selectionId);if(!selection||selection.user_id!==input.userId||selection.chat_id!==input.chatId||selection.session_id!==input.sessionId||Number(selection.superseded)!==0)return {status:'STALE_POOL_SELECTION' as const};const id=randomUUID(),at=new Date(input.now).toISOString(),budget=this.db.prepare("UPDATE canary_budget SET status='CLAIMED',attempts_used=1,intent_id=?,updated_at=? WHERE id=1 AND status='AVAILABLE' AND attempts_used=0").run(id,at).changes===1;if(!budget)return {status:'CANARY_BUDGET_UNAVAILABLE' as const};this.db.prepare('INSERT INTO canary_execution_intents(id,wallet,owner,state,idempotency_key,payload_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(id,input.wallet,input.owner,'PREVIEWED',key,JSON.stringify({telegram:{updateId:input.updateId,messageId:input.messageId,userId:input.userId,chatId:input.chatId,sessionId:input.sessionId,selectionId:input.selectionId},intent:input.payload},(_,v)=>typeof v==='bigint'?v.toString():v),at,at);this.db.prepare('INSERT OR IGNORE INTO canary_execution_transitions(intent_id,state,created_at) VALUES(?,?,?)').run(id,'PREVIEWED',at);return {status:'CLAIMED' as const,intent:this.canaryIntent(id)!};});return claim();}
 claimCanaryConfirmation(input:{confirmationId:string;owner:string;userId:string;chatId:string;wallet:string;now:number;payload:unknown}){const key=`telegram-canary:${input.confirmationId}`,claim=this.db.transaction(()=>{const existing=this.canaryIntentByKey(key);if(existing)return {status:'ALREADY_CLAIMED' as const,intent:existing};const confirmation=this.db.prepare('SELECT * FROM confirmation_requests WHERE id=?').get(input.confirmationId) as Record<string,unknown>|undefined;if(!confirmation||confirmation.owner!==input.owner||confirmation.action!=='SINGLE_SIDED_DOWNSIDE_MINT')return {status:'INVALID_CONFIRMATION' as const};if(confirmation.state!=='AWAITING_CONFIRMATION')return {status:'CONFIRMATION_NOT_ACTIVE' as const};if(Date.parse(String(confirmation.expires_at))<=input.now){this.db.prepare("UPDATE confirmation_requests SET state='EXPIRED',updated_at=? WHERE id=? AND state='AWAITING_CONFIRMATION'").run(new Date(input.now).toISOString(),input.confirmationId);return {status:'CONFIRMATION_EXPIRED' as const};}const id=randomUUID(),at=new Date(input.now).toISOString(),budget=this.db.prepare("UPDATE canary_budget SET status='CLAIMED',attempts_used=1,intent_id=?,updated_at=? WHERE id=1 AND status='AVAILABLE' AND attempts_used=0").run(id,at).changes===1;if(!budget)return {status:'CANARY_BUDGET_UNAVAILABLE' as const};this.db.prepare('INSERT INTO canary_execution_intents(id,wallet,owner,state,idempotency_key,payload_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(id,input.wallet,input.owner,'PREVIEWED',key,JSON.stringify(input.payload,(_,v)=>typeof v==='bigint'?v.toString():v),at,at);this.db.prepare('INSERT OR IGNORE INTO canary_execution_transitions(intent_id,state,created_at) VALUES(?,?,?)').run(id,'PREVIEWED',at);this.db.prepare("UPDATE confirmation_requests SET state='CONFIRMED',updated_at=? WHERE id=? AND state='AWAITING_CONFIRMATION'").run(at,input.confirmationId);return {status:'CLAIMED' as const,intent:this.canaryIntent(id)!};});return claim();}
 claimCanaryIntent(id:string){const at=new Date().toISOString(),claim=this.db.transaction(()=>{const changed=this.db.prepare("UPDATE canary_execution_intents SET state='FINAL_SIMULATION_PASSED',updated_at=? WHERE id=? AND state='PREVIEWED'").run(at,id).changes===1;if(changed)this.db.prepare('INSERT OR IGNORE INTO canary_execution_transitions(intent_id,state,created_at) VALUES(?,?,?)').run(id,'FINAL_SIMULATION_PASSED',at);return changed;});return claim();}
 transitionCanaryIntent(id:string,state:string,patch:{approvalHash?:string;mintHash?:string;tokenId?:string;failureReason?:string}={}){const at=new Date().toISOString(),transition=this.db.transaction(()=>{this.db.prepare('UPDATE canary_execution_intents SET state=?,approval_hash=COALESCE(?,approval_hash),mint_hash=COALESCE(?,mint_hash),token_id=COALESCE(?,token_id),failure_reason=COALESCE(?,failure_reason),updated_at=? WHERE id=?').run(state,patch.approvalHash??null,patch.mintHash??null,patch.tokenId??null,patch.failureReason??null,at,id);this.db.prepare('INSERT OR IGNORE INTO canary_execution_transitions(intent_id,state,created_at) VALUES(?,?,?)').run(id,state,at);});transition();return this.canaryIntent(id)!;}
 canaryIntentTransitions(id:string){return this.db.prepare('SELECT state,created_at FROM canary_execution_transitions WHERE intent_id=? ORDER BY created_at,rowid').all(id) as Array<{state:string;created_at:string}>;}
 activeCanaryExecutionCount(wallet:string){return Number((this.db.prepare("SELECT COUNT(*) AS count FROM canary_execution_intents WHERE wallet=? AND state IN ('PREVIEWED','FINAL_SIMULATION_PASSED','APPROVAL_REQUIRED','APPROVAL_SUBMITTED','APPROVAL_CONFIRMED','RANGE_REFRESHED','MINT_SIMULATION_PASSED','MINT_SUBMITTED')").get(wallet) as {count:number}).count);}
 upsertV4Position(input:{tokenId:bigint;owner:string;poolId:string;poolKey:unknown;currency0:string;currency1:string;fee:number;tickSpacing:number;hooks:string;tickLower:number;tickUpper:number;liquidity:bigint;initialAmount0:bigint;initialAmount1:bigint;mintHash:string;status?:'open'|'partially_closed'|'closed'|'burned';targetToken?:string;fundingToken?:string;targetSymbol?:string;fundingSymbol?:string;targetDecimals?:number;fundingDecimals?:number;targetIndex?:0|1;fundingIndex?:0|1;feeSemantics?:unknown;hookStatus?:unknown;valuationProvenance?:unknown;openIntentId?:string;openEvidence?:unknown}){const at=new Date().toISOString(),json=JSON.stringify(input.poolKey),j=(v:unknown)=>v===undefined?null:JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():x);this.db.prepare("INSERT INTO v4_positions(token_id,owner,pool_id,pool_key_json,currency0,currency1,fee,tick_spacing,hooks,tick_lower,tick_upper,liquidity_raw,initial_amount0_raw,initial_amount1_raw,status,mint_hash,created_at,updated_at,target_token,funding_token,target_symbol,funding_symbol,target_decimals,funding_decimals,target_index,funding_index,fee_semantics_json,hook_status_json,valuation_provenance_json,open_intent_id,open_evidence_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(token_id) DO UPDATE SET owner=excluded.owner,pool_id=excluded.pool_id,pool_key_json=excluded.pool_key_json,liquidity_raw=excluded.liquidity_raw,status=excluded.status,target_token=COALESCE(excluded.target_token,v4_positions.target_token),funding_token=COALESCE(excluded.funding_token,v4_positions.funding_token),updated_at=excluded.updated_at").run(input.tokenId.toString(),input.owner,input.poolId,json,input.currency0,input.currency1,input.fee,input.tickSpacing,input.hooks,input.tickLower,input.tickUpper,input.liquidity.toString(),input.initialAmount0.toString(),input.initialAmount1.toString(),input.status??'open',input.mintHash,at,at,input.targetToken??null,input.fundingToken??null,input.targetSymbol??null,input.fundingSymbol??null,input.targetDecimals??null,input.fundingDecimals??null,input.targetIndex??null,input.fundingIndex??null,j(input.feeSemantics),j(input.hookStatus),j(input.valuationProvenance),input.openIntentId??null,j(input.openEvidence));return this.v4Position(input.tokenId);}
 v4Position(tokenId:bigint|string){return this.db.prepare('SELECT * FROM v4_positions WHERE token_id=?').get(tokenId.toString()) as Record<string,unknown>|undefined;}
 listV4Positions(){return this.db.prepare('SELECT * FROM v4_positions ORDER BY created_at').all() as Record<string,unknown>[];}
 updateV4Position(input:{tokenId:bigint|string;liquidity:bigint;status:'open'|'partially_closed'|'closed'|'burned';principal?:TokenAmounts;fees?:TokenAmounts}){const at=new Date().toISOString(),row=this.v4Position(input.tokenId);if(!row)throw new Error('V4_POSITION_NOT_FOUND');const p=input.principal??zero(),f=input.fees??zero();this.db.prepare("UPDATE v4_positions SET liquidity_raw=?,status=?,withdrawn_principal0_raw=?,withdrawn_principal1_raw=?,claimed_fee0_raw=?,claimed_fee1_raw=?,updated_at=? WHERE token_id=?").run(input.liquidity.toString(),input.status,(BigInt(String(row.withdrawn_principal0_raw))+p.token0).toString(),(BigInt(String(row.withdrawn_principal1_raw))+p.token1).toString(),(BigInt(String(row.claimed_fee0_raw))+f.token0).toString(),(BigInt(String(row.claimed_fee1_raw))+f.token1).toString(),at,input.tokenId.toString());return this.v4Position(input.tokenId)!;}
 createV4LifecycleIntent(input:{tokenId:bigint|string;action:'collect'|'partial_close'|'full_close'|'burn';idempotencyKey:string;liquidity?:bigint;payload?:unknown}){const existing=this.db.prepare('SELECT * FROM v4_lifecycle_intents WHERE idempotency_key=?').get(input.idempotencyKey) as Record<string,unknown>|undefined;if(existing)return existing;const id=randomUUID(),at=new Date().toISOString(),run=this.db.transaction(()=>{this.db.prepare('INSERT INTO v4_lifecycle_intents(id,token_id,action,idempotency_key,state,liquidity_raw,payload_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,input.tokenId.toString(),input.action,input.idempotencyKey,'PREVIEWED',input.liquidity?.toString()??'0',JSON.stringify(input.payload??{},(_,v)=>typeof v==='bigint'?v.toString():v),at,at);this.db.prepare('INSERT INTO v4_lifecycle_transitions(intent_id,ordinal,state,details_json,created_at) VALUES(?,0,?,?,?)').run(id,'PREVIEWED','{}',at);});run();return this.v4LifecycleIntent(id)!;}
 v4LifecycleIntent(id:string){return this.db.prepare('SELECT * FROM v4_lifecycle_intents WHERE id=?').get(id) as Record<string,unknown>|undefined;}
 claimV4LifecycleIntent(id:string){const at=new Date().toISOString(),run=this.db.transaction(()=>{const changed=this.db.prepare("UPDATE v4_lifecycle_intents SET state='CLAIMED',updated_at=? WHERE id=? AND state='PREVIEWED'").run(at,id).changes===1;if(changed)this.db.prepare("INSERT INTO v4_lifecycle_transitions(intent_id,ordinal,state,details_json,created_at) SELECT ?,COALESCE(MAX(ordinal),-1)+1,'CLAIMED','{}',? FROM v4_lifecycle_transitions WHERE intent_id=?").run(id,at,id);return changed;});return run();}
 transitionV4LifecycleIntent(id:string,state:string,patch:{txHash?:string;failureReason?:string;details?:unknown}={}){const at=new Date().toISOString(),run=this.db.transaction(()=>{this.db.prepare('UPDATE v4_lifecycle_intents SET state=?,tx_hash=COALESCE(?,tx_hash),failure_reason=COALESCE(?,failure_reason),updated_at=? WHERE id=?').run(state,patch.txHash??null,patch.failureReason??null,at,id);this.db.prepare('INSERT OR IGNORE INTO v4_lifecycle_transitions(intent_id,ordinal,state,details_json,created_at) SELECT ?,COALESCE(MAX(ordinal),-1)+1,?,?,? FROM v4_lifecycle_transitions WHERE intent_id=?').run(id,state,JSON.stringify(patch.details??{},(_,v)=>typeof v==='bigint'?v.toString():v),at,id);});run();return this.v4LifecycleIntent(id)!;}
 v4LifecycleHistory(tokenId:bigint|string){return this.db.prepare('SELECT i.id,i.action,i.state,i.tx_hash,i.failure_reason,t.ordinal,t.state transition_state,t.details_json,t.created_at FROM v4_lifecycle_intents i JOIN v4_lifecycle_transitions t ON t.intent_id=i.id WHERE i.token_id=? ORDER BY i.created_at,t.ordinal').all(tokenId.toString()) as Record<string,unknown>[];}
 persistV4LifecycleReceipt(hash:string,intentId:string,receipt:unknown){return this.db.prepare('INSERT OR IGNORE INTO v4_lifecycle_receipts(tx_hash,intent_id,receipt_json,created_at) VALUES(?,?,?,?)').run(hash,intentId,JSON.stringify(receipt,(_,v)=>typeof v==='bigint'?v.toString():v),new Date().toISOString()).changes>0;}
 persistV4OperationalOpenReceipt(hash:string,intentId:string,phase:string,receipt:unknown){return this.db.prepare('INSERT OR IGNORE INTO v4_operational_open_receipts(tx_hash,intent_id,phase,receipt_json,created_at) VALUES(?,?,?,?,?)').run(hash,intentId,phase,JSON.stringify(receipt,(_,v)=>typeof v==='bigint'?v.toString():v),new Date().toISOString()).changes>0;}
 v4LifecycleReceipt(hash:string){return this.db.prepare('SELECT * FROM v4_lifecycle_receipts WHERE tx_hash=?').get(hash) as Record<string,unknown>|undefined;}
 v4LiveCanary(){return this.db.prepare('SELECT * FROM v4_live_canary WHERE id=1').get() as Record<string,unknown>;}
 claimV4LiveOpen(input:{intentId:string}){const at=new Date().toISOString(),run=this.db.transaction(()=>this.db.prepare("UPDATE v4_live_canary SET state='OPENING',open_intent_id=?,failure_reason=NULL,updated_at=? WHERE id=1 AND state='AVAILABLE_FOR_OPEN' AND token_id IS NULL").run(input.intentId,at).changes===1);return run();}
 claimV4OperationalOpen(input:{intentId:string}){const at=new Date().toISOString(),run=this.db.transaction(()=>{const changed=this.db.prepare("UPDATE v4_live_open_intents SET state='CLAIMED',updated_at=? WHERE id=? AND state='PREVIEWED'").run(at,input.intentId).changes===1;if(changed)this.db.prepare("INSERT OR IGNORE INTO v4_live_transitions(intent_id,ordinal,state,details_json,created_at) SELECT ?,COALESCE(MAX(ordinal),-1)+1,'CLAIMED','{}',? FROM v4_live_transitions WHERE intent_id=?").run(input.intentId,at,input.intentId);return changed;});return run();}
 markV4OperationalOpenRetryable(intentId:string){const at=new Date().toISOString(),run=this.db.transaction(()=>{const changed=this.db.prepare("UPDATE v4_live_open_intents SET state='FAILED_RETRYABLE',updated_at=? WHERE id=? AND state='FAILED' AND (json_extract(payload_json,'$.lane')='operational' OR json_extract(payload_json,'$.executor')='executeV4OperationalOpen') AND erc20_approval_hash IS NULL AND permit2_approval_hash IS NULL AND mint_hash IS NULL AND NOT EXISTS(SELECT 1 FROM v4_live_gas WHERE intent_id=v4_live_open_intents.id) AND NOT EXISTS(SELECT 1 FROM v4_operational_open_receipts WHERE intent_id=v4_live_open_intents.id)").run(at,intentId).changes===1;if(changed)this.db.prepare("INSERT OR IGNORE INTO v4_live_transitions(intent_id,ordinal,state,details_json,created_at) SELECT ?,COALESCE(MAX(ordinal),-1)+1,'FAILED_RETRYABLE',?,? FROM v4_live_transitions WHERE intent_id=?").run(intentId,JSON.stringify({safeToCreateFreshIntent:true,noTransactionBroadcast:true,lane:'operational'}),at,intentId);return changed;});return run();}
 claimV4LiveClose(input:{intentId:string;tokenId:string}){const at=new Date().toISOString(),run=this.db.transaction(()=>this.db.prepare("UPDATE v4_live_canary SET state='CLOSING',close_intent_id=?,failure_reason=NULL,updated_at=? WHERE id=1 AND state='OPENED' AND token_id=?").run(input.intentId,at,input.tokenId).changes===1);return run();}
 transitionV4LiveCanary(state:'AVAILABLE_FOR_OPEN'|'OPENING'|'OPENED'|'CLOSING'|'CLOSED'|'FAILED',patch:{tokenId?:string;closeIntentId?:string;failureReason?:string;remainingAllowance?:bigint}={}){const at=new Date().toISOString();this.db.prepare('UPDATE v4_live_canary SET state=?,token_id=COALESCE(?,token_id),close_intent_id=COALESCE(?,close_intent_id),failure_reason=COALESCE(?,failure_reason),remaining_allowance_raw=COALESCE(?,remaining_allowance_raw),updated_at=? WHERE id=1').run(state,patch.tokenId??null,patch.closeIntentId??null,patch.failureReason??null,patch.remainingAllowance?.toString()??null,at);return this.v4LiveCanary();}
 createV4LiveOpenIntent(input:{idempotencyKey:string;owner:string;userId?:string;chatId?:string;poolId:string;poolKey:unknown;amount:bigint;payload:unknown}){const prior=this.db.prepare('SELECT * FROM v4_live_open_intents WHERE idempotency_key=?').get(input.idempotencyKey) as Record<string,unknown>|undefined;if(prior)return prior;const id=randomUUID(),at=new Date().toISOString(),run=this.db.transaction(()=>{this.db.prepare("INSERT INTO v4_live_open_intents(id,idempotency_key,owner,telegram_user_id,telegram_chat_id,pool_id,pool_key_json,amount_raw,state,payload_json,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,? ,?,?,?)").run(id,input.idempotencyKey,input.owner,input.userId??null,input.chatId??null,input.poolId,JSON.stringify(input.poolKey),input.amount.toString(),'PREVIEWED',JSON.stringify(input.payload,(_,v)=>typeof v==='bigint'?v.toString():v),at,at);this.db.prepare("INSERT INTO v4_live_transitions(intent_id,ordinal,state,details_json,created_at) VALUES(?,0,'PREVIEWED','{}',?)").run(id,at);});run();return this.v4LiveOpenIntent(id)!;}
 v4LiveOpenIntent(id:string){return this.db.prepare('SELECT * FROM v4_live_open_intents WHERE id=?').get(id) as Record<string,unknown>|undefined;}
 transitionV4LiveOpenIntent(id:string,state:string,patch:{erc20Hash?:string;permit2Hash?:string;mintHash?:string;tokenId?:string;failureReason?:string;details?:unknown}={}){const at=new Date().toISOString(),run=this.db.transaction(()=>{this.db.prepare('UPDATE v4_live_open_intents SET state=?,erc20_approval_hash=COALESCE(?,erc20_approval_hash),permit2_approval_hash=COALESCE(?,permit2_approval_hash),mint_hash=COALESCE(?,mint_hash),token_id=COALESCE(?,token_id),failure_reason=COALESCE(?,failure_reason),updated_at=? WHERE id=?').run(state,patch.erc20Hash??null,patch.permit2Hash??null,patch.mintHash??null,patch.tokenId??null,patch.failureReason??null,at,id);this.db.prepare('INSERT OR IGNORE INTO v4_live_transitions(intent_id,ordinal,state,details_json,created_at) SELECT ?,COALESCE(MAX(ordinal),-1)+1,?,?,? FROM v4_live_transitions WHERE intent_id=?').run(id,state,JSON.stringify(patch.details??{},(_,v)=>typeof v==='bigint'?v.toString():v),at,id);});run();return this.v4LiveOpenIntent(id)!;}
 terminalizeV4OperationalNonBroadcast(input:{intentId:string;phase:string;hash:string;nonce:number;evidence:unknown}){const at=new Date().toISOString(),state=`${input.phase}_NON_BROADCAST_TERMINAL`;this.db.transaction(()=>{const row=this.v4LiveOpenIntent(input.intentId);if(!row||String(row.failure_reason)!=='V4_BROADCAST_PROVEN_ABSENT_AFTER_IDENTICAL_RESEND'||String(row.permit2_approval_hash).toLowerCase()!==input.hash.toLowerCase())throw new Error('V4_NON_BROADCAST_TERMINALIZATION_CONFLICT');this.db.prepare('UPDATE v4_live_open_intents SET state=?,failure_reason=NULL,updated_at=? WHERE id=?').run(state,at,input.intentId);this.db.prepare('INSERT OR IGNORE INTO v4_live_transitions(intent_id,ordinal,state,details_json,created_at) SELECT ?,COALESCE(MAX(ordinal),-1)+1,?,?,? FROM v4_live_transitions WHERE intent_id=?').run(input.intentId,state,JSON.stringify({phase:input.phase,exactHash:input.hash,nonce:input.nonce,classification:'PROVEN_NON_BROADCAST_SUPERSEDED_BY_SUFFICIENT_ALLOWANCE',evidence:input.evidence}),at,input.intentId);})();return this.v4LiveOpenIntent(input.intentId)!;}
 v4LiveTransitions(intentId:string){return this.db.prepare('SELECT ordinal,state,details_json,created_at FROM v4_live_transitions WHERE intent_id=? ORDER BY ordinal').all(intentId) as Record<string,unknown>[];}
 addV4LiveGasEstimate(input:{txHash:string;intentId:string;phase:string;gas:bigint;eth:bigint;usd:number}){this.db.prepare('INSERT OR IGNORE INTO v4_live_gas(tx_hash,intent_id,phase,estimated_gas,estimated_eth_raw,estimated_usd,created_at) VALUES(?,?,?,?,?,?,?)').run(input.txHash,input.intentId,input.phase,input.gas.toString(),input.eth.toString(),input.usd,new Date().toISOString());}
 confirmV4LiveGas(input:{txHash:string;gas:bigint;eth:bigint;usd:number}){const at=new Date().toISOString(),run=this.db.transaction(()=>{const changed=this.db.prepare('UPDATE v4_live_gas SET actual_gas=?,actual_eth_raw=?,actual_usd=?,confirmed_at=? WHERE tx_hash=? AND actual_gas IS NULL').run(input.gas.toString(),input.eth.toString(),input.usd,at,input.txHash).changes;if(changed)this.db.prepare('UPDATE v4_live_canary SET gas_spent_eth_raw=CAST(CAST(gas_spent_eth_raw AS INTEGER)+? AS TEXT),gas_spent_usd=gas_spent_usd+?,updated_at=? WHERE id=1').run(input.eth.toString(),input.usd,at);return changed;});return run();}
 confirmV4OperationalGas(input:{txHash:string;gas:bigint;eth:bigint;usd:number}){const at=new Date().toISOString();return this.db.prepare('UPDATE v4_live_gas SET actual_gas=?,actual_eth_raw=?,actual_usd=?,confirmed_at=? WHERE tx_hash=? AND actual_gas IS NULL').run(input.gas.toString(),input.eth.toString(),input.usd,at,input.txHash).changes>0;}
 v4OperationalGasSpentUsd(intentId:string){return Number((this.db.prepare('SELECT COALESCE(SUM(actual_usd),0) AS spent FROM v4_live_gas WHERE intent_id=?').get(intentId) as {spent:number}).spent);}
 v4LiveGas(){return this.db.prepare('SELECT * FROM v4_live_gas ORDER BY created_at').all() as Record<string,unknown>[];}
 createV4PoolSelection(input:{userId:string;chatId:string;sessionId:string;poolId:string;poolKey:unknown;discoveryBlock:bigint;liquidity:bigint;targetToken?:string;fundingToken?:string;targetIndex?:0|1;fundingIndex?:0|1;feeSemantics?:unknown;hookStatus?:unknown;refreshBlock?:bigint;valuationSnapshot?:unknown;eligibility?:boolean;blockers?:string[];expiresAtMs?:number;supersedeExisting?:boolean}){const id=randomUUID(),at=new Date().toISOString(),j=(v:unknown)=>JSON.stringify(v,(_,x)=>typeof x==='bigint'?x.toString():x);if(input.supersedeExisting!==false)this.supersedeV4PoolSelections(input.userId,input.chatId,input.sessionId);this.db.prepare('INSERT INTO v4_pool_selections(id,user_id,chat_id,session_id,pool_id,pool_key_json,discovery_block,liquidity_raw,created_at,target_token,funding_token,target_index,funding_index,fee_semantics_json,hook_status_json,refresh_block,valuation_snapshot_json,eligibility,blockers_json,expires_at_ms) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(id,input.userId,input.chatId,input.sessionId,input.poolId,j(input.poolKey),input.discoveryBlock.toString(),input.liquidity.toString(),at,input.targetToken??null,input.fundingToken??null,input.targetIndex??null,input.fundingIndex??null,input.feeSemantics===undefined?null:j(input.feeSemantics),input.hookStatus===undefined?null:j(input.hookStatus),input.refreshBlock?.toString()??null,input.valuationSnapshot===undefined?null:j(input.valuationSnapshot),input.eligibility?1:0,j(input.blockers??(input.eligibility?[]:['LEGACY_INCOMPLETE_SELECTION'])),input.expiresAtMs??null);return this.v4PoolSelection(id)!;}
 supersedeV4PoolSelections(userId:string,chatId:string,sessionId:string){return this.db.prepare('UPDATE v4_pool_selections SET superseded=1 WHERE user_id=? AND chat_id=? AND session_id=? AND superseded=0').run(userId,chatId,sessionId).changes;}
 supersedeOtherV4PoolSelections(userId:string,chatId:string,exceptSessionId:string){return this.db.prepare('UPDATE v4_pool_selections SET superseded=1 WHERE user_id=? AND chat_id=? AND session_id<>? AND superseded=0').run(userId,chatId,exceptSessionId).changes;}
 v4PoolSelection(id:string){return this.db.prepare('SELECT * FROM v4_pool_selections WHERE id=?').get(id) as Record<string,unknown>|undefined;}
 v4PoolSelectionsForSession(userId:string,chatId:string,sessionId:string){return this.db.prepare('SELECT * FROM v4_pool_selections WHERE user_id=? AND chat_id=? AND session_id=? AND superseded=0').all(userId,chatId,sessionId) as Record<string,unknown>[];}
 updateV4PoolSelectionState(id:string,input:{liquidity:bigint;refreshBlock?:bigint;eligibility:boolean;blockers:string[]}){this.db.prepare('UPDATE v4_pool_selections SET liquidity_raw=?,refresh_block=?,eligibility=?,blockers_json=? WHERE id=? AND superseded=0').run(input.liquidity.toString(),input.refreshBlock?.toString()??null,input.eligibility?1:0,JSON.stringify(input.blockers),id);return this.v4PoolSelection(id);}
 upsertV4RegistryPool(input:V4RegistryPoolRecord){const at=new Date().toISOString(),blockers:string[]=[];if(input.dynamicFee)blockers.push('DYNAMIC_FEE_UNSUPPORTED');if(input.hookClassification!=='ZERO_HOOK')blockers.push('NONZERO_HOOK_UNSUPPORTED');this.db.prepare("INSERT INTO v4_pool_registry(pool_id,chain_id,currency0,currency1,initialize_fee_raw,tick_spacing,hooks,initialization_block,initialization_tx_hash,initialization_tx_index,initialization_log_index,first_seen_at,hook_classification,dynamic_fee,static_fee_pips,validation_status,blockers_json,updated_at) VALUES(?,4663,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(pool_id) DO UPDATE SET currency0=excluded.currency0,currency1=excluded.currency1,initialize_fee_raw=excluded.initialize_fee_raw,tick_spacing=excluded.tick_spacing,hooks=excluded.hooks,initialization_block=excluded.initialization_block,initialization_tx_hash=COALESCE(excluded.initialization_tx_hash,v4_pool_registry.initialization_tx_hash),initialization_tx_index=COALESCE(excluded.initialization_tx_index,v4_pool_registry.initialization_tx_index),initialization_log_index=COALESCE(excluded.initialization_log_index,v4_pool_registry.initialization_log_index),hook_classification=excluded.hook_classification,dynamic_fee=excluded.dynamic_fee,static_fee_pips=excluded.static_fee_pips,updated_at=excluded.updated_at").run(input.poolId,input.currency0,input.currency1,input.initializeFeeRaw,input.tickSpacing,input.hooks,input.initializationBlock.toString(),input.initializationTxHash??null,input.initializationTxIndex??null,input.initializationLogIndex??null,at,input.hookClassification,input.dynamicFee?1:0,input.staticFeePips,blockers.length?'BLOCKED':'DISCOVERED',JSON.stringify(blockers),at);return this.v4RegistryPool(input.poolId);}
 v4RegistryPool(poolId:string){return this.db.prepare('SELECT * FROM v4_pool_registry WHERE lower(pool_id)=lower(?)').get(poolId) as Record<string,unknown>|undefined;}
 v4RegistryPoolsForToken(token:string,fundingTokens:string[]){if(!fundingTokens.length)return [];const placeholders=fundingTokens.map(()=>'?').join(','),lower=fundingTokens.map(x=>x.toLowerCase());return this.db.prepare(`SELECT * FROM v4_pool_registry WHERE (lower(currency0)=lower(?) AND lower(currency1) IN (${placeholders})) OR (lower(currency1)=lower(?) AND lower(currency0) IN (${placeholders})) ORDER BY initialization_block,pool_id`).all(token,...lower,token,...lower) as Record<string,unknown>[];}
 tokenMetadata(address:string){return this.db.prepare('SELECT * FROM token_metadata_cache WHERE lower(address)=lower(?)').get(address) as Record<string,unknown>|undefined;}
 v3CachedPoolsForToken(token:string,fundingTokens:string[],now=Date.now()){if(!fundingTokens.length)return [];const p=fundingTokens.map(()=>'?').join(','),lower=fundingTokens.map(x=>x.toLowerCase());return this.db.prepare(`SELECT * FROM v3_pool_state_cache WHERE initialized=1 AND CAST(liquidity_raw AS INTEGER)>0 AND refreshed_at_ms>? AND ((lower(token0_address)=lower(?) AND lower(token1_address) IN (${p})) OR (lower(token1_address)=lower(?) AND lower(token0_address) IN (${p}))) ORDER BY lower(pool_address) ASC`).all(now-120_000,token,...lower,token,...lower) as Record<string,unknown>[];}
 updateV4RegistryTvl(poolId:string,input:{tvlUsd?:number;tvlSource?:string;observedAtMs?:number;freshUntilMs?:number;status:string}){this.db.prepare('UPDATE v4_pool_registry SET tvl_usd=?,tvl_source=?,tvl_observed_at_ms=?,tvl_fresh_until_ms=?,tvl_status=?,updated_at=? WHERE lower(pool_id)=lower(?)').run(input.tvlUsd??null,input.tvlSource??null,input.observedAtMs??null,input.freshUntilMs??null,input.status,new Date().toISOString(),poolId);return this.v4RegistryPool(poolId);}
 upsertTokenMetadata(input:{address:string;symbol:string;name:string;decimals:number;refreshedAtMs?:number}){this.db.prepare('INSERT INTO token_metadata_cache(address,symbol,name,decimals,refreshed_at_ms) VALUES(?,?,?,?,?) ON CONFLICT(address) DO UPDATE SET symbol=excluded.symbol,name=excluded.name,decimals=excluded.decimals,refreshed_at_ms=excluded.refreshed_at_ms').run(input.address,input.symbol,input.name,input.decimals,input.refreshedAtMs??Date.now());}
 enqueueV4StateRefresh(poolId:string,priority:number,reason:string,now=Date.now()){this.db.prepare('INSERT INTO v4_state_refresh_queue(pool_id,priority,reason,requested_at_ms,available_at_ms) VALUES(?,?,?,?,?) ON CONFLICT(pool_id) DO UPDATE SET priority=max(priority,excluded.priority),reason=excluded.reason,requested_at_ms=excluded.requested_at_ms,available_at_ms=min(available_at_ms,excluded.available_at_ms)').run(poolId,priority,reason,now,now);}
 enqueueNewV4Pools(limit=100,now=Date.now()){const rows=this.db.prepare("SELECT pool_id FROM v4_pool_registry WHERE last_refreshed_at IS NULL ORDER BY initialization_block DESC LIMIT ?").all(limit) as Array<{pool_id:string}>;for(const row of rows)this.enqueueV4StateRefresh(row.pool_id,80,'new-pool',now);return rows.length;}
 enqueueV4PoolsDiscoveredBetween(fromBlock:bigint,toBlock:bigint,now=Date.now()){const rows=this.db.prepare('SELECT pool_id FROM v4_pool_registry WHERE CAST(initialization_block AS INTEGER) BETWEEN ? AND ?').all(fromBlock.toString(),toBlock.toString()) as Array<{pool_id:string}>;for(const row of rows)this.enqueueV4StateRefresh(row.pool_id,80,'new-pool',now);return rows.length;}
 enqueueHotV4Pools(limit=20,now=Date.now()){const cutoff=new Date(now-60_000).toISOString(),rows=this.db.prepare("SELECT pool_id FROM v4_pool_registry WHERE (validation_status='ELIGIBLE' OR CAST(active_liquidity_raw AS INTEGER)>0) AND (last_refreshed_at IS NULL OR last_refreshed_at<?) ORDER BY CASE WHEN validation_status='ELIGIBLE' THEN 0 ELSE 1 END,last_refreshed_at LIMIT ?").all(cutoff,limit) as Array<{pool_id:string}>;for(const row of rows)this.enqueueV4StateRefresh(row.pool_id,60,'active-or-eligible',now);return rows.length;}
 leaseV4StateRefresh(limit:number,leaseMs:number,now=Date.now()){const run=this.db.transaction(()=>{const rows=this.db.prepare('SELECT * FROM v4_state_refresh_queue WHERE available_at_ms<=? AND (leased_until_ms IS NULL OR leased_until_ms<?) ORDER BY priority DESC,requested_at_ms LIMIT ?').all(now,now,limit) as Record<string,unknown>[],lease=this.db.prepare('UPDATE v4_state_refresh_queue SET leased_until_ms=? WHERE pool_id=? AND (leased_until_ms IS NULL OR leased_until_ms<?)');return rows.filter(row=>lease.run(now+leaseMs,row.pool_id,now).changes===1);});return run();}
 completeV4StateRefresh(poolId:string){this.db.prepare('DELETE FROM v4_state_refresh_queue WHERE lower(pool_id)=lower(?)').run(poolId);}
 retryV4StateRefresh(poolId:string,error:string,attempts:number,now=Date.now()){const delay=Math.min(300_000,1000*2**Math.min(attempts,8));this.db.prepare('UPDATE v4_state_refresh_queue SET attempts=?,available_at_ms=?,leased_until_ms=NULL,last_error=? WHERE lower(pool_id)=lower(?)').run(attempts,now+delay,error.slice(0,500),poolId);}
 recordLatency(metric:string,durationMs:number,input:{provider?:string;fallbackUsed?:boolean;cacheAgeMs?:number;context?:unknown}={}){this.db.prepare('INSERT INTO latency_telemetry(metric,duration_ms,provider,fallback_used,cache_age_ms,context_json,created_at_ms) VALUES(?,?,?,?,?,?,?)').run(metric,Math.max(0,Math.round(durationMs)),input.provider??null,input.fallbackUsed?1:0,input.cacheAgeMs??null,JSON.stringify(input.context??{}),Date.now());}
 refreshV4RegistryPool(input:{poolId:string;sqrtPriceX96:bigint;tick:number;liquidity:bigint;protocolFee:number;lpFeePips:number;initialized:boolean;refreshBlock:bigint;validationStatus:string;blockers:string[]}){const at=new Date().toISOString();this.db.prepare('UPDATE v4_pool_registry SET sqrt_price_x96=?,current_tick=?,active_liquidity_raw=?,current_protocol_fee=?,current_lp_fee_pips=?,initialized=?,refresh_block=?,last_refreshed_at=?,validation_status=?,blockers_json=?,updated_at=? WHERE lower(pool_id)=lower(?)').run(input.sqrtPriceX96.toString(),input.tick,input.liquidity.toString(),input.protocolFee,input.lpFeePips,input.initialized?1:0,input.refreshBlock.toString(),at,input.validationStatus,JSON.stringify([...new Set(input.blockers)]),at,input.poolId);return this.v4RegistryPool(input.poolId);}
 v4RegistryCursor(){return this.db.prepare('SELECT * FROM v4_pool_discovery_cursor WHERE chain_id=4663').get() as Record<string,unknown>|undefined;}
 initializeV4RegistryCursor(input:{nextBlock:bigint;overlapBlocks:number;windowSize:number}){const at=new Date().toISOString();this.db.prepare('INSERT OR IGNORE INTO v4_pool_discovery_cursor(chain_id,next_block,overlap_blocks,window_size,updated_at) VALUES(4663,?,?,?,?)').run(input.nextBlock.toString(),input.overlapBlocks,input.windowSize,at);return this.v4RegistryCursor()!;}
 configureV4RegistryCursor(input:{windowSize?:number;overlapBlocks?:number}){const current=this.v4RegistryCursor();if(!current)throw new Error('V4_REGISTRY_CURSOR_NOT_INITIALIZED');const window=input.windowSize??Number(current.window_size),overlap=input.overlapBlocks??Number(current.overlap_blocks);if(!Number.isSafeInteger(window)||window<1||window>1_000_000||!Number.isSafeInteger(overlap)||overlap<0||overlap>=window)throw new Error('V4_REGISTRY_WINDOW_CONFIGURATION_INVALID');this.db.prepare('UPDATE v4_pool_discovery_cursor SET window_size=?,overlap_blocks=?,updated_at=? WHERE chain_id=4663').run(window,overlap,new Date().toISOString());return this.v4RegistryCursor()!;}
 startV4RegistrySync(chainBlock:bigint){const at=new Date().toISOString();this.db.prepare('UPDATE v4_pool_discovery_cursor SET last_chain_block=?,last_sync_started_at=?,last_error=NULL,updated_at=? WHERE chain_id=4663').run(chainBlock.toString(),at,at);}
 advanceV4RegistryCursor(nextBlock:bigint){this.db.prepare('UPDATE v4_pool_discovery_cursor SET next_block=?,updated_at=? WHERE chain_id=4663').run(nextBlock.toString(),new Date().toISOString());}
 finishV4RegistrySync(input:{durationMs:number;error?:string;fallbackUses?:number}){const at=new Date().toISOString();this.db.prepare('UPDATE v4_pool_discovery_cursor SET last_sync_completed_at=?,last_sync_duration_ms=?,last_error=?,fallback_uses=fallback_uses+?,updated_at=? WHERE chain_id=4663').run(at,input.durationMs,input.error??null,input.fallbackUses??0,at);}
 v4RegistryStatus(){const cursor=this.v4RegistryCursor(),counts=this.db.prepare("SELECT COUNT(*) total,SUM(CASE WHEN initialized=1 AND CAST(active_liquidity_raw AS INTEGER)>0 THEN 1 ELSE 0 END) active,SUM(CASE WHEN hook_classification!='ZERO_HOOK' THEN 1 ELSE 0 END) hooked,SUM(dynamic_fee) dynamic,SUM(CASE WHEN validation_status='ELIGIBLE' THEN 1 ELSE 0 END) eligible FROM v4_pool_registry").get() as Record<string,unknown>;return {cursor,counts};}
}
