// Public fixture only. It contains documented names and intentionally inert values.
module.exports={apps:[{
 name:'robinhood-lp-telegram',
 script:'infra/pm2/start-telegram.sh',
 env:{
  NODE_ENV:'production',DATA_DIR:'',DATABASE_PATH:'',RH_CHAIN_ID:'',RH_RPC_URL:'',RH_RPC_FALLBACK_URL:'',ALCHEMY_RPC_URL:'',ALCHEMY_RPC_URLS:'',RH_LOGS_RPC_URL:'',
  ROBIN_TELEGRAM_BOT_TOKEN:'',ROBIN_TELEGRAM_CHAT_ID:'',
  EXECUTION_ENABLED:'false',DRY_RUN:'true',EMERGENCY_PAUSE:'true',LIVE_CANARY_ENABLED:'false',V4_LIVE_CANARY_ENABLED:'false',
  MAX_POSITION_VALUE_USD:'',MAX_APPROVAL_VALUE_USD:'',MAX_REBALANCE_COMPOUND_VALUE_USD:'',MAX_REBALANCE_APPROVAL_VALUE_USD:'',MAX_BOT_MANAGED_EXPOSURE_USD:'',MAX_GAS_COST_USD:'',MAX_LIFECYCLE_GAS_USD:'',V4_CANARY_MAX_TX_GAS_USD:'',V4_CANARY_TOTAL_GAS_BUDGET_USD:''
 },filter_env:['NOVA_','BIRDEYE_API_KEY','HELIUS_API_KEY','HELIUS_FALLBACK_API_KEY','GMGN_API_KEY','JUPITER_API_KEY']
}]};
