import { setTimeout as sleep } from 'node:timers/promises';
import { adaptiveLogRead, chainAssetKey, inspectErc20, inspectV3Pool, loadChainRuntimeConfig, protocolDeployment, sanitizeSensitiveText, v3PoolCreatedEvent, type FallbackRpc, type ProtocolKey } from '@funi/core';
import { migrateSqlite, productionDatabasePaths, SqliteLedgerRepository } from '@funi/ledger';
import { inspectV3FamilyPosition } from '@funi/v3';
import { assertRuntimeProviderIdentity, createChainRuntimeContext, verifyDeploymentReadOnly, type ChainRuntimeContext } from '../../cli/src/multichain-runtime.js';

export type ReadOnlyChainKey='bsc'|'ethereum';
export type ReadOnlyWorkerRole='registry'|'state-cache';
export type ReadOnlyWorkerResult={chain:ReadOnlyChainKey;chainId:number;role:ReadOnlyWorkerRole;status:'DISABLED'|'CONFIGURATION_BLOCKED'|'IDLE'|'COMPLETED'|'BLOCKED';blockerReason?:string;protocols?:unknown[];poolsRefreshed?:number;positionsRefreshed?:number;mainnetTransactionsSent:0;signerConstructed:false;nonceReserved:false;actionableCallbacksCreated:false};

const workerProtocols:Readonly<Record<ReadOnlyChainKey,readonly ProtocolKey[]>>={bsc:['pancakeswap_v3'],ethereum:['uniswap_v3']};
const boundedInteger=(value:string|undefined,fallback:number,min:number,max:number)=>{const parsed=Number(value??fallback);return Number.isSafeInteger(parsed)&&parsed>=min&&parsed<=max?parsed:fallback;};
const blockerCode=(value:unknown)=>{const sanitized=sanitizeSensitiveText(value instanceof Error?value.message:String(value)),match=sanitized.match(/[A-Z][A-Z0-9_.:-]{2,199}/);return match?.[0]??'READ_ONLY_WORKER_BLOCKED';};
const baseResult=(chain:ReadOnlyChainKey,role:ReadOnlyWorkerRole):Omit<ReadOnlyWorkerResult,'status'>=>({chain,chainId:chain==='bsc'?56:1,role,mainnetTransactionsSent:0,signerConstructed:false,nonceReserved:false,actionableCallbacksCreated:false});

function persistWorkerBlocker(repo:SqliteLedgerRepository,context:{chainId:number;protocols:readonly ProtocolKey[];confirmations:number},role:ReadOnlyWorkerRole,reason:string){for(const protocol of context.protocols)repo.upsertChainRegistryCursor({chainId:context.chainId,protocol,cursorKind:role==='registry'?'deployment_verification':'state_cache',nextBlock:repo.chainRegistryCursor(context.chainId,protocol,role==='registry'?'deployment_verification':'state_cache')?.next_block as string|undefined??'0',finalityConfirmations:context.confirmations,state:{status:'BLOCKED',blockerCode:reason,stale:true}});}

async function registryCycle(context:ChainRuntimeContext,limits:{chunkSize:bigint;maxRequests:number;maxSplits:number;maxElapsedMs:number}):Promise<Pick<ReadOnlyWorkerResult,'protocols'|'poolsRefreshed'>>{
 await assertRuntimeProviderIdentity(context);const results:unknown[]=[],protocols=workerProtocols[context.profile.key as ReadOnlyChainKey],repo=context.repository;let poolsRefreshed=0;
 for(const protocol of protocols){const result=await verifyDeploymentReadOnly(context,protocol),verified=result.providers.find(item=>item.status==='VERIFIED') as Record<string,unknown>|undefined,reason=blockerCode(result.blockerReason??(result.providers.find(item=>item.status==='UNVERIFIED') as Record<string,unknown>|undefined)?.reason??'DEPLOYMENT_RUNTIME_NOT_VERIFIED');if(!verified)throw new Error(reason);
  const known=verified?.knownPool as Record<string,unknown>|undefined;if(known){repo.upsertChainPool({chainId:context.profile.chainId,protocol,poolAddress:String(known.pool),token0:String(known.token0),token1:String(known.token1),fee:Number(known.fee),tickSpacing:Number(known.tickSpacing),state:{sqrtPriceX96:known.sqrtPriceX96,tick:known.tick,liquidity:known.liquidity,verifiedBlock:verified?.verifiedBlock,verificationStatus:'VERIFIED_READ_ONLY',executionReadinessElevated:false},validationStatus:'VERIFIED_READ_ONLY'});poolsRefreshed++;}
  if(context.profile.key==='bsc'){const deployment=protocolDeployment(context.profile.chainId,protocol),factory=deployment.contracts.factory;if(!factory)throw new Error('DEPLOYMENT_FACTORY_MISSING');const latest=await context.rpc.withClient(client=>client.getBlockNumber(),{stage:'registry_finality_head',method:'eth_blockNumber',requiredCapabilities:['block_read']}),finalized=latest>BigInt(context.confirmationPolicy.receiptConfirmations)?latest-BigInt(context.confirmationPolicy.receiptConfirmations):0n,cursor=repo.chainRegistryCursor(context.profile.chainId,protocol,'deployment_verification'),from=BigInt(String(cursor?.next_block??'0'));
   if(from<=finalized){const to=from+limits.chunkSize-1n<finalized?from+limits.chunkSize-1n:finalized,read=await adaptiveLogRead<any>({rpc:context.rpc,address:factory,event:v3PoolCreatedEvent,fromBlock:from,toBlock:to,options:{chunkSize:limits.chunkSize,maxRequests:limits.maxRequests,maxRecursiveSplits:limits.maxSplits,maxElapsedMs:limits.maxElapsedMs}});if(read.status==='blocked')throw new Error(`BSC_LOG_DISCOVERY_PROVIDER_UNAVAILABLE:${read.failureCategory}`);const inspected=[];for(const log of read.logs){const args=log.args as Record<string,unknown>,poolAddress=String(args.pool??'');if(!/^0x[0-9a-f]{40}$/i.test(poolAddress))throw new Error('REGISTRY_POOL_CREATED_LOG_MALFORMED');const pool=await inspectV3Pool(context.rpc,poolAddress as `0x${string}`);if(pool.status==='unavailable'||pool.value.factory.toLowerCase()!==factory.toLowerCase())throw new Error('REGISTRY_DISCOVERED_POOL_VERIFICATION_FAILED');inspected.push(pool.value);}for(const pool of inspected){repo.upsertChainPool({chainId:context.profile.chainId,protocol,poolAddress:pool.address,token0:pool.token0,token1:pool.token1,fee:pool.fee,tickSpacing:pool.tickSpacing,state:{sqrtPriceX96:pool.sqrtPriceX96,tick:pool.tick,liquidity:pool.liquidity,verifiedBlock:pool.blockNumber,verificationStatus:'VERIFIED_READ_ONLY_LOG_DISCOVERY',executionReadinessElevated:false},validationStatus:'VERIFIED_READ_ONLY'});poolsRefreshed++;}repo.upsertChainRegistryCursor({chainId:context.profile.chainId,protocol,cursorKind:'deployment_verification',nextBlock:to+1n,finalityConfirmations:context.confirmationPolicy.receiptConfirmations,state:{chain:context.profile.key,protocol,registryVersion:result.registryVersion,verificationStatus:result.status,registryDiscovery:true,lastCompletedFromBlock:from,lastCompletedToBlock:to,minimumSuccessfulLogWindow:read.minimumSuccessfulLogWindow,providerCapabilities:context.rpc.capabilitySnapshot(),executionReadinessElevated:false}});}}
  else repo.upsertChainRegistryCursor({chainId:context.profile.chainId,protocol,cursorKind:'deployment_verification',nextBlock:String(verified.verifiedBlock),finalityConfirmations:context.confirmationPolicy.receiptConfirmations,state:{chain:context.profile.key,protocol,registryVersion:result.registryVersion,verificationStatus:result.status,verifiedBlock:verified.verifiedBlock,verifiedAt:verified.verifiedAt,codeHashes:verified.codeHashes}});
  results.push({protocol,status:result.status,blockerReason:result.status==='VERIFIED'?undefined:reason});
 }
 return {protocols:results,poolsRefreshed};
}

async function refreshPool(context:ChainRuntimeContext,protocol:ProtocolKey,row:Record<string,unknown>,nowMs:number){const repo=context.repository,address=String(row.pool_address),deployment=protocolDeployment(context.profile.chainId,protocol);try{const inspected=await inspectV3Pool(context.rpc,address as `0x${string}`);if(inspected.status==='unavailable')throw new Error(inspected.reason);const pool=inspected.value;if(pool.factory.toLowerCase()!==deployment.contracts.factory?.toLowerCase())throw new Error('STATE_CACHE_POOL_FACTORY_MISMATCH');const tokenResults=await Promise.all([pool.token0,pool.token1].map(token=>inspectErc20(context.rpc,token))),metadataBlockers:string[]=[];for(const [index,result] of tokenResults.entries()){if(result.status==='unavailable'){metadataBlockers.push(`TOKEN_${index}_METADATA_UNAVAILABLE`);continue;}context.tokenMetadataCache.set(chainAssetKey(context.profile.chainId,result.value.address),result.value);repo.upsertChainToken({chainId:context.profile.chainId,address:result.value.address,symbol:result.value.symbol,decimals:result.value.decimals,metadata:{name:result.value.name,provenance:result.provenance,executionReadinessElevated:false},refreshedAtMs:nowMs});}
  const priceBlocker='PRICE_EVIDENCE_MISSING';repo.upsertChainPool({chainId:context.profile.chainId,protocol,poolAddress:pool.address,token0:pool.token0,token1:pool.token1,fee:pool.fee,tickSpacing:pool.tickSpacing,state:{sqrtPriceX96:pool.sqrtPriceX96,tick:pool.tick,liquidity:pool.liquidity,initialized:pool.initialized,verifiedBlock:pool.blockNumber,observedAt:inspected.provenance.observedAt,priceEvidence:{status:'UNAVAILABLE',blockerCode:priceBlocker},metadataBlockers,executionReadinessElevated:false},validationStatus:'VERIFIED_READ_ONLY',blockerReason:priceBlocker,updatedAtMs:nowMs});context.poolRegistryCache.set(`${context.profile.chainId}:${protocol}:${pool.address.toLowerCase()}`,pool);return true;
 }catch(error){repo.markChainPoolStale(context.profile.chainId,protocol,address,blockerCode(error),nowMs);return false;}}

async function refreshPosition(context:ChainRuntimeContext,protocol:ProtocolKey,row:Record<string,unknown>){const repo=context.repository,identifier=String(row.position_identifier);try{const inspected=await inspectV3FamilyPosition({rpc:context.rpc,chainId:context.profile.chainId,protocol:protocol as 'uniswap_v3'|'pancakeswap_v3',tokenId:BigInt(identifier)});if(inspected.status==='unavailable')throw new Error(inspected.reason);const position=inspected.value;repo.upsertChainPosition({chainId:context.profile.chainId,protocol,positionIdentifier:identifier,legacyPositionId:row.legacy_position_id===null?undefined:String(row.legacy_position_id),owner:position.owner,provenance:row.provenance==='BOT_OPERATIONAL'?'BOT_OPERATIONAL':'MANUAL_EXTERNAL',lifecycleState:String(row.lifecycle_state),payload:{evidenceStatus:'VERIFIED_READ_ONLY',observedBlock:position.pool.blockNumber,token0:position.token0,token1:position.token1,fee:position.fee,tickLower:position.tickLower,tickUpper:position.tickUpper,liquidity:position.liquidity,tokensOwed0:position.tokensOwed0,tokensOwed1:position.tokensOwed1,valuationStatus:'UNAVAILABLE',blockerReason:'PRICE_EVIDENCE_MISSING',readOnly:true,executionReadinessElevated:false}});return true;
 }catch(error){repo.recordChainPositionBlocker(context.profile.chainId,protocol,identifier,blockerCode(error));return false;}}

async function stateCacheCycle(context:ChainRuntimeContext,batchLimit:number,nowMs:number):Promise<Pick<ReadOnlyWorkerResult,'poolsRefreshed'|'positionsRefreshed'>>{
 await assertRuntimeProviderIdentity(context);const repo=context.repository,protocols=workerProtocols[context.profile.key as ReadOnlyChainKey];let poolsRefreshed=0,positionsRefreshed=0;for(const protocol of protocols){const pools=repo.db.prepare('SELECT * FROM chain_pools WHERE chain_id=? AND protocol=? ORDER BY updated_at_ms LIMIT ?').all(context.profile.chainId,protocol,batchLimit) as Record<string,unknown>[];for(const pool of pools)if(await refreshPool(context,protocol,pool,nowMs))poolsRefreshed++;const positions=repo.chainPositions(context.profile.chainId,protocol).slice(0,batchLimit);for(const position of positions)if(await refreshPosition(context,protocol,position))positionsRefreshed++;const block=await context.rpc.withClient(client=>client.getBlockNumber(),{stage:'multichain_state_cache',method:'eth_blockNumber'});repo.upsertChainRegistryCursor({chainId:context.profile.chainId,protocol,cursorKind:'state_cache',nextBlock:block+1n,finalityConfirmations:context.confirmationPolicy.receiptConfirmations,state:{status:'COMPLETED',verifiedBlock:block,poolsRefreshed,positionsRefreshed,priceEvidenceStatus:'UNAVAILABLE',priceBlockerCode:'PRICE_EVIDENCE_MISSING',executionReadinessElevated:false}});}return {poolsRefreshed,positionsRefreshed};
}

export async function runReadOnlyWorkerOnce(input:{chain:ReadOnlyChainKey;role:ReadOnlyWorkerRole;env?:NodeJS.ProcessEnv;databasePath:string;migrationsDir?:string;rpc?:FallbackRpc;maxRetries?:number;batchLimit?:number;nowMs?:number}):Promise<ReadOnlyWorkerResult>{
 const env=input.env??process.env,config=loadChainRuntimeConfig(input.chain,env),base=baseResult(input.chain,input.role);if(!config.enabled)return {...base,status:'DISABLED',blockerReason:config.blockerReason??'CHAIN_DISABLED'};
 migrateSqlite(input.databasePath,input.migrationsDir??'infra/migrations');if(!config.available){const reason=blockerCode(config.blockerReason??'CHAIN_CONFIGURATION_UNAVAILABLE'),repo=new SqliteLedgerRepository(input.databasePath);try{persistWorkerBlocker(repo,{chainId:config.profile.chainId,protocols:workerProtocols[input.chain],confirmations:config.confirmations},input.role,reason);}finally{repo.close();}return {...base,status:'CONFIGURATION_BLOCKED',blockerReason:reason};}
 const context=createChainRuntimeContext({key:input.chain,databasePath:input.databasePath,env,rpc:input.rpc}),maxRetries=input.maxRetries??3,registryLimits={chunkSize:BigInt(boundedInteger(env.BSC_REGISTRY_LOG_CHUNK_SIZE,2_000,1,50_000)),maxRequests:boundedInteger(env.BSC_REGISTRY_LOG_MAX_REQUESTS,64,1,256),maxSplits:boundedInteger(env.BSC_REGISTRY_LOG_MAX_SPLITS,16,0,32),maxElapsedMs:boundedInteger(env.BSC_REGISTRY_LOG_MAX_ELAPSED_MS,10_000,100,60_000)};try{let last:unknown;for(let attempt=0;attempt<maxRetries;attempt++)try{const cycle=input.role==='registry'?await registryCycle(context,registryLimits):await stateCacheCycle(context,input.batchLimit??16,input.nowMs??Date.now());return {...base,status:'COMPLETED',...cycle};}catch(error){last=error;const message=error instanceof Error?error.message:'';if(/^BSC_LOG_DISCOVERY_PROVIDER_UNAVAILABLE/.test(message))return {...base,status:'IDLE',blockerReason:'BSC_LOG_DISCOVERY_PROVIDER_UNAVAILABLE'};if(/^WRONG_CHAIN_PROVIDER/.test(message))break;if(attempt+1<maxRetries)await sleep(Math.min(2_000,100*2**attempt));}const reason=blockerCode(last);persistWorkerBlocker(context.repository,{chainId:context.profile.chainId,protocols:workerProtocols[input.chain],confirmations:context.config.confirmations},input.role,reason);return {...base,status:'BLOCKED',blockerReason:reason};}finally{context.close();}
}

export async function runReadOnlyWorkerProcess(chain:ReadOnlyChainKey,role:ReadOnlyWorkerRole){const paths=productionDatabasePaths({dataDir:process.env.DATA_DIR,databasePath:process.env.DATABASE_PATH}),cadenceMs=boundedInteger(process.env.MULTICHAIN_READ_ONLY_CADENCE_MS,60_000,30_000,3_600_000),controller=new AbortController(),stop=()=>controller.abort();process.once('SIGTERM',stop);process.once('SIGINT',stop);try{while(!controller.signal.aborted){const result=await runReadOnlyWorkerOnce({chain,role,databasePath:paths.databasePath});process.stdout.write(JSON.stringify({...result,at:new Date().toISOString()})+'\n');try{await sleep(cadenceMs,undefined,{signal:controller.signal});}catch(error){if(!controller.signal.aborted)throw error;}}}finally{process.off('SIGTERM',stop);process.off('SIGINT',stop);}}
