import 'dotenv/config';
import { setTimeout as sleep } from 'node:timers/promises';
import { FallbackRpc, orderedRpcUrls, robinhoodMainnet } from '@funi/core';
import { migrateSqlite, productionDatabasePaths, SQLITE_RUNTIME_BUSY_TIMEOUT_MS, SqliteLedgerRepository } from '@funi/ledger';
import { assertFuniCredentialIsolation } from '../../shared/credential-isolation.js';
import { resolveCanonicalFuniWallet } from '../../shared/funi-wallet.js';
import { ACTIVE_OPEN_POSITION_REFRESH_DUE, acquireRpcReadLease, completeTargetedPositionReconciliation, enqueueTargetedPositionReconciliation, freshnessSafetyHeadroomMs, leaseTargetedPositionReconciliations, reconcileActivePositions, releaseRpcReadLease, retryTargetedPositionReconciliation } from '../../cli/src/active-position-reconciliation.js';
import { fetchV4RegistryPoolBatch, persistV4RegistryPoolBatch, planV4RegistryPoolBatch } from '../../cli/src/v4-registry.js';
import { acquireStatePersistenceLease, convergeOpenPendingV4BidLadder, fullyActionableV4BidLadder, leaseUrgentStateRefresh, releaseStatePersistenceLease, runnableUrgentWork, URGENT_TARGETED_POSITION_REASONS } from './state-cache-scheduling.js';

assertFuniCredentialIsolation(process.env);
delete process.env.LP_PRIVATE_KEY;delete process.env.LP_MNEMONIC;delete process.env.SEED_PHRASE;delete process.env.MNEMONIC;
process.env.EXECUTION_ENABLED='false';process.env.DRY_RUN='true';process.env.EMERGENCY_PAUSE='true';process.env.LIVE_CANARY_ENABLED='false';process.env.V4_LIVE_CANARY_ENABLED='false';
if(!process.env.ALCHEMY_RPC_URLS&&!process.env.ALCHEMY_RPC_URL)throw new Error('ALCHEMY_RPC_URL_REQUIRED');

const integer=(name:string,fallback:number,min:number,max:number)=>{const value=Number(process.env[name]??fallback);return Number.isSafeInteger(value)&&value>=min&&value<=max?value:fallback;};
const paths=productionDatabasePaths({dataDir:process.env.DATA_DIR,databasePath:process.env.DATABASE_PATH}),urls=orderedRpcUrls(process.env.ALCHEMY_RPC_URLS,process.env.ALCHEMY_RPC_URL),rpc=new FallbackRpc({...robinhoodMainnet,rpcUrls:urls},urls,{timeoutMs:integer('URGENT_STATE_RPC_TIMEOUT_MS',2_000,250,15_000)});
let wallet:ReturnType<typeof resolveCanonicalFuniWallet>;
try{wallet=resolveCanonicalFuniWallet({WALLET_ADDRESS:process.env.WALLET_ADDRESS,OPERATOR_WALLET:process.env.OPERATOR_WALLET,DEDICATED_WALLET_ADDRESS:process.env.DEDICATED_WALLET_ADDRESS});}catch(error){process.stderr.write(JSON.stringify({event:'fatal_config_error',process:'funi-v4-state-cache-urgent',code:'FUNI_CANONICAL_WALLET_MISMATCH',error:error instanceof Error?error.message:String(error),ownershipMutationDisabled:true,mainnetTransactionsSent:0,at:new Date().toISOString()})+'\n');throw error;}
const idleMs=integer('URGENT_STATE_IDLE_MS',250,100,2_000),nftBatch=integer('URGENT_NFT_BATCH_LIMIT',8,1,16),poolBatch=integer('URGENT_POOL_BATCH_LIMIT',4,1,8),evidenceTtlMs=integer('ACTIVE_POSITION_RECONCILIATION_TTL_MS',300_000,60_000,3_600_000),poolTtlMs=integer('STATE_CACHE_ACTIVE_POOL_TTL_MS',120_000,60_000,3_600_000);
migrateSqlite(paths.databasePath,'infra/migrations',{busyTimeoutMs:SQLITE_RUNTIME_BUSY_TIMEOUT_MS});
const open=()=>new SqliteLedgerRepository(paths.databasePath,{busyTimeoutMs:SQLITE_RUNTIME_BUSY_TIMEOUT_MS}),emit=(event:string,data:Record<string,unknown>={})=>{try{process.stdout.write(JSON.stringify({event,process:'funi-v4-state-cache-urgent',...data,at:new Date().toISOString()},(_,value)=>typeof value==='bigint'?value.toString():value)+'\n');}catch{}};
let stopping=false,cursor:0|1=0;process.on('SIGTERM',()=>{stopping=true;});process.on('SIGINT',()=>{stopping=true;});

function seedActiveOpenMaintenance(){const db=open(),now=Date.now();try{const positions=db.db.prepare("SELECT DISTINCT 'v4:'||x.token_id position_id,x.token_id,a.checked_at_ms,a.fresh_until_ms FROM v4_bid_ladders l JOIN v4_bid_ladder_legs x ON x.ladder_id=l.ladder_id JOIN active_position_reconciliations a ON a.position_id='v4:'||x.token_id WHERE l.execution_mode='LIVE' AND l.status='OPEN' AND x.status='OPEN' AND x.token_id IS NOT NULL AND a.owner_status='VERIFIED_OWNED' AND a.confirmed_active=1 AND a.terminal_reason IS NULL").all() as Array<{position_id:string;token_id:string;checked_at_ms:number;fresh_until_ms:number}>,pools=db.db.prepare("SELECT DISTINCT l.pool_id,r.last_refreshed_at FROM v4_bid_ladders l LEFT JOIN v4_pool_registry r ON lower(r.pool_id)=lower(l.pool_id) WHERE l.execution_mode='LIVE' AND l.status='OPEN'").all() as Array<{pool_id:string;last_refreshed_at:string|null}>;db.db.transaction(()=>{for(const row of positions){const ttl=Math.max(1,row.fresh_until_ms-row.checked_at_ms),due=row.fresh_until_ms-freshnessSafetyHeadroomMs(ttl);enqueueTargetedPositionReconciliation(db,{positionId:row.position_id,tokenId:row.token_id,protocol:'v4',reason:ACTIVE_OPEN_POSITION_REFRESH_DUE,priority:500,nowMs:row.checked_at_ms,availableAtMs:Math.max(now,due)});}for(const row of pools){const observed=row.last_refreshed_at?Date.parse(row.last_refreshed_at):now,due=observed+poolTtlMs-freshnessSafetyHeadroomMs(poolTtlMs);db.enqueueV4StateRefresh(row.pool_id,400,'ACTIVE_OPEN_POOL_REFRESH_DUE',observed,Math.max(now,due));}})();emit('active_open_maintenance_seeded',{positionCount:positions.length,poolCount:pools.length,mainnetTransactionsSent:0});}finally{db.close();}}

async function busy<T>(operation:string,work:()=>T|Promise<T>){let last:unknown;for(let attempt=0;attempt<4;attempt++){try{return await work();}catch(error){last=error;if(!/SQLITE_BUSY|database is locked/i.test(error instanceof Error?error.message:String(error)))throw error;const waitMs=25*2**attempt;emit('sqlite_busy_retry',{operation,attempt:attempt+1,waitMs,mainnetTransactionsSent:0});await sleep(waitMs);}}throw last;}
const persistenceLease=(ownerId:string,waitMs=5_000)=>({acquire:async()=>{const deadline=Date.now()+waitMs;do{const acquired=await busy('state_persistence_lease_acquire',()=>{const db=open();try{return acquireStatePersistenceLease(db.db,ownerId,10_000);}finally{db.close();}});if(acquired)return true;await sleep(25);}while(Date.now()<deadline);return false;},release:async()=>{await busy('state_persistence_lease_release',()=>{const db=open();try{return releaseStatePersistenceLease(db.db,ownerId);}finally{db.close();}});}});

function fullyActionableLadders(repo:SqliteLedgerRepository,ladderIds:string[],nowMs:number){return [...new Set(ladderIds)].filter(ladderId=>fullyActionableV4BidLadder(repo.db,ladderId,nowMs,poolTtlMs));}
function ladderIdsForPositions(repo:SqliteLedgerRepository,rows:Record<string,unknown>[]){return rows.flatMap(row=>{const position=repo.v4Position(String(row.token_id));return position?.open_intent_id?[String(position.open_intent_id)]:[];});}
function ladderIdsForPools(repo:SqliteLedgerRepository,poolIds:string[]){return poolIds.flatMap(pool=>(repo.db.prepare('SELECT ladder_id FROM v4_bid_ladders WHERE lower(pool_id)=lower(?)').all(pool) as Array<{ladder_id:string}>).map(row=>row.ladder_id));}
function convergeOpenPendingLadders(repo:SqliteLedgerRepository,ladderIds:string[],nowMs:number){return [...new Set(ladderIds)].filter(ladderId=>convergeOpenPendingV4BidLadder(repo,ladderId,nowMs,poolTtlMs));}

async function retryTargetedBatch(rows:Record<string,unknown>[],ownerId:string,error:string){const lease=persistenceLease(`${ownerId}:retry`,12_000);if(!(await lease.acquire()))return false;const db=open();try{db.db.transaction(()=>{for(const row of rows)retryTargetedPositionReconciliation(db,String(row.position_id),error,Date.now(),ownerId);})();return true;}finally{db.close();await lease.release();}}

async function serviceTargeted(){
 const leaseAtMs=Date.now(),ownerId=`urgent-nft:${leaseAtMs}`,rows=await busy('urgent_targeted_lease',()=>{const db=open();try{return leaseTargetedPositionReconciliations(db,nftBatch,15_000,leaseAtMs,{ownerId,lane:'urgent',reasons:URGENT_TARGETED_POSITION_REASONS});}finally{db.close();}});if(!rows.length)return false;
 const serviceStartedAtMs=Date.now(),db=open();let resetConvergedToWatching:string[]=[];const rpcLease={acquire:()=>{const leaseDb=open();try{return acquireRpcReadLease(leaseDb,ownerId,15_000,Date.now(),'urgent');}finally{leaseDb.close();}},release:()=>{const leaseDb=open();try{releaseRpcReadLease(leaseDb,ownerId,Date.now(),'urgent');}finally{leaseDb.close();}}};
 try{
  const ids=rows.map(row=>String(row.position_id)),result=await reconcileActivePositions({repo:db,rpc,wallet:wallet!,positionIds:ids,limit:ids.length,ttlMs:evidenceTtlMs,interactionId:ownerId,rpcLease,persistenceLease:persistenceLease(ownerId),refreshPortfolioSnapshot:false,onPersisted:(repo,positions)=>{const persistedAtMs=Date.now(),byId=new Map(positions.map(position=>[position.positionId,position]));for(const row of rows){const id=String(row.position_id),position=byId.get(id);if(position&&!position.error)completeTargetedPositionReconciliation(repo,id,persistedAtMs,ownerId);else retryTargetedPositionReconciliation(repo,id,position?.error??'TARGETED_RECONCILIATION_INCOMPLETE',persistedAtMs,ownerId);}resetConvergedToWatching=convergeOpenPendingLadders(repo,ladderIdsForPositions(repo,rows),persistedAtMs);}});
  if(result.rpcLeaseDeferred){await retryTargetedBatch(rows,ownerId,'URGENT_RPC_BUDGET_BUSY');return true;}
  const serviceEndedAtMs=Date.now(),ladders=ladderIdsForPositions(db,rows),actionable=fullyActionableLadders(db,ladders,serviceEndedAtMs),byId=new Map(result.positions.map(position=>[position.positionId,position]));
  for(const row of rows){const id=String(row.position_id),leaseAt=Number(row.leased_at_ms),maintenance=String(row.reason)===ACTIVE_OPEN_POSITION_REFRESH_DUE,freshUntilAtMs=maintenance?Number(row.requested_at_ms)+evidenceTtlMs:null,next=db.db.prepare("SELECT available_at_ms FROM targeted_position_reconciliation_requests WHERE position_id=? AND reason=?").get(id,ACTIVE_OPEN_POSITION_REFRESH_DUE) as {available_at_ms:number}|undefined,context={requestId:`${id}:${String(row.requested_at_ms)}`,positionId:id,tokenId:String(row.token_id),reason:String(row.reason),priority:Number(row.priority),enqueueAtMs:Number(row.requested_at_ms),nextDueAtMs:next?.available_at_ms??null,leaseAtMs:leaseAt,freshUntilAtMs,headroomMs:freshUntilAtMs===null?null:freshUntilAtMs-serviceStartedAtMs,refreshGapMs:maintenance?serviceEndedAtMs-Number(row.requested_at_ms):null,missedDeadlineCount:freshUntilAtMs!==null&&serviceStartedAtMs>=freshUntilAtMs?1:0,leaseOwner:ownerId,serviceStartedAtMs,serviceEndedAtMs,queueWaitMs:Math.max(0,leaseAt-Number(row.requested_at_ms)),rpcMs:result.totalRpcDurationMs,persistenceMs:result.totalPersistenceDurationMs,completionReason:byId.get(id)&&!byId.get(id)!.error?'RPC_REFRESHED':'RETRYABLE_FAILURE'};try{db.recordLatency('targeted_nft_request_lifecycle',serviceEndedAtMs-Number(row.requested_at_ms),{context});}catch{}emit('targeted_nft_request_lifecycle',context);}
  emit('rpc_cycle_telemetry',{interaction:'targeted-position-reconciliation',interactionId:ownerId,enqueueToLeaseMaxMs:Math.max(...rows.map(row=>Number(row.leased_at_ms)-Number(row.requested_at_ms))),rpcDurationMs:result.totalRpcDurationMs,persistenceDurationMs:result.totalPersistenceDurationMs,serviceStartedAtMs,serviceEndedAtMs,openToNftVerifiedMs:Math.max(...rows.map(row=>serviceEndedAtMs-Number(row.requested_at_ms))),fullyActionableLadders:actionable,resetConvergedToWatching,jobsLeased:rows.length,jobsCompleted:result.positions.filter(position=>!position.error).length,ethCallCount:result.ethCallCount,multicallCount:result.multicallCount,multicallMembers:result.multicallMembers,mainnetTransactionsSent:0});return true;
 }catch(error){const code=(error instanceof Error?error.message:String(error)).slice(0,160);await retryTargetedBatch(rows,ownerId,code||'URGENT_TARGETED_SERVICE_FAILED');emit('urgent_service_retryable',{lane:'targeted',ownerId,error:code,mainnetTransactionsSent:0});return true;}finally{db.close();}
}

async function retryPoolBatch(rows:Record<string,unknown>[],ownerId:string,error:string){const lease=persistenceLease(`${ownerId}:retry`,12_000);if(!(await lease.acquire()))return false;const db=open();try{db.db.transaction(()=>{for(const row of rows)db.retryV4StateRefresh(String(row.pool_id),error,Number(row.attempts)+1,Date.now(),ownerId);})();return true;}finally{db.close();await lease.release();}}

async function servicePools(){
 const leaseAtMs=Date.now(),ownerId=`urgent-pool:${leaseAtMs}`,rows=await busy('urgent_pool_lease',()=>{const db=open();try{return leaseUrgentStateRefresh(db.db,poolBatch,15_000,ownerId,leaseAtMs);}finally{db.close();}});if(!rows.length)return false;
 const serviceStartedAtMs=Date.now(),planDb=open();let required=rows,plan:ReturnType<typeof planV4RegistryPoolBatch>={rows:[]};
 try{const already=rows.filter(row=>{const registry=planDb.v4RegistryPool(String(row.pool_id)),observedAt=registry?.last_refreshed_at?Date.parse(String(registry.last_refreshed_at)):0,maintenance=String(row.reason)==='ACTIVE_OPEN_POOL_REFRESH_DUE';return maintenance?observedAt>Number(row.requested_at_ms)&&observedAt+poolTtlMs-serviceStartedAtMs>=freshnessSafetyHeadroomMs(poolTtlMs):observedAt>=Number(row.requested_at_ms);});if(already.length){const writer=persistenceLease(`${ownerId}:already-fresh`);if(!(await writer.acquire()))throw new Error('STATE_PERSISTENCE_LEASE_UNAVAILABLE');let resetConvergedToWatching:string[]=[];try{planDb.db.transaction(()=>{for(const row of already)planDb.completeV4StateRefresh(String(row.pool_id),ownerId,{ttlMs:poolTtlMs,nowMs:Date.now()});resetConvergedToWatching=convergeOpenPendingLadders(planDb,ladderIdsForPools(planDb,already.map(row=>String(row.pool_id))),Date.now());})();}finally{await writer.release();}for(const row of already){const ended=Date.now(),leaseAt=Number(row.leased_at_ms),maintenance=String(row.reason)==='ACTIVE_OPEN_POOL_REFRESH_DUE',freshUntilAtMs=maintenance?Number(row.requested_at_ms)+poolTtlMs:null,next=planDb.db.prepare("SELECT available_at_ms FROM v4_state_refresh_queue WHERE lower(pool_id)=lower(?) AND reason='ACTIVE_OPEN_POOL_REFRESH_DUE'").get(String(row.pool_id)) as {available_at_ms:number}|undefined,context={requestId:`${String(row.pool_id)}:${String(row.requested_at_ms)}`,poolId:String(row.pool_id),reason:String(row.reason),priority:Number(row.priority),enqueueAtMs:Number(row.requested_at_ms),nextDueAtMs:next?.available_at_ms??null,leaseAtMs:leaseAt,freshUntilAtMs,headroomMs:freshUntilAtMs===null?null:freshUntilAtMs-serviceStartedAtMs,refreshGapMs:maintenance?ended-Number(row.requested_at_ms):null,missedDeadlineCount:freshUntilAtMs!==null&&serviceStartedAtMs>=freshUntilAtMs?1:0,leaseOwner:ownerId,serviceStartedAtMs,serviceEndedAtMs:ended,queueWaitMs:Math.max(0,leaseAt-Number(row.requested_at_ms)),rpcMs:0,persistenceMs:ended-serviceStartedAtMs,completionReason:'ALREADY_FRESH_OBLIGATION_SATISFIED',resetConvergedToWatching};try{planDb.recordLatency('v4_state_refresh_request_lifecycle',ended-Number(row.requested_at_ms),{context});}catch{}emit('v4_state_refresh_request_lifecycle',context);}}required=rows.filter(row=>!already.includes(row));plan=planV4RegistryPoolBatch({repo:planDb,poolIds:required.map(row=>String(row.pool_id))});}finally{planDb.close();}
 if(!required.length)return true;if(!plan.rows.length){await retryPoolBatch(required,ownerId,'URGENT_POOL_IDENTITY_UNAVAILABLE');return true;}
 const rpcLeaseDb=open();let acquired=false;try{acquired=acquireRpcReadLease(rpcLeaseDb,ownerId,15_000,Date.now(),'urgent');}finally{rpcLeaseDb.close();}if(!acquired){await retryPoolBatch(required,ownerId,'URGENT_RPC_BUDGET_BUSY');return true;}
 const rpcStartedAtMs=Date.now();let fetched:Awaited<ReturnType<typeof fetchV4RegistryPoolBatch>>;try{fetched=await fetchV4RegistryPoolBatch({rpc,plan});}catch(error){const code=(error instanceof Error?error.message:String(error)).slice(0,160);await retryPoolBatch(required,ownerId,code||'URGENT_POOL_RPC_FAILED');return true;}finally{const releaseDb=open();try{releaseRpcReadLease(releaseDb,ownerId,Date.now(),'urgent');}finally{releaseDb.close();}}
 const rpcEndedAtMs=Date.now(),persistenceStartedAtMs=Date.now(),writer=persistenceLease(ownerId);if(!(await writer.acquire())){await retryPoolBatch(required,ownerId,'STATE_PERSISTENCE_LEASE_TIMEOUT');return true;}const db=open();let batch:{refreshed:string[];failed:string[];multicallPoolCount:number}={refreshed:[],failed:[],multicallPoolCount:0},resetConvergedToWatching:string[]=[];try{db.db.transaction(()=>{batch=persistV4RegistryPoolBatch({repo:db,result:fetched});for(const id of batch.refreshed)db.completeV4StateRefresh(id,ownerId,{ttlMs:poolTtlMs,nowMs:Date.now()});for(const row of required.filter(item=>batch.failed.includes(String(item.pool_id))))db.retryV4StateRefresh(String(row.pool_id),'BOUNDED_MULTICALL_MEMBER_FAILED',Number(row.attempts)+1,Date.now(),ownerId);resetConvergedToWatching=convergeOpenPendingLadders(db,ladderIdsForPools(db,batch.refreshed),Date.now());})();}finally{db.close();await writer.release();}
 const serviceEndedAtMs=Date.now(),telemetryDb=open();try{const ladderIds=ladderIdsForPools(telemetryDb,required.map(row=>String(row.pool_id))),actionable=fullyActionableLadders(telemetryDb,ladderIds,serviceEndedAtMs);for(const row of required){const id=String(row.pool_id),leaseAt=Number(row.leased_at_ms),maintenance=String(row.reason)==='ACTIVE_OPEN_POOL_REFRESH_DUE',freshUntilAtMs=maintenance?Number(row.requested_at_ms)+poolTtlMs:null,next=telemetryDb.db.prepare("SELECT available_at_ms FROM v4_state_refresh_queue WHERE lower(pool_id)=lower(?) AND reason='ACTIVE_OPEN_POOL_REFRESH_DUE'").get(id) as {available_at_ms:number}|undefined,refreshed=batch.refreshed.some(item=>item.toLowerCase()===id.toLowerCase()),context={requestId:`${id}:${String(row.requested_at_ms)}`,poolId:id,reason:String(row.reason),priority:Number(row.priority),enqueueAtMs:Number(row.requested_at_ms),nextDueAtMs:next?.available_at_ms??null,leaseAtMs:leaseAt,freshUntilAtMs,headroomMs:freshUntilAtMs===null?null:freshUntilAtMs-serviceStartedAtMs,refreshGapMs:maintenance?serviceEndedAtMs-Number(row.requested_at_ms):null,missedDeadlineCount:freshUntilAtMs!==null&&serviceStartedAtMs>=freshUntilAtMs?1:0,leaseOwner:ownerId,serviceStartedAtMs,rpcStartedAtMs,rpcEndedAtMs,serviceEndedAtMs,queueWaitMs:Math.max(0,leaseAt-Number(row.requested_at_ms)),rpcMs:rpcEndedAtMs-rpcStartedAtMs,persistenceMs:serviceEndedAtMs-persistenceStartedAtMs,completionReason:refreshed?'RPC_REFRESHED':'RETRYABLE_FAILURE'};try{telemetryDb.recordLatency('v4_state_refresh_request_lifecycle',serviceEndedAtMs-Number(row.requested_at_ms),{context});}catch{}emit('v4_state_refresh_request_lifecycle',context);}emit('rpc_cycle_telemetry',{interaction:'urgent-state-cache',interactionId:ownerId,enqueueToLeaseMaxMs:Math.max(...required.map(row=>Number(row.leased_at_ms)-Number(row.requested_at_ms))),rpcDurationMs:rpcEndedAtMs-rpcStartedAtMs,persistenceDurationMs:serviceEndedAtMs-persistenceStartedAtMs,serviceStartedAtMs,serviceEndedAtMs,openToPoolFreshMs:Math.max(...required.filter(row=>String(row.reason)==='OPERATIONAL_OPEN_POOL_FRESHNESS').map(row=>serviceEndedAtMs-Number(row.requested_at_ms)),0),fullyActionableLadders:actionable,resetConvergedToWatching,jobsLeased:required.length,jobsCompleted:batch.refreshed.length,missedDeadlineCount:required.filter(row=>String(row.reason)==='ACTIVE_OPEN_POOL_REFRESH_DUE'&&serviceStartedAtMs>=Number(row.requested_at_ms)+poolTtlMs).length,ethCallCount:required.length*2,multicallCount:1,multicallMembers:required.length*2,mainnetTransactionsSent:0});}finally{telemetryDb.close();}return true;
}

emit('urgent_state_verifier_started',{idleMs,nftBatch,poolBatch,rpcConcurrency:{urgent:1,background:1,totalMaximum:2},signerConstructed:false,transactionAuthority:false,mainnetTransactionsSent:0});
seedActiveOpenMaintenance();
while(!stopping){try{const db=open();let work;try{const now=Date.now(),critical=runnableUrgentWork(db.db,now,800);work=critical.p0||critical.p1?critical:runnableUrgentWork(db.db,now);}finally{db.close();}let ran=false;if(work.p0&&work.p1){ran=cursor===0?await serviceTargeted():await servicePools();cursor=cursor===0?1:0;}else if(work.p0)ran=await serviceTargeted();else if(work.p1)ran=await servicePools();if(ran)continue;}catch(error){emit('urgent_state_cycle_error',{error:(error instanceof Error?error.message:String(error)).slice(0,200),mainnetTransactionsSent:0});}if(!stopping)await sleep(idleMs);}
emit('urgent_state_verifier_stopped',{mainnetTransactionsSent:0});
