import { createHash } from 'node:crypto';
import { getAddress, toHex, type Address } from 'viem';
import {
  positionManagerAbi as v3PositionManagerAbi,
  ROBINHOOD_V3_DEPLOYMENT_SPECS,
  erc20Abi,
  robinhoodMainnet,
  type FallbackRpc,
} from '@robin/core';
import { amountsForLiquidity, poolId, sqrtPriceAtTick, positionManagerAbi as v4PositionManagerAbi, v4StateViewAbi, V4_ROBINHOOD_DEPLOYMENTS, type V4PoolKey } from '@robin/v4';
import type { SqliteLedgerRepository, TokenAmounts } from '@robin/ledger';
import { canonicalPortfolioAccounting, deriveTokenStableMarketRange, type OptionalUsd } from './portfolio.js';
import { positionAdoption } from './position-adoption.js';

export type TerminalReason='TRANSFERRED_OUT'|'BURNED'|'CLOSED_EMPTY'|'REPLACED'|'OWNERSHIP_LOST';
export type ActiveReconciliationRow={
 position_id:string;protocol_version:'v3'|'v4';token_id:string;manager_address:string;owner_result:string|null;
 owner_status:'VERIFIED_OWNED'|'VERIFIED_UNOWNED'|'NONEXISTENT'|'UNKNOWN';liquidity_raw:string|null;claimable0_raw:string|null;claimable1_raw:string|null;
 terminal_reason:TerminalReason|null;replaced_by_position_id:string|null;confirmed_active:number;contributes_equity:number;
 check_block:string|null;checked_at_ms:number;fresh_until_ms:number;retry_count:number;retry_after_ms:number|null;last_error:string|null;details_json:string;
};
export type PositionTruthClassification='CONFIRMED_ACTIVE_FRESH'|'CONFIRMED_ACTIVE_REFRESHING'|'OPEN_CONFIRMING'|'PENDING_NEVER_VERIFIED'|'TERMINAL';
export type ActivePositionTruth={positionId:string;protocol:'v3'|'v4';tokenId:string;localStatus:string;classification:PositionTruthClassification;terminalReason:TerminalReason|null;reconciliation?:ActiveReconciliationRow;contributesEquity:boolean};
const multicallAddress='0xca11bde05977b3631167028862be2a173976ca11' as Address;
const v3Manager=ROBINHOOD_V3_DEPLOYMENT_SPECS.find(item=>item.name==='positionManager')!.address;
const same=(a:string|undefined|null,b:string)=>Boolean(a&&a.toLowerCase()===b.toLowerCase());
const json=(value:unknown)=>JSON.stringify(value,(_,item)=>typeof item==='bigint'?item.toString():item);
const hash=(value:unknown)=>createHash('sha256').update(json(value)).digest('hex');
function reconciliation(repo:SqliteLedgerRepository,positionId:string){return repo.db.prepare('SELECT * FROM active_position_reconciliations WHERE position_id=?').get(positionId) as ActiveReconciliationRow|undefined;}
function replacement(repo:SqliteLedgerRepository,positionId:string){
 return repo.db.prepare("SELECT w.replacement_position_id FROM rebalance_workflows w JOIN rebalance_lineages l ON l.id=w.lineage_id WHERE (w.old_position_id=? OR l.root_position_id=?) AND w.replacement_position_id IS NOT NULL AND w.state IN ('REOPEN_CONFIRMED','COMPLETED') ORDER BY w.updated_at DESC LIMIT 1").get(positionId,positionId) as {replacement_position_id:string}|undefined;
}
export function activePositionTruth(repo:SqliteLedgerRepository,nowMs=Date.now()):ActivePositionTruth[]{
 const v4Ids=new Set(repo.listV4Positions().map(row=>String(row.token_id)));
 return repo.listPositions().map(position=>{
  const protocol=position.id.startsWith('v4:')||v4Ids.has(position.token_id)?'v4' as const:'v3' as const,v4=protocol==='v4'?repo.v4Position(position.token_id):undefined,localStatus=String(v4?.status??position.status),row=reconciliation(repo,position.id),terminal=row?.terminal_reason??(['burned','closed','transferred','replaced'].includes(localStatus)?(localStatus==='burned'?'BURNED':localStatus==='replaced'?'REPLACED':'CLOSED_EMPTY') as TerminalReason:null);
  let details:Record<string,unknown>={};try{details=row?JSON.parse(row.details_json):{};}catch{}
  const previouslyVerified=Boolean(row?.confirmed_active&&!terminal),fresh=previouslyVerified&&row!.fresh_until_ms>nowMs;
  const openConfirming=!terminal&&!previouslyVerified&&details.presentationState==='OPEN_CONFIRMING';
  const classification:PositionTruthClassification=terminal?'TERMINAL':fresh?'CONFIRMED_ACTIVE_FRESH':previouslyVerified?'CONFIRMED_ACTIVE_REFRESHING':openConfirming?'OPEN_CONFIRMING':'PENDING_NEVER_VERIFIED';
  return {positionId:position.id,protocol,tokenId:position.token_id,localStatus,classification,terminalReason:terminal,reconciliation:row,contributesEquity:previouslyVerified&&Boolean(row?.contributes_equity)};
 });
}
const confirmedPresentation=(item:ActivePositionTruth)=>item.classification==='CONFIRMED_ACTIVE_FRESH'||item.classification==='CONFIRMED_ACTIVE_REFRESHING';
export function activePositionReconciliationAudit(repo:SqliteLedgerRepository,nowMs=Date.now()){
 const positions=activePositionTruth(repo,nowMs).map(item=>({...item,lineage:replacement(repo,item.positionId)??null}));
 return {status:'READ_ONLY',observedAt:new Date(nowMs).toISOString(),positions,confirmedActiveCount:positions.filter(confirmedPresentation).length,refreshingCount:positions.filter(x=>x.classification==='CONFIRMED_ACTIVE_REFRESHING').length,openConfirmingCount:positions.filter(x=>x.classification==='OPEN_CONFIRMING').length,pendingReconciliationCount:positions.filter(x=>x.classification==='PENDING_NEVER_VERIFIED').length,terminalizedCount:positions.filter(x=>x.classification==='TERMINAL').length,mainnetTransactionsSent:0};
}
type Planned={positionId:string;protocol:'v3'|'v4';tokenId:string;manager:Address;local:Record<string,unknown>;contracts:any[];offset:number;members:number;replacedBy?:string;supplyToken?:Address;supplyDecimals?:number};
function plan(repo:SqliteLedgerRepository,positionId:string,offset:number):Planned|undefined{
 const generic=repo.db.prepare('SELECT * FROM positions WHERE id=?').get(positionId) as Record<string,unknown>|undefined;if(!generic)return;
 const protocol=positionId.startsWith('v4:')?'v4' as const:'v3' as const,tokenId=String(generic.token_id),replacedBy=replacement(repo,positionId)?.replacement_position_id;
 if(protocol==='v3')return {positionId,protocol,tokenId,manager:v3Manager,local:generic,offset,members:2,replacedBy,contracts:[{address:v3Manager,abi:v3PositionManagerAbi,functionName:'ownerOf',args:[BigInt(tokenId)]},{address:v3Manager,abi:v3PositionManagerAbi,functionName:'positions',args:[BigInt(tokenId)]}]};
 const row=repo.v4Position(tokenId);if(!row)return;const key=JSON.parse(String(row.pool_key_json)) as V4PoolKey,id=poolId(key),metadata=v4CurrentValuationDecimals(row,key),token0IsUsd=same(key.currency0,robinhoodMainnet.assets.USDG),token1IsUsd=same(key.currency1,robinhoodMainnet.assets.USDG),supplyToken=token0IsUsd?key.currency1:token1IsUsd?key.currency0:undefined,supplyDecimals=token0IsUsd?metadata?.currency1:token1IsUsd?metadata?.currency0:undefined,contracts=[
  {address:V4_ROBINHOOD_DEPLOYMENTS.positionManager,abi:v4PositionManagerAbi,functionName:'ownerOf',args:[BigInt(tokenId)]},
  {address:V4_ROBINHOOD_DEPLOYMENTS.positionManager,abi:v4PositionManagerAbi,functionName:'getPositionLiquidity',args:[BigInt(tokenId)]},
  {address:V4_ROBINHOOD_DEPLOYMENTS.stateView,abi:v4StateViewAbi,functionName:'getPositionInfo',args:[id,V4_ROBINHOOD_DEPLOYMENTS.positionManager,Number(row.tick_lower),Number(row.tick_upper),toHex(BigInt(tokenId),{size:32})]},
  {address:V4_ROBINHOOD_DEPLOYMENTS.stateView,abi:v4StateViewAbi,functionName:'getFeeGrowthInside',args:[id,Number(row.tick_lower),Number(row.tick_upper)]},
  {address:V4_ROBINHOOD_DEPLOYMENTS.stateView,abi:v4StateViewAbi,functionName:'getSlot0',args:[id]},
  ...(supplyToken&&supplyDecimals!==undefined?[{address:supplyToken,abi:erc20Abi,functionName:'totalSupply'}]:[])];
 return {positionId,protocol,tokenId,manager:V4_ROBINHOOD_DEPLOYMENTS.positionManager,local:row,offset,members:contracts.length,replacedBy,contracts,supplyToken,supplyDecimals};
}
const failed=(value:any)=>!value||value.status!=='success';
const reasonText=(value:any)=>String(value?.error?.shortMessage??value?.error?.message??'RPC_RESULT_UNAVAILABLE');
function persist(repo:SqliteLedgerRepository,input:{item:Planned;wallet:Address;results:any[];block:bigint;nowMs:number;ttlMs:number}){
 const {item,results}=input,ownerResult=results[0],positionResult=results[1];let ownerStatus:ActiveReconciliationRow['owner_status']='UNKNOWN',owner:string|null=null,liquidity:bigint|null=null,fee0:bigint|null=null,fee1:bigint|null=null,error:string|null=null;
 if(failed(ownerResult)){const text=reasonText(ownerResult);if(/nonexistent|invalid token|owner query|not_minted/i.test(text))ownerStatus='NONEXISTENT';else error=text;}
 else{owner=String(ownerResult.result);ownerStatus=same(owner,input.wallet)?'VERIFIED_OWNED':'VERIFIED_UNOWNED';}
 if(!failed(positionResult)){
  if(item.protocol==='v4')liquidity=BigInt(positionResult.result);
  else{const value=positionResult.result as readonly unknown[];liquidity=BigInt(String(value[7]));fee0=BigInt(String(value[10]));fee1=BigInt(String(value[11]));}
 }else if(ownerStatus!=='NONEXISTENT')error=reasonText(positionResult);
 if(item.protocol==='v4'&&ownerStatus==='VERIFIED_OWNED'&&results.slice(2,5).every(result=>!failed(result))){
  const stored=results[2].result as readonly [bigint,bigint,bigint],growth=results[3].result as readonly [bigint,bigint],mod=2n**256n,q128=2n**128n,active=liquidity??stored[0];
  fee0=active*((growth[0]-stored[1]+mod)%mod)/q128;fee1=active*((growth[1]-stored[2]+mod)%mod)/q128;
 }
 let terminal:TerminalReason|null=null;
 if(item.replacedBy)terminal='REPLACED';else if(ownerStatus==='NONEXISTENT'){if(item.protocol==='v4'){const burn=repo.v4BurnEvidence(item.tokenId);if(burn.previouslyMinted&&burn.burnConfirmed)terminal='BURNED';else error='V4_NONEXISTENT_WITHOUT_BURN_RECEIPT';}else terminal='BURNED';}else if(ownerStatus==='VERIFIED_UNOWNED'){const candidate=repo.db.prepare('SELECT acquisition_from,relevant_transfer_at FROM wallet_position_candidates WHERE protocol_version=? AND token_id=?').get(item.protocol,item.tokenId) as Record<string,unknown>|undefined;terminal=same(String(candidate?.acquisition_from??''),input.wallet)&&candidate?.relevant_transfer_at?'TRANSFERRED_OUT':'OWNERSHIP_LOST';}else if(ownerStatus==='VERIFIED_OWNED'&&liquidity===0n&&(fee0??0n)===0n&&(fee1??0n)===0n)terminal='CLOSED_EMPTY';
 const previous=reconciliation(repo,item.positionId);
 if(error&&previous?.confirmed_active&&!previous.terminal_reason){
  const details={poolSlot0:null,rpcError:error,presentationState:'CONFIRMED_ACTIVE_REFRESHING',lastVerifiedAtMs:previous.checked_at_ms};
  repo.db.prepare("UPDATE active_position_reconciliations SET fresh_until_ms=?,retry_count=retry_count+1,retry_after_ms=?,last_error=?,details_json=? WHERE position_id=?").run(input.nowMs,input.nowMs+60_000,error,json(details),item.positionId);
  return {positionId:item.positionId,ownerStatus:previous.owner_status,liquidity:previous.liquidity_raw===null?null:BigInt(previous.liquidity_raw),claimable0:previous.claimable0_raw===null?null:BigInt(previous.claimable0_raw),claimable1:previous.claimable1_raw===null?null:BigInt(previous.claimable1_raw),terminalReason:null,confirmedActive:true,error};
 }
 const supplyResult=item.protocol==='v4'&&item.supplyToken&&!failed(results[5])?results[5].result:undefined,supplyNormalized=supplyResult!==undefined&&item.supplyDecimals!==undefined?Number(BigInt(supplyResult))/10**item.supplyDecimals:NaN,supplyEvidence=Number.isFinite(supplyNormalized)&&supplyNormalized>0&&item.supplyToken&&item.supplyDecimals!==undefined?{raw:BigInt(supplyResult).toString(),normalized:supplyNormalized,kind:'TOTAL',source:'rpc:ERC20.totalSupply',observedAt:new Date(input.nowMs).toISOString(),decimals:item.supplyDecimals,token:item.supplyToken}:undefined,confirmed=ownerStatus==='VERIFIED_OWNED'&&!terminal&&((liquidity??0n)>0n||(fee0??0n)>0n||(fee1??0n)>0n),freshUntil=error?input.nowMs:input.nowMs+input.ttlMs,details={poolSlot0:item.protocol==='v4'&&!failed(results[4])?results[4].result:null,tokenSupply:supplyEvidence??null,rpcError:error,presentationState:confirmed?'CONFIRMED_ACTIVE_FRESH':terminal?'TERMINAL':'PENDING_NEVER_VERIFIED'};
 repo.db.prepare(`INSERT INTO active_position_reconciliations(position_id,protocol_version,token_id,manager_address,owner_result,owner_status,liquidity_raw,claimable0_raw,claimable1_raw,terminal_reason,replaced_by_position_id,confirmed_active,contributes_equity,check_block,checked_at_ms,fresh_until_ms,retry_count,retry_after_ms,last_error,details_json)
 VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(position_id) DO UPDATE SET owner_result=excluded.owner_result,owner_status=excluded.owner_status,liquidity_raw=excluded.liquidity_raw,claimable0_raw=excluded.claimable0_raw,claimable1_raw=excluded.claimable1_raw,terminal_reason=excluded.terminal_reason,replaced_by_position_id=excluded.replaced_by_position_id,confirmed_active=excluded.confirmed_active,contributes_equity=excluded.contributes_equity,check_block=excluded.check_block,checked_at_ms=excluded.checked_at_ms,fresh_until_ms=excluded.fresh_until_ms,retry_count=CASE WHEN excluded.last_error IS NULL THEN 0 ELSE active_position_reconciliations.retry_count+1 END,retry_after_ms=excluded.retry_after_ms,last_error=excluded.last_error,details_json=excluded.details_json`)
  .run(item.positionId,item.protocol,item.tokenId,item.manager,owner,ownerStatus,liquidity?.toString()??null,fee0?.toString()??null,fee1?.toString()??null,terminal,item.replacedBy??null,confirmed?1:0,confirmed?1:0,input.block.toString(),input.nowMs,freshUntil,0,error?input.nowMs+60_000:null,error,json(details));
 if(terminal){repo.db.prepare('UPDATE positions SET status=? WHERE id=?').run(terminal==='BURNED'?'burned':terminal==='REPLACED'?'replaced':'closed',item.positionId);if(item.protocol==='v4'){if(terminal==='REPLACED')repo.db.prepare('UPDATE v4_positions SET liquidity_raw=?,updated_at=? WHERE token_id=?').run(liquidity?.toString()??'0',new Date(input.nowMs).toISOString(),item.tokenId);else repo.db.prepare('UPDATE v4_positions SET status=?,liquidity_raw=?,updated_at=? WHERE token_id=?').run(terminal==='BURNED'?'burned':'closed',liquidity?.toString()??'0',new Date(input.nowMs).toISOString(),item.tokenId);}}
 else if(confirmed){repo.db.prepare("UPDATE positions SET status='open' WHERE id=?").run(item.positionId);if(item.protocol==='v4')repo.db.prepare("UPDATE v4_positions SET status='open',liquidity_raw=?,updated_at=? WHERE token_id=?").run(liquidity!.toString(),new Date(input.nowMs).toISOString(),item.tokenId);}
 return {positionId:item.positionId,ownerStatus,liquidity,claimable0:fee0,claimable1:fee1,terminalReason:terminal,confirmedActive:confirmed,error};
}
export async function reconcileActivePositions(input:{repo:SqliteLedgerRepository;rpc:FallbackRpc;wallet:Address;positionIds?:string[];limit?:number;ttlMs?:number;nowMs?:number;interactionId?:string}){
 const started=Date.now(),nowMs=input.nowMs??Date.now(),ttlMs=input.ttlMs??120_000,all=activePositionTruth(input.repo,nowMs),selected=input.positionIds??all.filter(item=>item.classification==='PENDING_NEVER_VERIFIED'||item.classification==='OPEN_CONFIRMING'||item.classification==='CONFIRMED_ACTIVE_REFRESHING').slice(0,input.limit??2).map(item=>item.positionId);
 let offset=0;const planned:Planned[]=[];for(const id of selected){const item=plan(input.repo,id,offset);if(item){planned.push(item);offset+=item.members;}}
 if(!planned.length)return {interactionId:input.interactionId??null,positions:[],activePositionChecks:0,skippedFreshTtlCount:all.filter(item=>item.classification==='CONFIRMED_ACTIVE_FRESH').length,ethCallCount:0,eth_blockNumberCount:0,getCodeCount:0,multicallCount:0,multicallMembers:0,provider:'none',startedAt:new Date(started).toISOString(),endedAt:new Date().toISOString(),totalRpcDurationMs:0,mainnetTransactionsSent:0};
 const rpcStarted=Date.now(),response=await input.rpc.withClient(async client=>Promise.all([client.getBlockNumber({cacheTime:0}),client.multicall({multicallAddress,allowFailure:true,contracts:planned.flatMap(item=>item.contracts)})])),rpcMs=Date.now()-rpcStarted,[block,results]=response;
 let positions:ReturnType<typeof persist>[]=[];input.repo.db.transaction(()=>{positions=planned.map(item=>persist(input.repo,{item,wallet:input.wallet,results:(results as any[]).slice(item.offset,item.offset+item.members),block,nowMs,ttlMs}));persistPortfolioSnapshot(input.repo,nowMs);})();
 return {interactionId:input.interactionId??null,positions,activePositionChecks:planned.length,skippedFreshTtlCount:all.length-planned.length,ethCallCount:offset,eth_blockNumberCount:1,getCodeCount:0,multicallCount:1,multicallMembers:offset,provider:'alchemy',startedAt:new Date(started).toISOString(),endedAt:new Date().toISOString(),totalRpcDurationMs:rpcMs,mainnetTransactionsSent:0};
}
function rawUsd(raw:bigint,decimals:number,usd:number){const value=Number(raw)/10**decimals*usd;return Number.isFinite(value)?value:null;}
type V4CurrentDecimals={currency0:number;currency1:number;source:'LIVE_V4_POSITION_INSPECTION'|'COMPLETE_ORIENTATION_METADATA'};
function validDecimals(value:unknown):value is number{return typeof value==='number'&&Number.isInteger(value)&&value>=0&&value<=255;}
function cachedCirculatingSupply(repo:SqliteLedgerRepository,address:Address,decimals:number,nowMs:number){
 const row=repo.db.prepare('SELECT observed_at_ms,source_json FROM gmgn_robinhood_observations WHERE lower(token_address)=lower(?) ORDER BY observed_at_ms DESC LIMIT 1').get(address) as {observed_at_ms:number;source_json:string}|undefined;
 if(!row||row.observed_at_ms>nowMs||nowMs-row.observed_at_ms>30*60_000)return;
 try{const basis=JSON.parse(row.source_json).supplyBasis as {kind?:unknown;raw?:unknown}|undefined,raw=typeof basis?.raw==='string'&&/^\d+$/.test(basis.raw)?basis.raw:undefined,normalized=raw?Number(BigInt(raw))/10**decimals:NaN;if(basis?.kind==='circulating'&&raw&&Number.isFinite(normalized)&&normalized>0)return {raw,normalized,kind:'CIRCULATING' as const,source:'gmgn cached circulating supply',observedAt:new Date(row.observed_at_ms).toISOString(),decimals};}catch{}return;
}
/** Current valuation metadata is currency-ordered and intentionally independent of historical accounting. */
export function v4CurrentValuationDecimals(row:Record<string,unknown>,key:V4PoolKey):V4CurrentDecimals|undefined{
 try{const metadata=JSON.parse(String(row.valuation_provenance_json??'')) as {currency0?:{address?:unknown;decimals?:unknown};currency1?:{address?:unknown;decimals?:unknown}};if(same(String(metadata.currency0?.address??''),key.currency0)&&same(String(metadata.currency1?.address??''),key.currency1)&&validDecimals(metadata.currency0?.decimals)&&validDecimals(metadata.currency1?.decimals))return {currency0:metadata.currency0.decimals,currency1:metadata.currency1.decimals,source:'LIVE_V4_POSITION_INSPECTION'};}catch{}
 const targetIndex=row.target_index===null||row.target_index===undefined?undefined:Number(row.target_index),targetDecimals=row.target_decimals===null||row.target_decimals===undefined?undefined:Number(row.target_decimals),fundingDecimals=row.funding_decimals===null||row.funding_decimals===undefined?undefined:Number(row.funding_decimals),target=String(row.target_token??''),funding=String(row.funding_token??'');
 if(targetIndex===0&&same(target,key.currency0)&&same(funding,key.currency1)&&validDecimals(targetDecimals)&&validDecimals(fundingDecimals))return {currency0:targetDecimals,currency1:fundingDecimals,source:'COMPLETE_ORIENTATION_METADATA'};
 if(targetIndex===1&&same(target,key.currency1)&&same(funding,key.currency0)&&validDecimals(targetDecimals)&&validDecimals(fundingDecimals))return {currency0:fundingDecimals,currency1:targetDecimals,source:'COMPLETE_ORIENTATION_METADATA'};
 return undefined;
}
function ledgerGasUsd(repo:SqliteLedgerRepository,positionId:string):OptionalUsd{const row=repo.db.prepare('SELECT COUNT(*) total,COUNT(usd_value) priced,COALESCE(SUM(usd_value),0) value FROM gas_costs WHERE position_id=?').get(positionId) as {total:number;priced:number;value:number};return row.total===row.priced&&Number.isFinite(row.value)?row.value:null;}
function historicalUsd(amounts:TokenAmounts,key:V4PoolKey,d0:number,d1:number):OptionalUsd{if(amounts.token0===0n&&amounts.token1===0n)return 0;if(amounts.token0>0n&&!same(key.currency0,robinhoodMainnet.assets.USDG))return null;if(amounts.token1>0n&&!same(key.currency1,robinhoodMainnet.assets.USDG))return null;const value=Number(amounts.token0)/10**d0+Number(amounts.token1)/10**d1;return Number.isFinite(value)?value:null;}
function receiptCostBasis(repo:SqliteLedgerRepository,positionId:string,row:Record<string,unknown>):OptionalUsd{
 const adoption=positionAdoption(repo,positionId);if(adoption?.baseline_provenance==='USER_VERIFIED_BASELINE'&&adoption.original_capital_usd!==null)return Number(adoption.original_capital_usd);
 const fundingIndex=Number(row.funding_index),fundingSymbol=String(row.funding_symbol??adoption?.funding_symbol??'');if(row.open_intent_id&&fundingSymbol==='USDG'){const raw=BigInt(String(fundingIndex===0?row.initial_amount0_raw:row.initial_amount1_raw)),value=Number(raw)/10**Number(row.funding_decimals??6);return Number.isFinite(value)?value:null;}
 const deposits=repo.db.prepare('SELECT token0_raw,token1_raw,prices_json FROM position_deposits WHERE position_id=?').all(positionId) as Array<{token0_raw:string;token1_raw:string;prices_json:string}>;if(!deposits.length)return null;let total=0;for(const deposit of deposits){let prices:Record<string,unknown>={};try{prices=JSON.parse(deposit.prices_json);}catch{return null;}const d0=Number(row.target_index)===0?Number(row.target_decimals??18):Number(row.funding_decimals??18),d1=Number(row.target_index)===1?Number(row.target_decimals??18):Number(row.funding_decimals??18),p0=Number(prices.token0Usd),p1=Number(prices.token1Usd),u0=Number.isFinite(p0)&&p0>0?p0:same(String(row.currency0),robinhoodMainnet.assets.USDG)?1:NaN,u1=Number.isFinite(p1)&&p1>0?p1:same(String(row.currency1),robinhoodMainnet.assets.USDG)?1:NaN;if((BigInt(deposit.token0_raw)>0n&&!Number.isFinite(u0))||(BigInt(deposit.token1_raw)>0n&&!Number.isFinite(u1)))return null;total+=Number(deposit.token0_raw)/10**d0*(Number.isFinite(u0)?u0:0)+Number(deposit.token1_raw)/10**d1*(Number.isFinite(u1)?u1:0);}return Number.isFinite(total)?total:null;
}
function lineageAccounting(repo:SqliteLedgerRepository,positionId:string){const row=repo.db.prepare('SELECT l.*,w.replacement_position_id FROM rebalance_lineages l LEFT JOIN rebalance_workflows w ON w.lineage_id=l.id WHERE l.root_position_id=? OR w.replacement_position_id=? ORDER BY w.updated_at DESC LIMIT 1').get(positionId,positionId) as Record<string,unknown>|undefined;if(!row)return null;const sums=repo.db.prepare("SELECT COALESCE(SUM(CASE WHEN kind='TOPUP_EXTERNAL_CAPITAL' THEN usd_value ELSE 0 END),0) topups FROM rebalance_accounting_events e JOIN rebalance_workflows w ON w.id=e.workflow_id WHERE w.lineage_id=?").get(String(row.id)) as {topups:number},replacement=row.replacement_position_id?String(row.replacement_position_id):null;return {costBasisUsd:Number(row.original_principal_usd)+Number(sums.topups),excluded:Boolean(replacement&&positionId!==replacement)};}
export type PersistedPortfolioSnapshot=ReturnType<typeof buildPersistedPortfolioSnapshot>;
export function buildPersistedPortfolioSnapshot(repo:SqliteLedgerRepository,nowMs=Date.now()){
 const truth=activePositionTruth(repo,nowMs),positions=[] as Array<Record<string,unknown>>;
 for(const item of truth){
  if(item.protocol!=='v4')continue;
  const row=repo.v4Position(item.tokenId);if(!row)continue;const rec=item.reconciliation,registry=repo.v4RegistryPool(String(row.pool_id)),key=JSON.parse(String(row.pool_key_json)) as V4PoolKey,metadata=v4CurrentValuationDecimals(row,key),d0=metadata?.currency0,d1=metadata?.currency1,totals=repo.collectionTotals(item.positionId),lineage=lineageAccounting(repo,item.positionId),terminal=item.classification==='TERMINAL';
  let currentPriceUsd:OptionalUsd=null,activePrincipalUsd:OptionalUsd=terminal?0:null,uncollectedFeesUsd:OptionalUsd=terminal?0:null,rangeStatus:'IN_RANGE'|'OUT_OF_RANGE'|'CLOSED'|'UNAVAILABLE'=terminal?'CLOSED':'UNAVAILABLE',range='Unavailable',priceBlock:string|null=null,priceObservedAt:string|null=null,marketRange:ReturnType<typeof deriveTokenStableMarketRange>|undefined;
  if(metadata&&registry?.sqrt_price_x96){const sqrt=BigInt(String(registry.sqrt_price_x96)),ratio=(Number(sqrt)/2**96)**2*10**(d0!-d1!),usd0=same(key.currency0,robinhoodMainnet.assets.USDG)?1:same(key.currency1,robinhoodMainnet.assets.USDG)?ratio:undefined,usd1=same(key.currency1,robinhoodMainnet.assets.USDG)?1:same(key.currency0,robinhoodMainnet.assets.USDG)?1/ratio:undefined,targetIndex=row.target_index===null||row.target_index===undefined?undefined:Number(row.target_index);if(usd0&&usd1){currentPriceUsd=targetIndex===0?usd0:targetIndex===1?usd1:null;let supply:Record<string,unknown>|undefined;try{supply=JSON.parse(String(rec?.details_json??'{}')).tokenSupply;}catch{}const normalized=Number(supply?.normalized),decimals=Number(supply?.decimals),volatile=same(key.currency0,robinhoodMainnet.assets.USDG)?key.currency1:same(key.currency1,robinhoodMainnet.assets.USDG)?key.currency0:undefined,volatileDecimals=same(key.currency0,robinhoodMainnet.assets.USDG)?d1!:same(key.currency1,robinhoodMainnet.assets.USDG)?d0!:undefined,circulating=volatile&&volatileDecimals!==undefined?cachedCirculatingSupply(repo,volatile,volatileDecimals,nowMs):undefined,total=Number.isFinite(normalized)&&normalized>0&&Number.isInteger(decimals)?{raw:String(supply?.raw),normalized,kind:'TOTAL' as const,source:String(supply?.source??'rpc:ERC20.totalSupply'),observedAt:String(supply?.observedAt??''),decimals}:undefined;marketRange=deriveTokenStableMarketRange({token0:key.currency0,token1:key.currency1,token0Usd:usd0,token1Usd:usd1,token0Decimals:d0!,token1Decimals:d1!,tickLower:Number(row.tick_lower),tickUpper:Number(row.tick_upper),supply:circulating??total});if(!terminal&&rec&&rec.liquidity_raw!==null){const amounts=amountsForLiquidity(sqrt,Number(row.tick_lower),Number(row.tick_upper),BigInt(rec.liquidity_raw)),p0=rawUsd(amounts.token0,d0!,usd0),p1=rawUsd(amounts.token1,d1!,usd1),f0=rawUsd(BigInt(rec.claimable0_raw??'0'),d0!,usd0),f1=rawUsd(BigInt(rec.claimable1_raw??'0'),d1!,usd1);activePrincipalUsd=p0!==null&&p1!==null?p0+p1:null;uncollectedFeesUsd=f0!==null&&f1!==null?f0+f1:null;rangeStatus=Number(registry.current_tick)>=Number(row.tick_lower)&&Number(registry.current_tick)<Number(row.tick_upper)?'IN_RANGE':'OUT_OF_RANGE';}priceBlock=registry.refresh_block?String(registry.refresh_block):null;priceObservedAt=registry.last_refreshed_at?String(registry.last_refreshed_at):null;}}
  const costBasisUsd=lineage?.costBasisUsd??receiptCostBasis(repo,item.positionId,row),collectedFeesUsd=metadata?historicalUsd(totals.fees,key,d0!,d1!):null,realizedProceedsUsd=metadata?historicalUsd(totals.principal,key,d0!,d1!):null,gasSpentUsd=ledgerGasUsd(repo,item.positionId),accounting=canonicalPortfolioAccounting({externalCapitalUsd:costBasisUsd,activePrincipalUsd,uncollectedFeesUsd,collectedFeesUsd,realizedProceedsUsd,gasSpentUsd}),opened=repo.db.prepare('SELECT MIN(block_timestamp) opened_at FROM position_deposits WHERE position_id=?').get(item.positionId) as {opened_at:string|null},adoption=positionAdoption(repo,item.positionId);
  positions.push({positionId:item.positionId,protocol:item.protocol,tokenId:item.tokenId,pair:`${String(row.target_symbol??'TOKEN')}/${String(row.funding_symbol??adoption?.funding_symbol??'FUNDING')}`,poolId:String(row.pool_id),status:String(row.status),range,rangeStatus,currentPriceUsd,marketRange,valuationMetadataStatus:metadata?'AVAILABLE':'VALUATION_METADATA_UNAVAILABLE',valuationMetadataSource:metadata?.source??null,valuationWarning:metadata?null:'VALUATION_METADATA_UNAVAILABLE',source:row.open_intent_id?'BOT_OPERATIONAL':adoption?'MANUAL_EXTERNAL':'TRACKED',accountingStatus:row.open_intent_id?'RECEIPT_ACCOUNTED':String(adoption?.accounting_status??'TRACKED'),accounting,openedAt:opened.opened_at,baselineProvenance:row.open_intent_id?'OPERATIONAL_OPEN_RECEIPT':adoption?.baseline_provenance??null,fundingProvenance:row.open_intent_id?'OPERATIONAL_OPEN_SELECTION':adoption?.funding_provenance??null,openIntentId:row.open_intent_id?String(row.open_intent_id):null,lifecycle:item.classification,terminalReason:item.terminalReason,ownerResult:rec?.owner_result??null,liquidityRaw:rec?.liquidity_raw??null,tickLower:Number(row.tick_lower),tickUpper:Number(row.tick_upper),claimable0Raw:rec?.claimable0_raw??null,claimable1Raw:rec?.claimable1_raw??null,lastReconciledAt:rec?new Date(rec.checked_at_ms).toISOString():null,priceSource:currentPriceUsd===null?null:'Persisted v4 StateView pool cache + verified token decimals',priceBlock,priceObservedAt,reconciliation:row.open_intent_id?'BOT_OPERATIONAL_RECEIPT_LEDGER':String(adoption?.accounting_status??(accounting.warnings.length?'PARTIAL':'COMPLETE')),excludedFromAggregateReason:lineage?.excluded?'REPLACED_BY_CHILD_POSITION':null});
 }
 const included=positions.filter(position=>!position.excludedFromAggregateReason),active=included.filter(position=>position.lifecycle==='CONFIRMED_ACTIVE_FRESH'||position.lifecycle==='CONFIRMED_ACTIVE_REFRESHING'),refreshing=active.filter(position=>position.lifecycle==='CONFIRMED_ACTIVE_REFRESHING'),openConfirmingTruth=truth.filter(item=>item.classification==='OPEN_CONFIRMING'),pendingTruth=truth.filter(item=>item.classification==='PENDING_NEVER_VERIFIED'),all=(field:string)=>included.length>0&&included.every(position=>typeof (position.accounting as Record<string,unknown>)[field]==='number')?included.reduce((sum,position)=>sum+Number((position.accounting as Record<string,unknown>)[field]),0):null,last=Math.max(0,...truth.map(item=>item.reconciliation?.checked_at_ms??0)),payload={observedAt:new Date(nowMs).toISOString(),positions,totalEquityUsd:all('currentEquityUsd'),originalCapitalUsd:all('externalCapitalUsd'),grossPnlUsd:all('grossPnlUsd'),netPnlUsd:all('netPnlUsd'),roiPct:null as number|null,uncollectedFeesUsd:all('uncollectedFeesUsd'),collectedFeesUsd:all('collectedFeesUsd'),realizedProceedsUsd:all('realizedProceedsUsd'),gasSpentUsd:all('gasSpentUsd'),activePositions:active.length,inRange:active.filter(position=>position.rangeStatus==='IN_RANGE').length,outOfRange:active.filter(position=>position.rangeStatus==='OUT_OF_RANGE').length,refreshingCount:refreshing.length,openConfirmingCount:openConfirmingTruth.length,pendingReconciliationCount:pendingTruth.length,lastReconciliationAt:last?new Date(last).toISOString():null,confirmedActiveCount:active.length,mainnetTransactionsSent:0};payload.roiPct=payload.netPnlUsd!==null&&payload.originalCapitalUsd!==null&&payload.originalCapitalUsd>0?payload.netPnlUsd/payload.originalCapitalUsd*100:null;return payload;
}
export function persistPortfolioSnapshot(repo:SqliteLedgerRepository,nowMs=Date.now()){const payload=buildPersistedPortfolioSnapshot(repo,nowMs),{observedAt:_observed,lastReconciliationAt:_last,...material}=payload,contentHash=hash(material);repo.db.prepare("INSERT INTO portfolio_persisted_snapshot(snapshot_key,payload_json,content_hash,refreshed_at_ms,last_reconciliation_at_ms) VALUES('current',?,?,?,?) ON CONFLICT(snapshot_key) DO UPDATE SET payload_json=excluded.payload_json,content_hash=excluded.content_hash,refreshed_at_ms=excluded.refreshed_at_ms,last_reconciliation_at_ms=excluded.last_reconciliation_at_ms").run(json(payload),contentHash,nowMs,payload.lastReconciliationAt?Date.parse(payload.lastReconciliationAt):null);return {...payload,contentHash};}
export function persistedPortfolioSnapshot(repo:SqliteLedgerRepository){const row=repo.db.prepare("SELECT * FROM portfolio_persisted_snapshot WHERE snapshot_key='current'").get() as Record<string,unknown>|undefined;return row?{...JSON.parse(String(row.payload_json)),contentHash:String(row.content_hash)}:persistPortfolioSnapshot(repo);}
export function enqueuePortfolioRefresh(repo:SqliteLedgerRepository,reason:string,nowMs=Date.now()){repo.db.prepare("INSERT INTO portfolio_refresh_requests(request_key,requested_at_ms,available_at_ms,reason) VALUES('current',?,?,?) ON CONFLICT(request_key) DO UPDATE SET requested_at_ms=max(requested_at_ms,excluded.requested_at_ms),available_at_ms=CASE WHEN leased_until_ms IS NULL THEN min(available_at_ms,excluded.available_at_ms) ELSE available_at_ms END,reason=excluded.reason").run(nowMs,nowMs,reason);}
export function leasePortfolioRefresh(repo:SqliteLedgerRepository,leaseMs:number,nowMs=Date.now()){const row=repo.db.prepare("SELECT * FROM portfolio_refresh_requests WHERE request_key='current' AND available_at_ms<=? AND (leased_until_ms IS NULL OR leased_until_ms<?)").get(nowMs,nowMs) as Record<string,unknown>|undefined;if(row)repo.db.prepare("UPDATE portfolio_refresh_requests SET leased_until_ms=? WHERE request_key='current'").run(nowMs+leaseMs);return row;}
export function completePortfolioRefresh(repo:SqliteLedgerRepository,nowMs=Date.now()){repo.db.prepare("UPDATE portfolio_refresh_requests SET completed_at_ms=?,leased_until_ms=NULL,available_at_ms=9223372036854775807,last_error=NULL,attempts=0 WHERE request_key='current'").run(nowMs);}
export function acquireRpcReadLease(repo:SqliteLedgerRepository,ownerId:string,leaseMs:number,nowMs=Date.now()){
 const run=repo.db.transaction(()=>{const row=repo.db.prepare("SELECT owner_id,leased_until_ms FROM rpc_read_work_lease WHERE lease_key='alchemy-read-budget'").get() as {owner_id:string;leased_until_ms:number}|undefined;if(row&&row.leased_until_ms>nowMs&&row.owner_id!==ownerId)return false;repo.db.prepare("INSERT INTO rpc_read_work_lease(lease_key,owner_id,leased_until_ms,updated_at_ms) VALUES('alchemy-read-budget',?,?,?) ON CONFLICT(lease_key) DO UPDATE SET owner_id=excluded.owner_id,leased_until_ms=excluded.leased_until_ms,updated_at_ms=excluded.updated_at_ms").run(ownerId,nowMs+leaseMs,nowMs);return true;});return run();
}
export function releaseRpcReadLease(repo:SqliteLedgerRepository,ownerId:string,nowMs=Date.now()){return repo.db.prepare("UPDATE rpc_read_work_lease SET leased_until_ms=?,updated_at_ms=? WHERE lease_key='alchemy-read-budget' AND owner_id=?").run(nowMs,nowMs,ownerId).changes===1;}

export function markOperationalPositionOpenConfirming(repo:SqliteLedgerRepository,input:{positionId:string;tokenId:string;intentId:string;mintHash:string;blockNumber:bigint;nowMs?:number}){
 const nowMs=input.nowMs??Date.now(),details=json({presentationState:'OPEN_CONFIRMING',intentId:input.intentId,mintHash:input.mintHash,blockNumber:input.blockNumber,receiptConfirmed:true});
 repo.db.prepare(`INSERT INTO active_position_reconciliations(position_id,protocol_version,token_id,manager_address,owner_status,terminal_reason,confirmed_active,contributes_equity,checked_at_ms,fresh_until_ms,retry_count,details_json)
 VALUES(?,'v4',?,?, 'UNKNOWN',NULL,0,0,?,?,0,?)
 ON CONFLICT(position_id) DO UPDATE SET details_json=CASE WHEN active_position_reconciliations.confirmed_active=1 THEN active_position_reconciliations.details_json ELSE excluded.details_json END,
 fresh_until_ms=CASE WHEN active_position_reconciliations.confirmed_active=1 THEN active_position_reconciliations.fresh_until_ms ELSE excluded.fresh_until_ms END`).run(input.positionId,input.tokenId,V4_ROBINHOOD_DEPLOYMENTS.positionManager,nowMs,nowMs,details);
 enqueueTargetedPositionReconciliation(repo,{positionId:input.positionId,tokenId:input.tokenId,protocol:'v4',reason:'OPERATIONAL_MINT_CONFIRMED',priority:1_000,nowMs});
}
export function enqueueTargetedPositionReconciliation(repo:SqliteLedgerRepository,input:{positionId:string;tokenId:string;protocol:'v3'|'v4';reason:string;priority?:number;nowMs?:number}){
 const nowMs=input.nowMs??Date.now(),pending=repo.db.prepare('SELECT 1 FROM targeted_position_reconciliation_requests WHERE position_id=?').get(input.positionId);repo.db.prepare(`INSERT INTO targeted_position_reconciliation_requests(position_id,token_id,protocol_version,reason,priority,requested_at_ms,available_at_ms)
 VALUES(?,?,?,?,?,?,?) ON CONFLICT(position_id) DO UPDATE SET reason=excluded.reason,priority=max(priority,excluded.priority),requested_at_ms=max(requested_at_ms,excluded.requested_at_ms),available_at_ms=CASE WHEN leased_until_ms IS NULL THEN min(available_at_ms,excluded.available_at_ms) ELSE available_at_ms END`).run(input.positionId,input.tokenId,input.protocol,input.reason,input.priority??100,nowMs,nowMs);
 return pending?'ALREADY_PENDING' as const:'ENQUEUED' as const;
}
export function leaseTargetedPositionReconciliations(repo:SqliteLedgerRepository,limit:number,leaseMs:number,nowMs=Date.now()){
 const run=repo.db.transaction(()=>{const rows=repo.db.prepare("SELECT * FROM targeted_position_reconciliation_requests WHERE available_at_ms<=? AND (leased_until_ms IS NULL OR leased_until_ms<?) ORDER BY priority DESC,requested_at_ms LIMIT ?").all(nowMs,nowMs,limit) as Record<string,unknown>[];const lease=repo.db.prepare('UPDATE targeted_position_reconciliation_requests SET leased_until_ms=? WHERE position_id=?');for(const row of rows)lease.run(nowMs+leaseMs,row.position_id);return rows;});return run();
}
export function completeTargetedPositionReconciliation(repo:SqliteLedgerRepository,positionId:string,nowMs=Date.now()){repo.db.prepare('DELETE FROM targeted_position_reconciliation_requests WHERE position_id=?').run(positionId);return nowMs;}
export function retryTargetedPositionReconciliation(repo:SqliteLedgerRepository,positionId:string,error:string,nowMs=Date.now()){const row=repo.db.prepare('SELECT attempts FROM targeted_position_reconciliation_requests WHERE position_id=?').get(positionId) as {attempts:number}|undefined,attempts=Number(row?.attempts??0)+1,delay=Math.min(60_000,1_000*2**Math.min(attempts,6));repo.db.prepare('UPDATE targeted_position_reconciliation_requests SET attempts=?,leased_until_ms=NULL,available_at_ms=?,last_error=? WHERE position_id=?').run(attempts,nowMs+delay,error.slice(0,500),positionId);}
