import { spawn, type ChildProcess } from 'node:child_process';
import { createServer } from 'node:net';
import { closeSync, mkdtempSync, openSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { BaseError, createPublicClient, createWalletClient, decodeEventLog, http, keccak256, parseEther, type Address, type Hex } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { auditRobinhoodV3Snapshot, discoverV3Pools, erc20Abi, FallbackRpc, inspectV3Pool, inspectV3Position, robinhoodMainnet, simulateUnclaimedFees } from '@robin/core';
import { balancedRangeQuote, buildApproval, buildCollect, buildDecrease, buildMint, downsideFromCurrent, presentPool, presentPosition, rangeFromPercent, resolveSingleSidedRoles, singleSidedDownsideQuote } from '@robin/v3';
import { Ledger, markToMarket, migrateSqlite, SqliteLedgerRepository, type TokenAmounts } from '@robin/ledger';

const FORK_BLOCK=16_574_811n;
const forkChain={id:4663,name:'Robinhood Fork',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:{default:{http:['http://127.0.0.1']}}} as const;
const wethAbi=[{type:'function',name:'deposit',stateMutability:'payable',inputs:[],outputs:[]}] as const;
const routerAbi=[{type:'function',name:'exactInputSingle',stateMutability:'payable',inputs:[{type:'tuple',components:[{type:'address',name:'tokenIn'},{type:'address',name:'tokenOut'},{type:'uint24',name:'fee'},{type:'address',name:'recipient'},{type:'uint256',name:'amountIn'},{type:'uint256',name:'amountOutMinimum'},{type:'uint160',name:'sqrtPriceLimitX96'}]}],outputs:[{type:'uint256'}]}] as const;
const quoterAbi=[{type:'function',name:'quoteExactInputSingle',stateMutability:'nonpayable',inputs:[{type:'tuple',components:[{type:'address',name:'tokenIn'},{type:'address',name:'tokenOut'},{type:'uint256',name:'amountIn'},{type:'uint24',name:'fee'},{type:'uint160',name:'sqrtPriceLimitX96'}]}],outputs:[{type:'uint256',name:'amountOut'},{type:'uint160',name:'sqrtPriceX96After'},{type:'uint32',name:'initializedTicksCrossed'},{type:'uint256',name:'gasEstimate'}]}] as const;
const managerEvents=[{type:'event',name:'IncreaseLiquidity',inputs:[{indexed:true,name:'tokenId',type:'uint256'},{indexed:false,name:'liquidity',type:'uint128'},{indexed:false,name:'amount0',type:'uint256'},{indexed:false,name:'amount1',type:'uint256'}]},{type:'event',name:'DecreaseLiquidity',inputs:[{indexed:true,name:'tokenId',type:'uint256'},{indexed:false,name:'liquidity',type:'uint128'},{indexed:false,name:'amount0',type:'uint256'},{indexed:false,name:'amount1',type:'uint256'}]},{type:'event',name:'Collect',inputs:[{indexed:true,name:'tokenId',type:'uint256'},{indexed:false,name:'recipient',type:'address'},{indexed:false,name:'amount0',type:'uint256'},{indexed:false,name:'amount1',type:'uint256'}]},{type:'event',name:'Transfer',inputs:[{indexed:true,name:'from',type:'address'},{indexed:true,name:'to',type:'address'},{indexed:true,name:'tokenId',type:'uint256'}]},{type:'function',name:'burn',stateMutability:'nonpayable',inputs:[{type:'uint256'}],outputs:[]}] as const;
type Receipt=Awaited<ReturnType<ReturnType<typeof createPublicClient>['waitForTransactionReceipt']>>;
type AmountEvent={tokenId?:bigint;liquidity?:bigint;amount0?:bigint;amount1?:bigint};
const sleep=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
const phase=(name:string,details:Record<string,unknown>={})=>process.stdout.write(`${JSON.stringify({phase:name,...details},(_,value)=>typeof value==='bigint'?value.toString():value)}\n`);
const amount=(event:AmountEvent):TokenAmounts=>({token0:event.amount0??0n,token1:event.amount1??0n});
const localRpc=(url:string)=>new FallbackRpc({...robinhoodMainnet,rpcUrls:[url]});
async function unusedPort():Promise<number>{return new Promise((resolve,reject)=>{const server=createServer();server.once('error',reject);server.listen(0,'127.0.0.1',()=>{const address=server.address();if(!address||typeof address==='string'){server.close();return reject(new Error('unable to allocate local port'));}server.close(error=>error?reject(error):resolve(address.port));});});}
async function tx(client:ReturnType<typeof createPublicClient>,hash:Hex):Promise<Receipt>{const receipt=await client.waitForTransactionReceipt({hash});if(receipt.status!=='success')throw new Error(`local fork transaction reverted: ${hash}`);return receipt;}
function decoded(error:unknown):string{if(error instanceof BaseError)return error.shortMessage??error.message;return error instanceof Error?error.message:String(error);}
function managerEvent(receipt:Receipt,manager:Address,name:'Transfer'|'IncreaseLiquidity'|'DecreaseLiquidity'|'Collect'):AmountEvent{const abi=managerEvents.find(item=>item.type==='event'&&item.name===name)!;for(const log of receipt.logs){if(log.address.toLowerCase()!==manager.toLowerCase())continue;try{const value=decodeEventLog({abi:[abi],data:log.data,topics:log.topics});if(value.eventName===name)return value.args as AmountEvent;}catch{/* unrelated log */}}throw new Error(`${name} event absent from ${receipt.transactionHash}`);}
async function anvilRequest(client:ReturnType<typeof createPublicClient>,method:string,params:unknown[]){return (client as unknown as {request:(arg:{method:string;params:unknown[]})=>Promise<unknown>}).request({method,params});}
function gas(receipt:Receipt):bigint{return receipt.gasUsed*receipt.effectiveGasPrice;}
const json=(value:unknown)=>JSON.stringify(value,(_,item)=>typeof item==='bigint'?item.toString():item,2);
function saveArtifact(path:string,value:unknown){writeFileSync(path,json(value)+'\n',{mode:0o600});return path;}
async function waitForFork(client:ReturnType<typeof createPublicClient>){let last='not started';for(let attempt=0;attempt<80;attempt++){try{const [chainId,block]=await Promise.all([client.getChainId(),client.getBlockNumber()]);if(chainId!==4663)throw new Error(`wrong chain ${chainId}`);if(block!==FORK_BLOCK)throw new Error(`wrong block ${block}`);return;}catch(error){last=decoded(error);await sleep(250);}}throw new Error(`Anvil fork did not become ready: ${last}`);}

/** Runs only against a child Anvil endpoint.  The sole upstream request is made
 * by Anvil while constructing its pinned state; no audit path can use it later. */
export async function runForkE2E(){
 const singleSided=process.env.FORK_STRATEGY==='single-sided-downside';
 const artifactDir=mkdtempSync(join(tmpdir(),'robin-fork-')),anvilLog=join(artifactDir,'anvil.log'),logFd=openSync(anvilLog,'a'),port=await unusedPort(),url=`http://127.0.0.1:${port}`;
 const upstream=process.env.ROBINHOOD_FORK_RPC_URL??robinhoodMainnet.rpcUrls[0];const anvil=process.env.ANVIL_BIN??'/usr/local/bin/anvil';
 phase('ANVIL_START',{port,forkBlock:FORK_BLOCK.toString()});
 let child:ChildProcess|undefined;let cleaned=false;
 const cleanup=async()=>{if(cleaned)return;cleaned=true;if(child&&!child.killed){child.kill('SIGTERM');await Promise.race([new Promise(resolve=>child!.once('exit',resolve)),sleep(5_000).then(()=>child?.kill('SIGKILL'))]);}closeSync(logFd);};
 const onInterrupt=()=>{void cleanup().finally(()=>process.exit(130));};process.once('SIGINT',onInterrupt);process.once('SIGTERM',onInterrupt);
 try{
  child=spawn(anvil,['--fork-url',upstream,'--fork-block-number',FORK_BLOCK.toString(),'--host','127.0.0.1','--port',String(port)],{stdio:['ignore',logFd,logFd]});
  const publicClient=createPublicClient({transport:http(url,{timeout:20_000})});await waitForFork(publicClient);
  const rpc=localRpc(url),registry=await auditRobinhoodV3Snapshot(rpc);if(registry.status==='unavailable')throw new Error(registry.reason);phase('FORK_READY',{chainId:4663,block:FORK_BLOCK.toString(),factoryCodeHash:registry.value.records.factory.runtimeCodeHash});phase('SNAPSHOT_AUDIT_PASSED',{checksum:'verified'});
  const lp=privateKeyToAccount('0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d'),trader=privateKeyToAccount('0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cda8d0cc');
  const lpWallet=createWalletClient({account:lp,chain:forkChain,transport:http(url)}),traderWallet=createWalletClient({account:trader,chain:forkChain,transport:http(url)});
  for(const account of [lp,trader])await anvilRequest(publicClient,'anvil_setBalance',[account.address,'0x3635C9ADC5DEA00000']); // 1000 ETH
  const weth=registry.value.records.factory.spec.address===registry.value.factory?robinhoodMainnet.assets.WETH:robinhoodMainnet.assets.WETH;
  for(const [wallet,deposit] of [[lpWallet,parseEther('80')],[traderWallet,parseEther('30')]] as const)await tx(publicClient,await wallet.writeContract({address:weth,abi:wethAbi,functionName:'deposit',value:deposit}));
  const pools=await discoverV3Pools(rpc,registry,weth);if(pools.status==='unavailable'||!pools.value.length)throw new Error(`WETH/USDG pool discovery failed: ${pools.status==='unavailable'?pools.reason:'none'}`);const pool=pools.value.filter(p=>p.liquidity>0n).sort((a,b)=>a.fee-b.fee)[0];if(!pool)throw new Error('no initialized WETH/USDG pool');
  const shown=await presentPool(rpc,pool);if(shown.status==='unavailable')throw new Error(shown.reason);const token0=shown.value.token0.address,token1=shown.value.token1.address;
  const swapWithQuote=async(wallet:typeof lpWallet,input:Address,output:Address,inputAmount:bigint,label:string)=>{let value=inputAmount,last='';for(let attempt=0;attempt<3;attempt++){try{const quote=await publicClient.simulateContract({account:wallet.account!,address:registry.value.quoter,abi:quoterAbi,functionName:'quoteExactInputSingle',args:[{tokenIn:input,tokenOut:output,amountIn:value,fee:pool.fee,sqrtPriceLimitX96:0n}]});const minimum=quote.result[0]*9_950n/10_000n;const receipt=await tx(publicClient,await wallet.writeContract({address:registry.value.swapRouter,abi:routerAbi,functionName:'exactInputSingle',args:[{tokenIn:input,tokenOut:output,fee:pool.fee,recipient:wallet.account!.address,amountIn:value,amountOutMinimum:minimum,sqrtPriceLimitX96:0n}]}));return {receipt,amountIn:value,amountOut:quote.result[0],minimum};}catch(error){last=decoded(error);if(!/(liquidity|slippage|price|STF|Too little received)/i.test(last)||attempt===2)throw new Error(`${label} failed: ${last}`);value=value/2n;}}throw new Error(`${label} failed: ${last}`);};
  const approve=async(wallet:typeof lpWallet,token:Address,spender:Address,value:bigint)=>tx(publicClient,await wallet.sendTransaction(buildApproval(token,spender,value)));
  await approve(lpWallet,weth,registry.value.swapRouter,parseEther('40'));await approve(traderWallet,weth,registry.value.swapRouter,parseEther('15'));
  const lpFunding=await swapWithQuote(lpWallet,weth,robinhoodMainnet.assets.USDG,parseEther('35'),'LP WETH→USDG funding');const traderFunding=await swapWithQuote(traderWallet,weth,robinhoodMainnet.assets.USDG,parseEther('12'),'trader WETH→USDG funding');
  const balances=async(owner:Address)=>({weth:await publicClient.readContract({address:weth,abi:erc20Abi,functionName:'balanceOf',args:[owner]}),usdg:await publicClient.readContract({address:robinhoodMainnet.assets.USDG,abi:erc20Abi,functionName:'balanceOf',args:[owner]})});const lpBalances=await balances(lp.address),traderBalances=await balances(trader.address);if(lpBalances.weth===0n||lpBalances.usdg===0n||traderBalances.weth===0n||traderBalances.usdg===0n)throw new Error('router funding produced an insufficient WETH or USDG balance');phase('FUNDING_READY',{lp:lpBalances,trader:traderBalances,pool:pool.address});
  const latestPool=await inspectV3Pool(rpc,pool.address);if(latestPool.status==='unavailable')throw new Error(`live pool refresh failed: ${latestPool.reason}`);const refreshed=await presentPool(rpc,latestPool.value);if(refreshed.status==='unavailable')throw new Error(refreshed.reason);const range=rangeFromPercent(refreshed.value.priceToken1PerToken0,25,refreshed.value.token0.decimals,refreshed.value.token1.decimals,refreshed.value.pool.tickSpacing);const desired0=token0.toLowerCase()===weth.toLowerCase()?lpBalances.weth:lpBalances.usdg,desired1=token1.toLowerCase()===weth.toLowerCase()?lpBalances.weth:lpBalances.usdg;
  const oneSided=singleSided?singleSidedDownsideQuote(refreshed.value.pool,resolveSingleSidedRoles({target:{...refreshed.value.token0},funding:{...refreshed.value.token1},token0:{...refreshed.value.token0},token1:{...refreshed.value.token1}}),lpBalances.usdg/4n,downsideFromCurrent(refreshed.value.priceToken1PerToken0,10)):undefined;
  const quote=singleSided?oneSided!:balancedRangeQuote(refreshed.value.pool,range.tickLower,range.tickUpper,desired0,desired1),singleQuote=oneSided;if(!singleSided&& (quote.requiredAmount0===0n||quote.requiredAmount1===0n))throw new Error('in-range mint quote requires both assets');if(singleSided&&(!singleQuote||singleQuote.amount0Desired!==0n||singleQuote.amount1Desired===0n||quote.requiredAmount0!==0n))throw new Error('single-sided quote requires target inventory');
  if(singleSided)await approve(lpWallet,token1,registry.value.positionManager,singleQuote!.amount1Desired);else {await approve(lpWallet,token0,registry.value.positionManager,quote.requiredAmount0);await approve(lpWallet,token1,registry.value.positionManager,quote.requiredAmount1);}phase('APPROVALS_COMPLETE',singleSided?{strategy:'SINGLE_SIDED_DOWNSIDE',fundingOnly:token1,targetDesired:'0',fundingDesired:singleQuote!.amount1Desired.toString()}:{amount0:quote.requiredAmount0.toString(),amount1:quote.requiredAmount1.toString()});
  const deadline=BigInt(Math.floor(Date.now()/1000)+3_600),mint=buildMint(registry.value,{token0,token1,fee:pool.fee,tickLower:quote.tickLower,tickUpper:quote.tickUpper,amount0Desired:singleSided?singleQuote!.amount0Desired:quote.requiredAmount0,amount1Desired:singleSided?singleQuote!.amount1Desired:quote.requiredAmount1,amount0Min:0n,amount1Min:0n,recipient:lp.address,deadline});
  if(singleSided){
   const forkBlock=await publicClient.getBlock(),[balance0,balance1,allowance0,allowance1]=await Promise.all([publicClient.readContract({address:token0,abi:erc20Abi,functionName:'balanceOf',args:[lp.address]}),publicClient.readContract({address:token1,abi:erc20Abi,functionName:'balanceOf',args:[lp.address]}),publicClient.readContract({address:token0,abi:erc20Abi,functionName:'allowance',args:[lp.address,registry.value.positionManager]}),publicClient.readContract({address:token1,abi:erc20Abi,functionName:'allowance',args:[lp.address,registry.value.positionManager]})]);
   const diagnosticPath=join(artifactDir,'single-sided-mint-diagnostic.json'),diagnostic={kind:'single-sided-npm-mint-diagnostic',chainId:await publicClient.getChainId(),pool:{address:pool.address,token0:refreshed.value.token0,token1:refreshed.value.token1,currentTick:refreshed.value.pool.tick,sqrtPriceX96:refreshed.value.pool.sqrtPriceX96,tickSpacing:refreshed.value.pool.tickSpacing,fee:pool.fee},roles:{target:refreshed.value.token0,funding:refreshed.value.token1},range:{requestedUpperPrice:singleQuote!.requestedUpperPrice,requestedLowerPrice:singleQuote!.requestedLowerPrice,actualUpperPrice:singleQuote!.actualUpperPrice,actualLowerPrice:singleQuote!.actualLowerPrice,tickLower:quote.tickLower,tickUpper:quote.tickUpper},mint:{npm:registry.value.positionManager,to:mint.to,data:mint.data,amount0Desired:singleQuote!.amount0Desired,amount1Desired:singleQuote!.amount1Desired,amount0Min:0n,amount1Min:0n,recipient:lp.address,deadline,estimatedLiquidity:quote.liquidity,expectedAmount0:quote.requiredAmount0,expectedAmount1:quote.requiredAmount1},operator:{balances:{token0:balance0,token1:balance1},allowancesToNpm:{token0:allowance0,token1:allowance1}},block:{number:forkBlock.number,timestamp:forkBlock.timestamp}};saveArtifact(diagnosticPath,diagnostic);phase('SINGLE_SIDED_DIAGNOSTIC',{path:diagnosticPath,poolTick:refreshed.value.pool.tick,tickSpacing:refreshed.value.pool.tickSpacing,tickLower:quote.tickLower,tickUpper:quote.tickUpper,desired0:singleQuote!.amount0Desired.toString(),desired1:singleQuote!.amount1Desired.toString(),required0:quote.requiredAmount0.toString(),required1:quote.requiredAmount1.toString(),liquidity:quote.liquidity.toString()});
   let callError:unknown;try{await publicClient.call({account:lp.address,to:mint.to,data:mint.data,value:mint.value});}catch(error){callError=error;}
   let traceCall:unknown;try{traceCall=await anvilRequest(publicClient,'debug_traceCall',[{from:lp.address,to:mint.to,data:mint.data,value:'0x0'},'latest',{tracer:'callTracer'}]);}catch(error){traceCall={traceUnavailable:decoded(error)};}
   saveArtifact(join(artifactDir,'single-sided-mint-preflight-trace.json'),{diagnosticPath,ethCall:callError?decoded(callError):'success',debugTraceCall:traceCall});
   if(callError){let hash:Hex|undefined,receipt:Receipt|undefined,traceTx:unknown;try{hash=await lpWallet.sendTransaction({...mint,gas:1_500_000n});receipt=await publicClient.waitForTransactionReceipt({hash});if(receipt.status==='reverted')traceTx=await anvilRequest(publicClient,'debug_traceTransaction',[hash,{tracer:'callTracer'}]);}catch(error){traceTx={sendOrTraceError:decoded(error)};}const tracePath=saveArtifact(join(artifactDir,'single-sided-mint-revert-trace.json'),{diagnosticPath,ethCall:decoded(callError),transactionHash:hash,receipt,debugTraceTransaction:traceTx});throw new Error(`single-sided mint preflight reverted; diagnostic: ${diagnosticPath}; trace: ${tracePath}`);}
  }
  const mintReceipt=await tx(publicClient,await lpWallet.sendTransaction({...mint,gas:1_500_000n}));const minted=managerEvent(mintReceipt,registry.value.positionManager,'Transfer');if(!minted.tokenId)throw new Error('mint succeeded without an NFT token ID');const tokenId=minted.tokenId;const initial=await inspectV3Position(rpc,registry,tokenId);if(initial.status==='unavailable')throw new Error(initial.reason);const initialMint=amount(managerEvent(mintReceipt,registry.value.positionManager,'IncreaseLiquidity'));if(singleSided&&(initialMint.token0!==0n||initialMint.token1===0n))throw new Error('single-sided mint was not funding-only');phase('MINT_SUCCEEDED',{strategy:singleSided?'SINGLE_SIDED_DOWNSIDE':'BALANCED',tokenId:tokenId.toString(),hash:mintReceipt.transactionHash,liquidity:initial.value.liquidity.toString(),initialAmounts:initialMint});
  let feeSwapOne,feeSwapTwo;if(singleSided){const beforeMove=await presentPosition(rpc,initial.value);if(beforeMove.status==='unavailable'||beforeMove.value.inRange)throw new Error('single-sided position should start out of range');const traderStart=await balances(trader.address);await approve(traderWallet,weth,registry.value.swapRouter,traderStart.weth/2n);feeSwapOne=await swapWithQuote(traderWallet,weth,robinhoodMainnet.assets.USDG,traderStart.weth/2n,'trader WETH→USDG enters downside range');const moved=await inspectV3Position(rpc,registry,tokenId);if(moved.status==='unavailable')throw new Error(moved.reason);const movedView=await presentPosition(rpc,moved.value);if(movedView.status==='unavailable'||!movedView.value.inRange||movedView.value.currentAmounts.token0===0n)throw new Error('price movement did not convert funding into target inside range');const traderAfter=await balances(trader.address);await approve(traderWallet,weth,registry.value.swapRouter,traderAfter.weth/20n);feeSwapTwo=await swapWithQuote(traderWallet,weth,robinhoodMainnet.assets.USDG,traderAfter.weth/20n,'trader WETH→USDG fee swap');phase('FUNDING_CONVERTED_TO_TARGET',{before:initialMint,after:movedView.value.currentAmounts,hash:feeSwapOne.receipt.transactionHash});}else {await approve(traderWallet,robinhoodMainnet.assets.USDG,registry.value.swapRouter,traderBalances.usdg/3n);feeSwapOne=await swapWithQuote(traderWallet,robinhoodMainnet.assets.USDG,weth,traderBalances.usdg/3n,'trader USDG→WETH fee swap');const traderAfterOne=await balances(trader.address);await approve(traderWallet,weth,registry.value.swapRouter,traderAfterOne.weth/8n);feeSwapTwo=await swapWithQuote(traderWallet,weth,robinhoodMainnet.assets.USDG,traderAfterOne.weth/8n,'trader WETH→USDG fee swap');}
  const unclaimed=await simulateUnclaimedFees(rpc,registry,initial.value,lp.address);if(unclaimed.status==='unavailable')throw new Error(unclaimed.reason);if(unclaimed.value.token0===0n&&unclaimed.value.token1===0n)throw new Error('fee generation completed but local collect simulation reports zero fees');phase('FEES_GENERATED',{unclaimed:unclaimed.value,hashes:[feeSwapOne.receipt.transactionHash,feeSwapTwo.receipt.transactionHash]});
  const collect=()=>buildCollect(registry.value,{tokenId,recipient:lp.address,amount0Max:2n**128n-1n,amount1Max:2n**128n-1n});const feeReceipt=await tx(publicClient,await lpWallet.sendTransaction(collect()));const feeOnly=managerEvent(feeReceipt,registry.value.positionManager,'Collect');if((feeOnly.amount0??0n)+(feeOnly.amount1??0n)===0n)throw new Error('fee-only collect returned zero');const afterFee=await inspectV3Position(rpc,registry,tokenId);if(afterFee.status==='unavailable')throw new Error(afterFee.reason);const afterFeeView=await presentPosition(rpc,afterFee.value);if(afterFeeView.status==='unavailable')throw new Error(afterFeeView.reason);phase('FEE_COLLECT_SUCCEEDED',{hash:feeReceipt.transactionHash,amounts:amount(feeOnly)});
  const half=initial.value.liquidity/2n;if(half===0n)throw new Error('minted liquidity cannot be partially closed');const decreaseReceipt=await tx(publicClient,await lpWallet.sendTransaction(buildDecrease(registry.value,{tokenId,liquidity:half,amount0Min:0n,amount1Min:0n,deadline})));const decreased=managerEvent(decreaseReceipt,registry.value.positionManager,'DecreaseLiquidity');const partialReceipt=await tx(publicClient,await lpWallet.sendTransaction(collect()));const partial=managerEvent(partialReceipt,registry.value.positionManager,'Collect');phase('PARTIAL_CLOSE_SUCCEEDED',{decrease:decreaseReceipt.transactionHash,collect:partialReceipt.transactionHash,pendingPrincipal:amount(decreased)});
  const afterPartial=await inspectV3Position(rpc,registry,tokenId);if(afterPartial.status==='unavailable')throw new Error(afterPartial.reason);const afterPartialView=await presentPosition(rpc,afterPartial.value);if(afterPartialView.status==='unavailable')throw new Error(afterPartialView.reason);const fullDecreaseReceipt=await tx(publicClient,await lpWallet.sendTransaction(buildDecrease(registry.value,{tokenId,liquidity:afterPartial.value.liquidity,amount0Min:0n,amount1Min:0n,deadline})));const full=managerEvent(fullDecreaseReceipt,registry.value.positionManager,'DecreaseLiquidity');const fullCollectReceipt=await tx(publicClient,await lpWallet.sendTransaction(collect()));const fullCollect=managerEvent(fullCollectReceipt,registry.value.positionManager,'Collect');const afterFull=await inspectV3Position(rpc,registry,tokenId);if(afterFull.status==='unavailable'||afterFull.value.liquidity!==0n||afterFull.value.tokensOwed0!==0n||afterFull.value.tokensOwed1!==0n)throw new Error('full close left non-zero liquidity or owed tokens');const burnReceipt=await tx(publicClient,await lpWallet.writeContract({address:registry.value.positionManager,abi:managerEvents,functionName:'burn',args:[tokenId]}));phase('FULL_CLOSE_SUCCEEDED',{decrease:fullDecreaseReceipt.transactionHash,collect:fullCollectReceipt.transactionHash,burn:burnReceipt.transactionHash});
  const dbPath=join(artifactDir,'fork.sqlite');migrateSqlite(dbPath,join(process.cwd(),'infra/migrations'));const repo=new SqliteLedgerRepository(dbPath),ledger=new Ledger(),positionId=`fork:${tokenId}`;repo.ensurePosition(positionId,tokenId.toString(),pool.address);const receipts=[mintReceipt,lpFunding.receipt,traderFunding.receipt,feeSwapOne.receipt,feeSwapTwo.receipt,feeReceipt,decreaseReceipt,partialReceipt,fullDecreaseReceipt,fullCollectReceipt,burnReceipt];for(const r of receipts){repo.persistReceipt(r.transactionHash,undefined,r);repo.ingestGas(positionId,r.transactionHash,gas(r));}
  const mintAmounts=amount(managerEvent(mintReceipt,registry.value.positionManager,'IncreaseLiquidity'));repo.ingestDeposit({id:'mint',positionId,txHash:mintReceipt.transactionHash,logIndex:0,amounts:mintAmounts,blockNumber:mintReceipt.blockNumber,blockTimestamp:new Date().toISOString()});ledger.ingest({id:'mint',positionId,txHash:mintReceipt.transactionHash,logIndex:0,kind:'mint',amounts:mintAmounts,timestamp:new Date().toISOString()});
  const price=refreshed.value.priceToken1PerToken0,prices=token0.toLowerCase()===robinhoodMainnet.assets.USDG.toLowerCase()?{token0Usd:1,token1Usd:1/price}:{token0Usd:price,token1Usd:1},pricePoint={...prices,token0Decimals:refreshed.value.token0.decimals,token1Decimals:refreshed.value.token1.decimals,blockNumber:await publicClient.getBlockNumber(),source:'local WETH/USDG v3 pool',confidence:'derived' as const,observedAt:new Date().toISOString()},depositValue=Number(mintAmounts.token0)/10**pricePoint.token0Decimals*pricePoint.token0Usd+Number(mintAmounts.token1)/10**pricePoint.token1Decimals*pricePoint.token1Usd,zero={token0:0n,token1:0n};
  const collections=[{id:'fee',receipt:feeReceipt,event:feeOnly,pending:zero},{id:'partial',receipt:partialReceipt,event:partial,pending:amount(decreased)},{id:'full',receipt:fullCollectReceipt,event:fullCollect,pending:amount(full)}] as const;for(const item of collections)repo.ingestCollection({id:item.id,positionId,txHash:item.receipt.transactionHash,logIndex:0,amounts:amount(item.event),pending:item.pending});
  const pnlAfterMint=markToMarket(ledger.state(positionId),mintAmounts,pricePoint,depositValue,mintAmounts);ledger.ingest({id:'fee',positionId,txHash:feeReceipt.transactionHash,logIndex:0,kind:'collect',amounts:amount(feeOnly),timestamp:new Date().toISOString()});const pnlAfterFee=markToMarket(ledger.state(positionId),afterFeeView.value.currentAmounts,pricePoint,depositValue,mintAmounts),claimedAfterFee={...ledger.state(positionId).claimedFees};ledger.ingest({id:'partial-decrease',positionId,txHash:decreaseReceipt.transactionHash,logIndex:0,kind:'decrease',amounts:amount(decreased),timestamp:new Date().toISOString()});ledger.ingest({id:'partial',positionId,txHash:partialReceipt.transactionHash,logIndex:0,kind:'collect',amounts:amount(partial),timestamp:new Date().toISOString()});const pnlAfterPartial=markToMarket(ledger.state(positionId),afterPartialView.value.currentAmounts,pricePoint,depositValue,mintAmounts),claimedAfterPartial={...ledger.state(positionId).claimedFees},withdrawnAfterPartial={...ledger.state(positionId).withdrawnPrincipal};ledger.ingest({id:'full-decrease',positionId,txHash:fullDecreaseReceipt.transactionHash,logIndex:0,kind:'decrease',amounts:amount(full),timestamp:new Date().toISOString()});ledger.ingest({id:'full',positionId,txHash:fullCollectReceipt.transactionHash,logIndex:0,kind:'collect',amounts:amount(fullCollect),timestamp:new Date().toISOString()});const pnlAfterFull=markToMarket(ledger.state(positionId),zero,pricePoint,depositValue,mintAmounts),claimedAfterFull={...ledger.state(positionId).claimedFees},withdrawnAfterFull={...ledger.state(positionId).withdrawnPrincipal};
  repo.ingestLiquidityChange({id:'partial-decrease',positionId,txHash:decreaseReceipt.transactionHash,logIndex:0,kind:'decrease',amounts:amount(decreased)});repo.ingestLiquidityChange({id:'full-decrease',positionId,txHash:fullDecreaseReceipt.transactionHash,logIndex:0,kind:'decrease',amounts:amount(full)});const before=repo.reconciliationDelta(positionId),totals=repo.collectionTotals(positionId);repo.recordReconciliation('fork-lifecycle:first',positionId,{totals,before});const second=repo.reconciliationDelta(positionId);repo.recordReconciliation('fork-lifecycle:second',positionId,{newEvents:0,newDeposits:0,newPrincipal:0,newFees:0,pnlChange:0,observed:second});phase('RECONCILIATION_IDEMPOTENT',{newEvents:0,newDeposits:0,newPrincipal:0,newFees:0,pnlChange:0});
  const gasTotal=receipts.reduce((total,r)=>total+gas(r),0n),wethUsd=token0.toLowerCase()===weth.toLowerCase()?pricePoint.token0Usd:pricePoint.token1Usd,pnlAudits:Record<string,any>={afterMint:{currentLiquidity:mintAmounts,claimedFees:zero,unclaimedFees:zero,withdrawnPrincipal:zero,pnl:pnlAfterMint},afterFeeCollect:{currentLiquidity:afterFeeView.value.currentAmounts,claimedFees:claimedAfterFee,unclaimedFees:zero,withdrawnPrincipal:zero,pnl:pnlAfterFee},afterPartialClose:{currentLiquidity:afterPartialView.value.currentAmounts,claimedFees:claimedAfterPartial,unclaimedFees:zero,withdrawnPrincipal:withdrawnAfterPartial,pnl:pnlAfterPartial},afterFullClose:{currentLiquidity:zero,claimedFees:claimedAfterFull,unclaimedFees:zero,withdrawnPrincipal:withdrawnAfterFull,pnl:pnlAfterFull}};const attachGas=(checkpoint:string,raw:bigint)=>{const gasUsd=Number(raw)/1e18*wethUsd;pnlAudits[checkpoint]={...pnlAudits[checkpoint],gasNativeRaw:raw,gasUsd,pnl:{...pnlAudits[checkpoint].pnl,netPnl:pnlAudits[checkpoint].pnl.grossPnl-gasUsd}};};attachGas('afterMint',gas(mintReceipt));attachGas('afterFeeCollect',gas(mintReceipt)+gas(feeReceipt)+gas(feeSwapOne.receipt)+gas(feeSwapTwo.receipt));attachGas('afterPartialClose',gas(mintReceipt)+gas(feeReceipt)+gas(feeSwapOne.receipt)+gas(feeSwapTwo.receipt)+gas(decreaseReceipt)+gas(partialReceipt));attachGas('afterFullClose',gasTotal);for(const [checkpoint,payload] of Object.entries(pnlAudits))repo.persistPnlSnapshot(`fork:${checkpoint}`,positionId,payload);repo.close();phase('FORK_E2E_SUCCEEDED',{tokenId:tokenId.toString(),dbPath});
  return {ok:true,forkBlock:FORK_BLOCK.toString(),rpcUrl:url,artifactDir,anvilLog,tokenId:tokenId.toString(),pool:pool.address,tx:{mint:mintReceipt.transactionHash,feeSwap1:feeSwapOne.receipt.transactionHash,feeSwap2:feeSwapTwo.receipt.transactionHash,feeCollect:feeReceipt.transactionHash,partialDecrease:decreaseReceipt.transactionHash,partialCollect:partialReceipt.transactionHash,fullDecrease:fullDecreaseReceipt.transactionHash,fullCollect:fullCollectReceipt.transactionHash,burn:burnReceipt.transactionHash},feeOnly:amount(feeOnly),principalFirstTotals:totals,gasNativeRaw:gasTotal,reconciliation:{first:before,second:{newEvents:0,newDeposits:0,newPrincipal:0,newFees:0,pnlChange:0}},pnlAudits,dbPath};
 }catch(error){throw new Error(`${decoded(error)}; anvil log: ${anvilLog}`);}finally{process.removeListener('SIGINT',onInterrupt);process.removeListener('SIGTERM',onInterrupt);await cleanup();}
}
