import 'dotenv/config';
import { join } from 'node:path';
import { getAddress, type Address } from 'viem';
import { auditRobinhoodV3Deployments, auditRobinhoodV3Snapshot, diagnoseV3SwapReadiness, discoverV3Pools, FallbackRpc, inspectErc20, inspectV3Pool, inspectV3Position, robinhoodMainnet, sanitizeRpcError, simulateUnclaimedFees, walletV3Positions } from '@robin/core';
import { balancedRangeQuote, buildApproval, buildMint, canExecuteV3, presentPool, presentPosition, rangeFromPercent, simulateApproval, simulateBuiltTransaction } from '@robin/v3';
import { backupSqlite, migrateSqlite, restoreSqliteBackup, sqliteStatus, SqliteLedgerRepository } from '@robin/ledger';
import { runForkE2E } from './fork-e2e.js';
import { sequentialApprovalMintSimulation } from './sequential-approval-sim.js';
import { runGuardedCanaryE2E } from './guarded-canary-e2e.js';
import { liveCanaryRoutePreflight } from './live-canary-route-preflight.js';
import { v4DeploymentStatus, v4LifecycleAudit, v4LifecyclePreflight, v4OpenPreflight, v4PnlAudit, v4PoolDiscover, v4PoolInspectById, v4PositionInspect, v4PositionReconcile } from './v4-cli.js';
import { runV4ForkE2E } from './v4-fork-e2e.js';
import { runV4LifecycleE2E } from './v4-lifecycle-e2e.js';
import { runGenericV4ForkE2E } from './v4-generic-fork-e2e.js';
import { allowanceAudit, dedicatedWallet, guardedWalletClient, initializeSafety, logsRpc, redactSecrets, runtimeEnv as env, runtimePaths, runtimeRpc as rpc, safetyPayload, staticCanaryReachability, walletPreflight, walletStatus } from './runtime.js';
import { V4_LIVE_AMOUNT, V4_LIVE_POOL_ID, V4_LIVE_POOL_KEY, defaultV4LiveLimits, v4LiveOpenPreflight } from './v4-live-canary.js';
import { bootstrapV4PoolRegistry, refreshV4RegistryPool, syncV4PoolRegistry, v4PoolsForToken, v4RegistryStatus } from './v4-registry.js';
import { buildPortfolioAudit } from './portfolio.js';
import { authorizeRebalanceWorkflow, calculateRebalancePlan, createRebalanceWorkflow, ensureRebalanceLineage, rebalanceTransitions, rebalanceWorkflow } from './rebalance.js';
import { runRebalanceDryRunE2E } from './rebalance-dry-run-e2e.js';
import { runV4RebalanceE2E } from './v4-rebalance-e2e.js';
import { adoptionAudit, importKnownV4Position, operationalOpenIntentAudit, syncWalletPositions, walletPositionSyncAudit } from './position-adoption.js';
import { activePositionReconciliationAudit, enqueueTargetedPositionReconciliation, reconcileActivePositions } from './active-position-reconciliation.js';
import { cleanupLegacyDirectLookupFanout } from './direct-token-lookup.js';
import { runV4OperationalOpenE2E } from './v4-operational-e2e.js';
import { safetyStatus, setDurableManualPause } from './safety-operator.js';
import { auditRobinhoodV4Deployments, positionManagerAbi, V4_ROBINHOOD_DEPLOYMENTS } from '@robin/v4';
import { executeV4Rebalance, rebalanceExecutionBlockers } from './v4-rebalance-executor.js';
import { executeV4OperationalOpen, prepareV4OperationalPreviewContext, v4OperationalOpenPreflight, type GenericV4OpenSelection } from './v4-operational-executor.js';
import { botManagedProjectedExposure } from './bot-managed-exposure.js';
import { applyErrorSecretScrub, applyRebalanceExactHashReconciliation, errorSecretScrubPlan, exactHashReconcileToken, previewRebalanceExactHashReconciliation, rebalanceResumeRecoveryCandidate, verifyExactHashReconcileToken } from './rebalance-transaction.js';
import { assertPermanentReleaseEligibility, assertRebalanceCommitmentNotPermanentlyReleased, insertRebalanceCommitmentRelease, rebalanceCommitmentReleaseEvidence, rebalanceCommitmentReleaseMarkerValid, releaseConfirmationToken, verifyReleaseConfirmationToken } from './rebalance-commitment-release.js';

const out=(value:unknown)=>process.stdout.write(JSON.stringify(redactSecrets(value),(_,v)=>typeof v==='bigint'?v.toString():v,2)+'\n');
const human=(title:string,value:Record<string,unknown>)=>{process.stdout.write(`${title}\n${Object.entries(value).map(([k,v])=>`- ${k}: ${typeof v==='string'?v:JSON.stringify(redactSecrets(v),(_,x)=>typeof x==='bigint'?x.toString():x)}`).join('\n')}\nJSON:\n`);out(value);};
const audited=()=>auditRobinhoodV3Deployments(rpc);
const deploymentVerdict=(audit:Awaited<ReturnType<typeof auditRobinhoodV3Deployments>>)=>audit.status==='available'?audit.value.verification:(audit.details as {verification?:unknown}|undefined)?.verification;
function repository(){return new SqliteLedgerRepository(runtimePaths.databasePath);}
function startup(){migrateSqlite(runtimePaths.databasePath,'infra/migrations');const repo=repository();try{const safety=initializeSafety(repo),reconciled=repo.reconcileAll();return {safety,reconciled};}finally{repo.close();}}
async function discover(tokenInput:string){const token=await inspectErc20(rpc,getAddress(tokenInput));if(token.status==='unavailable')return token;const registry=await audited(),pools=await discoverV3Pools(rpc,registry,token.value.address);if(pools.status==='unavailable')return pools;const displayed=(await Promise.all(pools.value.map(p=>presentPool(rpc,p)))).filter((x):x is Extract<typeof x,{status:'available'}>=>x.status==='available');displayed.sort((a,b)=>(b.value.estimatedTvlUsd.status==='available'?b.value.estimatedTvlUsd.value:-1)-(a.value.estimatedTvlUsd.status==='available'?a.value.estimatedTvlUsd.value:-1));return {token,pools:displayed,provenance:pools.provenance};}
function forkArtifact(dbPath:string,tokenId:string,checkpoint?:string){const repo=new SqliteLedgerRepository(dbPath),positionId=`fork:${tokenId}`;try{if(checkpoint)return {positionId,checkpoint,pnl:repo.pnlSnapshot(`fork:${checkpoint}`,positionId)};return {positionId,totals:repo.collectionTotals(positionId),observed:repo.reconciliationDelta(positionId),secondPass:{newEvents:0,newDeposits:0,newPrincipal:0,newFees:0,pnlChange:0}};}finally{repo.close();}}
function staticRoute(deploymentVerified:boolean,emergencyPause=env.EMERGENCY_PAUSE){const wallet=dedicatedWallet(),base=staticCanaryReachability({executionEnabled:env.EXECUTION_ENABLED,dryRun:env.DRY_RUN,emergencyPause,liveCanaryEnabled:env.LIVE_CANARY_ENABLED,signerConfigured:wallet.signerConfigured,operatorConfigured:Boolean(process.env.TELEGRAM_ALLOWED_USER_IDS?.trim()),chainId:env.RH_CHAIN_ID,deploymentVerified}),db=repository();try{const budgetAvailable=db.canaryBudgetAvailable(),manualPause=db.safetyState()?.manualPause===true,reason=base.reason??(manualPause?'DURABLE_MANUAL_PAUSE':!budgetAvailable?'CANARY_BUDGET_UNAVAILABLE':undefined);return {...base,budgetAvailable,manualPause,executionReachable:reason===undefined,reason};}finally{db.close();}}
async function liveCanaryPreflight(){const repo=repository();try{const deployment=await audited(),wallet=await walletPreflight(deployment,repo),safety=safetyPayload(repo),execution=staticRoute(deployment.status==='available',safety.effectiveEmergencyPause);return {status:execution.executionReachable&&repo.canaryBudgetAvailable()?'GUARDED_ROUTE_REACHABLE':'NO_BROADCAST',chainId:env.RH_CHAIN_ID,wallet,deployment:deployment.status,safety,execution,budget:repo.canaryBudget(),requirements:{walletFunding:'evaluated per selected funding intent',budget:'one durable attempt claimed by final confirmation; no arm required',confirmedPreviews:'exact persisted pool plus fresh sequential simulation required'},checkedAt:new Date().toISOString()};}finally{repo.close();}}
function option(name:string){const index=process.argv.indexOf(name);return index>=0?process.argv[index+1]:undefined;}
async function safetyOperatorCommand():Promise<boolean>{
 const [cmd,...args]=process.argv.slice(2);
 if(!['safety-status','safety-pause','safety-resume'].includes(cmd??''))return false;
 const runtime={chainId:env.RH_CHAIN_ID,executionEnabled:env.EXECUTION_ENABLED,dryRun:env.DRY_RUN,emergencyPause:env.EMERGENCY_PAUSE},databasePath=runtimePaths.databasePath;
 if(cmd==='safety-status'){
  if(args.length)throw new Error('usage: safety-status');
  const repo=repository();try{out(safetyStatus({repo,runtime,databasePath}));return true;}finally{repo.close();}
 }
 if(args[0]!=='--confirm')throw new Error(`usage: ${cmd} --confirm <reason>`);
 const reason=args.slice(1).join(' ').trim();
 if(!reason)throw new Error(`usage: ${cmd} --confirm <reason>`);
 migrateSqlite(databasePath,'infra/migrations');
 out(setDurableManualPause({openRepository:path=>new SqliteLedgerRepository(path),databasePath,runtime,paused:cmd==='safety-pause',confirmed:true,reason,actor:cmd==='safety-pause'?'cli:safety-pause':'cli:safety-resume'}));
 return true;
}
async function rebalanceResumeCommand():Promise<boolean>{
 const [cmd,...args]=process.argv.slice(2);if(cmd!=='rebalance-resume')return false;
 if(args.length!==4||args[0]!=='--workflow-id'||args[2]!=='--confirm'||!args[1]||args[3]!==args[1])throw new Error('usage: rebalance-resume --workflow-id <id> --confirm <id>');
 const workflowId=args[1]!;migrateSqlite(runtimePaths.databasePath,'infra/migrations');const repo=repository();
 try{
  const workflow=rebalanceWorkflow(repo,workflowId);if(!workflow)throw new Error('REBALANCE_WORKFLOW_NOT_FOUND');assertRebalanceCommitmentNotPermanentlyReleased(repo,workflowId);if(String(workflow.state)!=='FAILED_RECOVERABLE')throw new Error('REBALANCE_WORKFLOW_NOT_RECOVERABLE');
  let resumeFrom:string|undefined;try{resumeFrom=JSON.parse(String(workflow.state_json)).resumeFrom;}catch{}if(!['CLOSE_STARTED','CLOSE_FULL_CONFIRMED','CLOSE_CONFIRMED','ASSETS_CLASSIFIED','SURPLUS_SWAP_STARTED','SURPLUS_SWAP_CONFIRMED','TOPUP_STARTED','TOPUP_CONFIRMED','FUNDING_SWAP_STARTED','FUNDING_SWAP_CONFIRMED','PRICE_REFRESHED','REOPEN_STARTED','REOPEN_CONFIRMED'].includes(String(resumeFrom)))throw new Error('REBALANCE_POST_CLOSE_RESUME_REQUIRED');
  const oldPositionId=String(workflow.old_position_id);if(!oldPositionId.startsWith('v4:'))throw new Error('REBALANCE_V4_POSITION_REQUIRED');const tokenId=BigInt(oldPositionId.slice(3));
  const closeBurn=repo.db.prepare("SELECT * FROM rebalance_transactions WHERE workflow_id=? AND semantic_stage='CLOSE_BURN' AND status='CONFIRMED' ORDER BY attempt DESC LIMIT 1").get(workflowId) as Record<string,unknown>|undefined;if(!closeBurn)throw new Error('REBALANCE_CONFIRMED_CLOSE_BURN_REQUIRED');
  if(workflow.replacement_position_id!==null)throw new Error('REBALANCE_REPLACEMENT_POSITION_EXISTS');
  const later=repo.db.prepare("SELECT workflow_id,semantic_stage,status,tx_hash FROM rebalance_transactions WHERE workflow_id=? AND status IN ('PREPARED','SUBMITTED','CONFIRMED') AND (created_at>? OR (created_at=? AND id<>?)) ORDER BY created_at").all(workflowId,String(closeBurn.created_at),String(closeBurn.created_at),String(closeBurn.id)) as Record<string,unknown>[];rebalanceResumeRecoveryCandidate(workflowId,later);
  try{await rpc.withClient(client=>client.readContract({address:V4_ROBINHOOD_DEPLOYMENTS.positionManager,abi:positionManagerAbi,functionName:'ownerOf',args:[tokenId]}),{stage:'rebalance_resume_guard',method:'PositionManager.ownerOf'});throw new Error('REBALANCE_OLD_NFT_STILL_MINTED');}catch(error){if(error instanceof Error&&error.message==='REBALANCE_OLD_NFT_STILL_MINTED')throw error;if(!/NOT_MINTED|revert/i.test(error instanceof Error?error.message:String(error)))throw error;}
  const wallet=dedicatedWallet(),safety=safetyPayload(repo),deployment=await auditRobinhoodV4Deployments(rpc);if(!wallet.address)throw new Error('DEDICATED_WALLET_REQUIRED');
  const runtime={executionEnabled:env.EXECUTION_ENABLED,dryRun:env.DRY_RUN,emergencyPause:Boolean(safety.effectiveEmergencyPause),authorized:true,signerConfigured:wallet.signerConfigured},blockers=rebalanceExecutionBlockers({...runtime,chainId:env.RH_CHAIN_ID,deploymentVerified:deployment.status==='available'});
  if(blockers.length)return out({status:'EXECUTION_BLOCKED',workflowId,blockers,safety,mainnetTransactionsSent:0}),true;
  const result=await executeV4Rebalance({repo,rpc,walletClient:guardedWalletClient(),wallet:wallet.address as Address,workflowId,runtime,limits:{maxTxGasUsd:env.MAX_GAS_COST_USD,maxLifecycleGasUsd:env.MAX_LIFECYCLE_GAS_USD,nativeUsd:Number.NaN,compoundUsd:env.MAX_REBALANCE_COMPOUND_VALUE_USD,approvalUsd:env.MAX_REBALANCE_APPROVAL_VALUE_USD,slippageBps:env.MAX_SLIPPAGE_BPS},internalRecovery:true});
  const current=rebalanceWorkflow(repo,workflowId)!;return out({workflowId,state:current.state,transactionHashes:repo.db.prepare('SELECT semantic_stage,status,tx_hash FROM rebalance_transactions WHERE workflow_id=? ORDER BY created_at').all(workflowId),replacementPositionId:current.replacement_position_id,safety:safetyPayload(repo),result}),true;
 }finally{repo.close();}
}
async function rebalanceCommitmentReleaseCommand():Promise<boolean>{
 const [cmd,...args]=process.argv.slice(2);if(cmd!=='rebalance-commitment-release')return false;
 if(args[0]!=='--workflow-id'||!args[1])throw new Error('usage: rebalance-commitment-release --workflow-id <id> [--confirm <one-time-token>]');
 const workflowId=args[1],confirm=args[2]==='--confirm'?args[3]:undefined;if(args.length!==2&&(!confirm||args.length!==4))throw new Error('usage: rebalance-commitment-release --workflow-id <id> [--confirm <one-time-token>]');
 const repo=repository();try{const current=await assertPermanentReleaseEligibility(repo,workflowId,rpc),expiry=Date.now()+5*60_000;
  if(!confirm)return out({status:'RELEASE_CONFIRMATION_REQUIRED',workflowId,oldPositionId:current.evidence.oldPositionId,state:current.evidence.state,revision:current.evidence.revision,derivedCommitmentUsd:current.releasedCommitmentUsd,sourceWallet:current.evidence.sourceWalletAddress,evidenceFingerprint:current.fingerprint,preparedReleaseProof:current.evidence.preparedReleaseProof,transactionSummary:{count:current.evidence.transactions.length},receiptSummary:{count:current.evidence.receipts.length},accountingSummary:{count:current.evidence.accounting.length},irreversibleEffect:'Excludes this historical replacement commitment from Robin execution exposure; workflow is permanently non-resumable.',expiresAt:new Date(expiry).toISOString(),command:`npm run cli -- rebalance-commitment-release --workflow-id ${workflowId} --confirm ${releaseConfirmationToken({workflowId,fingerprint:current.fingerprint,releasedCommitmentUsd:current.releasedCommitmentUsd,expiresAt:expiry})}`}),true;
  if(env.EXECUTION_ENABLED||!env.DRY_RUN||!env.EMERGENCY_PAUSE||repo.safetyState()?.manualPause!==true||safetyPayload(repo).effectiveEmergencyPause!==true)throw new Error('REBALANCE_COMMITMENT_RELEASE_SAFETY_GATES_REQUIRED');
  if(!verifyReleaseConfirmationToken(confirm,{workflowId,fingerprint:current.fingerprint,releasedCommitmentUsd:current.releasedCommitmentUsd}))throw new Error('REBALANCE_COMMITMENT_RELEASE_CONFIRMATION_INVALID');
  return out({status:'PERMANENTLY_RELEASED',marker:insertRebalanceCommitmentRelease(repo,{workflowId,operatorActor:'cli:rebalance-commitment-release',operatorReason:'permanent operator abandonment',current}),mainnetTransactionsSent:0}),true;
 }finally{repo.close();}
}
function fullyClosed(repo:SqliteLedgerRepository){return !env.EXECUTION_ENABLED&&env.DRY_RUN&&env.EMERGENCY_PAUSE&&repo.safetyState()?.manualPause===true&&safetyPayload(repo).effectiveEmergencyPause===true;}
async function exactHashReconcileCommand():Promise<boolean>{
 const [cmd,...args]=process.argv.slice(2);if(cmd!=='rebalance-exact-hash-reconcile')return false;
 if(args[0]!=='--workflow-id'||!args[1]||args[2]!=='--stage'||!args[3]||![4,6].includes(args.length)||args.length===6&&(args[4]!=='--confirm'||!args[5]))throw new Error('usage: rebalance-exact-hash-reconcile --workflow-id <id> --stage <stage> [--confirm <token>]');
 const workflowId=args[1],stage=args[3],confirm=args[5],repo=repository();try{const wallet=dedicatedWallet().address;if(!wallet)throw new Error('DEDICATED_WALLET_REQUIRED');const preview=await previewRebalanceExactHashReconciliation(repo,rpc,wallet as Address,workflowId,stage),expiresAt=Date.now()+5*60_000,tokenInput={workflowId:preview.workflowId,transactionRowId:preview.transactionRowId,semanticStage:preview.semanticStage,exactHash:preview.exactHash,nonce:preview.nonce,receiptBlock:preview.receiptBlock,receiptStatus:preview.receiptStatus,journalFingerprint:preview.journalFingerprint};
  if(!confirm)return out({...preview,receipt:undefined,status:'EXACT_HASH_RECONCILIATION_CONFIRMATION_REQUIRED',confirmationExpiresAt:new Date(expiresAt).toISOString(),command:`npm run cli -- rebalance-exact-hash-reconcile --workflow-id ${workflowId} --stage ${stage} --confirm ${exactHashReconcileToken({...tokenInput,expiresAt})}`,signingUsed:false,broadcastUsed:false}),true;
  if(!fullyClosed(repo))throw new Error('REBALANCE_EXACT_HASH_RECONCILE_SAFETY_GATES_REQUIRED');let valid=verifyExactHashReconcileToken(confirm,tokenInput);if(!valid&&preview.currentJournalState.transactionStatus==='CONFIRMED'&&preview.currentJournalState.lifecycleState==='RECONCILED'&&preview.currentJournalState.workflowState==='CLOSE_FULL_CONFIRMED'){try{const bound=JSON.parse(Buffer.from(confirm,'base64url').toString('utf8')) as {journalFingerprint?:string};valid=verifyExactHashReconcileToken(confirm,{...tokenInput,journalFingerprint:String(bound.journalFingerprint)});}catch{valid=false;}}if(!valid)throw new Error('REBALANCE_EXACT_HASH_RECONCILE_CONFIRMATION_INVALID');return out({...applyRebalanceExactHashReconciliation(repo,preview),signingUsed:false,broadcastUsed:false}),true;
 }finally{repo.close();}
}
async function errorSecretScrubCommand():Promise<boolean>{
 const [cmd,...args]=process.argv.slice(2);if(cmd!=='error-secret-scrub')return false;if(args.length!==0&&!(args.length===2&&args[0]==='--confirm'&&args[1]))throw new Error('usage: error-secret-scrub [--confirm <token>]');const repo=repository();try{const plan=errorSecretScrubPlan(repo),expiresAt=Date.now()+5*60_000,confirm=args[1];if(!confirm){const token=Buffer.from(JSON.stringify({kind:'ERROR_SECRET_SCRUB',fingerprint:plan.fingerprint,expiresAt})).toString('base64url');return out({status:'ERROR_SECRET_SCRUB_CONFIRMATION_REQUIRED',affectedTables:plan.counts,totalRows:plan.totalRows,confirmationExpiresAt:new Date(expiresAt).toISOString(),command:`npm run cli -- error-secret-scrub --confirm ${token}`,historicalLogs:'Follow docs/error-secret-scrub.md; never print matching lines.'}),true;}let value:Record<string,unknown>;try{value=JSON.parse(Buffer.from(confirm,'base64url').toString('utf8'));}catch{throw new Error('ERROR_SECRET_SCRUB_CONFIRMATION_INVALID');}if(!fullyClosed(repo))throw new Error('ERROR_SECRET_SCRUB_SAFETY_GATES_REQUIRED');if(value.kind!=='ERROR_SECRET_SCRUB'||value.fingerprint!==plan.fingerprint||Number(value.expiresAt)<=Date.now())throw new Error('ERROR_SECRET_SCRUB_CONFIRMATION_INVALID');return out({status:'ERROR_SECRET_SCRUB_APPLIED',...applyErrorSecretScrub(repo,plan.fingerprint)}),true;}finally{repo.close();}
}
async function reconcilePositionCommand():Promise<boolean>{
 const [cmd,positionId,...extra]=process.argv.slice(2);if(cmd!=='reconcile-position')return false;
 if(!positionId||extra.length)throw new Error('usage: reconcile-position <v4:<token-id>|live:<token-id>>');
 const match=/^(v4|live):([1-9][0-9]*)$/.exec(positionId);if(!match)throw new Error('RECONCILE_POSITION_ID_INVALID');
 const repo=repository();try{
  const safety=safetyStatus({repo,runtime:{chainId:env.RH_CHAIN_ID,executionEnabled:env.EXECUTION_ENABLED,dryRun:env.DRY_RUN,emergencyPause:env.EMERGENCY_PAUSE},databasePath:runtimePaths.databasePath});
  if(!safety.manualPause||safety.executionEnabled||!safety.dryRun||!safety.emergencyPause||!safety.effectiveEmergencyPause)throw new Error('RECONCILE_POSITION_SAFETY_CLOSED_REQUIRED');
  const position=repo.listPositions().find(row=>row.id===positionId);if(!position)throw new Error('RECONCILE_POSITION_NOT_FOUND');
  const protocol=match[1]==='v4'?'v4' as const:'v3' as const,status=enqueueTargetedPositionReconciliation(repo,{positionId,tokenId:position.token_id,protocol,reason:'OPERATOR_TARGETED_RECONCILIATION'});
  out({command:'reconcile-position',positionId,queueStatus:status,safetyVerified:true,signingUsed:false,broadcastUsed:false});return true;
 }finally{repo.close();}
}
async function v4PositionImportCommand():Promise<boolean>{
 const [cmd,tokenInput,...args]=process.argv.slice(2);if(cmd!=='v4-position-import')return false;
 if(!tokenInput||!/^([1-9][0-9]*)$/.test(tokenInput))throw new Error('usage: v4-position-import <token-id> [--apply --confirm v4-position-import:<token-id>]');
 const apply=args.includes('--apply'),confirmation=args[2];
 if((!apply&&args.length)||apply&&(!confirmation||args.length!==3||args[0]!=='--apply'||args[1]!=='--confirm'||confirmation!==`v4-position-import:${tokenInput}`))throw new Error('usage: v4-position-import <token-id> [--apply --confirm v4-position-import:<token-id>]');
 const wallet=dedicatedWallet().address;if(!wallet)throw new Error('DEDICATED_WALLET_REQUIRED');
 if(apply)migrateSqlite(runtimePaths.databasePath,'infra/migrations');
 const repo=repository();try{
  const safety=safetyStatus({repo,runtime:{chainId:env.RH_CHAIN_ID,executionEnabled:env.EXECUTION_ENABLED,dryRun:env.DRY_RUN,emergencyPause:env.EMERGENCY_PAUSE},databasePath:runtimePaths.databasePath}),closed=safety.manualPause&&!safety.executionEnabled&&safety.dryRun&&safety.emergencyPause&&safety.effectiveEmergencyPause;
  const result=await importKnownV4Position({repo,rpc,wallet,tokenId:BigInt(tokenInput),apply,confirmed:apply,safetyClosed:closed});
  const queueStatus=apply&&(result.status==='ADOPTED'||result.status==='METADATA_REPAIRED')&&result.positionId?enqueueTargetedPositionReconciliation(repo,{positionId:result.positionId,tokenId:tokenInput,protocol:'v4',reason:'OPERATOR_KNOWN_EXTERNAL_V4_IMPORT'}):'NOT_QUEUED';
  out({command:'v4-position-import',...result,queueStatus,safety:apply?{manualPause:safety.manualPause,executionEnabled:safety.executionEnabled,dryRun:safety.dryRun,emergencyPause:safety.emergencyPause,effectiveEmergencyPause:safety.effectiveEmergencyPause}:undefined});return true;
 }finally{repo.close();}
}
async function main(){const [cmd,arg,arg2,arg3,arg4,arg5,arg6]=process.argv.slice(2),dbPath=runtimePaths.databasePath,migrations='infra/migrations';if(cmd==='v3-swap-readiness'){const result=await diagnoseV3SwapReadiness(rpc);out(result);if(result.readinessStatus!=='available')process.exitCode=1;return;}if(cmd==='db-status')return out({paths:runtimePaths,...sqliteStatus(dbPath,migrations)});if(cmd==='db-migrate')return out({paths:runtimePaths,...migrateSqlite(dbPath,migrations)});if(cmd==='db-backup'){startup();return out(await backupSqlite(dbPath,runtimePaths.backupDir,env.BACKUP_RETENTION));}if(cmd==='db-restore-test'){if(!arg)throw new Error('usage: db-restore-test <backup-path>');const target=`${dbPath}.restore-test`;try{restoreSqliteBackup(arg,target);return out({restored:target,status:sqliteStatus(target,migrations)});}finally{ /* deliberately leave the restore artifact for inspection */ }}if(cmd==='fork-e2e')return out(await runForkE2E());if(cmd==='telegram-session-status'){migrateSqlite(dbPath,migrations);const repo=repository();try{if(!arg&&!arg2)return out({rows:repo.telegramFlowAudit(Date.now())});if(!arg||!arg2)throw new Error('usage: telegram-session-status [<user-id> <chat-id>]');return out({rows:repo.telegramFlowDiagnostics({userId:arg,chatId:arg2,now:Date.now()})});}finally{repo.close();}}
 if(cmd==='wallet-position-sync-audit'){const db=repository();try{return out(walletPositionSyncAudit(db));}finally{db.close();}}
 if(cmd==='active-position-reconciliation-audit'){const db=repository();try{return out(activePositionReconciliationAudit(db));}finally{db.close();}}
 if(cmd==='direct-lookup-queue-cleanup'){const db=repository();try{return out(cleanupLegacyDirectLookupFanout(db,arg==='--apply'));}finally{db.close();}}
 if(cmd==='position-adoption-audit'){if(!arg)throw new Error('usage: position-adoption-audit <tokenId>');const db=repository();try{return out(adoptionAudit(db,arg));}finally{db.close();}}
 if(cmd==='operational-open-intent-audit'){if(!arg)throw new Error('usage: operational-open-intent-audit <intentId>');const db=repository();try{return out(operationalOpenIntentAudit(db,arg));}finally{db.close();}}
 if(cmd==='wallet-position-sync'){const wallet=dedicatedWallet().address;if(!wallet)throw new Error('dedicated wallet is not configured');migrateSqlite(dbPath,migrations);const db=repository();try{return out(await syncWalletPositions({repo:db,readRpc:rpc,logsRpc,wallet,fromBlock:env.WALLET_POSITION_FROM_BLOCK}));}finally{db.close();}}
 if(cmd==='portfolio-audit'){const db=repository();try{return out(await buildPortfolioAudit({rpc,repo:db,wallet:dedicatedWallet().address}));}finally{db.close();}}
 if(cmd==='rebalance-policy-preview'){const mode=option('--mode') as 'REBALANCE'|'REBALANCE_COMPOUND'|undefined,p0=Number(option('--original-principal')),principal=Number(option('--recovered-principal')),fees=Number(option('--verified-fees')),funding=option('--funding')??'USDG';if(!mode)throw new Error('usage: rebalance-policy-preview --mode REBALANCE|REBALANCE_COMPOUND --original-principal <usd> --recovered-principal <usd> --verified-fees <usd> --funding USDG|WETH');return out({plan:calculateRebalancePlan({mode,originalPrincipalUsd:p0,recoveredPrincipalUsd:principal,verifiedFeesUsd:fees,compoundCapUsd:env.MAX_REBALANCE_COMPOUND_VALUE_USD,originalFundingSymbol:funding}),limits:{manualEntryUsd:env.MAX_POSITION_VALUE_USD,manualApprovalUsd:env.MAX_APPROVAL_VALUE_USD,compoundUsd:env.MAX_REBALANCE_COMPOUND_VALUE_USD,rebalanceApprovalUsd:env.MAX_REBALANCE_APPROVAL_VALUE_USD},readOnly:true,mainnetTransactionsSent:0});}
 if(cmd==='rebalance-audit'){const db=repository();try{const workflowId=arg,workflows:Record<string,unknown>[]=workflowId?[rebalanceWorkflow(db,workflowId)].filter((workflow):workflow is Record<string,unknown>=>Boolean(workflow)):db.db.prepare('SELECT * FROM rebalance_workflows ORDER BY created_at').all() as Record<string,unknown>[];return out({workflows:workflows.map(workflow=>({...workflow,transitions:rebalanceTransitions(db,String(workflow.id)),receipts:db.db.prepare('SELECT stage,tx_hash,confirmed_at FROM rebalance_receipts WHERE workflow_id=? ORDER BY confirmed_at').all(String(workflow.id)),accounting:db.db.prepare('SELECT kind,token_address,amount_raw,usd_value,price_source,price_block,observed_at,provenance_json FROM rebalance_accounting_events WHERE workflow_id=? ORDER BY observed_at').all(String(workflow.id))})),lineages:db.db.prepare('SELECT * FROM rebalance_lineages ORDER BY created_at').all(),mainnetTransactionsSent:0});}finally{db.close();}}
 if(cmd==='rebalance-dry-run-e2e'){const forkArtifact=option('--fork-artifact');if(!forkArtifact)throw new Error('usage: rebalance-dry-run-e2e --fork-artifact <v4-generic-fork-e2e.json>');return out(runRebalanceDryRunE2E({forkArtifactPath:forkArtifact,artifactDir:join(runtimePaths.dataDir,'fork-artifacts')}));}
 if(cmd==='v4-operational-open-e2e')return out(await runV4OperationalOpenE2E());
 if(cmd==='v4-rebalance-e2e')return out(await runV4RebalanceE2E());
 const runtime=startup();if(cmd==='v4-fork-e2e')return out(await runV4ForkE2E());if(cmd==='v4-lifecycle-e2e')return out(await runV4LifecycleE2E());if(cmd==='v4-generic-fork-e2e')return out(await runGenericV4ForkE2E());if(cmd==='v4-deployment-status')return out(await v4DeploymentStatus(rpc));
 if(cmd==='v4-pool-registry-status'){const db=repository();try{return out(await v4RegistryStatus({repo:db,rpc}));}finally{db.close();}}
 if(cmd==='v4-pool-registry-bootstrap'){if(!arg||!arg2)throw new Error('usage: v4-pool-registry-bootstrap <fromBlock> <toBlock> [windowSize]');const db=repository();try{return out(await bootstrapV4PoolRegistry({repo:db,rpc,fromBlock:BigInt(arg),toBlock:BigInt(arg2),windowSize:arg3?Number(arg3):undefined,onEvent:(name,data)=>process.stderr.write(JSON.stringify({event:name,...data})+'\n')}));}finally{db.close();}}
 if(cmd==='v4-pool-registry-sync'){const db=repository();try{const configuredWindow=option('--window');if(configuredWindow)db.configureV4RegistryCursor({windowSize:Number(configuredWindow)});return out(await syncV4PoolRegistry({repo:db,rpc,toBlock:arg&&!arg.startsWith('--')?BigInt(arg):undefined,onEvent:(name,data)=>process.stderr.write(JSON.stringify({event:name,...data})+'\n')}));}finally{db.close();}}
 if(cmd==='v4-pools-for-token'||cmd==='v4-pool-discover'){if(!arg)throw new Error(`usage: ${cmd} <token>`);const db=repository();try{return out(await v4PoolsForToken({repo:db,rpc,token:getAddress(arg),onEvent:(name,data)=>process.stderr.write(JSON.stringify({event:name,...data})+'\n')}));}finally{db.close();}}
 if(cmd==='v4-pool-refresh'){if(!arg)throw new Error('usage: v4-pool-refresh <poolId>');const db=repository();try{return out(await refreshV4RegistryPool({repo:db,rpc,poolId:arg}));}finally{db.close();}}
 if(cmd==='v4-pool-inspect'){if(!arg)throw new Error('usage: v4-pool-inspect <poolId>');const db=repository();try{const registered=db.v4RegistryPool(arg);if(registered)return out({registry:registered,state:await refreshV4RegistryPool({repo:db,rpc,poolId:arg})});return out(await v4PoolInspectById(rpc,arg));}finally{db.close();}}if(cmd==='v4-open-preflight'){if(!arg||!arg2||!arg3)throw new Error('usage: v4-open-preflight <target> <funding> <amountRaw> [poolId] [--upper-drop 0 --lower-drop 30]');const range={upperDropPct:Number(option('--upper-drop')??0),lowerDropPct:Number(option('--lower-drop')??10)};return out(await v4OpenPreflight(rpc,getAddress(arg),getAddress(arg2),BigInt(arg3),arg4,undefined,range));}if(cmd==='chain-audit'||cmd==='rpc-status')return out({chain:robinhoodMainnet,health:await rpc.health()});if(cmd==='deployment-audit'){if(arg==='--snapshot'){if(arg2!=='--rpc-url'||!arg3)throw new Error('usage: deployment-audit --snapshot --rpc-url http://127.0.0.1:<port>');return out(await auditRobinhoodV3Snapshot(new FallbackRpc({...robinhoodMainnet,rpcUrls:[arg3]})));}if(arg==='--live'||!arg)return out(await audited());throw new Error('usage: deployment-audit --snapshot --rpc-url <url> | deployment-audit --live');}
 if(cmd==='wallet-status')return out(await walletStatus());if(cmd==='wallet-preflight'){const funding=option('--funding'),amount=option('--amount'),target=option('--target');if(funding&&amount&&target){const report=await liveCanaryRoutePreflight({funding,amount,target:getAddress(target)});return out(report.readiness);}const repo=repository();try{return out(await walletPreflight(await audited(),repo));}finally{repo.close();}}if(cmd==='allowance-audit')return out(await allowanceAudit(await audited()));if(cmd==='live-canary-preflight'){const report=await liveCanaryPreflight();if(arg==='--json')return out(report);return human('Live canary preflight (read-only; no broadcast path)',report as Record<string,unknown>);}if(cmd==='live-canary-route-preflight'){const funding=option('--funding'),amount=option('--amount'),target=option('--target');if(!funding||!amount||!target)throw new Error('usage: live-canary-route-preflight --funding USDG|WETH --amount <decimal> --target <address>');return out(await liveCanaryRoutePreflight({funding,amount,target:getAddress(target)}));}
 if(cmd==='sequential-approval-sim'){if(!arg||!arg2||!arg3||!arg4||!arg5||!arg6)throw new Error('usage: sequential-approval-sim <pool> <target> <funding> <fundingAmountRaw> <upperDropPct> <lowerDropPct>');const wallet=dedicatedWallet().address;if(!wallet)throw new Error('dedicated wallet is not configured');const [target,funding]=await Promise.all([inspectErc20(rpc,getAddress(arg2)),inspectErc20(rpc,getAddress(arg3))]);if(target.status==='unavailable')throw new Error(`target inspection failed: ${target.reason}`);if(funding.status==='unavailable')throw new Error(`funding inspection failed: ${funding.reason}`);return out(await sequentialApprovalMintSimulation({wallet,pool:getAddress(arg),target:{address:target.value.address,symbol:target.value.symbol,decimals:target.value.decimals},funding:{address:funding.value.address,symbol:funding.value.symbol,decimals:funding.value.decimals},fundingAmount:BigInt(arg4),upperDropPct:Number(arg5),lowerDropPct:Number(arg6),slippageBps:env.MAX_SLIPPAGE_BPS,deadlineSeconds:env.CONFIRMATION_TTL_SECONDS,upstreamUrl:env.RH_RPC_URL,artifactRoot:join(runtimePaths.dataDir,'fork-artifacts')}));}
 if(cmd==='token-inspect'){if(!arg)throw new Error('usage: token-inspect <address>');return out(await inspectErc20(rpc,getAddress(arg)));}if(cmd==='pool-inspect'){if(!arg)throw new Error('usage: pool-inspect <pool>');const p=await inspectV3Pool(rpc,getAddress(arg));return out(p.status==='available'?await presentPool(rpc,p.value):p);}if(cmd==='pool-discover'){if(!arg)throw new Error('usage: pool-discover <token>');return out(await discover(arg));}if(cmd==='wallet-positions'){const wallet=arg?getAddress(arg):dedicatedWallet().address;if(!wallet||!arg2&&!env.WALLET_POSITION_FROM_BLOCK)throw new Error('usage: wallet-positions [wallet] <fromBlock>; configure WALLET_POSITION_FROM_BLOCK for dedicated wallet');const from=arg?BigInt(arg2!):env.WALLET_POSITION_FROM_BLOCK!;return out(await walletV3Positions(rpc,await audited(),wallet,from));}if(cmd==='position-inspect'){if(!arg)throw new Error('usage: position-inspect <tokenId>');const registry=await audited(),position=await inspectV3Position(rpc,registry,BigInt(arg));if(position.status==='unavailable')return out(position);const wallet=dedicatedWallet().address;return out({position:await presentPosition(rpc,position.value),unclaimedFees:wallet?await simulateUnclaimedFees(rpc,registry,position.value,wallet):{status:'unavailable',reason:'configure dedicated wallet for authorized collect eth_call'}});}
 if(cmd==='bot-preflight'){const repo=repository();try{const [v3,v4]=await Promise.all([audited(),v4DeploymentStatus(rpc)]);return out({paths:runtimePaths,runtime,deploymentAudit:{v3:deploymentVerdict(v3),v4:v4.status==='available'?v4:((v4.details as {verification?:unknown}|undefined)?.verification??v4)},preflight:await walletPreflight(v3,repo),mainnetTransactionsSent:0});}finally{repo.close();}}if(cmd==='execution-preflight'){const d=await audited();return out({deploymentAudit:deploymentVerdict(d),gate:canExecuteV3(d,env.EXECUTION_ENABLED,env.DRY_RUN,safetyPayload().effectiveEmergencyPause),limits:{positionUsd:env.MAX_POSITION_VALUE_USD,approvalUsd:env.MAX_APPROVAL_VALUE_USD,gasUsd:env.MAX_GAS_COST_USD,slippageBps:env.MAX_SLIPPAGE_BPS},noBroadcast:true});}
 if(cmd==='reconcile-all'){const repo=repository();try{return out({reconciled:repo.reconcileAll(),pendingTransactions:repo.pendingTransactions()});}finally{repo.close();}}if(cmd==='runtime-status'){const repo=repository();try{const [deployment,v4Deployment]=await Promise.all([audited(),v4DeploymentStatus(rpc)]),safety=safetyPayload(repo),route=staticRoute(deployment.status==='available',safety.effectiveEmergencyPause),wallet=await walletStatus();return out({paths:runtimePaths,safety,wallet,deploymentAudit:{v3:deploymentVerdict(deployment),v4:v4Deployment.status==='available'?v4Deployment:((v4Deployment.details as {verification?:unknown}|undefined)?.verification??v4Deployment)},migration:sqliteStatus(dbPath,migrations),reconciliation:repo.reconcileAll(),pendingTransactions:repo.pendingTransactions(),executionReachable:route.executionReachable,executionRoute:route,v4LiveCanary:{state:repo.v4LiveCanary(),flags:{EXECUTION_ENABLED:env.EXECUTION_ENABLED,DRY_RUN:env.DRY_RUN,EMERGENCY_PAUSE:env.EMERGENCY_PAUSE,V4_LIVE_CANARY_ENABLED:env.V4_LIVE_CANARY_ENABLED},limits:{perTransactionGasUsd:env.V4_CANARY_MAX_TX_GAS_USD,lifecycleGasUsd:env.V4_CANARY_TOTAL_GAS_BUDGET_USD},executor:'executeV4LiveCanaryOpen / executeV4LiveCanaryClose'}});}finally{repo.close();}}
 if(cmd==='dry-run-add-liquidity'){if(!arg||!arg2||!arg3||!arg4)throw new Error('usage: dry-run-add-liquidity <token> <wallet> <amount0Raw> <amount1Raw>');const found=await discover(arg);if(!('pools'in found)||!found.pools.length)return out({status:'unavailable',reason:'no validated canonical-quote v3 pool'});const p=found.pools[0].value,range=rangeFromPercent(p.priceToken1PerToken0,5,p.token0.decimals,p.token1.decimals,p.pool.tickSpacing),quote=balancedRangeQuote(p.pool,range.tickLower,range.tickUpper,BigInt(arg3),BigInt(arg4)),d=await audited();if(d.status==='unavailable')return out(d);const wallet=getAddress(arg2),deadline=BigInt(Math.floor(Date.now()/1000)+600),mint=buildMint(d.value,{token0:p.token0.address,token1:p.token1.address,fee:p.pool.fee,tickLower:range.tickLower,tickUpper:range.tickUpper,amount0Desired:quote.requiredAmount0,amount1Desired:quote.requiredAmount1,amount0Min:quote.requiredAmount0*(10_000n-BigInt(env.MAX_SLIPPAGE_BPS))/10_000n,amount1Min:quote.requiredAmount1*(10_000n-BigInt(env.MAX_SLIPPAGE_BPS))/10_000n,recipient:wallet,deadline}),a0=buildApproval(p.token0.address,d.value.positionManager,quote.requiredAmount0),a1=buildApproval(p.token1.address,d.value.positionManager,quote.requiredAmount1);return out({simulation:'non-broadcast',currentBlock:quote.currentBlock,range,quote,mintCalldata:mint,mintSimulation:await simulateBuiltTransaction(rpc,wallet,mint),approval0:await simulateApproval(rpc,wallet,a0),approval1:await simulateApproval(rpc,wallet,a1),gate:canExecuteV3(d,env.EXECUTION_ENABLED,env.DRY_RUN,safetyPayload().effectiveEmergencyPause)});}
 throw new Error('commands: db-migrate db-status db-backup db-restore-test reconcile-all runtime-status wallet-status wallet-preflight allowance-audit live-canary-preflight live-canary-route-preflight bot-preflight execution-preflight fork-e2e guarded-canary-e2e v4-fork-e2e v4-lifecycle-e2e');}
async function forkArtifactCommand():Promise<boolean>{const [cmd,tokenId,checkpoint]=process.argv.slice(2),dbPath=process.env.SQLITE_PATH;if(!dbPath||!tokenId)return false;if(cmd==='position-inspect'){out(forkArtifact(dbPath,tokenId));return true;}if(cmd==='position-reconcile'){out(forkArtifact(dbPath,tokenId));return true;}if(cmd==='pnl-audit'){if(!checkpoint)throw new Error('usage: pnl-audit <forkTokenId> <afterMint|afterFeeCollect|afterPartialClose|afterFullClose>');out(forkArtifact(dbPath,tokenId,checkpoint));return true;}return false;}
async function canaryOperatorCommand():Promise<boolean>{const [cmd,arg,arg2]=process.argv.slice(2);if(!['canary-budget-status','canary-budget-reset','canary-status','canary-log-audit','position-reconcile','pnl-audit'].includes(cmd??''))return false;migrateSqlite(runtimePaths.databasePath,'infra/migrations');const repo=repository();try{if(cmd==='canary-budget-status'||cmd==='canary-status'){const last=repo.db.prepare('SELECT * FROM canary_execution_intents ORDER BY created_at DESC LIMIT 1').get();out({budget:repo.canaryBudget(),manualPause:repo.safetyState()?.manualPause===true,lastIntent:last??null,limits:{maxPositionUsd:5,maxApprovalUsd:5,maxAttempts:1}});return true;}if(cmd==='canary-budget-reset'){if(arg==='--confirm'&&arg2){if(!repo.resetCanaryBudget(arg2))throw new Error('invalid or expired one-time reset token');out({status:'MANUALLY_RESET',budget:repo.canaryBudget(),manualPause:repo.safetyState()?.manualPause===true});return true;}const request=repo.requestCanaryBudgetReset();out({status:'RESET_CONFIRMATION_REQUIRED',expiresAt:request.expiresAt,command:`npm run cli -- canary-budget-reset --confirm ${request.token}`});return true;}if(cmd==='canary-log-audit'){const intent=repo.db.prepare('SELECT * FROM canary_execution_intents ORDER BY created_at DESC LIMIT 1').get() as Record<string,unknown>|undefined;out({budget:repo.canaryBudget(),intent:intent??null,transitions:intent?repo.canaryIntentTransitions(String(intent.id)):[],receipts:intent?repo.db.prepare('SELECT tx_hash,reconciled_at FROM transaction_receipts WHERE intent_id=? ORDER BY rowid').all(String(intent.id)):[]});return true;}if(!arg)throw new Error(`usage: ${cmd} <tokenId>`);const positionId=`live:${arg}`;if(cmd==='position-reconcile'){const result=repo.reconcileAll().find(row=>row.positionId===positionId);out({tokenId:arg,reconciliation:result??'position not enrolled'});return true;}out({tokenId:arg,strategy:repo.strategyPosition(positionId),accounting:repo.positionAccounting(positionId),pnlSnapshots:repo.db.prepare('SELECT id,payload_json,created_at FROM pnl_snapshots WHERE position_id=? ORDER BY created_at').all(positionId)});return true;}finally{repo.close();}}
async function v4OperatorCommand():Promise<boolean>{const [cmd,arg]=process.argv.slice(2),commands=['v4-position-inspect','v4-position-reconcile','v4-position-collect-preflight','v4-position-partial-close-preflight','v4-position-full-close-preflight','v4-pnl-audit','v4-position-lifecycle-audit'];if(!commands.includes(cmd??''))return false;if(!arg)throw new Error(`usage: ${cmd} <tokenId>`);migrateSqlite(runtimePaths.databasePath,'infra/migrations');const db=repository(),tokenId=BigInt(arg);try{if(cmd==='v4-position-inspect')out(await v4PositionInspect(rpc,db,tokenId));else if(cmd==='v4-position-reconcile')out(await v4PositionReconcile(rpc,db,tokenId));else if(cmd==='v4-pnl-audit')out(v4PnlAudit(db,tokenId));else if(cmd==='v4-position-lifecycle-audit')out(v4LifecycleAudit(db,tokenId));else{const wallet=dedicatedWallet().address;if(!wallet)throw new Error('dedicated wallet is not configured');const percent=Number(option('--percent')??50) as 25|50|75;if(cmd==='v4-position-partial-close-preflight'&&![25,50,75].includes(percent))throw new Error('percent must be 25, 50, or 75');const action=cmd==='v4-position-collect-preflight'?'collect':cmd==='v4-position-full-close-preflight'?'full_close':'partial_close';out(await v4LifecyclePreflight(rpc,db,wallet,tokenId,action,action==='partial_close'?percent:undefined));}return true;}finally{db.close();}}
async function v4LiveOperatorCommand():Promise<boolean>{const [cmd,arg]=process.argv.slice(2),commands=['v4-live-canary-status','v4-live-open-preflight','v4-live-position-audit','v4-live-close-preflight','v4-live-canary-log-audit'];if(!commands.includes(cmd??''))return false;migrateSqlite(runtimePaths.databasePath,'infra/migrations');const db=repository();try{const wallet=dedicatedWallet();const limits={...defaultV4LiveLimits,maxTxGasUsd:env.V4_CANARY_MAX_TX_GAS_USD,totalGasUsd:env.V4_CANARY_TOTAL_GAS_BUDGET_USD,nativeUsd:env.GAS_USD_PER_NATIVE};const runtime={executionEnabled:env.EXECUTION_ENABLED,dryRun:env.DRY_RUN,emergencyPause:env.EMERGENCY_PAUSE,v4LiveCanaryEnabled:env.V4_LIVE_CANARY_ENABLED,signerConfigured:wallet.signerConfigured,allowlisted:Boolean(process.env.TELEGRAM_ALLOWED_USER_IDS?.trim())};if(cmd==='v4-live-canary-status'){out({canary:db.v4LiveCanary(),gas:db.v4LiveGas(),limits,flags:{EXECUTION_ENABLED:env.EXECUTION_ENABLED,DRY_RUN:env.DRY_RUN,EMERGENCY_PAUSE:env.EMERGENCY_PAUSE,V4_LIVE_CANARY_ENABLED:env.V4_LIVE_CANARY_ENABLED},exactPool:{id:V4_LIVE_POOL_ID,key:V4_LIVE_POOL_KEY}});return true;}if(cmd==='v4-live-open-preflight'){if(!wallet.address)throw new Error('dedicated wallet is not configured');const target=option('--target'),funding=option('--funding'),amount=option('--amount'),selected=option('--pool-id');if(!target||!funding||!amount||!selected)throw new Error('usage: v4-live-open-preflight --target <WETH> --funding USDG --amount 5 --pool-id <full PoolId> [--upper-drop 0 --lower-drop 30]');if(target.toLowerCase()!==V4_LIVE_POOL_KEY.currency0.toLowerCase()||funding.toUpperCase()!=='USDG'||amount!=='5'||selected.toLowerCase()!==V4_LIVE_POOL_ID)throw new Error('V4_LIVE_OPEN_INTENT_MISMATCH');const range={upperDropPct:Number(option('--upper-drop')??0),lowerDropPct:Number(option('--lower-drop')??10)};out(await v4LiveOpenPreflight({repo:db,rpc,wallet:wallet.address,runtime,limits,range}));return true;}if(!arg)throw new Error(`usage: ${cmd} <tokenId>`);const tokenId=BigInt(arg);if(cmd==='v4-live-position-audit'){const position=await v4PositionInspect(rpc,db,tokenId);out({canary:db.v4LiveCanary(),position,pnl:v4PnlAudit(db,tokenId),gas:db.v4LiveGas()});}else if(cmd==='v4-live-close-preflight')out({canary:db.v4LiveCanary(),preflight:await v4LifecyclePreflight(rpc,db,wallet.address!,tokenId,'full_close'),burnAfterClose:true,gasSpentUsd:db.v4LiveCanary().gas_spent_usd,limits});else out({canary:db.v4LiveCanary(),openIntent:db.v4LiveOpenIntent(String(db.v4LiveCanary().open_intent_id??'')),openTransitions:db.v4LiveTransitions(String(db.v4LiveCanary().open_intent_id??'')),lifecycle:db.v4LifecycleHistory(tokenId),gas:db.v4LiveGas()});return true;}finally{db.close();}}
const guardedCommand=process.argv[2]==='guarded-canary-e2e';
async function dispatch(){
 if(guardedCommand){if(process.argv[3]==='--help')out({usage:'guarded-canary-e2e (local pinned Anvil only)'});else out(await runGuardedCanaryE2E());return;}
 if(await exactHashReconcileCommand()||await errorSecretScrubCommand()||await reconcilePositionCommand()||await v4PositionImportCommand()||await rebalanceCommitmentReleaseCommand()||await rebalanceResumeCommand()||await safetyOperatorCommand()||await canaryOperatorCommand()||await forkArtifactCommand()||await v4LiveOperatorCommand()||await v4OperatorCommand())return;
 await main();
}
void dispatch().catch(e=>{process.stderr.write(JSON.stringify({level:'error',message:sanitizeRpcError(e,{stage:'cli_dispatch',method:'operator_command'})})+'\n');process.exitCode=1;});
