import { getAddress, keccak256, toHex, zeroAddress, type Address } from 'viem';
import { FallbackRpc, chainProfile, inspectErc20, inspectV3Pool, orientChainQuote, priceFromSqrtX96, protocolDeployment, type ChainRuntimeConfig } from '@funi/core';
import { SqliteLedgerRepository } from '@funi/ledger';
import { verifyV3ProtocolRoles, type GuardedV3Chain, type GuardedV3Protocol } from '@funi/v3';
import { acquireBscLegacyFeeEvidence, acquireEthereumEip1559FeeEvidence, derivedFeeEvidencePolicy, estimateGuardedV3LifecycleGas, type GuardedV3GasStage } from './v3-multichain-executor.js';
import { canonicalDeploymentVerification, type CanonicalDeploymentVerificationEvidence } from './multichain-runtime.js';

export type GuardedLiveReadinessState='READ_ONLY_READY'|'SIMULATION_READY'|'GUARDED_LIVE_CODE_READY'|'GUARDED_LIVE_CONFIGURATION_BLOCKED'|'GUARDED_LIVE_EVIDENCE_BLOCKED'|'UNSUPPORTED';
export type SimulationProofState='FORK_VERIFIED'|'RPC_SIMULATION_VERIFIED'|'SIMULATION_PARTIALLY_VERIFIED'|'SIMULATION_BLOCKED_BY_PROVIDER_CAPABILITY';

export type GuardedLiveReadinessInput={
 chainId:number;protocol:string;supported:boolean;readOnlyReady:boolean;simulationProof?:SimulationProofState;
 enabled:boolean;executionEnabled:boolean;dryRun:boolean;emergencyPause:boolean;deploymentVerified:boolean;providerHealthy:boolean;walletConfigured:boolean;
 walletBalanceVerified:boolean;gasPolicyValid:boolean;nativeGasSufficient:boolean;feeEvidenceFresh:boolean;priceEvidenceFresh:boolean;
 unresolvedChainTransactions:number;nonceMutexEmpty:boolean;previewBound:boolean;authorizationBound:boolean;
};

export function guardedLiveReadiness(input:GuardedLiveReadinessInput){
 if(!input.supported)return {state:'UNSUPPORTED' as const,blockers:['PROTOCOL_UNSUPPORTED']};
 if(!input.readOnlyReady)return {state:'GUARDED_LIVE_EVIDENCE_BLOCKED' as const,blockers:['READ_ONLY_RUNTIME_NOT_READY']};
 const configuration:string[]=[];if(!input.enabled)configuration.push('CHAIN_DISABLED');if(!input.executionEnabled)configuration.push('CHAIN_EXECUTION_DISABLED');if(input.dryRun)configuration.push('CHAIN_DRY_RUN_ENABLED');if(input.emergencyPause)configuration.push('CHAIN_EMERGENCY_PAUSE');if(!input.walletConfigured)configuration.push('CHAIN_WALLET_REQUIRED');if(!input.gasPolicyValid)configuration.push('CHAIN_GAS_POLICY_REQUIRED');
 const evidence:string[]=[];if(!input.deploymentVerified)evidence.push('DEPLOYMENT_RUNTIME_NOT_VERIFIED');if(!input.providerHealthy)evidence.push('PROVIDER_CHAIN_ID_UNVERIFIED');if(!input.walletBalanceVerified)evidence.push('CHAIN_WALLET_BALANCE_UNVERIFIED');if(!input.nativeGasSufficient)evidence.push('CHAIN_NATIVE_GAS_INSUFFICIENT_OR_UNKNOWN');if(!input.feeEvidenceFresh)evidence.push('FEE_EVIDENCE_STALE_OR_UNAVAILABLE');if(!input.priceEvidenceFresh)evidence.push('PRICE_EVIDENCE_STALE_OR_UNAVAILABLE');if(input.unresolvedChainTransactions>0)evidence.push('CHAIN_UNRESOLVED_TRANSACTION');if(!input.nonceMutexEmpty)evidence.push('CHAIN_NONCE_MUTEX_HELD');if(!input.previewBound)evidence.push('PREVIEW_CHAIN_BINDING_REQUIRED');if(!input.authorizationBound)evidence.push('CHAIN_AUTHORIZATION_INVALID');
 const proofVerified=input.simulationProof==='FORK_VERIFIED'||input.simulationProof==='RPC_SIMULATION_VERIFIED';if(!input.simulationProof||input.simulationProof==='SIMULATION_BLOCKED_BY_PROVIDER_CAPABILITY')evidence.push('EXACT_ACTION_SIMULATION_PROOF_REQUIRED');
 if(!input.simulationProof||input.simulationProof==='SIMULATION_BLOCKED_BY_PROVIDER_CAPABILITY')return {state:'READ_ONLY_READY' as const,blockers:[...configuration,...evidence]};
 if(input.simulationProof==='SIMULATION_PARTIALLY_VERIFIED')return {state:'SIMULATION_READY' as const,blockers:[...configuration,...evidence]};
 if(configuration.length)return {state:'GUARDED_LIVE_CONFIGURATION_BLOCKED' as const,blockers:[...configuration,...evidence]};
 if(evidence.length)return {state:proofVerified?'GUARDED_LIVE_EVIDENCE_BLOCKED' as const:'SIMULATION_READY' as const,blockers:evidence};
 return {state:'GUARDED_LIVE_CODE_READY' as const,blockers:[] as string[]};
}

export function configuredChainWallet(chainId:GuardedV3Chain,env:NodeJS.ProcessEnv=process.env):Address|undefined{
 const prefix=chainId===56?'BSC':'ETHEREUM',raw=env[`${prefix}_WALLET_ADDRESS`]??env.OPERATOR_WALLET??env.DEDICATED_WALLET_ADDRESS??env.WALLET_ADDRESS;if(!raw?.trim())return undefined;try{return getAddress(raw.trim());}catch{throw new Error(`${prefix}_WALLET_ADDRESS_INVALID`);}
}

const nftBalanceAbi=[{type:'function',name:'balanceOf',stateMutability:'view',inputs:[{type:'address'}],outputs:[{type:'uint256'}]}] as const;
const decimalsAbi=[{type:'function',name:'decimals',stateMutability:'view',inputs:[],outputs:[{type:'uint8'}]}] as const;
const revision=(value:unknown)=>keccak256(toHex(JSON.stringify(value,(_,item)=>typeof item==='bigint'?item.toString():item)));
export async function verifyChainWallet(input:{rpc:FallbackRpc;repo:SqliteLedgerRepository;chainId:GuardedV3Chain;protocol:GuardedV3Protocol;wallet?:Address;nowMs?:number}){
 const base={chainId:input.chainId,walletConfigured:Boolean(input.wallet),signerAccessed:false,signerConstructed:false};if(!input.wallet)return {...base,status:'CONFIGURATION_BLOCKED' as const,blockers:['CHAIN_WALLET_REQUIRED']};
 const health=await input.rpc.health(),correct=health.filter(item=>item.healthy&&item.chainId===input.chainId);if(!correct.length)return {...base,status:'BLOCKED' as const,blockers:['PROVIDER_CHAIN_ID_UNVERIFIED']};
 const nowMs=input.nowMs??Date.now(),settled=await Promise.allSettled(input.rpc.clients.map(async client=>{const [chainId,latest,pending,balance,block]=await Promise.all([client.getChainId(),client.getTransactionCount({address:input.wallet!,blockTag:'latest'}),client.getTransactionCount({address:input.wallet!,blockTag:'pending'}),client.getBalance({address:input.wallet!}),client.getBlockNumber()]);if(chainId!==input.chainId)throw new Error('CHAIN_WALLET_EVIDENCE_WRONG_CHAIN');return {latest,pending,balance,block};})),values=settled.flatMap(item=>item.status==='fulfilled'?[item.value]:[]);if(!values.length)return {...base,status:'BLOCKED' as const,blockers:['CHAIN_WALLET_STATE_UNAVAILABLE']};
 const nonceAgreement=new Set(values.map(item=>`${item.latest}:${item.pending}`)).size===1,balanceAgreement=new Set(values.map(item=>item.balance.toString())).size===1,latestNonce=values[0]!.latest,pendingNonce=values[0]!.pending,nativeBalance=values.reduce((a,b)=>a<b.balance?a:b.balance,values[0]!.balance),deployment=protocolDeployment(input.chainId,input.protocol),ownedNftCount=await input.rpc.withClient(client=>client.readContract({address:deployment.contracts.positionManager!,abi:nftBalanceAbi,functionName:'balanceOf',args:[input.wallet!]}),{stage:'chain_wallet_status',method:'PositionManager.balanceOf',requiredCapabilities:['eth_call']});
 const unresolved=input.repo.unresolvedChainTransactions(input.chainId,input.wallet),nonceMutexHeld=Boolean(input.repo.db.prepare('SELECT 1 FROM chain_nonce_mutex WHERE chain_id=? AND lower(wallet_address)=? AND expires_at>?').get(input.chainId,input.wallet.toLowerCase(),new Date(nowMs).toISOString())),blockers:string[]=[];if(!nonceAgreement)blockers.push('CHAIN_NONCE_PROVIDER_DISAGREEMENT');if(latestNonce!==pendingNonce)blockers.push('CHAIN_PENDING_NONCE_IN_FLIGHT');if(!balanceAgreement)blockers.push('CHAIN_BALANCE_PROVIDER_DISAGREEMENT');if(unresolved)blockers.push('CHAIN_UNRESOLVED_TRANSACTION');if(nonceMutexHeld)blockers.push('CHAIN_NONCE_MUTEX_HELD');const observedBlock=values.map(item=>item.block).reduce((a,b)=>a<b?a:b),freshUntilMs=nowMs+Math.max(5_000,chainProfile(input.chainId).expectedBlockTimeMs*4),nonceEvidenceHealthy=nonceAgreement&&latestNonce===pendingNonce&&!unresolved&&!nonceMutexHeld, walletEvidenceRevision=revision({chainId:input.chainId,wallet:input.wallet,latestNonce,pendingNonce,nativeBalance,observedBlock,nowMs,unresolved,nonceMutexHeld});
 return {...base,status:blockers.length?'BLOCKED' as const:'VERIFIED' as const,wallet:input.wallet,providerChainCorrect:true,providerCount:values.length,latestNonce,pendingNonce,nativeBalance,ownedNftCount,unresolvedChainTransactions:unresolved,nonceMutexEmpty:!nonceMutexHeld,nonceEvidenceHealthy,observedBlock,observedAtMs:nowMs,freshUntilMs,walletEvidenceRevision,blockers};
}

const positive=(env:NodeJS.ProcessEnv,key:string)=>{const raw=env[key];if(raw===undefined||raw.trim()==='')return undefined;const value=Number(raw);if(!Number.isFinite(value)||value<=0)throw new Error(`CONFIG_INVALID:${key}`);return value;};
const positiveBig=(env:NodeJS.ProcessEnv,key:string)=>{const raw=env[key];if(raw===undefined||raw.trim()==='')return undefined;const value=BigInt(raw);if(value<=0n)throw new Error(`CONFIG_INVALID:${key}`);return value;};

export function nativeUsdFromVerifiedPool(input:{chainId:GuardedV3Chain;protocol:GuardedV3Protocol;token0:Address;token1:Address;sqrtPriceX96:bigint;token0Decimals:number;token1Decimals:number;observedBlock:bigint;observedAtMs:number;nowMs?:number;maxAgeMs?:number}){
 const profile=chainProfile(input.chainId),nowMs=input.nowMs??Date.now(),maxAgeMs=input.maxAgeMs??Math.max(5_000,profile.expectedBlockTimeMs*4),stable=profile.quoteTokens.find(token=>token.stable&&(token.address.toLowerCase()===input.token0.toLowerCase()||token.address.toLowerCase()===input.token1.toLowerCase()));if(!stable)throw new Error('NATIVE_USD_STABLE_TOKEN_IDENTITY_INVALID');const wrapped=profile.wrappedNativeAddress,wrappedIs0=input.token0.toLowerCase()===wrapped.toLowerCase(),wrappedIs1=input.token1.toLowerCase()===wrapped.toLowerCase();if(!wrappedIs0&&!wrappedIs1)throw new Error('NATIVE_USD_WRAPPED_NATIVE_ORIENTATION_INVALID');if(wrappedIs0&&input.token1.toLowerCase()!==stable.address.toLowerCase()||wrappedIs1&&input.token0.toLowerCase()!==stable.address.toLowerCase())throw new Error('NATIVE_USD_TOKEN_ORIENTATION_INVALID');const expected0=wrappedIs0?profile.nativeDecimals:stable.decimals,expected1=wrappedIs1?profile.nativeDecimals:stable.decimals;if(input.token0Decimals!==expected0||input.token1Decimals!==expected1)throw new Error('NATIVE_USD_TOKEN_DECIMALS_INVALID');if(input.sqrtPriceX96<=0n)throw new Error('NATIVE_USD_POOL_PRICE_INVALID');const ageMs=nowMs-input.observedAtMs;if(ageMs<0||ageMs>maxAgeMs)throw new Error('NATIVE_USD_POOL_PRICE_STALE');const price1Per0=priceFromSqrtX96(input.sqrtPriceX96,input.token0Decimals,input.token1Decimals),oriented=orientChainQuote({chainId:input.chainId,token0:input.token0,token1:input.token1,token0Decimals:input.token0Decimals,token1Decimals:input.token1Decimals,price1Per0,baseToken:wrapped,quoteToken:stable.address}),nativeUsd=oriented.quotePerBase;if(!Number.isFinite(nativeUsd)||nativeUsd<0.01||nativeUsd>10_000_000)throw new Error('NATIVE_USD_VALUE_IMPLAUSIBLE');return {status:'AVAILABLE' as const,chainId:input.chainId,protocol:input.protocol,nativeUsd,priceSource:`verified ${input.protocol} wrapped-native/stable pool`,stableSymbol:stable.symbol,observedBlock:input.observedBlock,observedAtMs:input.observedAtMs,freshUntilMs:input.observedAtMs+maxAgeMs,orientation:oriented.orientation,evidenceRevision:revision({chainId:input.chainId,protocol:input.protocol,wrapped,stable:stable.address,nativeUsd,observedBlock:input.observedBlock,observedAtMs:input.observedAtMs})};
}

export async function runtimeNativeUsdValuation(input:{rpc:FallbackRpc;chainId:GuardedV3Chain;protocol:GuardedV3Protocol;deploymentEvidence:CanonicalDeploymentVerificationEvidence;nowMs?:number}){
 const nowMs=input.nowMs??Date.now(),market=input.deploymentEvidence.marketPool;if(input.deploymentEvidence.status!=='VERIFIED'||!market)return {status:'UNAVAILABLE' as const,reason:'VERIFIED_NATIVE_STABLE_POOL_EVIDENCE_UNAVAILABLE'};try{const address=getAddress(String(market.pool)),pool=await inspectV3Pool(input.rpc,address);if(pool.status==='unavailable')throw new Error('NATIVE_USD_POOL_STATE_UNAVAILABLE');const deployment=protocolDeployment(input.chainId,input.protocol);if(pool.value.factory.toLowerCase()!==deployment.contracts.factory!.toLowerCase())throw new Error('NATIVE_USD_POOL_FACTORY_INVALID');const profile=chainProfile(input.chainId),stable=profile.quoteTokens.find(token=>token.stable&&(token.address.toLowerCase()===pool.value.token0.toLowerCase()||token.address.toLowerCase()===pool.value.token1.toLowerCase()));if(!stable)throw new Error('NATIVE_USD_STABLE_TOKEN_IDENTITY_INVALID');const client=input.rpc.clients[0]!,stableDecimals=Number(await client.readContract({address:stable.address,abi:decimalsAbi,functionName:'decimals'}));if(stableDecimals!==stable.decimals)throw new Error('NATIVE_USD_STABLE_TOKEN_DECIMALS_INVALID');const token0Decimals=pool.value.token0.toLowerCase()===profile.wrappedNativeAddress.toLowerCase()?profile.nativeDecimals:stableDecimals,token1Decimals=pool.value.token1.toLowerCase()===profile.wrappedNativeAddress.toLowerCase()?profile.nativeDecimals:stableDecimals;return nativeUsdFromVerifiedPool({chainId:input.chainId,protocol:input.protocol,token0:pool.value.token0,token1:pool.value.token1,sqrtPriceX96:pool.value.sqrtPriceX96,token0Decimals,token1Decimals,observedBlock:pool.value.blockNumber,observedAtMs:nowMs,nowMs});}catch(error){return {status:'UNAVAILABLE' as const,reason:error instanceof Error?error.message:'NATIVE_USD_VALUATION_UNAVAILABLE'};}
}

export async function chainGasReadiness(input:{rpc:FallbackRpc;repo?:SqliteLedgerRepository;config:ChainRuntimeConfig;walletStatus:Awaited<ReturnType<typeof verifyChainWallet>>;protocol?:GuardedV3Protocol;action?:string;stages?:readonly GuardedV3GasStage[];previewRevision?:number;allowanceEvidenceRevision?:string;env?:NodeJS.ProcessEnv;nowMs?:number}){
 const env=input.env??process.env,nowMs=input.nowMs??Date.now(),chainId=input.config.profile.chainId as GuardedV3Chain,protocol=input.protocol??(chainId===56?'pancakeswap_v3':'uniswap_v3'),prefix=chainId===56?'BSC':'ETHEREUM',policy=derivedFeeEvidencePolicy(chainId),spreadOverride=positive(env,`${prefix}_MAX_PROVIDER_FEE_SPREAD_BPS`),maxAgeOverride=positive(env,`${prefix}_FEE_EVIDENCE_MAX_AGE_MS`),maxAge=maxAgeOverride??policy.maxAgeMs,blockers:string[]=[];let deploymentEvidence:CanonicalDeploymentVerificationEvidence|undefined,quote:Awaited<ReturnType<typeof acquireBscLegacyFeeEvidence>>|Awaited<ReturnType<typeof acquireEthereumEip1559FeeEvidence>>|undefined,valuation:Awaited<ReturnType<typeof runtimeNativeUsdValuation>>|undefined;
 try{deploymentEvidence=await canonicalDeploymentVerification({profile:input.config.profile,rpc:input.rpc,protocol,repo:input.repo,nowMs});if(deploymentEvidence.status!=='VERIFIED')blockers.push('DEPLOYMENT_RUNTIME_NOT_VERIFIED');}catch(error){blockers.push(error instanceof Error?error.message:'DEPLOYMENT_RUNTIME_NOT_VERIFIED');}
 try{quote=chainId===56?await acquireBscLegacyFeeEvidence({clients:input.rpc.clients,chainId,minimumGasPrice:positiveBig(env,'BSC_MIN_GAS_PRICE_WEI'),maximumGasPrice:positiveBig(env,'BSC_MAX_GAS_PRICE_WEI'),maximumProviderSpreadBps:spreadOverride,observedAtMs:nowMs}):await acquireEthereumEip1559FeeEvidence({clients:input.rpc.clients,chainId,maximumFeePerGas:positiveBig(env,'ETHEREUM_MAX_FEE_PER_GAS_WEI'),maximumProviderSpreadBps:spreadOverride,observedAtMs:nowMs});}catch(error){blockers.push(error instanceof Error?error.message:'FEE_EVIDENCE_UNAVAILABLE');}
 if(deploymentEvidence)valuation=await runtimeNativeUsdValuation({rpc:input.rpc,chainId,protocol,deploymentEvidence,nowMs});if(!valuation||valuation.status!=='AVAILABLE')blockers.push('NATIVE_USD_VALUATION_UNAVAILABLE');const nativeBalance='nativeBalance'in input.walletStatus?input.walletStatus.nativeBalance:undefined,feeFresh=quote!==undefined&&nowMs-quote.observedAtMs<=maxAge;
 let projection:Awaited<ReturnType<typeof estimateGuardedV3LifecycleGas>>|undefined;if(input.stages?.length&&quote&&deploymentEvidence?.status==='VERIFIED'&&nativeBalance!==undefined&&'wallet'in input.walletStatus&&input.walletStatus.wallet){try{projection=await estimateGuardedV3LifecycleGas({rpc:input.rpc,repo:input.repo,wallet:input.walletStatus.wallet,chainId,protocol,action:input.action??'SELECTED_ACTION',stages:input.stages,feeQuote:quote,feeEvidenceRevision:quote.evidenceRevision,feeEvidenceMaxAgeMs:maxAge,previewRevision:input.previewRevision??0,deploymentEvidenceRevision:deploymentEvidence.evidenceRevision,walletEvidenceRevision:'walletEvidenceRevision'in input.walletStatus?input.walletStatus.walletEvidenceRevision:'UNAVAILABLE',allowanceEvidenceRevision:input.allowanceEvidenceRevision??'NOT_APPLICABLE',nativeBalance,nativeUsd:valuation?.status==='AVAILABLE'?valuation.nativeUsd:undefined,nowMs});if(projection.funding.fundingDeficit>0n)blockers.push('CHAIN_NATIVE_GAS_INSUFFICIENT');}catch(error){blockers.push(error instanceof Error?error.message:'EXACT_ACTION_SIMULATION_PROOF_REQUIRED');}}
 return {chain:input.config.profile.key,chainId,protocol,walletConfigured:input.walletStatus.walletConfigured,nativeSymbol:input.config.profile.nativeSymbol,nativeBalance,deploymentEvidence,feeEvidenceStatus:quote?'AVAILABLE':'UNAVAILABLE',feeEvidenceFresh:feeFresh,feeEvidenceMaxAgeMs:maxAge,feeEvidence:quote,feeModel:quote?.feeModel,nativeUsd:valuation?.status==='AVAILABLE'?valuation.nativeUsd:undefined,nativeUsdEvidence:valuation,projectedGas:projection?.projectedActionGas??[],projectedGasStatus:projection?'AVAILABLE':'NOT_APPLICABLE',projectedLifecycleGas:projection?.projectedLifecycleGas,projectedLifecycleGasStatus:projection?'AVAILABLE':'NOT_APPLICABLE',projectionEvidenceRevision:projection?.previewEvidenceRevision,gasFunding:projection?.funding,sufficiency:projection?(projection.funding.fundingDeficit>0n?'insufficient':'sufficient'):'NOT_APPLICABLE',gasPolicyValid:Boolean(quote&&feeFresh),nonceEvidenceHealthy:'nonceEvidenceHealthy'in input.walletStatus&&input.walletStatus.nonceEvidenceHealthy,blockers:[...new Set(blockers)],signerAccessed:false,signerConstructed:false,nonceReserved:false,journalWritten:false,signingUsed:false,broadcastUsed:false};
}

const factoryAbi=[{type:'function',name:'getPool',stateMutability:'view',inputs:[{type:'address'},{type:'address'},{type:'uint24'}],outputs:[{type:'address'}]},{type:'function',name:'feeAmountTickSpacing',stateMutability:'view',inputs:[{type:'uint24'}],outputs:[{type:'int24'}]}] as const;
export async function registerManualVerifiedBscPool(input:{rpc:FallbackRpc;repo:SqliteLedgerRepository;poolAddress:Address;nowMs?:number}){
 const chainId=56 as const,protocol='pancakeswap_v3' as const,deployment=protocolDeployment(chainId,protocol),address=getAddress(input.poolAddress),health=await input.rpc.health();if(!health.some(item=>item.healthy&&item.chainId===chainId))throw new Error('MANUAL_POOL_PROVIDER_CHAIN_ID_UNVERIFIED');const client=input.rpc.clients[health.findIndex(item=>item.healthy&&item.chainId===chainId)]!;const code=await client.getBytecode({address});if(!code||code==='0x')throw new Error('MANUAL_POOL_RUNTIME_CODE_MISSING');await verifyV3ProtocolRoles({client,chainId,protocol});const inspected=await inspectV3Pool(input.rpc,address);if(inspected.status==='unavailable')throw new Error(`MANUAL_POOL_STATE_UNAVAILABLE:${inspected.reason}`);const pool=inspected.value;if(pool.factory.toLowerCase()!==deployment.contracts.factory!.toLowerCase())throw new Error('MANUAL_POOL_FACTORY_MISMATCH');const [canonical,spacing,token0,token1]=await Promise.all([client.readContract({address:deployment.contracts.factory!,abi:factoryAbi,functionName:'getPool',args:[pool.token0,pool.token1,pool.fee]}),client.readContract({address:deployment.contracts.factory!,abi:factoryAbi,functionName:'feeAmountTickSpacing',args:[pool.fee]}),inspectErc20(input.rpc,pool.token0),inspectErc20(input.rpc,pool.token1)]);if(canonical.toLowerCase()!==address.toLowerCase())throw new Error('MANUAL_POOL_DEPLOYER_RELATIONSHIP_UNVERIFIED');if(Number(spacing)!==pool.tickSpacing||pool.fee<=0||pool.tickSpacing<=0)throw new Error('MANUAL_POOL_FEE_OR_TICK_SPACING_INVALID');if(!pool.initialized||pool.sqrtPriceX96<=0n)throw new Error('MANUAL_POOL_STATE_INVALID');if(token0.status==='unavailable'||token1.status==='unavailable')throw new Error('MANUAL_POOL_TOKEN_CONTRACT_INVALID');
 const conflict=input.repo.db.prepare('SELECT protocol,token0_address,token1_address,fee FROM chain_pools WHERE chain_id=? AND lower(pool_address)=? AND protocol<>?').get(chainId,address.toLowerCase(),protocol) as Record<string,unknown>|undefined;if(conflict)throw new Error('MANUAL_POOL_CONFLICTING_PROTOCOL_REGISTRATION');const existing=input.repo.db.prepare('SELECT * FROM chain_pools WHERE chain_id=? AND protocol=? AND lower(pool_address)=?').get(chainId,protocol,address.toLowerCase()) as Record<string,unknown>|undefined;if(existing&&(String(existing.token0_address).toLowerCase()!==pool.token0.toLowerCase()||String(existing.token1_address).toLowerCase()!==pool.token1.toLowerCase()||Number(existing.fee)!==pool.fee))throw new Error('MANUAL_POOL_CONFLICTING_METADATA');
 for(const token of [token0.value,token1.value])input.repo.upsertChainToken({chainId,address:token.address,symbol:token.symbol,decimals:token.decimals,metadata:{name:token.name,source:'ONCHAIN_VERIFIED'},refreshedAtMs:input.nowMs});const row=input.repo.upsertChainPool({chainId,protocol,poolAddress:address,token0:pool.token0,token1:pool.token1,fee:pool.fee,tickSpacing:pool.tickSpacing,validationStatus:'MANUAL_VERIFIED',updatedAtMs:input.nowMs,state:{source:'MANUAL_VERIFIED',factory:pool.factory,initialized:pool.initialized,sqrtPriceX96:pool.sqrtPriceX96,tick:pool.tick,liquidity:pool.liquidity,verifiedBlock:pool.blockNumber,deploymentVersion:deployment.registryVersion,registryDiscoveryComplete:false,executionReadinessElevated:false}});return {status:existing?'ALREADY_REGISTERED_VERIFIED' as const:'REGISTERED' as const,chain:'bsc',chainId,protocol,pool:row,source:'MANUAL_VERIFIED',registryDiscoveryComplete:false,signerConstructed:false,nonceReserved:false,journalWritten:false,broadcastUsed:false,callbackCreated:false,exposureMutated:false};
}
