import { spawn } from 'node:child_process';
import { createServer } from 'node:net';
import { encodeAbiParameters, getAddress, keccak256, toHex, type Address, type PublicClient, type StateOverride } from 'viem';
import { FallbackRpc, chainProfile, erc20Abi, inspectErc20, inspectV3Pool, protocolDeployment, type ChainFeeQuote } from '@funi/core';
import { MAX_TICK, MIN_TICK, amountsForLiquidity, buildGuardedV3Approval, buildGuardedV3Mint, sqrtRatioAtTick, type GuardedV3Chain, type GuardedV3Protocol, type V3PoolExecutionEvidence, type V3TokenExecutionEvidence } from '@funi/v3';
import { estimateGuardedV3LifecycleGas, type GuardedV3GasStage } from './v3-multichain-executor.js';
import { providerSetRevision, type CanonicalDeploymentVerificationEvidence } from './multichain-runtime.js';

export const GAS_CALIBRATION_ACCOUNT=getAddress('0x000000000000000000000000000000000000ca11');
export type CalibrationSource='DIRECT_RPC'|'ANVIL_FORK';
export type CalibrationProviderSourceKey='BSC_RPC_URLS'|'ETHEREUM_RPC_URLS';
export type CalibrationProviderProvenance={requestedChainAlias:'bsc'|'ethereum';expectedChainId:GuardedV3Chain;observedChainId:GuardedV3Chain;providerSourceKey:CalibrationProviderSourceKey;providerIndex:number;providerSetRevision:`0x${string}`;calibrationSource:CalibrationSource;forkChainId?:GuardedV3Chain};
const uint128Max=(1n<<128n)-1n,sentinel=(1n<<255n)+0xca11n,revision=(value:unknown)=>keccak256(toHex(JSON.stringify(value,(_,item)=>typeof item==='bigint'?item.toString():item)));

const expectedSource=(chain:'bsc'|'ethereum'):CalibrationProviderSourceKey=>chain==='bsc'?'BSC_RPC_URLS':'ETHEREUM_RPC_URLS';
export function calibrationProviderRpc(chain:'bsc'|'ethereum',env:NodeJS.ProcessEnv=process.env){const profile=chainProfile(chain),providerSourceKey=expectedSource(chain),rpcUrls=(env[providerSourceKey]??'').split(',').map(value=>value.trim()).filter(Boolean);if(!rpcUrls.length)throw new Error(`GAS_CALIBRATION_PROVIDER_SOURCE_CONFIGURATION_MISSING:${providerSourceKey}`);const assets=Object.fromEntries([['WRAPPED_NATIVE',profile.wrappedNativeAddress],...profile.quoteTokens.map(item=>[item.symbol,item.address])]);return {providerSourceKey,rpc:new FallbackRpc({chainId:profile.chainId,name:profile.displayName,rpcUrls,nativeSymbol:profile.nativeSymbol,explorerUrl:profile.blockExplorerBase,assets},rpcUrls,{timeoutMs:8_000})};}
export async function bindCalibrationProvider(input:{requestedChainAlias:'bsc'|'ethereum';providerSourceKey:CalibrationProviderSourceKey;rpc:FallbackRpc}){
 const expectedChainId=chainProfile(input.requestedChainAlias).chainId as GuardedV3Chain,source=expectedSource(input.requestedChainAlias);if(input.providerSourceKey!==source)throw new Error(`GAS_CALIBRATION_PROVIDER_SOURCE_MISMATCH:${source}`);if(input.rpc.config.chainId!==expectedChainId)throw new Error('GAS_CALIBRATION_RPC_CONFIGURATION_CHAIN_MISMATCH');
 const observed=await Promise.allSettled(input.rpc.clients.map(async(client,providerIndex)=>({providerIndex,chainId:await client.getChainId()}))),fulfilled=observed.flatMap(item=>item.status==='fulfilled'?[item.value]:[]),wrong=fulfilled.find(item=>item.chainId!==expectedChainId);if(wrong)throw new Error(`GAS_CALIBRATION_PROVIDER_CHAIN_MISMATCH:${wrong.providerIndex}:${wrong.chainId}:${expectedChainId}`);const selected=fulfilled[0];if(!selected)throw new Error('GAS_CALIBRATION_PROVIDER_CHAIN_ID_UNAVAILABLE');const url=input.rpc.config.rpcUrls[selected.providerIndex]??'https://provider.invalid',rpc=new FallbackRpc({...input.rpc.config,rpcUrls:[url]},[url],{clients:[input.rpc.clients[selected.providerIndex]!]});
 const provenance:CalibrationProviderProvenance={requestedChainAlias:input.requestedChainAlias,expectedChainId,observedChainId:expectedChainId,providerSourceKey:source,providerIndex:selected.providerIndex,providerSetRevision:providerSetRevision(input.rpc),calibrationSource:'DIRECT_RPC'};return {rpc,provenance,forkUrl:url};
}

export function deriveCalibrationRange(currentTick:number,tickSpacing:number){
 if(!Number.isInteger(currentTick)||!Number.isInteger(tickSpacing)||tickSpacing<=0)throw new Error('GAS_CALIBRATION_TICK_EVIDENCE_INVALID');
 const minimum=Math.ceil(MIN_TICK/tickSpacing)*tickSpacing,maximum=Math.floor(MAX_TICK/tickSpacing)*tickSpacing;let tickLower=Math.floor(currentTick/tickSpacing)*tickSpacing,tickUpper=Math.ceil(currentTick/tickSpacing)*tickSpacing;if(tickLower===currentTick)tickLower-=tickSpacing;if(tickUpper===currentTick)tickUpper+=tickSpacing;if(Object.is(tickLower,-0))tickLower=0;if(Object.is(tickUpper,-0))tickUpper=0;if(tickLower<minimum||tickUpper>maximum||!(tickLower<currentTick&&currentTick<tickUpper))throw new Error('GAS_CALIBRATION_CURRENT_TICK_AT_PROTOCOL_BOUNDARY');
 return {currentTick,tickSpacing,tickLower,tickUpper,protocolMinimumTick:minimum,protocolMaximumTick:maximum,derivationRule:'nearest strict enclosing usable ticks; calibration-only, never a live range strategy'};
}

export function deriveWethOnlyCalibrationRange(currentTick:number,tickSpacing:number){
 if(!Number.isInteger(currentTick)||!Number.isInteger(tickSpacing)||tickSpacing<=0)throw new Error('GAS_CALIBRATION_TICK_EVIDENCE_INVALID');const minimum=Math.ceil(MIN_TICK/tickSpacing)*tickSpacing,maximum=Math.floor(MAX_TICK/tickSpacing)*tickSpacing;let tickUpper=Math.floor((currentTick-1)/tickSpacing)*tickSpacing,tickLower=tickUpper-tickSpacing;if(Object.is(tickLower,-0))tickLower=0;if(Object.is(tickUpper,-0))tickUpper=0;if(tickLower<minimum||tickUpper>maximum||!(tickLower<tickUpper&&tickUpper<currentTick))throw new Error('GAS_CALIBRATION_WETH_ONLY_RANGE_UNAVAILABLE');return {currentTick,tickSpacing,tickLower,tickUpper,protocolMinimumTick:minimum,protocolMaximumTick:maximum,derivationRule:'two adjacent usable ticks entirely below current tick; produces token1/WETH-only liquidity; calibration-only and never a live strategy'};
}

export function deriveRepresentativeAmounts(input:{sqrtPriceX96:bigint;tickLower:number;tickUpper:number;token0Decimals:number;token1Decimals:number}){
 if(input.sqrtPriceX96<=0n)throw new Error('GAS_CALIBRATION_POOL_PRICE_INVALID');const minimum0=10n**BigInt(Math.max(0,input.token0Decimals-6)),minimum1=10n**BigInt(Math.max(0,input.token1Decimals-6)),lower=sqrtRatioAtTick(input.tickLower),upper=sqrtRatioAtTick(input.tickUpper);let representativeLiquidity=1n,amount0Desired=0n,amount1Desired=0n;while(representativeLiquidity<=uint128Max){const amounts=amountsForLiquidity(input.sqrtPriceX96,lower,upper,representativeLiquidity);amount0Desired=amounts.amount0;amount1Desired=amounts.amount1;if(amount0Desired>=minimum0&&amount1Desired>=minimum1)break;representativeLiquidity*=2n;}if(representativeLiquidity>uint128Max||amount0Desired<=0n||amount1Desired<=0n)throw new Error('GAS_CALIBRATION_NONZERO_AMOUNTS_UNAVAILABLE');return {amount0Desired,amount1Desired,amount0Min:0n,amount1Min:0n,representativeLiquidity,derivationRule:'smallest power-of-two liquidity producing at least one millionth of each token; zero minima are calibration-only'};
}

export function deriveWethOnlyRepresentativeAmount(input:{sqrtPriceX96:bigint;tickLower:number;tickUpper:number}){
 const lower=sqrtRatioAtTick(input.tickLower),upper=sqrtRatioAtTick(input.tickUpper),minimumWeth=10n**12n;if(input.sqrtPriceX96<=upper)throw new Error('GAS_CALIBRATION_RANGE_NOT_WETH_ONLY');let representativeLiquidity=1n,amount1Desired=0n;while(representativeLiquidity<=uint128Max){const amounts=amountsForLiquidity(input.sqrtPriceX96,lower,upper,representativeLiquidity);if(amounts.amount0!==0n)throw new Error('GAS_CALIBRATION_USDC_AMOUNT_NOT_ZERO');amount1Desired=amounts.amount1;if(amount1Desired>=minimumWeth)break;representativeLiquidity*=2n;}if(representativeLiquidity>uint128Max||amount1Desired<=0n)throw new Error('GAS_CALIBRATION_WETH_AMOUNT_UNAVAILABLE');return {amount0Desired:0n,amount1Desired,amount0Min:0n,amount1Min:0n,representativeLiquidity,derivationRule:'smallest power-of-two liquidity producing at least one millionth WETH and exactly zero USDC'};
}

const balanceSlot=(owner:Address,index:number)=>keccak256(encodeAbiParameters([{type:'address'},{type:'uint256'}],[owner,BigInt(index)]));
const allowanceSlot=(owner:Address,spender:Address,index:number)=>{const outer=keccak256(encodeAbiParameters([{type:'address'},{type:'uint256'}],[owner,BigInt(index)]));return keccak256(encodeAbiParameters([{type:'address'},{type:'bytes32'}],[spender,outer]));};
async function slotProbe(client:PublicClient,input:{token:Address;owner:Address;spender:Address;kind:'BALANCE'|'ALLOWANCE';preferred?:number}){const candidates=[...(input.preferred===undefined?[]:[input.preferred]),...Array.from({length:32},(_,index)=>index)].filter((value,index,all)=>all.indexOf(value)===index);for(const index of candidates){const slot=input.kind==='BALANCE'?balanceSlot(input.owner,index):allowanceSlot(input.owner,input.spender,index),stateOverride:StateOverride=[{address:input.token,stateDiff:[{slot,value:toHex(sentinel,{size:32})}]}],observed=input.kind==='BALANCE'?await client.readContract({address:input.token,abi:erc20Abi,functionName:'balanceOf',args:[input.owner],stateOverride}):await client.readContract({address:input.token,abi:erc20Abi,functionName:'allowance',args:[input.owner,input.spender],stateOverride});if(observed===sentinel)return {index,slot};}throw new Error(`GAS_CALIBRATION_${input.kind}_STATE_OVERRIDE_SLOT_UNAVAILABLE`);}
export async function calibrationStateOverride(input:{client:PublicClient;token:Address;spender:Address;tokenAmount:bigint;nativeAmount:bigint;owner?:Address}){const owner=input.owner??GAS_CALIBRATION_ACCOUNT,balance=await slotProbe(input.client,{token:input.token,owner,spender:input.spender,kind:'BALANCE'}),allowance=await slotProbe(input.client,{token:input.token,owner,spender:input.spender,kind:'ALLOWANCE',preferred:balance.index+1}),stateOverride:StateOverride=[{address:owner,balance:input.nativeAmount+10n**18n},{address:input.token,stateDiff:[{slot:balance.slot,value:toHex(input.tokenAmount,{size:32})},{slot:allowance.slot,value:toHex(input.tokenAmount,{size:32})}]}];return {stateOverride,evidenceRevision:revision({token:input.token,owner,spender:input.spender,balanceSlot:balance.index,allowanceSlot:allowance.index,tokenAmount:input.tokenAmount,nativeAmount:input.nativeAmount})};}

export async function planGuardedV3OpenCalibration(input:{rpc:FallbackRpc;chainId:GuardedV3Chain;protocol:GuardedV3Protocol;poolAddress:Address;calibrationSource:CalibrationSource;recipient?:Address;stateOverrideFactory?:typeof calibrationStateOverride}){
 const profile=chainProfile(input.chainId),deployment=protocolDeployment(input.chainId,input.protocol),recipient=input.recipient??GAS_CALIBRATION_ACCOUNT;
 const poolResult=await inspectV3Pool(input.rpc,input.poolAddress);if(poolResult.status==='unavailable')throw new Error('GAS_CALIBRATION_VERIFIED_POOL_UNAVAILABLE');const poolState=poolResult.value;if(poolState.factory.toLowerCase()!==deployment.contracts.factory!.toLowerCase())throw new Error('GAS_CALIBRATION_POOL_FACTORY_MISMATCH');const pool:V3PoolExecutionEvidence={chainId:input.chainId,protocol:input.protocol,pool:poolState.address,token0:poolState.token0,token1:poolState.token1,fee:poolState.fee,tickSpacing:poolState.tickSpacing,initialized:poolState.initialized,factoryVerified:true,observedBlock:poolState.blockNumber},[token0,token1]=await Promise.all([inspectErc20(input.rpc,pool.token0),inspectErc20(input.rpc,pool.token1)]);if(token0.status==='unavailable'||token1.status==='unavailable')throw new Error('GAS_CALIBRATION_TOKEN_METADATA_UNAVAILABLE');
 const block=await input.rpc.withClient(client=>client.getBlock({blockTag:'latest'}),{stage:'open_gas_calibration',method:'eth_getBlockByNumber'});let range:ReturnType<typeof deriveCalibrationRange>|ReturnType<typeof deriveWethOnlyCalibrationRange>,amounts:{amount0Desired:bigint;amount1Desired:bigint;amount0Min:bigint;amount1Min:bigint;representativeLiquidity:bigint;derivationRule:string},stages:GuardedV3GasStage[],calibrationStateRevision:string,approvalRequirement:string,nativeFundingBehavior:string;
 if(input.chainId===1){const usdc=profile.quoteTokens.find(token=>token.symbol==='USDC')!;if(pool.token0.toLowerCase()!==usdc.address.toLowerCase()||pool.token1.toLowerCase()!==profile.wrappedNativeAddress.toLowerCase()||token0.value.decimals!==6||token1.value.decimals!==18)throw new Error('GAS_CALIBRATION_ETHEREUM_USDC_WETH_ORIENTATION_INVALID');range=deriveWethOnlyCalibrationRange(poolState.tick,poolState.tickSpacing);amounts=deriveWethOnlyRepresentativeAmount({sqrtPriceX96:poolState.sqrtPriceX96,tickLower:range.tickLower,tickUpper:range.tickUpper});const mint=buildGuardedV3Mint({chainId:1,protocol:'uniswap_v3',pool,recipient,tickLower:range.tickLower,tickUpper:range.tickUpper,amount0Desired:0n,amount1Desired:amounts.amount1Desired,amount0Min:0n,amount1Min:0n,deadline:block.timestamp+600n,nowUnix:block.timestamp,fundNative:true}),stateOverride=input.calibrationSource==='DIRECT_RPC'?[{address:recipient,balance:amounts.amount1Desired+10n**18n}] as StateOverride:undefined;calibrationStateRevision=revision({chainId:1,source:input.calibrationSource,recipient,nativeAmount:amounts.amount1Desired,nativeBalanceOnly:true});stages=[{stage:'NATIVE_ETH_WETH_MINT_MULTICALL',transaction:mint,stateOverride,calibrationOnly:true}];approvalRequirement='NOT_APPLICABLE_USDC_AMOUNT_ZERO';nativeFundingBehavior=input.calibrationSource==='DIRECT_RPC'?'native account balance override only; payable mint wraps ETH to WETH and refunds excess':'anvil_setBalance only; payable mint wraps ETH to WETH and refunds excess';}
 else{range=deriveCalibrationRange(poolState.tick,poolState.tickSpacing);amounts=deriveRepresentativeAmounts({sqrtPriceX96:poolState.sqrtPriceX96,tickLower:range.tickLower,tickUpper:range.tickUpper,token0Decimals:token0.value.decimals,token1Decimals:token1.value.decimals});const wrapped=profile.wrappedNativeAddress,wrappedIndex=pool.token0.toLowerCase()===wrapped.toLowerCase()?0:pool.token1.toLowerCase()===wrapped.toLowerCase()?1:-1;if(wrappedIndex<0)throw new Error('GAS_CALIBRATION_WRAPPED_NATIVE_POOL_REQUIRED');const stableIndex=wrappedIndex===0?1:0,stableAddress=stableIndex===0?pool.token0:pool.token1,stableProfile=profile.quoteTokens.find(token=>token.stable&&token.address.toLowerCase()===stableAddress.toLowerCase());if(!stableProfile)throw new Error('GAS_CALIBRATION_VERIFIED_STABLE_TOKEN_REQUIRED');const stableMetadata=stableIndex===0?token0.value:token1.value;if(stableMetadata.decimals!==stableProfile.decimals)throw new Error('GAS_CALIBRATION_STABLE_DECIMALS_MISMATCH');const stableAmount=stableIndex===0?amounts.amount0Desired:amounts.amount1Desired,nativeAmount=wrappedIndex===0?amounts.amount0Desired:amounts.amount1Desired,totalSupply=await input.rpc.withClient(client=>client.readContract({address:stableAddress,abi:erc20Abi,functionName:'totalSupply'}),{stage:'open_gas_calibration',method:'ERC20.totalSupply'}),tokenEvidence:V3TokenExecutionEvidence={chainId:56,token:stableAddress,runtimeCodePresent:true,decimals:stableMetadata.decimals,totalSupply,transferSemantics:'STANDARD_ERC20',approveReturn:'BOOL'},approval=buildGuardedV3Approval({chainId:56,protocol:'pancakeswap_v3',tokenEvidence,amount:stableAmount}),mint=buildGuardedV3Mint({chainId:56,protocol:'pancakeswap_v3',pool,recipient,tickLower:range.tickLower,tickUpper:range.tickUpper,amount0Desired:amounts.amount0Desired,amount1Desired:amounts.amount1Desired,amount0Min:0n,amount1Min:0n,deadline:block.timestamp+600n,nowUnix:block.timestamp,fundNative:true}),override=await input.rpc.withClient(client=>(input.stateOverrideFactory??calibrationStateOverride)({client,token:stableAddress,spender:deployment.contracts.positionManager!,tokenAmount:stableAmount,nativeAmount,owner:recipient}),{stage:'open_gas_calibration',method:'eth_call+stateOverride'}),accountBalanceOverride:StateOverride=[{address:recipient,balance:nativeAmount+10n**18n}];calibrationStateRevision=override.evidenceRevision;stages=[{stage:'STABLE_TOKEN_APPROVAL',transaction:approval,stateOverride:accountBalanceOverride,calibrationOnly:true},{stage:'NATIVE_WRAP_AND_MINT',transaction:mint,stateOverride:override.stateOverride,calibrationOnly:true}];approvalRequirement='stable-token approval exercised against synthetic state';nativeFundingBehavior='native BNB payment is included in mint multicall and counted once';}
 return {pool,poolState,token0:token0.value,token1:token1.value,range,amounts,stages,calibrationStateRevision,approvalRequirement,nativeFundingBehavior};
}

export async function calibrateGuardedV3OpenGas(input:{rpc:FallbackRpc;chainId:GuardedV3Chain;protocol:GuardedV3Protocol;poolAddress:Address;deploymentEvidence:CanonicalDeploymentVerificationEvidence;feeQuote:ChainFeeQuote;feeEvidenceRevision:string;feeEvidenceMaxAgeMs:number;walletEvidenceRevision:string;currentWalletNativeBalance:bigint;providerProvenance:CalibrationProviderProvenance;nativeUsd?:number;nowMs?:number;stateOverrideFactory?:typeof calibrationStateOverride}){
 const nowMs=input.nowMs??Date.now(),profile=chainProfile(input.chainId),deployment=protocolDeployment(input.chainId,input.protocol);if(input.providerProvenance.expectedChainId!==input.chainId||input.providerProvenance.observedChainId!==input.chainId||input.providerProvenance.requestedChainAlias!==profile.key||input.providerProvenance.providerSourceKey!==expectedSource(profile.key as 'bsc'|'ethereum')||input.providerProvenance.providerSetRevision!==input.deploymentEvidence.providerSetRevision)throw new Error('GAS_CALIBRATION_PROVIDER_PROVENANCE_INVALID');if(input.providerProvenance.calibrationSource==='ANVIL_FORK'&&input.providerProvenance.forkChainId!==input.chainId)throw new Error('GAS_CALIBRATION_FORK_CHAIN_MISMATCH');if(input.deploymentEvidence.status!=='VERIFIED'||input.deploymentEvidence.chainId!==input.chainId||input.deploymentEvidence.protocol!==input.protocol||input.deploymentEvidence.deploymentVersion!==deployment.registryVersion||input.deploymentEvidence.validUntilMs<nowMs)throw new Error('GAS_CALIBRATION_DEPLOYMENT_EVIDENCE_INVALID');const {range,amounts,stages,calibrationStateRevision,approvalRequirement,nativeFundingBehavior,token0,token1}=await planGuardedV3OpenCalibration({...input,calibrationSource:input.providerProvenance.calibrationSource});
 const projection=await estimateGuardedV3LifecycleGas({rpc:input.rpc,wallet:GAS_CALIBRATION_ACCOUNT,chainId:input.chainId,protocol:input.protocol,action:'OPEN_GAS_CALIBRATION',stages,feeQuote:input.feeQuote,feeEvidenceRevision:input.feeEvidenceRevision,feeEvidenceMaxAgeMs:input.feeEvidenceMaxAgeMs,previewRevision:nowMs,deploymentEvidenceRevision:input.deploymentEvidence.evidenceRevision,walletEvidenceRevision:input.walletEvidenceRevision,allowanceEvidenceRevision:calibrationStateRevision,nativeBalance:input.currentWalletNativeBalance,nativeUsd:input.nativeUsd,nowMs});return {status:'GAS_CALIBRATION_VERIFIED' as const,actionableOpenStatus:'ACTIONABLE_OPEN_NOT_CONFIGURED' as const,chain:profile.key,chainId:input.chainId,protocol:input.protocol,providerProvenance:input.providerProvenance,parameterDerivation:{token0:{decimals:token0.decimals,representativeAmountNonZero:amounts.amount0Desired>0n},token1:{decimals:token1.decimals,representativeAmountNonZero:amounts.amount1Desired>0n},currentTick:range.currentTick,tickSpacing:range.tickSpacing,tickLower:range.tickLower,tickUpper:range.tickUpper,rangeRule:range.derivationRule,amountRule:amounts.derivationRule,minimumAmounts:'zero for calibration only; no live slippage policy selected',nativeFundingBehavior,approvalRequirement},gasStages:projection.projectedActionGas,projectedLifecycleGas:projection.projectedLifecycleGas,maxFeePerGasUsed:input.feeQuote.feeModel==='eip1559'?input.feeQuote.maxFeePerGas:undefined,gasPriceUsed:input.feeQuote.feeModel==='legacy'?input.feeQuote.gasPrice:undefined,gasFunding:projection.funding,evidence:{deploymentRevision:input.deploymentEvidence.evidenceRevision,feeRevision:input.feeEvidenceRevision,calibrationStateRevision,projectionRevision:projection.previewEvidenceRevision,block:projection.funding.evidenceBlock,timeMs:projection.funding.evidenceTimeMs},calibrationFundingSource:input.providerProvenance.calibrationSource==='DIRECT_RPC'?'NATIVE_BALANCE_STATE_OVERRIDE':'ANVIL_SET_BALANCE',productionWalletCapitalUsed:false,calibrationParametersPromotableToExecution:false,executionReady:false,signerConstructed:false,nonceReserved:false,journalWritten:false,authorizationCreated:false,signingUsed:false,broadcastUsed:false};
}

async function unusedPort(){return new Promise<number>((resolve,reject)=>{const server=createServer();server.once('error',reject);server.listen(0,'127.0.0.1',()=>{const address=server.address();if(!address||typeof address==='string')return reject(new Error('GAS_CALIBRATION_ANVIL_PORT_UNAVAILABLE'));const port=address.port;server.close(error=>error?reject(error):resolve(port));});});}
export async function calibrateGuardedV3OpenGasWithFallback(input:Parameters<typeof calibrateGuardedV3OpenGas>[0]&{anvilBin?:string;forkUrl?:string}){try{return await calibrateGuardedV3OpenGas(input);}catch(directError){if(input.chainId!==1||!input.anvilBin||!input.forkUrl)throw directError;const port=await unusedPort(),url=`http://127.0.0.1:${port}`,child=spawn(input.anvilBin,['--fork-url',input.forkUrl,'--fork-block-number',input.deploymentEvidence.verifiedBlock.toString(),'--chain-id','1','--port',String(port),'-q'],{stdio:'ignore'}),rpc=new FallbackRpc({chainId:1,name:'Ethereum calibration fork',nativeSymbol:'ETH',rpcUrls:[url],assets:{}},[url],{timeoutMs:15_000});let spawnError:Error|undefined;child.once('error',error=>{spawnError=error;});try{let ready=false;for(let attempt=0;attempt<100;attempt++){if(spawnError)throw new Error('GAS_CALIBRATION_ANVIL_START_FAILED');try{if(await rpc.clients[0]!.getChainId()===1){ready=true;break;}}catch{}await new Promise(resolve=>setTimeout(resolve,100));}if(!ready)throw new Error('GAS_CALIBRATION_ANVIL_START_FAILED');await (rpc.clients[0] as any).request({method:'anvil_setBalance',params:[GAS_CALIBRATION_ACCOUNT,toHex(10n**20n)]});return await calibrateGuardedV3OpenGas({...input,rpc,providerProvenance:{...input.providerProvenance,observedChainId:1,calibrationSource:'ANVIL_FORK',forkChainId:1}});}finally{child.kill('SIGTERM');}}}
