import { spawn } from 'node:child_process';
import { createServer } from 'node:net';
import { createWalletClient, formatUnits, http, toHex, type Address } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { FallbackRpc, assertFreshFeeQuote, chainProfile, protocolDeployment, type ChainFeeQuote } from '@funi/core';
import { assertGuardedV3TransactionSemantics, buildGuardedV3Burn, buildGuardedV3Collect, buildGuardedV3Decrease, inspectV3FamilyPosition, type GuardedV3Chain, type GuardedV3Protocol, type V3BuiltTransaction } from '@funi/v3';
import { planGuardedV3OpenCalibration, type CalibrationProviderProvenance } from './open-gas-calibration.js';
import type { CanonicalDeploymentVerificationEvidence } from './multichain-runtime.js';

const forkAccount=privateKeyToAccount('0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80');
const enumerableAbi=[{type:'function',name:'balanceOf',stateMutability:'view',inputs:[{type:'address'}],outputs:[{type:'uint256'}]},{type:'function',name:'tokenOfOwnerByIndex',stateMutability:'view',inputs:[{type:'address'},{type:'uint256'}],outputs:[{type:'uint256'}]}] as const;
export type OperationalForkSourceKey='BSC_RPC_URLS'|'BSC_FORK_RPC_URL'|'ETHEREUM_RPC_URLS'|'ETHEREUM_FORK_RPC_URL';
export type OperationalGasStage={phase:'OPEN'|'EMERGENCY_FULL_EXIT';stage:string;transactionAction:string;estimatedGas:bigint;bufferedGas:bigint;actualGasUsed:bigint;receiptStatus:'SUCCESS';receiptBlock:bigint;destinationVerified:true;selectorVerified:true;valueVerified:true;successfulForkSimulationReceipt:true};

const buffered=(gas:bigint)=>(gas*12n+9n)/10n;
const sum=(values:readonly bigint[])=>values.reduce((total,value)=>total+value,0n);
const decimal=(value:bigint)=>formatUnits(value,18);
const usd=(value:bigint,nativeUsd?:number)=>nativeUsd===undefined?undefined:Number(decimal(value))*nativeUsd;

export function operationalForkSource(input:{chain:'bsc'|'ethereum';directProviderUrl:string;env?:NodeJS.ProcessEnv}){const env=input.env??process.env,forkKey=input.chain==='bsc'?'BSC_FORK_RPC_URL' as const:'ETHEREUM_FORK_RPC_URL' as const,directKey=input.chain==='bsc'?'BSC_RPC_URLS' as const:'ETHEREUM_RPC_URLS' as const,configured=env[forkKey]?.trim();return configured?{forkUrl:configured,forkSourceKey:forkKey}:{forkUrl:input.directProviderUrl,forkSourceKey:directKey};}

export function buildEmergencyExitTransactions(input:{chainId:GuardedV3Chain;protocol:GuardedV3Protocol;tokenId:bigint;liquidity:bigint;recipient:Address;deadline:bigint;nowUnix:bigint}){if(input.liquidity<=0n)throw new Error('OPERATIONAL_GAS_FLOOR_EXIT_LIQUIDITY_INVALID');return [{stage:'FULL_CLOSE_DECREASE',transaction:buildGuardedV3Decrease({chainId:input.chainId,protocol:input.protocol,tokenId:input.tokenId,liquidity:input.liquidity,fullLiquidity:input.liquidity,amount0Min:0n,amount1Min:0n,deadline:input.deadline,nowUnix:input.nowUnix})},{stage:'COLLECT',transaction:buildGuardedV3Collect({chainId:input.chainId,protocol:input.protocol,tokenId:input.tokenId,recipient:input.recipient})},{stage:'BURN',transaction:buildGuardedV3Burn({chainId:input.chainId,protocol:input.protocol,tokenId:input.tokenId})}] as const;}

export function buildOperationalGasFloorResult(input:{chainId:GuardedV3Chain;protocol:GuardedV3Protocol;stages:readonly OperationalGasStage[];feeQuote:ChainFeeQuote;feeEvidenceRevision:string;feeEvidenceMaxAgeMs:number;currentProductionNativeBalance:bigint;nativeUsd?:number;providerProvenance:CalibrationProviderProvenance;forkSourceKey:OperationalForkSourceKey;forkBlock:bigint;deploymentEvidenceRevision:string;nowMs:number}){
 assertFreshFeeQuote(chainProfile(input.chainId),input.feeQuote,{nowMs:input.nowMs,maxAgeMs:input.feeEvidenceMaxAgeMs});
 const chain=chainProfile(input.chainId).key,expectedProviderKey=input.chainId===56?'BSC_RPC_URLS':'ETHEREUM_RPC_URLS',allowedForkKeys=input.chainId===56?['BSC_RPC_URLS','BSC_FORK_RPC_URL']:['ETHEREUM_RPC_URLS','ETHEREUM_FORK_RPC_URL'];if(input.providerProvenance.requestedChainAlias!==chain||input.providerProvenance.expectedChainId!==input.chainId||input.providerProvenance.observedChainId!==input.chainId||input.providerProvenance.providerSourceKey!==expectedProviderKey||!allowedForkKeys.includes(input.forkSourceKey))throw new Error('OPERATIONAL_GAS_FLOOR_REPORT_PROVENANCE_INVALID');
 const open=input.stages.filter(stage=>stage.phase==='OPEN'),exit=input.stages.filter(stage=>stage.phase==='EMERGENCY_FULL_EXIT');if(!open.length||exit.length!==3)throw new Error('OPERATIONAL_GAS_FLOOR_STAGE_SET_INCOMPLETE');if(new Set(input.stages.map(stage=>`${stage.phase}:${stage.stage}`)).size!==input.stages.length)throw new Error('OPERATIONAL_GAS_FLOOR_DUPLICATE_STAGE');if(exit.map(stage=>stage.transactionAction).join(',')!=='full_close,collect,burn')throw new Error('OPERATIONAL_GAS_FLOOR_EXIT_SCOPE_INVALID');if(exit.some(stage=>stage.transactionAction==='mint'||stage.transactionAction==='approval'))throw new Error('OPERATIONAL_GAS_FLOOR_REPLACEMENT_OR_APPROVAL_FORBIDDEN');for(const stage of input.stages){if(stage.receiptStatus!=='SUCCESS'||!stage.successfulForkSimulationReceipt||stage.estimatedGas<=0n||stage.actualGasUsed<=0n||stage.bufferedGas!==buffered(stage.estimatedGas))throw new Error('OPERATIONAL_GAS_FLOOR_STAGE_EVIDENCE_INVALID');}
 const feePerGas=input.feeQuote.feeModel==='legacy'?input.feeQuote.gasPrice:input.feeQuote.maxFeePerGas,openGas=sum(open.map(stage=>stage.estimatedGas)),openBufferedGas=sum(open.map(stage=>stage.bufferedGas)),exitGas=sum(exit.map(stage=>stage.estimatedGas)),exitBufferedGas=sum(exit.map(stage=>stage.bufferedGas)),totalGas=openGas+exitGas,totalBufferedGas=openBufferedGas+exitBufferedGas,openNative=openBufferedGas*feePerGas,exitNative=exitBufferedGas*feePerGas,totalNative=openNative+exitNative,deficit=input.currentProductionNativeBalance>=totalNative?0n:totalNative-input.currentProductionNativeBalance;
 const stageGasSum=sum(input.stages.map(stage=>stage.estimatedGas)),bufferedStageGasSum=sum(input.stages.map(stage=>stage.bufferedGas));if(stageGasSum!==totalGas||bufferedStageGasSum!==totalBufferedGas||totalNative!==totalBufferedGas*feePerGas||deficit!==(input.currentProductionNativeBalance>=totalNative?0n:totalNative-input.currentProductionNativeBalance))throw new Error('OPERATIONAL_GAS_FLOOR_REPORT_ARITHMETIC_INVALID');
 return {status:'OPERATIONAL_GAS_FLOOR_VERIFIED' as const,openStatus:'OPEN_GAS_CALIBRATION_VERIFIED' as const,emergencyExitStatus:'EMERGENCY_EXIT_GAS_CALIBRATION_VERIFIED' as const,actionableOpenStatus:'ACTIONABLE_OPEN_NOT_CONFIGURED' as const,liveExecutionStatus:'LIVE_EXECUTION_DISABLED' as const,chain,chainId:input.chainId,protocol:input.protocol,stages:input.stages,exitNativeHandling:'NO_UNWRAP_STAGE_APPLICABLE_TO_CURRENT_GUARDED_EXIT',budgets:{OPEN:{rawGas:openGas,bufferedGas:openBufferedGas,bufferedNative:openNative,bufferedNativeDecimal:decimal(openNative),usdEquivalent:usd(openNative,input.nativeUsd)},EMERGENCY_FULL_EXIT:{rawGas:exitGas,bufferedGas:exitBufferedGas,bufferedNative:exitNative,bufferedNativeDecimal:decimal(exitNative),usdEquivalent:usd(exitNative,input.nativeUsd)},TOTAL_OPERATIONAL_FLOOR:{rawGas:totalGas,bufferedGas:totalBufferedGas,bufferedNative:totalNative,bufferedNativeDecimal:decimal(totalNative),currentProductionNativeBalance:input.currentProductionNativeBalance,currentProductionNativeBalanceDecimal:decimal(input.currentProductionNativeBalance),operationalFundingDeficit:deficit,operationalFundingDeficitDecimal:decimal(deficit),usdEquivalent:usd(totalNative,input.nativeUsd),fundingDeficitUsd:usd(deficit,input.nativeUsd)}},feeEvidence:{model:input.feeQuote.feeModel,feePerGas,revision:input.feeEvidenceRevision},provenance:{...input.providerProvenance,forkSource:'ANVIL_FORK' as const,forkSourceKey:input.forkSourceKey,forkChainId:input.chainId,forkBlock:input.forkBlock,deploymentEvidenceRevision:input.deploymentEvidenceRevision},reportConsistency:{stageGasSum,lifecycleGas:totalGas,bufferedStageGasSum,bufferedLifecycleGas:totalBufferedGas,nativeEqualsBufferedGasTimesFee:true,deficitArithmeticExact:true,decimalConversionsFromRawIntegers:true},signerConstructed:false,productionNonceReserved:false,productionJournalWritten:false,authorizationCreated:false,signingUsed:false,mainnetBroadcastUsed:false,executionReady:false,calibrationParametersPromotableToExecution:false,productionWalletCapitalUsed:false,forkOnlySigningUsed:true};
}

async function unusedPort(){return new Promise<number>((resolve,reject)=>{const server=createServer();server.once('error',reject);server.listen(0,'127.0.0.1',()=>{const address=server.address();if(!address||typeof address==='string')return reject(new Error('OPERATIONAL_GAS_FLOOR_ANVIL_PORT_UNAVAILABLE'));const port=address.port;server.close(error=>error?reject(error):resolve(port));});});}

export async function runOperationalGasFloor(input:{chainId:GuardedV3Chain;protocol:GuardedV3Protocol;poolAddress:Address;deploymentEvidence:CanonicalDeploymentVerificationEvidence;feeQuote:ChainFeeQuote;feeEvidenceRevision:string;feeEvidenceMaxAgeMs:number;currentProductionNativeBalance:bigint;nativeUsd?:number;providerProvenance:CalibrationProviderProvenance;forkUrl:string;forkSourceKey:OperationalForkSourceKey;anvilBin:string;nowMs?:number}){
 const nowMs=input.nowMs??Date.now(),profile=chainProfile(input.chainId),deployment=protocolDeployment(input.chainId,input.protocol);if(input.providerProvenance.expectedChainId!==input.chainId||input.providerProvenance.observedChainId!==input.chainId||input.providerProvenance.requestedChainAlias!==profile.key||input.providerProvenance.providerSetRevision!==input.deploymentEvidence.providerSetRevision)throw new Error('OPERATIONAL_GAS_FLOOR_PROVIDER_PROVENANCE_INVALID');if(input.deploymentEvidence.status!=='VERIFIED'||input.deploymentEvidence.chainId!==input.chainId||input.deploymentEvidence.protocol!==input.protocol||input.deploymentEvidence.deploymentVersion!==deployment.registryVersion||input.deploymentEvidence.validUntilMs<nowMs)throw new Error('OPERATIONAL_GAS_FLOOR_DEPLOYMENT_EVIDENCE_INVALID');const expectedForkKeys=input.chainId===56?['BSC_RPC_URLS','BSC_FORK_RPC_URL']:['ETHEREUM_RPC_URLS','ETHEREUM_FORK_RPC_URL'];if(!expectedForkKeys.includes(input.forkSourceKey))throw new Error('OPERATIONAL_GAS_FLOOR_FORK_SOURCE_MISMATCH');
 const upstreamRpc=new FallbackRpc({chainId:input.chainId,name:`${profile.displayName} fork upstream`,nativeSymbol:profile.nativeSymbol,rpcUrls:[input.forkUrl],assets:{}},[input.forkUrl],{timeoutMs:8_000});if(await upstreamRpc.clients[0]!.getChainId()!==input.chainId)throw new Error('OPERATIONAL_GAS_FLOOR_FORK_UPSTREAM_CHAIN_MISMATCH');const port=await unusedPort(),localUrl=`http://127.0.0.1:${port}`,child=spawn(input.anvilBin,['--fork-url',input.forkUrl,'--fork-block-number',input.deploymentEvidence.verifiedBlock.toString(),'--chain-id',String(input.chainId),'--port',String(port),'-q'],{stdio:'ignore'});let spawnError:Error|undefined;child.once('error',error=>{spawnError=error;});const rpc=new FallbackRpc({chainId:input.chainId,name:`${profile.displayName} operational gas-floor fork`,nativeSymbol:profile.nativeSymbol,rpcUrls:[localUrl],assets:{}},[localUrl],{timeoutMs:15_000});
 try{let ready=false;for(let attempt=0;attempt<100;attempt++){if(spawnError)throw new Error('OPERATIONAL_GAS_FLOOR_ANVIL_START_FAILED');try{if(await rpc.clients[0]!.getChainId()===input.chainId){ready=true;break;}}catch{}await new Promise(resolve=>setTimeout(resolve,100));}if(!ready)throw new Error('OPERATIONAL_GAS_FLOOR_ANVIL_START_FAILED');const client=rpc.clients[0]!;await (client as any).request({method:'anvil_setBalance',params:[forkAccount.address,toHex(10n**21n)]});const plan=await planGuardedV3OpenCalibration({rpc,chainId:input.chainId,protocol:input.protocol,poolAddress:input.poolAddress,calibrationSource:'ANVIL_FORK',recipient:forkAccount.address});if(input.chainId===56){const mintOverride=plan.stages.find(stage=>stage.stage==='NATIVE_WRAP_AND_MINT')?.stateOverride as any[]|undefined,tokenOverride=mintOverride?.find(item=>item.address.toLowerCase()!==forkAccount.address.toLowerCase()),balanceDiff=tokenOverride?.stateDiff?.[0];if(!tokenOverride||!balanceDiff)throw new Error('OPERATIONAL_GAS_FLOOR_BSC_SYNTHETIC_TOKEN_FUNDING_UNAVAILABLE');await (client as any).request({method:'anvil_setStorageAt',params:[tokenOverride.address,balanceDiff.slot,balanceDiff.value]});}
  const wallet=createWalletClient({account:forkAccount,chain:{id:input.chainId,name:profile.displayName,nativeCurrency:{name:profile.nativeSymbol,symbol:profile.nativeSymbol,decimals:18},rpcUrls:{default:{http:[localUrl]}}},transport:http(localUrl,{timeout:15_000})}),execute=async(phase:'OPEN'|'EMERGENCY_FULL_EXIT',stage:string,transaction:V3BuiltTransaction):Promise<OperationalGasStage>=>{assertGuardedV3TransactionSemantics(transaction);const request={account:forkAccount.address,to:transaction.to,data:transaction.data,value:transaction.value};await client.call(request);const estimatedGas=await client.estimateGas(request),bufferedGas=buffered(estimatedGas),hash=await wallet.sendTransaction({to:transaction.to,data:transaction.data,value:transaction.value,gas:bufferedGas} as any),receipt=await client.waitForTransactionReceipt({hash});if(receipt.status!=='success')throw new Error(`OPERATIONAL_GAS_FLOOR_FORK_STAGE_REVERTED:${stage}`);return {phase,stage,transactionAction:transaction.action,estimatedGas,bufferedGas,actualGasUsed:receipt.gasUsed,receiptStatus:'SUCCESS',receiptBlock:receipt.blockNumber,destinationVerified:true,selectorVerified:true,valueVerified:true,successfulForkSimulationReceipt:true};},stages:OperationalGasStage[]=[];for(const stage of plan.stages)stages.push(await execute('OPEN',stage.stage,stage.transaction));const manager=deployment.contracts.positionManager!,count=await client.readContract({address:manager,abi:enumerableAbi,functionName:'balanceOf',args:[forkAccount.address]});if(count<=0n)throw new Error('OPERATIONAL_GAS_FLOOR_SYNTHETIC_NFT_MISSING');const tokenId=await client.readContract({address:manager,abi:enumerableAbi,functionName:'tokenOfOwnerByIndex',args:[forkAccount.address,count-1n]}),position=await inspectV3FamilyPosition({rpc,chainId:input.chainId,protocol:input.protocol,tokenId});if(position.status!=='available'||position.value.liquidity<=0n)throw new Error('OPERATIONAL_GAS_FLOOR_SYNTHETIC_LIQUIDITY_MISSING');const block=await client.getBlock({blockTag:'latest'}),deadline=block.timestamp+600n,exit=buildEmergencyExitTransactions({chainId:input.chainId,protocol:input.protocol,tokenId,liquidity:position.value.liquidity,recipient:forkAccount.address,deadline,nowUnix:block.timestamp});for(const stage of exit)stages.push(await execute('EMERGENCY_FULL_EXIT',stage.stage,stage.transaction));return buildOperationalGasFloorResult({chainId:input.chainId,protocol:input.protocol,stages,feeQuote:input.feeQuote,feeEvidenceRevision:input.feeEvidenceRevision,feeEvidenceMaxAgeMs:input.feeEvidenceMaxAgeMs,currentProductionNativeBalance:input.currentProductionNativeBalance,nativeUsd:input.nativeUsd,providerProvenance:input.providerProvenance,forkSourceKey:input.forkSourceKey,forkBlock:input.deploymentEvidence.verifiedBlock,deploymentEvidenceRevision:input.deploymentEvidence.evidenceRevision,nowMs});
 }finally{child.kill('SIGTERM');}
}
