import { createHash } from 'node:crypto';
import { keccak256, parseTransaction, recoverTransactionAddress, size, type Address, type Hash, type Hex, type PublicClient, type TransactionReceipt, type WalletClient } from 'viem';
import { sanitizeRpcError, sanitizeSensitiveText, type FallbackRpc } from '@robin/core';
import type { SqliteLedgerRepository } from '@robin/ledger';
import { parseCurrencyTransfers } from '@robin/v4';
import { assertRebalanceCommitmentNotPermanentlyReleased } from './rebalance-commitment-release.js';

const json=(value:unknown)=>JSON.stringify(value,(_,item)=>typeof item==='bigint'?item.toString():item);
const parse=<T>(value:string)=>JSON.parse(value,(key,item)=>/^(gas|gasPrice|value)$/.test(key)&&typeof item==='string'?BigInt(item):item) as T;
export type RebalanceTxLimits={maxTxGasUsd:number;maxLifecycleGasUsd:number;nativeUsd:number};
export type RebalanceTxHooks={beforeSubmit?:(semanticStage:string)=>void|Promise<void>;afterBroadcast?:(semanticStage:string,hash:Hash)=>void|Promise<void>;beforeReceipt?:(semanticStage:string,hash:Hash)=>void|Promise<void>};
export type RebalanceTxInput={
 repo:SqliteLedgerRepository;rpc:FallbackRpc;walletClient:WalletClient;wallet:Address;workflowId:string;
 semanticStage:string;to:Address;data:Hex;limits:RebalanceTxLimits;hooks?:RebalanceTxHooks;
};
type PreparedRequest={account:Address;chainId:number;to:Address;data:Hex;value:bigint;gas:bigint;gasPrice:bigint;nonce:number};
type TxRow={id:string;workflow_id:string;semantic_stage:string;attempt:number;status:string;tx_hash:string;nonce:number;request_json:string;receipt_json:string|null;created_at:string;submitted_at:string|null;confirmed_at:string|null;updated_at:string;failure_reason:string|null};
export type ExactHashEvidence=
 |{kind:'RECEIPT';receipt:TransactionReceipt}
 |{kind:'PENDING';nonce:number}
 |{kind:'ABSENT';latestNonce:number;pendingNonce:number}
 |{kind:'INCONCLUSIVE';reason:'PROVIDER_ERROR'|'PROVIDER_DISAGREEMENT'|'NONCE_EVIDENCE_INVALID'|'MALFORMED_EVIDENCE'};

export function rebalanceResumeRecoveryCandidate(workflowId:string,rows:Array<Record<string,unknown>>){
 if(!rows.length)return undefined;const row=rows[0];
 if(rows.length!==1||!row||String(row.workflow_id)!==workflowId||!['PREPARED','SUBMITTED'].includes(String(row.status)))throw new Error('REBALANCE_LATER_TRANSACTION_EXISTS');
 return row;
}
export function rebalanceActualGasUsd(repo:SqliteLedgerRepository,workflowId:string){const row=repo.db.prepare("SELECT COALESCE(SUM(actual_gas_usd),0) value FROM rebalance_transactions WHERE workflow_id=? AND status='CONFIRMED'").get(workflowId) as {value:number};return Number(row.value);}
export function conservativeGasUsd(gas:bigint,gasPrice:bigint,nativeUsd:number){const usd=Number(gas*gasPrice)/1e18*nativeUsd;if(!Number.isFinite(usd)||usd<0)throw new Error('REBALANCE_GAS_ESTIMATE_UNAVAILABLE');return usd;}
export function bufferedBroadcastGasPrice(observedGasPrice:bigint){if(observedGasPrice<=0n)throw new Error('TRANSACTION_GAS_PRICE_INVALID');return observedGasPrice*12n/10n;}
export function assertRebalanceGas(input:{estimatedGasUsd:number;spentGasUsd:number;limits:RebalanceTxLimits}){if(!Number.isFinite(input.limits.nativeUsd)||input.limits.nativeUsd<=0||!Number.isFinite(input.estimatedGasUsd))throw new Error('REBALANCE_GAS_ESTIMATE_UNAVAILABLE');if(input.estimatedGasUsd>input.limits.maxTxGasUsd)throw new Error('TX_GAS_CAP_EXCEEDED');if(input.spentGasUsd+input.estimatedGasUsd>input.limits.maxLifecycleGasUsd)throw new Error('LIFECYCLE_GAS_BUDGET_EXCEEDED');}
function rowById(repo:SqliteLedgerRepository,id:string){return repo.db.prepare('SELECT * FROM rebalance_transactions WHERE id=?').get(id) as TxRow|undefined;}
function confirmed(repo:SqliteLedgerRepository,workflowId:string,semanticStage:string){return repo.db.prepare("SELECT * FROM rebalance_transactions WHERE workflow_id=? AND semantic_stage=? AND status='CONFIRMED' ORDER BY attempt DESC LIMIT 1").get(workflowId,semanticStage) as TxRow|undefined;}
function latest(repo:SqliteLedgerRepository,workflowId:string,semanticStage:string){return repo.db.prepare('SELECT * FROM rebalance_transactions WHERE workflow_id=? AND semantic_stage=? ORDER BY attempt DESC LIMIT 1').get(workflowId,semanticStage) as TxRow|undefined;}
async function waitReceipt(rpc:FallbackRpc,hash:Hash){const receipt=await rpc.withClient(client=>client.waitForTransactionReceipt({hash,timeout:60_000}),{stage:'receipt_recovery',method:'eth_getTransactionReceipt'}),valid=validatedReceipt(receipt,hash);if(!valid)throw new Error('REBALANCE_RECEIPT_EVIDENCE_INCONCLUSIVE:MALFORMED_EVIDENCE');return valid;}
function transactionNotFound(error:unknown){return /not found|could not be found|unknown transaction/i.test(error instanceof Error?error.message:String(error));}
function validHash(value:unknown):value is Hash{return typeof value==='string'&&/^0x[0-9a-fA-F]{64}$/.test(value);}
function validAddress(value:unknown):value is Address{return typeof value==='string'&&/^0x[0-9a-fA-F]{40}$/.test(value);}
function validatedReceipt(value:unknown,hash:Hash):TransactionReceipt|undefined{if(!value||typeof value!=='object')return undefined;const row=value as Record<string,unknown>;if(!validHash(row.transactionHash)||row.transactionHash.toLowerCase()!==hash.toLowerCase()||(row.status!=='success'&&row.status!=='reverted')||typeof row.blockNumber!=='bigint'||row.blockNumber<0n||typeof row.gasUsed!=='bigint'||row.gasUsed<0n||typeof row.effectiveGasPrice!=='bigint'||row.effectiveGasPrice<0n)return undefined;return value as TransactionReceipt;}
function validatedPending(value:unknown,wallet:Address,hash:Hash,expectedNonce?:number){if(!value||typeof value!=='object')return undefined;const row=value as Record<string,unknown>,nonce=row.nonce;if(!validHash(row.hash)||row.hash.toLowerCase()!==hash.toLowerCase()||typeof nonce!=='number'||!Number.isSafeInteger(nonce)||nonce<0||!validAddress(row.from)||row.from.toLowerCase()!==wallet.toLowerCase()||row.blockNumber!==null||(expectedNonce!==undefined&&nonce!==expectedNonce))return undefined;return nonce;}
async function providerEvidence(client:PublicClient,wallet:Address,hash:Hash,expectedNonce?:number):Promise<ExactHashEvidence>{
 try{const receipt=await client.getTransactionReceipt({hash}),valid=validatedReceipt(receipt,hash);return valid?{kind:'RECEIPT',receipt:valid}:{kind:'INCONCLUSIVE',reason:'MALFORMED_EVIDENCE'};}catch(error){if(!transactionNotFound(error))return {kind:'INCONCLUSIVE',reason:'PROVIDER_ERROR'};}
 try{const transaction=await client.getTransaction({hash}),nonce=validatedPending(transaction,wallet,hash,expectedNonce);return nonce===undefined?{kind:'INCONCLUSIVE',reason:'MALFORMED_EVIDENCE'}:{kind:'PENDING',nonce};}catch(error){if(!transactionNotFound(error))return {kind:'INCONCLUSIVE',reason:'PROVIDER_ERROR'};}
 try{const [latestNonce,pendingNonce]=await Promise.all([client.getTransactionCount({address:wallet,blockTag:'latest'}),client.getTransactionCount({address:wallet,blockTag:'pending'})]);if(!Number.isSafeInteger(latestNonce)||latestNonce<0||!Number.isSafeInteger(pendingNonce)||pendingNonce<0||pendingNonce<latestNonce)return {kind:'INCONCLUSIVE',reason:'NONCE_EVIDENCE_INVALID'};return {kind:'ABSENT',latestNonce,pendingNonce};}catch{return {kind:'INCONCLUSIVE',reason:'PROVIDER_ERROR'};}
}
function evidenceIdentity(evidence:ExactHashEvidence){if(evidence.kind==='RECEIPT')return `${evidence.kind}:${evidence.receipt.status}:${evidence.receipt.transactionHash.toLowerCase()}:${evidence.receipt.blockNumber}`;if(evidence.kind==='PENDING')return `${evidence.kind}:${evidence.nonce}`;if(evidence.kind==='ABSENT')return `${evidence.kind}:${evidence.latestNonce}:${evidence.pendingNonce}`;return evidence.kind;}
export async function rebalanceExactHashEvidence(rpc:FallbackRpc,wallet:Address,hash:Hash,expectedNonce?:number):Promise<ExactHashEvidence>{
 const direct=(rpc as unknown as {clients?:PublicClient[]}).clients,observations=direct?.length?await Promise.all(direct.map(client=>providerEvidence(client,wallet,hash,expectedNonce))):[await rpc.withClient(client=>providerEvidence(client,wallet,hash,expectedNonce),{stage:'transaction_recovery',method:'eth_getTransactionReceipt+eth_getTransaction+eth_getTransactionCount'})];
 const malformed=observations.find(item=>item.kind==='INCONCLUSIVE');if(malformed?.kind==='INCONCLUSIVE')return malformed;const identity=evidenceIdentity(observations[0]!);if(observations.some(item=>evidenceIdentity(item)!==identity))return {kind:'INCONCLUSIVE',reason:'PROVIDER_DISAGREEMENT'};return observations[0]!;
}
const stable=(value:unknown):string=>{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return `[${value.map(stable).join(',')}]`;const row=value as Record<string,unknown>;return `{${Object.keys(row).sort().map(key=>`${JSON.stringify(key)}:${stable(row[key])}`).join(',')}}`;};
const fingerprint=(value:unknown)=>createHash('sha256').update(stable(value)).digest('hex');
function exactReconcileRows(repo:SqliteLedgerRepository,workflowId:string,semanticStage:string){
 const workflow=repo.db.prepare('SELECT id,state,revision,state_json,execution_json,old_position_id,actual_gas_usd FROM rebalance_workflows WHERE id=?').get(workflowId) as Record<string,unknown>|undefined;if(!workflow)throw new Error('REBALANCE_WORKFLOW_NOT_FOUND');
 const transaction=repo.db.prepare('SELECT * FROM rebalance_transactions WHERE workflow_id=? AND semantic_stage=? ORDER BY attempt DESC LIMIT 1').get(workflowId,semanticStage) as TxRow|undefined;if(!transaction)throw new Error('REBALANCE_TRANSACTION_NOT_FOUND');
 const action=semanticStage==='CLOSE_FULL'?'full_close':semanticStage==='CLOSE_BURN'?'burn':undefined;if(!action)throw new Error('REBALANCE_EXACT_HASH_RECONCILE_STAGE_UNSUPPORTED');
 const lifecycle=repo.db.prepare("SELECT * FROM v4_lifecycle_intents WHERE idempotency_key LIKE ? AND action=? ORDER BY created_at DESC LIMIT 1").get(`rebalance:${workflowId}:${action}:%`,action) as Record<string,unknown>|undefined;if(!lifecycle)throw new Error('REBALANCE_LIFECYCLE_INTENT_NOT_FOUND');
 if(lifecycle.tx_hash&&String(lifecycle.tx_hash).toLowerCase()!==transaction.tx_hash.toLowerCase())throw new Error('REBALANCE_LIFECYCLE_HASH_CONFLICT');
 return {workflow,transaction,lifecycle,action};
}
export async function previewRebalanceExactHashReconciliation(repo:SqliteLedgerRepository,rpc:FallbackRpc,wallet:Address,workflowId:string,semanticStage:string){
 const current=exactReconcileRows(repo,workflowId,semanticStage),tx=current.transaction;if(!['PREPARED','SUBMITTED','CONFIRMED'].includes(tx.status)||!validHash(tx.tx_hash)||!Number.isSafeInteger(tx.nonce)||tx.nonce<0)throw new Error('REBALANCE_EXACT_HASH_RECONCILE_JOURNAL_INVALID');
 const evidence=await rebalanceExactHashEvidence(rpc,wallet,tx.tx_hash as Hash,tx.nonce);if(evidence.kind!=='RECEIPT'||evidence.receipt.status!=='success')throw new Error(evidence.kind==='INCONCLUSIVE'?`REBALANCE_EXACT_HASH_RECONCILE_AMBIGUOUS:${evidence.reason}`:'REBALANCE_EXACT_HASH_NOT_CONFIRMED');
 const position=repo.v4Position(String(current.workflow.old_position_id).replace(/^v4:/,''));if(!position||String(position.owner).toLowerCase()!==wallet.toLowerCase())throw new Error('REBALANCE_EXACT_HASH_RECONCILE_WALLET_MISMATCH');if(current.action==='full_close'&&BigInt(String(position.liquidity_raw))!==0n)throw new Error('REBALANCE_EXACT_HASH_RECONCILE_POSITION_NOT_CLOSED');
 const journal={workflow:current.workflow,transaction:tx,lifecycle:current.lifecycle,rebalanceReceipt:repo.db.prepare('SELECT stage,tx_hash,receipt_json FROM rebalance_receipts WHERE workflow_id=? AND stage=?').get(workflowId,current.action==='full_close'?'close-full':'close-burn')??null,lifecycleReceipt:repo.db.prepare('SELECT tx_hash,receipt_json FROM v4_lifecycle_receipts WHERE intent_id=?').get(String(current.lifecycle.id))??null};
 const journalFingerprint=fingerprint(journal),receipt=evidence.receipt;
 return {workflowId,transactionRowId:tx.id,semanticStage,exactHash:tx.tx_hash,nonce:tx.nonce,receiptBlock:Number(receipt.blockNumber),receiptStatus:receipt.status,currentJournalState:{transactionStatus:tx.status,lifecycleState:String(current.lifecycle.state),workflowState:String(current.workflow.state)},proposedRowChanges:['rebalance_transactions:CONFIRMED','rebalance_receipts:exact stage receipt','v4_lifecycle_intents:RECONCILED','v4_lifecycle_receipts:exact receipt','v4_lifecycle_transitions:SUBMITTED→CONFIRMED→RECONCILED','gas_costs:idempotent exact-hash row','rebalance_workflows:CLOSE_FULL_CONFIRMED'],resultingWorkflowCheckpoint:semanticStage==='CLOSE_FULL'?{confirmedStage:'CLOSE_FULL',nextResumableStage:'CLOSE_BURN'}:{confirmedStage:'CLOSE_BURN'},journalFingerprint,receipt};
}
export function exactHashReconcileToken(input:{workflowId:string;transactionRowId:string;semanticStage:string;exactHash:string;nonce:number;receiptBlock:number;receiptStatus:string;journalFingerprint:string;expiresAt:number}){return Buffer.from(JSON.stringify(input)).toString('base64url');}
export function verifyExactHashReconcileToken(token:string,input:{workflowId:string;transactionRowId:string;semanticStage:string;exactHash:string;nonce:number;receiptBlock:number;receiptStatus:string;journalFingerprint:string;now?:number}){try{const value=JSON.parse(Buffer.from(token,'base64url').toString('utf8'));return value.workflowId===input.workflowId&&value.transactionRowId===input.transactionRowId&&value.semanticStage===input.semanticStage&&String(value.exactHash).toLowerCase()===input.exactHash.toLowerCase()&&Number(value.nonce)===input.nonce&&Number(value.receiptBlock)===input.receiptBlock&&value.receiptStatus===input.receiptStatus&&value.journalFingerprint===input.journalFingerprint&&Number(value.expiresAt)>(input.now??Date.now());}catch{return false;}}
export function applyRebalanceExactHashReconciliation(repo:SqliteLedgerRepository,preview:Awaited<ReturnType<typeof previewRebalanceExactHashReconciliation>>){
 const current=exactReconcileRows(repo,preview.workflowId,preview.semanticStage),tx=current.transaction,receipt=preview.receipt,at=new Date().toISOString(),receiptJson=json(receipt),executionState=parse<Record<string,any>>(String(current.workflow.execution_json??'{}')),nativeUsd=Number(executionState.prices?.wethUsd),actualGasUsd=conservativeGasUsd(receipt.gasUsed,receipt.effectiveGasPrice,nativeUsd),positionId=String(current.workflow.old_position_id),tokenId=positionId.replace(/^v4:/,'');
 const already=tx.status==='CONFIRMED'&&String(current.workflow.state)==='CLOSE_FULL_CONFIRMED'&&Boolean(repo.db.prepare('SELECT 1 FROM v4_lifecycle_receipts WHERE intent_id=? AND tx_hash=?').get(String(current.lifecycle.id),tx.tx_hash));if(already)return {status:'ALREADY_RECONCILED' as const,workflowCheckpoint:'CLOSE_FULL_CONFIRMED',nextResumableStage:'CLOSE_BURN'};
 repo.db.transaction(()=>{
  const durable=exactReconcileRows(repo,preview.workflowId,preview.semanticStage);if(fingerprint({workflow:durable.workflow,transaction:durable.transaction,lifecycle:durable.lifecycle,rebalanceReceipt:repo.db.prepare('SELECT stage,tx_hash,receipt_json FROM rebalance_receipts WHERE workflow_id=? AND stage=?').get(preview.workflowId,'close-full')??null,lifecycleReceipt:repo.db.prepare('SELECT tx_hash,receipt_json FROM v4_lifecycle_receipts WHERE intent_id=?').get(String(durable.lifecycle.id))??null})!==preview.journalFingerprint)throw new Error('REBALANCE_EXACT_HASH_RECONCILE_EVIDENCE_CHANGED');
  repo.db.prepare("UPDATE rebalance_transactions SET status='CONFIRMED',receipt_json=?,actual_gas_raw=?,actual_gas_usd=?,submitted_at=COALESCE(submitted_at,?),confirmed_at=COALESCE(confirmed_at,?),failure_reason=NULL,updated_at=? WHERE id=? AND tx_hash=? AND status IN ('PREPARED','SUBMITTED','CONFIRMED')").run(receiptJson,receipt.gasUsed.toString(),actualGasUsd,at,at,at,tx.id,tx.tx_hash);
  repo.db.prepare('INSERT OR IGNORE INTO v4_lifecycle_receipts(tx_hash,intent_id,receipt_json,created_at) VALUES(?,?,?,?)').run(tx.tx_hash,String(current.lifecycle.id),receiptJson,at);
  for(const state of ['SUBMITTED','CONFIRMED','RECONCILED'])repo.db.prepare('INSERT OR IGNORE INTO v4_lifecycle_transitions(intent_id,ordinal,state,details_json,created_at) SELECT ?,COALESCE(MAX(ordinal),-1)+1,?,?,? FROM v4_lifecycle_transitions WHERE intent_id=?').run(String(current.lifecycle.id),state,json({exactHash:tx.tx_hash,blockNumber:receipt.blockNumber}),at,String(current.lifecycle.id));
  repo.db.prepare("UPDATE v4_lifecycle_intents SET state='RECONCILED',tx_hash=?,failure_reason=NULL,updated_at=? WHERE id=?").run(tx.tx_hash,at,String(current.lifecycle.id));
  if(current.action==='full_close'){const payload=parse<Record<string,any>>(String(current.lifecycle.payload_json)),prepared=payload.prepared;if(!prepared?.key||!prepared?.principal)throw new Error('REBALANCE_LIFECYCLE_PREPARATION_MISSING');const principal={token0:BigInt(prepared.principal.token0),token1:BigInt(prepared.principal.token1)},transfers=parseCurrencyTransfers(receipt.logs, String((repo.v4Position(tokenId) as Record<string,unknown>).owner) as Address,prepared.key),pending=repo.positionAccounting(positionId).pendingPrincipal;repo.ingestLiquidityChange({id:`v4:${tx.tx_hash}:decrease`,positionId,txHash:tx.tx_hash,logIndex:0,kind:'decrease',amounts:principal});repo.ingestCollection({id:`v4:${tx.tx_hash}:collect`,positionId,txHash:tx.tx_hash,logIndex:1,amounts:transfers,pending});repo.ingestGas(positionId,tx.tx_hash,receipt.gasUsed*receipt.effectiveGasPrice);const totals=repo.collectionTotals(positionId);repo.db.prepare("UPDATE v4_positions SET liquidity_raw='0',status='closed',claimed_fee0_raw=?,claimed_fee1_raw=?,withdrawn_principal0_raw=?,withdrawn_principal1_raw=?,updated_at=? WHERE token_id=?").run(totals.fees.token0.toString(),totals.fees.token1.toString(),totals.principal.token0.toString(),totals.principal.token1.toString(),at,tokenId);}
  repo.db.prepare('INSERT OR IGNORE INTO rebalance_receipts(workflow_id,stage,tx_hash,receipt_json,confirmed_at) VALUES(?,?,?,?,?)').run(preview.workflowId,current.action==='full_close'?'close-full':'close-burn',tx.tx_hash,receiptJson,at);
  if(current.action==='full_close'&&!['CLOSE_FULL_CONFIRMED','CLOSE_CONFIRMED','ASSETS_CLASSIFIED'].includes(String(current.workflow.state))){const details={confirmedStage:'CLOSE_FULL',nextResumableStage:'CLOSE_BURN',exactHash:tx.tx_hash,receiptBlock:receipt.blockNumber};repo.db.prepare("UPDATE rebalance_workflows SET state='CLOSE_FULL_CONFIRMED',revision=revision+1,state_json=?,last_error=NULL,actual_gas_usd=(SELECT COALESCE(SUM(actual_gas_usd),0) FROM rebalance_transactions WHERE workflow_id=? AND status='CONFIRMED'),updated_at=? WHERE id=?").run(json(details),preview.workflowId,at,preview.workflowId);repo.db.prepare("INSERT INTO rebalance_transitions(workflow_id,ordinal,state,details_json,created_at) SELECT ?,COALESCE(MAX(ordinal),-1)+1,'CLOSE_FULL_CONFIRMED',?,? FROM rebalance_transitions WHERE workflow_id=?").run(preview.workflowId,json(details),at,preview.workflowId);}
 })();return {status:'RECONCILED' as const,workflowCheckpoint:'CLOSE_FULL_CONFIRMED',nextResumableStage:'CLOSE_BURN'};
}
const scrubFields=[['rebalance_workflows','id','last_error'],['rebalance_workflows','id','state_json'],['rebalance_transactions','id','failure_reason'],['v4_lifecycle_intents','id','failure_reason'],['v4_state_refresh_queue','pool_id','last_error'],['v4_pool_discovery_cursor','chain_id','last_error'],['active_position_reconciliations','position_id','last_error'],['targeted_position_reconciliation_requests','position_id','last_error'],['portfolio_refresh_requests','request_key','last_error']] as const;
export function errorSecretScrubPlan(repo:SqliteLedgerRepository){const changes:Array<{table:string;key:string|number;column:string;before:string;after:string}>=[];for(const [table,key,column] of scrubFields){const exists=repo.db.prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?").get(table);if(!exists)continue;for(const row of repo.db.prepare(`SELECT ${key} row_key,${column} value FROM ${table} WHERE ${column} IS NOT NULL`).all() as Array<{row_key:string|number;value:string}>){const after=sanitizeSensitiveText(row.value);if(after!==row.value)changes.push({table,key:row.row_key,column,before:row.value,after});}}const counts=Object.entries(changes.reduce<Record<string,number>>((sum,item)=>(sum[item.table]=(sum[item.table]??0)+1,sum),{})).map(([table,rowCount])=>({table,rowCount}));return {counts,totalRows:changes.length,fingerprint:fingerprint(changes.map(({table,key,column,before})=>({table,key,column,before}))),changes};}
export function applyErrorSecretScrub(repo:SqliteLedgerRepository,expectedFingerprint:string){const plan=errorSecretScrubPlan(repo);if(plan.fingerprint!==expectedFingerprint)throw new Error('ERROR_SECRET_SCRUB_EVIDENCE_CHANGED');repo.db.transaction(()=>{for(const item of plan.changes)repo.db.prepare(`UPDATE ${item.table} SET ${item.column}=? WHERE ${scrubFields.find(field=>field[0]===item.table&&field[2]===item.column)![1]}=? AND ${item.column}=?`).run(item.after,item.key,item.before);})();return {counts:plan.counts,totalRows:plan.totalRows};}
export async function signWithConfiguredAccount(walletClient:WalletClient,request:Record<string,unknown>){const signer=walletClient as unknown as {account?:{signTransaction?:unknown};signTransaction(request:Record<string,unknown>):Promise<Hex>};if(!signer.account||typeof signer.account.signTransaction!=='function')throw new Error('REBALANCE_LOCAL_SIGNER_REQUIRED');return signer.signTransaction({...request,account:signer.account});}
export type BroadcastTransportEvidence={providerIndex:number;providerName:string;method:'eth_sendRawTransaction';parameterCount:1;serializedByteLength:number;expectedHashReturnedHashEqual:boolean|null;classification:'REQUESTED'|'ACCEPTED'|'HASH_MISMATCH'|'MALFORMED_RESPONSE'|'TRANSPORT_ERROR';errorCode?:string|number;error?:string};
function sanitizedTransportCode(error:unknown){let current:unknown=error;for(let depth=0;depth<4&&current&&typeof current==='object';depth++){const row=current as Record<string,unknown>,code=row.code??row.status;if((typeof code==='number'&&Number.isFinite(code))||(typeof code==='string'&&/^-?[A-Za-z0-9_.-]{1,40}$/.test(code)))return code as string|number;current=row.cause;}return undefined;}
/** Single canonical signed-transaction broadcast boundary. It validates the
 * envelope locally, invokes JSON-RPC with exactly one raw-byte parameter, and
 * never substitutes the local hash for provider response evidence. */
export async function broadcastSignedTransaction(input:{walletClient:WalletClient;serializedTransaction:Hex;expectedHash:Hash;expectedSender:Address;expectedChainId:number;expectedNonce:number;providerIndex?:number;providerName?:string;onEvidence?:(evidence:BroadcastTransportEvidence)=>void|Promise<void>}){
 const serialized=input.serializedTransaction;if(!/^0x[0-9a-fA-F]+$/.test(serialized)||serialized.length<=2||serialized.length%2!==0)throw new Error('TRANSACTION_SERIALIZED_BYTES_MALFORMED');
 const syntheticFixture=process.env.NODE_ENV==='test'&&(input.walletClient as unknown as {syntheticSerializedTransactionFixture?:boolean}).syntheticSerializedTransactionFixture===true;
 if(!syntheticFixture){let parsed:ReturnType<typeof parseTransaction>,sender:Address;try{parsed=parseTransaction(serialized as Parameters<typeof parseTransaction>[0]);sender=await recoverTransactionAddress({serializedTransaction:serialized as Parameters<typeof recoverTransactionAddress>[0]['serializedTransaction']});}catch{throw new Error('TRANSACTION_SERIALIZED_BYTES_MALFORMED');}
  if(sender.toLowerCase()!==input.expectedSender.toLowerCase()||Number(parsed.chainId)!==input.expectedChainId||Number(parsed.nonce)!==input.expectedNonce)throw new Error('TRANSACTION_SIGNED_ENVELOPE_MISMATCH');}
 const localHash=keccak256(serialized);if(localHash.toLowerCase()!==input.expectedHash.toLowerCase())throw new Error('TRANSACTION_EXPECTED_HASH_MISMATCH');
 const base={providerIndex:input.providerIndex??-1,providerName:input.providerName??'configured-write-provider',method:'eth_sendRawTransaction' as const,parameterCount:1 as const,serializedByteLength:size(serialized)};
 await input.onEvidence?.({...base,expectedHashReturnedHashEqual:null,classification:'REQUESTED'});
 const requester=input.walletClient as unknown as {request(args:{method:'eth_sendRawTransaction';params:[Hex]},options?:{retryCount?:number}):Promise<unknown>};let returned:unknown;
 try{returned=await requester.request({method:'eth_sendRawTransaction',params:[serialized]},{retryCount:0});}
 catch(error){const safe=sanitizeRpcError(error,{stage:'transaction_broadcast',method:'eth_sendRawTransaction'}),errorCode=sanitizedTransportCode(error);await input.onEvidence?.({...base,expectedHashReturnedHashEqual:null,classification:'TRANSPORT_ERROR',...(errorCode===undefined?{}:{errorCode}),error:safe});throw new Error(`TRANSACTION_BROADCAST_TRANSPORT_ERROR:${safe}`);}
 if(typeof returned!=='string'||!/^0x[0-9a-fA-F]{64}$/.test(returned)){await input.onEvidence?.({...base,expectedHashReturnedHashEqual:null,classification:'MALFORMED_RESPONSE'});throw new Error('TRANSACTION_BROADCAST_RESPONSE_MALFORMED');}
 const equal=returned.toLowerCase()===input.expectedHash.toLowerCase();await input.onEvidence?.({...base,expectedHashReturnedHashEqual:equal,classification:equal?'ACCEPTED':'HASH_MISMATCH'});if(!equal)throw new Error('TRANSACTION_PROVIDER_RETURNED_HASH_MISMATCH');
 return returned as Hash;
}
function reconcileReceipt(input:RebalanceTxInput,row:TxRow,hash:Hash,receipt:TransactionReceipt,recovered:boolean){
 if(receipt.status!=='success'){input.repo.db.prepare("UPDATE rebalance_transactions SET status='FAILED',receipt_json=?,failure_reason=?,updated_at=? WHERE id=? AND status<>'CONFIRMED'").run(json(receipt),'TRANSACTION_REVERTED',new Date().toISOString(),row.id);throw new Error(`REBALANCE_TRANSACTION_REVERTED:${input.semanticStage}`);}
 const durable=rowById(input.repo,row.id);if(durable?.status==='CONFIRMED'&&durable.receipt_json)return {hash,receipt:parse<TransactionReceipt>(durable.receipt_json),recovered:true};
 const gasUsed=receipt.gasUsed,effectiveGasPrice=receipt.effectiveGasPrice,actualGasUsd=conservativeGasUsd(gasUsed,effectiveGasPrice,input.limits.nativeUsd),spentBefore=rebalanceActualGasUsd(input.repo,input.workflowId);assertRebalanceGas({estimatedGasUsd:actualGasUsd,spentGasUsd:spentBefore,limits:input.limits});
 const at=new Date().toISOString();input.repo.db.transaction(()=>{input.repo.db.prepare("UPDATE rebalance_transactions SET status='CONFIRMED',actual_gas_raw=?,actual_gas_usd=?,receipt_json=?,confirmed_at=?,updated_at=? WHERE id=? AND status<>'CONFIRMED'").run(gasUsed.toString(),actualGasUsd,json(receipt),at,at,row.id);input.repo.db.prepare("UPDATE rebalance_workflows SET actual_gas_usd=(SELECT COALESCE(SUM(actual_gas_usd),0) FROM rebalance_transactions WHERE workflow_id=? AND status='CONFIRMED'),updated_at=? WHERE id=?").run(input.workflowId,at,input.workflowId);})();return {hash,receipt,recovered};
}
async function recoverReceipt(input:RebalanceTxInput,row:TxRow,hash:Hash,recovered:boolean){try{await input.hooks?.beforeReceipt?.(input.semanticStage,hash);const receipt=await waitReceipt(input.rpc,hash);return reconcileReceipt(input,row,hash,receipt,recovered);}catch(error){if(/TIMEOUT|timed out/i.test(error instanceof Error?error.message:String(error)))throw new Error(`REBALANCE_RECEIPT_RECOVERY_REQUIRED:${input.semanticStage}`);throw error;}}
function markObservedPending(repo:SqliteLedgerRepository,row:TxRow){if(row.status==='SUBMITTED')return row;const at=new Date().toISOString();repo.db.prepare("UPDATE rebalance_transactions SET status='SUBMITTED',submitted_at=COALESCE(submitted_at,?),updated_at=? WHERE id=? AND status='PREPARED'").run(at,at,row.id);return rowById(repo,row.id)??row;}
async function reconcileAmbiguousSend(input:RebalanceTxInput,row:TxRow,hash:Hash){
 const evidence=await rebalanceExactHashEvidence(input.rpc,input.wallet,hash,row.nonce);
 if(evidence.kind==='RECEIPT')return {kind:'RECEIPT' as const,row,receipt:evidence.receipt};
 if(evidence.kind==='PENDING')return {kind:'SUBMITTED' as const,row:markObservedPending(input.repo,row),hash,recovered:true};
 if(evidence.kind==='INCONCLUSIVE')throw new Error(`REBALANCE_BROADCAST_AMBIGUOUS:${evidence.reason}`);
 if(evidence.latestNonce===row.nonce&&evidence.pendingNonce===row.nonce)throw new Error('REBALANCE_BROADCAST_UNPROVEN_HASH_ABSENT_NONCE_AVAILABLE');
 throw new Error('REBALANCE_BROADCAST_UNPROVEN_NONCE_CONSUMED_OR_REPLACED');
}
function freshAttemptRecord(input:RebalanceTxInput,expected:TxRow|undefined,failExpected:boolean,request:PreparedRequest,serialized:Hex,estimatedGas:bigint,estimatedGasUsd:number){
 const hash=keccak256(serialized),attempt=Number(expected?.attempt??-1)+1,id=`${input.workflowId}:${input.semanticStage}:${attempt}`,at=new Date().toISOString();
 const inserted=input.repo.db.transaction(()=>{const current=latest(input.repo,input.workflowId,input.semanticStage);if(current?.id!==expected?.id)return false;if(failExpected){if(!current||!['PREPARED','SUBMITTED'].includes(current.status))return false;const failed=input.repo.db.prepare("UPDATE rebalance_transactions SET status='FAILED',failure_reason='NONCE_NO_LONGER_AVAILABLE' WHERE id=? AND status IN ('PREPARED','SUBMITTED')").run(current.id).changes;if(failed!==1)return false;}else if(current&&['PREPARED','SUBMITTED','CONFIRMED'].includes(current.status))return false;
  input.repo.db.prepare("INSERT INTO rebalance_transactions(id,workflow_id,semantic_stage,attempt,status,tx_hash,nonce,to_address,calldata_hash,request_json,estimated_gas_raw,estimated_gas_usd,created_at,updated_at) VALUES(?,?,?,?, 'PREPARED',?,?,?,?,?,?,?,?,?)").run(id,input.workflowId,input.semanticStage,attempt,hash,request.nonce,input.to,keccak256(input.data),json(request),estimatedGas.toString(),estimatedGasUsd,at,at);return true;})();
 if(!inserted)return {kind:'RACE' as const};const row=rowById(input.repo,id);if(!row)throw new Error('REBALANCE_PREPARED_ROW_MISSING');return {kind:'CREATED' as const,row,hash};
}
async function allocateAndSubmitFresh(input:RebalanceTxInput,expected:TxRow|undefined,failExpected:boolean,recovered:boolean){
 if(input.rpc.config.chainId!==4663)throw new Error('REBALANCE_WRONG_CHAIN');if(!input.repo.acquireNonceMutex(input.wallet,expected?BigInt(expected.nonce):0n))return {kind:'LOCKED' as const};
 try{
  const durable=latest(input.repo,input.workflowId,input.semanticStage);if(durable?.id!==expected?.id||(failExpected&&!['PREPARED','SUBMITTED'].includes(String(durable?.status))))return {kind:'RACE' as const};
  const [estimatedGas,observedGasPrice,nonce]=await input.rpc.withClient(client=>Promise.all([client.estimateGas({account:input.wallet,to:input.to,data:input.data,value:0n}),client.getGasPrice(),client.getTransactionCount({address:input.wallet,blockTag:'pending'})]),{stage:'transaction_prebroadcast',method:'eth_estimateGas+eth_gasPrice+eth_getTransactionCount'}),gasPrice=bufferedBroadcastGasPrice(observedGasPrice),gasLimit=estimatedGas*12n/10n,estimatedGasUsd=conservativeGasUsd(gasLimit,gasPrice,input.limits.nativeUsd),spentGasUsd=rebalanceActualGasUsd(input.repo,input.workflowId);assertRebalanceGas({estimatedGasUsd,spentGasUsd,limits:input.limits});
  const request:PreparedRequest={account:input.wallet,chainId:input.rpc.config.chainId,to:input.to,data:input.data,value:0n,gas:gasLimit,gasPrice,nonce},serialized=await signWithConfiguredAccount(input.walletClient,request),created=freshAttemptRecord(input,expected,failExpected,request,serialized,estimatedGas,estimatedGasUsd);if(created.kind==='RACE')return created;
  await input.hooks?.beforeSubmit?.(input.semanticStage);try{await broadcastSignedTransaction({walletClient:input.walletClient,serializedTransaction:serialized,expectedHash:created.hash,expectedSender:input.wallet,expectedChainId:input.rpc.config.chainId,expectedNonce:request.nonce});}catch{return reconcileAmbiguousSend(input,created.row,created.hash);}await input.hooks?.afterBroadcast?.(input.semanticStage,created.hash);
  const at=new Date().toISOString(),changed=input.repo.db.prepare("UPDATE rebalance_transactions SET status='SUBMITTED',submitted_at=COALESCE(submitted_at,?),updated_at=? WHERE id=? AND status='PREPARED'").run(at,at,created.row.id).changes;if(changed!==1){const current=rowById(input.repo,created.row.id);if(current?.status!=='SUBMITTED'&&current?.status!=='CONFIRMED')throw new Error('REBALANCE_SUBMISSION_STATE_CONFLICT');}
  return {kind:'SUBMITTED' as const,row:rowById(input.repo,created.row.id)??created.row,hash:created.hash,recovered};
 }finally{input.repo.releaseNonceMutex(input.wallet);}
}
function sameDurableRow(left:TxRow|undefined,right:TxRow|undefined){return left?.id===right?.id&&left?.status===right?.status&&left?.tx_hash===right?.tx_hash&&left?.nonce===right?.nonce&&left?.request_json===right?.request_json;}
async function retryPersistedLocked(input:RebalanceTxInput,row:TxRow,hash:Hash){
 if(!input.repo.acquireNonceMutex(input.wallet,BigInt(row.nonce)))return {kind:'LOCKED' as const};
 try{
  const durable=rowById(input.repo,row.id);if(!sameDurableRow(durable,row)||!durable||!['PREPARED','SUBMITTED'].includes(durable.status))return {kind:'RACE' as const};
  const evidence=await rebalanceExactHashEvidence(input.rpc,input.wallet,hash,durable.nonce);if(evidence.kind==='INCONCLUSIVE')throw new Error(`REBALANCE_TRANSACTION_EVIDENCE_INCONCLUSIVE:${evidence.reason}`);if(evidence.kind==='RECEIPT')return {kind:'RECEIPT' as const,row:durable,receipt:evidence.receipt};if(evidence.kind==='PENDING')return {kind:'PENDING' as const,row:markObservedPending(input.repo,durable)};if(evidence.latestNonce>durable.nonce)return {kind:'RACE' as const};if(evidence.pendingNonce>durable.nonce)throw new Error('REBALANCE_MEMPOOL_NONCE_CONFLICT');
  const request=parse<PreparedRequest>(durable.request_json),serialized=await signWithConfiguredAccount(input.walletClient,request);if(keccak256(serialized).toLowerCase()!==hash.toLowerCase())throw new Error('REBALANCE_SIGNED_TRANSACTION_HASH_MISMATCH');await input.hooks?.beforeSubmit?.(input.semanticStage);try{await broadcastSignedTransaction({walletClient:input.walletClient,serializedTransaction:serialized,expectedHash:hash,expectedSender:input.wallet,expectedChainId:input.rpc.config.chainId,expectedNonce:request.nonce});}catch{return reconcileAmbiguousSend(input,durable,hash);}await input.hooks?.afterBroadcast?.(input.semanticStage,hash);const at=new Date().toISOString(),changed=input.repo.db.prepare("UPDATE rebalance_transactions SET status='SUBMITTED',submitted_at=COALESCE(submitted_at,?),updated_at=? WHERE id=? AND status IN ('PREPARED','SUBMITTED')").run(at,at,durable.id).changes;if(changed!==1){const current=rowById(input.repo,durable.id);if(current?.status!=='SUBMITTED'&&current?.status!=='CONFIRMED')return {kind:'RACE' as const};}return {kind:'SUBMITTED' as const,row:rowById(input.repo,durable.id)??durable};
 }finally{input.repo.releaseNonceMutex(input.wallet);}
}

/** Every rebalance semantic stage uses the same durable exact-hash recovery,
 * nonce-drift classification, cross-process nonce lease, and atomic attempt journal. */
export async function executeRebalanceTransaction(input:RebalanceTxInput):Promise<{hash:Hash;receipt:TransactionReceipt;recovered:boolean}>{
 assertRebalanceCommitmentNotPermanentlyReleased(input.repo,input.workflowId);
 for(let recoveryRace=0;recoveryRace<4;recoveryRace++){
  const priorConfirmed=confirmed(input.repo,input.workflowId,input.semanticStage);if(priorConfirmed){if(!priorConfirmed.receipt_json)throw new Error('REBALANCE_CONFIRMED_RECEIPT_MISSING');return {hash:priorConfirmed.tx_hash as Hash,receipt:parse<TransactionReceipt>(priorConfirmed.receipt_json),recovered:true};}
  const row=latest(input.repo,input.workflowId,input.semanticStage);if(!row||!['PREPARED','SUBMITTED'].includes(row.status)){const created=await allocateAndSubmitFresh(input,row,false,false);if(created.kind==='LOCKED'){const durable=latest(input.repo,input.workflowId,input.semanticStage);if(!sameDurableRow(durable,row))continue;throw new Error('REBALANCE_NONCE_MUTEX_HELD');}if(created.kind==='RACE')continue;if(created.kind==='RECEIPT')return reconcileReceipt(input,created.row,created.row.tx_hash as Hash,created.receipt,true);return recoverReceipt(input,created.row,created.hash,created.recovered);}
  const hash=row.tx_hash as Hash,evidence=await rebalanceExactHashEvidence(input.rpc,input.wallet,hash,row.nonce);if(evidence.kind==='INCONCLUSIVE')throw new Error(`REBALANCE_TRANSACTION_EVIDENCE_INCONCLUSIVE:${evidence.reason}`);if(evidence.kind==='RECEIPT')return reconcileReceipt(input,row,hash,evidence.receipt,true);if(evidence.kind==='PENDING')return recoverReceipt(input,markObservedPending(input.repo,row),hash,true);
  if(evidence.latestNonce>row.nonce||evidence.pendingNonce>row.nonce)throw new Error('REBALANCE_EXACT_HASH_ABSENT_NONCE_CONSUMED_OR_REPLACED');if(row.status==='PREPARED'&&row.submitted_at===null&&evidence.latestNonce===row.nonce&&evidence.pendingNonce===row.nonce){let requiredGasPrice:bigint|undefined;try{const [block,networkGasPrice]=await input.rpc.withClient(client=>Promise.all([client.getBlock(),client.getGasPrice()]),{stage:'transaction_fee_recovery',method:'eth_getBlockByNumber+eth_gasPrice'}),baseFee=block.baseFeePerGas??0n;requiredGasPrice=networkGasPrice>baseFee?networkGasPrice:baseFee;}catch{requiredGasPrice=undefined;}const stored=parse<PreparedRequest>(row.request_json).gasPrice;if(requiredGasPrice!==undefined&&stored<requiredGasPrice){input.repo.db.prepare("UPDATE rebalance_transactions SET status='FAILED',failure_reason='PREPARED_GAS_PRICE_BELOW_CURRENT_NETWORK_FLOOR',updated_at=? WHERE id=? AND status='PREPARED' AND submitted_at IS NULL").run(new Date().toISOString(),row.id);continue;}}
  const retried=await retryPersistedLocked(input,row,hash);if(retried.kind==='LOCKED'){const durable=latest(input.repo,input.workflowId,input.semanticStage);if(!sameDurableRow(durable,row))continue;throw new Error('REBALANCE_NONCE_MUTEX_HELD');}if(retried.kind==='RACE')continue;if(retried.kind==='RECEIPT')return reconcileReceipt(input,retried.row,hash,retried.receipt,true);return recoverReceipt(input,retried.row,hash,true);
 }
 throw new Error('REBALANCE_RECOVERY_RACE_LIMIT');
}
