import { keccak256, toHex, type Address } from 'viem';
import { FallbackRpc, protocolDeployment } from '@funi/core';
import { SqliteLedgerRepository } from '@funi/ledger';
import { amountsForLiquidity, discoverOwnedV3TokenIds, inspectV3FamilyPosition, sqrtRatioAtTick, type GuardedV3Chain, type GuardedV3Protocol } from '@funi/v3';

const terminalStates=new Set(['COMPLETED','CANCELLED','ABANDONED','FAILED_PERMANENT']);
const fingerprint=(value:unknown)=>keccak256(toHex(JSON.stringify(value,(_,item)=>typeof item==='bigint'?item.toString():item)));

export async function reconcileGuardedV3Position(input:{repo:SqliteLedgerRepository;rpc:FallbackRpc;chainId:GuardedV3Chain;protocol:GuardedV3Protocol;tokenId:bigint;expectedOwner:Address;defaultProvenance?:'BOT_OPERATIONAL'|'MANUAL_EXTERNAL'}){
  const result=await inspectV3FamilyPosition({rpc:input.rpc,chainId:input.chainId,protocol:input.protocol,tokenId:input.tokenId});if(result.status==='unavailable')return {status:'UNAVAILABLE' as const,reason:result.reason};const position=result.value;if(position.owner.toLowerCase()!==input.expectedOwner.toLowerCase())return {status:'OWNERSHIP_MISMATCH' as const,owner:position.owner};const existing=input.repo.chainPosition(input.chainId,input.protocol,input.tokenId.toString()),provenance=(existing?.provenance as 'BOT_OPERATIONAL'|'MANUAL_EXTERNAL'|undefined)??input.defaultProvenance??'MANUAL_EXTERNAL',amounts=amountsForLiquidity(position.pool.sqrtPriceX96,sqrtRatioAtTick(position.tickLower),sqrtRatioAtTick(position.tickUpper),position.liquidity),lifecycleState=position.liquidity>0n?'ACTIVE':position.tokensOwed0>0n||position.tokensOwed1>0n?'CLOSED_COLLECTIBLE':'CLOSED_BURNABLE',rangeState=position.pool.tick<position.tickLower?'BELOW_RANGE':position.pool.tick>=position.tickUpper?'ABOVE_RANGE':'IN_RANGE';const row=input.repo.upsertChainPosition({chainId:input.chainId,protocol:input.protocol,positionIdentifier:input.tokenId.toString(),owner:position.owner,provenance,lifecycleState,payload:{token0:position.token0,token1:position.token1,fee:position.fee,tickLower:position.tickLower,tickUpper:position.tickUpper,currentTick:position.pool.tick,sqrtPriceX96:position.pool.sqrtPriceX96,liquidity:position.liquidity,principalAmount0:amounts.amount0,principalAmount1:amounts.amount1,tokensOwed0:position.tokensOwed0,tokensOwed1:position.tokensOwed1,rangeState,pool:position.pool.address,valuation:{status:'UNAVAILABLE',reason:'CHAIN_PRICE_EVIDENCE_REQUIRED'}}});return {status:'RECONCILED' as const,row,position,rangeState,principal:amounts};
}

export async function discoverGuardedV3Portfolio(input:{repo:SqliteLedgerRepository;rpc:FallbackRpc;chainId:GuardedV3Chain;protocol:GuardedV3Protocol;owner:Address;maximumPositions:number}){
  if(input.rpc.config.chainId!==input.chainId)throw new Error('V3_RPC_CHAIN_MISMATCH');const ids=await input.rpc.withClient(client=>discoverOwnedV3TokenIds({client,chainId:input.chainId,protocol:input.protocol,owner:input.owner,maximumPositions:input.maximumPositions}),{stage:'multichain_v3_portfolio',method:'PositionManager.balanceOf+tokenOfOwnerByIndex'}),results=[];for(const tokenId of ids)results.push(await reconcileGuardedV3Position({...input,tokenId,expectedOwner:input.owner,defaultProvenance:'MANUAL_EXTERNAL'}));return {chainId:input.chainId,protocol:input.protocol,owner:input.owner,positionIds:ids,results};
}

export function adoptGuardedV3ExternalPosition(input:{repo:SqliteLedgerRepository;chainId:GuardedV3Chain;protocol:GuardedV3Protocol;tokenId:bigint;owner:Address;authorized:boolean}){
  const row=input.repo.chainPosition(input.chainId,input.protocol,input.tokenId.toString());if(!row)throw new Error('CHAIN_POSITION_NOT_FOUND');if(String(row.owner_address).toLowerCase()!==input.owner.toLowerCase())throw new Error('CHAIN_POSITION_OWNERSHIP_MISMATCH');if(row.provenance!=='MANUAL_EXTERNAL')throw new Error('CHAIN_POSITION_NOT_MANUAL_EXTERNAL');if(!input.authorized)throw new Error('CHAIN_POSITION_ADOPTION_AUTHORIZATION_REQUIRED');return input.repo.upsertChainPosition({chainId:input.chainId,protocol:input.protocol,positionIdentifier:input.tokenId.toString(),owner:input.owner,provenance:'BOT_OPERATIONAL',lifecycleState:String(row.lifecycle_state),payload:JSON.parse(String(row.payload_json))});
}

export function createGuardedV3LifecyclePreview(input:{repo:SqliteLedgerRepository;chainId:GuardedV3Chain;protocol:GuardedV3Protocol;workflowId:string;idempotencyKey:string;action:'open'|'collect'|'partial_close'|'full_close'|'burn';positionIdentifier?:string;wallet:Address;fundingToken?:Address;previewRevision:number;incrementalCommitmentUsd?:number;exposureRevision?:string;capabilitySnapshot:unknown;safetyEvidence:unknown;feeEvidence:unknown;preview:unknown}){
  const deployment=protocolDeployment(input.chainId,input.protocol);if(input.positionIdentifier){const position=input.repo.chainPosition(input.chainId,input.protocol,input.positionIdentifier);if(!position)throw new Error('CHAIN_POSITION_NOT_FOUND');if(position.provenance!=='BOT_OPERATIONAL')throw new Error('MANUAL_EXTERNAL_EXECUTION_FORBIDDEN');if(String(position.owner_address).toLowerCase()!==input.wallet.toLowerCase())throw new Error('CHAIN_POSITION_OWNERSHIP_MISMATCH');}
  const incremental=input.incrementalCommitmentUsd??0;if(incremental<0)throw new Error('CHAIN_COMMITMENT_INVALID');const core={chainId:input.chainId,incrementalUsd:incremental},exposureEvidence={...core,revision:input.exposureRevision??fingerprint(core),fingerprint:fingerprint(core)};return input.repo.createChainV3Workflow({chainId:input.chainId,protocol:input.protocol,workflowId:input.workflowId,idempotencyKey:input.idempotencyKey,action:input.action,positionIdentifier:input.positionIdentifier,deploymentVersion:deployment.registryVersion,wallet:input.wallet,fundingToken:input.fundingToken,previewRevision:input.previewRevision,capabilitySnapshot:input.capabilitySnapshot,safetyEvidence:input.safetyEvidence,exposureEvidence,feeEvidence:input.feeEvidence,preview:input.preview,commitmentUsd:incremental});
}

export function authorizeGuardedV3Lifecycle(input:{repo:SqliteLedgerRepository;chainId:GuardedV3Chain;protocol:GuardedV3Protocol;workflowId:string;previewRevision:number;deploymentVersion:number;safetyEvidence:unknown;exposureEvidence:unknown;feeEvidence:unknown;authorizationRevision:number}){
  const row=input.repo.chainV3Workflow(input.chainId,input.protocol,input.workflowId);if(!row)throw new Error('CHAIN_V3_WORKFLOW_NOT_FOUND');if(Number(row.preview_revision)!==input.previewRevision)throw new Error('PREVIEW_REVISION_STALE');if(Number(row.deployment_version)!==input.deploymentVersion||protocolDeployment(input.chainId,input.protocol).registryVersion!==input.deploymentVersion)throw new Error('DEPLOYMENT_VERSION_CHANGED');for(const [column,value,code] of [['safety_evidence_json',input.safetyEvidence,'SAFETY_EVIDENCE_CHANGED'],['exposure_evidence_json',input.exposureEvidence,'EXPOSURE_EVIDENCE_CHANGED'],['fee_evidence_json',input.feeEvidence,'FEE_EVIDENCE_CHANGED']] as const)if(String(row[column])!==JSON.stringify(value))throw new Error(code);const commitment=Number(row.commitment_usd??0);if(commitment>0)input.repo.commitChainExposure({chainId:input.chainId,protocol:input.protocol,workflowId:input.workflowId,provenance:'BOT_OPERATIONAL',committedUsd:commitment,valuationStatus:'AVAILABLE',evidence:input.exposureEvidence});return input.repo.transitionChainV3Workflow({chainId:input.chainId,protocol:input.protocol,workflowId:input.workflowId,from:'PREVIEWED',to:'AUTHORIZED',authorizationRevision:input.authorizationRevision});
}

export function guardedV3ResidueStatus(repo:SqliteLedgerRepository,chainId:GuardedV3Chain,protocol?:GuardedV3Protocol){const args=protocol?[chainId,protocol]:[chainId],where=protocol?'chain_id=? AND protocol=?':'chain_id=?';return {workflows:repo.db.prepare(`SELECT workflow_id,protocol,state,position_identifier,replacement_position_identifier,updated_at FROM chain_v3_workflows WHERE ${where} AND state NOT IN ('COMPLETED','CANCELLED','ABANDONED','FAILED_PERMANENT') ORDER BY updated_at`).all(...args),transactions:repo.db.prepare(`SELECT journal_id,protocol,workflow_identity,semantic_stage,status,nonce,expected_hash FROM chain_transaction_journal WHERE ${where} AND status IN ('PREPARED','SUBMITTED') ORDER BY updated_at`).all(...args)};}
