import {
  getAddress,
  keccak256,
  parseTransaction,
  recoverTransactionAddress,
  toHex,
  type Address,
  type Hex,
  type TransactionReceipt,
  type TransactionSerialized,
  type StateOverride,
  type WalletClient,
} from 'viem';
import {
  FallbackRpc,
  actualGasEvidence,
  assertFreshFeeQuote,
  chainProfile,
  eip1559FeeQuote,
  legacyFeeQuote,
  protocolDeployment,
  requireProtocolCapability,
  type ChainFeeQuote,
  type ProtocolOperation,
} from '@funi/core';
import { SqliteLedgerRepository } from '@funi/ledger';
import {
  assertGuardedV3TransactionSemantics,
  type GuardedV3Chain,
  type GuardedV3Protocol,
  type V3BuiltTransaction,
} from '@funi/v3';
import type { CanonicalDeploymentVerificationEvidence } from './multichain-runtime.js';

export type GuardedV3Readiness = {
  chainId: GuardedV3Chain;
  protocol: GuardedV3Protocol;
  enabled: boolean;
  executionEnabled: boolean;
  dryRun: boolean;
  emergencyPause: boolean;
  deploymentVerification: 'VERIFIED'|'PARTIALLY_VERIFIED'|'UNVERIFIED'|'UNSUPPORTED';
  providerChainId?: number;
  wallet?: Address;
  nonceEvidenceHealthy: boolean;
  unresolvedChainTransactions: number;
  previewRevision: number;
  currentPreviewRevision: number;
  deploymentVersion: number;
  previewDeploymentVersion: number;
  safetyRevision: string;
  currentSafetyRevision: string;
  feeEvidenceFresh: boolean;
  priceEvidenceFresh: boolean;
  providerHealthy: boolean;
  walletBalanceVerified: boolean;
  gasPolicyValid: boolean;
  nativeGasSufficient: boolean;
  nonceMutexEmpty: boolean;
  previewBound: boolean;
  authorizationBound: boolean;
  simulationProofVerified: boolean;
  authorizationValid: boolean;
};

function rawGuardedV3ExecutionBlockers(input:GuardedV3Readiness):string[]{
  const blockers:string[]=[];
  try{guardedV3ChainProtocol(input.chainId,input.protocol);requireProtocolCapability(input.chainId,input.protocol,'open');}catch(error){blockers.push(error instanceof Error?error.message:'V3_CAPABILITY_UNAVAILABLE');}
  if(!input.enabled)blockers.push('CHAIN_DISABLED');if(!input.executionEnabled)blockers.push('CHAIN_EXECUTION_DISABLED');if(input.dryRun)blockers.push('CHAIN_DRY_RUN_ENABLED');if(input.emergencyPause)blockers.push('CHAIN_EMERGENCY_PAUSE');if(input.deploymentVerification!=='VERIFIED')blockers.push('DEPLOYMENT_RUNTIME_NOT_VERIFIED');if(!input.providerHealthy||input.providerChainId===undefined)blockers.push('PROVIDER_CHAIN_ID_UNVERIFIED');else if(input.providerChainId!==input.chainId)blockers.push('PROVIDER_CHAIN_ID_MISMATCH');if(!input.wallet)blockers.push('CHAIN_WALLET_REQUIRED');if(!input.walletBalanceVerified)blockers.push('CHAIN_WALLET_BALANCE_UNVERIFIED');if(!input.gasPolicyValid)blockers.push('CHAIN_GAS_POLICY_REQUIRED');if(!input.nativeGasSufficient)blockers.push('CHAIN_NATIVE_GAS_INSUFFICIENT_OR_UNKNOWN');if(!input.nonceEvidenceHealthy)blockers.push('CHAIN_NONCE_EVIDENCE_UNHEALTHY');if(!input.nonceMutexEmpty)blockers.push('CHAIN_NONCE_MUTEX_HELD');if(input.unresolvedChainTransactions>0)blockers.push('CHAIN_UNRESOLVED_TRANSACTION');if(!input.previewBound||input.previewRevision!==input.currentPreviewRevision)blockers.push('PREVIEW_REVISION_STALE');if(input.deploymentVersion!==input.previewDeploymentVersion)blockers.push('DEPLOYMENT_VERSION_CHANGED');if(input.safetyRevision!==input.currentSafetyRevision)blockers.push('SAFETY_REVISION_CHANGED');if(!input.feeEvidenceFresh)blockers.push('FEE_EVIDENCE_STALE');if(!input.priceEvidenceFresh)blockers.push('PRICE_EVIDENCE_STALE');if(!input.simulationProofVerified)blockers.push('EXACT_ACTION_SIMULATION_PROOF_REQUIRED');if(!input.authorizationBound||!input.authorizationValid)blockers.push('CHAIN_AUTHORIZATION_INVALID');return [...new Set(blockers)];
}

export function guardedV3ExecutionBlockers(input:GuardedV3Readiness):string[]{return rawGuardedV3ExecutionBlockers(input).map(code=>code==='CHAIN_NATIVE_GAS_INSUFFICIENT_OR_UNKNOWN'?'CHAIN_NATIVE_GAS_INSUFFICIENT':code==='CHAIN_AUTHORIZATION_INVALID'&&!input.authorizationBound?'CHAIN_AUTHORIZATION_REQUIRED':code);}

function guardedV3ChainProtocol(chainId:number,protocol:string):asserts chainId is GuardedV3Chain{
  if(chainId===56&&protocol==='pancakeswap_v3'||chainId===1&&protocol==='uniswap_v3')return;throw new Error(`V3_GUARDED_CHAIN_PROTOCOL_MISMATCH:${chainId}:${protocol}`);
}

export function derivedFeeEvidencePolicy(chainId:GuardedV3Chain){const profile=chainProfile(chainId);return {maximumProviderSpreadBps:2_500,maxAgeMs:Math.min(120_000,Math.max(5_000,profile.expectedBlockTimeMs*4))};}
const feeRevision=(value:unknown)=>keccak256(toHex(JSON.stringify(value,(_,item)=>typeof item==='bigint'?item.toString():item)));
const spreadBps=(minimum:bigint,maximum:bigint)=>maximum<=0n?Number.POSITIVE_INFINITY:Number((maximum-minimum)*10_000n/maximum);

export type LegacyFeeClient={getGasPrice():Promise<bigint>;getChainId?():Promise<number>;getBlockNumber?():Promise<bigint>};
export async function acquireBscLegacyFeeEvidence(input:{clients:readonly LegacyFeeClient[];chainId?:56;minimumGasPrice?:bigint;maximumGasPrice?:bigint;maximumProviderSpreadBps?:number;observedAtMs?:number}){
  const chainId=input.chainId??56,observedAtMs=input.observedAtMs??Date.now(),maximumProviderSpreadBps=input.maximumProviderSpreadBps??derivedFeeEvidencePolicy(chainId).maximumProviderSpreadBps;if(!input.clients.length)throw new Error('FEE_EVIDENCE_NO_PROVIDERS');const settled=await Promise.allSettled(input.clients.map(async client=>{const [providerChainId,gasPrice,block]=await Promise.all([client.getChainId?.()??chainId,client.getGasPrice(),client.getBlockNumber?.()??0n]);if(providerChainId!==chainId)throw new Error('FEE_EVIDENCE_WRONG_CHAIN');if(gasPrice<=0n)throw new Error('FEE_GAS_PRICE_INVALID');return {gasPrice,block};})),values=settled.flatMap(item=>item.status==='fulfilled'?[item.value]:[]);if(!values.length)throw new Error('FEE_EVIDENCE_UNAVAILABLE_BEFORE_SIGNING');const prices=values.map(value=>value.gasPrice),min=prices.reduce((a,b)=>a<b?a:b),max=prices.reduce((a,b)=>a>b?a:b),providerSpreadBps=spreadBps(min,max);if(!Number.isFinite(providerSpreadBps)||providerSpreadBps>maximumProviderSpreadBps)throw new Error('FEE_PROVIDER_DISAGREEMENT');const ordered=[...prices].sort((a,b)=>a<b?-1:a>b?1:0),median=ordered[Math.floor(ordered.length/2)]!,sampleBlock=values.map(value=>value.block).reduce((a,b)=>a<b?a:b);return {...legacyFeeQuote({gasPrice:median,minimumGasPrice:input.minimumGasPrice,maximumGasPrice:input.maximumGasPrice,observedAtMs}),chainId,providerCount:values.length,providerFailureCount:settled.length-values.length,minimumObserved:min,maximumObserved:max,providerSpreadBps,sampleBlock,evidenceRevision:feeRevision({chainId,observedAtMs,sampleBlock,prices})};
}

export type Eip1559FeeClient={getChainId?():Promise<number>;getBlock(input:{blockTag:'latest'}):Promise<{baseFeePerGas:bigint|null;number?:bigint;timestamp?:bigint}>;estimateMaxPriorityFeePerGas?():Promise<bigint>;getFeeHistory?(input:{blockCount:number;rewardPercentiles:readonly number[]}):Promise<{reward?:readonly (readonly bigint[])[]}>};
async function priorityFee(client:Eip1559FeeClient){try{if(client.estimateMaxPriorityFeePerGas)return await client.estimateMaxPriorityFeePerGas();}catch{}if(client.getFeeHistory){const history=await client.getFeeHistory({blockCount:4,rewardPercentiles:[50]});const rewards=(history.reward??[]).flat().filter(value=>value>0n).sort((a,b)=>a<b?-1:a>b?1:0);if(rewards.length)return rewards[Math.floor(rewards.length/2)]!;}throw new Error('EIP1559_PRIORITY_FEE_UNAVAILABLE');}
export async function acquireEthereumEip1559FeeEvidence(input:{clients:readonly Eip1559FeeClient[];chainId?:1;maximumFeePerGas?:bigint;maximumProviderSpreadBps?:number;observedAtMs?:number}){
  const chainId=input.chainId??1,observedAtMs=input.observedAtMs??Date.now(),maximumProviderSpreadBps=input.maximumProviderSpreadBps??derivedFeeEvidencePolicy(chainId).maximumProviderSpreadBps;if(!input.clients.length)throw new Error('FEE_EVIDENCE_NO_PROVIDERS');const settled=await Promise.allSettled(input.clients.map(async client=>{const [providerChainId,block,priority]=await Promise.all([client.getChainId?.()??chainId,client.getBlock({blockTag:'latest'}),priorityFee(client)]);if(providerChainId!==chainId)throw new Error('FEE_EVIDENCE_WRONG_CHAIN');if(block.baseFeePerGas===null||block.baseFeePerGas<=0n||priority<=0n)throw new Error('FEE_EIP1559_PROVIDER_VALUES_INVALID');return {base:block.baseFeePerGas,priority,block:block.number??0n};})),values=settled.flatMap(item=>item.status==='fulfilled'?[item.value]:[]);if(!values.length)throw new Error('FEE_EVIDENCE_UNAVAILABLE_BEFORE_SIGNING');const bases=values.map(item=>item.base),priorities=values.map(item=>item.priority),baseMin=bases.reduce((a,b)=>a<b?a:b),baseMax=bases.reduce((a,b)=>a>b?a:b),priorityMin=priorities.reduce((a,b)=>a<b?a:b),priorityMax=priorities.reduce((a,b)=>a>b?a:b),baseFeeSpreadBps=spreadBps(baseMin,baseMax),priorityFeeSpreadBps=spreadBps(priorityMin,priorityMax),providerSpreadBps=Math.max(baseFeeSpreadBps,priorityFeeSpreadBps);if(!Number.isFinite(providerSpreadBps)||providerSpreadBps>maximumProviderSpreadBps)throw new Error('FEE_PROVIDER_DISAGREEMENT');const ordered=[...values].sort((a,b)=>a.base<b.base?-1:a.base>b.base?1:0),median=ordered[Math.floor(ordered.length/2)]!,sampleBlock=values.map(value=>value.block).reduce((a,b)=>a<b?a:b);return {...eip1559FeeQuote({baseFeePerGas:median.base,maxPriorityFeePerGas:median.priority,maximumFeePerGas:input.maximumFeePerGas,observedAtMs}),chainId,providerCount:values.length,providerFailureCount:settled.length-values.length,minimumBaseFeeObserved:baseMin,maximumBaseFeeObserved:baseMax,minimumPriorityFeeObserved:priorityMin,maximumPriorityFeeObserved:priorityMax,baseFeeSpreadBps,priorityFeeSpreadBps,providerSpreadBps,sampleBlock,evidenceRevision:feeRevision({chainId,observedAtMs,sampleBlock,values})};
}

export type V3ExecutionReceipt=Pick<TransactionReceipt,'transactionHash'|'status'|'gasUsed'|'effectiveGasPrice'|'blockNumber'>;
export type V3ExecutorDependencies={
  simulate(tx:V3BuiltTransaction,wallet:Address):Promise<{gas:bigint}>;
  pendingNonce(wallet:Address):Promise<{nonce:number;providerCount:number}>;
  sign(request:Record<string,unknown>):Promise<Hex>;
  broadcast(serialized:Hex):Promise<Hex>;
  observe(input:{expectedHash:Hex;wallet:Address;nonce:number}):Promise<{status:'FOUND'|'NOT_FOUND'|'CONFLICT';hash?:Hex;evidence?:unknown}>;
  waitForReceipt(expectedHash:Hex,confirmations:number):Promise<V3ExecutionReceipt>;
  reconcile?(input:{receipt:V3ExecutionReceipt;expectedHash:Hex;workflowId:string;semanticStage:string}):Promise<unknown>;
};

export function createViemGuardedV3Dependencies(input:{rpc:FallbackRpc;walletClient:WalletClient;observationAttempts?:number;observationDelayMs?:number}):V3ExecutorDependencies{
  const attempts=input.observationAttempts??3,delayMs=input.observationDelayMs??250;if(attempts<=0||delayMs<0)throw new Error('V3_OBSERVATION_POLICY_INVALID');
  return {
    simulate:async(tx,wallet)=>input.rpc.withClient(async client=>{const request={account:wallet,to:tx.to,data:tx.data,value:tx.value};const [gas]=await Promise.all([client.estimateGas(request),client.call(request)]);return {gas};},{stage:'multichain_v3_preflight',method:`${tx.protocol}.${tx.action}.eth_call+eth_estimateGas`}),
    pendingNonce:async wallet=>{const settled=await Promise.allSettled(input.rpc.clients.map(client=>client.getTransactionCount({address:wallet,blockTag:'pending'}))),values=settled.flatMap(item=>item.status==='fulfilled'?[item.value]:[]);if(!values.length||new Set(values).size!==1)throw new Error('CHAIN_NONCE_PROVIDER_DISAGREEMENT');return {nonce:values[0]!,providerCount:values.length};},
    sign:async request=>input.walletClient.signTransaction(request as never),
    broadcast:async serialized=>{const client=input.rpc.clients[0];if(!client)throw new Error('BROADCAST_PROVIDER_UNAVAILABLE');return client.sendRawTransaction({serializedTransaction:serialized});},
    observe:async({expectedHash,wallet,nonce})=>{const evidence:unknown[]=[];for(let attempt=0;attempt<attempts;attempt++){const states=await Promise.all(input.rpc.clients.map(async(client,providerIndex)=>{let exact=false,conflictingHash:Hex|undefined;try{const transaction=await client.getTransaction({hash:expectedHash});exact=transaction.hash.toLowerCase()===expectedHash.toLowerCase();}catch{}try{const pending=await client.getBlock({blockTag:'pending',includeTransactions:true});const conflict=pending.transactions.find(item=>typeof item!=='string'&&item.from.toLowerCase()===wallet.toLowerCase()&&item.nonce===nonce&&item.hash.toLowerCase()!==expectedHash.toLowerCase());if(conflict&&typeof conflict!=='string')conflictingHash=conflict.hash;}catch{}return {providerIndex,exact,conflictingHash};}));evidence.push(states.map(item=>({providerIndex:item.providerIndex,exact:item.exact,conflict:Boolean(item.conflictingHash)})));const conflict=states.find(item=>item.conflictingHash);if(conflict)return {status:'CONFLICT' as const,hash:conflict.conflictingHash,evidence};if(states.some(item=>item.exact))return {status:'FOUND' as const,hash:expectedHash,evidence};if(attempt+1<attempts&&delayMs)await new Promise(resolve=>setTimeout(resolve,delayMs));}return {status:'NOT_FOUND' as const,evidence};},
    waitForReceipt:async(expectedHash,confirmations)=>input.rpc.withClient(client=>client.waitForTransactionReceipt({hash:expectedHash,confirmations}),{stage:'multichain_v3_confirmation',method:'eth_getTransactionReceipt'}),
  };
}

export type GuardedV3GasStage={stage:string;transaction:V3BuiltTransaction;requirement?:'REQUIRED'|'CONDITIONAL';stateOverride?:StateOverride;calibrationOnly?:boolean};
export function approvalStageForAllowance(input:{stage:string;transaction:V3BuiltTransaction;currentAllowance:bigint;requiredAllowance:bigint;conditional?:boolean}):GuardedV3GasStage|undefined{
 if(input.transaction.action!=='approval')throw new Error('V3_APPROVAL_STAGE_TRANSACTION_REQUIRED');if(input.currentAllowance<0n||input.requiredAllowance<=0n)throw new Error('V3_ALLOWANCE_EVIDENCE_INVALID');if(input.currentAllowance>=input.requiredAllowance)return undefined;return {stage:input.stage,transaction:input.transaction,requirement:input.conditional?'CONDITIONAL':'REQUIRED'};
}

export async function estimateGuardedV3LifecycleGas(input:{rpc:FallbackRpc;repo?:SqliteLedgerRepository;wallet:Address;chainId:GuardedV3Chain;protocol:GuardedV3Protocol;action:string;stages:readonly GuardedV3GasStage[];feeQuote:ChainFeeQuote;feeEvidenceRevision:string;feeEvidenceMaxAgeMs?:number;previewRevision:number;deploymentEvidenceRevision:string;walletEvidenceRevision:string;allowanceEvidenceRevision:string;nativeBalance:bigint;nativeUsd?:number;nowMs?:number}){
 guardedV3ChainProtocol(input.chainId,input.protocol);if(input.rpc.config.chainId!==input.chainId)throw new Error('V3_RPC_CHAIN_MISMATCH');if(!input.stages.length)throw new Error('EXACT_ACTION_TRANSACTION_REQUEST_REQUIRED');if(!Number.isSafeInteger(input.previewRevision)||input.previewRevision<0)throw new Error('PREVIEW_REVISION_INVALID');const nowMs=input.nowMs??Date.now(),deployment=protocolDeployment(input.chainId,input.protocol),maxAge=input.feeEvidenceMaxAgeMs??derivedFeeEvidencePolicy(input.chainId).maxAgeMs;assertFreshFeeQuote(chainProfile(input.chainId),input.feeQuote,{nowMs,maxAgeMs:maxAge});
 const beforeJournal=input.repo?Number((input.repo.db.prepare('SELECT COUNT(*) count FROM chain_transaction_journal WHERE chain_id=?').get(input.chainId) as {count:number}).count):0,beforeMutex=input.repo?Number((input.repo.db.prepare('SELECT COUNT(*) count FROM chain_nonce_mutex WHERE chain_id=?').get(input.chainId) as {count:number}).count):0,seenApprovals=new Set<string>(),normalized:GuardedV3GasStage[]=[];
 for(const stage of input.stages){const tx=stage.transaction;if(tx.chainId!==input.chainId||tx.protocol!==input.protocol)throw new Error('V3_GAS_STAGE_CHAIN_PROTOCOL_MISMATCH');if(tx.deploymentVersion!==deployment.registryVersion)throw new Error('DEPLOYMENT_VERSION_CHANGED');assertGuardedV3TransactionSemantics(tx);if(tx.action==='approval'){const key=`${tx.to.toLowerCase()}:${tx.data}`;if(seenApprovals.has(key))continue;seenApprovals.add(key);}normalized.push({...stage,requirement:stage.requirement??'REQUIRED'});}
 const estimates=[] as Array<{stage:string;transactionAction:string;requirement:'REQUIRED'|'CONDITIONAL';estimatedGas:bigint;bufferedGas:bigint;estimatedNative:bigint;bufferedNative:bigint;estimatedUsd?:number;bufferedUsd?:number;observedBlock:bigint;destinationVerified:true;selectorVerified:true;valueVerified:true;feeEnvelopeVerified:true}>;const feePerGas=input.feeQuote.feeModel==='legacy'?input.feeQuote.gasPrice:input.feeQuote.maxFeePerGas;
 for(const stage of normalized){const tx=stage.transaction,result=await input.rpc.withClient(async client=>{const request={account:input.wallet,to:tx.to,data:tx.data,value:tx.value,...(stage.stateOverride?{stateOverride:stage.stateOverride}:{})},[estimatedGas]=await Promise.all([client.estimateGas(request),client.call(request)]),observedBlock=await client.getBlockNumber();return {estimatedGas,observedBlock};},{stage:'guarded_v3_exact_gas_estimation',method:`${input.protocol}.${tx.action}.eth_call+eth_estimateGas`});if(result.estimatedGas<=0n)throw new Error('V3_SIMULATION_GAS_INVALID');const bufferedGas=(result.estimatedGas*12n+9n)/10n,estimatedNative=result.estimatedGas*feePerGas,bufferedNative=bufferedGas*feePerGas;estimates.push({stage:stage.stage,transactionAction:tx.action,requirement:stage.requirement!,estimatedGas:result.estimatedGas,bufferedGas,estimatedNative,bufferedNative,estimatedUsd:input.nativeUsd===undefined?undefined:Number(estimatedNative)/1e18*input.nativeUsd,bufferedUsd:input.nativeUsd===undefined?undefined:Number(bufferedNative)/1e18*input.nativeUsd,observedBlock:result.observedBlock,destinationVerified:true,selectorVerified:true,valueVerified:true,feeEnvelopeVerified:true});}
 const required=estimates.filter(stage=>stage.requirement==='REQUIRED'),sum=(values:readonly bigint[])=>values.reduce((total,value)=>total+value,0n),lowGas=sum(required.map(stage=>stage.estimatedGas)),highGas=sum(estimates.map(stage=>stage.estimatedGas)),lowBufferedGas=sum(required.map(stage=>stage.bufferedGas)),highBufferedGas=sum(estimates.map(stage=>stage.bufferedGas)),lowNative=sum(required.map(stage=>stage.estimatedNative)),highNative=sum(estimates.map(stage=>stage.estimatedNative)),lowBufferedNative=sum(required.map(stage=>stage.bufferedNative)),highBufferedNative=sum(estimates.map(stage=>stage.bufferedNative)),fundingDeficit=input.nativeBalance>=highBufferedNative?0n:highBufferedNative-input.nativeBalance,observedBlock=estimates.map(stage=>stage.observedBlock).reduce((a,b)=>a<b?a:b),previewEvidenceRevision=feeRevision({chainId:input.chainId,protocol:input.protocol,action:input.action,previewRevision:input.previewRevision,deploymentVersion:deployment.registryVersion,deploymentEvidenceRevision:input.deploymentEvidenceRevision,feeEvidenceRevision:input.feeEvidenceRevision,walletEvidenceRevision:input.walletEvidenceRevision,allowanceEvidenceRevision:input.allowanceEvidenceRevision,wallet:input.wallet,stages:normalized.map(stage=>({stage:stage.stage,requirement:stage.requirement,calibrationOnly:stage.calibrationOnly===true,stateOverrideRevision:stage.stateOverride?feeRevision(stage.stateOverride):undefined,request:feeRevision({to:stage.transaction.to,data:stage.transaction.data,value:stage.transaction.value})}))});
 if(input.repo){const afterJournal=Number((input.repo.db.prepare('SELECT COUNT(*) count FROM chain_transaction_journal WHERE chain_id=?').get(input.chainId) as {count:number}).count),afterMutex=Number((input.repo.db.prepare('SELECT COUNT(*) count FROM chain_nonce_mutex WHERE chain_id=?').get(input.chainId) as {count:number}).count);if(beforeJournal!==afterJournal||beforeMutex!==afterMutex)throw new Error('SIMULATE_ONLY_STATE_MUTATION_DETECTED');}
 return {chain:chainProfile(input.chainId).key,chainId:input.chainId,protocol:input.protocol,action:input.action,previewRevision:input.previewRevision,previewEvidenceRevision,deploymentVersion:deployment.registryVersion,deploymentEvidenceRevision:input.deploymentEvidenceRevision,feeEvidenceRevision:input.feeEvidenceRevision,walletEvidenceRevision:input.walletEvidenceRevision,allowanceEvidenceRevision:input.allowanceEvidenceRevision,simulationResult:'VERIFIED' as const,projectedActionGas:estimates,projectedLifecycleGas:{low:lowGas,high:highGas,bufferedLow:lowBufferedGas,bufferedHigh:highBufferedGas,conditionalStages:estimates.filter(stage=>stage.requirement==='CONDITIONAL').map(stage=>stage.stage)},funding:{currentNativeBalance:input.nativeBalance,projectedNativeRequirementLow:lowNative,projectedNativeRequirementHigh:highNative,safetyBufferedNativeRequirementLow:lowBufferedNative,safetyBufferedNativeRequirementHigh:highBufferedNative,fundingDeficit,projectedUsdLow:input.nativeUsd===undefined?undefined:Number(lowBufferedNative)/1e18*input.nativeUsd,projectedUsdHigh:input.nativeUsd===undefined?undefined:Number(highBufferedNative)/1e18*input.nativeUsd,fundingDeficitUsd:input.nativeUsd===undefined?undefined:Number(fundingDeficit)/1e18*input.nativeUsd,evidenceBlock:observedBlock,evidenceTimeMs:nowMs,actionAndLifecycleCovered:input.action},signerConstructed:false,nonceReserved:false,journalWritten:false,broadcastUsed:false};
}

export type ExecuteGuardedV3Input={repo:SqliteLedgerRepository;transaction:V3BuiltTransaction;workflowId:string;journalId:string;semanticStage:string;attempt:number;wallet:Address;capability:Extract<ProtocolOperation,'open'|'collect'|'partialClose'|'fullClose'|'burn'>;feeQuote:ChainFeeQuote;feeEvidenceMaxAgeMs:number;confirmations:number;readiness:GuardedV3Readiness;deploymentEvidence?:CanonicalDeploymentVerificationEvidence;dependencies:V3ExecutorDependencies;maximumGasUsd:number;projectedLifecycleGasUsd:number;maximumLifecycleGasUsd:number;nativeUsd?:number;nativeBalance:bigint;nowMs?:number};

function requestFingerprint(request:Record<string,unknown>):Hex{return keccak256(toHex(JSON.stringify(request,(_,value)=>typeof value==='bigint'?value.toString():value)));}

function assertSignedEnvelope(input:{serialized:Hex;transaction:V3BuiltTransaction;wallet:Address;nonce:number;gas:bigint;feeQuote:ChainFeeQuote}){
  const parsed=parseTransaction(input.serialized),serializedTransaction=input.serialized as TransactionSerialized;if(parsed.chainId!==input.transaction.chainId)throw new Error('SIGNED_ENVELOPE_CHAIN_ID_MISMATCH');if(parsed.nonce!==input.nonce)throw new Error('SIGNED_ENVELOPE_NONCE_MISMATCH');if(!parsed.to||parsed.to.toLowerCase()!==input.transaction.to.toLowerCase())throw new Error('SIGNED_ENVELOPE_DESTINATION_MISMATCH');if((parsed.value??0n)!==input.transaction.value||parsed.data!==input.transaction.data||parsed.gas!==input.gas)throw new Error('SIGNED_ENVELOPE_REQUEST_MISMATCH');if(input.feeQuote.feeModel==='legacy'){if(parsed.type!=='legacy'||parsed.gasPrice!==input.feeQuote.gasPrice||parsed.maxFeePerGas!==undefined||parsed.maxPriorityFeePerGas!==undefined)throw new Error('SIGNED_ENVELOPE_LEGACY_FEE_MISMATCH');}else if(parsed.type!=='eip1559'||parsed.maxFeePerGas!==input.feeQuote.maxFeePerGas||parsed.maxPriorityFeePerGas!==input.feeQuote.maxPriorityFeePerGas||parsed.gasPrice!==undefined)throw new Error('SIGNED_ENVELOPE_EIP1559_FEE_MISMATCH');return recoverTransactionAddress({serializedTransaction}).then(address=>{if(address.toLowerCase()!==input.wallet.toLowerCase())throw new Error('SIGNED_ENVELOPE_SIGNER_MISMATCH');});
}

export async function executeGuardedV3Transaction(input:ExecuteGuardedV3Input){
  const tx=input.transaction,profile=chainProfile(tx.chainId),deployment=protocolDeployment(tx.chainId,tx.protocol);guardedV3ChainProtocol(tx.chainId,tx.protocol);const blockers=guardedV3ExecutionBlockers(input.readiness);if(blockers.length)throw new Error(`V3_EXECUTION_BLOCKED:${blockers.join(',')}`);if(input.deploymentEvidence&&(input.deploymentEvidence.status!=='VERIFIED'||input.deploymentEvidence.chainId!==tx.chainId||input.deploymentEvidence.protocol!==tx.protocol||input.deploymentEvidence.deploymentVersion!==deployment.registryVersion||input.deploymentEvidence.validUntilMs<(input.nowMs??Date.now())))throw new Error('CANONICAL_DEPLOYMENT_EVIDENCE_INVALID_OR_STALE');requireProtocolCapability(tx.chainId,tx.protocol,input.capability);assertGuardedV3TransactionSemantics(tx);if(tx.deploymentVersion!==deployment.registryVersion)throw new Error('DEPLOYMENT_VERSION_CHANGED');assertFreshFeeQuote(profile,input.feeQuote,{nowMs:input.nowMs,maxAgeMs:input.feeEvidenceMaxAgeMs});
  const simulation=await input.dependencies.simulate(tx,input.wallet);if(simulation.gas<=0n)throw new Error('V3_SIMULATION_GAS_INVALID');if(input.nativeUsd===undefined||!Number.isFinite(input.nativeUsd)||input.nativeUsd<=0)throw new Error(`${profile.nativeSymbol}_USD_VALUATION_REQUIRED_BEFORE_SIGNING`);const projectedNative=simulation.gas*(input.feeQuote.feeModel==='legacy'?input.feeQuote.gasPrice:input.feeQuote.maxFeePerGas),projectedGasUsd=Number(projectedNative)/1e18*input.nativeUsd;if(input.nativeBalance<projectedNative+tx.value)throw new Error('CHAIN_NATIVE_GAS_BALANCE_INSUFFICIENT_BEFORE_SIGNING');if(!Number.isFinite(input.maximumGasUsd)||projectedGasUsd>input.maximumGasUsd)throw new Error('V3_PROJECTED_TRANSACTION_GAS_CAP_EXCEEDED');if(!Number.isFinite(input.projectedLifecycleGasUsd)||!Number.isFinite(input.maximumLifecycleGasUsd)||input.projectedLifecycleGasUsd+projectedGasUsd>input.maximumLifecycleGasUsd)throw new Error('V3_PROJECTED_LIFECYCLE_GAS_CAP_EXCEEDED');const nonceEvidence=await input.dependencies.pendingNonce(input.wallet);if(!Number.isSafeInteger(nonceEvidence.nonce)||nonceEvidence.providerCount<=0)throw new Error('CHAIN_NONCE_EVIDENCE_UNHEALTHY');if(!input.repo.acquireChainNonceMutex(tx.chainId,input.wallet,BigInt(nonceEvidence.nonce)))throw new Error('CHAIN_NONCE_MUTEX_HELD');
  try{
    const request:Record<string,unknown>={chainId:tx.chainId,nonce:nonceEvidence.nonce,to:tx.to,data:tx.data,value:tx.value,gas:simulation.gas,type:input.feeQuote.feeModel==='legacy'?'legacy':'eip1559',...(input.feeQuote.feeModel==='legacy'?{gasPrice:input.feeQuote.gasPrice}:{maxFeePerGas:input.feeQuote.maxFeePerGas,maxPriorityFeePerGas:input.feeQuote.maxPriorityFeePerGas})};
    const serialized=await input.dependencies.sign(request);await assertSignedEnvelope({serialized,transaction:tx,wallet:input.wallet,nonce:nonceEvidence.nonce,gas:simulation.gas,feeQuote:input.feeQuote});const expectedHash=keccak256(serialized),fingerprint=requestFingerprint(request),prepared=input.repo.persistChainPreparedTransaction({chainId:tx.chainId,chainKey:profile.key,protocol:tx.protocol,journalId:input.journalId,wallet:input.wallet,workflowIdentity:input.workflowId,semanticStage:input.semanticStage,attempt:input.attempt,nonce:nonceEvidence.nonce,transactionType:input.feeQuote.feeModel,expectedHash,to:tx.to,requestFingerprint:fingerprint,feeModel:input.feeQuote.feeModel,projectedGasNative:projectedNative,projectedGasUsd});if(prepared.status!=='PREPARED')throw new Error('CHAIN_JOURNAL_ALREADY_SUBMITTED_RECOVERY_REQUIRED');
    let providerEvidence:unknown;try{const returned=await input.dependencies.broadcast(serialized);if(returned.toLowerCase()!==expectedHash.toLowerCase())throw new Error('BROADCAST_RETURNED_UNEXPECTED_HASH');providerEvidence={broadcastHashMatched:true};}catch(error){const observed=await input.dependencies.observe({expectedHash,wallet:input.wallet,nonce:nonceEvidence.nonce});if(observed.status==='CONFLICT')throw new Error('PROVIDER_SAME_NONCE_DIFFERENT_HASH');if(observed.status!=='FOUND'||observed.hash?.toLowerCase()!==expectedHash.toLowerCase())throw new Error('BROADCAST_UNCERTAIN_EXPECTED_HASH_NOT_OBSERVED');providerEvidence={providerAcceptedThenErrored:true,observation:observed.evidence,errorClass:error instanceof Error?error.name:'Error'};}
    input.repo.transitionChainTransaction({chainId:tx.chainId,journalId:input.journalId,from:'PREPARED',to:'SUBMITTED',providerEvidence});const receipt=await input.dependencies.waitForReceipt(expectedHash,input.confirmations);if(receipt.transactionHash.toLowerCase()!==expectedHash.toLowerCase())throw new Error('RECEIPT_EXACT_HASH_MISMATCH');const gas=actualGasEvidence({chainId:tx.chainId,nativeSymbol:profile.nativeSymbol,gasUsed:receipt.gasUsed,effectiveGasPrice:receipt.effectiveGasPrice,nativeUsd:input.nativeUsd,projectedNative:simulation.gas*(input.feeQuote.feeModel==='legacy'?input.feeQuote.gasPrice:input.feeQuote.maxFeePerGas)});if(receipt.status!=='success'){input.repo.transitionChainTransaction({chainId:tx.chainId,journalId:input.journalId,from:'SUBMITTED',to:'FAILED',receipt,confirmationCount:input.confirmations,actualGasNative:gas.actualNative,actualGasUsd:gas.actualUsd,failureReason:'TRANSACTION_REVERTED'});return {status:'CONFIRMED_REVERT',expectedHash,receipt,gas,reconciled:false};}
    input.repo.transitionChainTransaction({chainId:tx.chainId,journalId:input.journalId,from:'SUBMITTED',to:'CONFIRMED',receipt,confirmationCount:input.confirmations,actualGasNative:gas.actualNative,actualGasUsd:gas.actualUsd});const actualGasPolicyBreached=gas.actualUsd!==undefined&&gas.actualUsd>input.maximumGasUsd;input.repo.recordChainV3LifecycleEvent({chainId:tx.chainId,protocol:tx.protocol,workflowId:input.workflowId,semanticStage:input.semanticStage,eventKind:'RECEIPT_CONFIRMED',journalId:input.journalId,expectedHash,payload:{receipt,gas,actualGasPolicyBreached}});
    try{const reconciliation=await input.dependencies.reconcile?.({receipt,expectedHash,workflowId:input.workflowId,semanticStage:input.semanticStage});input.repo.recordChainV3LifecycleEvent({chainId:tx.chainId,protocol:tx.protocol,workflowId:input.workflowId,semanticStage:input.semanticStage,eventKind:'RECONCILED',journalId:input.journalId,expectedHash,payload:reconciliation??{}});return {status:'CONFIRMED_RECONCILED',expectedHash,receipt,gas,actualGasPolicyBreached,reconciliation};}catch(error){return {status:'CONFIRMED_ACCOUNTING_PENDING',expectedHash,receipt,gas,actualGasPolicyBreached,reconciliationError:error instanceof Error?error.message:'RECONCILIATION_FAILED'};}
  }finally{input.repo.releaseChainNonceMutex(tx.chainId,input.wallet);}
}

export async function simulateOnlyGuardedV3Transaction(input:Omit<ExecuteGuardedV3Input,'journalId'|'semanticStage'|'attempt'|'confirmations'|'dependencies'> & {dependencies:Pick<V3ExecutorDependencies,'simulate'|'pendingNonce'>}){
 const tx=input.transaction,profile=chainProfile(tx.chainId),deployment=protocolDeployment(tx.chainId,tx.protocol),blockers=guardedV3ExecutionBlockers(input.readiness),configurationBlockers=blockers.filter(code=>['CHAIN_DISABLED','CHAIN_EXECUTION_DISABLED','CHAIN_DRY_RUN_ENABLED','CHAIN_EMERGENCY_PAUSE','CHAIN_WALLET_REQUIRED','CHAIN_GAS_POLICY_REQUIRED'].includes(code));
 const base={chain:profile.key,chainId:tx.chainId,protocol:tx.protocol,action:input.capability,readinessState:blockers.length?(configurationBlockers.length?'GUARDED_LIVE_CONFIGURATION_BLOCKED':'GUARDED_LIVE_EVIDENCE_BLOCKED'):'GUARDED_LIVE_CODE_READY',capabilityBlockers:blockers,signerConstructed:false,nonceReserved:false,journalWritten:false,broadcastUsed:false};if(blockers.length)return {...base,simulationResult:'BLOCKED' as const};
 if(input.deploymentEvidence&&(input.deploymentEvidence.status!=='VERIFIED'||input.deploymentEvidence.chainId!==tx.chainId||input.deploymentEvidence.protocol!==tx.protocol||input.deploymentEvidence.deploymentVersion!==deployment.registryVersion||input.deploymentEvidence.validUntilMs<(input.nowMs??Date.now())))throw new Error('CANONICAL_DEPLOYMENT_EVIDENCE_INVALID_OR_STALE');requireProtocolCapability(tx.chainId,tx.protocol,input.capability);assertGuardedV3TransactionSemantics(tx);if(tx.deploymentVersion!==deployment.registryVersion)throw new Error('DEPLOYMENT_VERSION_CHANGED');assertFreshFeeQuote(profile,input.feeQuote,{nowMs:input.nowMs,maxAgeMs:input.feeEvidenceMaxAgeMs});const beforeJournal=Number((input.repo.db.prepare('SELECT COUNT(*) count FROM chain_transaction_journal WHERE chain_id=?').get(tx.chainId) as {count:number}).count),beforeMutex=Number((input.repo.db.prepare('SELECT COUNT(*) count FROM chain_nonce_mutex WHERE chain_id=?').get(tx.chainId) as {count:number}).count),simulation=await input.dependencies.simulate(tx,input.wallet);if(simulation.gas<=0n)throw new Error('V3_SIMULATION_GAS_INVALID');const feePerGas=input.feeQuote.feeModel==='legacy'?input.feeQuote.gasPrice:input.feeQuote.maxFeePerGas,projectedNative=simulation.gas*feePerGas;if(input.nativeBalance<projectedNative+tx.value)throw new Error('CHAIN_NATIVE_GAS_BALANCE_INSUFFICIENT_BEFORE_SIGNING');if(input.nativeUsd===undefined||!Number.isFinite(input.nativeUsd)||input.nativeUsd<=0)throw new Error(`${profile.nativeSymbol}_USD_VALUATION_REQUIRED_BEFORE_SIGNING`);const projectedGasUsd=Number(projectedNative)/1e18*input.nativeUsd;if(projectedGasUsd>input.maximumGasUsd)throw new Error('V3_PROJECTED_TRANSACTION_GAS_CAP_EXCEEDED');if(input.projectedLifecycleGasUsd+projectedGasUsd>input.maximumLifecycleGasUsd)throw new Error('V3_PROJECTED_LIFECYCLE_GAS_CAP_EXCEEDED');const nonce=await input.dependencies.pendingNonce(input.wallet);if(!Number.isSafeInteger(nonce.nonce)||nonce.providerCount<=0)throw new Error('CHAIN_NONCE_EVIDENCE_UNHEALTHY');const afterJournal=Number((input.repo.db.prepare('SELECT COUNT(*) count FROM chain_transaction_journal WHERE chain_id=?').get(tx.chainId) as {count:number}).count),afterMutex=Number((input.repo.db.prepare('SELECT COUNT(*) count FROM chain_nonce_mutex WHERE chain_id=?').get(tx.chainId) as {count:number}).count);if(beforeJournal!==afterJournal||beforeMutex!==afterMutex)throw new Error('SIMULATE_ONLY_STATE_MUTATION_DETECTED');return {...base,simulationResult:'VERIFIED' as const,estimatedGas:simulation.gas,fundingRequirement:tx.value,gasRequirement:projectedNative,estimatedGasUsd:projectedGasUsd,nonceEvidence:{latestOrPending:nonce.nonce,providerCount:nonce.providerCount},destinationVerified:true,selectorVerified:true};
}

export async function simulateOnlyGuardedV3Sequence(input:Omit<Parameters<typeof simulateOnlyGuardedV3Transaction>[0],'transaction'> & {transactions:readonly V3BuiltTransaction[]}){if(!input.transactions.length)throw new Error('SIMULATE_ONLY_SEQUENCE_EMPTY');const results=[];for(const transaction of input.transactions)results.push(await simulateOnlyGuardedV3Transaction({...input,transaction}));return {chain:chainProfile(input.transactions[0]!.chainId).key,chainId:input.transactions[0]!.chainId,protocol:input.transactions[0]!.protocol,action:input.capability,simulationResult:results.every(item=>item.simulationResult==='VERIFIED')?'VERIFIED':'BLOCKED',stages:results.map((item,index)=>({index,transactionAction:input.transactions[index]!.action,simulationResult:item.simulationResult,estimatedGas:'estimatedGas'in item?item.estimatedGas:undefined,capabilityBlockers:item.capabilityBlockers})),signerConstructed:false,nonceReserved:false,journalWritten:false,broadcastUsed:false};}

export async function recoverGuardedV3Transaction(input:{repo:SqliteLedgerRepository;chainId:GuardedV3Chain;protocol:GuardedV3Protocol;journalId:string;workflowId:string;semanticStage:string;wallet:Address;confirmations:number;dependencies:Pick<V3ExecutorDependencies,'observe'|'waitForReceipt'|'reconcile'>;nativeUsd?:number}){
  const row=input.repo.db.prepare('SELECT * FROM chain_transaction_journal WHERE chain_id=? AND protocol=? AND journal_id=?').get(input.chainId,input.protocol,input.journalId) as Record<string,unknown>|undefined;if(!row)throw new Error('CHAIN_JOURNAL_NOT_FOUND');if(String(row.wallet_address).toLowerCase()!==input.wallet.toLowerCase()||String(row.workflow_identity)!==input.workflowId||String(row.semantic_stage)!==input.semanticStage)throw new Error('CHAIN_JOURNAL_RECOVERY_SCOPE_MISMATCH');if(row.status==='CONFIRMED')return {status:'ALREADY_CONFIRMED',expectedHash:row.expected_hash};if(row.status==='FAILED')return {status:'ALREADY_FAILED',expectedHash:row.expected_hash};getAddress(input.wallet);const expectedHash=String(row.expected_hash) as Hex,observed=await input.dependencies.observe({expectedHash,wallet:input.wallet,nonce:Number(row.nonce)});if(observed.status==='CONFLICT')throw new Error('PROVIDER_SAME_NONCE_DIFFERENT_HASH');if(observed.status!=='FOUND')return {status:'PREPARED_NOT_BROADCAST',expectedHash};if(row.status==='PREPARED')input.repo.transitionChainTransaction({chainId:input.chainId,journalId:input.journalId,from:'PREPARED',to:'SUBMITTED',providerEvidence:{recoveredExactHash:true}});const receipt=await input.dependencies.waitForReceipt(expectedHash,input.confirmations);if(receipt.transactionHash.toLowerCase()!==expectedHash.toLowerCase())throw new Error('RECEIPT_EXACT_HASH_MISMATCH');const profile=chainProfile(input.chainId),gas=actualGasEvidence({chainId:input.chainId,nativeSymbol:profile.nativeSymbol,gasUsed:receipt.gasUsed,effectiveGasPrice:receipt.effectiveGasPrice,nativeUsd:input.nativeUsd});input.repo.transitionChainTransaction({chainId:input.chainId,journalId:input.journalId,from:'SUBMITTED',to:receipt.status==='success'?'CONFIRMED':'FAILED',receipt,confirmationCount:input.confirmations,actualGasNative:gas.actualNative,actualGasUsd:gas.actualUsd,failureReason:receipt.status==='success'?undefined:'TRANSACTION_REVERTED'});if(receipt.status!=='success')return {status:'CONFIRMED_REVERT',expectedHash,receipt,gas};try{await input.dependencies.reconcile?.({receipt,expectedHash,workflowId:input.workflowId,semanticStage:input.semanticStage});return {status:'CONFIRMED_RECONCILED',expectedHash,receipt,gas};}catch{return {status:'CONFIRMED_ACCOUNTING_PENDING',expectedHash,receipt,gas};}
}
