import { createHash } from 'node:crypto';
import type { Address, Hex } from 'viem';
import type { SqliteLedgerRepository, V4BidLadderUsdResetCreation } from '@funi/ledger';
import { priceFromSqrtX96, robinhoodMainnet } from '@funi/core';
import { amountsForLiquidity, classifyV4RangeState, poolId, sqrtPriceAtTick, type V4PoolKey, type V4PoolState } from '@funi/v4';
import { evaluateV4BidLadderV1, planV4BidLadderV1, v4BidLadderPersistencePlan, type V4BidLadderPlan, type V4BidLadderPlanInput } from './v4-bid-ladder-planner.js';

export type BidLadderToken = { address: Address; symbol: string; decimals: number };
export type V4BidLadderPreview = { plan: V4BidLadderPlan; funding: BidLadderToken; target: BidLadderToken; owner: Address };
export type V4BidLadderPreviewSnapshot = { ladderId:string;pool:{id:Hex;key:V4PoolKey;sqrtPriceX96:string;tick:number;liquidity:string;initialized:boolean;blockNumber:string;protocolFee?:number;lpFee?:number};funding:BidLadderToken;target:BidLadderToken;totalFundingAmount:string;maxDownsideBps:number;owner:Address;deadline:string;referenceBlockHash?:Hex;createdAtMs:number };

export function deterministicV4BidLadderId(input:{poolId:string;fundingToken:string;targetToken:string;totalFundingAmount:bigint;referenceBlock:bigint;referenceTick:number;maxDownsideBps?:number}){
 const parts=[input.poolId.toLowerCase(),input.fundingToken.toLowerCase(),input.targetToken.toLowerCase(),input.totalFundingAmount.toString(),input.referenceBlock.toString(),String(input.referenceTick)];
 if((input.maxDownsideBps??5000)!==5000)parts.push(String(input.maxDownsideBps));
 return `v4bid_${createHash('sha256').update(parts.join(':')).digest('hex').slice(0,32)}`;
}
export function previewV4BidLadder(input:{pool:V4PoolState;funding:BidLadderToken;target:BidLadderToken;totalFundingAmount:bigint;maxDownsideBps?:number;owner:Address;deadline:bigint;referenceBlockHash?:Hex;nowMs:number}):V4BidLadderPreview{
 const ladderId=deterministicV4BidLadderId({poolId:input.pool.id,fundingToken:input.funding.address,targetToken:input.target.address,totalFundingAmount:input.totalFundingAmount,referenceBlock:input.pool.blockNumber,referenceTick:input.pool.tick,maxDownsideBps:input.maxDownsideBps});
 const plan=planV4BidLadderV1({ladderId,pool:input.pool,fundingToken:input.funding.address,targetToken:input.target.address,totalFundingAmount:input.totalFundingAmount,fundingDecimals:input.funding.decimals,targetDecimals:input.target.decimals,owner:input.owner,deadline:input.deadline,referenceBlockHash:input.referenceBlockHash,nowMs:input.nowMs,maxDownsideBps:input.maxDownsideBps});
 return {plan,funding:input.funding,target:input.target,owner:input.owner};
}
export function snapshotV4BidLadderPreview(preview:V4BidLadderPreview):V4BidLadderPreviewSnapshot{const {plan}=preview;return {ladderId:plan.ladderId,pool:{id:plan.pool.id,key:plan.pool.key,sqrtPriceX96:plan.pool.sqrtPriceX96.toString(),tick:plan.pool.tick,liquidity:plan.pool.liquidity.toString(),initialized:plan.pool.initialized,blockNumber:plan.pool.blockNumber.toString(),protocolFee:plan.pool.protocolFee,lpFee:plan.pool.lpFee},funding:preview.funding,target:preview.target,totalFundingAmount:plan.totalFundingAmount.toString(),maxDownsideBps:plan.maxDownsideBps,owner:preview.owner,deadline:plan.legs[0]!.mint.deadline.toString(),referenceBlockHash:plan.referenceBlockHash,createdAtMs:plan.createdAtMs};}
export function restoreV4BidLadderPreview(snapshot:V4BidLadderPreviewSnapshot):V4BidLadderPreview{const pool:V4PoolState={...snapshot.pool,sqrtPriceX96:BigInt(snapshot.pool.sqrtPriceX96),liquidity:BigInt(snapshot.pool.liquidity),blockNumber:BigInt(snapshot.pool.blockNumber)};const plan=planV4BidLadderV1({ladderId:snapshot.ladderId,pool,fundingToken:snapshot.funding.address,targetToken:snapshot.target.address,totalFundingAmount:BigInt(snapshot.totalFundingAmount),fundingDecimals:snapshot.funding.decimals,targetDecimals:snapshot.target.decimals,owner:snapshot.owner,deadline:BigInt(snapshot.deadline),referenceBlockHash:snapshot.referenceBlockHash,nowMs:snapshot.createdAtMs,maxDownsideBps:snapshot.maxDownsideBps??5000});return {plan,funding:snapshot.funding,target:snapshot.target,owner:snapshot.owner};}
const symbolEvidence=(preview:V4BidLadderPreview)=>({source:'TRUSTED_SELECTION_ERC20_METADATA_V1',observedAtMs:preview.plan.createdAtMs,bindings:[{address:preview.target.address.toLowerCase(),symbol:preview.target.symbol},{address:preview.funding.address.toLowerCase(),symbol:preview.funding.symbol}]});
const persistedPlan=(preview:V4BidLadderPreview)=>({...v4BidLadderPersistencePlan(preview.plan),targetSymbol:preview.target.symbol,fundingSymbol:preview.funding.symbol,symbolProvenance:symbolEvidence(preview)});
export function createV4BidLadderDryRun(repo:SqliteLedgerRepository,preview:V4BidLadderPreview){return repo.createDryRunBidLadder(persistedPlan(preview));}
export function createV4BidLadderLive(repo:SqliteLedgerRepository,preview:V4BidLadderPreview,entryUsdSnapshot:number,reset?:V4BidLadderUsdResetCreation){if(!Number.isFinite(entryUsdSnapshot)||entryUsdSnapshot<=0)throw new Error('V4_BID_LADDER_ENTRY_USD_INVALID');return repo.createLiveBidLadder({...persistedPlan(preview),executionMode:'LIVE',entryUsdSnapshot},reset??{rootLadderId:preview.plan.ladderId,generation:0,creationReason:'INITIAL_OPEN'});}
const amount=(raw:bigint,decimals:number)=>{const base=10n**BigInt(decimals),whole=raw/base,fraction=(raw%base).toString().padStart(decimals,'0').slice(0,6).replace(/0+$/,'');return `${whole}${fraction?`.`+fraction:''}`;};
export function formatV4BidLadderPreview(preview:V4BidLadderPreview){const p=preview.plan;return ['V4 BID Ladder V1','DRY RUN','',`Pool: ${preview.target.symbol}/${preview.funding.symbol}`,`Fee: ${p.pool.key.fee}`,`Tick spacing: ${p.pool.key.tickSpacing}`,`PoolId: ${p.pool.id}`,`Reference tick: ${p.referenceTick}`,`Reference block: ${p.referenceBlock}`,`Requested max downside: ${p.maxDownsideBps/100}%`,`Capital: ${amount(p.totalFundingAmount,preview.funding.decimals)} ${preview.funding.symbol}`,'Actual snapped ranges: ',...p.legs.map(leg=>`#${leg.index+1}  -${leg.upperDropBps/100}% → -${leg.lowerDropBps/100}%  ${leg.weightBps/100}%\n${amount(leg.fundingAmount,preview.funding.decimals)} ${preview.funding.symbol} · ticks ${leg.tickLower} / ${leg.tickUpper}`),'','DRY RUN ONLY','No transaction will be signed or broadcast.','Manual close only.'].join('\n');}
export function evaluatePersistedV4BidLadder(input:{parent:Record<string,unknown>;legs:Record<string,unknown>[];current:Pick<V4PoolState,'sqrtPriceX96'|'tick'>}){const fundingIndex=Number(input.parent.funding_index) as 0|1,targetIndex=Number(input.parent.target_index) as 0|1,referenceSqrt=sqrtPriceAtTick(Number(input.parent.reference_tick)),plannedFunding=input.legs.reduce((sum,row)=>sum+BigInt(String(row.funding_amount_raw)),0n);const legs=input.legs.map(row=>{const liquidity=BigInt(String(row.planned_liquidity_raw)),amounts=amountsForLiquidity(input.current.sqrtPriceX96,Number(row.tick_lower),Number(row.tick_upper),liquidity),referenceAmounts=amountsForLiquidity(referenceSqrt,Number(row.tick_lower),Number(row.tick_upper),liquidity),state=classifyV4RangeState(input.current.tick,Number(row.tick_lower),Number(row.tick_upper)),funding=fundingIndex===0?amounts.token0:amounts.token1,target=targetIndex===0?amounts.token0:amounts.token1,referenceFunding=fundingIndex===0?referenceAmounts.token0:referenceAmounts.token1;return {index:Number(row.leg_index),state:state==='above_range'?'ABOVE_RANGE':state==='in_range'?'IN_RANGE':'BELOW_RANGE',funding,target,referenceFunding};});const deployedFundingAtReference=legs.reduce((sum,leg)=>sum+leg.referenceFunding,0n);return {legs,totalFunding:legs.reduce((sum,leg)=>sum+leg.funding,0n),totalTarget:legs.reduce((sum,leg)=>sum+leg.target,0n),plannedFunding,deployedFundingAtReference,unallocatedFundingDust:plannedFunding>deployedFundingAtReference?plannedFunding-deployedFundingAtReference:0n,counts:legs.reduce((counts,leg)=>({...counts,[leg.state==='ABOVE_RANGE'?'above':leg.state==='IN_RANGE'?'in':'below']:counts[leg.state==='ABOVE_RANGE'?'above':leg.state==='IN_RANGE'?'in':'below']+1}),{above:0,in:0,below:0}),feeAccountingMode:'NOT_MODELED_PHASE1' as const};}
export type PersistedV4BidLadderCurrentState=Pick<V4PoolState,'id'|'key'|'sqrtPriceX96'|'tick'|'liquidity'|'initialized'>;
export type V4BidLadderPerformance={deployedUsd:number;currentPrincipalUsd:number|null;principal:{token0:bigint;token1:bigint};unrealizedPnlUsd:number|null;unrealizedPnlPct:number|null;claimedFeesUsd:number|null;unclaimedFeesUsd:number|null;totalFeesUsd:number|null;totalPnlUsd:number|null;totalPnlPct:number|null;claimedCurrentValue:boolean;feeBatchRpcCount:0|1|2;feeBatchLatencyMs:number|null};
const same=(a:unknown,b:unknown)=>String(a).toLowerCase()===String(b).toLowerCase();
export function bindPersistedV4BidLadderCurrentState(parent:Record<string,unknown>,current:PersistedV4BidLadderCurrentState|undefined){
 if(!current||!current.key||typeof current.id!=='string'||typeof current.sqrtPriceX96!=='bigint'||typeof current.liquidity!=='bigint'||!Number.isInteger(current.tick)||typeof current.initialized!=='boolean'||current.sqrtPriceX96<0n||current.liquidity<0n)return {status:'unavailable' as const};
 try{const expected=String(parent.pool_id),computed=poolId(current.key);if(!same(current.id,expected)||!same(computed,expected)||!same(current.key.currency0,parent.currency0)||!same(current.key.currency1,parent.currency1)||current.key.fee!==Number(parent.fee)||current.key.tickSpacing!==Number(parent.tick_spacing)||!same(current.key.hooks,parent.hooks))return {status:'unavailable' as const};return {status:'available' as const,value:current};}catch{return {status:'unavailable' as const};}
}
function unavailableInventoryLines(input:{legs:Record<string,unknown>[];funding:BidLadderToken}){const planned=input.legs.reduce((sum,row)=>sum+BigInt(String(row.funding_amount_raw)),0n);return [...input.legs.map(leg=>`#${Number(leg.leg_index)+1} · planned ${amount(BigInt(String(leg.funding_amount_raw)),input.funding.decimals)} ${input.funding.symbol} · ticks ${String(leg.tick_lower)} / ${String(leg.tick_upper)} · Inventory unavailable`),'',`Planned funding: ${amount(planned,input.funding.decimals)} ${input.funding.symbol}`,'Current inventory: Unavailable'];}
const positive=(value:unknown):value is number=>typeof value==='number'&&Number.isFinite(value)&&value>0;
export type V4BidLadderMarketCapEvidence={marketCapUsd:number;tokenPriceUsd:number};
/** Display-only GMGN token-info evidence for the persisted BID Ladder detail view. */
export function displayV4BidLadderMarketCapEvidence(input:{raw:unknown;observation:{tokenAddress:string;marketCapUsd?:number};targetAddress:string}):V4BidLadderMarketCapEvidence|undefined{
 if(!same(input.observation.tokenAddress,input.targetAddress))return undefined;
 const row=input.raw&&typeof input.raw==='object'&&!Array.isArray(input.raw)?input.raw as Record<string,unknown>:undefined,
   priceRow=row?.price&&typeof row.price==='object'&&!Array.isArray(row.price)?row.price as Record<string,unknown>:undefined,
   tokenPriceUsd=Number(priceRow?.price);
 if(!positive(tokenPriceUsd))return undefined;
 const canonical=input.observation.marketCapUsd;
 if(positive(canonical))return {marketCapUsd:canonical,tokenPriceUsd};
 const circulatingSupply=Number(row?.circulating_supply),totalSupply=Number(row?.total_supply),supply=positive(circulatingSupply)?circulatingSupply:positive(totalSupply)?totalSupply:undefined;
 return supply===undefined?undefined:{marketCapUsd:tokenPriceUsd*supply,tokenPriceUsd};
}
export function estimateV4BidLadderMarketCapRange(input:{parent:Record<string,unknown>;legs:Record<string,unknown>[];target:BidLadderToken;funding:BidLadderToken;evidence?:V4BidLadderMarketCapEvidence}){
 const evidence=input.evidence,targetIndex=Number(input.parent.target_index) as 0|1;
 if(!evidence||!positive(evidence.marketCapUsd)||!positive(evidence.tokenPriceUsd)||input.legs.length===0||!(targetIndex===0||targetIndex===1))return null;
 const first=input.legs[0]!,last=input.legs.at(-1)!;
 const startTick=targetIndex===0?Number(first.tick_upper):Number(first.tick_lower),deepestTick=targetIndex===0?Number(last.tick_lower):Number(last.tick_upper);
 const targetPriceAt=(tick:number)=>{const token1PerToken0=priceFromSqrtX96(sqrtPriceAtTick(tick),targetIndex===0?input.target.decimals:input.funding.decimals,targetIndex===1?input.target.decimals:input.funding.decimals);return targetIndex===0?token1PerToken0:1/token1PerToken0;};
 try{const startPrice=targetPriceAt(startTick),deepestPrice=targetPriceAt(deepestTick);if(!positive(startPrice)||!positive(deepestPrice))return null;const startUsd=evidence.marketCapUsd*startPrice/evidence.tokenPriceUsd,deepestUsd=evidence.marketCapUsd*deepestPrice/evidence.tokenPriceUsd;if(!positive(startUsd)||!positive(deepestUsd)||startUsd<deepestUsd)return null;return {startUsd,deepestUsd,startTick,deepestTick};}catch{return null;}
}
const compactUsd=(value:number)=>{if(!positive(value))return 'Unavailable';const units=[[1_000_000_000,'B'],[1_000_000,'M'],[1_000,'K']] as const;for(const [unit,label] of units)if(value>=unit){const scaled=value/unit;return `$${scaled.toLocaleString('en-US',{maximumFractionDigits:scaled>=100?0:scaled>=10?1:2})}${label}`;}return `$${value.toLocaleString('en-US',{maximumFractionDigits:value>=1?2:Math.min(8,Math.max(2,Math.ceil(-Math.log10(value))+2))})}`;};
function marketCapLines(input:{parent:Record<string,unknown>;legs:Record<string,unknown>[];target:BidLadderToken;funding:BidLadderToken;evidence?:V4BidLadderMarketCapEvidence}){const estimate=estimateV4BidLadderMarketCapRange(input),current=input.evidence?.marketCapUsd,valid=positive(current)&&positive(input.evidence?.tokenPriceUsd);return [`Current MC: ${valid?compactUsd(current):'Unavailable'}`,`Estimated ladder MC range: ${estimate?`${compactUsd(estimate.startUsd)} → ${compactUsd(estimate.deepestUsd)}`:'Unavailable'}`];}
function rawNonnegative(value:unknown,code:string){try{if(value===null||value===undefined||!/^\d+$/.test(String(value)))throw new Error(code);const parsed=BigInt(String(value));if(parsed<0n)throw new Error(code);return parsed;}catch{throw new Error(code);}}
function usdValue(raw:{token0:bigint;token1:bigint},prices:{token0Usd:number;token1Usd:number}|null,decimals:{token0:number;token1:number},stableIndex:0|1){if(!prices){const nonStable=stableIndex===0?raw.token1:raw.token0;if(nonStable!==0n)return null;return Number(stableIndex===0?raw.token0:raw.token1)/10**(stableIndex===0?decimals.token0:decimals.token1);}const value=Number(raw.token0)/10**decimals.token0*prices.token0Usd+Number(raw.token1)/10**decimals.token1*prices.token1Usd;return Number.isFinite(value)&&value>=0?value:null;}
export function calculateOpenV4BidLadderPerformance(input:{parent:Record<string,unknown>;legs:Record<string,unknown>[];positions:Record<string,unknown>[];current:Pick<V4PoolState,'sqrtPriceX96'|'liquidity'|'initialized'>;token0:BidLadderToken;token1:BidLadderToken;unclaimed?:{status:'available';token0:bigint;token1:bigint;rpcRoundTrips:2;latencyMs:number}|{status:'unavailable'}}):V4BidLadderPerformance|undefined{
 if(String(input.parent.status)!=='OPEN')return undefined;
 if(input.legs.length!==5||input.positions.length!==5)throw new Error('V4_BID_LADDER_PERFORMANCE_POSITION_SET_INVALID');
 const usdg=robinhoodMainnet.assets.USDG.toLowerCase(),stableIndex=input.token0.address.toLowerCase()===usdg?0:input.token1.address.toLowerCase()===usdg?1:null;if(stableIndex===null)throw new Error('V4_BID_LADDER_USD_VALUATION_UNAVAILABLE');
 const ratio=input.current.initialized&&input.current.liquidity>0n?priceFromSqrtX96(input.current.sqrtPriceX96,input.token0.decimals,input.token1.decimals):null,prices=ratio===null?null:stableIndex===0?{token0Usd:1,token1Usd:1/ratio}:{token0Usd:ratio,token1Usd:1};
 if(prices&&(!positive(prices.token0Usd)||!positive(prices.token1Usd)))throw new Error('V4_BID_LADDER_USD_VALUATION_UNAVAILABLE');
 const decimals={token0:input.token0.decimals,token1:input.token1.decimals},byTokenId=new Map(input.positions.map(row=>[String(row.token_id),row])),principal={token0:0n,token1:0n},claimed={token0:0n,token1:0n};let claimedAvailable=true;
 for(const leg of input.legs){const tokenId=leg.token_id;if(tokenId===null||tokenId===undefined)throw new Error('V4_BID_LADDER_TOKEN_ID_MISSING');const row=byTokenId.get(String(tokenId));if(!row)throw new Error('V4_BID_LADDER_POSITION_MISSING');const liquidity=rawNonnegative(row.liquidity_raw,'V4_BID_LADDER_LIQUIDITY_MALFORMED'),tickLower=Number(row.tick_lower),tickUpper=Number(row.tick_upper);if(!Number.isInteger(tickLower)||!Number.isInteger(tickUpper)||tickLower>=tickUpper)throw new Error('V4_BID_LADDER_POSITION_RANGE_MALFORMED');const amounts=amountsForLiquidity(input.current.sqrtPriceX96,tickLower,tickUpper,liquidity);principal.token0+=amounts.token0;principal.token1+=amounts.token1;try{claimed.token0+=rawNonnegative(row.claimed_fee0_raw,'V4_BID_LADDER_CLAIMED_FEE_MALFORMED');claimed.token1+=rawNonnegative(row.claimed_fee1_raw,'V4_BID_LADDER_CLAIMED_FEE_MALFORMED');}catch{claimedAvailable=false;}}
 const deployedUsd=Number(input.parent.entry_usd_snapshot),currentPrincipalUsd=usdValue(principal,prices,decimals,stableIndex);if(!positive(deployedUsd))throw new Error('V4_BID_LADDER_ENTRY_USD_INVALID');const unrealizedPnlUsd=currentPrincipalUsd===null?null:currentPrincipalUsd-deployedUsd,unrealizedPnlPct=unrealizedPnlUsd===null?null:unrealizedPnlUsd/deployedUsd*100,claimedFeesUsd=claimedAvailable?usdValue(claimed,prices,decimals,stableIndex):null,unclaimedFeesUsd=input.unclaimed?.status==='available'?usdValue(input.unclaimed,prices,decimals,stableIndex):null,totalFeesUsd=claimedFeesUsd===null||unclaimedFeesUsd===null?null:claimedFeesUsd+unclaimedFeesUsd,totalPnlUsd=totalFeesUsd===null||unrealizedPnlUsd===null?null:unrealizedPnlUsd+totalFeesUsd;
 return {deployedUsd,currentPrincipalUsd,principal,unrealizedPnlUsd,unrealizedPnlPct,claimedFeesUsd,unclaimedFeesUsd,totalFeesUsd,totalPnlUsd,totalPnlPct:totalPnlUsd===null?null:totalPnlUsd/deployedUsd*100,claimedCurrentValue:claimedAvailable&&(input.token0.address.toLowerCase()===usdg?claimed.token1:claimed.token0)>0n,feeBatchRpcCount:input.unclaimed?.status==='available'?input.unclaimed.rpcRoundTrips:0,feeBatchLatencyMs:input.unclaimed?.status==='available'?input.unclaimed.latencyMs:null};
}
const accountingUsd=(value:number)=>`$${value.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const signedUsd=(value:number)=>Math.abs(value)<.005?'$0.00':`${value>0?'+':'-'}$${Math.abs(value).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const signedPerformance=(usd:number,pct:number)=>{const displayPct=Math.abs(pct)<.005?0:pct;return `${signedUsd(usd)} (${displayPct>0?'+':''}${displayPct.toFixed(2)}%)`;};
function performanceLines(value:V4BidLadderPerformance){const principal=value.currentPrincipalUsd===null?'Unavailable':accountingUsd(value.currentPrincipalUsd),unrealized=value.unrealizedPnlUsd===null||value.unrealizedPnlPct===null?'Unavailable':signedPerformance(value.unrealizedPnlUsd,value.unrealizedPnlPct),claimed=value.claimedFeesUsd===null?'Unavailable':`${accountingUsd(value.claimedFeesUsd)}${value.claimedCurrentValue?' (current value)':''}`,unclaimed=value.unclaimedFeesUsd===null?'Unavailable':accountingUsd(value.unclaimedFeesUsd),totalFees=value.totalFeesUsd===null?'Unavailable':accountingUsd(value.totalFeesUsd),totalPnl=value.totalPnlUsd===null||value.totalPnlPct===null?'Unavailable':signedPerformance(value.totalPnlUsd,value.totalPnlPct);return ['Performance',`Deployed: ${accountingUsd(value.deployedUsd)}`,`Current principal: ${principal}`,`Unrealized PnL: ${unrealized}`,'','Fees',`Claimed: ${claimed}`,`Unclaimed: ${unclaimed}`,`Total fees: ${totalFees}`,'',`Total PnL incl. fees: ${totalPnl}`];}
export function formatPersistedV4BidLadder(input:{parent:Record<string,unknown>;legs:Record<string,unknown>[];funding:BidLadderToken;target:BidLadderToken;current?:PersistedV4BidLadderCurrentState;poolUsdMetricLine?:string;marketCapEvidence?:V4BidLadderMarketCapEvidence;performance?:V4BidLadderPerformance}){const status=String(input.parent.status),cancelledReason=status==='CANCELLED'&&String(input.parent.terminal_reason)==='AUTO_EXPIRED_PLANNED_30M'?['Expired after 30 minutes without execution.']:[],market=marketCapLines({parent:input.parent,legs:input.legs,target:input.target,funding:input.funding,evidence:input.marketCapEvidence}),base=status==='OPEN'?[`V4 BID Ladder V1 · OPEN`,'','Market',...market]:['V4 BID Ladder V1',`Status: ${status}`,...cancelledReason,...market],bound=bindPersistedV4BidLadderCurrentState(input.parent,input.current),metric=input.poolUsdMetricLine??'Pool TVL: Unavailable';if(bound.status==='unavailable'||!bound.value.initialized)return [...base,'Current state: Unavailable',metric,'Inventory evaluation: Unavailable',...unavailableInventoryLines(input),...(status==='OPEN'?[]:['Fees: not modeled in Phase 1'])].join('\n');const current=bound.value,performance=status==='OPEN'&&input.performance?['',...performanceLines(input.performance),'','Ladder',`Ladder: ${String(input.parent.ladder_id)}`,`Reference tick: ${String(input.parent.reference_tick)}`,`Reference block: ${String(input.parent.reference_block)}`]:[`Ladder: ${String(input.parent.ladder_id)}`,`Reference tick: ${String(input.parent.reference_tick)}`,`Reference block: ${String(input.parent.reference_block)}`];if(current.liquidity===0n)return [...base,`Current tick: ${current.tick}`,'Liquidity status: NO ACTIVE LIQUIDITY',metric,...performance,'Pool state: NO ACTIVE LIQUIDITY','Inventory evaluation: Unavailable','',...unavailableInventoryLines(input),...(status==='OPEN'?[]:['Fees: not modeled in Phase 1'])].join('\n');const value=evaluatePersistedV4BidLadder({parent:input.parent,legs:input.legs,current});return [...base,metric,`Current tick: ${current.tick}`,'Liquidity status: Active',...performance,'',...value.legs.map(leg=>`#${leg.index+1} ${leg.state} · ${amount(leg.funding,input.funding.decimals)} ${input.funding.symbol} · ${amount(leg.target,input.target.decimals)} ${input.target.symbol}`),'',`Planned funding: ${amount(value.plannedFunding,input.funding.decimals)} ${input.funding.symbol}`,`Deployed at reference: ${amount(value.deployedFundingAtReference,input.funding.decimals)} ${input.funding.symbol}`,`Unallocated deterministic dust: ${amount(value.unallocatedFundingDust,input.funding.decimals)} ${input.funding.symbol}`,`Aggregate funding: ${amount(value.totalFunding,input.funding.decimals)} ${input.funding.symbol}`,`Aggregate target: ${amount(value.totalTarget,input.target.decimals)} ${input.target.symbol}`,`Legs above/in/below: ${value.counts.above}/${value.counts.in}/${value.counts.below}`,...(status==='OPEN'?[]:['Fees: not modeled in Phase 1'])].join('\n');}
