import { getAddress, type Address, type Hex } from 'viem';
import { V4_ROBINHOOD_DEPLOYMENTS, auditRobinhoodV4Deployments, buildV4SingleSidedDownsidePlan, discoverV4Pools, inspectV4Pool, inspectV4PositionState, inspectV4PositionTerminalAware, permit2Allowance, poolId, type V4DownsideRangeRequest, type V4PoolKey } from '@robin/v4';
import { inspectErc20, priceFromSqrtX96, robinhoodMainnet, type FallbackRpc } from '@robin/core';
import type { SqliteLedgerRepository } from '@robin/ledger';
import { prepareV4Lifecycle, type V4LifecycleAction } from './v4-lifecycle.js';

export async function v4DeploymentStatus(rpc:FallbackRpc){const audit=await auditRobinhoodV4Deployments(rpc);if(audit.status==='unavailable')return audit;return {status:'available' as const,...audit.value.verification,deployment:V4_ROBINHOOD_DEPLOYMENTS,runtimeFingerprints:audit.value.runtimeFingerprints,provenance:audit.provenance,verificationBasis:'verified by official registry + on-chain bytecode/interface/relationship checks'};}
export async function v4PoolDiscover(rpc:FallbackRpc,token:Address){const found=await discoverV4Pools(rpc,token);if(found.status==='unavailable')return found;return {status:'available' as const,value:found.value.map(pool=>({...pool,active:pool.initialized&&pool.liquidity>0n,poolId:pool.id})),provenance:found.provenance};}
export async function v4PoolInspectById(rpc:FallbackRpc,id:string){const found=await discoverV4Pools(rpc,robinhoodMainnet.assets.WETH);if(found.status==='unavailable')return found;const pool=found.value.find(x=>x.id.toLowerCase()===id.toLowerCase());return pool?{status:'available' as const,value:pool,provenance:found.provenance}:{status:'unavailable' as const,reason:'V4_POOL_ID_NOT_DISCOVERED'};}
export async function v4OpenPreflight(rpc:FallbackRpc,target:Address,funding:Address,amount:bigint,poolIdInput?:string,owner:Address='0x0000000000000000000000000000000000000001',range:V4DownsideRangeRequest={upperDropPct:0,lowerDropPct:10}){const found=await discoverV4Pools(rpc,target);if(found.status==='unavailable')return found;const pair=[target,funding].sort((a,b)=>a.toLowerCase().localeCompare(b.toLowerCase())),candidates=found.value.filter(pool=>pool.key.currency0.toLowerCase()===pair[0]!.toLowerCase()&&pool.key.currency1.toLowerCase()===pair[1]!.toLowerCase()&&pool.liquidity>0n),pool=poolIdInput?candidates.find(x=>x.id.toLowerCase()===poolIdInput.toLowerCase()):candidates.sort((a,b)=>b.liquidity>a.liquidity?-1:1)[0];if(!pool)return {status:'unavailable' as const,reason:'V4_ACTIVE_DIRECT_POOL_UNAVAILABLE'};const [t,f,block]=await Promise.all([inspectErc20(rpc,target),inspectErc20(rpc,funding),rpc.withClient(c=>c.getBlock())]);if(t.status==='unavailable'||f.status==='unavailable')return {status:'unavailable' as const,reason:'token inspection failed'};const displayed=priceFromSqrtX96(pool.sqrtPriceX96,pool.key.currency0.toLowerCase()===target.toLowerCase()?t.value.decimals:f.value.decimals,pool.key.currency0.toLowerCase()===target.toLowerCase()?f.value.decimals:t.value.decimals),plan=buildV4SingleSidedDownsidePlan(pool,amount,owner,block.timestamp+600n,range);return {status:'NO_BROADCAST' as const,protocolVersion:'v4',pool:{...pool,poolId:poolId(pool.key)},target:t.value,funding:f.value,fundingAmount:amount,currentDisplayedPrice:pool.key.currency0.toLowerCase()===target.toLowerCase()?displayed:1/displayed,range:{requested:plan.requestedRange,effective:plan.effectiveRange,tickLower:plan.tickLower,tickUpper:plan.tickUpper},plan,approvalRequirements:['ERC20_TO_PERMIT2_REQUIRED','PERMIT2_TO_POSITION_MANAGER_REQUIRED'],mainnetTransactionsSent:0};}

async function terminalChain(rpc:FallbackRpc,repo:SqliteLedgerRepository,tokenId:bigint){const evidence=repo.v4BurnEvidence(tokenId);return inspectV4PositionTerminalAware(rpc,tokenId,{previouslyMinted:evidence.previouslyMinted,burnConfirmed:evidence.burnConfirmed,burnTxHash:evidence.burnTxHash as Hex|undefined});}
export async function v4PositionInspect(rpc:FallbackRpc,repo:SqliteLedgerRepository,tokenId:bigint){
 const ledger=repo.v4Position(tokenId),chain=await terminalChain(rpc,repo,tokenId);
 if('status' in chain&&chain.status==='burned')repo.finalizeV4TerminalAccounting(tokenId);
 const accounting=repo.positionAccounting(`v4:${tokenId}`);let allowanceAudit:unknown,terminalPnl:unknown;
 if(ledger){
  const owner=getAddress(String(ledger.owner)),funding=getAddress(String(ledger.funding_token??ledger.currency1)),key=JSON.parse(String(ledger.pool_key_json)) as V4PoolKey,fundingIndex=Number(ledger.funding_index??1) as 0|1,targetIndex=(fundingIndex===0?1:0) as 0|1,erc20Abi=[{type:'function',name:'allowance',stateMutability:'view',inputs:[{type:'address'},{type:'address'}],outputs:[{type:'uint256'}]}] as const;
  const [erc20,permit,block,pool,token0,token1]=await Promise.all([rpc.withClient(c=>c.readContract({address:funding,abi:erc20Abi,functionName:'allowance',args:[owner,V4_ROBINHOOD_DEPLOYMENTS.permit2]})),permit2Allowance(rpc,owner,funding,V4_ROBINHOOD_DEPLOYMENTS.positionManager),rpc.withClient(c=>c.getBlock()),inspectV4Pool(rpc,key),inspectErc20(rpc,key.currency0),inspectErc20(rpc,key.currency1)]);
  allowanceAudit={fundingToken:funding,erc20ToPermit2:{amount:erc20,usable:erc20>0n},permit2ToPositionManager:{amount:permit[0],expiration:permit[1],nonce:permit[2],usable:permit[0]>0n&&BigInt(permit[1])>block.timestamp}};
  if('status' in chain&&chain.status==='burned'){
   repo.db.prepare('UPDATE v4_live_canary SET remaining_allowance_raw=? WHERE token_id=? AND remaining_allowance_raw IS NULL').run(permit[0].toString(),tokenId.toString());
   const d0=token0.status==='available'?token0.value.decimals:Number(ledger.target_index===0?ledger.target_decimals:ledger.funding_decimals),d1=token1.status==='available'?token1.value.decimals:Number(ledger.target_index===1?ledger.target_decimals:ledger.funding_decimals),fundingSymbol=String(ledger.funding_symbol??(funding.toLowerCase()===robinhoodMainnet.assets.USDG.toLowerCase()?'USDG':'UNKNOWN')),nativeUsd=Number(process.env.GAS_USD_PER_NATIVE),fundingUsd=fundingSymbol==='USDG'?1:fundingSymbol==='WETH'&&Number.isFinite(nativeUsd)&&nativeUsd>0?nativeUsd:undefined;
   if(pool.status==='available'&&Number.isInteger(d0)&&Number.isInteger(d1)&&fundingUsd!==undefined){const onePerZero=priceFromSqrtX96(pool.value.sqrtPriceX96,d0,d1),usd0=fundingIndex===0?fundingUsd:fundingUsd/onePerZero,usd1=fundingIndex===1?fundingUsd:fundingUsd*onePerZero,initialRaw=fundingIndex===0?accounting.deposits.token0:accounting.deposits.token1,fundingDecimals=fundingIndex===0?d0:d1,initialFunding=Number(initialRaw)/10**fundingDecimals*fundingUsd,realizedValue=Number(accounting.withdrawnPrincipal.token0+accounting.claimedFees.token0)/10**d0*usd0+Number(accounting.withdrawnPrincipal.token1+accounting.claimedFees.token1)/10**d1*usd1,grossPnl=realizedValue-initialFunding;terminalPnl={status:'available',initialFundingUsd:initialFunding,realizedValueUsd:realizedValue,grossPnlUsd:grossPnl,fundingHoldBenchmarkUsd:initialFunding,lpVsFundingHoldUsd:grossPnl,gasCostUsd:accounting.gasUsd,executionDifferenceRaw:accounting.terminalDifferences,netAfterGasPnlUsd:grossPnl-accounting.gasUsd,priceSource:fundingSymbol==='USDG'?'v4 StateView direct USDG price':'v4 StateView direct WETH price + configured native USD'};}else terminalPnl={status:'USD_PNL_UNAVAILABLE',tokenDenominated:{withdrawnPrincipal:accounting.withdrawnPrincipal,claimedFees:accounting.claimedFees,terminalDifferences:accounting.terminalDifferences},fundingToken:funding,targetIndex,reason:'reliable funding-asset USD price or token decimals unavailable'};
  }
 }
 return {protocolVersion:'v4',tokenId,status:'status' in chain?chain.status:String(ledger?.status??'open'),terminal:'terminal' in chain?chain.terminal:false,owner:'owner' in chain?chain.owner:null,onchainLiquidity:'onchainLiquidity' in chain?chain.onchainLiquidity:chain.liquidity,nftExists:'nftExists' in chain?chain.nftExists:true,chain,ledger:repo.v4Position(tokenId),accounting,terminalPnl,allowanceAudit,lifecycle:repo.v4LifecycleHistory(tokenId)};
}
export async function v4PositionReconcile(rpc:FallbackRpc,repo:SqliteLedgerRepository,tokenId:bigint){const row=repo.v4Position(tokenId);if(!row)throw new Error('V4_POSITION_NOT_FOUND');const before=repo.reconciliationDelta(`v4:${tokenId}`),chain=await terminalChain(rpc,repo,tokenId);let terminalDifferencesInserted=0,status:string,onchainLiquidity:bigint;if('status' in chain){if(chain.status==='not_found')return {...chain,ledgerChanges:{eventsInserted:0,depositsInserted:0,principalAllocationsInserted:0,feeAllocationsInserted:0,terminalDifferencesInserted:0}};status='burned';onchainLiquidity=0n;terminalDifferencesInserted=repo.finalizeV4TerminalAccounting(tokenId).inserted;}else{onchainLiquidity=chain.liquidity;status=chain.liquidity===0n?'closed':String(row.status)==='partially_closed'?'partially_closed':'open';repo.db.prepare('UPDATE v4_positions SET liquidity_raw=?,status=?,updated_at=? WHERE token_id=?').run(chain.liquidity.toString(),status,new Date().toISOString(),tokenId.toString());}const after=repo.reconciliationDelta(`v4:${tokenId}`),ledgerChanges={eventsInserted:after.events-before.events,depositsInserted:after.deposits-before.deposits,principalAllocationsInserted:after.principal-before.principal,feeAllocationsInserted:after.fees-before.fees,terminalDifferencesInserted};return {tokenId,status,terminal:status==='burned',owner:status==='burned'?null:chain.owner,onchainLiquidity,nftExists:status!=='burned',ledgerChanges,accounting:repo.positionAccounting(`v4:${tokenId}`)};}
export async function v4LifecyclePreflight(rpc:FallbackRpc,repo:SqliteLedgerRepository,wallet:Address,tokenId:bigint,action:V4LifecycleAction,percent?:25|50|75){const prepared=await prepareV4Lifecycle({rpc,wallet,tokenId,action,percent,slippageBps:50,deadlineSeconds:600});return {status:'NO_BROADCAST',protocolVersion:'v4',tokenId,action,percent,poolId:prepared.state.pool.id,currentLiquidity:prepared.state.liquidity,liquidityToRemove:prepared.removedLiquidity,expectedPrincipal:prepared.principal,minimums:{amount0:prepared.plan.amount0Min,amount1:prepared.plan.amount1Min},calldataHash:prepared.plan.calldataHash,mainnetTransactionsSent:0};}
export function v4PnlAudit(repo:SqliteLedgerRepository,tokenId:bigint){const positionId=`v4:${tokenId}`,position=repo.v4Position(tokenId);return {position,accounting:repo.positionAccounting(positionId),totals:repo.collectionTotals(positionId),snapshots:repo.db.prepare('SELECT id,payload_json,created_at FROM pnl_snapshots WHERE position_id=? ORDER BY created_at').all(positionId),fundingHoldBenchmark:position?.funding_token?`original ${String(position.funding_symbol??position.funding_token)} funding deposit`:'historical currency1 funding deposit',usdStatus:position?.funding_token?'VALUATION_REQUIRES_VERIFIED_PRICE_PROVENANCE':'HISTORICAL_METADATA_FALLBACK'};}
export function v4LifecycleAudit(repo:SqliteLedgerRepository,tokenId:bigint){return {position:repo.v4Position(tokenId),history:repo.v4LifecycleHistory(tokenId),receipts:repo.db.prepare('SELECT r.tx_hash,r.intent_id,r.created_at FROM v4_lifecycle_receipts r JOIN v4_lifecycle_intents i ON i.id=r.intent_id WHERE i.token_id=? ORDER BY r.created_at').all(tokenId.toString())};}
