import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { createWalletClient, decodeEventLog, encodeFunctionData, http, keccak256, type Address, type Hash, type Hex } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { FallbackRpc, robinhoodMainnet } from '@robin/core';
import { V4_ROBINHOOD_DEPLOYMENTS, auditRobinhoodV4Deployments, buildStrictToken1Plan, discoverV4Pools, inspectV4Pool, inspectV4Position, permit2Allowance, permit2ApproveAbi, positionManagerAbi } from '@robin/v4';
import { dedicatedWallet } from './runtime.js';
import { startPinnedFork } from './fork-fixture.js';

const erc20WriteAbi=[{type:'function',name:'approve',stateMutability:'nonpayable',inputs:[{type:'address'},{type:'uint256'}],outputs:[{type:'bool'}]},{type:'function',name:'transfer',stateMutability:'nonpayable',inputs:[{type:'address'},{type:'uint256'}],outputs:[{type:'bool'}]},{type:'function',name:'allowance',stateMutability:'view',inputs:[{type:'address'},{type:'address'}],outputs:[{type:'uint256'}]},{type:'function',name:'balanceOf',stateMutability:'view',inputs:[{type:'address'}],outputs:[{type:'uint256'}]}] as const;
const json=(x:unknown)=>JSON.stringify(x,(_,v)=>typeof v==='bigint'?v.toString():v,2);
const assert: (ok:unknown,message:string)=>asserts ok=(ok,message)=>{if(!ok)throw new Error(message);};
const forkChain={id:4663,name:'Robinhood Fork',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:{default:{http:['http://127.0.0.1']}}} as const;
export async function runV4ForkE2E(){const fork=await startPinnedFork(),artifactPath=join(fork.dir,'v4-fork-e2e.json'),artifact:any={artifactPath,localRpcUrl:fork.url,mainnetTransactionsSent:0};try{const rpc=new FallbackRpc({...robinhoodMainnet,rpcUrls:[fork.url]}),audit=await auditRobinhoodV4Deployments(rpc,async url=>fetch(url));assert(audit.status==='available','v4 deployment verification failed on fork');const discovered=await discoverV4Pools(rpc,robinhoodMainnet.assets.WETH),pool=discovered.status==='available'?discovered.value.find(x=>x.id.toLowerCase()==='0xfcfae8fa0bd6da961bcf5d990f27690932deac4f093e99bf3e871691c6586593'):undefined;assert(pool&&pool.liquidity>0n,'active target v4 pool unavailable on pinned fork');
 const operator=privateKeyToAccount('0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d'),wallet=createWalletClient({account:operator,chain:forkChain,transport:http(fork.url)}),source='0x52e65B17fB6E5BA00Ed806f37Afcd2DaA50271Ca' as Address;await (fork.client as any).request({method:'anvil_setBalance',params:[operator.address,'0x3635C9ADC5DEA00000']});await (fork.client as any).request({method:'anvil_setBalance',params:[source,'0x3635C9ADC5DEA00000']});await (fork.client as any).request({method:'anvil_impersonateAccount',params:[source]});const sourceWallet=createWalletClient({account:source,chain:forkChain,transport:http(fork.url)}),funding=robinhoodMainnet.assets.USDG,target=robinhoodMainnet.assets.WETH,cap=5_000_000n;const sourceBalance=await fork.client.readContract({address:funding,abi:erc20WriteAbi,functionName:'balanceOf',args:[source]});assert(sourceBalance>=cap,`fork funding source has only ${sourceBalance} raw USDG`);const fundingHash=await sourceWallet.writeContract({address:funding,abi:erc20WriteAbi,functionName:'transfer',args:[operator.address,cap]});await fork.client.waitForTransactionReceipt({hash:fundingHash});await (fork.client as any).request({method:'anvil_stopImpersonatingAccount',params:[source]});const before={target:await fork.client.readContract({address:target,abi:erc20WriteAbi,functionName:'balanceOf',args:[operator.address]}),funding:await fork.client.readContract({address:funding,abi:erc20WriteAbi,functionName:'balanceOf',args:[operator.address]})};assert(before.target===0n&&before.funding===cap,'operator funding/zero-target preparation failed');
 const erc20Before=await fork.client.readContract({address:funding,abi:erc20WriteAbi,functionName:'allowance',args:[operator.address,V4_ROBINHOOD_DEPLOYMENTS.permit2]});let erc20ApprovalHash:Hash|undefined;if(erc20Before<cap){erc20ApprovalHash=await wallet.writeContract({address:funding,abi:erc20WriteAbi,functionName:'approve',args:[V4_ROBINHOOD_DEPLOYMENTS.permit2,cap]});assert((await fork.client.waitForTransactionReceipt({hash:erc20ApprovalHash})).status==='success','ERC20_TO_PERMIT2 approval reverted');}const erc20After=await fork.client.readContract({address:funding,abi:erc20WriteAbi,functionName:'allowance',args:[operator.address,V4_ROBINHOOD_DEPLOYMENTS.permit2]});assert(erc20After===cap,'ERC20_TO_PERMIT2 approval was not exact');
 const permitBefore=await permit2Allowance(rpc,operator.address,funding,V4_ROBINHOOD_DEPLOYMENTS.positionManager),block=await fork.client.getBlock(),expiration=block.timestamp+3600n;let permit2ApprovalHash:Hash|undefined;if(permitBefore[0]<cap||BigInt(permitBefore[1])<=block.timestamp){permit2ApprovalHash=await wallet.writeContract({address:V4_ROBINHOOD_DEPLOYMENTS.permit2,abi:permit2ApproveAbi,functionName:'approve',args:[funding,V4_ROBINHOOD_DEPLOYMENTS.positionManager,cap,Number(expiration)]});assert((await fork.client.waitForTransactionReceipt({hash:permit2ApprovalHash})).status==='success','PERMIT2_TO_POSITION_MANAGER approval reverted');}const permitAfter=await permit2Allowance(rpc,operator.address,funding,V4_ROBINHOOD_DEPLOYMENTS.positionManager);assert(permitAfter[0]===cap&&BigInt(permitAfter[1])===expiration&&permitAfter[2]===permitBefore[2],'Permit2 amount/expiration/nonce verification failed');
 const refreshed=await inspectV4Pool(rpc,pool.key);assert(refreshed.status==='available','post-approval StateView refresh failed');const deadline=(await fork.client.getBlock()).timestamp+600n,plan=buildStrictToken1Plan(refreshed.value,cap,operator.address,deadline,10);assert(plan.amount0Max===0n&&plan.amount0Expected===0n&&plan.amount1Expected>0n&&plan.amount1Max<=cap,'strict USDG-only plan failed');const nextBefore=await fork.client.readContract({address:V4_ROBINHOOD_DEPLOYMENTS.positionManager,abi:positionManagerAbi,functionName:'nextTokenId'});let gas:bigint;try{gas=await fork.client.estimateGas({account:operator.address,to:V4_ROBINHOOD_DEPLOYMENTS.positionManager,data:plan.calldata,value:0n});}catch(error){const message=error instanceof Error?error.message:String(error);throw new Error(`modifyLiquidities simulation failed; selector=${message.match(/0x[0-9a-fA-F]{8}/)?.[0]??'unknown'} actions=${plan.actions} calldataHash=${plan.calldataHash} pool=${plan.key.currency0}/${plan.key.currency1}/${plan.key.fee}/${plan.key.tickSpacing}/${plan.key.hooks} ticks=${plan.tickLower}:${plan.tickUpper} liquidity=${plan.liquidity} caps=${plan.amount0Max}:${plan.amount1Max} permit2=${permitAfter.join(':')} error=${message}`);}
 const mintHash=await wallet.sendTransaction({to:V4_ROBINHOOD_DEPLOYMENTS.positionManager,data:plan.calldata,value:0n,gas:gas*12n/10n}),receipt=await fork.client.waitForTransactionReceipt({hash:mintHash});assert(receipt.status==='success','modifyLiquidities receipt reverted');let tokenId:bigint|undefined;for(const log of receipt.logs)try{const event=decodeEventLog({abi:positionManagerAbi,data:log.data,topics:log.topics});if(event.eventName==='Transfer'&&event.args.from==='0x0000000000000000000000000000000000000000'&&event.args.to.toLowerCase()===operator.address.toLowerCase())tokenId=event.args.id;}catch{}assert(tokenId===nextBefore,'minted token ID did not match nextTokenId/Transfer');const first=await inspectV4Position(rpc,tokenId),second=await inspectV4Position(rpc,tokenId);assert(json(first)===json(second),'position inspection is not idempotent');assert(first.owner.toLowerCase()===operator.address.toLowerCase()&&first.liquidity>0n&&first.tickLower===plan.tickLower&&first.tickUpper===plan.tickUpper,'position owner/liquidity/range mismatch');const after={target:await fork.client.readContract({address:target,abi:erc20WriteAbi,functionName:'balanceOf',args:[operator.address]}),funding:await fork.client.readContract({address:funding,abi:erc20WriteAbi,functionName:'balanceOf',args:[operator.address]})},targetSpent=before.target-after.target,fundingSpent=before.funding-after.funding;assert(targetSpent===0n&&fundingSpent>0n&&fundingSpent<=cap,'wallet transfer proof failed');artifact.ok=true;artifact.pool=pool;artifact.approvals={fundingHash,erc20ApprovalHash,permit2ApprovalHash,erc20Before,erc20After,permitBefore,permitAfter,expiration,status:'READY_TO_MINT'};artifact.plan={currentTick:plan.currentTick,sqrtPriceX96:plan.sqrtPriceX96,tickLower:plan.tickLower,tickUpper:plan.tickUpper,liquidity:plan.liquidity,amount0Expected:plan.amount0Expected,amount1Expected:plan.amount1Expected,amount0Max:plan.amount0Max,amount1Max:plan.amount1Max,actions:plan.actions,calldataHash:plan.calldataHash};artifact.mint={hash:mintHash,tokenId,gasUsed:receipt.gasUsed};artifact.transfers={targetSpent,fundingSpent};artifact.inspections={first,second,idempotent:true};writeFileSync(artifactPath,json(artifact));return artifact;}catch(error){artifact.error=error instanceof Error?error.stack??error.message:String(error);writeFileSync(artifactPath,json(artifact));throw new Error(`${artifact.error}\nartifact: ${artifactPath}`);}finally{await fork.stop();}}
