import { createHash } from 'node:crypto';
import { existsSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { createWalletClient, http, parseEther, type Address, type Hash, type Transport } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { FallbackRpc, positionManagerAbi as v3PositionManagerAbi, robinhoodMainnet } from '@robin/core';
import { migrateSqlite, oneSidedMarkToMarket, SqliteLedgerRepository } from '@robin/ledger';
import { auditRobinhoodV4Deployments, buildStrictToken1Plan, buildV4ExactInputSingle, buildV4SingleSidedDownsidePlan, discoverV4Pools, inspectV4Pool, inspectV4PositionState, parseV4MintTokenId, permit2Allowance, permit2ApproveAbi, positionManagerAbi, V4_ROBINHOOD_DEPLOYMENTS } from '@robin/v4';
import { executeV4Lifecycle, recoverV4Lifecycle, V4ReceiptWaitInterrupted, type V4LifecycleAction, type V4LifecycleInput } from './v4-lifecycle.js';
import { confirmV4TelegramManagement, prepareV4TelegramManagement } from './v4-telegram-management.js';
import { executeV4LiveCanaryClose, executeV4LiveCanaryOpen } from './v4-live-canary.js';
import { startPinnedFork } from './fork-fixture.js';
import { dedicatedWallet, runtimeEnv, runtimePaths, runtimeRpc } from './runtime.js';
import { parseV4CustomRange, parseV4RangeChoice, v4RangeButtons } from '../../telegram-lp-bot/src/v4-range-ux.js';

const chain={id:4663,name:'Robinhood Fork',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:{default:{http:['http://127.0.0.1']}}} as const;
const erc20=[{type:'function',name:'approve',stateMutability:'nonpayable',inputs:[{type:'address'},{type:'uint256'}],outputs:[{type:'bool'}]},{type:'function',name:'transfer',stateMutability:'nonpayable',inputs:[{type:'address'},{type:'uint256'}],outputs:[{type:'bool'}]},{type:'function',name:'allowance',stateMutability:'view',inputs:[{type:'address'},{type:'address'}],outputs:[{type:'uint256'}]},{type:'function',name:'balanceOf',stateMutability:'view',inputs:[{type:'address'}],outputs:[{type:'uint256'}]}] as const;
const wethAbi=[...erc20,{type:'function',name:'deposit',stateMutability:'payable',inputs:[],outputs:[]}] as const;
const assert:(x:unknown,m:string)=>asserts x=(x,m)=>{if(!x)throw new Error(`ASSERTION_FAILED: ${m}`);};
const json=(x:unknown)=>JSON.stringify(x,(_,v)=>typeof v==='bigint'?v.toString():v,2);
const WRITE=new Set(['eth_sendTransaction','eth_sendRawTransaction']);
const loopback=(url:string)=>{const h=new URL(url).hostname;return h==='127.0.0.1'||h==='localhost'||h==='::1'||h==='[::1]';};
function guardWrite(url:string,method:string){if(WRITE.has(method)&&!loopback(url))throw new Error(`NON_LOCAL_RPC_WRITE_BLOCKED:${method}`);}
function guardedHttp(url:string,writes:Array<{method:string;url:string}>):Transport{const base=http(url);return ((options:any)=>{const transport=base(options);return {...transport,request:async(req:any)=>{guardWrite(url,req.method);if(WRITE.has(req.method))writes.push({method:req.method,url});return transport.request(req);}};}) as Transport;}
function fileProof(path:string){if(!existsSync(path))return {exists:false};const s=statSync(path);return {exists:true,sha256:createHash('sha256').update(readFileSync(path)).digest('hex'),mtimeMs:s.mtimeMs,size:s.size};}
async function productionProof(wallet:Address|undefined){const v3=await runtimeRpc.withClient(c=>Promise.all([c.readContract({address:'0x73991a25C818Bf1f1128dEAaB1492D45638DE0D3',abi:v3PositionManagerAbi,functionName:'ownerOf',args:[333525n]}),c.readContract({address:'0x73991a25C818Bf1f1128dEAaB1492D45638DE0D3',abi:v3PositionManagerAbi,functionName:'positions',args:[333525n]})])).catch(()=>null);const allowances=wallet?await Promise.all([runtimeRpc.withClient(c=>c.readContract({address:robinhoodMainnet.assets.WETH,abi:erc20,functionName:'allowance',args:[wallet,V4_ROBINHOOD_DEPLOYMENTS.permit2]})),runtimeRpc.withClient(c=>c.readContract({address:robinhoodMainnet.assets.USDG,abi:erc20,functionName:'allowance',args:[wallet,V4_ROBINHOOD_DEPLOYMENTS.permit2]})),permit2Allowance(runtimeRpc,wallet,robinhoodMainnet.assets.WETH,V4_ROBINHOOD_DEPLOYMENTS.positionManager),permit2Allowance(runtimeRpc,wallet,robinhoodMainnet.assets.USDG,V4_ROBINHOOD_DEPLOYMENTS.positionManager)]).catch(()=>null):null;return {nonce:wallet?await runtimeRpc.withClient(c=>c.getTransactionCount({address:wallet,blockTag:'pending'})):null,database:fileProof(runtimePaths.databasePath),flags:{EXECUTION_ENABLED:runtimeEnv.EXECUTION_ENABLED,DRY_RUN:runtimeEnv.DRY_RUN,EMERGENCY_PAUSE:runtimeEnv.EMERGENCY_PAUSE,LIVE_CANARY_ENABLED:runtimeEnv.LIVE_CANARY_ENABLED,V4_LIVE_CANARY_ENABLED:runtimeEnv.V4_LIVE_CANARY_ENABLED},v3Position:v3,allowances};}

export async function runV4LifecycleE2E(){
 const fork=await startPinnedFork(),artifactPath=join(fork.dir,'v4-lifecycle-e2e.json'),artifact:any={artifactPath,localRpcUrl:fork.url,mainnetTransactionsSent:0},writes:Array<{method:string;url:string}>=[];
 let publicWriteGuard=false;try{guardWrite('https://robinhoodchain-mainnet.example','eth_sendRawTransaction');}catch(error){publicWriteGuard=String(error).includes('NON_LOCAL_RPC_WRITE_BLOCKED');}assert(publicWriteGuard,'public RPC write guard did not fail closed');
 const productionWallet=dedicatedWallet().address,productionBefore=await productionProof(productionWallet);
 try{
  const rpc=new FallbackRpc({...robinhoodMainnet,rpcUrls:[fork.url]}),audit=await auditRobinhoodV4Deployments(rpc);assert(audit.status==='available','v4 deployment unavailable');
  const found=await discoverV4Pools(rpc,robinhoodMainnet.assets.WETH),pool=found.status==='available'?found.value.find(p=>p.id==='0xfcfae8fa0bd6da961bcf5d990f27690932deac4f093e99bf3e871691c6586593'):undefined;assert(pool&&pool.liquidity>0n,'active WETH/USDG pool missing');const rangeButtons=v4RangeButtons('fork-selection'),rangeProof=[10,30,50,60].map(value=>{const range=parseV4RangeChoice(String(value));assert(range!=='custom','preset parsed as custom');const plan=buildV4SingleSidedDownsidePlan(pool,5_000_000n,'0x70997970C51812dc3A010C7d01b50e0d17dc79C8',(BigInt(Date.now())/1000n)+600n,range);assert(plan.amount0Expected===0n&&plan.amount1Expected>0n&&plan.currentTick>=plan.tickUpper,'Telegram preset lost funding-only invariant');return {value,range,ticks:[plan.tickLower,plan.tickUpper],calldataHash:plan.calldataHash};}),customRange=parseV4CustomRange('30,60'),customPlan=buildV4SingleSidedDownsidePlan(pool,5_000_000n,'0x70997970C51812dc3A010C7d01b50e0d17dc79C8',(BigInt(Date.now())/1000n)+600n,customRange);let invalidCustomRejected=false;try{parseV4CustomRange('60,30');}catch{invalidCustomRejected=true;}assert(invalidCustomRejected&&customPlan.amount0Expected===0n,'Telegram custom range proof failed');
  const operator=privateKeyToAccount('0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d'),trader=privateKeyToAccount('0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cda8d0cc'),operatorWallet=createWalletClient({account:operator,chain,transport:guardedHttp(fork.url,writes)}),traderWallet=createWalletClient({account:trader,chain,transport:guardedHttp(fork.url,writes)});
  for(const account of [operator,trader])await (fork.client as any).request({method:'anvil_setBalance',params:[account.address,'0x3635C9ADC5DEA00000']});
  const target=robinhoodMainnet.assets.WETH,funding=robinhoodMainnet.assets.USDG,cap=5_000_000n,source='0x52e65B17fB6E5BA00Ed806f37Afcd2DaA50271Ca' as Address;
  await (fork.client as any).request({method:'anvil_setBalance',params:[source,'0x3635C9ADC5DEA00000']});await (fork.client as any).request({method:'anvil_impersonateAccount',params:[source]});const sourceWallet=createWalletClient({account:source,chain,transport:guardedHttp(fork.url,writes)}),fundHash=await sourceWallet.writeContract({address:funding,abi:erc20,functionName:'transfer',args:[operator.address,cap]});await fork.client.waitForTransactionReceipt({hash:fundHash});await (fork.client as any).request({method:'anvil_stopImpersonatingAccount',params:[source]});
  assert(await fork.client.readContract({address:target,abi:erc20,functionName:'balanceOf',args:[operator.address]})===0n,'operator WETH not zero');
  const dbPath=join(fork.dir,'v4-lifecycle.sqlite');migrateSqlite(dbPath,'infra/migrations');const repo=new SqliteLedgerRepository(dbPath),before0=await fork.client.readContract({address:target,abi:erc20,functionName:'balanceOf',args:[operator.address]}),before1=await fork.client.readContract({address:funding,abi:erc20,functionName:'balanceOf',args:[operator.address]}),progress:string[]=[];
  const open=await executeV4LiveCanaryOpen({repo,rpc,walletClient:operatorWallet,wallet:operator.address,runtime:{executionEnabled:true,dryRun:false,emergencyPause:false,v4LiveCanaryEnabled:true,signerConfigured:true,allowlisted:true},idempotencyKey:'telegram-v4-open:e2e',userId:'operator',chatId:'local-anvil',limits:{maxTxGasUsd:.25,totalGasUsd:1,nativeUsd:1},allowLocalTest:true,notify:state=>{progress.push(state);}});assert(open.status==='POSITION_RECONCILED','production v4 live open executor failed');const tokenId=BigInt(open.tokenId),mintHash=open.mintHash as Hash,mintReceipt=await fork.client.getTransactionReceipt({hash:mintHash}),mintState=await inspectV4PositionState(rpc,tokenId),after0=await fork.client.readContract({address:target,abi:erc20,functionName:'balanceOf',args:[operator.address]}),after1=await fork.client.readContract({address:funding,abi:erc20,functionName:'balanceOf',args:[operator.address]});assert(before0-after0===0n&&before1-after1>0n&&before1-after1<=cap,'single-sided mint transfer mismatch');const positionId=`v4:${tokenId}`;assert(repo.v4Position(tokenId)&&String(repo.v4LiveCanary().state)==='OPENED','production open did not enroll the NFT');const duplicateOpen=await executeV4LiveCanaryOpen({repo,rpc,walletClient:operatorWallet,wallet:operator.address,runtime:{executionEnabled:true,dryRun:false,emergencyPause:false,v4LiveCanaryEnabled:true,signerConfigured:true,allowlisted:true},idempotencyKey:'telegram-v4-open:e2e',limits:{maxTxGasUsd:.25,totalGasUsd:1,nativeUsd:1},allowLocalTest:true});assert(duplicateOpen.status==='ALREADY_COMPLETED','duplicate live open was not idempotent');
  await fork.client.waitForTransactionReceipt({hash:await traderWallet.writeContract({address:target,abi:wethAbi,functionName:'deposit',value:parseEther('20')})});const traderAmount=parseEther('12'),traderApprove=await traderWallet.writeContract({address:target,abi:erc20,functionName:'approve',args:[V4_ROBINHOOD_DEPLOYMENTS.permit2,traderAmount]});await fork.client.waitForTransactionReceipt({hash:traderApprove});const traderPermitHash=await traderWallet.writeContract({address:V4_ROBINHOOD_DEPLOYMENTS.permit2,abi:permit2ApproveAbi,functionName:'approve',args:[target,V4_ROBINHOOD_DEPLOYMENTS.universalRouter,traderAmount,Number((await fork.client.getBlock()).timestamp+3600n)]});await fork.client.waitForTransactionReceipt({hash:traderPermitHash});
  const preSwapTick=mintState.pool.tick,swap=buildV4ExactInputSingle({key:pool.key,zeroForOne:true,amountIn:traderAmount,amountOutMinimum:0n,deadline:(await fork.client.getBlock()).timestamp+600n}),swapGas=await fork.client.estimateGas({account:trader.address,to:swap.to,data:swap.data}),swapHash=await traderWallet.sendTransaction({to:swap.to,data:swap.data,gas:swapGas*12n/10n}),swapReceipt=await fork.client.waitForTransactionReceipt({hash:swapHash});assert(swapReceipt.status==='success','v4 trader swap failed');const afterSwap=await inspectV4PositionState(rpc,tokenId);assert(afterSwap.pool.tick!==preSwapTick,'v4 swap did not move tick');
  assert(afterSwap.claimableFees.status==='available'&&afterSwap.claimableFees.token0+afterSwap.claimableFees.token1>0n,'StateView claimable fee entitlement remained zero after in-range swap');
  artifact.feeEntitlementAfterSwap=afterSwap.claimableFees;
  const baseSnapshot=await (fork.client as any).request({method:'evm_snapshot',params:[]}) as string;
  const base=(action:V4LifecycleAction,key:string,percent?:25|50|75):V4LifecycleInput=>({repo,rpc,walletClient:operatorWallet,wallet:operator.address,tokenId,action,percent,slippageBps:50,deadlineSeconds:600,idempotencyKey:key});
  const telegramPreview=await prepareV4TelegramManagement({...base('collect','happy:collect'),userId:'operator',chatId:'local-anvil',messageId:'collect-1'});const collect=await confirmV4TelegramManagement({...base('collect','unused'),userId:'operator',chatId:'local-anvil',intentId:telegramPreview.intentId});assert(collect.ok&&collect.transfers.token0+collect.transfers.token1>0n,'standalone fee collect was zero');const partialPreview=await prepareV4TelegramManagement({...base('partial_close','happy:partial',50),userId:'operator',chatId:'local-anvil',messageId:'partial-1'});const partial=await confirmV4TelegramManagement({...base('partial_close','unused',50),userId:'operator',chatId:'local-anvil',intentId:partialPreview.intentId});assert(partial.ok&&partial.remainingLiquidity>0n&&partial.remainingLiquidity<mintState.liquidity,'partial close failed');const duplicatePartial=await confirmV4TelegramManagement({...base('partial_close','unused-again',50),userId:'operator',chatId:'local-anvil',intentId:partialPreview.intentId});assert(duplicatePartial.status==='ALREADY_COMPLETED','duplicate partial close was not idempotent');const firstDelta=repo.reconciliationDelta(positionId);repo.reconcileAll();const secondDelta=repo.reconciliationDelta(positionId);assert(json(firstDelta)===json(secondDelta),'second reconciliation changed ledger');const full=await executeV4LiveCanaryClose({repo,rpc,walletClient:operatorWallet,wallet:operator.address,runtime:{executionEnabled:true,dryRun:false,emergencyPause:false,v4LiveCanaryEnabled:true,signerConfigured:true,allowlisted:true},tokenId,idempotencyKey:'telegram-v4-close:e2e',limits:{maxTxGasUsd:.25,totalGasUsd:1,nativeUsd:1},allowLocalTest:true});assert(full.status==='CLOSED'&&full.close.ok&&full.burn.ok,'production full close and burn route failed');const burn=full.burn,duplicateClose=await executeV4LiveCanaryClose({repo,rpc,walletClient:operatorWallet,wallet:operator.address,runtime:{executionEnabled:true,dryRun:false,emergencyPause:false,v4LiveCanaryEnabled:true,signerConfigured:true,allowlisted:true},tokenId,idempotencyKey:'telegram-v4-close:e2e',limits:{maxTxGasUsd:.25,totalGasUsd:1,nativeUsd:1},allowLocalTest:true});assert(duplicateClose.status==='ALREADY_COMPLETED','duplicate live close was not rejected');let burned=false;try{await fork.client.readContract({address:V4_ROBINHOOD_DEPLOYMENTS.positionManager,abi:positionManagerAbi,functionName:'ownerOf',args:[tokenId]});}catch{burned=true;}assert(burned,'burned NFT still has owner');
  const accounting=repo.positionAccounting(positionId),finalPool=await inspectV4Pool(rpc,pool.key);assert(finalPool.status==='available','final pool unavailable');const price=Number(finalPool.value.sqrtPriceX96*finalPool.value.sqrtPriceX96)/Number(2n**192n)*1e12,pnl=oneSidedMarkToMarket(accounting,{currentLiquidity:{token0:0n,token1:0n},current:{token0Usd:price,token1Usd:1,token0Decimals:18,token1Decimals:6,blockNumber:finalPool.value.blockNumber,source:'v4 StateView WETH/USDG',confidence:'derived',observedAt:new Date().toISOString()},initialFunding:cap,fundingIndex:1,initialFundingExecutionValue:5,fundingDecimals:6,targetDecimals:18,targetPriceInFunding:price});repo.persistPnlSnapshot(`v4:final:${tokenId}`,positionId,pnl);
  const duplicateTelegram=await confirmV4TelegramManagement({...base('collect','unused-again'),userId:'operator',chatId:'local-anvil',intentId:telegramPreview.intentId});assert(duplicateTelegram.status==='ALREADY_COMPLETED','duplicate Telegram confirmation submitted again');const liveCanaryProof=repo.v4LiveCanary(),liveGasProof=repo.v4LiveGas();
  repo.close();
  // Real submitted-hash recovery: each transaction is mined locally, its wait is interrupted,
  // then a newly opened repository resolves the same hash without a second submission.
  assert(await (fork.client as any).request({method:'evm_revert',params:[baseSnapshot]}),'snapshot restore failed');
  let resetSnapshot=await (fork.client as any).request({method:'evm_snapshot',params:[]}) as string;const recoveries:Record<string,unknown>={};
  const seed=(path:string)=>{migrateSqlite(path,'infra/migrations');const r=new SqliteLedgerRepository(path);r.ensurePosition(positionId,tokenId.toString(),pool.id);r.upsertV4Position({tokenId,owner:operator.address,poolId:pool.id,poolKey:pool.key,currency0:pool.key.currency0,currency1:pool.key.currency1,fee:pool.key.fee,tickSpacing:pool.key.tickSpacing,hooks:pool.key.hooks,tickLower:mintState.tickLower,tickUpper:mintState.tickUpper,liquidity:mintState.liquidity,initialAmount0:0n,initialAmount1:cap,mintHash});r.ingestDeposit({id:`recovery:${mintHash}`,positionId,txHash:mintHash,logIndex:0,amounts:{token0:0n,token1:cap},blockNumber:mintReceipt.blockNumber,blockTimestamp:new Date().toISOString()});return r;};
  for(const scenario of [{name:'collect',action:'collect' as const},{name:'partial',action:'partial_close' as const,percent:50 as const},{name:'full',action:'full_close' as const}]){const recoveryDb=join(fork.dir,`v4-recovery-${scenario.name}.sqlite`);let recoveryRepo=seed(recoveryDb);const interruptedInput={...base(scenario.action,`recovery:${scenario.name}`,scenario.percent),repo:recoveryRepo,hooks:{beforeReceiptWait:()=>{throw new V4ReceiptWaitInterrupted();}}},interrupted=await executeV4Lifecycle(interruptedInput);assert(interrupted.status==='RECOVERY_REQUIRED'&&interrupted.hash,`${scenario.name} timeout hash not persisted`);recoveryRepo.close();recoveryRepo=new SqliteLedgerRepository(recoveryDb);const recovered=await recoverV4Lifecycle({...interruptedInput,repo:recoveryRepo,hooks:undefined});assert(recovered.ok&&recoveryRepo.v4LifecycleReceipt(interrupted.hash),`${scenario.name} restart recovery failed`);recoveries[scenario.name]={interrupted,recovered,history:recoveryRepo.v4LifecycleHistory(tokenId)};recoveryRepo.close();assert(await (fork.client as any).request({method:'evm_revert',params:[resetSnapshot]}),`${scenario.name} reset failed`);resetSnapshot=await (fork.client as any).request({method:'evm_snapshot',params:[]}) as string;}
  const burnDb=join(fork.dir,'v4-recovery-burn.sqlite');let burnRepo=seed(burnDb);const burnBase=(action:V4LifecycleAction,key:string):V4LifecycleInput=>({...base(action,key),repo:burnRepo}),burnClose=await executeV4Lifecycle(burnBase('full_close','recovery:burn:close'));assert(burnClose.ok&&burnClose.remainingLiquidity===0n,'burn recovery setup close failed');const burnInterruptedInput={...burnBase('burn','recovery:burn'),hooks:{beforeReceiptWait:()=>{throw new V4ReceiptWaitInterrupted();}}},burnInterrupted=await executeV4Lifecycle(burnInterruptedInput);assert(burnInterrupted.status==='RECOVERY_REQUIRED'&&burnInterrupted.hash,'burn timeout hash missing');burnRepo.close();burnRepo=new SqliteLedgerRepository(burnDb);const burnRecovered=await recoverV4Lifecycle({...burnInterruptedInput,repo:burnRepo,hooks:undefined});assert(burnRecovered.ok&&burnRepo.v4LifecycleReceipt(burnInterrupted.hash),'burn restart recovery failed');recoveries.burn={interrupted:burnInterrupted,recovered:burnRecovered,history:burnRepo.v4LifecycleHistory(tokenId)};burnRepo.close();
  const productionAfter=await productionProof(productionWallet);assert(json(productionBefore)===json(productionAfter),'production state changed');assert(writes.length>0&&writes.every(w=>loopback(w.url)),'non-loopback write observed');
  Object.assign(artifact,{ok:true,dbPath,pool,tokenId,mint:{hash:mintHash,amount0:0n,amount1:before1-after1},openExecutor:{result:open,progress,duplicateOpen},swap:{hash:swapHash,beforeTick:preSwapTick,afterTick:afterSwap.pool.tick},telegram:{openConfirmations:1,closeConfirmations:1,managementPreview:telegramPreview,rangeButtons,rangeProof,customRange:{requested:customRange,ticks:[customPlan.tickLower,customPlan.tickUpper],calldataHash:customPlan.calldataHash},invalidCustomRejected},collect,partial,duplicatePartial,full,burn,duplicateClose,liveCanary:liveCanaryProof,gas:liveGasProof,reconciliation:{first:firstDelta,second:secondDelta,delta:0},accounting,pnl,recovery:recoveries,mainnetIsolation:{publicWriteGuard,allWritesLoopback:true,localWrites:writes.length,productionBefore,productionAfter}});writeFileSync(artifactPath,json(artifact));return artifact;
 }catch(error){artifact.error=error instanceof Error?error.stack??error.message:String(error);writeFileSync(artifactPath,json(artifact));throw new Error(`${artifact.error}\nartifact: ${artifactPath}`);}finally{await fork.stop();}
}
