import { createHash } from 'node:crypto';
import { existsSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { createWalletClient, http, parseEther, type Address, type Hash } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';
import { FallbackRpc, robinhoodMainnet } from '@robin/core';
import { migrateSqlite, SqliteLedgerRepository } from '@robin/ledger';
import { buildV4ExactInputSingle, discoverV4Pools, inspectV4PositionState, permit2ApproveAbi, positionManagerAbi, V4_ROBINHOOD_DEPLOYMENTS, v4ExecutionBlockers } from '@robin/v4';
import { startPinnedFork } from './fork-fixture.js';
import { executeV4LiveCanaryOpen } from './v4-live-canary.js';
import { authorizeRebalanceWorkflow, calculateRebalancePlan, createRebalanceWorkflow, ensureRebalanceLineage, rebalanceTransitions } from './rebalance.js';
import { executeV4Rebalance } from './v4-rebalance-executor.js';
import { buildPortfolioAudit, trustedWethUsdReference } from './portfolio.js';
import { runtimePaths } from './runtime.js';
import { confirmAdoptionBaseline, createAdoptionBaselineConfirmation, positionAdoption, setAdoptedFundingAsset, syncWalletPositions } from './position-adoption.js';

const chain={id:4663,name:'Robinhood Fork',nativeCurrency:{name:'Ether',symbol:'ETH',decimals:18},rpcUrls:{default:{http:['http://127.0.0.1']}}} as const;
const erc20=[{type:'function',name:'transfer',stateMutability:'nonpayable',inputs:[{type:'address'},{type:'uint256'}],outputs:[{type:'bool'}]},{type:'function',name:'approve',stateMutability:'nonpayable',inputs:[{type:'address'},{type:'uint256'}],outputs:[{type:'bool'}]},{type:'function',name:'balanceOf',stateMutability:'view',inputs:[{type:'address'}],outputs:[{type:'uint256'}]}] as const;
const wethAbi=[...erc20,{type:'function',name:'deposit',stateMutability:'payable',inputs:[],outputs:[]}] as const;
const assert:(value:unknown,message:string)=>asserts value=(value,message)=>{if(!value)throw new Error(`ASSERTION_FAILED:${message}`);};
const json=(value:unknown)=>JSON.stringify(value,(_,item)=>typeof item==='bigint'?item.toString():item,2);
const proof=(path:string)=>{if(!existsSync(path))return {exists:false};const stat=statSync(path);return {exists:true,size:stat.size,sha256:createHash('sha256').update(readFileSync(path)).digest('hex')};};

export async function runV4RebalanceE2E(){
 const productionBefore=proof(runtimePaths.databasePath),fork=await startPinnedFork(),artifactPath=join(fork.dir,'v4-rebalance-e2e.json'),artifact:any={artifactPath,pinnedBlock:17_400_000,mainnetTransactionsSent:0};
 try{
  await (fork.client as any).request({method:'evm_setNextBlockTimestamp',params:[Math.floor(Date.now()/1000)]});await (fork.client as any).request({method:'evm_mine',params:[]});
	  const rpc=new FallbackRpc({...robinhoodMainnet,rpcUrls:[fork.url]}),found=await discoverV4Pools(rpc,robinhoodMainnet.assets.WETH),v4Pools=found.status==='available'?found.value:[],pool=v4Pools.find(item=>item.id==='0xfcfae8fa0bd6da961bcf5d990f27690932deac4f093e99bf3e871691c6586593');assert(pool&&pool.liquidity>0n,'active WETH/USDG pool missing');
  const operator=privateKeyToAccount('0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d'),trader=privateKeyToAccount('0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cda8d0cc'),wallet=createWalletClient({account:operator,chain,transport:http(fork.url)}),traderWallet=createWalletClient({account:trader,chain,transport:http(fork.url)}),source='0x52e65B17fB6E5BA00Ed806f37Afcd2DaA50271Ca' as Address;
  for(const address of [operator.address,trader.address,source])await (fork.client as any).request({method:'anvil_setBalance',params:[address,'0x3635C9ADC5DEA00000']});
  await (fork.client as any).request({method:'anvil_impersonateAccount',params:[source]});const sourceWallet=createWalletClient({account:source,chain,transport:http(fork.url)});await fork.client.waitForTransactionReceipt({hash:await sourceWallet.writeContract({address:robinhoodMainnet.assets.USDG,abi:erc20,functionName:'transfer',args:[operator.address,50_000_000n]})});await (fork.client as any).request({method:'anvil_stopImpersonatingAccount',params:[source]});
  async function generateFees(){await fork.client.waitForTransactionReceipt({hash:await traderWallet.writeContract({address:robinhoodMainnet.assets.WETH,abi:wethAbi,functionName:'deposit',value:parseEther('4')})});const amount=parseEther('3');await fork.client.waitForTransactionReceipt({hash:await traderWallet.writeContract({address:robinhoodMainnet.assets.WETH,abi:erc20,functionName:'approve',args:[V4_ROBINHOOD_DEPLOYMENTS.permit2,amount]})});await fork.client.waitForTransactionReceipt({hash:await traderWallet.writeContract({address:V4_ROBINHOOD_DEPLOYMENTS.permit2,abi:permit2ApproveAbi,functionName:'approve',args:[robinhoodMainnet.assets.WETH,V4_ROBINHOOD_DEPLOYMENTS.universalRouter,amount,Number((await fork.client.getBlock()).timestamp+3600n)]})});const swap=buildV4ExactInputSingle({key:pool!.key,zeroForOne:true,amountIn:amount,amountOutMinimum:0n,deadline:(await fork.client.getBlock()).timestamp+600n});await fork.client.waitForTransactionReceipt({hash:await traderWallet.sendTransaction({to:swap.to,data:swap.data,gas:(await fork.client.estimateGas({account:trader.address,to:swap.to,data:swap.data}))*12n/10n})});}
  async function scenario(mode:'REBALANCE'|'REBALANCE_COMPOUND',failureStages:string[]=[]){
   const setupPath=join(fork.dir,`setup-${mode.toLowerCase()}.sqlite`);migrateSqlite(setupPath,'infra/migrations');const setupRepo=new SqliteLedgerRepository(setupPath),amount=5_000_000n,selection={poolId:pool!.id,key:pool!.key,target:robinhoodMainnet.assets.WETH,funding:robinhoodMainnet.assets.USDG,targetIndex:0 as const,fundingIndex:1 as const,amount,targetSymbol:'WETH',fundingSymbol:'USDG',targetDecimals:18,fundingDecimals:6,feeSemantics:pool!.feeSemantics,hookStatus:pool!.hookSemantics,valuationProvenance:{source:'pinned-fork on-chain pool'},selectionId:`fork-${mode}`},open=await executeV4LiveCanaryOpen({repo:setupRepo,rpc,walletClient:wallet,wallet:operator.address,runtime:{executionEnabled:true,dryRun:false,emergencyPause:false,v4LiveCanaryEnabled:true,signerConfigured:true,allowlisted:true},idempotencyKey:`fork-open-${mode}`,selection,range:{upperDropPct:0,lowerDropPct:30},limits:{maxTxGasUsd:.25,totalGasUsd:1,nativeUsd:1},allowLocalTest:true});assert(open.status==='POSITION_RECONCILED','setup mint failed');const tokenId=BigInt(open.tokenId),positionId=`v4:${tokenId}`,mintReceipt=await fork.client.getTransactionReceipt({hash:open.mintHash as Hash});setupRepo.close();
	   const dbPath=join(fork.dir,`rebalance-${mode.toLowerCase()}.sqlite`);migrateSqlite(dbPath,'infra/migrations');const repo=new SqliteLedgerRepository(dbPath);for(const candidate of v4Pools.filter(item=>item.liquidity>0n&&(item.key.currency0.toLowerCase()===robinhoodMainnet.assets.USDG.toLowerCase()||item.key.currency1.toLowerCase()===robinhoodMainnet.assets.USDG.toLowerCase()))){repo.upsertV4RegistryPool({poolId:candidate.id,currency0:candidate.key.currency0,currency1:candidate.key.currency1,initializeFeeRaw:candidate.key.fee,tickSpacing:candidate.key.tickSpacing,hooks:candidate.key.hooks,initializationBlock:candidate.blockNumber,dynamicFee:Boolean(candidate.feeSemantics?.dynamicFee),staticFeePips:candidate.feeSemantics?.staticFeePips??candidate.key.fee,hookClassification:candidate.hookSemantics?.classification??'ZERO_HOOK'});repo.refreshV4RegistryPool({poolId:candidate.id,sqrtPriceX96:candidate.sqrtPriceX96,tick:candidate.tick,liquidity:candidate.liquidity,protocolFee:candidate.protocolFee??0,lpFeePips:candidate.lpFee??candidate.key.fee,initialized:candidate.initialized,refreshBlock:candidate.blockNumber,validationStatus:v4ExecutionBlockers(candidate).length?'BLOCKED':'ELIGIBLE',blockers:v4ExecutionBlockers(candidate)});}const sync=await syncWalletPositions({repo,readRpc:rpc,logsRpc:rpc,wallet:operator.address,fromBlock:mintReceipt.blockNumber>2n?mintReceipt.blockNumber-2n:0n,windowSize:10n,maxWindows:2});assert(sync.adopted.some(item=>item.status==='AUTO_ADOPTED'&&item.tokenId===tokenId.toString()),'manual v4 NFT was not auto-adopted');let adoption=positionAdoption(repo,positionId);assert(adoption?.source==='MANUAL_EXTERNAL'&&adoption.adoption_status==='AUTO_ADOPTED','adoption provenance missing');if(!adoption.funding_provenance)setAdoptedFundingAsset(repo,{positionId,token:robinhoodMainnet.assets.USDG,symbol:'USDG',provenance:'USER_SELECTED_FUNDING'});const baseline=createAdoptionBaselineConfirmation(repo,{positionId,userId:'fork-operator',chatId:'fork',baselineUsd:5,nowMs:1_000,ttlMs:1_000});assert(confirmAdoptionBaseline(repo,{id:baseline.id,userId:'fork-operator',chatId:'fork',nowMs:1_500}).status==='CONFIRMED','adoption baseline confirmation failed');adoption=positionAdoption(repo,positionId);assert(adoption?.accounting_status==='ADOPTED_REBALANCE_READY','adopted position not rebalance ready');const price=await trustedWethUsdReference(rpc);assert(price.status==='available','WETH/USDG reference unavailable');repo.db.prepare('UPDATE position_deposits SET prices_json=? WHERE position_id=?').run(json({token0Usd:price.value,token1Usd:1,source:'pinned-fork canonical WETH/USDG',blockNumber:price.blockNumber.toString()}),positionId);
   await generateFees();const before=await inspectV4PositionState(rpc,tokenId);assert(before.claimableFees.status==='available'&&before.claimableFees.token0+before.claimableFees.token1>0n,'fees were not generated');const portfolio=await buildPortfolioAudit({rpc,repo,wallet:operator.address}),tracked=portfolio.positions.find(item=>item.positionId===positionId);assert(tracked?.accounting.externalCapitalUsd!==null&&tracked?.accounting.activePrincipalUsd!==null&&tracked?.accounting.uncollectedFeesUsd!==null,'portfolio accounting unavailable');const trackedPosition=tracked!,p0=trackedPosition.accounting.externalCapitalUsd!,plan=calculateRebalancePlan({mode,originalPrincipalUsd:p0,recoveredPrincipalUsd:trackedPosition.accounting.activePrincipalUsd!,verifiedFeesUsd:trackedPosition.accounting.uncollectedFeesUsd!,compoundCapUsd:5000,originalFundingSymbol:'USDG'}),maximumTopUpUsd=Math.min(p0,plan.requiredTopUpUsd+plan.actualReopenUsd*.005),lineage=ensureRebalanceLineage(repo,{rootPositionId:positionId,originalPrincipalUsd:p0,fundingToken:robinhoodMainnet.assets.USDG,fundingSymbol:'USDG',protocol:'v4',poolId:pool!.id}),workflow=createRebalanceWorkflow(repo,{idempotencyKey:`fork-rebalance-${mode}`,lineageId:String(lineage.id),oldPositionId:positionId,mode,downsidePct:30,preview:{plan,maximumTopUpUsd,wallet:{originalFundingUsd:45,usdgUsd:45},approval:{requestedApprovalUsd:plan.actualReopenUsd}}}),workflowId=String(workflow.id);authorizeRebalanceWorkflow(repo,{workflowId,maximumTopUpUsd,balances:{originalFundingUsd:45,usdgUsd:45}});
	   const failed:string[]=[],run=async(stage?:string)=>{let injected=false;try{return await executeV4Rebalance({repo,rpc,walletClient:wallet,wallet:operator.address,workflowId,runtime:{executionEnabled:true,dryRun:false,emergencyPause:false,authorized:true,signerConfigured:true},limits:{maxTxGasUsd:500,maxLifecycleGasUsd:2000,nativeUsd:1,compoundUsd:5000,approvalUsd:5000,slippageBps:50},allowLocalTest:true,internalRecovery:true,hooks:stage?{beforeSubmit:semantic=>{if(!injected&&semantic===stage){injected=true;throw new Error(`DELIBERATE_${stage}_FAILURE`);}}}:undefined});}catch(error){failed.push(String(error));return null;}};
   for(const stage of failureStages){await run(stage);const state=repo.db.prepare('SELECT state FROM rebalance_workflows WHERE id=?').get(workflowId) as {state:string};assert(state.state==='FAILED_RECOVERABLE',`${stage} did not leave recoverable state`);}
   const result=await run();assert(result?.status==='COMPLETED','rebalance did not complete');const duplicate=await run(),completed=repo.db.prepare('SELECT * FROM rebalance_workflows WHERE id=?').get(workflowId) as Record<string,unknown>,transactions=repo.db.prepare('SELECT semantic_stage,status,tx_hash FROM rebalance_transactions WHERE workflow_id=? ORDER BY created_at').all(workflowId),accounting=repo.db.prepare('SELECT kind,usd_value FROM rebalance_accounting_events WHERE workflow_id=? ORDER BY observed_at').all(workflowId),transitions=rebalanceTransitions(repo,workflowId),oldBurned=await fork.client.readContract({address:V4_ROBINHOOD_DEPLOYMENTS.positionManager,abi:positionManagerAbi,functionName:'ownerOf',args:[tokenId]}).then(()=>false,()=>true);assert(oldBurned,'old NFT was not burned');assert(duplicate?.status==='ALREADY_COMPLETED','duplicate callback was not idempotent');const afterPortfolio=await buildPortfolioAudit({rpc,repo,wallet:operator.address}),oldPortfolio=afterPortfolio.positions.find(item=>item.positionId===positionId),replacementPortfolio=afterPortfolio.positions.find(item=>item.positionId===String(completed.replacement_position_id));assert(oldPortfolio?.excludedFromAggregateReason==='REPLACED_BY_CHILD_POSITION'&&replacementPortfolio&&!replacementPortfolio.excludedFromAggregateReason,'portfolio replacement double-count protection failed');const portfolioProof={aggregate:afterPortfolio.aggregate,oldExcluded:oldPortfolio.excludedFromAggregateReason,replacementIncluded:replacementPortfolio.positionId};repo.close();return {mode,workflowId,oldTokenId:tokenId,replacementPositionId:completed.replacement_position_id,plan,adoption,sync,failed,resumed:failureStages.length,transactions,accounting,transitions,oldBurned,duplicate,portfolioProof};}
  const normal=await scenario('REBALANCE',['PRINCIPAL_TARGET_TO_FUNDING']),compound=await scenario('REBALANCE_COMPOUND',['REOPEN_MINT']),productionAfter=proof(runtimePaths.databasePath);Object.assign(artifact,{ok:true,poolId:pool.id,normal,compound,productionIsolation:{databaseOpenedByHarness:false,before:productionBefore,after:productionAfter,note:'hash may change while production workers write their own state'},allWritesLoopback:true});writeFileSync(artifactPath,json(artifact));return artifact;
 }catch(error){artifact.error=error instanceof Error?error.stack??error.message:String(error);writeFileSync(artifactPath,json(artifact));throw new Error(`${artifact.error}\nartifact:${artifactPath}`);}finally{await fork.stop();}
}
